### ISSUE TITLE
Master throws exception due to incorrect cookie change handler.

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/jupyterhub#1011]
**How to reproduce the issue**

Just start the service

**What you expected to happen**

jupyterhub to start

**What actually happens**

```
[I 2017-03-07 18:15:36.804 JupyterHub app:750] Loading cookie_secret from /home/stefano/simphony-remote/jupyterhub/jupyterhub_cookie_secret
[E 2017-03-07 18:15:36.805 JupyterHub app:1614]
    Traceback (most recent call last):
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/jupyterhub/app.py", line 1611, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.5/types.py", line 199, in __next__
        return next(self.__wrapped)
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/jupyterhub/app.py", line 1369, in initialize
        self.init_secrets()
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/jupyterhub/app.py", line 797, in init_secrets
        self.cookie_secret = secret
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/traitlets/traitlets.py", line 558, in __set__
        self.set(obj, value)
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/traitlets/traitlets.py", line 547, in set
        obj._notify_trait(self.name, old_value, new_value)
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/traitlets/traitlets.py", line 1049, in _notify_trait
        'type': 'change',
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/traitlets/traitlets.py", line 1083, in notify_change
        c(change)
      File "/home/stefano/simphony-remote/venv/lib/python3.5/site-packages/jupyterhub/app.py", line 425, in _cookie_secret_check
        secret = change.new
    AttributeError: 'dict' object has no attribute 'new'
```

should be change["new"].

**Share what version of JupyterHub you are using**

master

**Comment by minrk** [comment]
This is new in traitlets 4.3. `setup.py` should be expressing this dependency now, if you do `pip install .`.

**Comment by minrk** [comment]
(or more specifically: `pip install --upgrade traitlets`)

**Comment by stefanoborini** [comment]
ah! ok. Thanks!
