### ISSUE TITLE
Authentication issue while logging to Jupyterhub thru browser

### ISSUE THREAD

**Issue by uday2002** [jupyterhub/jupyterhub#1013]
Hi,

I'm facing a authentication issues while logging to Jupyterhub. Please find the log:

```
^[[31m[E 2017-03-06 13:55:18.038 JupyterHub log:100]^[[0;10m 500 POST /hub/login?next=%2Fhub%2Fhome (@::ffff:172.22.6.26) 164.07ms
^[[31m[E 2017-03-06 15:59:36.207 JupyterHub orm:382]^[[0;10m Unhandled error starting udayn's server: Expecting value: line 1 column 1 (char 0)
^[[31m[E 2017-03-06 15:59:36.220 JupyterHub web:1524]^[[0;10m Uncaught exception POST /hub/login?next=%2Fhub%2Fhome (::ffff:172.22.6.26)
    HTTPServerRequest(protocol='http', host='ashdswdev02', method='POST', uri='/hub/login?next=%2Fhub%2Fhome', version='HTTP/1.1', remote_ip='::ffff:172.22.6.26', headers={'Via': '1.1 HYD-ISA01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Language': 'en-US,en;q=0.8', 'Cache-Control': 'max-age=0', 'Host': 'ashdswdev02', 'Content-Length': '36', 'Referer': 'http://ashdswdev02/hub/login?next=%2Fhub%2Fhome', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Origin': 'http://ashdswdev02', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-For': '::ffff:172.22.6.26', 'Connection': 'close', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '80'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 72, in post
        yield self.spawn_single_user(user)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 286, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 392, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 373, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 56, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.env)
      File "/opt/anaconda3/lib/python3.5/site-packages/sudospawner/spawner.py", line 48, in do
        return json.loads(data.decode('utf8'))
      File "/opt/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/opt/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

^[[31m[E 2017-03-06 15:59:36.232 JupyterHub log:99]^[[0;10m {
      "Via": "1.1 HYD-ISA01",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept-Language": "en-US,en;q=0.8",
      "Cache-Control": "max-age=0",
      "Host": "ashdswdev02",
      "Content-Length": "36",
      "Referer": "http://ashdswdev02/hub/login?next=%2Fhub%2Fhome",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Origin": "http://ashdswdev02",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-For": "::ffff:172.22.6.26",
      "Connection": "close",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80"
```

Any help. Please let me know.

Thanks

**Comment by minrk** [comment]
The failure is in sudospawner. This is typically a permission and/or PATH issue. What version of sudospawner do you have? What are the permissions on `which sudospawner`?

**Comment by uday2002** [comment]
Thanks Minrk, I solved the issue. I rolled back the Jupyter to the last day, It was working fine. Thanks.

Version is 0.6.0.
