### ISSUE TITLE
JupyterHub Daemon 500 internal server error on some users

### ISSUE THREAD

**Issue by ashkan-leo** [jupyterhub/jupyterhub#1017]
I have created a service in Ubuntu 16.04 to start jupyterhub. Here is the unit file:

```
[Unit]
Description=Jupyterhub
After=syslog.target network.target

[Service]
Type=simple
User=rhea
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/leo/.local/bin"
ExecStart=/usr/local/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target

```

I can successfully login and use the notebook when using my credentials. However, when other users want to login, they get ```500: Internal Server Error```.

This is part of the log file I get when I try to login as some other user:
```

[D 2017-03-10 18:38:19.945 JupyterHub log:100] 200 GET /hub/static/css/style.min.css?v=d96e0760e0c2b7356ce89635b646c350 (@::ffff:10.143.8.48) 1.59ms
[I 2017-03-10 18:38:51.045 JupyterHub log:100] 302 GET / (@::ffff:10.143.8.48) 1.70ms
[I 2017-03-10 18:38:51.049 JupyterHub log:100] 302 GET /hub (@::ffff:10.143.8.48) 0.71ms
[I 2017-03-10 18:38:51.098 JupyterHub log:100] 302 GET /hub/ (@::ffff:10.143.8.48) 1.53ms
[I 2017-03-10 18:38:51.104 JupyterHub log:100] 302 GET /login (@::ffff:10.143.8.48) 0.95ms
[I 2017-03-10 18:38:51.112 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.143.8.48) 1.97ms
[D 2017-03-10 18:38:51.125 JupyterHub log:100] 200 GET /hub/static/css/style.min.css?v=d96e0760e0c2b7356ce89635b646c350 (@::ffff:10.143.8.48) 1.38ms
[E 2017-03-10 18:38:58.618 JupyterHub user:251] Unhandled error starting ericsson's server: 'pid'
[E 2017-03-10 18:38:58.647 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:10.143.8.48)
    HTTPServerRequest(protocol='https', host='aroserver:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:10.143.8.48', headers={'Content-Length': '38', 'Origin': 'https://aroserver:8000', 'X-Forwarded-Proto': 'https', 'Accept-Language': 'en-US,en;q=0.8,fa;q=0.6', 'X-Forwarded-Host': 'aroserver:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'X-Forwarded-For': '::ffff:10.143.8.48', 'Connection': 'close', 'Referer': 'https://aroserver:8000/hub/login', 'Host': 'aroserver:8000', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, br', 'Cache-Control': 'max-age=0', 'X-Forwarded-Port': '8000', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/sudospawner/spawner.py", line 84, in start
        self.pid = reply['pid']
    KeyError: 'pid'
    
[D 2017-03-10 18:38:58.652 JupyterHub base:462] No template for 500
[E 2017-03-10 18:38:58.658 JupyterHub log:99] {
      "Content-Length": "38",
      "Origin": "https://aroserver:8000",
      "X-Forwarded-Proto": "https",
      "Accept-Language": "en-US,en;q=0.8,fa;q=0.6",
      "X-Forwarded-Host": "aroserver:8000",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "X-Forwarded-For": "::ffff:10.143.8.48",
      "Connection": "close",
      "Referer": "https://aroserver:8000/hub/login",
      "Host": "aroserver:8000",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
      "Accept-Encoding": "gzip, deflate, br",
      "Cache-Control": "max-age=0",
      "X-Forwarded-Port": "8000",
      "Content-Type": "application/x-www-form-urlencoded"
    }
```

I am using Jupyterhub version 0.7.2.

The jupyter troubleshoot output:
```
$PATH:
	/home/leo/.local/bin
	/opt/zeppelin-0.7.0-bin-all/bin
	/opt/spark/spark-2.1.0-bin-hadoop2.7/bin
	/home/leo/bin
	/home/leo/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/usr/lib/jvm/java-8-oracle/bin
	/usr/lib/jvm/java-8-oracle/db/bin
	/usr/lib/jvm/java-8-oracle/jre/bin

sys.path:
	/home/leo/.local/bin
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/home/leo/.local/lib/python3.5/site-packages
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Nov 17 2016, 17:05:23) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.8.0-41-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/home/leo/.local/bin/jupyter
	/home/leo/.local/bin/jupyter

pip list:
	alembic (0.9.1)
	appdirs (1.4.3)
	apturl (0.5.2)
	beautifulsoup4 (4.4.1)
	bleach (1.5.0)
	blinker (1.3)
	Brlapi (0.6.4)
	chardet (2.3.0)
	checkbox-support (0.22)
	colorama (0.3.7)
	command-not-found (0.3)
	cryptography (1.2.3)
	decorator (4.0.11)
	defer (1.0.6)
	entrypoints (0.2.2)
	feedparser (5.1.3)
	guacamole (0.9.2)
	html5lib (0.999)
	httplib2 (0.9.1)
	idna (2.0)
	ipykernel (4.5.2)
	ipython (5.3.0)
	ipython-genutils (0.1.0)
	ipywidgets (6.0.0)
	Jinja2 (2.8)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.0.0)
	jupyter-console (5.1.0)
	jupyter-core (4.3.0)
	jupyterhub (0.7.2)
	jupyterhub-systemdspawner (0.9.10)
	language-selector (0.1)
	louis (2.6.4)
	lxml (3.5.0)
	Mako (1.0.3)
	MarkupSafe (0.23)
	mistune (0.7.3)
	nbconvert (5.1.1)
	nbformat (4.3.0)
	notebook (4.4.1)
	oauthlib (1.0.3)
	onboard (1.2.0)
	packaging (16.8)
	padme (1.1.1)
	pamela (0.3.0)
	pandocfilters (1.4.1)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	Pillow (3.1.2)
	pip (9.0.1)
	plainbox (0.25)
	prompt-toolkit (1.0.13)
	psutil (5.2.0)
	ptyprocess (0.5.1)
	pyasn1 (0.1.9)
	pycups (1.9.73)
	pycurl (7.43.0)
	Pygments (2.2.0)
	pygobject (3.20.0)
	PyJWT (1.3.0)
	pyparsing (2.2.0)
	python-apt (1.1.0b1)
	python-dateutil (2.6.0)
	python-debian (0.1.27)
	python-editor (1.0.3)
	python-systemd (231)
	pyxdg (0.25)
	pyzmq (16.0.2)
	qtconsole (4.2.1)
	reportlab (3.3.0)
	requests (2.9.1)
	sessioninstaller (0.0.0)
	setuptools (34.3.1)
	simplegeneric (0.8.1)
	six (1.10.0)
	SQLAlchemy (1.1.6)
	ssh-import-id (5.5)
	sudospawner (0.3.0)
	system-service (0.3)
	terminado (0.6)
	testpath (0.3)
	thefuck (3.14)
	tornado (4.4.2)
	traitlets (4.3.2)
	ubuntu-drivers-common (0.0.0)
	ufw (0.35)
	unattended-upgrades (0.1)
	unity-scope-calculator (0.1)
	unity-scope-chromiumbookmarks (0.1)
	unity-scope-colourlovers (0.1)
	unity-scope-devhelp (0.1)
	unity-scope-firefoxbookmarks (0.1)
	unity-scope-gdrive (0.7)
	unity-scope-manpages (0.1)
	unity-scope-openclipart (0.1)
	unity-scope-texdoc (0.1)
	unity-scope-tomboy (0.1)
	unity-scope-virtualbox (0.1)
	unity-scope-yelp (0.1)
	unity-scope-zotero (0.1)
	urllib3 (1.13.1)
	usb-creator (0.3.0)
	wcwidth (0.1.7)
	wheel (0.29.0)
	widgetsnbextension (2.0.0)
	xdiagnose (3.8.4.1)
	xkit (0.0.0)
	XlsxWriter (0.7.3)
```

I also tried to debug the ```spawner.py``` file myself, the reply is ``` {'error': 'Exited with status: 1', 'ok': False}```.

Any help is appreciated, I have already tried other approaches for similar issues without any luck.

**Comment by laurikoobas** [comment]
Try adding a print(cmd) before line 58 at the spawner.py (https://github.com/jupyterhub/sudospawner/blob/master/sudospawner/spawner.py), see what it is trying to do.

**Comment by anujgupta82** [comment]
@ashkan-leo : Any progress ? we are facing exactly the same issue

**Comment by minrk** [comment]
Can you try with sudospawner 0.4? That may give a better error message. The most common issues with sudospawner are ensuring that permissions are configured correctly.

**Comment by ashkan-leo** [comment]
I restarted the machine and now JupyterHub is running without any issues. I don't have any idea what the problem was...

**Comment by willingc** [comment]
Glad you have it working now @ashkan-leo.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by elham9449** [comment]
Hi everyone
The same problem is occurring to me

What can I do to resolve this issue?

**Comment by TEMA237** [comment]
Hello dear genius,
I got the same problem
