### ISSUE TITLE
extra_log_handlers option prevents jupyterhub from starting 

### ISSUE THREAD

**Issue by Mou5e** [jupyterhub/jupyterhub#1022]
I set extra_log_handlers with:
```
import logging
c.JupyterHub.extra_log_handlers=[logging.handlers.TimedRotatingFileHandler('/path/to/log/test.log', when='M', interval=1)]
```
I mainly want log rotation.

This prevents JupyterHub from starting because traitlets seems to have difficulty copying the handler object:
```
[E 2017-03-14 19:05:03.579 JupyterHub app:1527]
    Traceback (most recent call last):
      File "conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1524, in launch_instance_async
        yield self.initialize(argv)
      File "conda/lib/python3.5/types.py", line 199, in __next__
        return next(self.__wrapped)
      File "conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1293, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "conda/lib/python3.5/site-packages/traitlets/config/application.py", line 603, in load_config_file
        self.update_config(new_config)
      File "conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 198, in update_config
        self._load_config(config)
      File "conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 153, in _load_config
        setattr(self, name, deepcopy(config_value))
      File "conda/lib/python3.5/copy.py", line 155, in deepcopy
        y = copier(x, memo)
      File "conda/lib/python3.5/copy.py", line 218, in _deepcopy_list
        y.append(deepcopy(a, memo))
      File "conda/lib/python3.5/copy.py", line 182, in deepcopy
        y = _reconstruct(x, rv, 1, memo)
      File "conda/lib/python3.5/copy.py", line 297, in _reconstruct
        state = deepcopy(state, memo)
      File "conda/lib/python3.5/copy.py", line 155, in deepcopy
        y = copier(x, memo)
      File "conda/lib/python3.5/copy.py", line 243, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "conda/lib/python3.5/copy.py", line 174, in deepcopy
        rv = reductor(4)
    TypeError: cannot serialize '_io.TextIOWrapper' object
```

I'm on jupyterhub 0.7.2 and traitlets 4.3.1.

**Comment by minrk** [comment]
I'd highly recommend *against* using extra_log_file, as it only captures the logs of the Hub itself, and you will lose information unless you are spawning the proxy and single-user servers separately using other systems that capture and manage logs. Capturing all output to a file and using external log managers (e.g. `logrotate` or `multilog`) tends to behave better.

**Comment by willingc** [comment]
@Mou5e We recently added information to the docs on [rotating logs](https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#how-do-i-set-up-rotating-daily-logs) which should give you additional configuration info.

I'm closing this issue as resolved.
