### ISSUE TITLE
Unhandled error in API request after installing `conda_nb`

### ISSUE THREAD

**Issue by Sentient07** [jupyterhub/jupyterhub#1024]
I had faced this error on opening launching the browser after updating the `conda_nb` package 
``` 
[E 15:45:59.652 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/neena/anaconda2/envs/ramana/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/neena/anaconda2/envs/ramana/lib/python2.7/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/home/neena/anaconda2/envs/ramana/lib/python2.7/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/home/neena/anaconda2/envs/ramana/lib/python2.7/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
[E 15:45:59.658 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.5", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/tree?token=e41a234f0105c11388f2935ab896351cce3f757368b0d288", 
      "Cookie": "_xsrf=2|28519894|6ba8b6059dc62f2f2b95dcc9bdd07a15|1489615953; username-localhost-8888=\"2|1:0|10:1489659353|23:username-localhost-8888|44:NGQwNGJkOTY0YmI4NDRjZjgzNzljYmU0NjBiODZhZWY=|3bfc8dddcedfde5e640c5ce006e1ec9fc0c16aa682443e68c5e064a843a0e23b\""
    }
```

**Comment by minrk** [comment]
This is a bug in the `nb_conda` package. I believe it will be fixed if you upgrade it:

    conda upgrade nb_conda

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!
