### ISSUE TITLE
pip3 install fail. Below is my code. Thanks!!!

### ISSUE THREAD

**Issue by lk1983823** [jupyterhub/jupyterhub#1037]
```
The directory '/home/swx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/swx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages
swx@swx-virtual-machine:~$ sudo pip3 install jupyter
The directory '/home/swx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/swx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-5.1.0-py2.py3-none-any.whl
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-6.0.0-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 365kB/s 
Collecting qtconsole (from jupyter)
  Downloading qtconsole-4.2.1-py2.py3-none-any.whl (104kB)
    100% |████████████████████████████████| 112kB 605kB/s 
Collecting notebook (from jupyter)
  Downloading notebook-4.4.1-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 6.9MB 118kB/s 
Collecting nbconvert (from jupyter)
  Downloading nbconvert-5.1.1-py2.py3-none-any.whl (372kB)
    100% |████████████████████████████████| 378kB 467kB/s 
Collecting ipykernel (from jupyter)
  Downloading ipykernel-4.5.2-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 264kB/s 
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.4/dist-packages (from jupyter-console->jupyter)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from jupyter-console->jupyter)
Requirement already satisfied: pygments in /usr/local/lib/python3.4/dist-packages (from jupyter-console->jupyter)
Requirement already satisfied: ipython in /usr/local/lib/python3.4/dist-packages (from jupyter-console->jupyter)
Collecting widgetsnbextension~=2.0.0 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-2.0.0-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 215kB/s 
Collecting nbformat>=4.2.0 (from ipywidgets->jupyter)
  Downloading nbformat-4.3.0-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 515kB/s 
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.4/dist-packages (from ipywidgets->jupyter)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.4/dist-packages (from qtconsole->jupyter)
Collecting jinja2 (from notebook->jupyter)
  Downloading Jinja2-2.9.5-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 484kB/s 
Collecting terminado>=0.3.3; sys_platform != "win32" (from notebook->jupyter)
  Downloading terminado-0.6.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'
```

**Comment by minrk** [comment]
That looks like pip has gotten itself confused. Can you try:

    pip3 install --upgrade setuptools pip

**Comment by lk1983823** [comment]
@minrk  thanks, I solved the problem, with sudo pip3 install --upgrade six， sudo apt remove python3-pyparsing，   sudo pip3 install pyparsing
