### ISSUE TITLE
SudoSpawner fails to start subprocess

### ISSUE THREAD

**Issue by dsblank** [jupyterhub/jupyterhub#111]
I believe that everything is setup as to the new sudo spawner config:
- went through checklist in wiki
- not using whitelist
- rhea can execute sudo spawner fine
- can log in
- error when bringing up dashboard
- works fine when run as root

```
# cd /etc/jupyterhub
# sudo -u rhea jupyterhub --JupyterHub.spawner=sudospawner.SudoSpawner
[I 12:15:52.083 JupyterHub] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 12:15:52.111 JupyterHub] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 12:15:52.117 JupyterHub] Not using whitelist. Any authenticated user will be allowed.
[I 12:15:52.127 JupyterHub] Starting proxy @ http://*:8000/
12:15:52.220 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
12:15:52.223 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 12:16:08.428 JupyterHub] 302 GET / (127.0.0.1) 1.13ms
[I 12:16:08.443 JupyterHub] 302 GET /hub (127.0.0.1) 0.79ms
[E 12:16:08.473 JupyterHub] Could not open static file '/usr/local/share/jupyter/static/images/favicon.ico'
[I 12:16:08.475 JupyterHub] 304 GET /hub/ (127.0.0.1) 22.78ms
[I 12:16:10.049 JupyterHub] 304 GET /hub/login (127.0.0.1) 12.52ms
[I 12:16:13.378 JupyterHub] Spawning jupyterhub-singleuser --user=dblank --port=33560 --cookie-name=jupyter-hub-token-dblank --base-url=/user/dblank --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api
[E 12:16:13.381 JupyterHub] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='jupyter.physics.brynmawr.edu:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'http://jupyter.physics.brynmawr.edu:8000/hub/login', 'Content-Length': '32', 'Cookie': 'jupyter-hub-token="2|1:0|10:1418403800|17:jupyter-hub-token|44:OTFjMDM2YTIwOWZhNDFiNTlhYjI1MWE0MGQ3NTAxMGI=|a8b6016dca567168be0377732c133f3ed894e97a3eb3fa36fbf0897f93075449"', 'X-Forwarded-Port': '8000', 'X-Forwarded-Proto': 'http', 'Accept-Language': 'en-US,en;q=0.5', 'Host': 'jupyter.physics.brynmawr.edu:8000', 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Connection': 'close', 'X-Forwarded-For': '165.106.10.85', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0', 'Accept-Encoding': 'gzip, deflate'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1334, in _execute
        result = yield result
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/login.py", line 60, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 173, in spawn_single_user
        config=self.config,
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 313, in spawn
        yield spawner.start()
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 160, in wrapper
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/spawner.py", line 324, in start
        preexec_fn=self.make_preexec_fn(self.user.name),
      File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.4/subprocess.py", line 1447, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
```

**Comment by griffinmilsap** [comment]
I'm having a similar issue, but no amount of re-installing things seems to help..  Any ideas?

```
[I 2015-02-05 23:29:12.372 JupyterHub spawner:331] Spawning jupyterhub-singleuser --user=griffin --port=35184 --cookie-name=jupyter-hub-token-griffin --base-url=/user/griffin --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api
[E 2015-02-05 23:29:12.377 JupyterHub web:1407] Uncaught exception POST /hub/login?next= (96.44.23.111)
    HTTPServerRequest(protocol='http', host='cerebro.neuro.jhu.edu', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='96.44.23.111', headers={'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Language': 'en-US,en;q=0.8', 'X-Forwarded-Proto': 'http', 'Cache-Control': 'max-age=0', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36', 'Content-Length': '39', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Connection': 'close', 'Origin': 'http://cerebro.neuro.jhu.edu', 'Referer': 'http://cerebro.neuro.jhu.edu/hub/login', 'X-Forwarded-Port': '80', 'Host': 'cerebro.neuro.jhu.edu', 'X-Forwarded-For': '96.44.23.111', 'Cookie': 'jupyter-hub-token="2|1:0|10:1423181004|17:jupyter-hub-token|44:ZDgwNjE3NDcxNDVkNDhiMTkzMmY3MGNiNzJiYWMxYTk=|f8f3280fc492a051023c9a6bbbdc3e3ebf7820f738451cfc1935a1d9c622be20"; _ga=GA1.2.468218616.1401898916; __utma=135642670.468218616.1401898916.1422902834.1422902834.1; __utmc=135642670; __utmz=135642670.1422902834.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'})
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/site-packages/tornado/web.py", line 1334, in _execute
        result = yield result
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/lib64/python3.4/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/jupyterhub/jupyterhub/handlers/login.py", line 60, in post
        yield self.spawn_single_user(user)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/lib64/python3.4/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/jupyterhub/jupyterhub/handlers/base.py", line 214, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/lib64/python3.4/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/jupyterhub/jupyterhub/orm.py", line 320, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/lib64/python3.4/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib64/python3.4/site-packages/tornado/gen.py", line 160, in wrapper
        result = func(*args, **kwargs)
      File "/usr/local/jupyterhub/jupyterhub/spawner.py", line 333, in start
        preexec_fn=self.make_preexec_fn(self.user.name),
      File "/usr/lib64/python3.4/subprocess.py", line 858, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
[E 2015-02-05 23:29:12.395 JupyterHub web:1811] 500 POST /hub/login?next= (96.44.23.111) 121.20ms
```

**Comment by minrk** [comment]
@griffinmilsap thanks! Sorry for the confusion.
