### ISSUE TITLE
Tornado exception behind corporate proxy

### ISSUE THREAD

**Issue by deisi** [jupyterhub/jupyterhub#1122]
**Short**
Its impossible to run jupyterhub behind a corperate proxy.

**How to reproduce the issue**

installed jupyterhub as a local user with:

``` bash
pip3 install --user jupyterhub
pip3 install --user --upgrade notebook
```

npm and packages were installed with sudo sytemwide.

start jupyterhub with:
 ```
sudo -E jupyterhub -f /home/malte/.jupyterhub/jupyterhub_config.py --debug
```
In the config I only defined ssl key and certificate:

``` python
#  Use with ssl_key
c.JupyterHub.ssl_cert = '/home/malte/.jupyterhub/cert.pem'

## Path to SSL key file for the public facing interface of the proxy
#  
#  Use with ssl_cert
c.JupyterHub.ssl_key = '/home/malte/.jupyterhub/key.pem'

```

**What actually happens**
The server starts and I can connect with:

```
https://localhost:8000
```
I can login using PAM Credentials, but then the actual notebook server never starts and I get the following log:
https://pastebin.com/2DXGqDQE

It seems, that the start of the notebook server doesnt work.  Because of the:
```
[W 2017-05-03 12:34:16.356 JupyterHub user:278] malte's server never showed up at http://127.0.0.1:50438/user/malte after 30 seconds. Giving up
```

I'm not shure about the spamming of 
```
[W 2017-05-03 12:34:16.251 malte iostream:1327] SSL Error on 7 ('127.0.0.1', 47916): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
```
where does that come from.

**Share what version of JupyterHub you are using**
0.7.2

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/home/malte/.local/bin
	/home/malte/bin
	/home/malte/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/malte/.local/bin
	/home/malte/.local/bin

sys.path:
	/home/malte/.local/bin
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/home/malte/.local/lib/python3.5/site-packages
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Nov 17 2016, 17:05:23) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/home/malte/.local/bin/jupyter
	/home/malte/.local/bin/jupyter
	/home/malte/.local/bin/jupyter
	/home/malte/.local/bin/jupyter

pip list:
	alabaster (0.7.10)
	alembic (0.9.1)
	appdirs (1.4.3)
	apturl (0.5.2)
	argh (0.26.2)
	astroid (1.4.4)
	Babel (2.4.0)
	beautifulsoup4 (4.4.1)
	bleach (2.0.0)
	blinker (1.3)
	bqplot (0.9.0)
	Brlapi (0.6.4)
	bumpversion (0.5.3)
	chardet (2.3.0)
	checkbox-support (0.22)
	command-not-found (0.3)
	coverage (4.3.4)
	cryptography (1.2.3)
	cycler (0.10.0)
	Cython (0.25.2)
	decorator (4.0.11)
	defer (1.0.6)
	docutils (0.13.1)
	entrypoints (0.2.2)
	feedparser (5.1.3)
	flake8 (3.3.0)
	guacamole (0.9.2)
	html2text (2016.1.8)
	html5lib (0.999999999)
	httplib2 (0.9.1)
	idna (2.0)
	imagesize (0.7.1)
	ipykernel (4.6.1)
	ipython (6.0.0)
	ipython-genutils (0.2.0)
	ipywidgets (6.0.0)
	jedi (0.10.2)
	Jinja2 (2.9.6)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.0.1)
	jupyter-console (5.1.0)
	jupyter-core (4.3.0)
	jupyter-dashboards (0.7.0)
	jupyterhub (0.7.2)
	language-selector (0.1)
	lazy-object-proxy (1.2.1)
	logilab-common (1.1.0)
	louis (2.6.4)
	lxml (3.5.0)
	Mako (1.0.3)
	MarkupSafe (1.0)
	matplotlib (2.0.0)
	mccabe (0.6.1)
	mistune (0.7.4)
	nbconvert (5.1.1)
	nbformat (4.3.0)
	notebook (5.0.0)
	numpy (1.12.1)
	oauthlib (1.0.3)
	olefile (0.44)
	onboard (1.2.0)
	packaging (16.8)
	padme (1.1.1)
	pamela (0.3.0)
	pandas (0.19.2)
	pandocfilters (1.4.1)
	pathtools (0.1.2)
	pep8 (1.7.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	Pillow (4.1.0)
	pip (9.0.1)
	plainbox (0.25)
	pluggy (0.4.0)
	prompt-toolkit (1.0.14)
	ptyprocess (0.5.1)
	py (1.4.33)
	pyasn1 (0.1.9)
	pycodestyle (2.3.1)
	pycups (1.9.73)
	pycurl (7.43.0)
	PyEmail (0.0.1)
	pyflakes (1.5.0)
	Pygments (2.2.0)
	pygobject (3.20.0)
	PyJWT (1.3.0)
	pylint (1.5.2)
	pyparsing (2.2.0)
	python-apt (1.1.0b1)
	python-dateutil (2.6.0)
	python-debian (0.1.27)
	python-editor (1.0.3)
	python-systemd (231)
	pytz (2017.2)
	pyxdg (0.25)
	PyYAML (3.12)
	pyzmq (16.0.2)
	qtconsole (4.3.0)
	reportlab (3.3.0)
	requests (2.13.0)
	scipy (0.19.0)
	seaborn (0.7.1)
	sessioninstaller (0.0.0)
	setuptools (35.0.1)
	simplegeneric (0.8.1)
	six (1.10.0)
	snowballstemmer (1.2.1)
	Sphinx (1.5.5)
	SQLAlchemy (1.1.9)
	ssh-import-id (5.5)
	system-service (0.3)
	terminado (0.6)
	testpath (0.3)
	tornado (4.5.1)
	tox (2.7.0)
	traitlets (4.3.2)
	traittypes (0.0.6)
	ubuntu-drivers-common (0.0.0)
	ufw (0.35)
	unattended-upgrades (0.1)
	unity-scope-calculator (0.1)
	unity-scope-chromiumbookmarks (0.1)
	unity-scope-colourlovers (0.1)
	unity-scope-devhelp (0.1)
	unity-scope-firefoxbookmarks (0.1)
	unity-scope-gdrive (0.7)
	unity-scope-manpages (0.1)
	unity-scope-openclipart (0.1)
	unity-scope-texdoc (0.1)
	unity-scope-tomboy (0.1)
	unity-scope-virtualbox (0.1)
	unity-scope-yelp (0.1)
	unity-scope-zotero (0.1)
	unity-tweak-tool (0.0.7)
	urllib3 (1.13.1)
	usb-creator (0.3.0)
	virtualenv (15.1.0)
	watchdog (0.8.3)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	wheel (0.29.0)
	widgetsnbextension (2.0.0)
	wrapt (1.8.0)
	xdiagnose (3.8.4.1)
	xkit (0.0.0)
	XlsxWriter (0.7.3)
	xmltodict (0.10.2)

```

```
sudo -E jupyter troubleshoot
```
doesnt work.

I'm behind a company web proxy. Can that be a source of trouble here, or is it due to the way I installed jupyter and jupyterhub?

**Comment by minrk** [comment]
Do you perhaps have an HTTP_PROXY or HTTPS_PROXY env variable set? The peculiar thing is the SSL version messages indicate that it's trying to use https to connect to an http-only server. I'm not sure precisely how that would happen, but some system-wide proxy config could be the culprit.

**Comment by deisi** [comment]
Hey, jep I do have a proxy set up. Proxy is set throughout NetworkManager, env variables and /etc/environment. In all three cases I configured  HTTP_PROXY, HTTPS_PROXY and NO_PROXY


oh man I hate this proxy. It always makes trouble. Any idea how to fix it?

**Comment by deisi** [comment]
Here is the config:

```
http_proxy="http://some_ip"
https_proxy="https://some_ip:8080/"
no_proxy=localhost,127.0.0.0/8,::1,10.20.0.0/17
```

**Comment by minrk** [comment]
Hm. It looks like no_proxy is set correctly (127.0.0.0/8 should exclude 127.0.0.1). Since JupyterHub itself should only be talking to localhost (unless you are using external auth), you could unset these environment variables for the JupyterHub process and see if it helps. I get a bit confused about which code is responsible for handling these things, but it's possible that whatever's dealing with it recognizes http_proxy, but not no_proxy.

**Comment by deisi** [comment]
I unseted the env variables with:
```
unset no_proxy
unset http_proxy
unset https_proxy
```
and saw that the output of  ```env | grep proxy``` is empty.
Afterwards I started jupyterhub with `jupyterhub -f .jupyterhub/jupyterhub_config.py`
and also with `sudo -E jupyterhub -f .jupyterhub/jupyterhub_config.py`

In both cases I still get the same error. Do I also need to reset the NetworkManager proxy settings and possibly the cat /etc/environment settings?

**Comment by deisi** [comment]
Now I also tried after disabling the proxy in NetworkManager and it didn't change anything.

**Comment by deisi** [comment]
any further idea how I could deal with this?

**Comment by willingc** [comment]
Hi @deisi, If you run your configuration with JupyterHub master, what do you see?

**Comment by deisi** [comment]
Sadly I cant install the current master. When I try to install with: 
`pip3 install --user .`
I Get

```
Installing collected packages: jupyterhub
  Found existing installation: jupyterhub 0.7.2
    Uninstalling jupyterhub-0.7.2:
      Successfully uninstalled jupyterhub-0.7.2
  Running setup.py install for jupyterhub ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-e655srt9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b8orx_kh-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /home/malte/.local/lib/python3.5/site-packages/setuptools/dist.py:341: UserWarning: Normalizing '0.8.0.dev' to '0.8.0.dev0'
      normalized_version,
    running install
    running build
    running build_py
    running js
    installing build dependencies with npm
    npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
    jupyterhub-deps@0.0.0 /tmp/pip-e655srt9-build
    ├── bower@1.8.0
    ├─┬ clean-css@3.4.28
    │ ├─┬ commander@2.8.1
    │ │ └── graceful-readlink@1.0.1
    │ └─┬ source-map@0.4.4
    │   └── amdefine@1.0.1
    ├─┬ less@2.7.2
    │ ├─┬ errno@0.1.4
    │ │ └── prr@0.0.0
    │ ├── graceful-fs@4.1.11
    │ ├── image-size@0.5.5
    │ ├── mime@1.3.6
    │ ├─┬ mkdirp@0.5.1
    │ │ └── minimist@0.0.8
    │ ├─┬ promise@7.3.1
    │ │ └── asap@2.0.6
    │ ├─┬ request@2.81.0
    │ │ ├── aws-sign2@0.6.0
    │ │ ├── aws4@1.6.0
    │ │ ├── caseless@0.12.0
    │ │ ├─┬ combined-stream@1.0.5
    │ │ │ └── delayed-stream@1.0.0
    │ │ ├── extend@3.0.1
    │ │ ├── forever-agent@0.6.1
    │ │ ├─┬ form-data@2.1.4
    │ │ │ └── asynckit@0.4.0
    │ │ ├─┬ har-validator@4.2.1
    │ │ │ ├─┬ ajv@4.11.8
    │ │ │ │ ├── co@4.6.0
    │ │ │ │ └─┬ json-stable-stringify@1.0.1
    │ │ │ │   └── jsonify@0.0.0
    │ │ │ └── har-schema@1.0.5
    │ │ ├─┬ hawk@3.1.3
    │ │ │ ├── boom@2.10.1
    │ │ │ ├── cryptiles@2.0.5
    │ │ │ ├── hoek@2.16.3
    │ │ │ └── sntp@1.0.9
    │ │ ├─┬ http-signature@1.1.1
    │ │ │ ├── assert-plus@0.2.0
    │ │ │ ├─┬ jsprim@1.4.1
    │ │ │ │ ├── assert-plus@1.0.0
    │ │ │ │ ├── extsprintf@1.3.0
    │ │ │ │ ├── json-schema@0.2.3
    │ │ │ │ └─┬ verror@1.10.0
    │ │ │ │   ├── assert-plus@1.0.0
    │ │ │ │   └── core-util-is@1.0.2
    │ │ │ └─┬ sshpk@1.13.1
    │ │ │   ├── asn1@0.2.3
    │ │ │   ├── assert-plus@1.0.0
    │ │ │   ├── bcrypt-pbkdf@1.0.1
    │ │ │   ├─┬ dashdash@1.14.1
    │ │ │   │ └── assert-plus@1.0.0
    │ │ │   ├── ecc-jsbn@0.1.1
    │ │ │   ├─┬ getpass@0.1.7
    │ │ │   │ └── assert-plus@1.0.0
    │ │ │   ├── jsbn@0.1.1
    │ │ │   └── tweetnacl@0.14.5
    │ │ ├── is-typedarray@1.0.0
    │ │ ├── isstream@0.1.2
    │ │ ├── json-stringify-safe@5.0.1
    │ │ ├─┬ mime-types@2.1.16
    │ │ │ └── mime-db@1.29.0
    │ │ ├── oauth-sign@0.8.2
    │ │ ├── performance-now@0.2.0
    │ │ ├── qs@6.4.0
    │ │ ├── safe-buffer@5.1.1
    │ │ ├── stringstream@0.0.5
    │ │ ├─┬ tough-cookie@2.3.2
    │ │ │ └── punycode@1.4.1
    │ │ ├── tunnel-agent@0.6.0
    │ │ └── uuid@3.1.0
    │ └── source-map@0.5.6
    └── less-plugin-clean-css@1.5.1
    
    npm WARN jupyterhub-deps@0.0.0 license should be a valid SPDX license expression
    bower jquery#~3.2               cached https://github.com/components/jquery.git#3.2.1
    bower jquery#~3.2             validate 3.2.1 against https://github.com/components/jquery.git#~3.2
    bower font-awesome#~4.7         cached https://github.com/components/font-awesome.git#4.7.0
    bower font-awesome#~4.7       validate 4.7.0 against https://github.com/components/font-awesome.git#~4.7
    bower bootstrap#~3.3            cached https://github.com/components/bootstrap.git#3.3.7
    bower bootstrap#~3.3          validate 3.3.7 against https://github.com/components/bootstrap.git#~3.3
    bower                            retry Request to https://bower.herokuapp.com/packages/moment failed with ECONNRESET, retrying in 1.2s
    bower                            retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 1.1s
    bower                            retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 2.8s
    bower                            retry Request to https://bower.herokuapp.com/packages/moment failed with ECONNRESET, retrying in 2.8s
    bower                            retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 7.2s
    bower                            retry Request to https://bower.herokuapp.com/packages/moment failed with ECONNRESET, retrying in 7.7s
    bower                            retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 12.8s
    bower                            retry Request to https://bower.herokuapp.com/packages/moment failed with ECONNRESET, retrying in 10.9s
    bower                            retry Request to https://bower.herokuapp.com/packages/moment failed with ECONNRESET, retrying in 27.6s
    bower                            retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 26.8s
    bower moment#~2.18          ECONNRESET Request to https://bower.herokuapp.com/packages/moment failed: tunneling socket could not be established, cause=socket hang up
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-e655srt9-build/setup.py", line 314, in <module>
        main()
      File "/tmp/pip-e655srt9-build/setup.py", line 311, in main
        setup(**setup_args)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/malte/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-e655srt9-build/setup.py", line 256, in run
        self.run_command('js')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-e655srt9-build/setup.py", line 186, in run
        check_call(args, cwd=here, env=env, shell=shell)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1
    
    ----------------------------------------
  Rolling back uninstall of jupyterhub
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-e655srt9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b8orx_kh-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-e655srt9-build/

```

**Comment by willingc** [comment]
@minrk I was getting similar subprocess error with doc builds yesterday^^ Thoughts?

**Comment by deisi** [comment]
I checked that https://bower.herokuapp.com/packages/moment and https://bower.herokuapp.com/packages/requirejs are reachable and they are. Also the git repos they link to are just fine.

**Comment by deisi** [comment]
I updated to 0.8.0b1 because master doesnt install for me and the problem is still there. Not the message looks slightly different though. 

```
[I 2017-08-16 17:40:26.808 JupyterHub spawner:963] Spawning jupyterhub-singleuser --port=37328
Failed to set groups [Errno 1] Operation not permitted
[W 2017-08-16 17:40:27.767 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2017-08-16 17:40:28.794 SingleUserNotebookApp singleuser:367] Starting jupyterhub-singleuser server version 0.8.0.b1
[I 2017-08-16 17:40:28.798 JupyterHub log:122] 200 GET /hub/api (@127.0.0.1) 1.53ms
[I 2017-08-16 17:40:28.799 SingleUserNotebookApp notebookapp:1366] Serving notebooks from local directory: /home/malte
[I 2017-08-16 17:40:28.799 SingleUserNotebookApp notebookapp:1366] 0 active kernels 
[I 2017-08-16 17:40:28.800 SingleUserNotebookApp notebookapp:1366] The Jupyter Notebook is running at: https://[all ip addresses on your system]:37328/user/malte/
[I 2017-08-16 17:40:28.800 SingleUserNotebookApp notebookapp:1367] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2017-08-16 17:40:33.572 SingleUserNotebookApp iostream:1327] SSL Error on 8 ('127.0.0.1', 33624): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 2017-08-16 17:40:36.900 JupyterHub base:475] User malte is slow to become responsive (timeout=10)
[I 2017-08-16 17:40:36.901 JupyterHub log:122] 302 POST /hub/login?next= → /hub/ (@::ffff:10.20.60.29) 10520.99ms
[I 2017-08-16 17:40:36.958 JupyterHub log:122] 302 GET /hub/ → /hub/home (malte@::ffff:10.20.60.29) 3.41ms
[W 2017-08-16 17:40:36.965 SingleUserNotebookApp iostream:1327] SSL Error on 8 ('127.0.0.1', 33630): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 2017-08-16 17:40:36.965 JupyterHub user:431] malte's server never showed up at http://127.0.0.1:37328/user/malte/ after 30 seconds. Giving up
[I 2017-08-16 17:40:36.967 SingleUserNotebookApp notebookapp:1308] Shutting down kernels
[I 2017-08-16 17:40:37.019 JupyterHub log:122] 200 GET /hub/home (malte@::ffff:10.20.60.29) 9.90ms
[E 2017-08-16 17:40:37.277 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f23eba89f60> after timeout
    Traceback (most recent call last):
      File "/home/malte/.local/lib/python3.5/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/home/malte/.local/lib/python3.5/site-packages/jupyterhub/user.py", line 447, in spawn
        raise e
      File "/home/malte/.local/lib/python3.5/site-packages/jupyterhub/user.py", line 423, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/home/malte/.local/lib/python3.5/site-packages/jupyterhub/utils.py", line 178, in wait_for_http_server
        "Server at {url} didn't respond in {timeout} seconds".format(url=url, timeout=timeout)
      File "/home/malte/.local/lib/python3.5/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:37328/user/malte/ didn't respond in 30 seconds

```

**Comment by willingc** [comment]
Can you post your `jupyterhub_config.py` file?

**Comment by minrk** [comment]
The `SSL Error` lines are likely the problem. Seems like the connection is trying to do some https when the server's only listening on http. Maybe this is the proxy yet again? Or maybe the proxy is affecting the single-user env as well?

You can try adding

```python
import os
import pprint
pprint.pprint(dict(os.environ))
```

to your `jupyter_notebook_config.py`, which should trigger during the single-user server launch.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
