### ISSUE TITLE
.so on FreeBSD

### ISSUE THREAD

**Issue by lcfcefyn** [jupyterhub/jupyterhub#1123]
Hello, we had install Jupyterhub in a freebsd server and we have problems initializing a C++ kernel, cling. We install every dependencies and cling throught pkg install. Well, the trouble is that the kernel dies and tries to restart but thereś no way.

```
  File "/usr/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/clingkernel.py", line 317, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/clingkernel.py", line 103, in __init__
    mode = ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libclingJupyter.so: invalid file format
[I 2017-05-03 14:28:56.721 root restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 9fcb5195-8fd7-4a1f-84d8-e7e88680849a restarted
Traceback (most recent call last):
  File "/usr/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/clingkernel.py", line 317, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/llvm39_cern-root/share/cling/Jupyter/kernel/clingkernel.py", line 103, in __init__
    mode = ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /usr/local/lib/libclingJupyter.so: invalid file format**
[W 2017-05-03 14:28:59.783 root restarter:95] KernelRestarter: restart failed
[W 2017-05-03 14:28:59.784 root kernelmanager:54] Kernel 9fcb5195-8fd7-4a1f-84d8-e7e88680849a died, removing from map.
ERROR:root:kernel 9fcb5195-8fd7-4a1f-84d8-e7e88680849a restarted failed!
[W 2017-05-03 14:28:59.856 root handlers:508] Kernel deleted before session
[W 2017-05-03 14:28:59.857 root log:47] 410 DELETE /user/root/api/sessions/1fb07dbb-3c31-4f22-b3d7-13235729dfd6 (192.168.0.5) 3.52ms referer=http://jupyter.lc.efn.uncor.edu/user/root/notebooks/Untitled3.ipynb?kernel_name=cling
[I 2017-05-03 14:30:44.549 root handlers:179] Saving file at /Untitled3.ipynb
```

Seems to be the format of the .so file. When we open it, has this,

```bash
#!/bin/sh
# $FreeBSD$

LLVM_PREFIX=   "/usr/local/llvm39_cern-root"
LLVM_SUFFIX=   "39_cern-root"

tool=$(basename $0)
tool="${LLVM_PREFIX}/bin/${tool%${LLVM_SUFFIX}}"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}${LLVM_PREFIX}/lib
" \
    "${tool}" "${@}"
```

Well, we have no idea how to correct this. If you can help us, we will thanks a lot.

**Comment by minrk** [comment]
That's really bizarre. My guess is the cling kernel didn't install correctly. Since you used `pkg install`, that suggests to me that suggests to me that the cling FreeBSD package is not built correctly, but it could be an issue with cling itself. `libclingJupyter` should be a binary shared-library, not a shell script. It's probably best to bring this up with either the cling package or the maintainer of the FreeBSD port.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
