### ISSUE TITLE
JupyterHub is unable to load module spawner modules

### ISSUE THREAD

**Issue by kuldeepyadav** [jupyterhub/jupyterhub#1124]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**
I have using following file content in jupyter_config.py. 

```python
from dockerspawner import SystemUserSpawner

c.JupyterHub.confirm_no_ssl = True
c.JupyterHub.spawner_class = SystemUserSpawner  #tried 'dockerspawner.SystemUserSpawner' too

# The docker instances need access to the Hub, so the default loopback port doesn't work:
from IPython.utils.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]
```

JupyterHub is failing to import any of spawner class. It throw following error.

```
[E 2017-05-03 19:10:20.173 JupyterHub application:574] Exception while loading config file /home/vkenprohub/jupyterhub_config.py
    Traceback (most recent call last):
      File "/home/vkenprohub/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/vkenprohub/.local/lib/python3.5/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/vkenprohub/.local/lib/python3.5/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/vkenprohub/.local/lib/python3.5/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/home/vkenprohub/jupyterhub_config.py", line 2, in <module>
        from dockerspawner import SystemUserSpawner
    ImportError: No module named 'dockerspawner'
```

However, in a python prompt on the host machine. This import i.e. `from dockerspawner import SystemUserSpawner` works just fine.

**What you expected to happen**

**What actually happens**

**Share what version of JupyterHub you are using**
0.7.2

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
$PATH:
	/home/vkenprohub/.local/bin
	/home/vkenprohub/bin
	/home/vkenprohub/.local/bin
	/home/vkenprohub/anaconda3/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/vkenprohub/.local/bin
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/home/vkenprohub/.local/lib/python3.5/site-packages
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.2 (default, Nov 17 2016, 17:05:23) 
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-75-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
	/home/vkenprohub/.local/bin/jupyter
	/home/vkenprohub/.local/bin/jupyter
	/home/vkenprohub/anaconda3/bin/jupyter

pip list:
	alabaster (0.7.9)
	alembic (0.9.1)
	anaconda-client (1.6.0)
	anaconda-navigator (1.5)
	anaconda-project (0.4.1)
	astroid (1.4.9)
	astropy (1.3)
	Babel (2.3.4)
	backports.shutil-get-terminal-size (1.0.0)
	beautifulsoup4 (4.5.3)
	bitarray (0.8.1)
	blaze (0.10.1)
	bokeh (0.12.4)
	boto (2.45.0)
	Bottleneck (1.2.0)
	cffi (1.9.1)
	chardet (2.3.0)
	chest (0.2.3)
	click (6.7)
	cloudpickle (0.2.2)
	clyent (1.2.2)
	colorama (0.3.7)
	conda (4.3.14)
	configobj (5.0.6)
	contextlib2 (0.5.4)
	cryptography (1.7.1)
	cycler (0.10.0)
	Cython (0.25.2)
	cytoolz (0.8.2)
	dask (0.13.0)
	datashape (0.5.4)
	decorator (4.0.11)
	dill (0.2.5)
	docker (2.2.1)
	docker-py (1.10.6)
	docker-pycreds (0.2.1)
	dockerspawner (0.7.0)
	docutils (0.13.1)
	escapism (0.0.1)
	et-xmlfile (1.0.1)
	fastcache (1.0.2)
	Flask (0.12)
	Flask-Cors (3.0.2)
	gevent (1.2.1)
	greenlet (0.4.11)
	h5py (2.6.0)
	HeapDict (1.0.0)
	idna (2.2)
	imagesize (0.7.1)
	ipykernel (4.5.2)
	ipython (5.1.0)
	ipython-genutils (0.1.0)
	ipywidgets (5.2.2)
	isort (4.2.5)
	itsdangerous (0.24)
	jdcal (1.3)
	jedi (0.9.0)
	Jinja2 (2.9.4)
	jsonschema (2.5.1)
	jupyter (1.0.0)
	jupyter-client (4.4.0)
	jupyter-console (5.0.0)
	jupyter-core (4.2.1)
	jupyterhub (0.7.2)
	jupyterhub-systemdspawner (0.9.10)
	lazy-object-proxy (1.2.2)
	llvmlite (0.15.0)
	locket (0.2.0)
	lxml (3.7.2)
	Mako (1.0.6)
	MarkupSafe (0.23)
	matplotlib (2.0.0)
	mistune (0.7.3)
	mpmath (0.19)
	multipledispatch (0.4.9)
	nbconvert (4.2.0)
	nbformat (4.2.0)
	networkx (1.11)
	nltk (3.2.2)
	nose (1.3.7)
	notebook (4.3.1)
	numba (0.30.1)
	numexpr (2.6.1)
	numpy (1.11.3)
	numpydoc (0.6.0)
	odo (0.5.0)
	openpyxl (2.4.1)
	pamela (0.3.0)
	pandas (0.19.2)
	partd (0.3.7)
	pathlib2 (2.2.0)
	patsy (0.4.1)
	pep8 (1.7.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	Pillow (4.0.0)
	pip (9.0.1)
	ply (3.9)
	prompt-toolkit (1.0.9)
	psutil (5.0.1)
	ptyprocess (0.5.1)
	py (1.4.32)
	pyasn1 (0.1.9)
	pycosat (0.6.1)
	pycparser (2.17)
	pycrypto (2.6.1)
	pycurl (7.43.0)
	pyflakes (1.5.0)
	Pygments (2.1.3)
	pylint (1.6.4)
	pyOpenSSL (16.2.0)
	pyparsing (2.1.4)
	pytest (3.0.5)
	python-dateutil (2.6.0)
	python-editor (1.0.3)
	pytz (2016.10)
	PyYAML (3.12)
	pyzmq (16.0.2)
	QtAwesome (0.4.3)
	qtconsole (4.2.1)
	QtPy (1.2.1)
	redis (2.10.5)
	requests (2.12.4)
	rope-py3k (0.9.4.post1)
	scikit-image (0.12.3)
	scikit-learn (0.18.1)
	scipy (0.18.1)
	seaborn (0.7.1)
	setuptools (27.2.0)
	simplegeneric (0.8.1)
	singledispatch (3.4.0.3)
	six (1.10.0)
	snowballstemmer (1.2.1)
	sockjs-tornado (1.0.3)
	Sphinx (1.5.1)
	spyder (3.1.2)
	SQLAlchemy (1.1.5)
	statsmodels (0.6.1)
	sympy (1.0)
	tables (3.3.0)
	terminado (0.6)
	toolz (0.8.2)
	tornado (4.4.2)
	traitlets (4.3.1)
	unicodecsv (0.14.1)
	wcwidth (0.1.7)
	websocket-client (0.40.0)
	Werkzeug (0.11.15)
	wheel (0.29.0)
	widgetsnbextension (1.2.6)
	wrapt (1.10.8)
	xlrd (1.0.0)
	XlsxWriter (0.9.6)
	xlwt (1.2.0)

conda list:
	# packages in environment at /home/vkenprohub/anaconda3:
	#
	_license                  1.1                      py36_1  
	alabaster                 0.7.9                    py36_0  
	alembic                   0.9.1                     <pip>
	anaconda                  4.3.1               np111py36_0  
	anaconda-client           1.6.0                    py36_0  
	anaconda-navigator        1.5.0                    py36_0  
	anaconda-project          0.4.1                    py36_0  
	astroid                   1.4.9                    py36_0  
	astropy                   1.3                 np111py36_0  
	babel                     2.3.4                    py36_0  
	backports                 1.0                      py36_0  
	beautifulsoup4            4.5.3                    py36_0  
	bitarray                  0.8.1                    py36_0  
	blaze                     0.10.1                   py36_0  
	bokeh                     0.12.4                   py36_0  
	boto                      2.45.0                   py36_0  
	bottleneck                1.2.0               np111py36_0  
	cairo                     1.14.8                        0  
	cffi                      1.9.1                    py36_0  
	chardet                   2.3.0                    py36_0  
	chest                     0.2.3                    py36_0  
	click                     6.7                      py36_0  
	cloudpickle               0.2.2                    py36_0  
	clyent                    1.2.2                    py36_0  
	colorama                  0.3.7                    py36_0  
	conda                     4.3.14                   py36_0  
	conda-env                 2.6.0                         0  
	configobj                 5.0.6                    py36_0  
	contextlib2               0.5.4                    py36_0  
	cryptography              1.7.1                    py36_0  
	curl                      7.52.1                        0  
	cycler                    0.10.0                   py36_0  
	cython                    0.25.2                   py36_0  
	cytoolz                   0.8.2                    py36_0  
	dask                      0.13.0                   py36_0  
	datashape                 0.5.4                    py36_0  
	dbus                      1.10.10                       0  
	decorator                 4.0.11                   py36_0  
	dill                      0.2.5                    py36_0  
	docker                    2.2.1                     <pip>
	docker-py                 1.10.6                    <pip>
	docker-pycreds            0.2.1                     <pip>
	dockerspawner             0.7.0                     <pip>
	docutils                  0.13.1                   py36_0  
	entrypoints               0.2.2                    py36_0  
	escapism                  0.0.1                     <pip>
	et_xmlfile                1.0.1                    py36_0  
	expat                     2.1.0                         0  
	fastcache                 1.0.2                    py36_1  
	flask                     0.12                     py36_0  
	flask-cors                3.0.2                    py36_0  
	fontconfig                2.12.1                        2  
	freetype                  2.5.5                         2  
	get_terminal_size         1.0.0                    py36_0  
	gevent                    1.2.1                    py36_0  
	glib                      2.50.2                        1  
	greenlet                  0.4.11                   py36_0  
	gst-plugins-base          1.8.0                         0  
	gstreamer                 1.8.0                         0  
	h5py                      2.6.0               np111py36_2  
	harfbuzz                  0.9.39                        2  
	hdf5                      1.8.17                        1  
	heapdict                  1.0.0                    py36_1  
	icu                       54.1                          0  
	idna                      2.2                      py36_0  
	imagesize                 0.7.1                    py36_0  
	ipykernel                 4.5.2                    py36_0  
	ipython                   5.1.0                    py36_0  
	ipython_genutils          0.1.0                    py36_0  
	ipywidgets                5.2.2                    py36_1  
	isort                     4.2.5                    py36_0  
	itsdangerous              0.24                     py36_0  
	jbig                      2.1                           0  
	jdcal                     1.3                      py36_0  
	jedi                      0.9.0                    py36_1  
	jinja2                    2.9.4                    py36_0  
	jpeg                      9b                            0  
	jsonschema                2.5.1                    py36_0  
	jupyter                   1.0.0                    py36_3  
	jupyter_client            4.4.0                    py36_0  
	jupyter_console           5.0.0                    py36_0  
	jupyter_core              4.2.1                    py36_0  
	jupyterhub                0.7.2                     <pip>
	jupyterhub-systemdspawner 0.9.10                    <pip>
	lazy-object-proxy         1.2.2                    py36_0  
	libffi                    3.2.1                         1  
	libgcc                    4.8.5                         2  
	libgfortran               3.0.0                         1  
	libiconv                  1.14                          0  
	libpng                    1.6.27                        0  
	libsodium                 1.0.10                        0  
	libtiff                   4.0.6                         3  
	libxcb                    1.12                          1  
	libxml2                   2.9.4                         0  
	libxslt                   1.1.29                        0  
	llvmlite                  0.15.0                   py36_0  
	locket                    0.2.0                    py36_1  
	lxml                      3.7.2                    py36_0  
	Mako                      1.0.6                     <pip>
	markupsafe                0.23                     py36_2  
	matplotlib                2.0.0               np111py36_0  
	mistune                   0.7.3                    py36_0  
	mkl                       2017.0.1                      0  
	mkl-service               1.1.2                    py36_3  
	mpmath                    0.19                     py36_1  
	multipledispatch          0.4.9                    py36_0  
	nbconvert                 4.2.0                    py36_0  
	nbformat                  4.2.0                    py36_0  
	networkx                  1.11                     py36_0  
	nltk                      3.2.2                    py36_0  
	nose                      1.3.7                    py36_1  
	notebook                  4.3.1                    py36_0  
	numba                     0.30.1              np111py36_0  
	numexpr                   2.6.1               np111py36_2  
	numpy                     1.11.3                   py36_0  
	numpydoc                  0.6.0                    py36_0  
	odo                       0.5.0                    py36_1  
	openpyxl                  2.4.1                    py36_0  
	openssl                   1.0.2k                        1  
	pamela                    0.3.0                     <pip>
	pandas                    0.19.2              np111py36_1  
	partd                     0.3.7                    py36_0  
	path.py                   10.0                     py36_0  
	pathlib2                  2.2.0                    py36_0  
	patsy                     0.4.1                    py36_0  
	pcre                      8.39                          1  
	pep8                      1.7.0                    py36_0  
	pexpect                   4.2.1                    py36_0  
	pickleshare               0.7.4                    py36_0  
	pillow                    4.0.0                    py36_0  
	pip                       9.0.1                    py36_1  
	pixman                    0.34.0                        0  
	ply                       3.9                      py36_0  
	prompt_toolkit            1.0.9                    py36_0  
	psutil                    5.0.1                    py36_0  
	ptyprocess                0.5.1                    py36_0  
	py                        1.4.32                   py36_0  
	pyasn1                    0.1.9                    py36_0  
	pycosat                   0.6.1                    py36_1  
	pycparser                 2.17                     py36_0  
	pycrypto                  2.6.1                    py36_4  
	pycurl                    7.43.0                   py36_2  
	pyflakes                  1.5.0                    py36_0  
	pygments                  2.1.3                    py36_0  
	pylint                    1.6.4                    py36_1  
	pyopenssl                 16.2.0                   py36_0  
	pyparsing                 2.1.4                    py36_0  
	pyqt                      5.6.0                    py36_2  
	pytables                  3.3.0               np111py36_0  
	pytest                    3.0.5                    py36_0  
	python                    3.6.0                         0  
	python-dateutil           2.6.0                    py36_0  
	python-editor             1.0.3                     <pip>
	pytz                      2016.10                  py36_0  
	pyyaml                    3.12                     py36_0  
	pyzmq                     16.0.2                   py36_0  
	qt                        5.6.2                         3  
	qtawesome                 0.4.3                    py36_0  
	qtconsole                 4.2.1                    py36_1  
	qtpy                      1.2.1                    py36_0  
	readline                  6.2                           2  
	redis                     3.2.0                         0  
	redis-py                  2.10.5                   py36_0  
	requests                  2.12.4                   py36_0  
	rope                      0.9.4                    py36_1  
	ruamel_yaml               0.11.14                  py36_1  
	scikit-image              0.12.3              np111py36_1  
	scikit-learn              0.18.1              np111py36_1  
	scipy                     0.18.1              np111py36_1  
	seaborn                   0.7.1                    py36_0  
	setuptools                27.2.0                   py36_0  
	simplegeneric             0.8.1                    py36_1  
	singledispatch            3.4.0.3                  py36_0  
	sip                       4.18                     py36_0  
	six                       1.10.0                   py36_0  
	snowballstemmer           1.2.1                    py36_0  
	sockjs-tornado            1.0.3                    py36_0  
	sphinx                    1.5.1                    py36_0  
	spyder                    3.1.2                    py36_0  
	sqlalchemy                1.1.5                    py36_0  
	sqlite                    3.13.0                        0  
	statsmodels               0.6.1               np111py36_1  
	sympy                     1.0                      py36_0  
	terminado                 0.6                      py36_0  
	tk                        8.5.18                        0  
	toolz                     0.8.2                    py36_0  
	tornado                   4.4.2                    py36_0  
	traitlets                 4.3.1                    py36_0  
	unicodecsv                0.14.1                   py36_0  
	wcwidth                   0.1.7                    py36_0  
	websocket-client          0.40.0                    <pip>
	werkzeug                  0.11.15                  py36_0  
	wheel                     0.29.0                   py36_0  
	widgetsnbextension        1.2.6                    py36_0  
	wrapt                     1.10.8                   py36_0  
	xlrd                      1.0.0                    py36_0  
	xlsxwriter                0.9.6                    py36_0  
	xlwt                      1.2.0                    py36_0  
	xz                        5.2.2                         1  
	yaml                      0.1.6                         0  
	zeromq                    4.1.5                         0  
	zlib                      1.2.8                         3



```

**Comment by minrk** [comment]
My guess is that you have multiple Pythons installed (I see anaconda3 and a system-wide Python), and packages only installed in one and not the other. You can check with:

    head -n1 $(which jupyterhub)

which will show you the Python JupyterHub is using, e.g. `#!/usr/bin/python3`. Using that Python, you can run `/path/to/python -m pip list` and `/path/to/python -c 'import dockerspawner'` to verify that everything is installed for the right environment.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by nitinaggarwal1986** [comment]
I got this error for the jupyterhub-systemdspawner and jupyterhub-nativeauthenticator modules. I think I also have the issue of double python installation (mentioned by @minrk above) which happened because of nbgrader installation.  

What I did to solve this is to run pip install for these two packages again. I think this made the duplicates of these packages for the other python. Please let me know if I am wrong.
