### ISSUE TITLE
JupyterHub's sudospawner is flooding logs every 30 seconds for every user

### ISSUE THREAD

**Issue by dcervenkov** [jupyterhub/jupyterhub#1128]
JupyterHub's sudospawner is flooding logs every 30 seconds for every user. I'm trying to understand why and if this is expected behavior. Other than this, JupyterHub is running fine, without any problems.

The log entries in question are 
```
May 05 15:01:33 fooserver sudo[2346]: jupyterhub : TTY=unknown ; PWD=/etc/jupyterhub ; USER=bar ; COMMAND=/usr/local/bin/sudospawner
May 05 15:01:33 fooserver sudo[2346]: pam_unix(sudo:session): session opened for user bar by (uid=0)
May 05 15:01:33 fooserver sudo[2346]: pam_unix(sudo:session): session closed for user bar
```
Every user seems to have his own timer, but it happens every 30 seconds for each logged user (or maybe user with open notebooks). 

I understand this is related to the sudospawner command being run as root (without password) thanks to the `/etc/sudoers.d/jupyterhub` file. What I don't understand is why it runs so often and not just when it spawns single-user servers.

**How to reproduce the issue**
Run JupyterHub with sudospawner and open a notebook.

**What you expected to happen**
sudospawner runs once per spawning of single-user server.

**What actually happens**
sudospawner runs every 30 seconds per user.

**Share what version of JupyterHub you are using**
JupyterHub 0.6.1

**Output of `jupyter troubleshoot`**
```
$PATH:
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /usr/local/bin
        /usr/lib/python3.4
        /usr/lib/python3.4/plat-x86_64-linux-gnu
        /usr/lib/python3.4/lib-dynload
        /usr/local/lib/python3.4/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.4.2 (default, Oct  8 2014, 10:45:20) 
        [GCC 4.9.1]

platform.platform():
        Linux-3.16.5.1-x86_64-with-debian-8.7

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        argparse (1.2.1)
        backports-abc (0.4)
        backports.shutil-get-terminal-size (1.0.0)
        backports.ssl-match-hostname (3.5.0.1)
        certifi (2016.2.28)
        cffi (0.8.6)
        chardet (2.3.0)
        colorama (0.3.2)
        cryptography (0.6.1)
        cycler (0.10.0)
        dblatex (0.3.5.post2)
        decorator (4.0.10)
        defusedxml (0.4.1)
        dnspython (1.12.0)
        docutils (0.12)
        gyp (0.1)
        html5lib (0.999)
        ipykernel (4.3.1)
        ipython (4.2.0)
        ipython-genutils (0.1.0)
        jupyter-client (4.3.0)
        jupyter-core (4.1.0)
        lhapdf (5.9.1)
        matplotlib (1.5.1)
        meld (3.12.1)
        mercurial (3.1.2)
        ndg-httpsclient (0.3.2)
        numpy (1.8.2)
        PAM (0.4.2)
        pandas (0.18.1)
        pathlib2 (2.1.0)
        patsy (0.4.1)
        pexpect (4.1.0)
        pickleshare (0.7.2)
        Pillow (2.6.1)
        pip (1.5.6)
        ply (3.4)
        ptyprocess (0.5.1)
        pyasn1 (0.1.7)
        pychecker (0.8.19)
        pycparser (2.10)
        pycrypto (2.6.1)
        Pygments (2.0.1)
        pygobject (3.14.0)
        Pymacs (0.25)
        pyOpenSSL (0.14)
        pyparsing (2.1.5)
        python-apt (0.9.3.12)
        python-dateutil (2.5.3)
        python-debian (0.1.27)
        python-debianbts (1.11)
        pytz (2016.4)
        pyzmq (15.2.0)
        reportbug (6.6.3)
        requests (2.4.3)
        roman (2.0.0)
        root-numpy (4.5.1)
        root-pandas (0.1.1)
        rootpy (0.8.2)
        scikit-learn (0.17.1)
        scipy (0.17.1)
        seaborn (0.7.1)
        setuptools (23.0.0)
        simplegeneric (0.8.1)
        singledispatch (3.4.0.3)
        six (1.8.0)
        SOAPpy (0.12.22)
        statsmodels (0.6.1)
        tornado (4.3)
        traitlets (4.2.1)
        urllib3 (1.9.1)
        wheel (0.24.0)
        wsgiref (0.1.2)
        wstools (0.4.3)

```

**Comment by willingc** [comment]
Hi @dcervenkov,

I'm glad you have things working. I notice that you are running JupyterHub v0.6.1. The current stable release is [0.7.2](https://github.com/jupyterhub/jupyterhub/releases/tag/0.7.2). I would recommend upgrading to that release and letting us know if that does or does not resolve the logging. Thanks.

**Comment by willingc** [comment]
You may wish to check that you are using the current sudospawner release as well. The current release is [0.4.0](https://github.com/jupyterhub/sudospawner/releases/tag/0.4.0).

**Comment by dcervenkov** [comment]
Hi @willingc,

thanks for the speedy reaction. The sudospawner was also outdated (0.3.0). I upgraded both jupyterhub and sudospawner via pip. Unfortunately, now launching of jupyterhub fails. Relevant log part follows
```
May 05 18:35:17 fooserver systemd[1]: Starting Jupyterhub...
May 05 18:35:17 fooserver systemd[1]: Started Jupyterhub.
May 05 18:35:18 fooserver jupyterhub[3069]: [I 2017-05-05 18:35:18.380 JupyterHub app:724] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
May 05 18:35:18 fooserver jupyterhub[3069]: [W 2017-05-05 18:35:18.430 JupyterHub app:365]
May 05 18:35:18 fooserver jupyterhub[3069]: Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
May 05 18:35:18 fooserver jupyterhub[3069]: Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
May 05 18:35:18 fooserver jupyterhub[3069]: [E 2017-05-05 18:35:18.436 JupyterHub app:1527]
May 05 18:35:18 fooserver jupyterhub[3069]: Traceback (most recent call last):
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1524, in launch_instance_async
May 05 18:35:18 fooserver jupyterhub[3069]: yield self.initialize(argv)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1310, in initialize
May 05 18:35:18 fooserver jupyterhub[3069]: yield self.init_users()
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 871, in init_users
May 05 18:35:18 fooserver jupyterhub[3069]: user = orm.User.find(db, name)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 407, in find
May 05 18:35:18 fooserver jupyterhub[3069]: return db.query(cls).filter(cls.name==name).first()
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
May 05 18:35:18 fooserver jupyterhub[3069]: ret = list(self[0:1])
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
May 05 18:35:18 fooserver jupyterhub[3069]: return list(res)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
May 05 18:35:18 fooserver jupyterhub[3069]: return self._execute_and_instances(context)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
May 05 18:35:18 fooserver jupyterhub[3069]: result = conn.execute(querycontext.statement, self._params)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
May 05 18:35:18 fooserver jupyterhub[3069]: return meth(self, multiparams, params)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
May 05 18:35:18 fooserver jupyterhub[3069]: return connection._execute_clauseelement(self, multiparams, params)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
May 05 18:35:18 fooserver jupyterhub[3069]: compiled_sql, distilled_params
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
May 05 18:35:18 fooserver jupyterhub[3069]: context)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
May 05 18:35:18 fooserver jupyterhub[3069]: exc_info
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
May 05 18:35:18 fooserver jupyterhub[3069]: reraise(type(exception), exception, tb=exc_tb, cause=cause)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
May 05 18:35:18 fooserver jupyterhub[3069]: raise value.with_traceback(tb)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
May 05 18:35:18 fooserver jupyterhub[3069]: context)
May 05 18:35:18 fooserver jupyterhub[3069]: File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
May 05 18:35:18 fooserver jupyterhub[3069]: cursor.execute(statement, parameters)
May 05 18:35:18 fooserver jupyterhub[3069]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: users.auth_state [SQL: 'SELECT users.id AS users_id, users.name AS users_name, users._se
May 05 18:35:18 fooserver systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE
May 05 18:35:18 fooserver systemd[1]: Unit jupyterhub.service entered failed state.
```

Some googling pointed me to the command `jupyterhub upgrade-db`, however that failed too with the following output
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 19c0846f6344, base revision for 0.5
INFO  [alembic.runtime.migration] Running upgrade 19c0846f6344 -> eeb276e51423, auth_state
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: users

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.9.1', 'console_scripts', 'alembic')()
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.4/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.4/dist-packages/alembic/script/base.py", line 416, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.4/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.4/dist-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/alembic/env.py", line 70, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/alembic/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.4/dist-packages/alembic/runtime/environment.py", line 817, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.4/dist-packages/alembic/runtime/migration.py", line 323, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/alembic/versions/eeb276e51423_auth_state.py", line 21, in upgrade
    op.add_column('users', sa.Column('auth_state', JSONDict))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.4/dist-packages/alembic/operations/ops.py", line 1551, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.4/dist-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.4/dist-packages/alembic/operations/toimpl.py", line 123, in add_column
    schema=schema
  File "/usr/local/lib/python3.4/dist-packages/alembic/ddl/impl.py", line 172, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.4/dist-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users [SQL: 'ALTER TABLE users ADD COLUMN auth_state TEXT']
[E 2017-05-05 18:48:33.363 JupyterHub app:1527]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1525, in launch_instance_async
        yield self.start()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1436, in start
        self.subapp.start()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 185, in start
        dbutil.upgrade(hub.db_url)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/dbutil.py", line 80, in upgrade
        ['alembic', '-c', alembic_ini, 'upgrade', revision]
      File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmp6sh9okcf/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 1
```


Current output of `jupyter troubleshoot` for completeness
```
$PATH:
        /usr/local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /usr/local/bin
        /usr/local/lib/python3.4/dist-packages/pip-9.0.1-py3.4.egg
        /usr/lib/python3.4
        /usr/lib/python3.4/plat-x86_64-linux-gnu
        /usr/lib/python3.4/lib-dynload
        /usr/local/lib/python3.4/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.4.2 (default, Oct  8 2014, 10:45:20) 
        [GCC 4.9.1]

platform.platform():
        Linux-3.16.5.1-x86_64-with-debian-8.7

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        alembic (0.9.1)
        appdirs (1.4.3)
        backports-abc (0.5)
        backports.shutil-get-terminal-size (1.0.0)
        bleach (2.0.0)
        chardet (2.3.0)
        colorama (0.3.2)
        cycler (0.10.0)
        decorator (4.0.11)
        entrypoints (0.2.2)
        html5lib (0.999999999)
        ipykernel (4.6.1)
        ipython (6.0.0)
        ipython-genutils (0.2.0)
        ipywidgets (5.1.5)
        jedi (0.10.2)
        Jinja2 (2.9.6)
        jsonschema (2.6.0)
        jupyter (1.0.0)
        jupyter-client (5.0.1)
        jupyter-console (4.1.1)
        jupyter-core (4.3.0)
        jupyterhub (0.7.2)
        Mako (1.0.6)
        MarkupSafe (1.0)
        matplotlib (1.5.1)
        mistune (0.7.4)
        nbconvert (5.1.1)
        nbformat (4.3.0)
        notebook (5.0.0)
        numpy (1.11.0)
        packaging (16.8)
        pamela (0.3.0)
        pandas (0.18.1)
        pandocfilters (1.4.1)
        patsy (0.4.1)
        pexpect (4.2.1)
        pickleshare (0.7.4)
        pip (9.0.1)
        prompt-toolkit (1.0.14)
        ptyprocess (0.5.1)
        Pygments (2.2.0)
        pygobject (3.14.0)
        pyparsing (2.2.0)
        python-dateutil (2.6.0)
        python-editor (1.0.3)
        pytz (2016.4)
        pyzmq (16.0.2)
        qtconsole (4.2.1)
        requests (2.13.0)
        root-numpy (4.5.1)
        root-pandas (0.1.1)
        scikit-learn (0.17.1)
        scipy (0.17.1)
        seaborn (0.7.1)
        setuptools (35.0.2)
        simplegeneric (0.8.1)
        six (1.10.0)
        SQLAlchemy (1.1.9)
        statsmodels (0.6.1)
        sudospawner (0.4.0)
        terminado (0.6)
        testpath (0.3)
        tornado (4.5.1)
        traitlets (4.3.2)
        typing (3.6.1)
        urllib3 (1.9.1)
        wcwidth (0.1.7)
        webencodings (0.5.1)
        wheel (0.24.0)
        widgetsnbextension (1.2.3)
```

**Comment by dcervenkov** [comment]
OK, I had to remove `/etc/jupyterhub/jupyterhub.sqlite` and `/etc/jupyterhub/jupyterhub_cookie_secret` and now it works. However, we are back to the inital problem - flooding logs every 30 seconds for every logged in user.

**Comment by willingc** [comment]
OK, thanks for the update. I'm glad upgrading though initially a challenge is now working.

@minrk Do you have any idea why the logs would be outputting so frequently?

**Comment by parente** [comment]
It's the check for server liveliness. I forgot the exact setting name at the moment but you can adjust it.

**Comment by dcervenkov** [comment]
@parente Thanks, I found it, the option is called `c.Spawner.poll_interval` and is located in `jupyterhub_config.py`. Setting a longer interval helps somewhat. But I still don't understand, why every user needs to poll the spawner. What is the rationale behind that? If I have a 100 users, by default, it will be polling it every 0.3 seconds on average.

**Comment by minrk** [comment]
Polling local processes is handled using [`os.kill(pid, 0)`](https://github.com/jupyterhub/jupyterhub/blob/0.7.2/jupyterhub/spawner.py#L834). In sudospawner, signals are sent [via the sudospawner mediator](https://github.com/jupyterhub/sudospawner/blob/0.4.0/sudospawner/spawner.py#L97) because only the process owner can call `os.kill`. *However*, if the process exists it will raise `PermissionError`, so we can use this error to indicate process existence without invoking sudo (special-case`signal == 0`).
