### ISSUE TITLE
Docker container cannot connect to hub API

### ISSUE THREAD

**Issue by yuanzhou** [jupyterhub/jupyterhub#1135]
I'm running JupyterHub 0.7.2 on AWS EC2 instance of Amazon Linux. I installed docker and DockerSpawner to work with JupyterHub. And testing with PAM authentication, which works fine. And I could start and stop the docker container of a user with no issue. My only issue is after starting the docker container server of a user, I kept seeing this:

![capture](https://cloud.githubusercontent.com/assets/195873/26004394/add24c9c-3703-11e7-97a9-76b200286bc6.PNG)

So I found this https://github.com/jupyterhub/jupyterhub/issues/537 and tried to set the `c.JupyterHub.hub_ip='10.0.1.4'` but no luck and the proxy failed to bind to hub with this IP.

![capture3](https://cloud.githubusercontent.com/assets/195873/26005217/64c7f788-3706-11e7-8c5f-9634320eecb1.PNG)

I also read the top rated answer at http://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach and below is the output of my case:

![capture2](https://cloud.githubusercontent.com/assets/195873/26004563/44b16daa-3704-11e7-8594-1c2b82da66da.PNG)

Please advise, thanks in advance!

**Comment by yuanzhou** [comment]
And here is the output of `docker logs jupyter-demo`:

````
 Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/services/auth.py", line 165, in user_for_cookie
        'Authorization' : 'token %s' % self.api_token,
      File "/opt/conda/lib/python3.5/site-packages/requests/api.py", line 70, in get
        return request('get', url, params=params, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/api.py", line 56, in request
        return session.request(method=method, url=url, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyter-hub-token-zhy19   /2%7C1%3A0%7C10%3A1494615088%7C23%3Ajupyter-hub-token-zhy19%7C44%3AYzIxNjVlZGJlMDQyNDRkYzgxMGNkZTVmNDFlNTI5ZGE%3D%7C62cf7827403f063c2331dd4a8a0ed5d2c5ed5afbca64ad5c76429fc5584   ceb9f (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fad171b5710>: Failed to establish a new connection: [Errno 111] Connecti   on refused',))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 994, in send_error
        self.write_error(status_code, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 414, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 346, in render_template
        ns.update(self.template_namespace)
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 356, in template_namespace
        logged_in=self.logged_in,
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 116, in logged_in
        user = self.get_current_user()
      File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 87, in get_current_user
        return self.login_handler.get_user(self)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 72, in get_user
        return handler.get_current_user()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/services/auth.py", line 305, in get_current_user
        user_model = self.hub_auth.get_user(self)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/services/auth.py", line 217, in get_user
        user_model = self.user_for_cookie(encrypted_cookie)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/services/auth.py", line 174, in user_for_cookie
        raise HTTPError(500, msg)
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: 8a2   6040c7fea)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.)
[W 2017-05-12 18:51:28.737 zhy19 log:47] 404 GET /user/zhy19/static/components/preact-compat/preact-compat.min.js.map (::ffff:130.49.179.89) 3.29ms referer=None

````

**Comment by minrk** [comment]
When running with Docker, you generally want to set the bind and connect ips of the Hub separately:

```python
c.JupyterHub.hub_ip = '0.0.0.0' # listen on all interfaces
c.DockerSpawner.hub_connect_ip = '10.0.1.4' # or whatever the Hub's IP is, as seen by the Spawners
```

**Comment by pphetra** [comment]
should be "c.DockerSpawner.hub_ip_connect"

**Comment by SofianeB** [comment]
[E 2018-04-23 13:34:18.376 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/jupyter/hub/api (attempt 1/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-23 13:34:20.390 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/jupyter/hub/api (attempt 2/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-23 13:34:24.404 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/jupyter/hub/api (attempt 3/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2018-04-23 13:34:32.421 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://127.0.0.1:8081/jupyter/hub/api (attempt 4/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused
[C 2018-04-23 13:34:43.704 SingleUserNotebookApp notebookapp:1402] received signal 15, stopping
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 367, in start
    ioloop.IOLoop.current().run_sync(self.check_hub_version)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 577, in run_sync
    self.start()
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 1390, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1403, in _signal_stop
    self.io_loop.add_callback_from_signal(self.io_loop.stop)
AttributeError: 'SingleUserNotebookApp' object has no attribute 'io_loop'

**Comment by SofianeB** [comment]
My jupyterhub is running on 127.0.0.1 (host). Any hints on this?

**Comment by dyltini** [comment]
set c.JupyterHub.hub_ip='172.etc.etc.etc'
also, delete existing failed docker container and retry

docker ps --all
docker rm container_name

**Comment by SofianeB** [comment]
Thank you @dyltini. I have been working on this yesterday and tried many combination of hub_ip but no one work.  My last error was that the container is not able to contact the jupyterhub, which is running on host (127.0.01). So I don't know if it is a networking problem. 
@minrk proposed to start a server on host and try to access it with curl but it does not work. 
Is there a way to make this work without adding the flag --network='host'?

**Comment by dyltini** [comment]
did you delete the docker container?

**Comment by SofianeB** [comment]
@dyltini  After 2 days I solved the problem. 
That was due to container port and iptables blocking access to 8081.
