### ISSUE TITLE
how to solve 500 : Internal Server Error ?

### ISSUE THREAD

**Issue by ksai14** [jupyterhub/jupyterhub#1159]
Centos7
I use godaddy domain.

```
[I 2017-05-28 04:00:57.038 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="stat"' '--cookie-nam                         e="jupyter-hub-token-stat"' '--base-url="/user/stat"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="ht                         tp://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=56666
[E 2017-05-28 04:00:57.043 JupyterHub spawner:793] Permission denied trying to run '/home/anaconda3/bin/jupyter                         hub-singleuser'. Does stat have access to this file?
[E 2017-05-28 04:00:57.045 JupyterHub user:251] Unhandled error starting stat's server: [Errno 13] Permission d                         enied
[E 2017-05-28 04:00:57.223 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (203.241.235.152)
    HTTPServerRequest(protocol='https', host='www.dobestaldastat.com:8888', method='POST', uri='/hub/login?next                         =', version='HTTP/1.1', remote_ip='203.241.235.152', headers={'Referer': 'https://www.dobestaldastat.com:8888/h                         ub/login', 'Content-Length': '30', 'X-Forwarded-Host': 'www.dobestaldastat.com:8888', 'X-Forwarded-Port': '8888                         ', 'Cache-Control': 'max-age=0', 'Accept-Language': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4', 'X-Forwarded-For': '                         203.241.235.152', 'Origin': 'https://www.dobestaldastat.com:8888', 'Upgrade-Insecure-Requests': '1', 'User-Agen                         t': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safa                         ri/537.36', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'www.dobestaldastat.com:8888', 'Connec                         tion': 'close', 'X-Forwarded-Proto': 'https', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,                         image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br'})
    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/home/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single                         _user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/home/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/home/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/anaconda3/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/home/anaconda3/lib/python3.5/site-packages/jupyterhub/spawner.py", line 787, in start
        start_new_session=True, # don't forward signals
      File "/home/anaconda3/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/home/anaconda3/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied

[E 2017-05-28 04:00:57.278 JupyterHub log:99] {
      "Referer": "https://www.dobestaldastat.com:8888/hub/login",
      "Content-Length": "30",
      "X-Forwarded-Host": "www.dobestaldastat.com:8888",
      "X-Forwarded-Port": "8888",
      "Cache-Control": "max-age=0",
      "Accept-Language": "ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4",
      "X-Forwarded-For": "203.241.235.152",
      "Origin": "https://www.dobestaldastat.com:8888",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58                         .0.3029.110 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Host": "www.dobestaldastat.com:8888",
      "Connection": "close",
      "X-Forwarded-Proto": "https",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate, br"
    }
[E 2017-05-28 04:00:57.278 JupyterHub log:100] 500 POST /hub/login?next= (@203.241.235.152) 947.30ms
```

500 : Internal Server Error
Failed to start your server. Please contact admin.

**Comment by minrk** [comment]
If you are using the default Spawner, it must be run as root in order to have permission to switch users.

**Comment by willingc** [comment]
Hi @ksai14, I hope @minrk's suggestion helped resolve your issue. I will close this issue in 7 days if there are no further questions. If you do have more questions, please let us know.
