### ISSUE TITLE
Can't run jupyter notebook outside of root/sudo permissions

### ISSUE THREAD

**Issue by Qwertyismypw** [jupyterhub/jupyterhub#1196]
I am working with clusters and am attempting to set up jupyter on the machines to run both python2 and python3, as well as other kernels such as spark and scala. While I am in root mode, I can run jupyter notebook without any issues. All of the kernels are established, connection is established, etc. I think this is because I have write access to everything during this time. However, when I remove my root privileges I receive this error:

```
/usr/lib/anaconda2/lib/python2.7/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/ssawan200' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
Traceback (most recent call last):
  File "/usr/lib/anaconda2/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/usr/lib/anaconda2/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/usr/lib/anaconda2/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

A few others and myself think this is because its trying to write something to our designated personal directory, but it is technically not us (and only you/root can write to the directory), so it gets denied, and it is also attempting to grab .jupyter (as well as other files) from the $HOME path (which is set to /root and users without root privileges can't access that directory)?

Any ideas on what the issue could be? or how to go about fixing it? We tried changing the $HOME env, but that did not fix the issue (probably because the files didn't exist elsewhere).

Insert jupyter troubleshoot output here

```

$PATH:
        /usr/lib/anaconda2/bin
        /usr/lib/anaconda2/bin/
        /usr/hdp/2.4.3.0-227/hadoop/bin
        /usr/hdp/current/accumulo-master/bin
        /opt/scala-2.11.8/bin
        /opt/geomesa/geomesa-1.2.7/dist/tools/geomesa-tools-1.2.7/bin
        /usr/java/default/bin
        /usr/bin/scala/bin
        /usr/hdp/current/flume-server/bin
        /usr/hdp/current/flume-server/lib
        /usr/hdp/current/flume-server/lib/ext/*
        /usr/hdp/current/hive-client/bin
        /usr/hdp/current/hadoop-client/bin
        /usr/hdp/current/mahout-client/bin
        /usr/hdp/current/sqoop-client/bin
        /usr/hdp/current/spark-thriftserver/bin
        /usr/hdp/current/accumulo-client/bin
        /usr/hdp/current/hadoop-hdfs-client/bin
        /usr/hdp/current/falcon-client/bin
        /usr/hdp/current/pig-client/bin
        /usr/hdp/current/hadoop-yarn-client/bin
        /usr/hdp/current/hbase-client/bin
        /bin
        /opt/oracle/client-11.2.0/bin
        /app/platform/apache-maven-3.3.9//bin
        /usr/java/default/bin
        /usr/bin/scala/bin
        /usr/hdp/current/hive-client/bin
        /usr/hdp/2.4.3.0-227/hadoop/bin
        /usr/hdp/current/hadoop-client/bin
        /usr/hdp/current/sqoop-client/bin
        /usr/hdp/current/accumulo-master/bin
        /usr/hdp/current/spark-thriftserver/bin
        /usr/hdp/current/accumulo-client/bin
        /usr/hdp/current/hadoop-hdfs-client/bin
        /usr/hdp/current/pig-client/bin
        /usr/hdp/current/hadoop-yarn-client/bin
        /usr/hdp/current/hbase-client/bin
        /opt/spark-2.0.2/bin
        /opt/oracle/client-11.2.0/bin
        /opt/geomesa/geomesa-1.2.7/dist/tools/geomesa-tools-1.2.7/bin
        /usr/lib/anaconda2/bin/
        /usr/hdp/2.4.3.0-227/hadoop/bin
        /usr/hdp/current/accumulo-master/bin
        /opt/scala-2.11.8/bin
        /opt/geomesa/geomesa-1.2.7/dist/tools/geomesa-tools-1.2.7/bin
        /opt/teradata/client/14.10/tbuild/bin
        /opt/teradata/client/15.10/bin
        /usr/lib64/qt-3.3/bin
        /usr/local/bin
        /bin
        /usr/bin
        /usr/local/sbin
        /usr/sbin
        /sbin
        /app/platform/apache-maven-3.3.9/bin
        /app/platform/apache-maven-3.3.9/bin
        /root/bin
        /root/anaconda3/bin/python

sys.path:
        /usr/lib/anaconda2/bin
        /opt/spark-2.0.2/python/lib/py4j-0.10.3-src.zip
        /opt/spark-2.0.2/python
        /data01
        /usr/lib/anaconda2/lib/python27.zip
        /usr/lib/anaconda2/lib/python2.7
        /usr/lib/anaconda2/lib/python2.7/plat-linux2
        /usr/lib/anaconda2/lib/python2.7/lib-tk
        /usr/lib/anaconda2/lib/python2.7/lib-old
        /usr/lib/anaconda2/lib/python2.7/lib-dynload
        /usr/lib/anaconda2/lib/python2.7/site-packages
        /usr/lib/anaconda2/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg
        /usr/lib/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg

sys.executable:
        /usr/lib/anaconda2/bin/python

sys.version:
        2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:42:40)
        [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

platform.platform():
        Linux-2.6.32-642.15.1.el6.x86_64-x86_64-with-centos-6.8-Final

which -a jupyter:
        /usr/lib/anaconda2/bin/jupyter
        /usr/lib/anaconda2/bin/jupyter
        /usr/lib/anaconda2/bin/jupyter

pip list:
        alabaster (0.7.8)
        anaconda-client (1.4.0)
        anaconda-navigator (1.2.1)
        argcomplete (1.0.0)
        astropy (1.2.1)
        Babel (2.3.3)
        backports-abc (0.4)
        backports.shutil-get-terminal-size (1.0.0)
        backports.ssl-match-hostname (3.4.0.2)
        beautifulsoup4 (4.4.1)
        bitarray (0.8.1)
        blaze (0.10.1)
        bokeh (0.12.0)
        boto (2.40.0)
        Bottleneck (1.1.0)
        cdecimal (2.3)
        cffi (1.6.0)
        chest (0.2.3)
        click (6.6)
        cloudpickle (0.2.1)
        clyent (1.2.2)
        colorama (0.3.7)
        conda-build (1.21.3)
        conda-env (2.5.0a0)
        configobj (5.0.6)
        configparser (3.5.0b2)
        contextlib2 (0.5.3)
        cryptography (1.4)
        cycler (0.10.0)
        Cython (0.24)
        cytoolz (0.8.0)
        dask (0.10.0)
        datashape (0.5.2)
        decorator (4.0.11)
        dill (0.2.5)
        docutils (0.12)
        dynd (0.7.3.dev1)
        enum34 (1.1.6)
        et-xmlfile (1.0.1)
        fastcache (1.0.2)
        Flask (0.11.1)
        Flask-Cors (2.1.2)
        funcsigs (1.0.2)
        functools32 (3.2.3.post2)
        futures (3.0.5)
        gevent (1.1.1)
        greenlet (0.4.10)
        grin (1.2.1)
        h5py (2.6.0)
        HeapDict (1.0.0)
        idna (2.1)
        imagesize (0.7.1)
        ipaddress (1.0.16)
        ipykernel (4.3.1)
        ipython (4.2.0)
        ipython-genutils (0.1.0)
        ipywidgets (4.1.1)
        itsdangerous (0.24)
        jdcal (1.2)
        jedi (0.9.0)
        Jinja2 (2.8)
        jsonschema (2.5.1)
        jupyter (1.0.0)
        jupyter-client (4.4.0)
        jupyter-console (4.1.1)
        jupyter-core (4.2.1)
        llvmlite (0.11.0)
        locket (0.2.0)
        lxml (3.6.0)
        MarkupSafe (0.23)
        matplotlib (1.5.1)
        mistune (0.7.2)
        mpmath (0.19)
        multipledispatch (0.4.8)
        nb-anacondacloud (1.1.0)
        nb-conda (1.1.0)
        nb-conda-kernels (1.0.3)
        nbconvert (4.2.0)
        nbformat (4.0.1)
        nbpresent (3.0.2)
        networkx (1.11)
        nltk (3.2.1)
        nose (1.3.7)
        notebook (4.2.1)
        numba (0.26.0)
        numexpr (2.6.0)
        numpy (1.11.1)
        odo (0.5.0)
        openpyxl (2.3.2)
        pandas (0.18.1)
        partd (0.3.4)
        path.py (0.0.0)
        pathlib2 (2.1.0)
        patsy (0.4.1)
        pep8 (1.7.0)
        pexpect (4.0.1)
        pickleshare (0.7.2)
        Pillow (3.2.0)
        pip (9.0.1)
        ply (3.8)
        psutil (4.3.0)
        ptyprocess (0.5.1)
        py (1.4.31)
        pyasn1 (0.1.9)
        pycairo (1.10.0)
        pycosat (0.6.1)
        pycparser (2.14)
        pycrypto (2.6.1)
        pycurl (7.43.0)
        pyflakes (1.2.3)
        Pygments (2.1.3)
        pyOpenSSL (16.0.0)
        pyparsing (2.1.4)
        pytest (2.9.2)
        python-dateutil (2.5.3)
        pytz (2016.4)
        PyYAML (3.11)
        pyzmq (16.0.2)
        qtconsole (4.2.1)
        QtPy (1.0.2)
        redis (2.10.5)
        requests (2.10.0)
        rope (0.9.4)
        ruamel-yaml (-VERSION)
        scikit-image (0.12.3)
        scikit-learn (0.17.1)
        scipy (0.17.1)
        setuptools (23.0.0)
        simplegeneric (0.8.1)
        singledispatch (3.4.0.3)
        six (1.10.0)
        snowballstemmer (1.2.1)
        sockjs-tornado (1.0.3)
        Sphinx (1.4.1)
        sphinx-rtd-theme (0.1.9)
        spyder (2.3.9)
        SQLAlchemy (1.0.13)
        statsmodels (0.6.1)
        sympy (1.0)
        tables (3.2.2)
        terminado (0.6)
        toolz (0.8.0)
        toree (0.1.0.dev8)
        tornado (4.3)
        traitlets (4.3.1)
        unicodecsv (0.14.1)
        Werkzeug (0.11.10)
        wheel (0.29.0)
        xlrd (1.0.0)
        XlsxWriter (0.9.2)
        xlwt (1.1.2)

conda list:
        # packages in environment at /usr/lib/anaconda2:
        #
        _nb_ext_conf              0.2.0                    py27_0
        alabaster                 0.7.8                    py27_0
        anaconda                  4.1.1               np111py27_0
        anaconda-client           1.4.0                    py27_0
        anaconda-navigator        1.2.1                    py27_0
        argcomplete               1.0.0                    py27_1
        astropy                   1.2.1               np111py27_0
        babel                     2.3.3                    py27_0
        backports                 1.0                      py27_0
        backports_abc             0.4                      py27_0
        beautifulsoup4            4.4.1                    py27_0
        bitarray                  0.8.1                    py27_0
        blaze                     0.10.1                   py27_0
        bokeh                     0.12.0                   py27_0
        boto                      2.40.0                   py27_0
        bottleneck                1.1.0               np111py27_0
        cairo                     1.12.18                       6
        cdecimal                  2.3                      py27_2
        cffi                      1.6.0                    py27_0
        chest                     0.2.3                    py27_0
        click                     6.6                      py27_0
        cloudpickle               0.2.1                    py27_0
        clyent                    1.2.2                    py27_0
        colorama                  0.3.7                    py27_0
        conda                     4.1.6                    py27_0
        conda-build               1.21.3                   py27_0
        conda-env                 2.5.1                    py27_0
        configobj                 5.0.6                    py27_0
        configparser              3.5.0b2                  py27_1
        contextlib2               0.5.3                    py27_0
        cryptography              1.4                      py27_0
        curl                      7.49.0                        0
        cycler                    0.10.0                   py27_0
        cython                    0.24                     py27_0
        cytoolz                   0.8.0                    py27_0
        dask                      0.10.0                   py27_0
        datashape                 0.5.2                    py27_0
        decorator                 4.0.10                   py27_0
        decorator                 4.0.11                    <pip>
        dill                      0.2.5                    py27_0
        docutils                  0.12                     py27_2
        dynd-python               0.7.2                    py27_0
        entrypoints               0.2.2                    py27_0
        enum34                    1.1.6                    py27_0
        et_xmlfile                1.0.1                    py27_0
        fastcache                 1.0.2                    py27_1
        flask                     0.11.1                   py27_0
        flask-cors                2.1.2                    py27_0
        fontconfig                2.11.1                        6
        freetype                  2.5.5                         1
        funcsigs                  1.0.2                    py27_0
        functools32               3.2.3.2                  py27_0
        futures                   3.0.5                    py27_0
        get_terminal_size         1.0.0                    py27_0
        gevent                    1.1.1                    py27_0
        greenlet                  0.4.10                   py27_0
        grin                      1.2.1                    py27_3
        h5py                      2.6.0               np111py27_1
        hdf5                      1.8.16                        0
        heapdict                  1.0.0                    py27_1
        idna                      2.1                      py27_0
        imagesize                 0.7.1                    py27_0
        ipaddress                 1.0.16                   py27_0
        ipykernel                 4.3.1                    py27_0
        ipython                   4.2.0                    py27_0
        ipython_genutils          0.1.0                    py27_0
        ipywidgets                4.1.1                    py27_0
        itsdangerous              0.24                     py27_0
        jbig                      2.1                           0
        jdcal                     1.2                      py27_1
        jedi                      0.9.0                    py27_1
        jinja2                    2.8                      py27_1
        jpeg                      8d                            1
        jsonschema                2.5.1                    py27_0
        jupyter                   1.0.0                    py27_3
        jupyter-client            4.4.0                     <pip>
        jupyter-core              4.2.1                     <pip>
        jupyter_client            4.3.0                    py27_0
        jupyter_console           4.1.1                    py27_0
        jupyter_core              4.1.0                    py27_0
        libdynd                   0.7.2                         0
        libffi                    3.2.1                         0
        libgfortran               3.0.0                         1
        libpng                    1.6.22                        0
        libsodium                 1.0.10                        0
        libtiff                   4.0.6                         2
        libxml2                   2.9.2                         0
        libxslt                   1.1.28                        0
        llvmlite                  0.11.0                   py27_0
        locket                    0.2.0                    py27_1
        lxml                      3.6.0                    py27_0
        markupsafe                0.23                     py27_2
        matplotlib                1.5.1               np111py27_0
        mistune                   0.7.2                    py27_0
        mkl                       11.3.3                        0
        mkl-service               1.1.2                    py27_2
        mpmath                    0.19                     py27_1
        multipledispatch          0.4.8                    py27_0
        nb_anacondacloud          1.1.0                    py27_0
        nb_conda                  1.1.0                    py27_0
        nb_conda_kernels          1.0.3                    py27_0
        nbconvert                 4.2.0                    py27_0
        nbformat                  4.0.1                    py27_0
        nbpresent                 3.0.2                    py27_0
        networkx                  1.11                     py27_0
        nltk                      3.2.1                    py27_0
        nose                      1.3.7                    py27_1
        notebook                  4.2.1                    py27_0
        numba                     0.26.0              np111py27_0
        numexpr                   2.6.0               np111py27_0
        numpy                     1.11.1                   py27_0
        odo                       0.5.0                    py27_1
        openpyxl                  2.3.2                    py27_0
        openssl                   1.0.2h                        1
        pandas                    0.18.1              np111py27_0
        partd                     0.3.4                    py27_0
        patchelf                  0.9                           0
        path.py                   8.2.1                    py27_0
        pathlib2                  2.1.0                    py27_0
        patsy                     0.4.1                    py27_0
        pep8                      1.7.0                    py27_0
        pexpect                   4.0.1                    py27_0
        pickleshare               0.7.2                    py27_0
        pillow                    3.2.0                    py27_1
        pip                       8.1.2                    py27_0
        pip                       9.0.1                     <pip>
        pixman                    0.32.6                        0
        ply                       3.8                      py27_0
        psutil                    4.3.0                    py27_0
        ptyprocess                0.5.1                    py27_0
        py                        1.4.31                   py27_0
        pyasn1                    0.1.9                    py27_0
        pycairo                   1.10.0                   py27_0
        pycosat                   0.6.1                    py27_1
        pycparser                 2.14                     py27_1
        pycrypto                  2.6.1                    py27_4
        pycurl                    7.43.0                   py27_0
        pyflakes                  1.2.3                    py27_0
        pygments                  2.1.3                    py27_0
        pyopenssl                 0.16.0                   py27_0
        pyparsing                 2.1.4                    py27_0
        pyqt                      4.11.4                   py27_3
        pytables                  3.2.2               np111py27_4
        pytest                    2.9.2                    py27_0
        python                    2.7.12                        1
        python-dateutil           2.5.3                    py27_0
        pytz                      2016.4                   py27_0
        pyyaml                    3.11                     py27_4
        pyzmq                     15.2.0                   py27_1
        pyzmq                     16.0.2                    <pip>
        qt                        4.8.7                         3
        qtconsole                 4.2.1                    py27_0
        qtpy                      1.0.2                    py27_0
        readline                  6.2                           2
        redis                     3.2.0                         0
        redis-py                  2.10.5                   py27_0
        requests                  2.10.0                   py27_0
        rope                      0.9.4                    py27_1
        ruamel_yaml               0.11.7                   py27_0
        scikit-image              0.12.3              np111py27_1
        scikit-learn              0.17.1              np111py27_2
        scipy                     0.17.1              np111py27_1
        setuptools                23.0.0                   py27_0
        simplegeneric             0.8.1                    py27_1
        singledispatch            3.4.0.3                  py27_0
        sip                       4.16.9                   py27_0
        six                       1.10.0                   py27_0
        snowballstemmer           1.2.1                    py27_0
        sockjs-tornado            1.0.3                    py27_0
        sphinx                    1.4.1                    py27_0
        sphinx_rtd_theme          0.1.9                    py27_0
        spyder                    2.3.9                    py27_0
        sqlalchemy                1.0.13                   py27_0
        sqlite                    3.13.0                        0
        ssl_match_hostname        3.4.0.2                  py27_1
        statsmodels               0.6.1               np111py27_1
        sympy                     1.0                      py27_0
        terminado                 0.6                      py27_0
        tk                        8.5.18                        0
        toolz                     0.8.0                    py27_0
        toree                     0.1.0.dev8                <pip>
        tornado                   4.3                      py27_1
        traitlets                 4.2.1                    py27_0
        traitlets                 4.3.1                     <pip>
        unicodecsv                0.14.1                   py27_0
        werkzeug                  0.11.10                  py27_0
        wheel                     0.29.0                   py27_0
        xlrd                      1.0.0                    py27_0
        xlsxwriter                0.9.2                    py27_0
        xlwt                      1.1.2                    py27_0
        xz                        5.2.2                         0
        yaml                      0.1.6                         0
        zeromq                    4.1.4                         0
        zlib                      1.2.8                         3
```

**Comment by minrk** [comment]
Since it says the `conda` command is not found, this looks like a PATH issue. What Spawner are you using and how did you install JupyterHub? I don't see jupyerhub in your package listing, so maybe it's in a different env?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over a month. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reques to reopen this issue. Thanks! :sunflower:
