### ISSUE TITLE
All the Kernels in Jupyterhub gets dead just immediately after opening from the Browser.

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyterhub/jupyterhub#1200]
Environment:
jupyter --version --> 4.3.0
pip --version --> pip 9.0.1

Even when running `jupyter kernelspec list` I am getting the error as : 
```
Traceback (most recent call last):
  File "/app/install/jupyter/anaconda3/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/jupyter_client/connect.py", line 24, in <module>
    from traitlets.config import LoggingConfigurable
ImportError: No module named 'traitlets.config'
```
The Jupyterhub was spawned using : `nohup jupyterhub --no-ssl` & which was running fine till yesterday. Then i was trying to install jupyter_dashboard using conda which did not installed. I did raised a separate track for that https://github.com/jupyter/dashboards/issues/299.
```
Error Message from nohup log
 restarter:103] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/app/install/jupyter/anaconda3/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/app/install/jupyter/anaconda3/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/app/install/jupyter/anaconda3/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named 'traitlets.config'
```
This being our production environment and an earlier response will be really helpful.

Regards,
Sudipta

**Comment by sudipto84goswami** [comment]
Just to add on it traitlets package was already installed through pip and is available on the server itself.

**Comment by sudipto84goswami** [comment]
In addition to do when i upgraded jupyterhub and also did jupyterhub upgrade-db the hubprocess started. However I am getting the below traceback:

Traceback (most recent call last):
  File "/app/install/jupyter/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/app/install/jupyter/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/sas_kernel/__main__.py", line 18, in <module>
    from ipykernel.kernelapp import IPKernelApp
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
ImportError: No module named 'pickleshare'

The Pickelshare is already installed:
pip install pickleshare
Requirement already satisfied: pickleshare in /app/install/jupyter/anaconda3/lib/python3.5/site-packages

Can you please help me with this.

**Comment by willingc** [comment]
Hi @sudipto84goswami,

First, you will need to have traitlets installed properly. Please follow the suggested steps outlined in https://github.com/jupyter/dashboards/issues/299#issuecomment-312251494.

**Comment by sudipto84goswami** [comment]
Thanks Carol. This is now solved. After upgrading Jupyerthub along with db and after a restart everything works normal.

**Comment by willingc** [comment]
I'm glad that it's resolved @sudipto84goswami.

**Comment by sudipto84goswami** [comment]
Just one more thing on this, i am seeing a warning messages on the login page:

Warning: JupyterHub seems to be served over an unsecured HTTP connection. We strongly recommend enabling HTTPS for JupyterHub.

Is there anyway to suppress this.
