### ISSUE TITLE
Getting error for few users while loggin to jupyter and it is getting hung

### ISSUE THREAD

**Issue by uttamkumar123** [jupyterhub/jupyterhub#1235]
We have a jupyter setup using Anaconda3 (Anaconda3-2.4.1). We started seeing a recent issue with some of the users when they login to jupyter hub, as This Session's transaction has been rolled back due to a previous exception during flush and then jupyter hub though process is still running and the ui gets hung for all users.

Can anyone help us in fixing it.

```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xmo8n7n5', 'base_url': '/user/xmo8n7n5'}]]

Complete error:
E 2017-06-08 14:28:05.483 JupyterHub http1connection:54] Uncaught exception
Traceback (most recent call last):
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/http1connection.py", line 238, in read_message
delegate.finish()
**self.handler_kwargs)
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 181, in init
self.clear()
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 285, in clear
self.set_default_headers()
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 123, in set_default_headers
headers.setdefault("Content-Security-Policy", self.content_security_policy)
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 113, in content_security_policy
"report-uri " + self.csp_report_uri,
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 102, in csp_report_uri
url_path_join(self.hub.server.base_url, 'security/csp-report')
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in get
return self.impl.get(instance_state(instance), dict)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
value = self.callable_(state, passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 514, in _load_for_state
passive
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 550, in _get_ident_for_use_get
for pk in self.mapper.primary_key
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 550, in 
for pk in self.mapper.primary_key
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 2455, in get_state_attr_by_column
return state.manager[prop.key].impl.get(state, dict, passive=passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
value = state._load_expired(state, passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
self.manager.deferred_scalar_loader(self, toload)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 664, in load_scalar_attributes
only_load_props=attribute_names)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
return q.one()
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2528, in one
ret = list(self)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2571, in iter
return self._execute_and_instances(context)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
close_with_result=True)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
**kw)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 893, in connection
execution_options=execution_options)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
engine, execution_options)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
self._assert_active()
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
% self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xmo8n7n5', 'base_url': '/user/xmo8n7n5'}]]
```

**Comment by uttamkumar123** [comment]
My config file:
c.JupyterHub.admin_access = True
c.Authenticator.admin_users = {'',''}
c.JupyterHub.hub_port = 8880
c.JupyterHub.port = 8000
c.JupyterHub.config_file = '/etc/jupyterhub/jupyterhub_config.py'

**Comment by willingc** [comment]
Hi @uttamkumar123,

When you start JupyterHub, make sure that there are no other stale `jupyterhub` or `configurable-http-proxy` processes running.

Which version of jupyterhub and configurable-http-proxy are you running?
```
jupyterhub --version
configurable-http-proxy --version
```

cc/ @minrk similar to #1228

**Comment by minrk** [comment]
The error is similar, but I don't think it's the same as #1228. The test issues are generally threading related, and there is only one thread in a real JupyterHub instance. I think an error is not being handled correctly, such that the session is never re-usable. We would need the logs surrounding the very first occurrence of this error (actually, I think an error *before* the first occurrence of this rollback error will be the cause).

**Comment by uttamkumar123** [comment]
Thank You minrk and willingc for your reponse and apology for not replying.
We take care in our jupyterhub startup script, to cleanup any stale processess of jupyterhub and configurable-http-proxy, but for some reason, it just hangs and i always see address already in use error. Sometimes, even after restarting , i will be able to login, but the user who reported the issue, tries it and it again hang without getting him login even a single time. So , we also tries to delete .jupyter and .ipython folder in their hoe dir to clear any notebook/jupyter cache, holding any session and then it fixes. As of now we have been trying these trial and error method , but not able to reach to a permanent fix.

Version 
Jupyterhub - 0.7.0
configurable-http-proxy - 1.3.1

File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
        % self._rollback_exception
    sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xcozkan', 'base_url': '/user/*****'}]]

**Comment by uttamkumar123** [comment]
@minrk 

Below is the sequence of logs. We had a running jupyterhub and a user submitted a spark notebook whcih running and suddenly below sequence of the logs occurs and the jupyter hub hangs. In every restart, we are cleaning up configurable-http-proxy too. Above is version info of jupyterhub and configurable-http-proxy.

Please let me know if you need the trace logs enabled for more info. Any suggestion is appreciated as not able to find any clue on why it is happening. I have checked everything on the server if any other process is conflicting on port 8000 or 8880 but there is no case. This server is dedicated to be a jupyterhub host.

[W 2017-08-08 14:09:49.438 xknakamo handlers:255] Replacing stale connection: 0c0f26d6-3acd-401c-813c-876b463e3226:D5EE8E62A71346F1938DD8EE0ED43539
[I 2017-08-08 14:09:49.443 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-xknakamo/[secret] (xknakamo@127.0.0.1) 9.81ms
[I 2017-08-08 14:17:41.496 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-xknakamo/[secret] (xknakamo@127.0.0.1) 9.83ms
[I 2017-08-08 14:17:41.796 xknakamo handlers:179] Saving file at /Validation.ipynb
[I 2017-08-08 14:18:26.383 xknakamo log:47] 302 GET /user/xknakamo/notebooks/Validation.ipynb (::ffff:10.3.48.158) 0.80ms
[I 2017-08-08 14:18:26.516 xknakamo log:47] 302 GET /user/xknakamo/notebooks/Validation.ipynb (::ffff:10.3.48.158) 0.42ms
[W 2017-08-08 14:18:26.541 JupyterHub pages:41] Redirecting /hub/?next=%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb to /hub/user/xknakamo/notebooks/Validation.ipynb. For sharing public links, use /us
er-redirect/
[I 2017-08-08 14:18:26.544 JupyterHub log:100] 302 GET /hub/?next=%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb (@::ffff:10.3.48.158) 2.89ms
[I 2017-08-08 14:18:26.646 JupyterHub log:100] 302 GET /hub/user/xknakamo/notebooks/Validation.ipynb (@::ffff:10.3.48.158) 0.84ms
[I 2017-08-08 14:18:26.782 JupyterHub log:100] 200 GET /hub/login?next=%2Fhub%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb (@::ffff:10.3.48.158) 1.25ms
[W 2017-08-08 14:18:27.050 JupyterHub pages:41] Redirecting /hub/?next=%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb to /hub/user/xknakamo/notebooks/Validation.ipynb. For sharing public links, use /us
er-redirect/
[I 2017-08-08 14:18:27.052 JupyterHub log:100] 302 GET /hub/?next=%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb (@::ffff:10.3.48.158) 0.76ms
[I 2017-08-08 14:18:27.165 JupyterHub log:100] 302 GET /hub/user/xknakamo/notebooks/Validation.ipynb (@::ffff:10.3.48.158) 0.78ms
[E 2017-08-08 14:18:33.147 JupyterHub web:1524] Uncaught exception POST /hub/login?next=%2Fhub%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb (::ffff:10.3.48.158)
    HTTPServerRequest(protocol='http', host='<jupyter hub host>:8000', method='POST', uri='/hub/login?next=%2Fhub%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb', version='HTTP/1.1', remote_ip='::
ffff:10.3.48.158', headers={'Content-Length': '41', 'Origin': 'http://<jupyter hub host>:8000', 'Cache-Control': 'max-age=0', 'Referer': 'http://<jupyter hub host>:8000/hub/login?next=%2Fhub%2
Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36', 'Upgrade-Insecur
e-Requests': '1', 'X-Forwarded-For': '::ffff:10.3.48.158', 'Host': '<jupyter hub host>:8000', 'X-Forwarded-Port': '8000', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'Accept': '
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'X-Forwarded-Host': '<jupyter hub host>:8000', 'Content-Type': 'application/x-www-form-urlencoded', 'Connectio
n': 'close'})
Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 207, in spawn
        db.commit()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 801, in commit
        self.transaction.commit()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in commit
        self._prepare_impl()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
        self.session.flush()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2015, in flush
        self._flush(objects)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2133, in _flush
        transaction.rollback(_capture_exception=True)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
        raise value
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2097, in _flush
        flush_context.execute()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
        rec.execute(self)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
        uow


  File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
        uow
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
        mapper, table, insert)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
        execute(statement, params)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
        None, None)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
        raise value.with_traceback(tb)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
        context = constructor(dialect, self, conn, *args)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 569, in _init_compiled
        self._process_executesingle_defaults()
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 1014, in _process_executesingle_defaults
        val = self.get_insert_default(c)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 966, in get_insert_default
        return self._exec_default(column.default, column.type)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 952, in _exec_default
        return default.arg(self)
      File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 1990, in <lambda>
        return lambda ctx: fn()
      File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/utils.py", line 24, in random_port
        sock.bind(('', 0))
    sqlalchemy.exc.StatementError: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-*******', 'base_url': '/user/*******'}]]
14:20:31.358 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
14:20:31.360 - error: [ConfigProxy] 503 POST /hub/login?next=%2Fhub%2Fuser%2Fxknakamo%2Fnotebooks%2FValidation.ipynb
[E 2017-08-08 14:20:31.362 JupyterHub http1connection:54] Uncaught exception

**Comment by dzhongyi** [comment]
@uttamkumar123 I've had this problem. I guess it's the data change issue. I drop the jupyterhub database and create a new one, the problem seems to have been solved.

**Comment by willingc** [comment]
Thanks @dzhongyi for the additional info. 

One other suggestion re: the initial post would be to upgrade to JupyterHub 0.8.x and the stable version for configurable-http-proxy.
