### ISSUE TITLE
Jupyterhub with dockerSpawner on single server - issue with IPs

### ISSUE THREAD

**Issue by mpant** [jupyterhub/jupyterhub#1273]
Hello , Any help on the issue below is appreciated. Thanks Meenal
**Issue**
I am trying to setup Jupyterhub multiuser (with Github oauth) on EC2 instance and I am using Docker Spawner. I can run jupyterhub on commandline and the container spawns and gets connected  as expected. However when I try to run jupyterhub as a service I am trouble with jupyterhub and docker spawner as below (detailed syslog output below): 

500 : Internal Server Error

Spawner failed to start [status=ExitCode=127, Error='', FinishedAt=2017-07-26T05:50:43.977427414Z]

**Config file and IPs**

After looking at previous posts and doing a google search I believe IPs are an issue - below is the snippet from my jupyterhub_config.py file that sets the IPs
```
#Set correct IPs for docker
from jupyter_client.localinterfaces import public_ips
c.JupyterHub.hub_ip = '0.0.0.0' #public_ips()[0]
c.DockerSpawner.hub_ip_connect = public_ips()[0]
#Proxy IP
c.JupyterHub.ip = public_ips()[0]
c.JupyterHub.port = 443
c.JupyterHub.proxy_api_ip = public_ips()[0]
c.JupyterHub.cookie_secret_file = '/home/ubuntu/jupyterhub_cookie_secret'
c.JupyterHub.proxy_cmd = ['/usr/local/bin/configurable-http-proxy']
```
**Share what version of JupyterHub you are using**
 jupyterhub --version
0.7.2
**Syslog Traceback**
```
ubuntu@ip-172-31-4-36:~$ tail -f /var/log/syslog
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: [W 2017-07-26 05:50:04.633 JupyterHub app:365]
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]:     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]:     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]:
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:04.663 JupyterHub app:1453] Hub API listening on http://0.0.0.0:8081/hub/
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:04.666 JupyterHub app:1176] Starting proxy @ http://172.31.4.36:443/
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: 05:50:04.788 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: 05:50:04.804 - info: [ConfigProxy] Proxying https://172.31.4.36:443 to http://127.0.0.1:8081
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: 05:50:04.805 - info: [ConfigProxy] Proxy API at http://172.31.4.36:444/api/routes
Jul 26 05:50:04 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:04.871 JupyterHub app:1485] JupyterHub is now running at http://172.31.4.36:443/
Jul 26 05:50:40 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:40.115 JupyterHub log:100] 302 GET /hub/ (mpant@223.196.115.131) 2.91ms
Jul 26 05:50:40 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:40.977 JupyterHub log:100] 200 GET /hub/home (mpant@223.196.115.131) 25.55ms
Jul 26 05:50:43 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:43.130 JupyterHub log:100] 302 GET /hub/spawn (mpant@223.196.115.131) 3.87ms
Jul 26 05:50:43 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:43.460 JupyterHub log:100] 302 GET /user/mpant (@223.196.115.131) 2.86ms
Jul 26 05:50:43 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:43.812 JupyterHub dockerspawner:438] Found existing container 'jupyter-mpant' (id: 70b1077)
Jul 26 05:50:43 ip-172-31-4-36 jupyterhub[22920]: [I 2017-07-26 05:50:43.813 JupyterHub dockerspawner:450] Starting container 'jupyter-mpant' (id: 70b1077)
Jul 26 05:50:43 ip-172-31-4-36 systemd-udevd[22940]: Could not generate persistent MAC address for vethb388b92: No such file or directory
Jul 26 05:50:43 ip-172-31-4-36 systemd-udevd[22937]: Could not generate persistent MAC address for veth4ef0f41: No such file or directory
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.660887] device vethb388b92 entered promiscuous mode
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.660934] IPv6: ADDRCONF(NETDEV_UP): vethb388b92: link is not ready
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.767114] eth0: renamed from veth4ef0f41
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.767292] IPv6: ADDRCONF(NETDEV_CHANGE): vethb388b92: link becomes ready
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.767318] docker0: port 1(vethb388b92) entered forwarding state
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.767324] docker0: port 1(vethb388b92) entered forwarding state
Jul 26 05:50:43 ip-172-31-4-36 jupyterhub[22920]: [W 2017-07-26 05:50:43.960 JupyterHub dockerspawner:498] casting port to int from value '32773'
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.834364] docker0: port 1(vethb388b92) entered disabled state
Jul 26 05:50:43 ip-172-31-4-36 kernel: [388428.834423] veth4ef0f41: renamed from eth0
Jul 26 05:50:44 ip-172-31-4-36 kernel: [388428.846559] docker0: port 1(vethb388b92) entered disabled state
Jul 26 05:50:44 ip-172-31-4-36 kernel: [388428.846803] device vethb388b92 left promiscuous mode
Jul 26 05:50:44 ip-172-31-4-36 kernel: [388428.846805] docker0: port 1(vethb388b92) entered disabled state
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]: [W 2017-07-26 05:50:53.814 JupyterHub web:1587] 500 GET /hub/user/mpant (223.196.115.131): Spawner failed to start [status=ExitCode=127, Error='', FinishedAt=2017-07-26T05:50:43.977427414Z]
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]: [E 2017-07-26 05:50:53.827 JupyterHub log:99] {
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "X-Forwarded-For": "223.196.115.131",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Referer": "https://jupyterhub.pykids.us/hub/home",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Cookie": "jupyter-hub-token=\"2|1:0|10:1500689143|17:jupyter-hub-token|44:ZTM2NWY5ZjEzNmRhNDM3ZWI5NzcwY2E3NmQ1Zjg1MzE=|80e73a954aad016e254dc65e07e46badbed02299d8aac547d97ebe9e4a0322f4\"; _xsrf=2|04821bf2|212433c6b2b41aa9f79dbf9ef05c2697|1500614392",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "X-Forwarded-Host": "jupyterhub.pykids.us",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Host": "jupyterhub.pykids.us",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "X-Forwarded-Proto": "https",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Accept-Encoding": "gzip, deflate, br",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Accept-Language": "en-US,en;q=0.5",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "X-Forwarded-Port": "443",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0",
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:       "Connection": "close"
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]:     }
Jul 26 05:50:53 ip-172-31-4-36 jupyterhub[22920]: [E 2017-07-26 05:50:53.829 JupyterHub log:100] 500 GET /hub/user/mpant (mpant@223.196.115.131) 10038.75ms
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]: [W 2017-07-26 05:51:14.061 JupyterHub user:278] mpant's server never showed up at http://127.0.0.1:32773/user/mpant after 30 seconds. Giving up
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]: [E 2017-07-26 05:51:14.071 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fd97db71128> after timeout
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:     Traceback (most recent call last):
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:       File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:         future.result()
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:       File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 294, in spawn
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:         raise e
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:       File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 270, in spawn
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:         yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:       File "/usr/local/lib/python3.5/dist-packages/jupyterhub/orm.py", line 108, in wait_up
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:         yield wait_for_http_server(self.url, timeout=timeout)
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:       File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:         **locals()
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:     TimeoutError: Server at http://127.0.0.1:32773/user/mpant didn't respond in 30 seconds
Jul 26 05:51:14 ip-172-31-4-36 jupyterhub[22920]:
Jul 26 05:55:04 ip-172-31-4-36 jupyterhub[22920]: 05:55:04.893 - info: [ConfigProxy] 200 GET /api/routes
```

**Comment by mpant** [comment]
Can anyone help with this issue?  Thanks

**Comment by mpant** [comment]
Thankyou Carol, I have been able to resolve this . I am not quite sure what
worked but I rewrote the jupyterhub_config.py
https://gist.github.com/mpant/621301e0e4514a719d73616b5069af34  and it
resolved my issue.

Thanks,
Meenal

**Comment by willingc** [comment]
Good to hear @mpant. Feel free to ping us on the gitter channel if you run in to anything else.
