### ISSUE TITLE
Docker error for containerized local deployment 

### ISSUE THREAD

**Issue by rueberger** [jupyterhub/jupyterhub#1284]
# Problem 

I am setting up a jupyterhub deployment for internal use at Janelia. I'm trying to integrate as much as possible into our existing infrastructure and also using our own hardware, so what I'm trying to do  doesn't map so well onto the existing docs.  

I'm running jupyterhub from docker, using LDAPAuthenticator and DockerSpawner. I am able to successfully authenticate but the server fails to start with the following:

```[I 2017-07-27 17:35:18.949 JupyterHub dockerspawner:459] Starting container 'jupyter-bergera' (id: 7b55bc9)
[E 2017-07-27 17:35:18.952 JupyterHub user:251] Unhandled error starting bergera's server: Providing configuration in the start() method is no longer supported. Use the host_config param in create_container instead.
[E 2017-07-27 17:35:18.962 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (10.8.0.186)
    HTTPServerRequest(protocol='http', host='c04u01:8080', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='10.8.0.186', headers={'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '38', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.8', 'Referer': 'http://c04u01:8080/hub/login', 'Connection': 'keep-alive', 'Cookie': 'gsScrollPos-1340=0; gsScrollPos-1025=0; gsScrollPos-1371=0; username-c04u01-8335=2|1:0|10:1498887801|20:username-c04u01-8335|48:OWM2OTNlYmUtMjYxNy00MTRjLTkxZTctYjViZmJlZGQ3MzY0|ae36f007c321e5e23d2378e1753936f8a8b8947693f53e3f5abdd7a9d98645a9; _xsrf=2|3af27381|059c461f48750cb91767a71bae5fc6a9|1501000793', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Cache-Control': 'max-age=0', 'Origin': 'http://c04u01:8080', 'Host': 'c04u01:8080'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 468, in start
        yield self.docker('start', self.container_id, **start_kwargs)
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 330, in _docker
        return m(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/docker/api/container.py", line 1073, in start
        'Providing configuration in the start() method is no longer '
    docker.errors.DeprecatedMethod: Providing configuration in the start() method is no longer supported. Use the host_config param in create_container instead.
    
[E 2017-07-27 17:35:18.971 JupyterHub log:99] {
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "Content-Length": "38",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.8",
      "Referer": "http://c04u01:8080/hub/login",
      "Connection": "keep-alive",
      "Cookie": "gsScrollPos-1340=0; gsScrollPos-1025=0; gsScrollPos-1371=0; username-c04u01-8335=2|1:0|10:1498887801|20:username-c04u01-8335|48:OWM2OTNlYmUtMjYxNy00MTRjLTkxZTctYjViZmJlZGQ3MzY0|ae36f007c321e5e23d2378e1753936f8a8b8947693f53e3f5abdd7a9d98645a9; _xsrf=2|3af27381|059c461f48750cb91767a71bae5fc6a9|1501000793",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Cache-Control": "max-age=0",
      "Origin": "http://c04u01:8080",
      "Host": "c04u01:8080"
    }
[E 2017-07-27 17:35:18.971 JupyterHub log:100] 500 POST /hub/login?next= (@10.8.0.186) 103.56ms
```

# Background

### Dockerfile

```
FROM jupyterhub/jupyterhub:0.7.2

WORKDIR /srv/jupyterhub

ADD . /srv/jupyterhub

RUN pip install -r requirements.txt
RUN  git clone https://github.com/jupyterhub/dockerspawner.git && \
     cd dockerspawner && \
     pip install . && \
     cd ..

EXPOSE 8000
EXPOSE 389
```

### requirements.txt

```
tensorflow
keras
bokeh
matplotlib
jupyterhub-ldapauthenticator
```

### Dockerfile 

```
FROM rueberger/jupyterhub_base:latest

WORKDIR /srv/jupyterhub

# copy in jupyterhub_config.py
ADD . /srv/jupyterhub

EXPOSE 8080

CMD jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
```

### jupyterhub_config.py 

```
# Configuration file for jupyterhub.

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'


# Connect containers to this Docker network
network_name = 'jhub'
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
# Pass the network name as argument to spawned containers
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
c.DockerSpawner.extra_start_kwargs = { 'network_mode': network_name }
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = '*'
c.JupyterHub.hub_port = 8080

c.DockerSpawner.container_ip = '0.0.0.0'
c.DockerSpawner.hub_ip_connect = 'jhub'


## The public facing ip of the whole application (the proxy)
c.JupyterHub.ip = '*'

## The class to use for spawning single-user servers.
#
#  Should be a subclass of Spawner.
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'


#------------------------------------------------------------------------------
# LDAP config
#------------------------------------------------------------------------------

c.LDAPAuthenticator.server_address = 'ldap-vip1.int.janelia.org'

c.LDAPAuthenticator.bind_dn_template = 'cn={username},ou=People,dc=hhmi,dc=org'

c.LDAPAuthenticator.use_ssl = False

```
### `pip list`

```
alembic (0.8.9)
backports.weakref (1.0rc1)
bkcharts (0.2)
bleach (1.5.0)
bokeh (0.12.6)
conda (4.2.13)
cycler (0.10.0)
decorator (4.0.10)
docker (2.4.2)
docker-pycreds (0.2.1)
dockerspawner (0.7.0)
escapism (0.0.1)
html5lib (0.9999999)
ipython-genutils (0.1.0)
Jinja2 (2.8)
jupyterhub (0.7.2)
jupyterhub-ldapauthenticator (1.1)
Keras (2.0.6)
ldap3 (2.2.4)
Mako (1.0.6)
Markdown (2.6.8)
MarkupSafe (0.23)
matplotlib (2.0.2)
numpy (1.13.1)
pamela (0.3.0)
pip (9.0.1)
protobuf (3.3.0)
pyasn1 (0.3.1)
pycosat (0.6.1)
pycrypto (2.6.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
python-editor (1.0.3)
pytz (2017.2)
PyYAML (3.12)
requests (2.12.4)
ruamel-yaml (-VERSION)
scipy (0.19.1)
setuptools (27.2.0)
six (1.10.0)
SQLAlchemy (1.1.4)
tensorflow (1.2.1)
Theano (0.9.0)
tornado (4.4.2)
traitlets (4.3.0)
websocket-client (0.44.0)
Werkzeug (0.12.2)
wheel (0.29.0)
```

## DockerSpawner image

I use `jupyterhub/singleuser`

##  Deploy command 

`docker run --name jhub -h jhub -p 8000:8000 -p 8080:8080  -v /var/run/docker.sock:/var/run/docker.sock jhub`

Let me know if it would be helpful to provide any other info.

Thanks in advance for your help!!

**Comment by willingc** [comment]
[Gitter log](https://pastebin.com/z3srhPJf)

**Reported error**
```
docker.errors.DeprecatedMethod: Providing configuration in the start() method is no longer supported. Use the host_config param in create_container instead.
```

**Comment by willingc** [comment]
@rueberger A couple of thoughts:

- It looks like you have a base image `rueberger/jupyterhub_base` that you have created and use that image in another `Dockerfile` to create the `Jhub` image. Perhaps that is causing a problem with networking or ports.
- Perhaps change `'*'` in `jupyterhub_config.py` [See doc ref](http://jupyterhub.readthedocs.io/en/latest/networking-basics.html#set-the-proxy-s-ip-address-and-port)

If it's not too inconvenient, would you mind sharing the debug log from the beginning of JupyterHub's start to the error? Thanks.

cc/@minrk

**Comment by rueberger** [comment]
Of course it's not too inconvenient, it's the least I can do! Here it is https://gist.github.com/rueberger/a860ddda211724694d3d7cd7691a57e6.

(this is after changing the ip wildcard to an empty string)

I added 

```
c.JupyterHub.log_level = 'DEBUG'
c.Spawner.debug = True
``` 

to my config to get that. Perhaps I also need to set that flag for DockerSpawner itself? 

I'm using the base image just to speed up build times. If you think there's reason to believe this issue could be caused by network, I'll try out collapsing it all into one image.

**Comment by willingc** [comment]
Thanks @rueberger.

@mirnk, I'm going to defer to you on this one. Will you take a look at the networking configuration and see if something jumps out at you? Thanks!

**Comment by rueberger** [comment]
I resolved this issue by removing the `c.extra_start_kwargs` declaration in `jupyterhub_config.py`. 

The problematic line is [here](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L468). I think this is actually a bug, `docker-py` docs say that [an error is raised if any args besides container are passed](http://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.start).

I'll give a summary of this deployment once everything is going.

**Comment by willingc** [comment]
@rueberger Thanks! Glad you found the issue. Please let us know how the rest goes.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you have additional action items related to the issue. Thanks! 🌻

**Comment by rueberger** [comment]
Oops sorry... I forgot to follow up and now I've forgotten entirely what I did... 

I did get everything working in the end. For posterity's sake, [here's the repo](https://github.com/rueberger/janelia_jupyterhub).

Thanks for your help @willingc!
