### ISSUE TITLE
Troubleshooting SSL certification and proxy binding to EC2 public IP

### ISSUE THREAD

**Issue by sbanerjee23** [jupyterhub/jupyterhub#1327]
I'm trying to enable SSL certification for a jupyterhub installation on an EC2 instance running Ubuntu 16.04. I installed jupyterhub from conda-forge and am running it inside a conda environment. I am able to run `jupyterhub` without configuring my SSL certificate and key, and access the hub by going to my EC2 IPv4 public IP. I registered a free domain for testing and used the instructions here (https://jupyterhub.readthedocs.io/en/latest/security-basics.html#enabling-ssl-encryption) to get a SSL cert and key. I made some minor changes to the config file (below), put the EC2 public IP and HTTPS port in the `c.JupyterHub.ip`; `c.JupyterHub.port` fields, and made sure the inbound/outbound rules on the instance allowed for traffic from ports 443, 22, 8000, and 80. 

When I run `jupyterhub` after configuration, I get what I think is a public IP not available error (verbose error output below) `[ConfigProxy] Uncaught Exception Error: listen EADDRNOTAVAIL 34.2XX.XXX.XX:443`. Also am able to run `configurable-http-proxy` and `configurable-http-proxy --ip 0.0.0.0 --port 443` without errors. My understanding is that the `hub_ip` and `hub_port` are local/internal so can be left as default and the `ip` is the public EC2 ip (in my case) and `port` is the port to use for SSL authentication. Have I configured these incorrectly? In general, I'm having a hard time diagnosing whether this is a problem with my SSL certificate/key, choice of free domain, jupyterhub configuration, instance traffic rules, a dependency issue as a result of installing from conda-forge, or something else. I know very little about networking, proxies, or SSL authentication so fingers crossed this is a simple mistake on my part. Any advice would be much appreciated. If I am forgetting any other information, please let me know. 

PS. Felt this problem was somewhat similar to #271 and #530, but wasn't sure. 

**Error**
```
(db1) root@ip-17X-XX-XX-XXX:/home/ubuntu# jupyterhub -f jupyterhub_config.py 
[I 2017-08-09 05:19:14.327 JupyterHub app:724] Loading cookie_secret from /home/ubuntu/jupyterhub_cookie_secret
[W 2017-08-09 05:19:14.358 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2017-08-09 05:19:14.366 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-08-09 05:19:14.366 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-08-09 05:19:14.366 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-08-09 05:19:14.379 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8000/hub/
[I 2017-08-09 05:19:14.383 JupyterHub app:1176] Starting proxy @ http://34.2XX.XXX.XX:443/
05:19:14.565 - info: [ConfigProxy] Proxying https://34.2XX.XXX.XX:443 to http://127.0.0.1:8000
05:19:14.568 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
05:19:14.574 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRNOTAVAIL 34.2XX.XXX.XX:443
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
[C 2017-08-09 05:19:25.482 JupyterHub app:1459] Failed to start proxy
    Traceback (most recent call last):
      File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/jupyterhub/app.py", line 1457, in start
        yield self.start_proxy()
      File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/jupyterhub/app.py", line 1204, in start_proxy
        yield server.wait_up(1)
      File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_server(self.ip or '127.0.0.1', self.port, timeout=timeout)
      File "/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/jupyterhub/utils.py", line 60, in wait_for_server
        **locals()
    TimeoutError: Server at 34.2XX.XXX.XX:443 didn't respond in 1 seconds
```

**Uncommented lines in `jupyterhub_config.py`**
```
c.JupyterHub.hub_ip = '127.0.0.1'
c.JupyterHub.hub_port = 8000

c.JupyterHub.ip = '34.2XX.XX.XX'
c.JupyterHub.port = 443

c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/my_domain.tk/fullchain.pem'
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/my_domain.tk/privkey.pem'
```
**Version and `jupyter troubleshoot` output**
0.7.2
```
$PATH:
	/home/deployment/miniconda3/envs/db1/bin
	/home/deployment/miniconda3/envs/db1/bin
	/home/deployment/miniconda3/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/snap/bin
	/snap/bin

sys.path:
	/home/deployment/miniconda3/envs/db1/bin
	/home/deployment/miniconda3/envs/db1/lib/python35.zip
	/home/deployment/miniconda3/envs/db1/lib/python3.5
	/home/deployment/miniconda3/envs/db1/lib/python3.5/plat-linux
	/home/deployment/miniconda3/envs/db1/lib/python3.5/lib-dynload
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/channelarchiver-0.0.5-py3.5.egg
	/home/deployment/other_src/portable-fs
	/home/deployment/other_src/filestore
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/jsonschema-2.6.0-py3.5.egg
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/pymongo-3.4.0-py3.5-linux-x86_64.egg
	/home/deployment/other_src/portable-mds
	/home/deployment/other_src/metadatastore
	/home/deployment/other_src/databroker
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/attrs-16.3.0-py3.5.egg
	/home/deployment/other_src/xpdAn
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg
	/home/deployment/miniconda3/envs/db1/lib/python3.5/site-packages/tzlocal-1.1.2-py3.5.egg

sys.executable:
	/home/deployment/miniconda3/envs/db1/bin/python

sys.version:
	3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
	[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

platform.platform():
	Linux-4.4.0-72-generic-x86_64-with-debian-stretch-sid

which -a jupyter:
	/home/deployment/miniconda3/envs/db1/bin/jupyter
	/home/deployment/miniconda3/envs/db1/bin/jupyter
	/home/deployment/miniconda3/bin/jupyter

pip list:
	anaconda-client (1.6.3)
	asn1crypto (0.22.0)
	attrs (16.3.0)
	autobahn (0.18.1)
	Automat (0.5.0)
	bleach (1.5.0)
	boltons (16.3.1)
	cffi (1.10.0)
	channelarchiver (0.0.5)
	click (6.7)
	clyent (1.2.2)
	constantly (15.1.0)
	cryptography (1.8.1)
	cycler (0.10.0)
	cytoolz (0.8.2)
	databroker (0.7.0+104.gb7c2a2e, /home/deployment/other_src/databroker)
	decorator (4.0.11)
	doct (1.0.2)
	entrypoints (0.2.2)
	fabio (0.4.0)
	filestore (0.8.0+0.g0253aaf.dirty, /home/deployment/other_src/filestore)
	h5py (2.7.0)
	hkdf (0.0.3)
	html5lib (0.999)
	humanize (0.5.1)
	idna (2.5)
	incremental (16.10.1)
	ipaddress (1.0.18)
	ipykernel (4.6.1)
	ipython (6.0.0)
	ipython-genutils (0.2.0)
	ipywidgets (6.0.0)
	jedi (0.10.2)
	Jinja2 (2.9.6)
	jsonschema (2.6.0)
	jupyter-client (5.1.0)
	jupyter-core (4.3.0)
	jupyterhub (0.7.2)
	lmfit (0.8.3)
	lxml (3.7.3)
	magic-wormhole (0.9.2)
	MarkupSafe (0.23)
	matplotlib (1.5.1)
	metadatastore (0.6.4+6.gab46a64, /home/deployment/other_src/metadatastore)
	mistune (0.7.4)
	mock (2.0.0)
	mongoquery (1.1.0)
	nb-anacondacloud (1.4.0)
	nb-conda (2.2.0)
	nb-conda-kernels (2.1.0)
	nbconvert (5.2.1)
	nbformat (4.3.0)
	nbpresent (3.0.2)
	networkx (1.11)
	notebook (5.0.0)
	numpy (1.11.3)
	olefile (0.44)
	packaging (16.8)
	pamela (0.3.0)
	pandas (0.20.1)
	pandocfilters (1.4.1)
	pbr (1.10.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	Pillow (4.1.1)
	PIMS (0.2.2)
	pip (9.0.1)
	ply (3.10)
	portable-fs (0+untagged.31.g3499828, /home/deployment/other_src/portable-fs)
	portable-mds (0+untagged.57.g244ae8b, /home/deployment/other_src/portable-mds)
	prettytable (0.7.2)
	prompt-toolkit (1.0.14)
	ptyprocess (0.5.1)
	py (1.4.33)
	pyasn1 (0.2.3)
	pyasn1-modules (0.0.8)
	pycparser (2.17)
	pyFAI (0.13.1)
	Pygments (2.2.0)
	pymongo (3.3.0)
	PyNaCl (1.0.1)
	pyOpenSSL (16.2.0)
	pyparsing (2.1.4)
	pytest (3.0.7)
	python-dateutil (2.6.0)
	pytz (2017.2)
	PyWavelets (0.5.2)
	pyxDamerauLevenshtein (1.4.1)
	PyYAML (3.12)
	pyzmq (16.0.2)
	requests (2.14.2)
	scikit-beam (0.0.9.post0)
	scikit-image (0.13.0)
	scipy (0.19.0)
	service-identity (16.0.0)
	setproctitle (1.1.10)
	setuptools (27.2.0)
	simplegeneric (0.8.1)
	six (1.10.0)
	spake2 (0.7)
	SQLAlchemy (1.1.9)
	terminado (0.6)
	testpath (0.3)
	tifffile (0.9.0)
	toolz (0.8.2)
	tornado (4.5.1)
	tqdm (4.11.2)
	traitlets (4.3.2)
	Twisted (17.1.0)
	txaio (2.6.2)
	tzlocal (1.1.2)
	wcwidth (0.1.7)
	wheel (0.29.0)
	widgetsnbextension (2.0.0)
	xlrd (1.0.0)
	xonsh (0.5.10)
	xpdan (0.0.0a0, /home/deployment/other_src/xpdAn)
	zope.interface (4.3.3)

conda list:
	# packages in environment at /home/deployment/miniconda3/envs/db1:
	#
	_nb_ext_conf              0.4.0                    py35_1  
	anaconda-client           1.6.3                    py35_0  
	asn1crypto                0.22.0                    <pip>
	atk                       1.28.0                        0    ska
	attrs                     16.3.0                    <pip>
	autobahn                  0.18.1                    <pip>
	Automat                   0.5.0                     <pip>
	bleach                    1.5.0                    py35_0  
	boltons                   16.3.1                   py35_0    lightsource2
	cairo                     1.8.8                         0    ska
	cffi                      1.10.0                   py35_0  
	channelarchiver           0.0.5.6                  py35_1    lightsource2
	click                     6.7                       <pip>
	clyent                    1.2.2                    py35_0  
	configurable-http-proxy   2.0.0                         0    conda-forge
	constantly                15.1.0                    <pip>
	cryptography              1.8.1                     <pip>
	cycler                    0.10.0                   py35_0  
	cytoolz                   0.8.2                    py35_0  
	dbus                      1.10.10                       0  
	decorator                 4.0.11                   py35_0  
	doct                      1.0.2                    py35_0    lightsource2
	entrypoints               0.2.2                    py35_1  
	expat                     2.1.0                         0  
	fabio                     0.4.0               np111py35_0    conda-forge
	fontconfig                2.12.1                        3  
	freetype                  2.5.5                         2  
	gettext                   0.19                          0    lightsource2
	glib                      2.50.2                        1  
	gst-plugins-base          1.8.0                         0  
	gstreamer                 1.8.0                         0  
	gtk-plus                  2.18.3                        0    ska
	h5py                      2.7.0               np111py35_0  
	hdf5                      1.8.17                        1  
	hkdf                      0.0.3                     <pip>
	html5lib                  0.999                    py35_0  
	humanize                  0.5.1                     <pip>
	icu                       54.1                          0  
	idna                      2.5                       <pip>
	incremental               16.10.1                   <pip>
	ipaddress                 1.0.18                    <pip>
	ipykernel                 4.6.1                    py35_0  
	ipython                   6.0.0                    py35_1  
	ipython_genutils          0.2.0                    py35_0  
	ipywidgets                6.0.0                    py35_0  
	jbig                      2.1                           0  
	jedi                      0.10.2                   py35_2  
	jinja2                    2.9.6                    py35_0  
	jpeg                      9b                            0  
	jsonschema                2.6.0                    py35_0  
	jsonschema                2.6.0                     <pip>
	jupyter_client            5.1.0                    py35_0  
	jupyter_core              4.3.0                    py35_0  
	jupyterhub                0.7.2                    py35_0    conda-forge
	libffi                    3.2.1                         1  
	libgcc                    5.2.0                         0  
	libgfortran               3.0.0                         1  
	libiconv                  1.14                          0  
	libpng                    1.6.27                        0  
	libsodium                 1.0.10                        0  
	libtiff                   4.0.6                         3  
	libxcb                    1.12                          1  
	libxml2                   2.9.4                         0  
	libxslt                   1.1.29                        0  
	lmfit                     0.8.3                    py35_1    conda-forge
	lxml                      3.7.3                    py35_0  
	magic-wormhole            0.9.2                     <pip>
	markupsafe                0.23                     py35_2  
	matplotlib                1.5.1               np111py35_0  
	mistune                   0.7.4                    py35_0  
	mkl                       2017.0.1                      0  
	mock                      2.0.0                    py35_0  
	mongoquery                1.1.0                    py35_0    conda-forge
	nb_anacondacloud          1.4.0                    py35_0  
	nb_conda                  2.2.0                    py35_0  
	nb_conda_kernels          2.1.0                    py35_0  
	nbconvert                 5.2.1                    py35_0  
	nbformat                  4.3.0                    py35_0  
	nbpresent                 3.0.2                    py35_0  
	networkx                  1.11                     py35_0  
	nodejs                    6.6.0                         0    conda-forge
	notebook                  5.0.0                    py35_0  
	numpy                     1.11.3                   py35_0  
	olefile                   0.44                     py35_0  
	openssl                   1.0.2k                        2  
	packaging                 16.8                      <pip>
	pamela                    0.3.0                    py35_0    conda-forge
	pandas                    0.20.1              np111py35_0  
	pandocfilters             1.4.1                    py35_0  
	pango                     1.26.0                        0    ska
	path.py                   10.3.1                   py35_0  
	pbr                       1.10.0                   py35_0  
	pcre                      8.39                          1  
	pexpect                   4.2.1                    py35_0  
	pickleshare               0.7.4                    py35_0  
	pillow                    4.1.1                    py35_0  
	pims                      0.2.2                    py35_0    lightsource2
	pip                       9.0.1                    py35_1  
	pixman                    0.16.2                        0    ska
	ply                       3.10                     py35_0  
	prettytable               0.7.2                    py35_0    conda-forge
	prompt_toolkit            1.0.14                   py35_0  
	ptyprocess                0.5.1                    py35_0  
	py                        1.4.33                   py35_0  
	pyasn1                    0.2.3                     <pip>
	pyasn1-modules            0.0.8                     <pip>
	pycairo                   1.8.8                         0    ska
	pycparser                 2.17                     py35_0  
	pyfai                     0.13.1              np111py35_0    conda-forge
	pygments                  2.2.0                    py35_0  
	pygobject                 2.20.0                        0    ska
	pygtk                     2.16.0                        0    ska
	pymongo                   3.3.0                    py35_0  
	pynacl                    1.0.1                    py35_0    conda-forge
	pyOpenSSL                 16.2.0                    <pip>
	pyparsing                 2.1.4                    py35_0  
	pyqt                      4.11.4                   py35_2    conda-forge
	pytest                    3.0.7                    py35_0  
	python                    3.5.3                         1  
	python-dateutil           2.6.0                    py35_0  
	pytz                      2017.2                   py35_0  
	pywavelets                0.5.2               np111py35_0  
	pyxdameraulevenshtein     1.4.1                    py35_0    conda-forge
	pyyaml                    3.12                     py35_0  
	pyzmq                     16.0.2                   py35_0  
	qt                        4.8.7                         4  
	readline                  6.2                           2  
	requests                  2.14.2                   py35_0  
	scikit-beam               0.0.9               np111py35_0    conda-forge
	scikit-image              0.13.0              np111py35_0  
	scipy                     0.19.0              np111py35_0  
	service-identity          16.0.0                    <pip>
	setproctitle              1.1.10                   py35_0    conda-forge
	setuptools                27.2.0                   py35_0  
	simplegeneric             0.8.1                    py35_1  
	sip                       4.18                     py35_0  
	six                       1.10.0                   py35_0  
	spake2                    0.7                       <pip>
	sqlalchemy                1.1.9                    py35_0  
	sqlite                    3.13.0                        0  
	system                    5.8                           2  
	terminado                 0.6                      py35_0  
	testpath                  0.3                      py35_0  
	tifffile                  0.9.0               np111py35_0    lightsource2
	tk                        8.5.18                        0  
	toolz                     0.8.2                    py35_0  
	tornado                   4.5.1                    py35_0  
	tqdm                      4.11.2                    <pip>
	traitlets                 4.3.2                    py35_0  
	Twisted                   17.1.0                    <pip>
	txaio                     2.6.2                     <pip>
	tzlocal                   1.1.2                    py35_1    lightsource2
	wcwidth                   0.1.7                    py35_0  
	wheel                     0.29.0                   py35_0  
	widgetsnbextension        2.0.0                    py35_0  
	xlrd                      1.0.0                    py35_0  
	xonsh                     0.5.10                   py35_2    conda-forge
	xraylib                   3.2.0               np111py35_1    conda-forge
	xz                        5.2.2                         1  
	yaml                      0.1.6                         0  
	zeromq                    4.1.5                         0  
	zlib                      1.2.8                         3  
	zope.interface            4.3.3                     <pip>

```

**Comment by minrk** [comment]
You're right that `.hub_ip` and `.hub_port` are the internal ip and port of the Hub process. `.ip` and `.port` are the *bind* addresses of the proxy. My guess is that `34.2XX.XXX.XX` isn't a local IP of your server, but instead an ip of an AWS proxy/load-balancer/etc., so you can't bind to it. You can probably use the default `ip` of all-interfaces (or `0.0.0.0`), and it should work.

**Comment by sbanerjee23** [comment]
Thanks a lot. I left all the defaults in the config file, specified the https 443 port, paths to the SSL key and certificate, and was able to get the hub running on a secure domain.
