### ISSUE TITLE
Singleuser errors with usernames containing special chars

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1329]
Using DummyAuthenticator and username (gunjan_baid@berkeley.edu), singleuser server fails with:

```
   Traceback (most recent call last):
      File "/srv/app/venv/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/srv/app/venv/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 129, in get
        self.hub_auth.set_cookie(self, token)
      File "/srv/app/venv/lib/python3.6/site-packages/jupyterhub/services/auth.py", line 492, in set_cookie
        **kwargs
      File "/srv/app/venv/lib/python3.6/site-packages/tornado/web.py", line 619, in set_secure_cookie
        expires_days=expires_days, **kwargs)
      File "/srv/app/venv/lib/python3.6/site-packages/tornado/web.py", line 548, in set_cookie
        self._new_cookie[name] = value
      File "/usr/lib/python3.6/http/cookies.py", line 521, in __setitem__
        self.__set(key, rval, cval)
      File "/usr/lib/python3.6/http/cookies.py", line 511, in __set
        M.set(key, real_value, coded_value)
      File "/usr/lib/python3.6/http/cookies.py", line 380, in set
        raise CookieError('Illegal key %r' % (key,))
    http.cookies.CookieError: Illegal key 'user-gunjan_baid@berkeley.edu'
```

repeatedly.

**Comment by minrk** [comment]
Is this with 0.7 or master? What Spawner? I don't think usernames are used in cookie names in master.

**Comment by yuvipanda** [comment]
Yup, this is master and kubespawner.

**Comment by yuvipanda** [comment]
I can repro this on master with the following simple config: 


```
c.JupyterHub.spawner_class = 'simplespawner.SimpleLocalProcessSpawner'

c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
```

**Comment by yuvipanda** [comment]
The cookie name it was trying to set was `user-yuvipanda@gmail.com`. Not sure where that's being set from...

**Comment by minrk** [comment]
Roger, found it. #1333 fixes it.
