### ISSUE TITLE
Exception in /admin on sorting by running servers

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#1345]
**How to reproduce the issue**
On current master, visit /admin and click any sort arrow next to "Running".
 
**What you expected to happen**
Servers are sorted.

**What actually happens**
An error is produced, `500 : Internal Server Error`.
The hub logs show
```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 193, in decorated
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/pages.py", line 179, in get
        cols = [ getattr(orm.User, mapping.get(c, c)) for c in sorts ]
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/pages.py", line 179, in <listcomp>
        cols = [ getattr(orm.User, mapping.get(c, c)) for c in sorts ]
    AttributeError: type object 'User' has no attribute '_server_id'
```
**Share what version of JupyterHub you are using**
Current master.

Looks like this is related to https://github.com/jupyterhub/jupyterhub/issues/766#issuecomment-267297617.

**Comment by minrk** [comment]
Thanks for testing! Should be fixed by #1346
