### ISSUE TITLE
500 error on login, backend log shows "Failed to get JSON result from mediator"

### ISSUE THREAD

**Issue by dramaley** [jupyterhub/jupyterhub#1357]
Hello. I am trying to get JupyterHub 0.7.2 (installed via Anaconda3) running as a non-privileged user. The login page displays, but when i provide proper credentials i get:
```
500 : Internal Server Error
Failed to start your server. Please contact admin.
```

I find this in the logfile on the server when i try to log in:
```
[E 2017-08-22 13:48:16.270 JupyterHub spawner:77] Failed to get JSON result from mediator: ''
[E 2017-08-22 13:48:16.273 JupyterHub user:251] Unhandled error starting ramaley's server: substring not found
[E 2017-08-22 13:48:16.288 JupyterHub web:1590] Uncaught exception POST /jupyterhub/hub/login?next= (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='analytics.drake.edu', method='POST', uri='/jupyterhub/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1', headers={'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '80', 'Content-Length': '46', 'Connection': 'close', 'X-Forwarded-Server': 'analytics.drake.edu', 'X-Forwarded-Host': 'analytics.drake.edu', 'X-Forwarded-For': '10.11.1.13,::ffff:127.0.0.1', 'Via': '1.1 analytics.drake.edu', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Referer': 'https://analytics.drake.edu/jupyterhub/hub/login', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.7,ja;q=0.3', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Host': 'analytics.drake.edu'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 90, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/opt/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 74, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found
    
[E 2017-08-22 13:48:16.301 JupyterHub log:99] {
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "Content-Length": "46",
      "Connection": "close",
      "X-Forwarded-Server": "analytics.drake.edu",
      "X-Forwarded-Host": "analytics.drake.edu",
      "X-Forwarded-For": "10.11.1.13,::ffff:127.0.0.1",
      "Via": "1.1 analytics.drake.edu",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Referer": "https://analytics.drake.edu/jupyterhub/hub/login",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.7,ja;q=0.3",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
      "Host": "analytics.drake.edu"
    }
[E 2017-08-22 13:48:16.301 JupyterHub log:100] 500 POST /jupyterhub/hub/login?next= (@::ffff:127.0.0.1) 267.45ms
```

Here are the non-comment contents of the config file, /opt/anaconda3/etc/jupyterhub/config.py:
```
c.JupyterHub.base_url = '/jupyterhub'
c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
c.JupyterHub.pid_file = '/var/run/jupyterhub/jupyterhub.pid'
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.Spawner.default_url = '/home/{username}'
c.Spawner.notebook_dir = '/'
c.PAMAuthenticator.open_sessions = False
```

The systemd configuration for the daemon is:
```
[Unit]
Description=Jupyterhub
After=network-online.target

[Service]
User=jupyterhub
RuntimeDirectory=jupyterhub
Environment=PATH=/opt/anaconda3/bin:/usr/bin
ExecStart=/opt/anaconda3/bin/jupyterhub --config=/opt/anaconda3/etc/jupyterhub/config.py
WorkingDirectory=/opt/anaconda3/etc/jupyterhub

[Install]
WantedBy=multi-user.target
```

The user i've created to run JupyterHub looks like this in /etc/passwd:
```
jupyterhub:x:986:984:JupyterHub daemon:/opt/anaconda3/etc/jupyterhub:/sbin/nologin
```

The sudoers configuration is:
```
Cmnd_Alias JUPYTER_CMD = /opt/anaconda3/bin/sudospawner
jupyterhub ALL=(ALL) NOPASSWD:JUPYTER_CMD
```

I have tested that sudo works:
```
# sudo -u jupyterhub sudo -n -u ramaley /opt/anaconda3/bin/sudospawner --help
Usage: /opt/anaconda3/bin/sudospawner [OPTIONS]
...
# sudo -u jupyterhub /opt/anaconda3/bin/python3 -c "import pamela, getpass; print(pamela.authenticate('ramaley', getpass.getpass()))"
Password: 
None
```
(If i enter a bad password for the last command, i get an error that includes "Authentication failure".)

The only other oddity i can think of is that the users are not local; PAM is configured to look to an LDAP server. When users log in, PAM creates their home directory. The "ramaley" user used in the examples above is an LDAP user. Any ideas?

**Comment by dramaley** [comment]
Update:
```
https://medium.com/@ybarraud/setting-up-jupyterhub-with-sudospawner-and-anaconda-844628c0dbee
```
suggests adding JupyterHub's path to the secure_path in sudoers. So i added this line to my sudoers configuration:
```
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/anaconda3/bin
```
Now i no longer get the 500 errors! Instead, after login, i get a 404.

I'm not sure what to do next. I cranked up the logging a bit and here's an entire session of logging in and seeing the 404:
```
[D 2017-08-24 14:21:56.443 JupyterHub spawner:584] Polling subprocess every 30s
[D 2017-08-24 14:21:56.662 JupyterHub utils:84] Server at http://127.0.0.1:54532/jupyterhub/user/ramaley responded with 302
[I 2017-08-24 14:21:56.662 JupyterHub base:322] User ramaley server took 1.501 seconds to start
[I 2017-08-24 14:21:56.662 JupyterHub orm:188] Adding user ramaley to proxy /jupyterhub/user/ramaley => http://127.0.0.1:54532
[D 2017-08-24 14:21:56.664 JupyterHub orm:146] Fetching POST http://127.0.0.1:8001/api/routes/jupyterhub/user/ramaley
[D 2017-08-24 14:21:56.668 JupyterHub base:236] Setting cookie for ramaley: jupyter-hub-token-ramaley, {}
[D 2017-08-24 14:21:56.671 JupyterHub base:236] Setting cookie for ramaley: jupyter-hub-token, {}
[I 2017-08-24 14:21:56.674 JupyterHub log:100] 302 POST /jupyterhub/hub/login?next= (@::ffff:127.0.0.1) 1597.69ms
[I 2017-08-24 14:21:56.674 JupyterHub login:91] User logged in: ramaley
[D 2017-08-24 14:21:56.775 JupyterHub pages:49] User is running: /jupyterhub/user/ramaley
[D 2017-08-24 14:21:56.775 JupyterHub base:236] Setting cookie for ramaley: jupyter-hub-token-ramaley, {}
[I 2017-08-24 14:21:56.780 JupyterHub log:100] 302 GET /jupyterhub/hub/ (ramaley@::ffff:127.0.0.1) 5.79ms
[I 2017-08-24 14:21:56.941 JupyterHub log:100] 200 GET /jupyterhub/hub/api/authorizations/cookie/jupyter-hub-token-ramaley/[secret] (ramaley@127.0.0.1) 10.71ms
```

The 404 page still displays a header that includes a "Control Panel" button. After waiting a bit, i clicked "Control Panel", "Stop My Server", and "Logout". For what it's worth, those actions produced a few more lines in the log:
```
[I 2017-08-24 14:23:49.867 JupyterHub log:100] 200 GET /jupyterhub/hub/home (ramaley@::ffff:127.0.0.1) 243.04ms
[I 2017-08-24 14:23:52.861 JupyterHub orm:207] Removing user ramaley from proxy
[D 2017-08-24 14:23:52.863 JupyterHub orm:146] Fetching DELETE http://127.0.0.1:8001/api/routes/jupyterhub/user/ramaley
[D 2017-08-24 14:23:53.303 JupyterHub spawner:869] Interrupting 7237
[I 2017-08-24 14:23:53.763 JupyterHub base:388] User ramaley server took 0.901 seconds to stop
[I 2017-08-24 14:23:53.767 JupyterHub log:100] 204 DELETE /jupyterhub/hub/api/users/ramaley/server (ramaley@::ffff:127.0.0.1) 1123.04ms
[I 2017-08-24 14:23:55.803 JupyterHub login:19] User logged out: ramaley
[I 2017-08-24 14:23:55.808 JupyterHub log:100] 302 GET /jupyterhub/hub/logout (ramaley@::ffff:127.0.0.1) 3.99ms
[I 2017-08-24 14:23:55.845 JupyterHub log:100] 302 GET /jupyterhub/hub/ (@::ffff:127.0.0.1) 0.85ms
[I 2017-08-24 14:23:55.878 JupyterHub log:100] 302 GET /jupyterhub/login (@::ffff:127.0.0.1) 0.71ms
[I 2017-08-24 14:23:55.927 JupyterHub log:100] 200 GET /jupyterhub/hub/login (@::ffff:127.0.0.1) 7.45ms
```

Any ideas on what i can check next?

**Comment by minrk** [comment]
On what URL do you see 404? I don't see any 404s logged.

**Comment by dramaley** [comment]
The 404 shows up on the page right after providing credentials. Here's the URL that my browser shows:
https://analytics.drake.edu/jupyterhub/user/ramaley/home/ramaley?

I can capture HTTP headers from the session if that would be helpful.

**Comment by dramaley** [comment]
I checked a process listing and can see that Jupyter runs as my account when i log in:

```
# ps -ef | grep jupyter
ramaley   4710  4709  0 14:31 ?        00:00:01 /opt/anaconda3/bin/python /opt/anaconda3/bin/jupyterhub-singleuser --user="ramaley" --cookie-name="jupyter-hub-token-ramaley" --base-url="/jupyterhub/user/ramaley" --hub-host="" --hub-prefix="/jupyterhub/hub/" --hub-api-url="http://127.0.0.1:8081/jupyterhub/hub/api" --ip="127.0.0.1" --port=51632 --notebook-dir="/" --NotebookApp.default_url="/home/ramaley"
root      4799  4009  0 14:37 pts/2    00:00:00 grep --color=auto jupyter
jupyter+  7311     1  0 Aug24 ?        00:00:30 /opt/anaconda3/bin/python /opt/anaconda3/bin/jupyterhub --config=/opt/anaconda3/etc/jupyterhub/config.py
jupyter+  7315  7311  0 Aug24 ?        00:00:02 node /opt/anaconda3/bin/configurable-http-proxy --ip  --port 8000 --api-ip 127.0.0.1 --api-port 8001 --default-target http://127.0.0.1:8081 --error-target http://127.0.0.1:8081/jupyterhub/hub/error
```

Here's the command that runs as the "ramaley" user, reformatted so arguments are easier to read:

```
/opt/anaconda3/bin/python
 /opt/anaconda3/bin/jupyterhub-singleuser
 --user="ramaley"
 --cookie-name="jupyter-hub-token-ramaley"
 --base-url="/jupyterhub/user/ramaley"
 --hub-host=""
 --hub-prefix="/jupyterhub/hub/"
 --hub-api-url="http://127.0.0.1:8081/jupyterhub/hub/api"
 --ip="127.0.0.1"
 --port=51632
 --notebook-dir="/"
 --NotebookApp.default_url="/home/ramaley"
```

I can confirm that "/home/ramaley" in the last argument is ramaley's home directory. Is there anything else in there that looks amiss? I'm not really sure what exactly i'm looking for.

**Comment by minrk** [comment]
What we probably need is the output of the single-user server. The `extra_log_file` config only captures the Hub's own output, which means that the single-user server output is still going wherever the Hub's stdout/err are going. This could be /var/log/syslog.

I don't generally recommend the use of `extra_log_file` for this reason. Instead, I think it's better to pipe output at the stdout/err level, e.g.

    jupyterhub &>> /var/log/jupyterhub.log

Since you are using systemd, you might be able to access the logs with `journalctl`:

    journalctl -u jupyterhub

Once you have found the output of the jupyterhub process itself, you should see error messages coming from the jupyterhub-singleuser subprocess.

**Comment by dramaley** [comment]
Hello again! I tried to figure out how to get more logs. I was unable to use &>> redirection in the systemd service file, but i did find more logs using the journalctl command.

I added this to the config.py file:
```
c.Spawner.args = ['--debug']
```

After adding that, when i start up JupyterHub and log in, i get the logs below. I can see the --debug in the arguments when it starts jupyterhub-singleuser. I then logged in via the web GUI and saw the 404 error. I don't see 404 reflected in the logs below though. Is there any other way to get more logs? Or is there anything useful in what i was already able to capture? Please note that i did a search/replace of the real host name to "example.com", but otherwise these logs are raw:
```
Sep 06 13:24:28 example.com systemd[1]: Started Jupyterhub.
Sep 06 13:24:28 example.com systemd[1]: Starting Jupyterhub...
Sep 06 13:24:29 example.com jupyterhub[7513]: [I 2017-09-06 13:24:29.095 JupyterHub app:724] Loading cookie_secret from /opt/anaconda3/etc/jupyterhub/jupyterhub_cookie_secret
Sep 06 13:24:29 example.com jupyterhub[7513]: [W 2017-09-06 13:24:29.128 JupyterHub app:365]
Sep 06 13:24:29 example.com jupyterhub[7513]: Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
Sep 06 13:24:29 example.com jupyterhub[7513]: Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
Sep 06 13:24:29 example.com jupyterhub[7513]: [W 2017-09-06 13:24:29.131 JupyterHub app:864] No admin users, admin interface will be unavailable.
Sep 06 13:24:29 example.com jupyterhub[7513]: [W 2017-09-06 13:24:29.131 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
Sep 06 13:24:29 example.com jupyterhub[7513]: [I 2017-09-06 13:24:29.132 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
Sep 06 13:24:29 example.com jupyterhub[7513]: [I 2017-09-06 13:24:29.159 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/jupyterhub/hub/
Sep 06 13:24:29 example.com jupyterhub[7513]: [W 2017-09-06 13:24:29.162 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
Sep 06 13:24:29 example.com jupyterhub[7513]: [I 2017-09-06 13:24:29.163 JupyterHub app:1176] Starting proxy @ http://*:8000/jupyterhub/
Sep 06 13:24:29 example.com jupyterhub[7513]: 13:24:29.281 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
Sep 06 13:24:29 example.com jupyterhub[7513]: 13:24:29.287 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
Sep 06 13:24:29 example.com jupyterhub[7513]: 13:24:29.288 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
Sep 06 13:24:29 example.com jupyterhub[7513]: [I 2017-09-06 13:24:29.367 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/jupyterhub/
Sep 06 13:25:58 example.com python[7513]: pam_sss(login:auth): authentication success; logname= uid=986 euid=986 tty= ruser= rhost= user=ramaley
Sep 06 13:25:58 example.com sudo[7544]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 170906 13:25:59 mediator:89] Spawning /opt/anaconda3/bin/jupyterhub-singleuser '--user="ramaley"' '--cookie-name="jupyter-hub-token-ramaley"' '--base-url="/jupyterhub/user/ramaley"' '--hub-host=""' '--hub-prefix="/jupyterhub/hub/"' '--hub-api-url="http://127.0.0.1:8081/jupyterhub/hub/api"' '--ip="127.0.0.1"' --port=60064 '--notebook-dir="/"' '--NotebookApp.default_url="/home/ramaley"' --debug
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.336 ramaley application:178] Searching ['/home/ramaley', '/home/ramaley/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.337 ramaley application:555] Looking for jupyter_config in /etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.337 ramaley application:555] Looking for jupyter_config in /usr/local/etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.337 ramaley application:555] Looking for jupyter_config in /opt/anaconda3/etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.337 ramaley application:555] Looking for jupyter_config in /home/ramaley/.jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.337 ramaley application:555] Looking for jupyter_config in /home/ramaley
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.338 ramaley application:555] Looking for jupyter_notebook_config in /etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.338 ramaley application:555] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.339 ramaley application:555] Looking for jupyter_notebook_config in /opt/anaconda3/etc/jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.339 ramaley application:555] Looking for jupyter_notebook_config in /home/ramaley/.jupyter
Sep 06 13:26:00 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.339 ramaley application:555] Looking for jupyter_notebook_config in /home/ramaley
Sep 06 13:26:00 example.com jupyterhub[7513]: [W 2017-09-06 13:26:00.364 ramaley login:225] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.374 ramaley notebookapp:1366] Serving notebooks from local directory: /
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.374 ramaley notebookapp:1366] 0 active kernels
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.374 ramaley notebookapp:1366] The Jupyter Notebook is running at: http://127.0.0.1:60064/jupyterhub/user/ramaley/
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.374 ramaley notebookapp:1367] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.388 ramaley log:47] 302 GET /jupyterhub/user/ramaley (127.0.0.1) 0.55ms
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.389 JupyterHub base:322] User ramaley server took 1.506 seconds to start
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.389 JupyterHub orm:188] Adding user ramaley to proxy /jupyterhub/user/ramaley => http://127.0.0.1:60064
Sep 06 13:26:00 example.com jupyterhub[7513]: 13:26:00.394 - info: [ConfigProxy] Adding route /jupyterhub/user/ramaley -> http://127.0.0.1:60064
Sep 06 13:26:00 example.com jupyterhub[7513]: 13:26:00.396 - info: [ConfigProxy] 201 POST /api/routes/jupyterhub/user/ramaley
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.401 JupyterHub log:100] 302 POST /jupyterhub/hub/login?next= (@::ffff:127.0.0.1) 1602.85ms
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.401 JupyterHub login:91] User logged in: ramaley
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.479 JupyterHub log:100] 302 GET /jupyterhub/hub/ (ramaley@::ffff:127.0.0.1) 5.13ms
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.538 ramaley log:47] 302 GET /jupyterhub/user/ramaley (::ffff:127.0.0.1) 0.47ms
Sep 06 13:26:00 example.com jupyterhub[7513]: [I 2017-09-06 13:26:00.603 JupyterHub log:100] 200 GET /jupyterhub/hub/api/authorizations/cookie/jupyter-hub-token-ramaley/[secret] (ramaley@127.0.0.1) 16.69ms
```

After logging in, i waited a bit, used the GUI to stop my single user server, and logged out. The logs from those actions are below.
```
Sep 06 13:26:30 example.com sudo[7560]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:27:00 example.com sudo[7568]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:27:30 example.com sudo[7572]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:00 example.com sudo[7576]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:30 example.com sudo[7580]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:55 example.com sudo[7591]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.596 ramaley auth:190] Received request from Hub user {'name': 'ramaley', 'admin': False, 'groups': [], 'server': '/jupyterhub/user/ramaley', 'pending': None, 'last_activity': '2017-09-06T18:26:00.172197'}
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.596 ramaley auth:286] Allowing whitelisted Hub user ramaley
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.596 ramaley handlers:210] Using contents: services/contents
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.621 ramaley handlers:591] Path base/images/favicon.ico served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/base/images/favicon.ico
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.622 ramaley handlers:591] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.622 ramaley handlers:591] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/jquery-typeahead/dist/jquery.typeahead.min.css
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.622 ramaley handlers:591] Path style/style.min.css served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/style/style.min.css
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.623 ramaley handlers:591] Path components/es6-promise/promise.min.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/es6-promise/promise.min.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.623 ramaley handlers:591] Path components/preact/index.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/preact/index.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.623 ramaley handlers:591] Path components/proptypes/index.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/proptypes/index.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.624 ramaley handlers:591] Path components/preact-compat/index.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/preact-compat/index.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.624 ramaley handlers:591] Path components/requirejs/require.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/requirejs/require.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [W 2017-09-06 13:26:00.624 ramaley log:47] 404 GET /jupyterhub/user/ramaley/home/ramaley? (::ffff:127.0.0.1) 49.93ms referer=https://analytics.drake.edu/jupyterhub/hub/login
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.875 ramaley handlers:591] Path custom.css served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/custom/custom.css
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:00.877 ramaley log:47] 304 GET /jupyterhub/user/ramaley/custom/custom.css (::ffff:127.0.0.1) 1.54ms
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:01.329 ramaley handlers:591] Path components/jquery/jquery.min.js served from /opt/anaconda3/lib/python3.6/site-packages/notebook/static/components/jquery/jquery.min.js
Sep 06 13:28:56 example.com jupyterhub[7513]: [D 2017-09-06 13:26:01.330 ramaley log:47] 200 GET /jupyterhub/user/ramaley/static/components/jquery/jquery.min.js?v=20170906132600 (::ffff:127.0.0.1) 1.26ms
Sep 06 13:28:56 example.com jupyterhub[7513]: [I 2017-09-06 13:28:56.041 JupyterHub log:100] 200 GET /jupyterhub/hub/home (ramaley@::ffff:127.0.0.1) 245.54ms
Sep 06 13:28:57 example.com sudo[7594]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:57 example.com jupyterhub[7513]: [I 2017-09-06 13:28:57.629 JupyterHub orm:207] Removing user ramaley from proxy
Sep 06 13:28:57 example.com jupyterhub[7513]: 13:28:57.633 - info: [ConfigProxy] Removing route /jupyterhub/user/ramaley
Sep 06 13:28:57 example.com jupyterhub[7513]: 13:28:57.634 - info: [ConfigProxy] 204 DELETE /api/routes/jupyterhub/user/ramaley
Sep 06 13:28:57 example.com sudo[7597]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:57 example.com sudo[7600]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:58 example.com sudo[7603]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:58 example.com sudo[7606]: jupyterhub : TTY=unknown ; PWD=/opt/anaconda3/etc/jupyterhub ; USER=ramaley ; COMMAND=/opt/anaconda3/bin/sudospawner
Sep 06 13:28:58 example.com jupyterhub[7513]: [I 2017-09-06 13:28:58.266 ramaley notebookapp:1419] Interrupted...
Sep 06 13:28:58 example.com jupyterhub[7513]: [I 2017-09-06 13:28:58.267 ramaley notebookapp:1308] Shutting down kernels
Sep 06 13:28:58 example.com jupyterhub[7513]: [I 2017-09-06 13:28:58.526 JupyterHub base:388] User ramaley server took 0.896 seconds to stop
Sep 06 13:28:58 example.com jupyterhub[7513]: [I 2017-09-06 13:28:58.530 JupyterHub log:100] 204 DELETE /jupyterhub/hub/api/users/ramaley/server (ramaley@::ffff:127.0.0.1) 1120.53ms
Sep 06 13:28:59 example.com jupyterhub[7513]: [I 2017-09-06 13:28:59.800 JupyterHub login:19] User logged out: ramaley
Sep 06 13:28:59 example.com jupyterhub[7513]: [I 2017-09-06 13:28:59.804 JupyterHub log:100] 302 GET /jupyterhub/hub/logout (ramaley@::ffff:127.0.0.1) 3.84ms
Sep 06 13:28:59 example.com jupyterhub[7513]: [I 2017-09-06 13:28:59.924 JupyterHub log:100] 302 GET /jupyterhub/hub/ (@::ffff:127.0.0.1) 0.86ms
Sep 06 13:29:00 example.com jupyterhub[7513]: [I 2017-09-06 13:29:00.014 JupyterHub log:100] 302 GET /jupyterhub/login (@::ffff:127.0.0.1) 0.76ms
Sep 06 13:29:00 example.com jupyterhub[7513]: [I 2017-09-06 13:29:00.103 JupyterHub log:100] 200 GET /jupyterhub/hub/login (@::ffff:127.0.0.1) 7.71ms
```

**Comment by minrk** [comment]
Aha! The 404 is because `/home/ramalay` doesn't exist as a URL. it needs to be `/tree/home/{username}/` to get to the directory listing.

**Comment by dramaley** [comment]
OK! I wasn't sure what you meant, so first i did "ln -s / /tree" so that in the filesystem, /tree/home/ramaley would work. That didn't help. So then i tried logging in and changing the URL in my browser to add /tree in there... that worked!

I wasn't sure how to get the login process to automatically add /tree to the URL, but looked through the config.py file again and found "c.Spawner.default_url" -- after adding /tree as part of that, everything seems to be working!

So this turned out to be a configuration error. But it is fixed now. Thank you for the help!
