### ISSUE TITLE
Getting error for few users while loggin to jupyter and it is getting hung

### ISSUE THREAD

**Issue by uttamkumar123** [jupyterhub/jupyterhub#1372]
We have a jupyter setup using Anaconda3 (Anaconda3-2.4.1). We started seeing a recent issue with some of the users when they login to jupyter hub, as This Session's transaction has been rolled back due to a previous exception during flush and then jupyter hub though process is still running and the ui gets hung for all users.

**How to reproduce the issue**
This issue is very intermittent. We take care in our jupyterhub startup script, to cleanup any stale processess of jupyterhub and configurable-http-proxy, but for some reason, it just hangs and i always see address already in use error. Sometimes, even after restarting , i will be able to login, but the user who reported the issue, tries it and it again hang without getting him login even a single time. So , we also tries to delete .jupyter and .ipython folder in their hoe dir to clear any notebook/jupyter cache, holding any session and then it fixes. As of now we have been trying these trial and error method , but not able to reach to a permanent fix.

**Share what version of JupyterHub you are using**
Jupyterhub - 0.7.0
configurable-http-proxy - 1.3.1

Error logs 👍 
Sequence of event logs -

```
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
% self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xcozkan', 'base_url': '/user/*****'}]]

sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xmo8n7n5', 'base_url': '/user/xmo8n7n5'}]]
```

Complete error:

```
E 2017-06-08 14:28:05.483 JupyterHub http1connection:54] Uncaught exception
Traceback (most recent call last):
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/http1connection.py", line 238, in read_message
delegate.finish()
**self.handler_kwargs)
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 181, in init
self.clear()
File "/opt/anaconda3/lib/python3.5/site-packages/tornado/web.py", line 285, in clear
self.set_default_headers()
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 123, in set_default_headers
headers.setdefault("Content-Security-Policy", self.content_security_policy)
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 113, in content_security_policy
"report-uri " + self.csp_report_uri,
File "/opt/anaconda3/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 102, in csp_report_uri
url_path_join(self.hub.server.base_url, 'security/csp-report')
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in get
return self.impl.get(instance_state(instance), dict)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
value = self.callable_(state, passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 514, in _load_for_state
passive
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 550, in _get_ident_for_use_get
for pk in self.mapper.primary_key
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 550, in 
for pk in self.mapper.primary_key
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 2455, in get_state_attr_by_column
return state.manager[prop.key].impl.get(state, dict, passive=passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
value = state._load_expired(state, passive)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
self.manager.deferred_scalar_loader(self, toload)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 664, in load_scalar_attributes
only_load_props=attribute_names)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
return q.one()
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2528, in one
ret = list(self)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2571, in iter
return self._execute_and_instances(context)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
close_with_result=True)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
**kw)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 893, in connection
execution_options=execution_options)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
engine, execution_options)
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
self._assert_active()
File "/opt/anaconda3/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
% self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (builtins.OSError) [Errno 98] Address already in use [SQL: 'INSERT INTO servers (proto, ip, port, base_url, cookie_name) VALUES (?, ?, ?, ?, ?)'] [parameters: [{'cookie_name': 'jupyter-hub-token-xmo8n7n5', 'base_url': '/user/xmo8n7n5'}]]
```

**Comment by minrk** [comment]
I think we don't properly reset the db session when an error like this occurs. I'm not sure how the EADDRINUSE could enter into it, though. That seems rather odd. What sql driver are you using?

**Comment by uttamkumar123** [comment]
Dev team usually run spark jobs in our bigdata env using jupyter notebook and storing data into hive db. I dont thing they are using any sql driver while running it.

My question is , do you see any issue with the jupyterhub version i am using or should i upgrade ?

**Comment by uttamkumar123** [comment]
Sometime even when a user is trying to login and not running any notebook, this error happens.

**Comment by willingc** [comment]
Hi @uttamkumar123,

> My question is , do you see any issue with the jupyterhub version i am using or should i upgrade ?

I recommend upgrading to 0.7.2 or 0.8.0b5. There have been many updates since 0.7.0.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
