### ISSUE TITLE
OAuth errors when users try to log in

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1398]
For a small fraction of users, we run into errors like the following:

```
E 2017-09-04 07:00:38.076 JupyterHub web:1590] Uncaught exception GET /hub/oauth_callback?state=<state>&authuser=0&hd=berkeley.edu&session_state=b<session-state>9&prompt=none (10.240.0.7)
    HTTPServerRequest(protocol='http', host='datahub.berkeley.edu', method='GET', uri='/hub/oauth_callback?state=<state>&prompt=none', version='HTTP/1.1', remote_ip='10.240.0.7', headers={'X-Forwarded-Port': '80', 'Connection': 'close', 'X-Forwarded-For': '10.240.0.7', 'X-Forwarded-Host': 'datahub.berkeley.edu', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'X-Forwarded-Proto': 'http', 'Accept-Encoding': 'gzip, deflate', 'Cookie': 'oauthenticator-state=2|1:0|10:1504508409|20:oauthenticator-state|304:<state>', 'Host': 'datahub.berkeley.edu', 'Accept-Language': 'en-US,en;q=0.8,ko;q=0.6'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/oauthenticator/oauth2.py", line 183, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 327, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/auth.py", line 221, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.5/dist-packages/oauthenticator/google.py", line 63, in authenticate
        self._OAUTH_USERINFO_URL + '?access_token=' + access_token
    tornado.httpclient.HTTPError: HTTP 500: Internal Server Error

[E 2017-09-04 07:00:38.078 JupyterHub log:114] {
      "X-Forwarded-Port": "80",
      "Connection": "close",
      "X-Forwarded-For": "10.240.0.7",
      "X-Forwarded-Host": "datahub.berkeley.edu",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "X-Forwarded-Proto": "http",
      "Accept-Encoding": "gzip, deflate",
      "Cookie": "oauthenticator-state=2|1:0|10:1504508409|20:oauthenticator-state|304:<state>",
      "Host": "datahub.berkeley.edu",
      "Accept-Language": "en-US,en;q=0.8,ko;q=0.6"
    }
```

Then they can't access their server at all for a while.

**Comment by minrk** [comment]
If I read it correctly, that's a 500 error from google's own server (note that it's httpclient, meaning a request *from* JupyterHub failed with 500).

I'm not sure how much we can do when Google OAuth isn't working other than tell users to come back later.

**Comment by richmoore1962** [comment]
Would like to have this

**Comment by richmoore1962** [comment]
Need help loading this wife cheating on me please help me with this se says I'm crazy but in not

**Comment by willingc** [comment]
@minrk @yuvipanda I'm closing this. Feel free to reopen if needed.
