### ISSUE TITLE
Commit 71378d2 Breaks GitHub Authentication

### ISSUE THREAD

**Issue by tjcrone** [jupyterhub/jupyterhub#1410]
Hello. I decided to get back up to speed with the development of JupyterHub, and I noticed that commit 71378d2 breaks my authentication using the LocalGitHubOAuthenticator. Any idea what is going on? Thanks!

**How to reproduce the issue**

Move from f5d0855 to 71378d2

**What you expected to happen**

I expected log in to my JupyterHub account

**What actually happens**

500: Internal Server Error

**Share what version of JupyterHub you are using**

71378d2

**Output from  `jupyter --debug`**

```

[E 2017-09-11 09:36:23.739 JupyterHub web:1548] Uncaught exception GET /jupyter/hub/oauth_callback?code=45461ffa7f082a41e34b (10.0.0.1)
    HTTPServerRequest(protocol='https', host='server.org', method='GET', uri='/jupyter/hub/oauth_callback?code=45461ffa7f082a41e34b', version='HTTP/1.1', remote_ip='10.0.0.1', headers={'X-Forwarded-Proto': 'https', 'Cookie': '_xsrf=2|39bed59a|b7837492eb5461ffa8edb42066315219|8473920468; __utma=130943570.400335978.1501800110.1502571750.1503064596.4; __utmz=130943570.1503064596.4.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.400335978.1501800110; __utma=227718799.400335978.1501800110.1504611955.1504611955.1; __utmz=227718799.1504611955.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); tomato_menu_status=overview.asp; tomato_status_overview_refresh=3; tomato_menu_forward=basic.asp', 'Referer': 'https://server.org/jupyter/hub/login', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'X-Forwarded-Host': 'server.org', 'Connection': 'close', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'en-US,en;q=0.8', 'X-Forwarded-For': '10.0.0.1,127.0.0.1', 'Accept-Encoding': 'gzip, deflate, br', 'X-Real-Ip': '10.0.0.1', 'Host': 'server.org', 'X-Forwarded-Port': '443'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/oauthenticator/oauth2.py", line 54, in get
        user = self.user_from_username(username)
      File "/usr/local/src/jupyterhub/jupyterhub/handlers/base.py", line 230, in user_from_username
        user = self.find_user(username)
      File "/usr/local/src/jupyterhub/jupyterhub/handlers/base.py", line 225, in find_user
        orm_user = orm.User.find(db=self.db, name=name)
      File "/usr/local/src/jupyterhub/jupyterhub/orm.py", line 178, in find
        return db.query(cls).filter(cls.name == name).first()
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
        ret = list(self[0:1])
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
        return list(res)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
        return self._execute_and_instances(context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
        context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
        context)
      File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.InterfaceError: <unprintable InterfaceError object>

```

**Comment by tjcrone** [comment]
I figured it out. I had to pip upgrade oauthenticator. Cheers.
