### ISSUE TITLE
[Question] Which format is expected for SSL-keys?

### ISSUE THREAD

**Issue by inkrement** [jupyterhub/jupyterhub#1436]
Hi, this is just a question. I try to deploy jupyterhub with SSL, but I get the following startup-error:

```
_tls_common.js:90
        c.context.setKey(options.key);
                  ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:90:19)
    at Server (_tls_wrap.js:749:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:47:10)
    at new ConfigurableProxy (/opt/conda/lib/node_modules/configurable-http-proxy/lib/configproxy.js:174:35)
    at Object.<anonymous> (/opt/conda/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:189:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

So I guess the private.key file has the wrong format. At the moment it is a RSA-file. What is expected? And how can I convert it?

**Comment by minrk** [comment]
I think it should be PEM format, as produced by:

    openssl genrsa -out my.key 2048

**Comment by inkrement** [comment]
thanks!
