### ISSUE TITLE
My solution with Spawner failed to start (500 error) (zmq) issue

### ISSUE THREAD

**Issue by colingoldberg** [jupyterhub/jupyterhub#1452]
This post is just in case someone else has the same problem - it now seems to be running for me.

Problem: 
After successfully logging in, getting error message "Spawner failed to start [status=1]"
In summary: Jupyter stdout/stderr on server shows:
File "/usr/local/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'"

Solution:
I uninstalled pyzmq and reinstalled it
ie.
- pip3 uninstall pyzmq
 - Successfully uninstalled pyzmq-16.0.2
- pip3 install pyzmq
 - Successfully installed pyzmq-16.0.2
As you can see, the pyzmq version was unchanged.

I then reran jupyter - as above - and it worked!

I hope this helps to save time for anyone who has the same symptoms.

Regards

Colin Goldberg

My Details:
**How to reproduce the issue**
- Add a unix user and password for testing jupyter
- Whitelist the unix user in jupyterhub_config.py
- Run jupyter -f /path/to/jupyterhub_config.py --debug (no ssl)
- Access jupyter at http://<server ip>:8000
- Log in with username and password

**What actually happens**
- Browser error message "Spawner failed to start [status=1]"
- Server output:
```
[I 2017-09-26 15:27:53.794 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-09-26 15:27:53.798 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-09-26 15:27:53.798 JupyterHub app:1176] Starting proxy @ http://*:8000/
[D 2017-09-26 15:27:53.798 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
15:27:53.910 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
15:27:53.919 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
15:27:53.920 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py:39: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54360), raddr=('127.0.0.1', 8000)>
  socket.create_connection((ip, port))
/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py:39: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 54362), raddr=('127.0.0.1', 8000)>
  socket.create_connection((ip, port))
/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py:39: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 46920), raddr=('127.0.0.1', 8001)>
  socket.create_connection((ip, port))
/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py:39: ResourceWarning: unclosed <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 46922), raddr=('127.0.0.1', 8001)>
  socket.create_connection((ip, port))
[D 2017-09-26 15:27:54.004 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-09-26 15:27:54.005 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
[I 2017-09-26 15:28:24.450 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="jupusr"' '--cookie-name="jupyter-hub-token-jupusr"' '--base-url="/user/jupusr"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=36081
[D 2017-09-26 15:28:24.457 JupyterHub spawner:584] Polling subprocess every 30s
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 30, in <module>
    from notebook.notebookapp import (
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/usr/local/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/usr/local/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/local/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/local/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
[W 2017-09-26 15:28:34.478 JupyterHub web:1587] 500 POST /hub/login?next= (::ffff:69.122.41.67): Spawner failed to start [status=1]
[D 2017-09-26 15:28:34.482 JupyterHub base:462] No template for 500
[E 2017-09-26 15:28:34.529 JupyterHub log:99] {
      "X-Forwarded-Host": "<server ip>:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:69.122.41.67",
      "Accept-Language": "en-US,en;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://<server ip>:8000/hub/login?next=",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "http://<server ip>:8000",
      "Cache-Control": "max-age=0",
      "Content-Length": "36",
      "Connection": "close",
      "Host": "<server ip>:8000"
    }
[E 2017-09-26 15:28:34.529 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:69.122.41.67) 10130.81ms
[W 2017-09-26 15:28:54.522 JupyterHub user:278] jupusr's server never showed up at http://127.0.0.1:36081/user/jupusr after 30 seconds. Giving up
[E 2017-09-26 15:28:54.536 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f913efc4398> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 294, in spawn
        raise e
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 270, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:36081/user/jupusr didn't respond in 30 seconds

```

**Share what version of JupyterHub you are using**
# jupyter --version
4.3.0

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

$PATH:
	/usr/local/bin
	/root/.nvm/versions/node/v7.7.3/bin
	/sbin
	/bin
	/usr/sbin
	/usr/bin
	/opt/aws/bin
	/usr/local/bin
	/usr/local/share/spark-2.2.0-bin-hadoop2.7/bin

sys.path:
	/usr/local/bin
	/var/app/current/ml/libs
	/usr/local/lib/python36.zip
	/usr/local/lib/python3.6
	/usr/local/lib/python3.6/lib-dynload
	/root/.local/lib/python3.6/site-packages
	/usr/local/lib/python3.6/site-packages

sys.executable:
	/usr/local/bin/python3.6

sys.version:
	3.6.2 (default, Sep 25 2017, 14:46:07) 
	[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

platform.platform():
	Linux-4.4.51-40.58.amzn1.x86_64-x86_64-with-glibc2.9

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	aws-cfn-bootstrap (1.4)
	awscli (1.11.132)
	Babel (0.9.4)
	backports.ssl-match-hostname (3.4.0.2)
	boto (2.42.0)
	botocore (1.5.95)
	bzr (2.6.0)
	chardet (2.0.1)
	cloud-init (0.7.6)
	colorama (0.2.5)
	configobj (4.7.2)
	configparser (3.5.0)
	docutils (0.11)
	ecdsa (0.11)
	enum34 (1.1.6)
	flake8 (3.4.1)
	futures (3.0.3)
	iniparse (0.3.1)
	javabridge (1.0.14)
	Jinja2 (2.7.2)
	jmespath (0.9.2)
	jsonpatch (1.2)
	jsonpointer (1.0)
	kitchen (1.1.1)
	liac-arff (2.1.1)
	lockfile (0.8)
	MarkupSafe (0.11)
	mccabe (0.6.1)
	mercurial (4.2.3)
	mysql-connector-python (2.1.6)
	numpy (1.12.1)
	pandas (0.20.1)
	paramiko (1.15.1)
	PIL (1.1.6)
	pip (9.0.1)
	ply (3.4)
	pyasn1 (0.1.7)
	pycodestyle (2.3.1)
	pycrypto (2.6.1)
	pycurl (7.19.0)
	pyflakes (1.5.0)
	pygpgme (0.3)
	pyliblzma (0.5.3)
	pystache (0.5.3)
	python-daemon (1.5.2)
	python-dateutil (2.1)
	python-weka-wrapper (0.3.10)
	pytz (2017.2)
	pyxattr (0.5.0)
	PyYAML (3.10)
	requests (1.2.3)
	rsa (3.4.1)
	scikit-learn (0.18.1)
	scipy (0.19.0)
	setuptools (12.2)
	simplejson (3.6.5)
	six (1.8.0)
	sklearn (0.0)
	urlgrabber (3.10)
	urllib3 (1.8.2)
	virtualenv (12.0.7)
	yum-metadata-parser (1.1.4)

```

**Comment by colingoldberg** [comment]
I am closing this because I only reported this as a possible solution for anyone else who has the same symptoms.
