### ISSUE TITLE
Exception when logout with auto_login=True

### ISSUE THREAD

**Issue by ktong** [jupyterhub/jupyterhub#1453]
**How to reproduce the issue**
Press logout button

**What you expected to happen**
Shows logout.html

**What actually happens**
Exception:
```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/login.py", line 23, in get
        self.render('logout.html')
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 724, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 857, in render_string
        if template_path not in RequestHandler._template_loaders:
    TypeError: unhashable type: 'list'
```

**Share what version of JupyterHub you are using**
Jupyterhub 0.8 with auto_login=True

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/srv/jupyterhub
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.3 (default, Jan 19 2017, 14:11:04)
	[GCC 6.3.0 20170118]

platform.platform():
	Linux-4.4.52+-x86_64-with-Ubuntu-17.04-zesty

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter
```

**Comment by minrk** [comment]
Thanks! Fixed by #1454
