### ISSUE TITLE
Users not able to use jupyterhub notebooks

### ISSUE THREAD

**Issue by will17cr** [jupyterhub/jupyterhub#1479]
**How to reproduce the issue**
jupyterhub installed in Ubuntu 17.04 by admin user
configured with jupyterhub_config.py

Installed via pip3, not anaconda, easy_install or any other
installed with the command sudo pip3 install jupyterhub
regular command pip3 install... did not work, got Errorno 13 permission denied to dist-packages in /usr/local/lib/python3.5/

**What you expected to happen**
In appearance it seemed to be working ok
It was possible to run jupyterhub, it worked the ssl and key config in the config file

In a remote host it was possible to open jupyterhub url, login with any user and navigate through folders

**What actually happens**
Problem is that any user but admin (user that have sudo privileges and installed everything) had issues opening a notebook and creating a notebook

If admin user opens a notebook kernel get ready and on,
if admin user creates a notebook there are no issues, new notebook is shown, kernel is activated and ready to proceed

If any user but admin opens or creates a notebook kernel tries to start and crash entering in a loop of "trying to restart".
In the server side several tries and errors are logged: 

```
will@splat:/usr/local/etc/jupyterhub$ sudo jupyterhub
[I 2017-10-12 17:09:13.494 JupyterHub app:849] Loading cookie_secret from /usr/local/etc/jupyterhub/jupyterhub_cookie_secret
[W 2017-10-12 17:09:13.506 JupyterHub app:966] No admin users, admin interface will be unavailable.
[W 2017-10-12 17:09:13.506 JupyterHub app:967] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-10-12 17:09:13.506 JupyterHub app:994] Not using whitelist. Any authenticated user will be allowed.
[I 2017-10-12 17:09:13.539 JupyterHub app:1539] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-10-12 17:09:13.539 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2017-10-12 17:09:13.540 JupyterHub proxy:458] Starting proxy @ https://*:8000/
17:09:13.639 - info: [ConfigProxy] Proxying https://*:8000 to (no default)
17:09:13.641 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
17:09:13.668 - info: [ConfigProxy] 200 GET /api/routes 
[W 2017-10-12 17:09:13.668 JupyterHub proxy:304] Adding missing default route
[I 2017-10-12 17:09:13.668 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
17:09:13.677 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
17:09:13.678 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2017-10-12 17:09:13.678 JupyterHub app:1592] JupyterHub is now running at https://:8000/
[I 2017-10-12 17:09:25.384 JupyterHub log:122] 302 GET / → /hub (@::ffff:172.17.2.118) 0.57ms
[I 2017-10-12 17:09:25.402 JupyterHub log:122] 302 GET /hub → /hub/login (@::ffff:172.17.2.118) 0.58ms
[W 2017-10-12 17:09:25.413 JupyterHub base:208] Invalid cookie token
[W 2017-10-12 17:09:25.416 JupyterHub base:208] Invalid cookie token
[W 2017-10-12 17:09:25.435 JupyterHub base:208] Invalid cookie token
[I 2017-10-12 17:09:25.435 JupyterHub log:122] 200 GET /hub/login (@::ffff:172.17.2.118) 23.48ms
[I 2017-10-12 17:09:33.630 JupyterHub base:345] User logged in: daer
Last login: Thu Oct 12 16:44:45 CST 2017
Welcome to Ubuntu 17.04 (GNU/Linux 4.10.0-37-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * What are your preferred Linux desktop apps?  Help us set the default
   desktop apps in Ubuntu 18.04 LTS:
   - https://ubu.one/apps1804

0 packages can be updated.
0 updates are security updates.

[I 2017-10-12 17:09:33.980 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=54995 '--notebook-dir="~/notebooks"'
[I 2017-10-12 17:09:34.387 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.0
[I 2017-10-12 17:09:34.389 JupyterHub log:122] 200 GET /hub/api (@127.0.0.1) 0.50ms
[I 2017-10-12 17:09:34.390 SingleUserNotebookApp notebookapp:1441] Serving notebooks from local directory: /home/daer/notebooks
[I 2017-10-12 17:09:34.390 SingleUserNotebookApp notebookapp:1441] 0 active kernels
[I 2017-10-12 17:09:34.390 SingleUserNotebookApp notebookapp:1441] The Jupyter Notebook is running at:
[I 2017-10-12 17:09:34.390 SingleUserNotebookApp notebookapp:1441] http://127.0.0.1:54995/user/daer/
[I 2017-10-12 17:09:34.390 SingleUserNotebookApp notebookapp:1442] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2017-10-12 17:09:34.820 SingleUserNotebookApp log:122] 302 GET /user/daer/ → /user/daer/tree? (@127.0.0.1) 1.19ms
[I 2017-10-12 17:09:34.821 JupyterHub base:446] User daer took 1.191 seconds to start
[I 2017-10-12 17:09:34.825 JupyterHub proxy:231] Adding user daer to proxy /user/daer/ => http://127.0.0.1:54995
17:09:34.827 - info: [ConfigProxy] Adding route /user/daer -> http://127.0.0.1:54995
17:09:34.827 - info: [ConfigProxy] 201 POST /api/routes/user/daer 
[I 2017-10-12 17:09:34.828 JupyterHub log:122] 302 POST /hub/login?next= → /hub/ (@::ffff:172.17.2.118) 1216.92ms
[I 2017-10-12 17:09:34.845 JupyterHub log:122] 302 GET /hub/ → /user/daer/ (daer@::ffff:172.17.2.118) 3.18ms
[I 2017-10-12 17:09:34.856 SingleUserNotebookApp log:122] 302 GET /user/daer/ → /user/daer/tree? (@::ffff:172.17.2.118) 0.36ms
[I 2017-10-12 17:09:34.866 SingleUserNotebookApp log:122] 302 GET /user/daer/tree? → /hub/api/oauth2/authorize?redirect_uri=%2Fuser%2Fdaer%2Foauth_callback&client_id=user-daer&response_type=code&state=eyJuZXh0X3VybCI6ICIvdXNlci9kYWVyL3RyZWU_IiwgInV1aWQiOiAiZjJlNmFiOTc4Y2YwNDRmOGFkOTA3MDVlODg2ODI5ZGMifQ (@::ffff:172.17.2.118) 2.21ms
[I 2017-10-12 17:09:34.992 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?redirect_uri=%2Fuser%2Fdaer%2Foauth_callback&client_id=user-daer&response_type=code&state=eyJuZXh0X3VybCI6ICIvdXNlci9kYWVyL3RyZWU_IiwgInV1aWQiOiAiZjJlNmFiOTc4Y2YwNDRmOGFkOTA3MDVlODg2ODI5ZGMifQ → /user/daer/oauth_callback?code=af7010ed-2268-4982-8963-852f40a5a637&state=eyJuZXh0X3VybCI6ICIvdXNlci9kYWVyL3RyZWU_IiwgInV1aWQiOiAiZjJlNmFiOTc4Y2YwNDRmOGFkOTA3MDVlODg2ODI5ZGMifQ (daer@::ffff:172.17.2.118) 114.33ms
[I 2017-10-12 17:09:35.208 JupyterHub log:122] 200 POST /hub/api/oauth2/token (daer@127.0.0.1) 198.96ms
[I 2017-10-12 17:09:35.212 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (daer@127.0.0.1) 3.29ms
[I 2017-10-12 17:09:35.212 SingleUserNotebookApp auth:818] Logged-in user {'last_activity': '2017-10-12T23:09:33.991736', 'groups': [], 'name': 'daer', 'server': '/user/daer/', 'admin': False, 'pending': None, 'kind': 'user'}
[I 2017-10-12 17:09:35.213 SingleUserNotebookApp log:122] 302 GET /user/daer/oauth_callback?code=af7010ed-2268-4982-8963-852f40a5a637&state=eyJuZXh0X3VybCI6ICIvdXNlci9kYWVyL3RyZWU_IiwgInV1aWQiOiAiZjJlNmFiOTc4Y2YwNDRmOGFkOTA3MDVlODg2ODI5ZGMifQ → /user/daer/tree? (@::ffff:172.17.2.118) 210.92ms
[I 2017-10-12 17:09:35.231 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (daer@127.0.0.1) 2.55ms
[I 2017-10-12 17:09:35.269 SingleUserNotebookApp log:122] 200 GET /user/daer/tree? (daer@::ffff:172.17.2.118) 42.34ms
[I 2017-10-12 17:09:35.714 SingleUserNotebookApp log:122] 200 GET /user/daer/api/config/common?_=1507849783260 (daer@::ffff:172.17.2.118) 5.76ms
[I 2017-10-12 17:09:35.718 SingleUserNotebookApp log:122] 200 GET /user/daer/api/config/tree?_=1507849783259 (daer@::ffff:172.17.2.118) 2.38ms
[I 2017-10-12 17:09:35.728 SingleUserNotebookApp log:122] 200 GET /user/daer/api/terminals?_=1507849783261 (daer@::ffff:172.17.2.118) 0.64ms
[I 2017-10-12 17:09:35.741 SingleUserNotebookApp log:122] 200 GET /user/daer/api/kernelspecs (daer@::ffff:172.17.2.118) 3.50ms
[I 2017-10-12 17:09:35.743 SingleUserNotebookApp log:122] 200 GET /user/daer/api/terminals?_=1507849783263 (daer@::ffff:172.17.2.118) 0.85ms
[I 2017-10-12 17:09:35.746 SingleUserNotebookApp log:122] 200 GET /user/daer/api/sessions?_=1507849783262 (daer@::ffff:172.17.2.118) 2.17ms
[I 2017-10-12 17:09:36.342 SingleUserNotebookApp log:122] 200 GET /user/daer/api/contents?type=directory&_=1507849783264 (daer@::ffff:172.17.2.118) 4.54ms
[I 2017-10-12 17:09:42.284 SingleUserNotebookApp handlers:155] Creating new notebook in 
[I 2017-10-12 17:09:42.438 SingleUserNotebookApp log:122] 201 POST /user/daer/api/contents (daer@::ffff:172.17.2.118) 154.90ms
[I 2017-10-12 17:09:42.550 SingleUserNotebookApp log:122] 200 GET /user/daer/notebooks/Untitled1.ipynb?kernel_name=python3 (daer@::ffff:172.17.2.118) 52.70ms
[I 2017-10-12 17:09:43.241 SingleUserNotebookApp log:122] 200 GET /user/daer/api/config/notebook?_=1507849790709 (daer@::ffff:172.17.2.118) 1.95ms
[I 2017-10-12 17:09:43.244 SingleUserNotebookApp log:122] 200 GET /user/daer/api/config/common?_=1507849790710 (daer@::ffff:172.17.2.118) 1.82ms
[I 2017-10-12 17:09:43.337 SingleUserNotebookApp log:122] 200 GET /user/daer/api/kernelspecs (daer@::ffff:172.17.2.118) 4.80ms
[I 2017-10-12 17:09:43.526 SingleUserNotebookApp log:122] 200 GET /user/daer/api/contents/Untitled1.ipynb?type=notebook&_=1507849790711 (daer@::ffff:172.17.2.118) 93.39ms
[W 2017-10-12 17:09:43.541 SingleUserNotebookApp log:122] 404 GET /user/daer/nbextensions/widgets/notebook/js/extension.js?v=20171012170934 (daer@::ffff:172.17.2.118) 8.00ms
[I 2017-10-12 17:09:43.666 SingleUserNotebookApp kernelmanager:127] Kernel started: 95c07211-ba3c-4047-9fe8-6dbd8206b821
[I 2017-10-12 17:09:43.667 SingleUserNotebookApp log:122] 201 POST /user/daer/api/sessions (daer@::ffff:172.17.2.118) 21.50ms
[I 2017-10-12 17:09:43.669 SingleUserNotebookApp log:122] 200 GET /user/daer/api/contents/Untitled1.ipynb/checkpoints?_=1507849790712 (daer@::ffff:172.17.2.118) 0.92ms
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
[I 2017-10-12 17:09:46.668 SingleUserNotebookApp restarter:103] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
[I 2017-10-12 17:09:49.677 SingleUserNotebookApp restarter:103] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
[I 2017-10-12 17:09:52.682 SingleUserNotebookApp restarter:103] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
[W 2017-10-12 17:09:53.733 SingleUserNotebookApp handlers:234] Timeout waiting for kernel_info reply from 95c07211-ba3c-4047-9fe8-6dbd8206b821
[I 2017-10-12 17:09:53.735 SingleUserNotebookApp log:122] 101 GET /user/daer/api/kernels/95c07211-ba3c-4047-9fe8-6dbd8206b821/channels?session_id=8C2D3A72010D466F8B4143F871EC1DDB (daer@::ffff:172.17.2.118) 10004.66ms
[I 2017-10-12 17:09:55.687 SingleUserNotebookApp restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 95c07211-ba3c-4047-9fe8-6dbd8206b821 restarted
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named 'IPython.paths'
[W 2017-10-12 17:09:58.696 SingleUserNotebookApp restarter:95] KernelRestarter: restart failed
[W 2017-10-12 17:09:58.696 SingleUserNotebookApp kernelmanager:90] Kernel 95c07211-ba3c-4047-9fe8-6dbd8206b821 died, removing from map.
ERROR:root:kernel 95c07211-ba3c-4047-9fe8-6dbd8206b821 restarted failed!
[W 2017-10-12 17:09:58.730 SingleUserNotebookApp handlers:545] Kernel deleted before session
[W 2017-10-12 17:09:58.731 SingleUserNotebookApp log:122] 410 DELETE /user/daer/api/sessions/56f45471-bf08-4920-9650-ff0fde4aa175 (daer@::ffff:172.17.2.118) 3.07ms
```

**Share what version of JupyterHub you are using**
jupyterhub (0.8.0)
ipython (6.2.1)
ipython-genutils (0.2.0)

jupyter troubleshoot output

```
$PATH:
    /usr/local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
    /snap/bin
    /snap/bin

sys.path:
    /usr/local/bin
    /usr/lib/python35.zip
    /usr/lib/python3.5
    /usr/lib/python3.5/plat-x86_64-linux-gnu
    /usr/lib/python3.5/lib-dynload
    /home/will/.local/lib/python3.5/site-packages
    /usr/local/lib/python3.5/dist-packages
    /usr/lib/python3/dist-packages

sys.executable:
    /usr/bin/python3

sys.version:
    3.5.3 (default, Sep 14 2017, 22:58:41) 
    [GCC 6.3.0 20170406]

platform.platform():
    Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty

which -a jupyter:
    /usr/local/bin/jupyter
    /usr/local/bin/jupyter

```

**Comment by minrk** [comment]
The `IPython.paths` error tells me that `IPython < 4` is being imported. Perhaps an old IPython is still in `/home/will/.local/lib/python3.5/site-packages` or `/usr/lib/python3/dist-packages`?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
