### ISSUE TITLE
socket hang up & LDAPSocketOpenError: invalid server address

### ISSUE THREAD

**Issue by mrinmoyprasad** [jupyterhub/jupyterhub#1486]
Hi! Users are unable to login into JupyterHub with `504 Gateway Time-out` errors. I am behind corporate proxy, but weirdly another server setup using same configurations work. However, launching new servers result in JupyterHub rendering same errors. 

**How to reproduce the issue**
I am running JupyterHub 0.8.0 dev docker image, with docker images from docker stacks as my single-user server image. This is done on an EC2 instance.

**What you expected to happen**
User logs in to his notebook server running in his single user server container

**What actually happens**
`504 Gateway Time-out`. In the logs, there are `Error: socket hang up` and `ldap3.core.exceptions.LDAPSocketOpenError: invalid server address` errors. 

**Share what version of JupyterHub you are using**
JupyterHub 0.8.0 dev in a docker image

**Running** _jupyter troubleshoot_ **from the command line, if possible, and posting
its output would also be helpful.**
Did not work, as jupyter is not installed on host, but only in containers, which are never launched due to this error.

Here are the logs I see:

```19:52:09.523 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8444/api/routes
[D 2017-10-16 19:52:09.537 JupyterHub app:1266] Proxy started and appears to be up
[I 2017-10-16 19:52:09.538 JupyterHub app:1571] JupyterHub is now running at http://127.0.0.1:8443/
[I 2017-10-16 19:52:17.929 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 24.19ms
[I 2017-10-16 19:52:29.499 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.44ms
[I 2017-10-16 19:52:39.359 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.59ms
[D 2017-10-16 19:52:45.645 JupyterHub ldapauthenticator:76] DN= 'cn=eid,ou=dev,ou=users,dc=org,dc=company,dc=com'
19:52:57.926 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
19:52:57.928 - error: [ConfigProxy] 503 GET /hub/login
.
.
.
19:55:09.572 - error: [ConfigProxy] 503 GET /hub/login
[E 2017-10-16 19:55:25.810 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (::ffff:10.6.8.33)
    HTTPServerRequest(protocol='http', host='domain.company.com', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:10.6.8.33', headers={'X-Forwarded-Host': 'domain.company.com', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'domain.company.com', 'Referer': 'https://domain.company.com/hub/login', 'Upgrade-Insecure-Requests': '1', 'Content-Type': 'application/x-www-form-urlencoded', 'X-Forwarded-Proto': 'https,https', 'Origin': 'https://domain.company.com', 'X-Forwarded-For': '10.223.57.58,::ffff:10.6.8.33', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Length': '33', 'X-Amzn-Trace-Id': 'Root=1-59e50e0d-082f51616186b84d35dffc39', 'Cache-Control': 'max-age=0', 'Connection': 'close', 'Cookie': 'AMCVS_317906C354252E890A4C98BC%40AdobeOrg=1; AdallomAuth00=mWBFSaKeGXdoPI0jypiFIqbH4CjYpVTZm_PhTQ4yGDywFbvxpwR72ZdmPTiPPa2uJJZZhmSmRN1yq3EjMofemWPYtNtlNAthd0AW7noRJ8JkjP1yqfsGEJZ9Y8cR5wglSBQdVmMIspPcYCt7Vs20yJtDem5V6H6MrDt0wqd1kle5gtwuE34MGerpj8xxsXdd94CD0SVlUe632me5JfJ7qk7-C-aAAvp0itzFIW0P8ven_xLkMoDZq9hy-obAst_ibvQzXVK9__ahN3gU4fsDZ3LG5TDopQ0qp0DT6ZGdYJQPejDo4jXoJ7mY88pFr4VR; AdallomAuthCount=1; SP_opentoken=T1RLAQJ-hh2gZSsd_7TlnD6kr_rWbI-68xCmLljtY_nNrddzUqCCDHn-AADgaKDIiKzCVrfQ0cOvzRmCHBWO_2TXs-catNIhPZVYwWLMJJX8JRX5EhEkaZOlB3ghxEJw9265-Yi2ngs2CB6maZIJhre-y1nPfpmT-q_AFUCXAzL781aG5G7WXJFvwOz01tjhm3P0-Z7ZJCG1uO8LVzozsAgPmxDM_GizuwlpvSVB0gts5e-dnSmhI-a8ZjP-e8qy0uqI2RQlnfx7ALj7lzBdgA8LcF2NzG5Kk4xSCSIwCC0lyO6gmCQEV22icznBw3BH8IzuO9PNcXiBd28YaOHwj093vvdq85dZyZSr4tc*; rtFa=F+6H8pmlTN5fWb85s0B1Piihbv7aVDieI3mcXJlKi8MA1GD55jL8IrZCvhxyGCOxv2IgfQsDwKsyVux3EDGhcrQIfMzk7VuxMkhXsm4stYMCgDT2Ps4crAGK4dTGxw+ipUDLMvJ4q5+DGEk462Yt/nJTMzL+MVC0/4vs+SeChkABJ9pHM83OSnB/IQawypaK9krJGTo42DnlT7vXdCL05RW9W/OkbqOZwb0K9yzgjzChSnXkLGstBz3jl65wFAwqKLtwDYpdN3Gui9xa2A4lmYw7qYh7rN0OFRBYyiS1ui2QFyIEDUHw8z6oYA7HPrv9sniXD/ghDrJk14FQnpEWQxKWm8gCaI6Ddemm/fYxbFE/4kyI8UiDUQqJMoLBBhgKIAAAAA==; AMCV_317906C354252E890A4C98BC%40AdobeOrg=817868104%7CMCIDTS%7C17456%7CMCMID%7C54876541603268899802651014124376103873%7CMCAAMLH-1508775470%7C7%7CMCAAMB-1508775470%7CNRX38WO0n5BH8Th-nqAG_A%7CMCOPTOUT-1508177870s%7CNONE%7CMCAID%7CNONE; s_pers=%20gpv_p4%3Dhttps%253A%252F%252Fdocs.company.com%252Fwelcome%7C1508172471702%3B%20s_nr%3D1508170671709-Repeat%7C1510762671709%3B; s_sess=%20s_sq%3D%3B%20s_cc%3Dtrue%3B; _ga=GA1.2.1393795620.1507390666; _gid=GA1.2.253296827.1508170668', 'X-Forwarded-Port': '443,443'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 74, in post
        username = yield self.authenticate(data)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 281, in authenticate
        result = yield auth.get_authenticated_user(self, data)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/auth.py", line 171, in get_authenticated_user
        username = yield self.authenticate(handler, data)
      File "/opt/conda/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/ldapauthenticator/ldapauthenticator.py", line 83, in authenticate
        isBound = conn.bind()
      File "/opt/conda/lib/python3.5/site-packages/ldap3/core/connection.py", line 508, in bind
        self.open(read_server_info=False)
      File "/opt/conda/lib/python3.5/site-packages/ldap3/strategy/sync.py", line 55, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/opt/conda/lib/python3.5/site-packages/ldap3/strategy/base.py", line 148, in open
        raise LDAPSocketOpenError('invalid server address')
    ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

[D 2017-10-16 19:55:25.814 JupyterHub base:462] No template for 500
[E 2017-10-16 19:55:25.822 JupyterHub log:99] {
      "X-Forwarded-Host": "domain.company.com",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
      "Accept-Encoding": "gzip, deflate, br",
      "Host": "domain.company.com",
      "Referer": "https://domain.company.com/hub/login",
      "Upgrade-Insecure-Requests": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "X-Forwarded-Proto": "https,https",
      "Origin": "https://domain.company.com",
      "X-Forwarded-For": "10.223.57.58,::ffff:10.6.8.33",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.8",
      "Content-Length": "33",
      "X-Amzn-Trace-Id": "Root=1-59e50e0d-082f51616186b84d35dffc39",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "Cookie": "AMCVS_317906C354252E890A4C98BC%40AdobeOrg=1; AdallomAuth00=mWBFSaKeGXdoPI0jypiFIqbH4CjYpVTZm_PhTQ4yGDywFbvxpwR72ZdmPTiPPa2uJJZZhmSmRN1yq3EjMofemWPYtNtlNAthd0AW7noRJ8JkjP1yqfsGEJZ9Y8cR5wglSBQdVmMIspPcYCt7Vs20yJtDem5V6H6MrDt0wqd1kle5gtwuE34MGerpj8xxsXdd94CD0SVlUe632me5JfJ7qk7-C-aAAvp0itzFIW0P8ven_xLkMoDZq9hy-obAst_ibvQzXVK9__ahN3gU4fsDZ3LG5TDopQ0qp0DT6ZGdYJQPejDo4jXoJ7mY88pFr4VR; AdallomAuthCount=1; SP_opentoken=T1RLAQJ-hh2gZSsd_7TlnD6kr_rWbI-68xCmLljtY_nNrddzUqCCDHn-AADgaKDIiKzCVrfQ0cOvzRmCHBWO_2TXs-catNIhPZVYwWLMJJX8JRX5EhEkaZOlB3ghxEJw9265-Yi2ngs2CB6maZIJhre-y1nPfpmT-q_AFUCXAzL781aG5G7WXJFvwOz01tjhm3P0-Z7ZJCG1uO8LVzozsAgPmxDM_GizuwlpvSVB0gts5e-dnSmhI-a8ZjP-e8qy0uqI2RQlnfx7ALj7lzBdgA8LcF2NzG5Kk4xSCSIwCC0lyO6gmCQEV22icznBw3BH8IzuO9PNcXiBd28YaOHwj093vvdq85dZyZSr4tc*; rtFa=F+6H8pmlTN5fWb85s0B1Piihbv7aVDieI3mcXJlKi8MA1GD55jL8IrZCvhxyGCOxv2IgfQsDwKsyVux3EDGhcrQIfMzk7VuxMkhXsm4stYMCgDT2Ps4crAGK4dTGxw+ipUDLMvJ4q5+DGEk462Yt/nJTMzL+MVC0/4vs+SeChkABJ9pHM83OSnB/IQawypaK9krJGTo42DnlT7vXdCL05RW9W/OkbqOZwb0K9yzgjzChSnXkLGstBz3jl65wFAwqKLtwDYpdN3Gui9xa2A4lmYw7qYh7rN0OFRBYyiS1ui2QFyIEDUHw8z6oYA7HPrv9sniXD/ghDrJk14FQnpEWQxKWm8gCaI6Ddemm/fYxbFE/4kyI8UiDUQqJMoLBBhgKIAAAAA==; AMCV_317906C354252E890A4C98BC%40AdobeOrg=817868104%7CMCIDTS%7C17456%7CMCMID%7C54876541603268899802651014124376103873%7CMCAAMLH-1508775470%7C7%7CMCAAMB-1508775470%7CNRX38WO0n5BH8Th-nqAG_A%7CMCOPTOUT-1508177870s%7CNONE%7CMCAID%7CNONE; s_pers=%20gpv_p4%3Dhttps%253A%252F%252Fdoc.company.com%252Fwelcome%7C1508172471702%3B%20s_nr%3D1508170671709-Repeat%7C1510762671709%3B; s_sess=%20s_sq%3D%3B%20s_cc%3Dtrue%3B; _ga=GA1.2.1393795620.1507390666; _gid=GA1.2.253296827.1508170668",
      "X-Forwarded-Port": "443,443"
    }
[E 2017-10-16 19:55:25.822 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:10.6.8.33) 160175.73ms
[I 2017-10-16 19:55:25.825 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.03ms
[D 2017-10-16 19:55:25.827 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.830 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.92ms
[I 2017-10-16 19:55:25.833 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 0.98ms
[D 2017-10-16 19:55:25.834 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.836 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.22ms
[I 2017-10-16 19:55:25.839 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.02ms
[D 2017-10-16 19:55:25.840 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.843 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.31ms
[I 2017-10-16 19:55:25.846 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 0.98ms
[D 2017-10-16 19:55:25.847 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.850 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin%3Fnext%3D (@172.17.0.2) 1.23ms
[D 2017-10-16 19:55:25.850 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.853 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.24ms
[I 2017-10-16 19:55:25.856 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 0.99ms
[D 2017-10-16 19:55:25.857 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.860 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.26ms
[I 2017-10-16 19:55:25.863 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.01ms
[D 2017-10-16 19:55:25.864 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.866 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.23ms
[I 2017-10-16 19:55:25.869 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 0.97ms
[D 2017-10-16 19:55:25.870 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.873 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.24ms
[I 2017-10-16 19:55:25.876 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 0.97ms
[D 2017-10-16 19:55:25.877 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.879 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.26ms
[I 2017-10-16 19:55:25.883 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.01ms
[D 2017-10-16 19:55:25.883 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.886 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.24ms
[I 2017-10-16 19:55:25.889 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 0.98ms
[D 2017-10-16 19:55:25.890 JupyterHub pages:223] No template for 503
[I 2017-10-16 19:55:25.893 JupyterHub log:100] 200 GET /hub/error/503?url=%2Fhub%2Flogin (@172.17.0.2) 1.22ms
[I 2017-10-16 19:55:25.896 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 0.99ms
[I 2017-10-16 19:55:29.592 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.50ms
[I 2017-10-16 19:55:48.031 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.46ms
[I 2017-10-16 19:55:59.623 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.46ms
[I 2017-10-16 19:56:18.055 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.50ms
[I 2017-10-16 19:56:29.651 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.49ms
[I 2017-10-16 19:56:48.087 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.160) 1.48ms
[I 2017-10-16 19:56:59.662 JupyterHub log:100] 200 GET /hub/login (@::ffff:10.6.8.33) 1.45ms
[D 2017-10-16 19:57:09.557 JupyterHub orm:153] Fetching GET http://127.0.0.1:8444/api/routes```

**Comment by willingc** [comment]
Hi @mrinmoyprasad. Sorry for the delay in responding.

Do you see the same issue if you run the latest stable version of JupyterHub 0.8.0?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
