### ISSUE TITLE
500 : Internal Server Error when Jupyterhub starts as a system service 

### ISSUE THREAD

**Issue by denisafanasev** [jupyterhub/jupyterhub#1494]
Hi All,

I have got an "500 : Internal Server Error" error after login as any user when I have start JupyterHub as a system service on Ubuntu 16.04 (AWS distribution). In case I have start JupyterHub from a command line as "sudo jupyterhub" or just "jupyterhub" it works normally without any error.

I am running JuoyterHub under Acaconda3 env which is install by user "ubuntu" and login into JupyterHub as user "dafanasev" (in the log below)

My `/etc/systemd/system/jupyterhub.service` is:
```
[Unit]
Description="JupyterHub"
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/ubuntu/anaconda3/bin"
ExecStart=/home/ubuntu/anaconda3/bin/jupyterhub --debug --log-file /var/log/jupyterhub.log

[Install]
WantedBy=multi-user.target
```

In the log file I see:
```
[I 2017-10-19 09:04:21.139 JupyterHub log:100] 302 GET /hub/ (@::ffff:185.36.60.154) 2.55ms
[I 2017-10-19 09:04:21.418 JupyterHub log:100] 302 GET /login (@::ffff:185.36.60.154) 0.79ms
[I 2017-10-19 09:04:21.690 JupyterHub log:100] 200 GET /hub/login (@::ffff:185.36.60.154) 1.52ms
[D 2017-10-19 09:04:22.910 JupyterHub log:100] 304 GET /favicon.ico (@::ffff:185.36.60.154) 4.27ms
[I 2017-10-19 09:04:24.643 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="dafanasev"' '--cookie-name="jupyter-hub-token-dafanasev"' '--base-url="/user/dafanasev"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=60401
[D 2017-10-19 09:04:24.650 JupyterHub spawner:584] Polling subprocess every 30s
[W 2017-10-19 09:04:34.662 JupyterHub web:1587] 500 POST /hub/login?next= (::ffff:185.36.60.154): Spawner failed to start [status=1]
[D 2017-10-19 09:04:34.665 JupyterHub base:462] No template for 500
[E 2017-10-19 09:04:34.669 JupyterHub log:99] {
      "X-Forwarded-Host": “server_name:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:185.36.60.154",
      "Connection": "close",
      "Cookie": "_ga=GA1.3.66730028.1507908346; _ym_uid=1507908345529457843; _xsrf=2|c9c272c8|824787f3bc4d773beabb09d424042f91|1507036879",
      "Content-Length": "37",
      "Dnt": "1",
      "Upgrade-Insecure-Requests": "1",
      "Referer": "http://server_name:8000/hub/login",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.4 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.4",
      "Origin": "http://server_name:8000",
      "Content-Type": "application/x-www-form-urlencoded",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-us",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Host": “server_name:8000"
    }
[E 2017-10-19 09:04:34.669 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:185.36.60.154) 10121.42ms
```
Any ideas / recommendations?

**Comment by denisafanasev** [comment]
I have managed to find the problem, the deals is path variable. It have to be 

PATH=/home/ubuntu/anaconda3/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

Due to the is other python version in the /usr/local/sbin and it seems it starts then the Jupytherhub opens a single notebook.

**Comment by karthikpitchaimani** [comment]
I was getting the below exception. I have not created any specific jupyterusergroup, created a Linux user and added to shadow and wheel group. Should we need to create a separate group or?
OS: SUSE Linux 11 SP3 and JupyterHub 0.8.1
Kindly help me to fix this issues.
**500 : Internal Server** 
[D 2018-01-14 21:11:47.760 JupyterHub user:184] Creating <class 'jupyterhub.spawner.LocalProcessSpawner'> for lta-uat-jupyter:
[D 2018-01-14 21:11:47.761 JupyterHub app:1211] Loading state for lta-uat-jupyter from db
[D 2018-01-14 21:11:47.761 JupyterHub app:1236] lta-uat-jupyter not running
[D 2018-01-14 21:11:47.763 JupyterHub app:1241] Loaded users:
    lta-uat-jupyter
[I 2018-01-14 21:11:47.767 JupyterHub app:1528] Hub API listening on http://0.0.0.0:8081/hub/
[W 2018-01-14 21:11:47.768 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-01-14 21:11:47.768 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-01-14 21:11:47.768 JupyterHub proxy:458] Starting proxy @ http://0.0.0.0:8000/
[D 2018-01-14 21:11:47.768 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://pxthdd07:8081/hub/error']
21:11:47.929 - info: [ConfigProxy] Proxying http://0.0.0.0:8000 to (no default)
21:11:47.932 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2018-01-14 21:11:48.676 JupyterHub proxy:491] Proxy started and appears to be up
[D 2018-01-14 21:11:48.678 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[W 2018-01-14 21:11:48.688 JupyterHub proxy:304] Adding missing default route
[I 2018-01-14 21:11:48.688 JupyterHub proxy:370] Adding default route for Hub: / => http://pxthdd07:8081
[D 2018-01-14 21:11:48.689 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
21:11:48.689 - info: [ConfigProxy] 200 GET /api/routes
21:11:48.693 - info: [ConfigProxy] Adding route / -> http://pxthdd07:8081
21:11:48.694 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-01-14 21:11:48.694 JupyterHub app:1581] JupyterHub is now running at http://0.0.0.0:8000/
[I 2018-01-14 21:12:03.948 JupyterHub log:122] 200 GET /hub/home (lta-uat-jupyter@10.8.95.244) 22.47ms
[I 2018-01-14 21:12:05.052 JupyterHub log:122] 302 GET /hub/spawn â /user/lta-uat-jupyter/ (lta-uat-jupyter@10.8.95.244) 2.08ms
[I 2018-01-14 21:12:05.061 JupyterHub log:122] 302 GET /user/lta-uat-jupyter/ â /hub/user/lta-uat-jupyter/ (@10.8.95.244) 0.33ms
[D 2018-01-14 21:12:05.071 JupyterHub base:421] Initiating spawn for lta-uat-jupyter
[I 2018-01-14 21:12:05.250 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=52731 --debug
[D 2018-01-14 21:12:05.256 JupyterHub spawner:727] Polling subprocess every 30s
[D 2018-01-14 21:12:05.300 JupyterHub base:427] 0/100 concurrent spawns
[D 2018-01-14 21:12:05.300 JupyterHub base:430] 0 active servers
Traceback (most recent call last):
  File "/var/opt/teradata/anaconda3/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 314, in migrate_config
    super(SingleUserNotebookApp, self).migrate_config()
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyter_core/migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 23, in <module>
    from jedi.api import classes
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 14, in <module>
    from jedi.evaluate import representation as er
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 69, in <module>
    from jedi.evaluate import representation as er
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/evaluate/representation.py", line 52, in <module>
    from jedi.evaluate import docstrings
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jedi/evaluate/docstrings.py", line 46, in <module>
    from numpydoc.docscrape import NumpyDocString
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/numpydoc/__init__.py", line 5, in <module>
    from .numpydoc import setup
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/numpydoc/numpydoc.py", line 31, in <module>
    from .docscrape_sphinx import get_doc_object, SphinxDocString
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/numpydoc/docscrape_sphinx.py", line 14, in <module>
    from sphinx.jinja2glue import BuiltinTemplateLoader
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/sphinx/jinja2glue.py", line 22, in <module>
    from sphinx.application import TemplateBridge
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 30, in <module>
    from sphinx.config import Config
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util.i18n import format_date
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/babel/util.py", line 19, in <module>
    from babel import localtime
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/babel/localtime/_unix.py", line 111, in _get_localzone
    with open(tzpath, 'rt') as tzfile:
PermissionError: [Errno 13] Permission denied: '/etc/sysconfig/clock'
**[W 2018-01-14 21:12:15.304 JupyterHub web:1587] 500 GET /hub/user/lta-uat-jupyter/ (10.8.95.244): Spawner failed to start [status=1]. The logs for lta-uat-jupyter may contain details.
[D 2018-01-14 21:12:15.305 JupyterHub base:633] No template for 500**
[E 2018-01-14 21:12:15.312 JupyterHub log:114] {
      "X-Forwarded-Host": "10.8.104.243:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "10.8.95.244",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1515926469|17:jupyter-hub-token|44:ODAwNDdmYjE4Mzk2NGJjN2EwMGM2YjE4MzMwYTg1YzE=|f2851d4faab14bbc7acd3a1be2929b34141a99ebf58649f2655a441c1a1a4430\"",
      "Accept-Language": "en-US,en;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://10.8.104.243:8000/hub/home",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "10.8.104.243:8000"
    }
**[E 2018-01-14 21:12:15.312 JupyterHub log:122] 500 GET /hub/user/lta-uat-jupyter/ (lta-uat-jupyter@10.8.95.244) 10241.18ms
[W 2018-01-14 21:12:34.672 JupyterHub user:458] lta-uat-jupyter's server never showed up at http://127.0.0.1:52731/user/lta-uat-jupyter/ after 30 seconds. Giving up**
[E 2018-01-14 21:12:34.756 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fc6a70361d0> after timeout
    Traceback (most recent call last):
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/var/opt/teradata/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:52731/user/lta-uat-jupyter/ didn't respond in 30 seconds

[D 2018-01-14 21:16:48.695 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
21:16:48.697 - info: [ConfigProxy] 200 GET /api/routes
