### ISSUE TITLE
docker does not spawn with jupyterhub 0.8.0 and jupyterhub/dockerspawner

### ISSUE THREAD

**Issue by rydeng** [jupyterhub/jupyterhub#1501]
when I spawn the docker , I has these logs. But in jupyterhub 0.7.2, it is OK:

```[I 2017-10-24 15:24:43.243 BigJupyterHub log:122] 302 GET /hub/spawn → /user/rydeng/ (rydeng@171.210.195.108) 5.01ms
[I 2017-10-24 15:24:43.349 BigJupyterHub log:122] 302 GET /user/rydeng/ → /hub/user/rydeng/ (@171.210.195.108) 1.17ms
[W 2017-10-24 15:24:43.685 BigJupyterHub dockerspawner:545] Removing container that should have been cleaned up: jupyter-rydeng (id: dfa166d)
[I 2017-10-24 15:24:43.697 BigJupyterHub dockerspawner:578] create - kwargs, {'name': 'jupyter-rydeng', 'command': ['python3', '../docker_biglab_singleuser/singleuserapp.py', '--ip="0.0.0.0"', '--port=8888'], 'environment': {'JUPYTERHUB_API_URL': 'http://172.26.63.144:8081/hub/api', 'JPY_API_TOKEN': 'b7648b0d1c4b4c0db8269615845c2c56', 'JUPYTERHUB_BASE_URL': '/', 'JUPYTERHUB_HOST': '', 'JUPYTERHUB_OAUTH_CALLBACK_URL': '/user/rydeng/oauth_callback', 'JUPYTERHUB_API_TOKEN': 'b7648b0d1c4b4c0db8269615845c2c56', 'JUPYTERHUB_CLIENT_ID': 'user-rydeng', 'JUPYTERHUB_USER': 'rydeng', 'JUPYTERHUB_SERVICE_PREFIX': '/user/rydeng/'}, 'image': 'bigquant/biglabsingleuser', 'user': '1003:1003', 'ports': {'8888/tcp': None}, 'volumes': ['/bqmnt/bqranker/data', '/bqmnt/data/bigdata', '/bqmnt/data/var_app/enabled', '/bqmnt/data/var_app_data', '/bqmnt/data2/datasource/', '/bqmnt/data_shared/data/bigdata/v1/bigdb', '/bqmnt/data_shared2', '/bqmnt/data_t2/datasource/', '/home/jovyan/work', '/opt/conda/lib/python3.5/site-packages/IPython', '/opt/conda/lib/python3.5/site-packages/notebook', '/var/app/data', '/var/app/data/bigquant/datasource/v2/', '/var/app/data/bigquant/datasource/v2_t2/', '/var/app/data/bqranker', '/var/app/enabled', '/var/app/log/biglab']}
[I 2017-10-24 15:24:43.791 BigJupyterHub dockerspawner:613] Created container 'jupyter-rydeng' (id: 8c3a2a5) from image bigquant/biglabsingleuser
[I 2017-10-24 15:24:43.791 BigJupyterHub dockerspawner:630] Starting container 'jupyter-rydeng' (id: 8c3a2a5)
[I 2017-10-24 15:24:43.792 BigJupyterHub dockerspawner:640] Starting container 1111111111111111111111111111111111111111111{}
[I 2017-10-24 15:24:43.970 BigJupyterHub dockerspawner:643] Starting container 2222222222222222222222222222222222222222222
[I 2017-10-24 15:24:43.977 BigJupyterHub dockerspawner:651] Started of container '8c3a2a5', ip 127.0.0.1, port 32792
[W 2017-10-24 15:24:53.692 BigJupyterHub web:1587] 500 GET /hub/user/rydeng/ (171.210.195.108): Spawner failed to start [status=ExitCode=2, Error='', FinishedAt=2017-10-24T07:24:44.066493501Z]. The logs for rydeng may contain details.
[E 2017-10-24 15:24:53.699 BigJupyterHub log:114] {
      "Accept-Language": "zh-CN,zh;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36",
      "Connection": "upgrade",
      "Cache-Control": "max-age=0",
      "X-Real-Ip": "171.210.195.108",
      "Referer": "https://bigquant.com/account/login/?next=https%3A%2F%2Fbigquant.com%2Faccount%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252Ftesti.bigquant.com%252Fhub%252Fcas_callback",
      "X-Forwarded-Host": "testi.bigquant.com",
      "Host": "testi.bigquant.com",
      "Upgrade-Insecure-Requests": "1",
      "X-Nginx-Proxy": "true",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "X-Forwarded-Proto": "https,http",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1508829883|17:jupyter-hub-token|44:MmRkYzA4Y2EwYzg0NDcwNWJmNTRmMWFiOTM0YWQ1ZDM=|86b99757668dbce5a8639f0eee923f16bfbfa33380985af47d493f1c80bb07b6\"; gr_user_id=d9a58db7-97ff-489a-b2ba-ca5637106b8f; _xsrf=2|ac904b95|e11e2a7cee9edee53c710e0b2c74376e|1507538189; gr_session_id_aab706c8f4b762a5=dccbd152-0977-4fd8-8e50-7e10654ad2f0; Hm_lvt_c58f67ca105d070ca7563b4b14210980=1508750640,1508752319,1508757305,1508812035; Hm_lpvt_c58f67ca105d070ca7563b4b14210980=1508829875; __bqssid=2f411e67c3c88c60b8c83b3cd0c4f3b4; __bqasid=f94ab867f5c5eb0a9a34050fb4a9f567",
      "X-Forwarded-Port": "80",
      "X-Forwarded-For": "171.210.195.108,::ffff:127.0.0.1"
    }
[E 2017-10-24 15:24:53.699 BigJupyterHub log:122] 500 GET /hub/user/rydeng/ (rydeng@171.210.195.108) 10252.44ms
[W 2017-10-24 15:25:16.792 BigJupyterHub user:458] rydeng's server never showed up at http://127.0.0.1:32792/user/rydeng/ after 30 seconds. Giving up
[E 2017-10-24 15:25:16.840 BigJupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7ff93a5e7160> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32792/user/rydeng/ didn't respond in 30 seconds

**Comment by rydeng** [comment]
I found in the latest dockerspawner, there is these code, when I delete the line `command=cmd`, it is ok
'''
create_kwargs = dict(
                image=image,
                environment=self.get_env(),
                volumes=self.volume_mount_points,
                name=self.container_name,
                command=cmd,
                user="{}:{}".format(bigquant_uid, bigquant_uid)   # BIGQUANT
            )
