### ISSUE TITLE
Jupyterhub Deprecated Spawner.start should return ip and port?

### ISSUE THREAD

**Issue by ziedbouf** [jupyterhub/jupyterhub#1559]
Dear all, 

I have an issue when building my jupyterhub using the following ansible book (https://github.com/natbusa/jupyterhub-ansible-deploy). from my understanding is  that the custom image spawner created by the author doesn't explicitly return both container ip and port while this seems to be required by jupyterhub version >= 0.7.

```python
from dockerspawner import SystemUserSpawner
from traitlets import default, Unicode, List
from tornado import gen

class DockerImageChooserSpawner(SystemUserSpawner):
    '''Enable the user to select the docker image that gets spawned.

    Define the available docker images in the JupyterHub configuration and pull
    them to the execution nodes:

    c.JupyterHub.spawner_class = DockerImageChooserSpawner
    c.DockerImageChooserSpawner.dockerimages = [
        'jupyterhub/singleuser',
        'jupyter/r-singleuser'
    ]
    '''

    dockerimages = List(
        trait = Unicode(),
        default_value = ['jupyterhub/systemuser'],
        minlen = 1,
        config = True,
        help = "Docker images that have been pre-pulled to the execution host."
    )

    form_template = Unicode("""
        <label for="dockerimage">Select a Docker image:</label>
        <select class="form-control" name="dockerimage" required autofocus>
            {option_template}
        </select>""",  config = True, help = "Form template.")

    option_template = Unicode("""<option value="{image}">{image}</option>""",
        config = True, help = "Template for html form options." )

    @default('options_form')
    def _options_form(self):
        """Return the form with the drop-down menu."""
        options = ''.join([
                              self.option_template.format(image=di) for di in self.dockerimages
                              ])
        return self.form_template.format(option_template=options)

    def options_from_form(self, formdata):
        """Parse the submitted form data and turn it into the correct
           structures for self.user_options."""

        default = self.dockerimages[0]

        # formdata looks like {'dockerimage': ['jupyterhub/singleuser']}"""
        dockerimage = formdata.get('dockerimage', [default])[0]

        # Don't allow users to input their own images
        if dockerimage not in self.dockerimages: dockerimage = default

        options = {
            'container_image':  dockerimage,
            'container_prefix': super().container_prefix
        }
        return options

    @gen.coroutine
    def start(self, image=None, extra_create_kwargs=None,
              extra_start_kwargs=None, extra_host_config=None):

        # container_prefix is used to construct container_name
        self.container_prefix = self.user_options['container_prefix']

        # start the container
        yield SystemUserSpawner.start(
            self, image=self.user_options['container_image'],
            extra_create_kwargs=extra_create_kwargs,
            extra_host_config=extra_host_config)

```

Any suggestion on how returning both containers ip and port?

**Comment by ziedbouf** [comment]
Fixed the deprecation by adding the following:
`` return (self.ip, self.port)
But the error i got is timeout as the jupyter hub is not able to connect to the server:
```
[W 2017-11-23 10:17:53.175 JupyterHub user:278] zied's server never showed up at http://127.0.0.1:8888/user/zied after 180 seconds. Giving up
[I 2017-11-23 10:17:53.179 JupyterHub dockerspawner:642] Stopping container jupyter-zied (id: 5c6f5bb)
[I 2017-11-23 10:17:53.410 JupyterHub dockerspawner:648] Removing container jupyter-zied (id: 5c6f5bb)
[E 2017-11-23 10:17:53.445 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7f7e99a3bc50> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 294, in spawn
        raise e
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 270, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:8888/user/zied didn't respond in 180 seconds
```

I am using the following configuration:
```
c.PAMAuthenticator.service = 'login'
import os
c.PAMAuthenticator.open_sessions = False
c.PAMAuthenticator.service = 'login'
c.JupyterHub.hub_ip = '10.154.0.2'
c.JupyterHub.ip = '10.154.0.2'
c.JupyterHub.proxy_api_ip = '10.154.0.2'
from imagespawner import DockerImageChooserSpawner
c.JupyterHub.spawner_class = DockerImageChooserSpawner
c.Spawner.notebook_dir = '~'
c.DockerSpawner.container_ip = "0.0.0.0"
c.DockerSpawner.volumes = { '/home/{username}':'/home/{username}' }
c.DockerSpawner.remove_containers = True
c.DockerImageChooserSpawner.dockerimages = [u'natbusa/jupyterhub-scipy-lab', u'natbusa/jupyterhub-datascience-lab', u'natbusa/jupyterhub-tensorflow-lab', u'natbusa/jup$
c.SystemUserSpawner.host_homedir_format_string = '/home/{username}'
c.JupyterHub.ssl_cert = '/etc/jupyterhub/server.crt'
c.JupyterHub.ssl_key = '/etc/jupyterhub/server.key
```

**Comment by minrk** [comment]
DockerSpawner already returns the right ip and port, so you should only need to pass through this value. Instead of:


```python
yield SystemUserSpawner.start(self, ...)
```

which awaits the result, discards it and then returns None, you should return the original return value:

```python
return SystemUserSpawner.start(self, ...)
```

And for good measure, it's probably best to use `super`:

```python
return super().start(...) # no self!
```

**Comment by ziedbouf** [comment]
@minrk what i got is `Error: 'Future' object is not iterable`

**Comment by ziedbouf** [comment]
@minrk i am not so sure what's happening because i am new to the python world, but just making the following changes and it worked:
`res = SystemUserSpawner.start(self, ...)
return res
`
The images are around jupyterlab, do you think it will be the same as spining up any other docker jupyter images like the official ones.
