### ISSUE TITLE
COMMAND_FAILED: failed: iptables v1.4.21: Port `0' not valid

### ISSUE THREAD

**Issue by yocode** [jupyterhub/jupyterhub#1565]
Hello,

I have not come across this issue asked before.
I can log into my jupyterhub server fine. When I try to launch a notebook using I recieve the following error.

```
COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32797 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0' failed: iptables v1.4.21: Port `0' not valid
```

I'm using dockerspawner as the spawner.
```
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.32/containers/8c664ca2721876250ab9fbe9c3b8d8045d36777cbb6274715cb4156bbadb136d/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
    ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 566, in start
    yield self.docker('start', self.container_id, **start_kwargs)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 409, in _docker
    return m(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 1085, in start
    self._raise_for_status(res)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint jupyter-jonathan_2Es_2Eklein(8c1ab730940fa4eeb2fe9115c2582416ba2fe42c2ae74485d786eb8bbab1a60c):  (COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32797 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0' failed: iptables v1.4.21: Port `0' not valid

Try `iptables -h' or 'iptables --help' for more information.
)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/site-packages/tornado/log.py", line 193, in format
    formatted = self._fmt % record.__dict__
KeyError: 'highlevel'
Call stack:
  File "/bin/jupyterhub", line 4, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/jupyterhub/app.py", line 1632, in launch_instance
    loop.start()
  File "/usr/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 121, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1426, in _run_once
    handle._run()
  File "/usr/lib64/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/lib64/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1152, in inner
    self.run()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 427, in spawn
    user=self.name, error=e,
Message: 'Unhandled error starting jonathan.s.klein@pwc.com\'s server: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint jupyter-jonathan_2Es_2Eklein(8c1ab730940fa4eeb2fe9115c2582416ba2fe42c2ae74485d786eb8bbab1a60c):  (COMMAND_FAILED: \'/usr/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32797 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0\' failed: iptables v1.4.21: Port `0\' not valid\n\nTry `iptables -h\' or \'iptables --help\' for more information.\n)")'
```

I'm running the jupyterhub server on Centos7. In Centos7 firewalld is the firewall provider. Firewalld invokes the iptables command. Is jupyterhub trying to invoke the iptables-service as well?

**Comment by willingc** [comment]
@yocode What versions of JupyterHub and dockerspawner are you using?

> When I try to launch a notebook using I recieve the following error.

What were you using? Looks like you left out a word or have a typo.

**Comment by minrk** [comment]
JupyterHub doesn't invoke iptables. I'm unsure why this iptables would be called or why. Port 0 is typically used as a bind port (it is valid) to allow the system to select the port. I don't *think* we explicitly pass port 0 anywhere in DockerSpawner, but I could be wrong. I'm not sure what generates this iptables call, though. Does a container exist? Can you `docker inspect` it?

**Comment by yocode** [comment]
@willingc 

Hi,

jupyterhub --version
0.8.1

python3.6 -m pip show dockerspawner
Name: dockerspawner
Version: 0.9.1

Thanks for you help.

@minrk 

No container exists. I can get to the jupyterhub site, when I click 'Start My Server", that's when I see the error message occur in standard out. No container results from the action.

Thanks for you help!

**Comment by yocode** [comment]
I disabled firewalld.

systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2017-12-04 15:22:51 UTC; 23min ago
     Docs: man:firewalld(1)
 Main PID: 9694 (code=exited, status=0/SUCCESS)

restarting the jupyterhub server and trying to open a notebook results in the same error.

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 222, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.32/containers/8c664ca2721876250ab9fbe9c3b8d8045d36777cbb6274715cb4156bbadb136d/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
    ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 566, in start
    yield self.docker('start', self.container_id, **start_kwargs)
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 409, in _docker
    return m(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 1085, in start
    self._raise_for_status(res)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint jupyter-jonathan_2Es_2Eklein_40pwc_2Ecom (14acd34b3c344d4549f3b1ed0b8f94114343ae5299db9e14d8c579e419714341):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 32837 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0: iptables v1.4.21: Port `0' not valid

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))")

**Comment by yocode** [comment]
I was able to get past this issue by reinstalling the application on Debian.

**Comment by willingc** [comment]
Thanks for the update @yocode. Just for info for the next person that may run across this, did you reinstall jupyterhub and dockerspawner or just one of them?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
