### ISSUE TITLE
Jupyter Hub 500 Internal Server Error

### ISSUE THREAD

**Issue by sarbanes** [jupyterhub/jupyterhub#1589]
While I am trying to logon into Jupyter Hub (<server-name>:8081/hub/login) by using 'Sign I using certificate' I am getting the 500 Internal Server Error!
See below what the /jupyter/var/log/juphub.log contains:

```
[E 2017-12-18 23:47:18,228.228 JupyterHub log:100] 500 POST /hub/login?next= (@123.123.123.143) 4.61ms
[I 2017-12-18 23:49:31,043.043 JupyterHub log:100] 200 GET /hub/login (@123.123.123.143) 5.14ms
[E 2017-12-18 23:49:43,998.998 JupyterHub web:1590] Uncaught exception POST /hub/login?next= (123.123.123.143)
HTTPServerRequest(protocol='http', host='linux-host.net:8081', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='123.123.123.143', headers={'Cookie': '_ga=GA1.2.890158783.1476982962', 'X-Forwarded-For': '169.36.186.143', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Host': 'gbld2567280.eu.hedani.net:8081', 'Accept-Language': 'en-US,en;q=0.8', 'Content-Type': 'application/x-www-form-urlencoded', 'Referer': 'http://gbld2567280.eu.hedani.net:8081/hub/login', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36', 'Origin': 'http://gbld2567280.eu.hedani.net:8081', 'Cache-Control': 'max-age=0', 'Connection': 'Keep-Alive', 'X-Bluecoat-Via': '39e96424425a64ce', 'Content-Length': '9', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, identity'})
Traceback (most recent call last):
  File "/home/jupyterhub/0.7.2/lib/python3.5/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/home/jupyterhub/0.7.2/lib/python3.5/site-packages/csauth/login.py", line 61, in post
    identity = json.loads(self.request.headers.get(self.authenticator.header_identity))
  File "/home/opt/python3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
 
[E 2017-12-18 23:49:44,005.005 JupyterHub log:99] {
  "Cookie": "_ga=GA1.2.890158783.1476982962",
  "X-Forwarded-For": "123.123.123.143",
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
  "Host": "gbld2567280.eu.hedani.net:8081",
  "Accept-Language": "en-US,en;q=0.8",
  "Content-Type": "application/x-www-form-urlencoded",
  "Referer": "http://linux-host.net:8081/hub/login",
  "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36",
  "Origin": "http://linux-host.net:8081",
  "Cache-Control": "max-age=0",
  "Connection": "Keep-Alive",
  "X-Bluecoat-Via": "39e96424425a64ce",
  "Content-Length": "9",
 "Upgrade-Insecure-Requests": "1",
  "Accept-Encoding": "gzip, deflate, identity"
}
[E 2017-12-18 23:49:44,005.005 JupyterHub log:100] 500 POST /hub/login?next= (@123.123.123.143) 4.54ms
 ```

**Comment by minrk** [comment]
That looks like a bug in the csauth package (I'm not familiar with it). From the looks of it, it needs to handle the case of the identity header being undefined, which presumably means no user is identified.
