### ISSUE TITLE
JupyterHub: Not able to login Linux Users

### ISSUE THREAD

**Issue by karthikpitchaimani** [jupyterhub/jupyterhub#1612]
Hi Team,
I have configured JupyterHub 0.8.1 with normal Linux user, not a root user.
I started JupyterHub with the default setting like JupyterHub -- no-ssl and I could be able to JupytherHub in the browser.
I was struggling to log in the JupyterHub, when I try to login with Linux user, It says **_invalid username and password._**
**Console it says PAM Authentication failed (XXXX@:ffff:IP): (PAM Error 7) Authentication failure.**
Kindly let me know if anything more permission need to be done with that particular Linux user.
Thanks in advance.
Regards,
Karthik.P

**Comment by sangramga** [comment]
@karthikpitchaimani try starting hub with sudo (as a root user). Maybe PAM Authenticator needs root permissions if you are using Local Spawner(Default spawner of JupyterHub).

**Comment by karthikpitchaimani** [comment]
Thank you. Yes, I corrected now I could able to log in but I was getting the below error.

[W 2018-01-09 18:17:52.754 JupyterHub proxy:304] Adding missing default route
[I 2018-01-09 18:17:52.754 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2018-01-09 18:17:52.754 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
18:17:52.758 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
18:17:52.758 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-01-09 18:17:52.758 JupyterHub app:1581] JupyterHub is now running at http://:8000/
18:18:00.054 - debug: [ConfigProxy] PROXY WEB /hub/home to http://127.0.0.1:8081
[I 2018-01-09 18:18:00.084 JupyterHub log:122] 200 GET /hub/home (lta-uat-jupyter@::ffff:10.8.95.244) 22.64ms
18:18:04.241 - debug: [ConfigProxy] PROXY WEB /hub/spawn to http://127.0.0.1:8081
[I 2018-01-09 18:18:04.246 JupyterHub log:122] 302 GET /hub/spawn â /user/lta-uat-jupyter/ (lta-uat-jupyter@::ffff:10.8.95.244) 2.50ms
18:18:04.254 - debug: [ConfigProxy] PROXY WEB /user/lta-uat-jupyter/ to http://127.0.0.1:8081
[I 2018-01-09 18:18:04.257 JupyterHub log:122] 302 GET /user/lta-uat-jupyter/ â /hub/user/lta-uat-jupyter/ (@::ffff:10.8.95.244) 0.36ms
18:18:04.264 - debug: [ConfigProxy] PROXY WEB /hub/spawn to http://127.0.0.1:8081
18:18:04.265 - debug: [ConfigProxy] PROXY WEB /hub/user/lta-uat-jupyter/ to http://127.0.0.1:8081
[I 2018-01-09 18:18:04.268 JupyterHub log:122] 302 GET /hub/spawn â /user/lta-uat-jupyter/ (lta-uat-jupyter@::ffff:10.8.95.244) 1.84ms
[D 2018-01-09 18:18:04.270 JupyterHub base:421] Initiating spawn for lta-uat-jupyter
18:18:04.273 - debug: [ConfigProxy] PROXY WEB /user/lta-uat-jupyter/ to http://127.0.0.1:8081
[D 2018-01-09 18:18:04.494 JupyterHub base:427] 0/100 concurrent spawns
[D 2018-01-09 18:18:04.494 JupyterHub base:430] 0 active servers
[I 2018-01-09 18:18:04.496 JupyterHub log:122] 302 GET /user/lta-uat-jupyter/ â /hub/user/lta-uat-jupyter/ (@::ffff:10.8.95.244) 0.49ms
18:18:04.508 - debug: [ConfigProxy] PROXY WEB /hub/user/lta-uat-jupyter/ to http://127.0.0.1:8081
[D 2018-01-09 18:18:04.512 JupyterHub base:718] Waiting for lta-uat-jupyter pending spawn
**[I 180109 18:18:04 mediator:89] Spawning /home/lta-uat-jupyter/anaconda3/bin/jupyterhub-singleuser --port=34850 --debug**
Traceback (most recent call last):
  File "/home/lta-uat-jupyter/anaconda3/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1362, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 314, in migrate_config
    super(SingleUserNotebookApp, self).migrate_config()
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyter_core/migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/api/__init__.py", line 23, in <module>
    from jedi.api import classes
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/api/classes.py", line 14, in <module>
    from jedi.evaluate import representation as er
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 69, in <module>
    from jedi.evaluate import representation as er
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/evaluate/representation.py", line 52, in <module>
    from jedi.evaluate import docstrings
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jedi/evaluate/docstrings.py", line 46, in <module>
    from numpydoc.docscrape import NumpyDocString
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/numpydoc/__init__.py", line 5, in <module>
    from .numpydoc import setup
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/numpydoc/numpydoc.py", line 31, in <module>
    from .docscrape_sphinx import get_doc_object, SphinxDocString
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/numpydoc/docscrape_sphinx.py", line 14, in <module>
    from sphinx.jinja2glue import BuiltinTemplateLoader
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/sphinx/jinja2glue.py", line 22, in <module>
    from sphinx.application import TemplateBridge
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/sphinx/application.py", line 30, in <module>
    from sphinx.config import Config
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util.i18n import format_date
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/sphinx/util/i18n.py", line 19, in <module>
    import babel.dates
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/babel/util.py", line 19, in <module>
    from babel import localtime
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/babel/localtime/_unix.py", line 111, in _get_localzone
    with open(tzpath, 'rt') as tzfile:
PermissionError: [Errno 13] Permission denied: '/etc/sysconfig/clock'
[E 180109 18:18:05 mediator:43] mediator result: {'ok': False, 'error': 'Exited with status: 1'}
[E 2018-01-09 18:18:05.563 JupyterHub user:427] Unhandled error starting lta-uat-jupyter's server: 'pid'
[E 2018-01-09 18:18:05.624 JupyterHub web:1590] Uncaught exception GET /hub/user/lta-uat-jupyter/ (::ffff:10.8.95.244)
    HTTPServerRequest(protocol='http', host='10.8.111.211:8000', method='GET', uri='/hub/user/lta-uat-jupyter/', version='HTTP/1.1', remote_ip='::ffff:10.8.95.244', headers={'X-Forwarded-Host': '10.8.111.211:8000', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::ffff:10.8.95.244', 'Cookie': 'jupyter-hub-token="2|1:0|10:1515490653|17:jupyter-hub-token|44:NjY2OGQ4MWNmMTZjNGI0M2E3M2MwNjkzZWEwNjAyYzQ=|e905db91928f26865c82e8b864b42cbc69ad035f5dcc578bcb7efb031d83ddfb"', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36', 'Referer': 'http://10.8.111.211:8000/hub/home', 'Connection': 'close', 'Host': '10.8.111.211:8000'})
    Traceback (most recent call last):
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 720, in get
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), spawner._spawn_future)
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/lta-uat-jupyter/anaconda3/lib/python3.6/site-packages/sudospawner/spawner.py", line 92, in start
        self.pid = reply['pid']
    KeyError: 'pid'

[D 2018-01-09 18:18:05.627 JupyterHub base:633] No template for 500
[E 2018-01-09 18:18:05.634 JupyterHub log:114] {
      "X-Forwarded-Host": "10.8.111.211:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:10.8.95.244",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1515490653|17:jupyter-hub-token|44:NjY2OGQ4MWNmMTZjNGI0M2E3M2MwNjkzZWEwNjAyYzQ=|e905db91928f26865c82e8b864b42cbc69ad035f5dcc578bcb7efb031d83ddfb\"",
      "Accept-Language": "en-US,en;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36",
      "Referer": "http://10.8.111.211:8000/hub/home",
      "Connection": "close",
      "Host": "10.8.111.211:8000"
    }
Kindly let me know **_If anything OS compatibility issues, we are using SLES 11 Linux OS._**
Thanks in Advance.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
