### ISSUE TITLE
User Not Spawning Properly When Container Is Deleted

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#1632]
**How to reproduce the issue**

1. Run jupyterhub with dockerspawner.
1. Login to jupyterhub
1. Open a notebook
1. Delete the user container via `docker rm -f`
1. Refresh the browser tab containing notebook

**What you expected to happen**

The container to restart / to be created again.

**What actually happens**

Error message appears: 

_**503 : Service Unavailable
Your server appears to be down. Try restarting it from the hub**_

**Share what version of JupyterHub you are using**

Running docker logs sample:
```
[E 2018-01-25 16:36:39.247 JupyterHub web:1590] Uncaught exception GET /hub/user/admin/api/terminals?1516898198193 (172.18.0.1)
    HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/hub/user/admin/api/terminals?1516898198193', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'X-Forwarded-Host': 'localhost', 'X-Forwarded-Port': '443', 'Cookie': 'jupyter-hub-token="2|1:0|10:1516898167|17:jupyter-hub-token|44:MjlkNDU4ODYxOGM5NDdmNThkNzdiNGQ4ZDY4NGVkYmY=|a5bf7ef25b7ea3b617ae624ac09be45f79f5cebf4a4ef7c46f74a6ab82880843"; _ga=GA1.2.61604677.1516895019; _gid=GA1.2.101205250.1516895020; sf-jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcl9pZCI6MX0%3D.ibZeft%2BKS48UaAoO0o4GyM1yaVv6FCQLsRLfiiP0Ixw%3D; _xsrf=2|9f28cbcf|c0223421ff96c5d418b86fd0921b25b0|1516895060; _gat_client_tracker=1', 'Accept-Language': 'en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,bg;q=0.6,it;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://localhost/user/admin/lab?ct=lab&cid=2&fid=section-05%2F02-ItemBasedCF.ipynb', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36', 'X-Xsrftoken': '2|9f28cbcf|c0223421ff96c5d418b86fd0921b25b0|1516895060', 'X-Forwarded-Proto': 'https,https', 'X-Forwarded-For': '172.18.0.1,172.18.0.5', 'X-Real-Ip': '172.18.0.1', 'Host': 'localhost', 'Connection': 'upgrade'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 736, in get
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), spawner._spawn_future)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 458, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 444, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/srv/jupyterhub/dockerspawner/dockerspawner/dockerspawner.py", line 503, in start
        yield self.docker('start', self.container_id, **start_kwargs)
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/srv/jupyterhub/dockerspawner/dockerspawner/dockerspawner.py", line 340, in _docker
        return m(*args, **kwargs)
      File "/srv/jupyterhub/docker-py/docker/utils/decorators.py", line 21, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/srv/jupyterhub/docker-py/docker/api/container.py", line 383, in start
        self._raise_for_status(res)
      File "/srv/jupyterhub/docker-py/docker/client.py", line 174, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"OCI runtime create failed: container_linux.go:296: starting container process caused \\"exec: \\\\\\"start-singleuser.sh\\\\\\": executable file not found in $PATH\\": unknown"}'")
```

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
root@d1ee7f8fd3d1:/srv/jupyterhub# jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/opt/conda/bin
	/opt/conda/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/opt/conda/bin
	/opt/conda/lib/python36.zip
	/opt/conda/lib/python3.6
	/opt/conda/lib/python3.6/lib-dynload
	/opt/conda/lib/python3.6/site-packages
	/srv/jupyterhub/dockerspawner
	/srv/jupyterhub/docker-py
	/srv/jupyterhub/jwtauthenticator

sys.executable:
	/opt/conda/bin/python

sys.version:
	3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 21:42:08) 
	[GCC 7.2.0]

platform.platform():
	Linux-4.13.0-31-generic-x86_64-with-debian-8.10

which -a jupyter:
	/opt/conda/bin/jupyter
	/opt/conda/bin/jupyter

pip list:
	alembic (0.9.7)
	asn1crypto (0.22.0)
	bleach (2.1.2)
	certifi (2017.7.27.1)
	cffi (1.10.0)
	chardet (3.0.4)
	conda (4.4.6)
	cryptography (2.0.3)
	decorator (4.1.2)
	docker-py (1.10.6, /srv/jupyterhub/docker-py)
	docker-pycreds (0.2.1)
	dockerspawner (0.5.0, /srv/jupyterhub/dockerspawner)
	entrypoints (0.2.3)
	escapism (1.0.0)
	html5lib (1.0.1)
	idna (2.6)
	ipykernel (4.8.0)
	ipython (6.2.1)
	ipython-genutils (0.2.0)
	ipywidgets (7.1.1)
	jedi (0.11.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.2.2)
	jupyter-console (5.2.0)
	jupyter-core (4.4.0)
	jupyterhub (0.8.1.dev0)
	jupyterhub-jwtauthenticator (0.1, /srv/jupyterhub/jwtauthenticator)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	netifaces (0.10.6)
	notebook (5.3.1)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.1.1)
	pexpect (4.3.1)
	pickleshare (0.7.4)
	pip (9.0.1)
	prompt-toolkit (1.0.15)
	psycopg2 (2.7.3.2)
	ptyprocess (0.5.2)
	pycosat (0.6.3)
	pycparser (2.18)
	Pygments (2.2.0)
	pyOpenSSL (17.2.0)
	PySocks (1.6.7)
	python-dateutil (2.6.1)
	python-editor (1.0.3)
	python-oauth2 (1.0.1)
	pyzmq (16.0.4)
	qtconsole (4.3.1)
	requests (2.18.4)
	ruamel-yaml (0.11.14)
	Send2Trash (1.4.2)
	setuptools (36.5.0.post20170921)
	simplegeneric (0.8.1)
	six (1.10.0)
	SQLAlchemy (1.1.13)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (4.5.2)
	traitlets (4.3.2)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	websocket-client (0.46.0)
	wheel (0.29.0)
	widgetsnbextension (3.1.3)

conda list:
	# packages in environment at /opt/conda:
	#
	alembic                   0.9.7                     <pip>
	asn1crypto                0.22.0           py36h265ca7c_1  
	bleach                    2.1.2                     <pip>
	ca-certificates           2017.08.26           h1d4fec5_0  
	certifi                   2017.7.27.1      py36h8b7b77e_0  
	cffi                      1.10.0           py36had8d393_1  
	chardet                   3.0.4            py36h0f667ec_1  
	conda                     4.4.6                    py36_0  
	conda-env                 2.6.0                h36134e3_1  
	cryptography              2.0.3            py36ha225213_1  
	decorator                 4.1.2            py36hd076ac8_0  
	docker-py                 1.10.6                    <pip>
	docker-pycreds            0.2.1                     <pip>
	dockerspawner             0.5.0                     <pip>
	entrypoints               0.2.3                     <pip>
	escapism                  1.0.0                     <pip>
	html5lib                  1.0.1                     <pip>
	idna                      2.6              py36h82fb2a8_1  
	ipykernel                 4.8.0                     <pip>
	ipython                   6.2.1                     <pip>
	ipython_genutils          0.2.0            py36hb52b0d5_0  
	ipywidgets                7.1.1                     <pip>
	jedi                      0.11.1                    <pip>
	jinja2                    2.10             py36ha16c418_0  
	jsonschema                2.6.0                     <pip>
	jupyter                   1.0.0                     <pip>
	jupyter-client            5.2.2                     <pip>
	jupyter-console           5.2.0                     <pip>
	jupyter-core              4.4.0                     <pip>
	jupyterhub                0.8.1.dev0                <pip>
	jupyterhub-jwtauthenticator 0.1                       <pip>
	libedit                   3.1                  heed3624_0  
	libffi                    3.2.1                h4deb6c0_3  
	libgcc-ng                 7.2.0                h7cc24e2_2  
	libstdcxx-ng              7.2.0                h7a57d05_2  
	Mako                      1.0.7                     <pip>
	markupsafe                1.0              py36hd9260cd_1  
	mistune                   0.8.3                     <pip>
	nbconvert                 5.3.1                     <pip>
	nbformat                  4.4.0                     <pip>
	ncurses                   6.0                  h06874d7_1  
	netifaces                 0.10.6                    <pip>
	notebook                  5.3.1                     <pip>
	openssl                   1.0.2n               hb7f436b_0  
	pamela                    0.3.0                     <pip>
	pandocfilters             1.4.2                     <pip>
	parso                     0.1.1                     <pip>
	pexpect                   4.3.1                     <pip>
	pickleshare               0.7.4                     <pip>
	pip                       9.0.1            py36h6c6f9ce_4  
	prompt-toolkit            1.0.15                    <pip>
	psycopg2                  2.7.3.2                   <pip>
	ptyprocess                0.5.2                     <pip>
	pycosat                   0.6.3            py36h0a5515d_0  
	pycparser                 2.18             py36hf9f622e_1  
	Pygments                  2.2.0                     <pip>
	pyopenssl                 17.2.0           py36h5cc804b_0  
	pysocks                   1.6.7            py36hd97a5b1_1  
	python                    3.6.4                hc3d631a_0  
	python-dateutil           2.6.1                     <pip>
	python-editor             1.0.3                     <pip>
	python-oauth2             1.0.1                     <pip>
	pyzmq                     16.0.4                    <pip>
	qtconsole                 4.3.1                     <pip>
	readline                  7.0                  hac23ff0_3  
	requests                  2.18.4           py36he2e5f8d_1  
	ruamel_yaml               0.11.14          py36ha2fb22d_2  
	Send2Trash                1.4.2                     <pip>
	setuptools                36.5.0           py36he42e2e1_0  
	simplegeneric             0.8.1                     <pip>
	six                       1.10.0           py36hcac75e4_1  
	sqlalchemy                1.1.13           py36hfb5efd7_0  
	sqlite                    3.20.1               h6d8b0f3_1  
	terminado                 0.8.1                     <pip>
	testpath                  0.3.1                     <pip>
	tk                        8.6.7                h5979e9b_1  
	tornado                   4.5.2            py36h1283b2a_0  
	traitlets                 4.3.2            py36h674d592_0  
	urllib3                   1.22             py36hbe7ace6_0  
	wcwidth                   0.1.7                     <pip>
	webencodings              0.5.1                     <pip>
	websocket-client          0.46.0                    <pip>
	wheel                     0.29.0           py36he7f4e38_1  
	widgetsnbextension        3.1.3                     <pip>
	xz                        5.2.3                h2bcbf08_1  
	yaml                      0.1.7                h96e3832_1  
	zlib                      1.2.11               hfbfcf68_1
```

**Note**:
I think this happens because the container was deleted, but the state / session stays in the database. When the browser (notebook) is refreshed, the server tries to recover using the state from the database, but unsuccessfully, as there is no container anymore.

**Comment by katsar0v** [comment]
The issue is solved, error came from code edits made by me
