### ISSUE TITLE
HUB seems to die after a while

### ISSUE THREAD

**Issue by pgarapon** [jupyterhub/jupyterhub#1647]
Hi, 
I have jupyterhub set up with sudospawner and have been very happy with it. 
I recently had to renew my SSL certificate, and it seems that since the proxy server is unstable and dies after a few hours of being idle. 
I tracked the following error message, I don't thing any query is causing this, just no activity for a while.  

the jupyterhub server seems to have died, and the http proxy seem to have died, while the node server is still up. (if that makes any sense)

```
02:43:02.979 - error: [ConfigProxy] Failed to get custom error page Error: connect ECONNREFUSED 127.0.0.1:8081
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```
maybe a setting that is wrong or something ? using: 

jupyterhub v 0.8.0
node v6.11.0
configurable-http-proxy v 3.0.0

on ubuntu / digital ocean droplet.

**Comment by pgarapon** [comment]
it seems to have to do with the hub_ip being not accessible. I am not sure what to choose to make it visible ? I tried 10.10.10.10, but the hub would not start: 
```
[E 2018-02-05 02:19:14.566 JupyterHub app:1536] Failed to bind hub to http://10.10.10.10:8081/hub/
```

**Comment by pgarapon** [comment]
maybe I should try to force the single user servers to be local ? I am running on a digital ocean droplet, I would be surprised if it wasnt the case ?

**Comment by pgarapon** [comment]
I now seem to understand is that the hub is expected to be listening on port localhost:8081, it is all fine in the hour or two after the launch of the hub. (localhost:8081 is reachable with netmap and of course in the browser)
BUT it is the hub that seems to die after a while. I do not see anything in the log, maybe a configuration of my machine ? really bizarre. 

When I start jupyterhub, all is fine, the three servers are detected with telnet 
```
$ netstat -l | grep localhost
tcp        0      0 localhost:8001          *:*                     LISTEN     
tcp        0      0 localhost:53898         *:*                     LISTEN     
tcp        0      0 localhost:tproxy        *:*                     LISTEN 
```
and in fact localhost:8081 can be tested with netmap, but after a couple of hours, boom, the hub dies, with no trace in the log.

**Comment by pgarapon** [comment]
it looks like it is a hangup problem and as I learnt [here](https://askubuntu.com/questions/611968/differences-between-command-disown-and-nohup-command-disown), running jupyterhub & is not enough to protect from hangups, and disown is needed. 

Weird that it would sometimes happen even though the shell session is still alive, and that it would not occur in the previous 6 month or so.
