### ISSUE TITLE
Cannot start JupyterHub "Failed to start proxy"

### ISSUE THREAD

**Issue by whao** [jupyterhub/jupyterhub#1705]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub:

- Please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues)
  search feature to check if your issue has been asked already. If it has,
  please add your comments to the existing issue.

- Where applicable, please fill out the details below to help us troubleshoot
  the issue that you are facing. Please be as thorough as you are able to
  provide details on the issue.

**How to reproduce the issue**
I have followed the instructions and installed
```zsh
npm install -g configurable-http-proxy
pip3 install jupyterhub  
```
**What you expected to happen**
Starting up
**What actually happens**
```zsh
➜  ~ sudo jupyterhub
[I 2018-03-06 05:27:35.915 JupyterHub app:871] Writing cookie_secret to /home/{username}/jupyterhub_cookie_secret
[I 2018-03-06 05:27:35.929 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-03-06 05:27:35.929 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-03-06 05:27:35.932 alembic.runtime.migration migration:327] Running stamp_revision  -> 3ec6993fe20c
[W 2018-03-06 05:27:35.949 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-03-06 05:27:35.950 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-03-06 05:27:35.950 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-03-06 05:27:35.968 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-03-06 05:27:35.969 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-03-06 05:27:35.969 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-03-06 05:27:35.969 JupyterHub proxy:458] Starting proxy @ http://*:8000/
05:27:36.068 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
05:27:36.070 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[C 2018-03-06 05:27:47.545 JupyterHub app:1535] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/jupyterhub/app.py", line 1533, in start
        yield self.proxy.start()
      File "/usr/lib/python3.6/site-packages/jupyterhub/proxy.py", line 489, in start
        yield server.wait_up(1)
      File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 146, in wait_for_server
        timeout=timeout
      File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at {hostname}:8000 didn't respond in 1 seconds
```
**Share what version of JupyterHub you are using**
```zsh
➜  ~ sudo jupyterhub --version
0.8.1
```

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```

Insert jupyter troubleshoot output here
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/bin
	/sbin
	/bin
	/usr/sbin
	/usr/bin

sys.path:
	/usr/bin
	/usr/lib64/python36.zip
	/usr/lib64/python3.6
	/usr/lib64/python3.6/lib-dynload
	/usr/lib64/python3.6/site-packages
	/usr/lib/python3.6/site-packages

sys.executable:
	/usr/bin/python3.6

sys.version:
	3.6.4 (default, Dec 19 2017, 14:48:12)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

platform.platform():
	Linux-3.10.0-693.17.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core

which -a jupyter:
	/bin/jupyter
	/bin/jupyter
	/usr/bin/jupyter

pip list:
	alembic (0.9.8)
	astroid (1.6.1)
	autopep8 (1.3.4)
	bleach (2.1.2)
	certifi (2018.1.18)
	chardet (3.0.4)
	decorator (4.2.1)
	entrypoints (0.2.3)
	html5lib (1.0.1)
	idna (2.6)
	ipykernel (4.8.2)
	ipython (6.2.1)
	ipython-genutils (0.2.0)
	ipywidgets (7.1.2)
	isort (4.3.4)
	jedi (0.11.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.2.2)
	jupyter-console (5.2.0)
	jupyter-core (4.4.0)
	jupyterhub (0.8.1)
	lazy-object-proxy (1.3.1)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mccabe (0.6.1)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	notebook (5.4.0)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.1.1)
	pexpect (4.4.0)
	pickleshare (0.7.4)
	pip (9.0.1)
	prompt-toolkit (1.0.15)
	ptyprocess (0.5.2)
	pycodestyle (2.3.1)
	Pygments (2.2.0)
	pylint (1.8.2)
	python-dateutil (2.6.1)
	python-editor (1.0.3)
	python-oauth2 (1.1.0)
	pyzmq (17.0.0)
	qtconsole (4.3.1)
	requests (2.18.4)
	Send2Trash (1.5.0)
	setuptools (38.5.1)
	simplegeneric (0.8.1)
	six (1.11.0)
	speedtest-cli (2.0.0)
	SQLAlchemy (1.2.4)
	sudospawner (0.5.1)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (5.0)
	traitlets (4.3.2)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	widgetsnbextension (3.1.4)
	wrapt (1.10.11)

```

**Comment by whao** [comment]
Solved. Issue closed.

**Comment by perez1987** [comment]
what issue?¿ Please can you give details? Thx!

**Comment by amangarg96** [comment]
Hi, I am having the same issue. Could you please tell what solved the issue for you?
