### ISSUE TITLE
JupyterHub is running on EC2 instance, but unable to connect remotely from browser

### ISSUE THREAD

**Issue by justkar4u** [jupyterhub/jupyterhub#1738]
Hi All,

Trying to setup jupyter hub from scratch. Using Jupyterhub version 0.8.1, node version v6.13.1, RHEL 7
Stuck with below issue now. Any idea what am I missing ? Appreciate any help in advance !

**How to reproduce the issue**
When I start the ./jupyter from miniconda3/bin

**What you expected to happen**
I expect the jupyter server to initialize and be accessible remotely

**What actually happens**
```
[]$ ./jupyterhub --ip=10.240.27.175 --port=8000
[I 2018-03-22 18:39:53.513 JupyterHub app:834] Loading cookie_secret from /home/xyz/miniconda3/bin/jupyterhub_cookie_secret
[W 2018-03-22 18:39:53.531 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-03-22 18:39:53.531 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-03-22 18:39:53.531 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-03-22 18:39:53.560 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-03-22 18:39:53.561 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
[W 2018-03-22 18:39:53.561 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-03-22 18:39:53.561 JupyterHub proxy:458] Starting proxy @ http://10.240.27.175:8000/
18:39:53.745 - info: [ConfigProxy] Proxying http://10.240.27.175:8000 to (no default)
18:39:53.748 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
18:39:53.911 - info: [ConfigProxy] 200 GET /api/routes
[W 2018-03-22 18:39:53.911 JupyterHub proxy:304] Adding missing default route
[I 2018-03-22 18:39:53.911 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
18:39:53.917 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
18:39:53.918 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-03-22 18:39:53.919 JupyterHub app:1581] JupyterHub is now running at http://10.240.27.175:8000/
18:44:53.923 - info: [ConfigProxy] 200 GET /api/routes
18:49:53.923 - info: [ConfigProxy] 200 GET /api/routes
18:54:53.923 - info: [ConfigProxy] 200 GET /api/routes
18:59:53.922 - info: [ConfigProxy] 200 GET /api/routes
```

Debug Output:

```
[]$ ./jupyterhub --debug
[D 2018-03-22 19:15:10.409 JupyterHub application:555] Looking for jupyterhub_config in /home/xyz/miniconda3/bin
[D 2018-03-22 19:15:10.410 JupyterHub app:1343] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[I 2018-03-22 19:15:10.411 JupyterHub app:834] Loading cookie_secret from /home/xyz/miniconda3/bin/jupyterhub_cookie_secret
[D 2018-03-22 19:15:10.412 JupyterHub app:886] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2018-03-22 19:15:10.426 JupyterHub orm:504] database schema version found: 3ec6993fe20c
[W 2018-03-22 19:15:10.430 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-03-22 19:15:10.430 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-03-22 19:15:10.431 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[D 2018-03-22 19:15:10.452 JupyterHub app:1241] Loaded users:
[I 2018-03-22 19:15:10.459 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-03-22 19:15:10.460 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
[W 2018-03-22 19:15:10.460 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-03-22 19:15:10.460 JupyterHub proxy:458] Starting proxy @ http://*:8000/
[D 2018-03-22 19:15:10.461 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error']
19:15:10.643 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
19:15:10.647 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2018-03-22 19:15:11.016 JupyterHub proxy:491] Proxy started and appears to be up
[D 2018-03-22 19:15:11.017 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
19:15:11.028 - info: [ConfigProxy] 200 GET /api/routes
[W 2018-03-22 19:15:11.028 JupyterHub proxy:304] Adding missing default route
[I 2018-03-22 19:15:11.028 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2018-03-22 19:15:11.028 JupyterHub proxy:552] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
19:15:11.034 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
19:15:11.035 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-03-22 19:15:11.036 JupyterHub app:1581] JupyterHub is now running at http://:8000/

[]$ configurable-http-proxy
19:06:37.466 - warn: [ConfigProxy] REST API is not authenticated.
19:06:37.477 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
19:06:37.478 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes

[]$ netstat -an | grep 8081
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN
unix  3      [ ]         STREAM     CONNECTED     438081

This is my Jupyter Config file.
[jupyterhub_config.txt](https://github.com/jupyterhub/jupyterhub/files/1831842/jupyterhub_config.txt)

```

**Comment by justkar4u** [comment]
Hi @minrk , 
I have seen your posts on similar issues and tried them but it hasn't helped. Can you please help here?

1. Do I need to disable something explicitly on my Linux firewall?
2. Am I missing any other configuration ?

**Comment by minrk** [comment]
Are you able to connect to port 8000 (not 8081) from inside the machine?

**Comment by justkar4u** [comment]
Thanks @minrk . Seems like the Above issue was because of firewall. Now seeing "500 : Internal Server Error" issue.
```
[I 2018-03-27 20:20:52.782 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=49025
Failed to set groups [Errno 1] Operation not permitted
[E 2018-03-27 20:20:52.789 JupyterHub user:427] Unhandled error starting auraetl's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
[E 2018-03-27 20:20:52.800 JupyterHub web:1621] Uncaught exception GET /hub/user/auraetl/ (10.11.160.35)
    HTTPServerRequest(protocol='http', host='10.240.1.72:8000', method='GET', uri='/hub/user/auraetl/', version='HTTP/1.1', remote_ip='10.11.160.35')
    Traceback (most recent call last):
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 747, in get
        yield self.spawn_single_user(current_user)
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/auraetl/miniconda3/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/home/auraetl/miniconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 988, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/home/auraetl/miniconda3/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/home/auraetl/miniconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'

[E 2018-03-27 20:20:52.809 JupyterHub log:114] {
      "X-Forwarded-Host": "10.240.1.72:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "10.11.160.35",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1522181821|17:jupyter-hub-token|44:Y2Q1ODhiMjQyZjA5NGZiYzlhOGI4ZDRmYTIxY2FmODE=|17e4720e0db990d9008a97c00f1c17e2ade248bf7ef464731c7a6755eb6efdd6\"",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://10.240.1.72:8000/hub/home",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "10.240.1.72:8000"
    }
[E 2018-03-27 20:20:52.809 JupyterHub log:122] 500 GET /hub/user/auraetl/ (auraetl@10.11.160.35) 249.37ms
```

I changed the jupyter_config file as per your suggestion in  https://github.com/jupyterhub/jupyterhub/issues/598 but still having the issue.
