### ISSUE TITLE
delete faild 

### ISSUE THREAD

**Issue by liuzhliang** [jupyterhub/jupyterhub#1741]
delete faild  
Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute result = yield result File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run value = future.result() File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) File "<string>", line 4, in raise_exc_info File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper yielded = next(result) File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 235, in delete yield gen.maybe_future(cm.delete(path)) File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 278, in delete self.delete_file(path) File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 499, in delete_file send2trash(os_path) File "/usr/local/lib/python3.6/site-packages/send2trash/plat_other.py", line 185, in send2trash dest_trash = find_ext_volume_trash(topdir) File "/usr/local/lib/python3.6/site-packages/send2trash/plat_other.py", line 145, in find_ext_volume_trash trash_dir = find_ext_volume_fallback_trash(volume_root) File "/usr/local/lib/python3.6/site-packages/send2trash/plat_other.py", line 139, in find_ext_volume_fallback_trash check_create(trash_dir) File "/usr/local/lib/python3.6/site-packages/send2trash/plat_other.py", line 84, in check_create os.makedirs(dir, 0o700) File "/usr/local/lib/python3.6/os.py", line 220, in makedirs mkdir(name, mode) PermissionError: [Errno 13] Permission denied: b'/data/.Trash-1018'

**Comment by minrk** [comment]
Can you provide more information? What version of JupyterHub? What Spawner are you using? What OS? What version of Python? Can you include `conda list` and/or `pip list`?

This is related to the send2trash behavior, which is disabled in jupyterhub master by #1688

**Comment by liuzhliang** [comment]
CentOS Linux 


jupyterhub --version 0.8.1

Python 3.6.4 


![sc](https://user-images.githubusercontent.com/21074321/37892838-cb8cac8e-310b-11e8-84a1-ad9ecc07d3f5.png)
![def](https://user-images.githubusercontent.com/21074321/37892843-d2c3be84-310b-11e8-9761-4c9beef31442.png)

**Comment by liuzhliang** [comment]
@minrk

**Comment by minrk** [comment]
You can disable the trash mechanism by placing:

```python
c.FileContentsManager.delete_to_trash = False
```

in `/etc/jupyter/jupyter_notebook_config.py`

**Comment by liuzhliang** [comment]
@minrk  I have "c.F ileContentsManager. Delete_to_trash = False" written jupyter_notebook_config.Py but still delete faild

**Comment by elgalu** [comment]
@liuzhliang hopefully you are not adding those extra spaces? `c.F ile..` ??

You can also try to install latest JupyterHub from master branch:

```sh
ENV JUPYTERHUB_COMMIT="b26b1bc038029fe6ff790b195591ca48250fdd15"
RUN mkdir /tmp/clone && cd /tmp/clone \
 && git clone https://github.com/jupyterhub/jupyterhub \
 && cd jupyterhub \
 && git checkout ${JUPYTERHUB_COMMIT} -b "2018-04-02" \
 && npm install && ./bower-lite \
 && pip install --no-cache-dir --upgrade .
```

**Comment by willingc** [comment]
@liuzhliang Is this still an issue for you or can we close this? Thanks.
