### ISSUE TITLE
cant login gives 500 error 

### ISSUE THREAD

**Issue by Manjukb** [jupyterhub/jupyterhub#1752]
Hi! Thanks for using JupyterHub.
 
  
**What actually happens**
when i try to login i get 500 : Internal Server Error in web interface 

logs says 

```
[E 2018-03-26 17:47:19.135 JupyterHub web:1621] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/manju/.local/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
      File "/home/manju/jupyterhub/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/home/manju/jupyterhub/jupyterhub/handlers/base.py", line 429, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/manju/jupyterhub/jupyterhub/auth.py", line 228, in get_authenticated_user
        authenticated = await self.authenticate(handler, data)
      File "/usr/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/ldapauthenticator/ldapauthenticator.py", line 109, in authenticate
        if conn.bind():
      File "/usr/local/lib/python3.5/dist-packages/ldap3/core/connection.py", line 521, in bind
        self.open(read_server_info=False)
      File "/usr/local/lib/python3.5/dist-packages/ldap3/strategy/sync.py", line 56, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/usr/local/lib/python3.5/dist-packages/ldap3/strategy/base.py", line 149, in open
        raise LDAPSocketOpenError('invalid server address')
    ldap3.core.exceptions.LDAPSocketOpenError: invalid server address
    
[E 2018-03-26 17:47:19.175 JupyterHub log:126] {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
      "Connection": "keep-alive",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8081/hub/login",
      "Cookie": "JSESSIONID.9b4d66d0=node01kfh1d9pbwu011gx00taf15tpv0.node0; oauthenticator-state=\"2|1:0|10:1522045011|20:oauthenticator-state|120:ZXlKdVpYaDBYM1Z5YkNJNklDSWlMQ0FpYzNSaGRHVmZhV1FpT2lBaU5tRm1NV1UyTUdKa1lUZzVOR0l4TWpoaU16STVOR1l6TXpaak1UZGxPRElpZlE9PQ==|ce883412ac7c22c7ada895ddcdca25ad88beeb4631c0a66b904a473febb1b551\"",
      "Cache-Control": "max-age=0",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Host": "127.0.0.1:8081",
      "Origin": "http://127.0.0.1:8081",
      "Accept-Encoding": "gzip, deflate, br",
      "Upgrade-Insecure-Requests": "1",
      "Content-Length": "29"
    }
[E 2018-03-26 17:47:19.175 JupyterHub log:134] 500 POST /hub/login?next= (@127.0.0.1) 98.42ms
```

**Comment by ranjitiyer** [comment]
You should verify if LDAP is configured to connect to the correct server address

`ldap3.core.exceptions.LDAPSocketOpenError: invalid server address`

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
