### ISSUE TITLE
Permission denied when starting a new user server from admin console

### ISSUE THREAD

**Issue by PandaWhoCodes** [jupyterhub/jupyterhub#1762]
I tried running the bootstrap script to make default content everytime a new user starts a server, but I keep getting 
PermissionError: [Errno 13] Permission denied: '/home/test/.local
Test is the user that I created.
Im using the bootstrap.sh example on my Ubuntu 16.04 machine with the latest code taken from gi

**Comment by PandaWhoCodes** [comment]
```
shed exception=TimeoutError("Server at http://127.0.0.1:60920/user/test/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:60920/user/test/ didn't respond in 30 seconds

```

I created a new user from the admin panel and then started the server from the admin panel.
I keep getting this error even after I remove the custom spawner code

**Comment by willingc** [comment]
Hi @PandaWhoCodes, Can you provide a bit more information on your environment? Which authenticator and spawner are you using? Which JupyterHub version? Also providing contents of the debug log would be helpful. Thanks.

**Comment by PandaWhoCodes** [comment]
Localspawner
Latest release of jupyterhub

**Comment by willingc** [comment]
Hi there, Please try the latest JupyterHub release 0.9.3.

Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
