### ISSUE TITLE
[Windows] npm install fails on ./bower-lite

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#1773]
I'm trying to get things working on Windows with the latest jupyterhub master and get the below error from `npm install`
```
(jupyterhub) C:\dev\src\jupyterhub>npm install --unsafe-perm

> jupyterhub-deps@0.0.0 postinstall C:\dev\src\jupyterhub
> ./bower-lite

'.' is not recognized as an internal or external command,
operable program or batch file.

npm WARN jupyterhub-deps@0.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Miniconda3\\envs\\jupyterhub\\node.exe" "C:\\Miniconda3\\envs\\jupyterhub\\node_modules\\npm\\bin\\npm-cli.js" "install" "--unsafe-perm"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jupyterhub-deps@0.0.0 postinstall: `./bower-lite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyterhub-deps@0.0.0 postinstall script './bower-lite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyterhub-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bower-lite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterhub-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyterhub-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\src\jupyterhub\npm-debug.log
```

**Comment by dhirschfeld** [comment]
The end of the debug log:
```
11350 silly install runPostinstallTopLevelLifecycles
11351 silly build jupyterhub-deps@0.0.0
11352 info linkStuff jupyterhub-deps@0.0.0
11353 silly linkStuff jupyterhub-deps@0.0.0 has C:\dev\src as its parent node_modules
11354 verbose linkBins jupyterhub-deps@0.0.0
11355 verbose linkMans jupyterhub-deps@0.0.0
11356 silly install jupyterhub-deps@0.0.0 C:\dev\src\jupyterhub\jupyterhub-deps-16aa5975
11357 info lifecycle jupyterhub-deps@0.0.0~install: jupyterhub-deps@0.0.0
11358 silly lifecycle jupyterhub-deps@0.0.0~install: no script for install, continuing
11359 silly postinstall jupyterhub-deps@0.0.0 C:\dev\src\jupyterhub\jupyterhub-deps-16aa5975
11360 info lifecycle jupyterhub-deps@0.0.0~postinstall: jupyterhub-deps@0.0.0
11361 verbose lifecycle jupyterhub-deps@0.0.0~postinstall: unsafe-perm in lifecycle true
11362 verbose lifecycle jupyterhub-deps@0.0.0~postinstall: PATH: C:\Miniconda3\envs\jupyterhub\node_modules\npm\bin\node-gyp-bin;C:\dev\src\jupyterhub\node_modules\.bin;C:\Miniconda3\envs\jupyterhub;C:\Miniconda3\envs\jupyterhub\Library\mingw-w64\bin;C:\Miniconda3\envs\jupyterhub\Library\usr\bin;C:\Miniconda3\envs\jupyterhub\Library\bin;C:\Miniconda3\envs\jupyterhub\Scripts;C:\Miniconda3\envs\jupyterhub\bin;C:\Miniconda3;C:\Miniconda3\Library\mingw-w64\bin;C:\Miniconda3\Library\usr\bin;C:\Miniconda3\Library\bin;C:\Miniconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\bin\git\cmd;C:\bin\git\mingw64\bin;C:\bin\git\usr\bin;C:\Program Files\Docker;C:\Users\dhirschf\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code Insiders\bin
11363 verbose lifecycle jupyterhub-deps@0.0.0~postinstall: CWD: C:\dev\src\jupyterhub
11364 silly lifecycle jupyterhub-deps@0.0.0~postinstall: Args: [ '/d /s /c', './bower-lite' ]
11365 silly lifecycle jupyterhub-deps@0.0.0~postinstall: Returned: code: 1  signal: null
11366 info lifecycle jupyterhub-deps@0.0.0~postinstall: Failed to exec postinstall script
11367 warn jupyterhub-deps@0.0.0 license should be a valid SPDX license expression
11368 verbose If you need help, you may report this error at:
11368 verbose     <https://github.com/npm/npm/issues>
11369 verbose stack Error: jupyterhub-deps@0.0.0 postinstall: `./bower-lite`
11369 verbose stack Exit status 1
11369 verbose stack     at EventEmitter.<anonymous> (C:\Miniconda3\envs\jupyterhub\node_modules\npm\lib\utils\lifecycle.js:255:16)
11369 verbose stack     at emitTwo (events.js:106:13)
11369 verbose stack     at EventEmitter.emit (events.js:191:7)
11369 verbose stack     at ChildProcess.<anonymous> (C:\Miniconda3\envs\jupyterhub\node_modules\npm\lib\utils\spawn.js:40:14)
11369 verbose stack     at emitTwo (events.js:106:13)
11369 verbose stack     at ChildProcess.emit (events.js:191:7)
11369 verbose stack     at maybeClose (internal/child_process.js:920:16)
11369 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
11370 verbose pkgid jupyterhub-deps@0.0.0
11371 verbose cwd C:\dev\src\jupyterhub
11372 error Windows_NT 10.0.14393
11373 error argv "C:\\Miniconda3\\envs\\jupyterhub\\node.exe" "C:\\Miniconda3\\envs\\jupyterhub\\node_modules\\npm\\bin\\npm-cli.js" "install" "--unsafe-perm"
11374 error node v6.13.1
11375 error npm  v3.10.10
11376 error code ELIFECYCLE
11377 error jupyterhub-deps@0.0.0 postinstall: `./bower-lite`
11377 error Exit status 1
11378 error Failed at the jupyterhub-deps@0.0.0 postinstall script './bower-lite'.
11378 error Make sure you have the latest version of node.js and npm installed.
11378 error If you do, this is most likely a problem with the jupyterhub-deps package,
11378 error not with npm itself.
11378 error Tell the author that this fails on your system:
11378 error     ./bower-lite
11378 error You can get information on how to open an issue for this project with:
11378 error     npm bugs jupyterhub-deps
11378 error Or if that isn't available, you can get their info via:
11378 error     npm owner ls jupyterhub-deps
11378 error There is likely additional logging output above.
11379 verbose exit [ 1, true ]
```

**Comment by dhirschfeld** [comment]
The below patch seemed to do the job:
```patch
diff --git a/package.json b/package.json
index df99a7c..757d1d3 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
     "url": "https://github.com/jupyter/jupyterhub.git"
   },
   "scripts": {
-    "postinstall": "./bower-lite",
+    "postinstall": "python ./bower-lite",
     "lessc": "lessc"
   },
   "devDependencies": {
```
...not sure if that's a suitable cross-platform solution though?

On Windows at least it seemed to allow the install to complete:
```
(jupyterhub) C:\dev\src\jupyterhub>npm install --unsafe-perm

> jupyterhub-deps@0.0.0 postinstall C:\dev\src\jupyterhub
> python bower-lite

C:\dev\src\jupyterhub\node_modules\bootstrap -> C:\dev\src\jupyterhub\share\jupyterhub\static\components\bootstrap
C:\dev\src\jupyterhub\node_modules\font-awesome -> C:\dev\src\jupyterhub\share\jupyterhub\static\components\font-awesome
C:\dev\src\jupyterhub\node_modules\jquery -> C:\dev\src\jupyterhub\share\jupyterhub\static\components\jquery
C:\dev\src\jupyterhub\node_modules\moment -> C:\dev\src\jupyterhub\share\jupyterhub\static\components\moment
C:\dev\src\jupyterhub\node_modules\requirejs -> C:\dev\src\jupyterhub\share\jupyterhub\static\components\requirejs
npm WARN jupyterhub-deps@0.0.0 license should be a valid SPDX license expression
```
