### ISSUE TITLE
Running jupyterhub with dockerspawner "unable to fetch server API version (2,no such file or directory)

### ISSUE THREAD

**Issue by raghu20ram** [jupyterhub/jupyterhub#1837]
Hi ,
i am trying to use docker spawner in jupyterhub. I have added the below in the jupyterhub_config.py file 
```
# Configuration file for Jupyter Hub

c = get_config()

#from oauthenticator.github import LocalGitHubOAuthenticator
#c.JupyterHub.authenticator_class = LocalGitHubOAuthenticator
#c.LocalGitHubOAuthenticator.create_system_users = True


#c.JupyterHub.ssl_key = 'jupyterhub.key'
#c.JupyterHub.ssl_cert = 'jupyterhub.crt'

from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
from dockerspawner import DockerSpawner
c.JupyterHub.spawner_class = DockerSpawner

#c.DockerSpawner.image = "jupyterhub/singleuser"
#c.JupyterHub.port = 443
c.JupyterHub.cookie_secret_file = 'jupyterhub_cookie_secret'
#c.DockerSpawner.hub_ip_connect = '10.200.2.247'
#c.JupyterHub.hub_ip = '10.200.2.247'
#c.JupyterHub.proxy_api_ip = '0.0.0.0'
#c.JupyterHub.hub_ip = '0.0.0.0'
#c.DockerSpawner.notebook_dir = '/'
#c.DockerSpawner.default_url = '/tree/home/{username}'
c.DockerSpawner.volumes = {'jupyter-raghu20ram':'/home/jovyan/work'}
c.Authenticator.admin_users = {'raghu20ram'}
from jupyter_client.localinterfaces import public_ips
print(public_ips()[0])
c.JupyterHub.hub_ip = public_ips()[0]

#c.Spawner.args = ['--debug']
c.JupyterHub.log_level = 'DEBUG'
c.Spawner.debug = True
c.DockerSpawner.debug = True
#c.ConfigurableHTTPProxy.api_url = 'http://172.17.0.8'
#import os
#os.system('ifconfig')
#print(os.open('ifconfig'))
#from netifaces import AF_INET, AF_INET6, AF_LINK, AF_PACKET, AF_BRIDGE
#import netifaces
#print(netifaces.interfaces())

#import psutil
#print(psutil.net_if_addrs())
#import socket
#import fcntl
#import struct

#def get_ip_address(ifname):
    #s = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
    #return socket.inet_ntoa(fcntl.ioctl(
	#s.fileno(),
        #0x8915,
#        struct.pack('256s', ifname[:15].encode('utf-8'))
 #   )[20:24])

#print(get_ip_address('eth0'))


#docker0 = netifaces.ifaddresses('eth0')
#print('docker0')
#print(docker0)
#docker0_ipv4 = docker0[netifaces.AF_INET][0]
#print('docker0_ipv4')
#print(docker0_ipv4)
#c.JupyterHub.hub_ip = docker0_ipv4['addr']
#print('docker0_ipv4[addr]')
#print(docker0_ipv4['addr']) ```



After running jupyterhub with the above config config i am getting the below error:

```
[D 2018-04-27 12:14:53.583 JupyterHub base:421] Initiating spawn for raghu20ram
[D 2018-04-27 12:14:53.872 JupyterHub dockerspawner:444] Getting container 'jupyter-raghu20ram'
[D 2018-04-27 12:14:53.873 JupyterHub base:427] 0/100 concurrent spawns
[D 2018-04-27 12:14:53.873 JupyterHub base:430] 0 active servers
[E 2018-04-27 12:14:53.898 JupyterHub user:427] Unhandled error starting raghu20ram's server: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[D 2018-04-27 12:14:53.898 JupyterHub dockerspawner:444] Getting container 'jupyter-raghu20ram'
[E 2018-04-27 12:14:53.907 JupyterHub user:436] Failed to cleanup raghu20ram's server that failed to start
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 432, in spawn
        yield self.stop()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 501, in stop
        status = yield spawner.poll()
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 421, in poll
        container = yield self.get_container()
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 447, in get_container
        'inspect_container', self.container_name
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 408, in _docker
        m = getattr(self.client, method)
      File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 62, in client
        client = docker.APIClient(**kwargs)
      File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 154, in __init__
        self._version = self._retrieve_server_version()
      File "/opt/conda/lib/python3.6/site-packages/docker/api/client.py", line 179, in _retrieve_server_version
        'Error while fetching server API version: {0}'.format(e)
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by raghu20ram** [comment]
by the way,Iam using 'jupyterhub/singleuser' docker image

**Comment by sangramga** [comment]
``c.JupyterHub.spawner_class = DockerSpawner``  
This config seems to be incorrect. Try changing it to the following 
``c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner' ``

**Comment by raghu20ram** [comment]
hi @willingc  , i have solved the above problem by adding -v /var/run/docker.sock:var/run/docker.sock to my docker run command. Now, after every successful login a container is being created with respective username. The problem is after creating the container i am able to see a log message saying "Waiting for pending spawn" and after a while i am able to see the below error, and there is 500 error on the browser.
````
[E 2018-05-02 06:45:25.560 JupyterHub gen:940] Exception in Future <Future finished exception=TimeoutError("Server at http://127.0.0.1:32789/user/aananth123/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32789/user/aananth123/ didn't respond in 30 seconds
    
[E 2018-05-02 06:45:25.564 JupyterHub gen:940] Exception in Future <Future finished exception=TimeoutError("Server at http://127.0.0.1:32789/user/aananth123/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32789/user/aananth123/ didn't respond in 30 seconds
    
[E 2018-05-02 06:45:25.565 JupyterHub web:1621] Uncaught exception GET /hub/user/aananth123/ (::ffff:10.200.2.247)
    HTTPServerRequest(protocol='https', host='10.200.0.87:8003', method='GET', uri='/hub/user/aananth123/', version='HTTP/1.1', remote_ip='::ffff:10.200.2.247')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 720, in get
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), spawner._spawn_future)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32789/user/aananth123/ didn't respond in 30 seconds
```
please suggest a solution for this error

**Comment by sangramga** [comment]
Which version of Docker are you using? Please make sure that Docker is installed properly and docker daemon is running. 
Also specify Dockerspawner and jupyterhub version.

**Comment by Vadims06** [comment]
hi @raghu20ram , I faced with the same issue. Pls specify when and how did you specify '-v /var/run/docker.sock:var/run/docker.sock' command?

**Comment by raghu20ram** [comment]
@Vadims06 append -v /var/run/docker.sock:var/run/docker.sock to your docker run command which you use to create the conatiner
