### ISSUE TITLE
Conda environment creation from jupyter failing (JSON parse issue)

### ISSUE THREAD

**Issue by tikenn** [jupyterhub/jupyterhub#1844]
Hi, I have recently spent a few days troubleshooting this issue and have had limited success with a few variations.  My objective is to get a jupyterhub installation running that can create conda environments with the assistance of `nb_conda`, `nb_conda_kernels`, and `ipykernel`.  While I have had success in the past, it seems some updates might have broken a few things.  I know that `nb_conda` was recently updated, so I apologize if this is not a jupyterhub issue.  Below is the final iteration that I have tried that still seems to fail but comes the closest in that the conda environment does get created with an error on the UI and a JSON parse error in server log.

**How to reproduce the issue**
- Install anaconda3 in `/opt/anaconda3` on Ubuntu Server 16.04
- Add `/opt/anaconda3/bin` to beginning of `path` in `/etc/environment`
- Create .condarc file in jupyter user's home directory with the following content
```
channels:
  - defaults
  - conda-forge
create_default_packages:
  - pip
  - ipykernel
  - nb_conda
  - nb_conda_kernels
ssl_verify: true
envs_dirs:
  - ~/.conda/envs
```
- Install jupyterhub following [quickstart](https://jupyterhub.readthedocs.io/en/latest/quickstart.html) using `conda` and local notebooks
- Create jupyterhub config file in `/etc/jupyterhub`
- Bind IP address to local IP (not 127.0.0.1)
- Add startup script as defined [here](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#ubuntudebian-anaconda3-with-systemd) putting `/opt/anaconda3/bin` at the beginning of path
- Apply `nb_conda` fix described [here](https://github.com/Anaconda-Platform/nb_conda/issues/66#issuecomment-363212868)
- Startup jupyterhub and navigate to hub in browser
- Navigate to conda tab and create environment called 'test'

**What you expected to happen**
I expected a new environment called 'test' to be displayed in the list of environments in addition to 'root'

**What actually happens**
Instead, the following happens:
- An error message is displayed in the browser as shown in the screenshot
![jupyterhub conda environment error](https://user-images.githubusercontent.com/8184994/39491990-b2a1b552-4d53-11e8-80df-90cfd4fe0518.PNG)
- The conda environment actually gets created (shows up as a folder in `~/.conda/envs` and a browser refresh reveals the environment)
- Server log shows a JSON parse error
```
[W 2018-05-01 15:20:38.975 SingleUserNotebookApp envmanager:99] [nb_conda] JSON parse fail:
    Extra data: line 16 column 1 (char 1090)
[E 2018-05-01 15:20:38.976 SingleUserNotebookApp web:1621] Uncaught exception POST /user/tikenn/conda/environments/test/create (192.168.56.105)
    HTTPServerRequest(protocol='http', host='192.168.56.101:8000', method='POST', uri='/user/tikenn/conda/environments/test/create', version='HTTP/1.1', remote_ip='192.168.56.105')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 2949, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 670, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/nb_conda/handlers.py", line 101, in post
        data = self.env_manager.create_env(env, env_type)
      File "/opt/anaconda3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 123, in create_env
        return self.clean_conda_json(output)
      File "/opt/anaconda3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 102, in clean_conda_json
        lines = [line for line in lines if re.match(JSONISH_RE)]
      File "/opt/anaconda3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 102, in <listcomp>
        lines = [line for line in lines if re.match(JSONISH_RE)]
    TypeError: match() missing 1 required positional argument: 'string'
[W 2018-05-01 15:20:38.979 SingleUserNotebookApp handlers:525] Unhandled error
[E 2018-05-01 15:20:38.980 SingleUserNotebookApp log:114] {
      "X-Forwarded-Host": "192.168.56.101:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "192.168.56.105",
      "Cookie": "user-tikenn=2|1:0|10:1525205894|11:user-tikenn|48:ODQwNDNkN2MtNDAzMS00MzM4LTg3Y2QtOGQwMzc0NGE5ZDY5|d2fd4aa9ba1a56754aab9e04d929079174bf0bf864fe0b7d6c5b081d1cfc93ca; _xsrf=2|9c45c838|5d563a3460e8e234d71cc6187c12d526|1524255356",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://192.168.56.101:8000/user/tikenn/tree?",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36",
      "X-Xsrftoken": "2|9c45c838|5d563a3460e8e234d71cc6187c12d526|1524255356",
      "X-Requested-With": "XMLHttpRequest",
      "Origin": "http://192.168.56.101:8000",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Content-Length": "12",
      "Connection": "close",
      "Host": "192.168.56.101:8000"
    }
```

**Share what version of JupyterHub you are using**
0.8.1

`jupyter troubleshoot` output:
```
$PATH:
	/opt/anaconda3/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/opt/anaconda3/bin

sys.path:
	/opt/anaconda3/bin
	/opt/anaconda3/lib/python36.zip
	/opt/anaconda3/lib/python3.6
	/opt/anaconda3/lib/python3.6/lib-dynload
	/opt/anaconda3/lib/python3.6/site-packages
	/opt/anaconda3/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg

sys.executable:
	/opt/anaconda3/bin/python

sys.version:
	3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
	[GCC 7.2.0]

platform.platform():
	Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid

which -a jupyter:
	/opt/anaconda3/bin/jupyter
	/opt/anaconda3/bin/jupyter

pip list:
	Package                            Version  
	---------------------------------- ---------
	alabaster                          0.7.10   
	alembic                            0.9.9    
	anaconda-client                    1.6.14   
	anaconda-navigator                 1.8.4    
	anaconda-project                   0.8.2    
	asn1crypto                         0.24.0   
	astroid                            1.6.3    
	astropy                            3.0.2    
	attrs                              17.4.0   
	Babel                              2.5.3    
	backcall                           0.1.0    
	backports.shutil-get-terminal-size 1.0.0    
	beautifulsoup4                     4.6.0    
	bitarray                           0.8.1    
	bkcharts                           0.2      
	blaze                              0.11.3   
	bleach                             2.1.3    
	bokeh                              0.12.15  
	boto                               2.48.0   
	Bottleneck                         1.2.1    
	certifi                            2018.4.16
	cffi                               1.11.5   
	chardet                            3.0.4    
	click                              6.7      
	cloudpickle                        0.5.2    
	clyent                             1.2.2    
	colorama                           0.3.9    
	conda                              4.5.1    
	conda-build                        3.10.0   
	conda-verify                       2.0.0    
	contextlib2                        0.5.5    
	cryptography                       2.2.2    
	cycler                             0.10.0   
	Cython                             0.28.2   
	cytoolz                            0.9.0.1  
	dask                               0.17.2   
	datashape                          0.5.4    
	decorator                          4.3.0    
	distributed                        1.21.6   
	docutils                           0.14     
	entrypoints                        0.2.3    
	et-xmlfile                         1.0.1    
	fastcache                          1.0.2    
	filelock                           3.0.4    
	Flask                              0.12.2   
	Flask-Cors                         3.0.3    
	gevent                             1.2.2    
	glob2                              0.6      
	gmpy2                              2.0.8    
	greenlet                           0.4.13   
	h5py                               2.7.1    
	heapdict                           1.0.0    
	html5lib                           1.0.1    
	idna                               2.6      
	imageio                            2.3.0    
	imagesize                          1.0.0    
	ipykernel                          4.8.2    
	ipython                            6.3.1    
	ipython-genutils                   0.2.0    
	ipywidgets                         7.2.1    
	isort                              4.3.4    
	itsdangerous                       0.24     
	jdcal                              1.4      
	jedi                               0.12.0   
	Jinja2                             2.10     
	jsonschema                         2.6.0    
	jupyter                            1.0.0    
	jupyter-client                     5.2.3    
	jupyter-console                    5.2.0    
	jupyter-core                       4.4.0    
	jupyterhub                         0.8.1    
	jupyterlab                         0.32.1   
	jupyterlab-launcher                0.10.5   
	kiwisolver                         1.0.1    
	lazy-object-proxy                  1.3.1    
	llvmlite                           0.22.0   
	locket                             0.2.0    
	lxml                               4.2.1    
	Mako                               1.0.7    
	MarkupSafe                         1.0      
	matplotlib                         2.2.2    
	mccabe                             0.6.1    
	mistune                            0.8.3    
	mkl-fft                            1.0.0    
	mkl-random                         1.0.1    
	more-itertools                     4.1.0    
	mpmath                             1.0.0    
	msgpack-python                     0.5.6    
	multipledispatch                   0.5.0    
	navigator-updater                  0.1.0    
	nb-anacondacloud                   1.4.0    
	nb-conda                           2.2.1    
	nb-conda-kernels                   2.1.0    
	nbconvert                          5.3.1    
	nbformat                           4.4.0    
	nbpresent                          3.0.2    
	networkx                           2.1      
	nltk                               3.2.5    
	nose                               1.3.7    
	notebook                           5.4.1    
	numba                              0.37.0   
	numexpr                            2.6.4    
	numpy                              1.14.2   
	numpydoc                           0.8.0    
	odo                                0.5.1    
	olefile                            0.45.1   
	openpyxl                           2.5.3    
	packaging                          17.1     
	pamela                             0.3.0    
	pandas                             0.22.0   
	pandocfilters                      1.4.2    
	parso                              0.2.0    
	partd                              0.3.8    
	path.py                            11.0.1   
	pathlib2                           2.3.2    
	patsy                              0.5.0    
	pep8                               1.7.1    
	pexpect                            4.5.0    
	pickleshare                        0.7.4    
	Pillow                             5.1.0    
	pip                                10.0.1   
	pkginfo                            1.4.2    
	pluggy                             0.6.0    
	ply                                3.11     
	prompt-toolkit                     1.0.15   
	psutil                             5.4.5    
	ptyprocess                         0.5.2    
	py                                 1.5.3    
	pycodestyle                        2.4.0    
	pycosat                            0.6.3    
	pycparser                          2.18     
	pycrypto                           2.6.1    
	pycurl                             7.43.0.1 
	pyflakes                           1.6.0    
	Pygments                           2.2.0    
	pylint                             1.8.4    
	pyodbc                             4.0.23   
	pyOpenSSL                          17.5.0   
	pyparsing                          2.2.0    
	PySocks                            1.6.8    
	pytest                             3.5.1    
	pytest-arraydiff                   0.2      
	pytest-astropy                     0.3.0    
	pytest-doctestplus                 0.1.3    
	pytest-openfiles                   0.3.0    
	pytest-remotedata                  0.2.1    
	python-dateutil                    2.7.2    
	python-editor                      1.0.3    
	python-oauth2                      1.0.1    
	pytz                               2018.4   
	PyWavelets                         0.5.2    
	PyYAML                             3.12     
	pyzmq                              17.0.0   
	QtAwesome                          0.4.4    
	qtconsole                          4.3.1    
	QtPy                               1.4.0    
	requests                           2.18.4   
	rope                               0.10.7   
	ruamel-yaml                        0.15.35  
	scikit-image                       0.13.1   
	scikit-learn                       0.19.1   
	scipy                              1.0.1    
	seaborn                            0.8.1    
	Send2Trash                         1.5.0    
	setuptools                         39.1.0   
	simplegeneric                      0.8.1    
	singledispatch                     3.4.0.3  
	six                                1.11.0   
	snowballstemmer                    1.2.1    
	sortedcollections                  0.6.1    
	sortedcontainers                   1.5.10   
	Sphinx                             1.7.4    
	sphinxcontrib-websupport           1.0.1    
	spyder                             3.2.8    
	SQLAlchemy                         1.2.7    
	statsmodels                        0.8.0    
	sympy                              1.1.1    
	tables                             3.4.3    
	tblib                              1.3.2    
	terminado                          0.8.1    
	testpath                           0.3.1    
	toolz                              0.9.0    
	tornado                            5.0.2    
	traitlets                          4.3.2    
	typing                             3.6.4    
	unicodecsv                         0.14.1   
	urllib3                            1.22     
	wcwidth                            0.1.7    
	webencodings                       0.5.1    
	Werkzeug                           0.14.1   
	wheel                              0.31.0   
	widgetsnbextension                 3.2.1    
	wrapt                              1.10.11  
	xlrd                               1.1.0    
	XlsxWriter                         1.0.4    
	xlwt                               1.3.0    
	zict                               0.1.3

conda list:
	# packages in environment at /opt/anaconda3:
	#
	# Name                    Version                   Build  Channel
	_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0  
	_nb_ext_conf              0.4.0                    py36_1  
	alabaster                 0.7.10           py36h306e16b_0  
	alembic                   0.9.9                      py_0    conda-forge
	anaconda                  custom           py36hbbc8b67_0  
	anaconda-client           1.6.14                   py36_0  
	anaconda-navigator        1.8.4                    py36_0  
	anaconda-project          0.8.2            py36h44fb852_0  
	asn1crypto                0.24.0                   py36_0  
	astroid                   1.6.3                    py36_0  
	astropy                   3.0.2            py36h3010b51_1  
	attrs                     17.4.0                   py36_0  
	babel                     2.5.3                    py36_0  
	backcall                  0.1.0                    py36_0  
	backports                 1.0              py36hfa02d7e_1  
	backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
	beautifulsoup4            4.6.0            py36h49b8c8c_1  
	bitarray                  0.8.1            py36h14c3975_1  
	bkcharts                  0.2              py36h735825a_0  
	blaze                     0.11.3           py36h4e06776_0  
	bleach                    2.1.3                    py36_0  
	blosc                     1.14.3               hdbcaa40_0  
	bokeh                     0.12.15                  py36_0  
	boto                      2.48.0           py36h6e4cd66_1  
	bottleneck                1.2.1            py36haac1ea0_0  
	bzip2                     1.0.6                h9a117a8_4  
	ca-certificates           2018.03.07                    0  
	cairo                     1.14.12              h7636065_2  
	certifi                   2018.4.16                py36_0  
	cffi                      1.11.5           py36h9745a5d_0  
	chardet                   3.0.4            py36h0f667ec_1  
	click                     6.7              py36h5253387_0  
	cloudpickle               0.5.2                    py36_1  
	clyent                    1.2.2            py36h7e57e65_1  
	colorama                  0.3.9            py36h489cec4_0  
	conda                     4.5.1                    py36_0  
	conda-build               3.10.0                   py36_0  
	conda-env                 2.6.0                h36134e3_1  
	conda-verify              2.0.0            py36h98955d8_0  
	configurable-http-proxy   3.1.0                   node8_1    conda-forge
	contextlib2               0.5.5            py36h6c84a62_0  
	cryptography              2.2.2            py36h14c3975_0  
	curl                      7.59.0               h84994c4_0  
	cycler                    0.10.0           py36h93f1223_0  
	cython                    0.28.2           py36h14c3975_0  
	cytoolz                   0.9.0.1          py36h14c3975_0  
	dask                      0.17.2                   py36_0  
	dask-core                 0.17.2                   py36_0  
	datashape                 0.5.4            py36h3ad6b5c_0  
	dbus                      1.13.2               h714fa37_1  
	decorator                 4.3.0                    py36_0  
	distributed               1.21.6                   py36_0  
	docutils                  0.14             py36hb0f60f5_0  
	entrypoints               0.2.3            py36h1aec115_2  
	et_xmlfile                1.0.1            py36hd6bccc3_0  
	expat                     2.2.5                he0dffb1_0  
	fastcache                 1.0.2            py36h14c3975_2  
	filelock                  3.0.4                    py36_0  
	flask                     0.12.2           py36hb24657c_0  
	flask-cors                3.0.3            py36h2d857d3_0  
	fontconfig                2.12.6               h49f89f6_0  
	freetype                  2.8                  hab7d2ae_1  
	get_terminal_size         1.0.0                haa9412d_0  
	gevent                    1.2.2            py36h2fe25dc_0  
	glib                      2.56.1               h000015b_0  
	glob2                     0.6              py36he249c77_0  
	gmp                       6.1.2                h6c8ec71_1  
	gmpy2                     2.0.8            py36hc8893dd_2  
	graphite2                 1.3.11               hf63cedd_1  
	greenlet                  0.4.13           py36h14c3975_0  
	gst-plugins-base          1.14.0               hbbd80ab_1  
	gstreamer                 1.14.0               hb453b48_1  
	h5py                      2.7.1            py36h3585f63_0  
	harfbuzz                  1.7.6                h5f0a787_1  
	hdf5                      1.10.1               h9caa474_1  
	heapdict                  1.0.0                    py36_2  
	html5lib                  1.0.1            py36h2f9c1c0_0  
	icu                       58.2                 h9c2bf20_1  
	idna                      2.6              py36h82fb2a8_1  
	imageio                   2.3.0                    py36_0  
	imagesize                 1.0.0                    py36_0  
	intel-openmp              2018.0.0                      8  
	ipykernel                 4.8.2                    py36_0  
	ipython                   6.3.1                    py36_0  
	ipython_genutils          0.2.0            py36hb52b0d5_0  
	ipywidgets                7.2.1                    py36_0  
	isort                     4.3.4                    py36_0  
	itsdangerous              0.24             py36h93cc618_1  
	jbig                      2.1                  hdba287a_0  
	jdcal                     1.4                      py36_0  
	jedi                      0.12.0                   py36_1  
	jinja2                    2.10             py36ha16c418_0  
	jpeg                      9b                   h024ee3a_2  
	jsonschema                2.6.0            py36h006f8b5_0  
	jupyter                   1.0.0                    py36_4  
	jupyter_client            5.2.3                    py36_0  
	jupyter_console           5.2.0            py36he59e554_1  
	jupyter_core              4.4.0            py36h7c827e3_0  
	jupyterhub                0.8.1                    py36_0    conda-forge
	jupyterlab                0.32.1                   py36_0  
	jupyterlab_launcher       0.10.5                   py36_0  
	kiwisolver                1.0.1            py36h764f252_0  
	lazy-object-proxy         1.3.1            py36h10fcdad_0  
	libcurl                   7.59.0               h1ad7b7a_0  
	libedit                   3.1                  heed3624_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc                    7.2.0                h69d50b8_2  
	libgcc-ng                 7.2.0                hdf63c60_3  
	libgfortran-ng            7.2.0                hdf63c60_3  
	libpng                    1.6.34               hb9fc6fc_0  
	libsodium                 1.0.16               h1bed415_0  
	libssh2                   1.8.0                h9cfc8f7_4  
	libstdcxx-ng              7.2.0                hdf63c60_3  
	libtiff                   4.0.9                h28f6b97_0  
	libtool                   2.4.6                h544aabb_3  
	libxcb                    1.13                 h1bed415_1  
	libxml2                   2.9.8                hf84eae3_0  
	libxslt                   1.1.32               h1312cb7_0  
	llvmlite                  0.22.0           py36ha27ea49_0  
	locket                    0.2.0            py36h787c0ad_1  
	lxml                      4.2.1            py36h23eabaa_0  
	lzo                       2.10                 h49e0be7_2  
	mako                      1.0.7                    py36_0    conda-forge
	markupsafe                1.0              py36hd9260cd_1  
	matplotlib                2.2.2            py36h0e671d2_1  
	mccabe                    0.6.1            py36h5ad9710_1  
	mistune                   0.8.3            py36h14c3975_1  
	mkl                       2018.0.2                      1  
	mkl-service               1.1.2            py36h17a0993_4  
	mkl_fft                   1.0.1            py36h3010b51_0  
	mkl_random                1.0.1            py36h629b387_0  
	more-itertools            4.1.0                    py36_0  
	mpc                       1.0.3                hec55b23_5  
	mpfr                      3.1.5                h11a74b3_2  
	mpmath                    1.0.0            py36hfeacd6b_2  
	msgpack-python            0.5.6            py36h6bb024c_0  
	multipledispatch          0.5.0                    py36_0  
	navigator-updater         0.1.0            py36h14770f7_0  
	nb_anacondacloud          1.4.0                    py36_0  
	nb_conda                  2.2.1            py36h8118bb2_0  
	nb_conda_kernels          2.1.0                    py36_0  
	nbconvert                 5.3.1            py36hb41ffb7_0  
	nbformat                  4.4.0            py36h31c9010_0  
	nbpresent                 3.0.2            py36h5f95a39_1  
	ncurses                   6.0                  h9df7e31_2  
	networkx                  2.1                      py36_0  
	nltk                      3.2.5            py36h7532b22_0  
	nodejs                    8.10.0                        0    conda-forge
	nose                      1.3.7            py36hcdf7029_2  
	notebook                  5.4.1                    py36_0  
	numba                     0.37.0          np114py36h5fcf951_0  
	numexpr                   2.6.4            py36hc4a3f9a_0  
	numpy                     1.14.2           py36hdbf6ddf_1  
	numpydoc                  0.8.0                    py36_0  
	odo                       0.5.1            py36h90ed295_0  
	olefile                   0.45.1                   py36_0  
	openpyxl                  2.5.3                    py36_0  
	openssl                   1.0.2o               h20670df_0  
	packaging                 17.1                     py36_0  
	pamela                    0.3.0                    py36_0    conda-forge
	pandas                    0.22.0           py36hf484d3e_0  
	pandoc                    1.19.2.1             hea2e7c5_1  
	pandocfilters             1.4.2            py36ha6701b7_1  
	pango                     1.41.0               hd475d92_0  
	parso                     0.2.0                    py36_0  
	partd                     0.3.8            py36h36fd896_0  
	patchelf                  0.9                  hf79760b_2  
	path.py                   11.0.1                   py36_0  
	pathlib2                  2.3.2                    py36_0  
	patsy                     0.5.0                    py36_0  
	pcre                      8.42                 h439df22_0  
	pep8                      1.7.1                    py36_0  
	pexpect                   4.5.0                    py36_0  
	pickleshare               0.7.4            py36h63277f8_0  
	pillow                    5.1.0            py36h3deb7b8_0  
	pip                       10.0.1                   py36_0  
	pixman                    0.34.0               hceecf20_3  
	pkginfo                   1.4.2                    py36_1  
	pluggy                    0.6.0            py36hb689045_0  
	ply                       3.11                     py36_0  
	prompt_toolkit            1.0.15           py36h17d85b1_0  
	psutil                    5.4.5            py36h14c3975_0  
	ptyprocess                0.5.2            py36h69acd42_0  
	py                        1.5.3                    py36_0  
	pycodestyle               2.4.0                    py36_0  
	pycosat                   0.6.3            py36h0a5515d_0  
	pycparser                 2.18             py36hf9f622e_1  
	pycrypto                  2.6.1            py36h14c3975_7  
	pycurl                    7.43.0.1         py36hb7f436b_0  
	pyflakes                  1.6.0            py36h7bd6a15_0  
	pygments                  2.2.0            py36h0d3125c_0  
	pylint                    1.8.4                    py36_0  
	pyodbc                    4.0.23           py36hf484d3e_0  
	pyopenssl                 17.5.0           py36h20ba746_0  
	pyparsing                 2.2.0            py36hee85983_1  
	pyqt                      5.9.2            py36h751905a_0  
	pysocks                   1.6.8                    py36_0  
	pytables                  3.4.3            py36h02b9ad4_0  
	pytest                    3.5.1                    py36_0  
	pytest-arraydiff          0.2                      py36_0  
	pytest-astropy            0.3.0                    py36_0  
	pytest-doctestplus        0.1.3                    py36_0  
	pytest-openfiles          0.3.0                    py36_0  
	pytest-remotedata         0.2.1                    py36_0  
	python                    3.6.5                hc3d631a_2  
	python-dateutil           2.7.2                    py36_0  
	python-editor             1.0.3                    py36_0    conda-forge
	python-oauth2             1.0.1                    py36_0    conda-forge
	pytz                      2018.4                   py36_0  
	pywavelets                0.5.2            py36he602eb0_0  
	pyyaml                    3.12             py36hafb9ca4_1  
	pyzmq                     17.0.0           py36h14c3975_0  
	qt                        5.9.5                h7e424d6_0  
	qtawesome                 0.4.4            py36h609ed8c_0  
	qtconsole                 4.3.1            py36h8f73b5b_0  
	qtpy                      1.4.0                    py36_0  
	readline                  7.0                  ha6073c6_4  
	requests                  2.18.4           py36he2e5f8d_1  
	rope                      0.10.7           py36h147e2ec_0  
	ruamel_yaml               0.15.35          py36h14c3975_1  
	scikit-image              0.13.1           py36h14c3975_1  
	scikit-learn              0.19.1           py36h7aa7ec6_0  
	scipy                     1.0.1            py36hfc37229_0  
	seaborn                   0.8.1            py36hfad7ec4_0  
	send2trash                1.5.0                    py36_0  
	setuptools                39.1.0                   py36_0  
	simplegeneric             0.8.1                    py36_2  
	singledispatch            3.4.0.3          py36h7a266c3_0  
	sip                       4.19.8           py36hf484d3e_0  
	six                       1.11.0           py36h372c433_1  
	snappy                    1.1.7                hbae5bb6_3  
	snowballstemmer           1.2.1            py36h6febd40_0  
	sortedcollections         0.6.1                    py36_0  
	sortedcontainers          1.5.10                   py36_0  
	sphinx                    1.7.4                    py36_0  
	sphinxcontrib             1.0              py36h6d0f590_1  
	sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
	spyder                    3.2.8                    py36_0  
	sqlalchemy                1.2.7            py36h6b74fdf_0  
	sqlite                    3.23.1               he433501_0  
	statsmodels               0.8.0            py36h8533d0b_0  
	sympy                     1.1.1            py36hc6d1c1c_0  
	tblib                     1.3.2            py36h34cf8b6_0  
	terminado                 0.8.1                    py36_1  
	testpath                  0.3.1            py36h8cadb63_0  
	tk                        8.6.7                hc745277_3  
	toolz                     0.9.0                    py36_0  
	tornado                   5.0.2                    py36_0  
	traitlets                 4.3.2            py36h674d592_0  
	typing                    3.6.4                    py36_0  
	unicodecsv                0.14.1           py36ha668878_0  
	unixodbc                  2.3.6                h1bed415_0  
	urllib3                   1.22             py36hbe7ace6_0  
	wcwidth                   0.1.7            py36hdf4376a_0  
	webencodings              0.5.1            py36h800622e_1  
	werkzeug                  0.14.1                   py36_0  
	wheel                     0.31.0                   py36_0  
	widgetsnbextension        3.2.1                    py36_0  
	wrapt                     1.10.11          py36h28b7045_0  
	xlrd                      1.1.0            py36h1db9f0c_1  
	xlsxwriter                1.0.4                    py36_0  
	xlwt                      1.3.0            py36h7b00a1f_0  
	xz                        5.2.3                h5e939de_4  
	yaml                      0.1.7                had09818_2  
	zeromq                    4.2.5                h439df22_0  
	zict                      0.1.3            py36h3a3bf81_0  
	zlib                      1.2.11               ha838bed_2
```

**Comment by willingc** [comment]
Thanks @tikenn
