### ISSUE TITLE
RuntimeError during shutdown after spawning a server

### ISSUE THREAD

**Issue by ssanderson** [jupyterhub/jupyterhub#1857]
Hi All!  I'm working on spinning up a small Jupyterhub instance for my PyCon tutorial, and I'm seeing a worrisome stack trace on shutdown:

**How to reproduce the issue**

- Run jupyterhub in its default configuration from a terminal.
- Log in and spawn a server.
- Stop the hub by hitting `CTRL-C` on the command line.

**What you expected to happen**

I expected the hub to shut down without reporting any errors.

**What actually happens**

During shutdown, the hub prints the following stack trace before exiting:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ssanderson/.virtualenvs/fonc/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 307, in _confirm_exit
    ioloop.IOLoop.instance().stop()
  File "/home/ssanderson/.virtualenvs/fonc/lib/python3.5/site-packages/tornado/ioloop.py", line 221, in instance
    return IOLoop.current()
  File "/home/ssanderson/.virtualenvs/fonc/lib/python3.5/site-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2'.
``` 

There don't seem to be any visible negative consequences of this besides hanging for a few seconds before shutting down, but the error looks potentially indicative of a concerning issue.

**Share what version of JupyterHub you are using**

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
(fonc) [~/projects/foundations-of-numerical-computing]$ jupyter troubleshoot
$PATH:
        /home/ssanderson/.virtualenvs/fonc/bin
        /home/ssanderson/.virtualenvs/fonc/bin
        /home/ssanderson/.cargo/bin
        /usr/local/heroku/bin

        /home/ssanderson/bin
        /home/ssanderson/.local/bin
        /usr/local/bin
        /usr/local/sbin
        /home/ssanderson/.rvm/gems/ruby-2.4.4/bin
        /home/ssanderson/.rvm/gems/ruby-2.4.4@global/bin
        /home/ssanderson/.rvm/rubies/ruby-2.4.4/bin
        /home/ssanderson/.cargo/bin
        /usr/local/heroku/bin

        /home/ssanderson/bin
        /home/ssanderson/.local/bin
        /usr/local/bin
        /usr/local/sbin
        /home/ssanderson/bin
        /home/ssanderson/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin
        /home/ssanderson/.rvm/bin

sys.path:
        /home/ssanderson/.virtualenvs/fonc/bin
        /home/ssanderson/.virtualenvs/fonc/lib/python35.zip
        /home/ssanderson/.virtualenvs/fonc/lib/python3.5
        /home/ssanderson/.virtualenvs/fonc/lib/python3.5/plat-x86_64-linux-gnu
        /home/ssanderson/.virtualenvs/fonc/lib/python3.5/lib-dynload
        /usr/lib/python3.5
        /usr/lib/python3.5/plat-x86_64-linux-gnu
        /home/ssanderson/.virtualenvs/fonc/lib/python3.5/site-packages

sys.executable:
        /home/ssanderson/.virtualenvs/fonc/bin/python3

sys.version:
        3.5.2 (default, Nov 23 2017, 16:37:01)
        [GCC 5.4.0 20160609]

platform.platform():
        Linux-4.13.0-39-generic-x86_64-with-Ubuntu-16.04-xenial

which -a jupyter:
        /home/ssanderson/.virtualenvs/fonc/bin/jupyter
        /home/ssanderson/.virtualenvs/fonc/bin/jupyter

pip list:
        Package          Version
        ---------------- ---------
        alembic          0.9.9
        backcall         0.1.0
        bleach           2.1.3
        certifi          2018.4.16
        chardet          3.0.4
        decorator        4.3.0
        docker           3.3.0
        docker-pycreds   0.2.3
        dockerspawner    0.9.1
        entrypoints      0.2.3
        escapism         1.0.0
        html5lib         1.0.1
        idna             2.6
        ipykernel        4.8.2
        ipython          6.3.1
        ipython-genutils 0.2.0
        jedi             0.12.0
        Jinja2           2.10
        jsonschema       2.6.0
        jupyter-client   5.2.3
        jupyter-core     4.4.0
        jupyterhub       0.8.1
        Mako             1.0.7
        MarkupSafe       1.0
        mistune          0.8.3
        nbconvert        5.3.1
        nbformat         4.4.0
        notebook         5.4.1
        pamela           0.3.0
        pandocfilters    1.4.2
        parso            0.2.0
        pexpect          4.5.0
        pickleshare      0.7.4
        pip              10.0.1
        prompt-toolkit   1.0.15
        ptyprocess       0.5.2
        Pygments         2.2.0
        python-dateutil  2.7.2
        python-editor    1.0.3
        python-oauth2    1.1.0
        pyzmq            17.0.0
        requests         2.18.4
        Send2Trash       1.5.0
        setuptools       39.1.0
        simplegeneric    0.8.1
        six              1.11.0
        SQLAlchemy       1.2.7
        terminado        0.8.1
        testpath         0.3.1
        tornado          5.0.2
        traitlets        4.3.2
        urllib3          1.22
        wcwidth          0.1.7
        webencodings     0.5.1
        websocket-client 0.47.0
        wheel            0.31.0
```

**Comment by minrk** [comment]
Pinning tornado to `<5.0` should fix it. Tornado 5 changes how instance and asyncio integration work. It's fixed in master, but there hasn't been a release yet (working on a beta right now).

**Comment by ssanderson** [comment]
:+1:
