### ISSUE TITLE
Loading configfile broken

### ISSUE THREAD

**Issue by deric** [jupyterhub/jupyterhub#1860]
**How to reproduce the issue**

Install a jupyterhub in a container. If there's some problem with the config any error is silently ignored.

**What you expected to happen**

I'm expecting to load a config file passed under `-f /etc/jupyter/jupyterhub_config.py`

**What actually happens**

Nothing at all.

```
application:555] Looking for  jupyterhub_config in /etc/jupyter/
```

**Share what version of JupyterHub you are using**

```
jupyter-core==4.4.0
jupyterhub==0.8.1
```

```
jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.                                                                                      
$PATH:
        /usr/local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /usr/local/bin
        /usr/lib/python35.zip
        /usr/lib/python3.5
        /usr/lib/python3.5/plat-x86_64-linux-gnu
        /usr/lib/python3.5/lib-dynload
        /usr/local/lib/python3.5/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.5.3 (default, Jan 19 2017, 14:11:04) 
        [GCC 6.3.0 20170118]

platform.platform():
        Linux-4.9.0-6-amd64-x86_64-with-debian-9.4

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        alembic (0.9.9)
        backcall (0.1.0)
        bleach (2.1.3)
        certifi (2018.4.16)
        chardet (3.0.4)
        Cython (0.28.2)
        decorator (4.3.0)
        entrypoints (0.2.3)
        enum34 (1.1.6)
        h5py (2.7.1)
        html5lib (0.9999999)
        idna (2.6)
        ipykernel (4.8.2)
        ipython (6.3.1)
        ipython-genutils (0.2.0)
        jedi (0.12.0)
        Jinja2 (2.10)
        jsonschema (2.6.0)
        jupyter-client (5.2.3)
        jupyter-core (4.4.0)
        jupyterhub (0.8.1)
        jupyterhub-ldapauthenticator (1.1)
        Keras (2.1.6)
        ldap3 (2.5)
        Mako (1.0.7)
        Markdown (2.6.11)
        MarkupSafe (1.0)
        mistune (0.8.3)
        nbconvert (5.3.1)
        nbformat (4.4.0)
        notebook (5.4.1)
        numpy (1.14.3)
        pamela (0.3.0)
        pandocfilters (1.4.2)
        parso (0.2.0)
        pexpect (4.5.0)
        pickleshare (0.7.4)
        pip (9.0.1)
        prompt-toolkit (1.0.15)
        protobuf (3.5.2.post1)
        ptyprocess (0.5.2)
        pyasn1 (0.4.2)
        pycurl (7.43.0.1)
        Pygments (2.2.0)
        python-dateutil (2.7.2)
        python-editor (1.0.3)
        python-oauth2 (1.1.0)
        PyYAML (3.12)
        pyzmq (17.0.0)
        requests (2.18.4)
        scikit-learn (0.19.1)
        scipy (1.0.1)
        Send2Trash (1.5.0)
        setuptools (33.1.1)
        simplegeneric (0.8.1)
        six (1.11.0)
        SQLAlchemy (1.2.7)
        tensorflow (1.4.1)
        tensorflow-tensorboard (0.4.0)
        terminado (0.8.1)
        testpath (0.3.1)
        tornado (5.0.2)
        traitlets (4.3.2)
        urllib3 (1.22)
        wcwidth (0.1.7)
        Werkzeug (0.14.1)
        wheel (0.31.0)
```

**Comment by minrk** [comment]
Hm, it should exit, and does when I test:

```
$ cat jupyterhub_config.py
1/0
$ jupyterhub -f jupyterhub_config.py --debug
[D 2018-05-04 17:30:57.499 JupyterHub application:555] Looking for jupyterhub_config in /private/tmp
[E 2018-05-04 17:30:57.500 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/jupyterhub/app.py", line 1358, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/benjaminrk/env/jhub-stable/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/private/tmp/jupyterhub_config.py", line 1, in <module>
        1/0
    ZeroDivisionError: division by zero

[D 2018-05-04 17:30:57.501 JupyterHub application:647] Exiting application: jupyterhub
```

Can you describe what sort of error is in your config that it's ignoring?
