### ISSUE TITLE
jupyterhub login failed with 500 error code (Spawner failed to start [status=1])

### ISSUE THREAD

**Issue by Y-L-18** [jupyterhub/jupyterhub#1874]
The "not able to login" issue started to happen after I deleted the previous AWS instance and the volume associated with it and recreated a new AWS instance. (I do remember I changed ownership for some files from root to ubuntu at that time, but not sure which ones exactly I touched at that time.. I might have pip installed some packages or so at that time as well)  When I tried to login to the jupyterhub as I previously did, I encountered several issues.  I started to tune things, restart computer, etc and ended up with still the 500 error code and log messages that looked confusing to me, as shown below.  I have been searching on the internet and tried bunches of resolutions but in vain.

When I recreated the AWS instance, I tried to set the custom port to 6102 (and chose to use the original key when initiated the new AWS instance), but later edited it back to 6101.  The "port in use" error message showed up once when I tried to login with the newly created AWS instance.  I killed it with sudo kill $(sudo lsof -t -i :6102)  then we I rechecked all opening ports with netstat -pntl on ubuntu, it showed me that both 6101 and 6102 were no longer there..

below is the whole terminal log that keeps coming back to me if I try to login from ubuntu to jupyterhub:

```
ubuntu@ip-xxx-xx-xx-xxx:~$ sudo miniconda3/bin/jupyterhub
[I 2018-05-07 17:39:35.232 JupyterHub app:622] Loading cookie_secret from /home/ubuntu/jupyterhub_cookie_secret
[W 2018-05-07 17:39:35.271 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2018-05-07 17:39:35.275 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2018-05-07 17:39:35.275 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-05-07 17:39:35.275 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2018-05-07 17:39:35.307 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-05-07 17:39:35.310 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2018-05-07 17:39:35.310 JupyterHub app:968] Starting proxy @ http://*:6101/
17:39:35.431 - info: [ConfigProxy] Proxying http://*:6101 to http://127.0.0.1:8081
17:39:35.434 - info: [ConfigProxy] Proxy API at http://127.0.0.1:6102/api/routes
[I 2018-05-07 17:39:35.514 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:6101/
Last login: Mon May  7 16:57:59 UTC 2018
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-121-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

147 packages can be updated.
0 updates are security updates.


[I 2018-05-07 17:39:42.738 JupyterHub spawner:467] Spawning /home/ubuntu/miniconda3/bin/jupyterhub-singleuser --user=training01 --port=43595 --cookie-name=jupyter-hub-token-training01 --base-url=/user/training01 --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/jupyterhub-singleuser", line 21, in <module>
    import notebook
  File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/jupyterhub-singleuser", line 23, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[W 2018-05-07 17:39:52.757 JupyterHub web:1545] 500 POST /hub/login?next= (::ffff:73.93.153.78): Spawner failed to start [status=1]
[E 2018-05-07 17:39:52.783 JupyterHub log:99] {
      "Accept-Language": "en-US,en;q=0.9",
      "Connection": "close",
      "Host": "13.56.232.136:6101",
      "X-Forwarded-Host": "13.56.232.136:6101",
      "X-Forwarded-For": "::ffff:73.93.153.78",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "X-Forwarded-Proto": "http",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Encoding": "gzip, deflate",
      "Origin": "http://13.56.232.136:6101",
      "X-Forwarded-Port": "6101",
      "Referer": "http://13.56.232.136:6101/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Cache-Control": "max-age=0",
      "Content-Length": "33"
    }
[E 2018-05-07 17:39:52.783 JupyterHub log:100] 500 POST /hub/login?next= (@::ffff:73.93.153.78) 10140.52ms
[W 2018-05-07 17:40:12.824 JupyterHub user:264] training01's server never showed up at http://127.0.0.1:43595/user/training01 after 30 seconds. Giving up
[E 2018-05-07 17:40:12.833 JupyterHub gen:878] Exception in Future <tornado.concurrent.Future object at 0x7fb65379cb00> after timeout
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/tornado/gen.py", line 874, in error_callback
        future.result()
      File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 280, in spawn
        raise e
      File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/jupyterhub/user.py", line 256, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/home/ubuntu/miniconda3/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:43595/user/training01 didn't respond in 30 seconds
```

**Comment by minrk** [comment]
That looks like a version mismatch of the jupyter_core package. Try `conda upgrade jupyter_core`

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Thanks! 🌻
