### ISSUE TITLE
Culler fails with "TypeError: can't compare offset-naive and offset-aware datetimes" in 0.9.0b3

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/jupyterhub#1919]
**How to reproduce the issue**
Run jupyterhub 0.9.0b3 with culler

**What you expected to happen**
cull_idle_servers.py to run without errors
**What actually happens**
Get an error:

> [I 2018-05-25 15:28:51.187 JupyterHub log:158] 200 GET /paws/hub/api/users (cull-idle@127.0.0.1) 77.08ms
> Traceback (most recent call last):
>   File "/usr/local/bin/cull_idle_servers.py", line 114, in <module>
>     loop.run_sync(cull)
>   File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 581, in run_sync
>     return future_cell[0].result()
>   File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1113, in run
>     yielded = self.gen.send(value)
>   File "/usr/local/bin/cull_idle_servers.py", line 87, in cull_idle
>     if last_activity < cull_limit:
> TypeError: can't compare offset-naive and offset-aware datetimes
> 

**Share what version of JupyterHub you are using**
0.9.0b3

**Comment by chicocvenancio** [comment]
I'm now realizing my install still uses the old cull_idle_servers.py as that is not updated by pip. Let me test with the new one.

**Comment by chicocvenancio** [comment]
With the updated version it works fine.
