### ISSUE TITLE
error in docker connection

### ISSUE THREAD

**Issue by chaomaer** [jupyterhub/jupyterhub#1921]
magically, I deploy the docker with jupyterhub successfully, the Next Day, i restart the jupyterhub, the block occurs.
the browser error:(magic is myhostname)
```
Failed to connect to Hub API at 'http://magic:8081/hub/api'.  Is the Hub accessible at this URL (from host: 06079ca81e1b)?
```
the terminal errors:
```
302 GET /hub/api/oauth2/authorize?client_id=user-chaomaer&redirect_uri=%2Fuser%2Fchaomaer%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImU4OTQ4MjdmMDAxMTRkZjdhYmFmM2M3NjIzOGM0NjU3IiwgIm5leHRfdXJsIjogIi91c2VyL2NoYW9tYWVyL3RyZWU_In0 → /user/chaomaer/oauth_callback?code=8fdcc380-fe26-4838-a6f8-aa91fa4194cc&state=eyJ1dWlkIjogImU4OTQ4MjdmMDAxMTRkZjdhYmFmM2M3NjIzOGM0NjU3IiwgIm5leHRfdXJsIjogIi91c2VyL2NoYW9tYWVyL3RyZWU_In0 (chaomaer@::ffff:127.0.0.1) 66.38ms
```
it means that i can't pass the auth.
and my command is:
```
sudo rm jupyter*
sudo jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
```
the fatal docker log error is:
```
 Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
        ret = callback()
      File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 344, in wrapped
        raise_exc_info(exc)
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 315, in wrapped
        ret = fn(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 293, in <lambda>
        future, lambda future: callback(future.result()))
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/tornado/tcpclient.py", line 226, in connect
        addrinfo = yield self.resolver.resolve(host, port, af)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 364, in resolve
        None, _resolve_addr, host, port, family)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 349, in _resolve_addr
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -3] Temporary failure in name resolution
```
jupyterhub_config.py
```
c = get_config()
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = 'jupyter/scipy-notebook'
c.JupyterHub.hub_ip = '0.0.0.0'  # listen on all interfaces
c.JupyterHub.hub_connect_ip = 'magic'  # ip as seen on the docker network. Can also be a hostname.
```
can someone helps me, thanks at advance.

**Comment by GH1995** [comment]
> I add a new user, and then use the new user to login, it works.

it donot work.
