### ISSUE TITLE
Trouble with Permissions similar to issue #510

### ISSUE THREAD

**Issue by SeaDude** [jupyterhub/jupyterhub#1924]
Seems i'm unable to start Jupyter Lab due to permission issues on the ssl cert directory. I don't know what permission levels to set on the directory and don't want to expose the cert to non-privaleged users. Please advise. 
Thank you. 
(IP address is redacted below)

**How to reproduce the issue**
`jupyterhub --ip=X.X.X.X --port=443 --ssl-cert /etc/nginx/ssl/mycert.cert`

**What you expected to happen**
`Proxy started Starting @ https://X.X.X.X:443/

**What actually happens**
```
me@jupyterVM:/opt/anaconda/anaconda4$ jupyterhub --ip=X.X.X.X --port=443 --ssl-cert /etc/nginx/ssl/mycert.cert 
[I 2018-05-28 03:41:28.798 JupyterHub app:834] Loading cookie_secret from /opt/anaconda/anaconda4/jupyterhub_cookie_secret
[W 2018-05-28 03:41:28.821 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-05-28 03:41:28.822 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-05-28 03:41:28.822 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-05-28 03:41:28.850 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-05-28 03:41:28.852 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2018-05-28 03:41:28.853 JupyterHub proxy:458] Starting proxy @ https://X.X.X.X:443/
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES: permission denied, open '/etc/nginx/ssl/mycert.cert'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/opt/anaconda/anaconda4/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:139:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
[C 2018-05-28 03:41:29.807 JupyterHub app:1535] Failed to start proxy
    Traceback (most recent call last):
      File "/opt/anaconda/anaconda4/lib/python3.6/site-packages/jupyterhub/app.py", line 1533, in start
        yield self.proxy.start()
      File "/opt/anaconda/anaconda4/lib/python3.6/site-packages/jupyterhub/proxy.py", line 482, in start
        _check_process()
      File "/opt/anaconda/anaconda4/lib/python3.6/site-packages/jupyterhub/proxy.py", line 478, in _check_process
        raise e
    RuntimeError: Proxy failed to start with exit code 1
```

**Share what version of JupyterHub you are using**
`0.8.1`

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
me@jupyterVM:/opt/anaconda/anaconda4$ jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$PATH:
	/opt/anaconda/anaconda4/bin
	/opt/anaconda/anaconda4/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games

sys.path:
	/opt/anaconda/anaconda4/bin
	/opt/anaconda/anaconda4/lib/python36.zip
	/opt/anaconda/anaconda4/lib/python3.6
	/opt/anaconda/anaconda4/lib/python3.6/lib-dynload
	/opt/anaconda/anaconda4/lib/python3.6/site-packages
	/opt/anaconda/anaconda4/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg

sys.executable:
	/opt/anaconda/anaconda4/bin/python

sys.version:
	3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
	[GCC 7.2.0]

platform.platform():
	Linux-4.13.0-1018-azure-x86_64-with-debian-stretch-sid

which -a jupyter:
	/opt/anaconda/anaconda4/bin/jupyter
	/opt/anaconda/anaconda4/bin/jupyter

pip list:
	alabaster (0.7.10)
	alembic (0.9.9)
	anaconda-client (1.6.9)
	anaconda-navigator (1.7.0)
	anaconda-project (0.8.2)
	asn1crypto (0.24.0)
	astroid (1.6.1)
	astropy (2.0.3)
	attrs (17.4.0)
	Babel (2.5.3)
	backports.shutil-get-terminal-size (1.0.0)
	beautifulsoup4 (4.6.0)
	bitarray (0.8.1)
	bkcharts (0.2)
	blaze (0.11.3)
	bleach (2.1.2)
	bokeh (0.12.13)
	boto (2.48.0)
	Bottleneck (1.2.1)
	certifi (2018.1.18)
	cffi (1.11.4)
	chardet (3.0.4)
	click (6.7)
	cloudpickle (0.5.2)
	clyent (1.2.2)
	colorama (0.3.9)
	conda (4.5.4)
	conda-build (3.4.1)
	conda-verify (2.0.0)
	contextlib2 (0.5.5)
	cryptography (2.1.4)
	cycler (0.10.0)
	Cython (0.27.3)
	cytoolz (0.9.0)
	dask (0.16.1)
	datashape (0.5.4)
	decorator (4.2.1)
	distributed (1.20.2)
	docutils (0.14)
	entrypoints (0.2.3)
	et-xmlfile (1.0.1)
	fastcache (1.0.2)
	filelock (2.0.13)
	Flask (0.12.2)
	Flask-Cors (3.0.3)
	gevent (1.2.2)
	glob2 (0.6)
	gmpy2 (2.0.8)
	greenlet (0.4.12)
	h5py (2.7.1)
	heapdict (1.0.0)
	html5lib (1.0.1)
	idna (2.6)
	imageio (2.2.0)
	imagesize (0.7.1)
	ipykernel (4.8.0)
	ipython (6.2.1)
	ipython-genutils (0.2.0)
	ipywidgets (7.1.1)
	isort (4.2.15)
	itsdangerous (0.24)
	jdcal (1.3)
	jedi (0.11.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.2.2)
	jupyter-console (5.2.0)
	jupyter-core (4.4.0)
	jupyterhub (0.8.1)
	jupyterlab (0.31.5)
	jupyterlab-launcher (0.10.2)
	lazy-object-proxy (1.3.1)
	llvmlite (0.21.0)
	locket (0.2.0)
	lxml (4.1.1)
	Mako (1.0.7)
	MarkupSafe (1.0)
	matplotlib (2.1.2)
	mccabe (0.6.1)
	mistune (0.8.3)
	mpmath (1.0.0)
	msgpack-python (0.5.1)
	multipledispatch (0.4.9)
	navigator-updater (0.1.0)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	networkx (2.1)
	nltk (3.2.5)
	nose (1.3.7)
	notebook (5.4.0)
	numba (0.36.2)
	numexpr (2.6.4)
	numpy (1.14.0)
	numpydoc (0.7.0)
	odo (0.5.1)
	olefile (0.45.1)
	openpyxl (2.4.10)
	packaging (16.8)
	pamela (0.3.0)
	pandas (0.22.0)
	pandocfilters (1.4.2)
	parso (0.1.1)
	partd (0.3.8)
	path.py (10.5)
	pathlib2 (2.3.0)
	patsy (0.5.0)
	pep8 (1.7.1)
	pexpect (4.3.1)
	pickleshare (0.7.4)
	Pillow (5.0.0)
	pip (9.0.1)
	pkginfo (1.4.1)
	pluggy (0.6.0)
	ply (3.10)
	prompt-toolkit (1.0.15)
	psutil (5.4.3)
	ptyprocess (0.5.2)
	py (1.5.2)
	pycodestyle (2.3.1)
	pycosat (0.6.3)
	pycparser (2.18)
	pycrypto (2.6.1)
	pycurl (7.43.0.1)
	pyflakes (1.6.0)
	Pygments (2.2.0)
	pylint (1.8.2)
	pyodbc (4.0.22)
	pyOpenSSL (17.5.0)
	pyparsing (2.2.0)
	PySocks (1.6.7)
	pytest (3.3.2)
	python-dateutil (2.6.1)
	python-editor (1.0.3)
	python-oauth2 (1.0.1)
	pytz (2017.3)
	PyWavelets (0.5.2)
	PyYAML (3.12)
	pyzmq (16.0.3)
	QtAwesome (0.4.4)
	qtconsole (4.3.1)
	QtPy (1.3.1)
	requests (2.18.4)
	rope (0.10.7)
	ruamel-yaml (0.15.35)
	scikit-image (0.13.1)
	scikit-learn (0.19.1)
	scipy (1.0.0)
	seaborn (0.8.1)
	Send2Trash (1.4.2)
	setuptools (38.4.0)
	simplegeneric (0.8.1)
	singledispatch (3.4.0.3)
	six (1.11.0)
	snowballstemmer (1.2.1)
	sortedcollections (0.5.3)
	sortedcontainers (1.5.9)
	Sphinx (1.6.6)
	sphinxcontrib-websupport (1.0.1)
	spyder (3.2.6)
	SQLAlchemy (1.2.1)
	statsmodels (0.8.0)
	sympy (1.1.1)
	tables (3.4.2)
	tblib (1.3.2)
	terminado (0.8.1)
	testpath (0.3.1)
	toolz (0.9.0)
	tornado (4.5.3)
	traitlets (4.3.2)
	typing (3.6.2)
	unicodecsv (0.14.1)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	Werkzeug (0.14.1)
	wheel (0.30.0)
	widgetsnbextension (3.1.0)
	wrapt (1.10.11)
	xlrd (1.1.0)
	XlsxWriter (1.0.2)
	xlwt (1.3.0)
	zict (0.1.3)

conda list:
	# packages in environment at /opt/anaconda/anaconda4:
	#
	# Name                    Version                   Build  Channel
	_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0  
	alabaster                 0.7.10           py36h306e16b_0  
	alembic                   0.9.9                      py_0    conda-forge
	anaconda                  5.1.0                    py36_2  
	anaconda-client           1.6.9                    py36_0  
	anaconda-navigator        1.7.0                    py36_0  
	anaconda-project          0.8.2            py36h44fb852_0  
	asn1crypto                0.24.0                   py36_0  
	astroid                   1.6.1                    py36_0  
	astropy                   2.0.3            py36h14c3975_0  
	attrs                     17.4.0                   py36_0  
	babel                     2.5.3                    py36_0  
	backports                 1.0              py36hfa02d7e_1  
	backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
	beautifulsoup4            4.6.0            py36h49b8c8c_1  
	bitarray                  0.8.1            py36h14c3975_1  
	bkcharts                  0.2              py36h735825a_0  
	blaze                     0.11.3           py36h4e06776_0  
	bleach                    2.1.2                    py36_0  
	bokeh                     0.12.13          py36h2f9c1c0_0  
	boto                      2.48.0           py36h6e4cd66_1  
	bottleneck                1.2.1            py36haac1ea0_0  
	bzip2                     1.0.6                h9a117a8_4  
	ca-certificates           2017.08.26           h1d4fec5_0  
	cairo                     1.14.12              h77bcde2_0  
	certifi                   2018.1.18                py36_0  
	cffi                      1.11.4           py36h9745a5d_0  
	chardet                   3.0.4            py36h0f667ec_1  
	click                     6.7              py36h5253387_0  
	cloudpickle               0.5.2                    py36_1  
	clyent                    1.2.2            py36h7e57e65_1  
	colorama                  0.3.9            py36h489cec4_0  
	conda                     4.5.4                    py36_0  
	conda-build               3.4.1                    py36_0  
	conda-env                 2.6.0                h36134e3_1  
	conda-verify              2.0.0            py36h98955d8_0  
	configurable-http-proxy   3.1.0                   node8_1    conda-forge
	contextlib2               0.5.5            py36h6c84a62_0  
	cryptography              2.1.4            py36hd09be54_0  
	curl                      7.58.0               h84994c4_0  
	cycler                    0.10.0           py36h93f1223_0  
	cython                    0.27.3           py36h1860423_0  
	cytoolz                   0.9.0            py36h14c3975_0  
	dask                      0.16.1                   py36_0  
	dask-core                 0.16.1                   py36_0  
	datashape                 0.5.4            py36h3ad6b5c_0  
	dbus                      1.12.2               hc3f9b76_1  
	decorator                 4.2.1                    py36_0  
	distributed               1.20.2                   py36_0  
	docutils                  0.14             py36hb0f60f5_0  
	entrypoints               0.2.3            py36h1aec115_2  
	et_xmlfile                1.0.1            py36hd6bccc3_0  
	expat                     2.2.5                he0dffb1_0  
	fastcache                 1.0.2            py36h14c3975_2  
	filelock                  2.0.13           py36h646ffb5_0  
	flask                     0.12.2           py36hb24657c_0  
	flask-cors                3.0.3            py36h2d857d3_0  
	fontconfig                2.12.4               h88586e7_1  
	freetype                  2.8                  hab7d2ae_1  
	get_terminal_size         1.0.0                haa9412d_0  
	gevent                    1.2.2            py36h2fe25dc_0  
	glib                      2.53.6               h5d9569c_2  
	glob2                     0.6              py36he249c77_0  
	gmp                       6.1.2                h6c8ec71_1  
	gmpy2                     2.0.8            py36hc8893dd_2  
	graphite2                 1.3.10               hf63cedd_1  
	greenlet                  0.4.12           py36h2d503a6_0  
	gst-plugins-base          1.12.4               h33fb286_0  
	gstreamer                 1.12.4               hb53b477_0  
	h5py                      2.7.1            py36h3585f63_0  
	harfbuzz                  1.7.4                hc5b324e_0  
	hdf5                      1.10.1               h9caa474_1  
	heapdict                  1.0.0                    py36_2  
	html5lib                  1.0.1            py36h2f9c1c0_0  
	icu                       58.2                 h9c2bf20_1  
	idna                      2.6              py36h82fb2a8_1  
	imageio                   2.2.0            py36he555465_0  
	imagesize                 0.7.1            py36h52d8127_0  
	intel-openmp              2018.0.0             hc7b2577_8  
	ipykernel                 4.8.0                    py36_0  
	ipython                   6.2.1            py36h88c514a_1  
	ipython_genutils          0.2.0            py36hb52b0d5_0  
	ipywidgets                7.1.1                    py36_0  
	isort                     4.2.15           py36had401c0_0  
	itsdangerous              0.24             py36h93cc618_1  
	jbig                      2.1                  hdba287a_0  
	jdcal                     1.3              py36h4c697fb_0  
	jedi                      0.11.1                   py36_0  
	jinja2                    2.10             py36ha16c418_0  
	jpeg                      9b                   h024ee3a_2  
	jsonschema                2.6.0            py36h006f8b5_0  
	jupyter                   1.0.0                    py36_4  
	jupyter_client            5.2.2                    py36_0  
	jupyter_console           5.2.0            py36he59e554_1  
	jupyter_core              4.4.0            py36h7c827e3_0  
	jupyterhub                0.8.1                    py36_0    conda-forge
	jupyterlab                0.31.5                   py36_0  
	jupyterlab_launcher       0.10.2                   py36_0  
	lazy-object-proxy         1.3.1            py36h10fcdad_0  
	libcurl                   7.58.0               h1ad7b7a_0  
	libedit                   3.1                  heed3624_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc                    7.2.0                h69d50b8_2  
	libgcc-ng                 7.2.0                h7cc24e2_2  
	libgfortran-ng            7.2.0                h9f7466a_2  
	libpng                    1.6.34               hb9fc6fc_0  
	libsodium                 1.0.15               hf101ebd_0  
	libssh2                   1.8.0                h9cfc8f7_4  
	libstdcxx-ng              7.2.0                h7a57d05_2  
	libtiff                   4.0.9                h28f6b97_0  
	libtool                   2.4.6                h544aabb_3  
	libxcb                    1.12                 hcd93eb1_4  
	libxml2                   2.9.7                h26e45fe_0  
	libxslt                   1.1.32               h1312cb7_0  
	llvmlite                  0.21.0           py36ha241eea_0  
	locket                    0.2.0            py36h787c0ad_1  
	lxml                      4.1.1            py36hf71bdeb_1  
	lzo                       2.10                 h49e0be7_2  
	mako                      1.0.7                    py36_0    conda-forge
	markupsafe                1.0              py36hd9260cd_1  
	matplotlib                2.1.2            py36h0e671d2_0  
	mccabe                    0.6.1            py36h5ad9710_1  
	mistune                   0.8.3                    py36_0  
	mkl                       2018.0.1             h19d6760_4  
	mkl-service               1.1.2            py36h17a0993_4  
	mpc                       1.0.3                hec55b23_5  
	mpfr                      3.1.5                h11a74b3_2  
	mpmath                    1.0.0            py36hfeacd6b_2  
	msgpack-python            0.5.1            py36h6bb024c_0  
	multipledispatch          0.4.9            py36h41da3fb_0  
	navigator-updater         0.1.0            py36h14770f7_0  
	nbconvert                 5.3.1            py36hb41ffb7_0  
	nbformat                  4.4.0            py36h31c9010_0  
	ncurses                   6.0                  h9df7e31_2  
	networkx                  2.1                      py36_0  
	nltk                      3.2.5            py36h7532b22_0  
	nodejs                    8.10.0                        0    conda-forge
	nose                      1.3.7            py36hcdf7029_2  
	notebook                  5.4.0                    py36_0  
	numba                     0.36.2          np114py36hc6662d5_0  
	numexpr                   2.6.4            py36hc4a3f9a_0  
	numpy                     1.14.0           py36h3dfced4_1  
	numpydoc                  0.7.0            py36h18f165f_0  
	odo                       0.5.1            py36h90ed295_0  
	olefile                   0.45.1                   py36_0  
	openpyxl                  2.4.10                   py36_0  
	openssl                   1.0.2n               hb7f436b_0  
	packaging                 16.8             py36ha668100_1  
	pamela                    0.3.0                    py36_0    conda-forge
	pandas                    0.22.0           py36hf484d3e_0  
	pandoc                    1.19.2.1             hea2e7c5_1  
	pandocfilters             1.4.2            py36ha6701b7_1  
	pango                     1.41.0               hd475d92_0  
	parso                     0.1.1            py36h35f843b_0  
	partd                     0.3.8            py36h36fd896_0  
	patchelf                  0.9                  hf79760b_2  
	path.py                   10.5             py36h55ceabb_0  
	pathlib2                  2.3.0            py36h49efa8e_0  
	patsy                     0.5.0                    py36_0  
	pcre                      8.41                 hc27e229_1  
	pep8                      1.7.1                    py36_0  
	pexpect                   4.3.1                    py36_0  
	pickleshare               0.7.4            py36h63277f8_0  
	pillow                    5.0.0            py36h3deb7b8_0  
	pip                       9.0.1            py36h6c6f9ce_4  
	pixman                    0.34.0               hceecf20_3  
	pkginfo                   1.4.1            py36h215d178_1  
	pluggy                    0.6.0            py36hb689045_0  
	ply                       3.10             py36hed35086_0  
	prompt_toolkit            1.0.15           py36h17d85b1_0  
	psutil                    5.4.3            py36h14c3975_0  
	ptyprocess                0.5.2            py36h69acd42_0  
	py                        1.5.2            py36h29bf505_0  
	pycodestyle               2.3.1            py36hf609f19_0  
	pycosat                   0.6.3            py36h0a5515d_0  
	pycparser                 2.18             py36hf9f622e_1  
	pycrypto                  2.6.1            py36h14c3975_7  
	pycurl                    7.43.0.1         py36hb7f436b_0  
	pyflakes                  1.6.0            py36h7bd6a15_0  
	pygments                  2.2.0            py36h0d3125c_0  
	pylint                    1.8.2                    py36_0  
	pyodbc                    4.0.22           py36hf484d3e_0  
	pyopenssl                 17.5.0           py36h20ba746_0  
	pyparsing                 2.2.0            py36hee85983_1  
	pyqt                      5.6.0            py36h0386399_5  
	pysocks                   1.6.7            py36hd97a5b1_1  
	pytables                  3.4.2            py36h3b5282a_2  
	pytest                    3.3.2                    py36_0  
	python                    3.6.4                hc3d631a_1  
	python-dateutil           2.6.1            py36h88d3b88_1  
	python-editor             1.0.3                    py36_0    conda-forge
	python-oauth2             1.0.1                    py36_0    conda-forge
	pytz                      2017.3           py36h63b9c63_0  
	pywavelets                0.5.2            py36he602eb0_0  
	pyyaml                    3.12             py36hafb9ca4_1  
	pyzmq                     16.0.3           py36he2533c7_0  
	qt                        5.6.2               h974d657_12  
	qtawesome                 0.4.4            py36h609ed8c_0  
	qtconsole                 4.3.1            py36h8f73b5b_0  
	qtpy                      1.3.1            py36h3691cc8_0  
	readline                  7.0                  ha6073c6_4  
	requests                  2.18.4           py36he2e5f8d_1  
	rope                      0.10.7           py36h147e2ec_0  
	ruamel_yaml               0.15.35          py36h14c3975_1  
	scikit-image              0.13.1           py36h14c3975_1  
	scikit-learn              0.19.1           py36h7aa7ec6_0  
	scipy                     1.0.0            py36hbf646e7_0  
	seaborn                   0.8.1            py36hfad7ec4_0  
	send2trash                1.4.2                    py36_0  
	setuptools                38.4.0                   py36_0  
	simplegeneric             0.8.1                    py36_2  
	singledispatch            3.4.0.3          py36h7a266c3_0  
	sip                       4.18.1           py36h51ed4ed_2  
	six                       1.11.0           py36h372c433_1  
	snowballstemmer           1.2.1            py36h6febd40_0  
	sortedcollections         0.5.3            py36h3c761f9_0  
	sortedcontainers          1.5.9                    py36_0  
	sphinx                    1.6.6                    py36_0  
	sphinxcontrib             1.0              py36h6d0f590_1  
	sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
	spyder                    3.2.6                    py36_0  
	sqlalchemy                1.2.1            py36h14c3975_0  
	sqlite                    3.22.0               h1bed415_0  
	statsmodels               0.8.0            py36h8533d0b_0  
	sympy                     1.1.1            py36hc6d1c1c_0  
	tblib                     1.3.2            py36h34cf8b6_0  
	terminado                 0.8.1                    py36_1  
	testpath                  0.3.1            py36h8cadb63_0  
	tk                        8.6.7                hc745277_3  
	toolz                     0.9.0                    py36_0  
	tornado                   4.5.3                    py36_0  
	traitlets                 4.3.2            py36h674d592_0  
	typing                    3.6.2            py36h7da032a_0  
	unicodecsv                0.14.1           py36ha668878_0  
	unixodbc                  2.3.4                hc36303a_1  
	urllib3                   1.22             py36hbe7ace6_0  
	wcwidth                   0.1.7            py36hdf4376a_0  
	webencodings              0.5.1            py36h800622e_1  
	werkzeug                  0.14.1                   py36_0  
	wheel                     0.30.0           py36hfd4bba0_1  
	widgetsnbextension        3.1.0                    py36_0  
	wrapt                     1.10.11          py36h28b7045_0  
	xlrd                      1.1.0            py36h1db9f0c_1  
	xlsxwriter                1.0.2            py36h3de1aca_0  
	xlwt                      1.3.0            py36h7b00a1f_0  
	xz                        5.2.3                h55aa19d_2  
	yaml                      0.1.7                had09818_2  
	zeromq                    4.2.2                hbedb6e5_2  
	zict                      0.1.3            py36h3a3bf81_0  
	zlib                      1.2.11               ha838bed_2
```

**Comment by minrk** [comment]
The certificate needs to be readable by the user running the configurable-http-proxy process (generally the user you are when you type `jupyterhub`). If you want to run the hub as non-root and also protect this cert, you can make it owned by you in a private location. If it needs to be read by multiple processes, you can make it owned by a group, of which you are a member.

However, from the location (`/etc/nginx`), perhaps you are already running nginx on this machine? If so, you can do SSL termination with nginx and put JupyterHub only on localhost. We have [an example nginx config for this](https://jupyterhub.readthedocs.io/en/stable/reference/config-examples.html#nginx).

**Comment by SeaDude** [comment]
Oh thank you so much for the prompt response. I'm going to run through the entire setup again this time documented in my github repo. I'll share when complete. 

Question: What is the benefit of doing ssl termination with nginx as opposed to within jupyterhub itself?

**Comment by SeaDude** [comment]
Head spinning... [here is everything I've done to](https://github.com/SeaDude/azure-jupyterhub/blob/testing/jupyterLabInstall.md): 

- get an Azure VM running Ubuntu 17.10 w/ self-signed ssl certs
- install Anaconda as root user to `/opt/anaconda/anaconda4`
- install jupyterhub via conda

Cannot get jupyterhub running. Shows `JupyterHub is now running at http://:8000/` What am I missing here?

**Comment by willingc** [comment]
Hi @SeaDude, I'm closing this issue and let's continue discussion about installation and configuration in #1936
