### ISSUE TITLE
Upgrade from working to non working jupyterhub, AttributeError: 'PAMAuthenticator' object has no attribute 'enable_auth_state'

### ISSUE THREAD

**Issue by nauhpc** [jupyterhub/jupyterhub#1986]
Hello guys,

We just upgraded our jupyterhub from 0.7.2 to current. When we try to start the jupyterhub we get the following in the logs. We cannot find an answer from el goog ...

[E 2018-06-14 16:25:45.804 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/asyncio/futures.py", line 293, in result
        raise self._exception
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 1377, in initialize
        yield self.init_users()
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/asyncio/futures.py", line 293, in result
        raise self._exception
      File "/packages/python/anaconda/jupyter/miniconda3/lib/python3.5/site-packages/jupyterhub/app.py", line 930, in init_users
        if self.authenticator.enable_auth_state:
    AttributeError: 'PAMAuthenticator' object has no attribute 'enable_auth_state'

Thanks guys!

**Comment by minrk** [comment]
That looks like something went wrong in the upgrade because it means PAMAuthenticator isn't from jupyterhub >= 0.8. Try removing jupyterhub and reinstalling it

**Comment by willingc** [comment]
I'm closing this as #1991 is a more recent issue related to the same deployment. Let's troubleshoot configuration issues on that issue. Thanks @nauhpc.
