### ISSUE TITLE
Jupyterhub doesn't start after new install, traitlets.traitlets.TraitError: The 'port' trait of a Server instance must be an int, but a value of '' <class 'str'> was specified.

### ISSUE THREAD

**Issue by nauhpc** [jupyterhub/jupyterhub#1991]
Hello all,

Trying to move on from a failed upgrade, we've tried installing jupyterhub fresh and cannot get it to work properly with our config file. Upon login we receive a 500 error, and in the logs we see:

```
[E 2018-06-15 14:11:00.639 JupyterHub base:948] Preventing implicit spawn for cbc because last spawn failed: The 'port' trait of a Server instance must be an int, but a value of '' <class 'str'> was specified.
[E 2018-06-15 14:11:00.639 JupyterHub web:1621] Uncaught exception GET /hub/user/cbc/ (134.114.70.8)
    HTTPServerRequest(protocol='https', host='jupyter.hpc.nau.edu', method='GET', uri='/hub/user/cbc/', version='HTTP/1.1', remote_ip='134.114.70.8')
    Traceback (most recent call last):
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 950, in get
        raise copy.copy(exc).with_traceback(exc.__traceback__)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 999, in get
        await self.spawn_single_user(user)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 670, in spawn_single_user
        await gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 625, in finish_user_spawn
        await spawn_future
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/tmp/slurmspawner/slurmspawner/slurmspawner.py", line 316, in start
        self.user.server.port = port
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/traitlets/traitlets.py", line 585, in __set__
        self.set(obj, value)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/traitlets/traitlets.py", line 559, in set
        new_value = self._validate(obj, value)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate
        value = self.validate(obj, value)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/traitlets/traitlets.py", line 1870, in validate
        self.error(obj, value)
      File "/packages/python/anaconda/jupyter/lib/python3.6/site-packages/traitlets/traitlets.py", line 625, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'port' trait of a Server instance must be an int, but a value of '' <class 'str'> was specified.
    
[D 2018-06-15 14:11:00.642 JupyterHub base:844] No template for 500
```
Please help, thanks!

**Comment by willingc** [comment]
Which version of JupyterHub are you running?

**Comment by nauhpc** [comment]
Hi,

We are running, I believe the most recent version: 

./lib/python3.6/site-packages/jupyterhub-0.9.0-py3.6.egg-info

Thanks!

**Comment by willingc** [comment]
> 
```
[E 2018-06-15 14:11:00.639 JupyterHub base:948] Preventing implicit spawn for cbc because last spawn failed: The 'port' trait of a Server instance must be an int, but a value of '' <class 'str'> was specified.
[E 2018-06-15 14:11:00.639 JupyterHub web:1621] Uncaught exception GET /hub/user/cbc/ (134.114.70.8)
    HTTPServerRequest(protocol='https', host='jupyter.hpc.nau.edu', method='GET', uri='/hub/user/cbc/', version='HTTP/1.1', remote_ip='134.114.70.8')
    Traceback (most recent call last):
...
File "/tmp/slurmspawner/slurmspawner/slurmspawner.py", line 316, in start
        self.user.server.port = port
...
traitlets.traitlets.TraitError: The 'port' trait of a Server instance must be an int, but a value of '' <class 'str'> was specified.
    
[D 2018-06-15 14:11:00.642 JupyterHub base:844] No template for 500
```

@minrk I'm having trouble isolating what the cause of this failure is. Is it in the batchspawner settings for slurmspawner or within JupyterHub?

**Comment by ravirajuv** [comment]
Hi there,

I am also facing the same issue. Below is my issue:

[I 2018-07-06 13:37:34.042 JupyterHub dockerspawner:399] Found existing container 'j                                                                                    upyter-dv_2Ekd_40pg_2Ecom' (id: 2e4c1bb)
[I 2018-07-06 13:37:34.042 JupyterHub dockerspawner:404] Starting container 'jupyter                                                                                    -dv_2Ekd_40pg_2Ecom' (id: 2e4c1bb)
[E 2018-07-06 13:37:34.356 JupyterHub user:474] Unhandled error starting dv.kd@pg.co                                                                                    m's server: The 'port' trait of a Server instance must be an int, but a value of '32                                                                                    771' <class 'str'> was specified.
[I 2018-07-06 13:37:34.360 JupyterHub dockerspawner:474] Stopping container jupyter-                                                                                    dv_2Ekd_40pg_2Ecom (id: 2e4c1bb)

Thanks in advance.

**Comment by nauhpc** [comment]
Hi, we ended up using the batchspawner as it is more up to date. We were able to get jupyterhub working, thank you!
