### ISSUE TITLE
in Anaconda use jupyter notebook

### ISSUE THREAD

**Issue by wangaiwudi** [jupyterhub/jupyterhub#2061]
Traceback (most recent call last):
  File "D:\ruanjian\Anaconda\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "D:\ruanjian\Anaconda\lib\site-packages\tornado\websocket.py", line 810, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

**Comment by willingc** [comment]
Hi @wangaiwudi, 

You will need to provide us with a bit more information about what your question is. Thanks.
