### ISSUE TITLE
Compatibility between conda env and python virtualenv and kernel start

### ISSUE THREAD

**Issue by guillaumeeb** [jupyterhub/jupyterhub#2069]
Hi everyone,

I'm currently deploying a jupyterhub on an HPC cluster with PBS. I ran into an issue that I wanted to share when playing with custom kernel. I'm not sure that it should be opened here...

So my setup is as follow:
 * Jupyterhub installed with conda, launched on a dedicated server, configured with batchSpawner for launching singleuser-notebook through PBSPro.
 * The notebook are launched using a conda environnment accessible to each HPC user (`module load conda; source activate myjupyterhubenv`)

In my home directory, I've got another conda install, with other environments. I created a kernel spec for a given environment. I get to chose it in my notebook, everything works fine.

A colleague of mine comes and try the hub, she has a custom kernel saved through `ipython kernel install --user --name her_awesome_env`. This kernel, is NOT a conda installed one, but a classic python installed manually. And then the error appears:

````
[I 2018-08-03 07:47:39.883 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/core/ultratb.py", line 115, in <module>
    from IPython.core import debugger
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/core/debugger.py", line 39, in <module>
    from IPython.utils import coloransi, py3compat
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/IPython/utils/py3compat.py", line 218, in <module>
    PYPY = platform.python_implementation() == "PyPy"
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/platform.py", line 1234, in python_implementation
    return _sys_version()[0]
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:17:00) \n[GCC 7.2.0]'
````

So here I decided to change my setup: I kept jupyterhub installed through conda, but for the singleuser-notebook, I used the python default install without conda. Issue above resolved, but then I cannot launch my own conda env kernel anymore:

````
/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:216:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
Traceback (most recent call last):
  File "/work/ADM/hpc/eynardbg/Outils/miniconda3/envs/test_jupyter/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/work/ADM/hpc/eynardbg/Outils/miniconda3/envs/test_jupyter/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (/work/logiciels/rh7/Python/3.6.5/lib/python3.6/site-packages/zmq/backend/cython/__init__.py)
````

The workaround here is to specify into the kernel spec to reset the PYTHONPATH:

````
{
 "argv": [
  "/work/ADM/hpc/eynardbg/Outils/miniconda3/envs/test_jupyter/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "test_jupyter",
 "language": "python",
 "env": {
    "PYTHONPATH":""
 }
}
````

So questions are:
* Are those known issues ?
* Is there a way to launch non conda python kernel from a conda singleuser-notebook ?

**Comment by minrk** [comment]
Yes, you can definitely launch any kernel in any env, no matter what the env is of the notebook serve. There should be no relationship between the two, but environment variables are inherited by default. You may have some env variables set in the notebook env that shouldn't be inherited by the subprocess. Resetting those env variables in your kernelspec is definitely one way to ensure they are not passed on. Setting PYTHONPATH is always going to cause a problem, and should ~never be used. It will especially cause a problem when you have one Python process that's going to start processes in a different env. The same is likely to occur with other env variables like LD_LIBRARY_PATH, etc.

**Comment by guillaumeeb** [comment]
Thanks @minrk

So is there a solution for the first described issue? Non conda kernel launched from a conda notebook? I did not dig further, but should playing around with PYTHONPATH or LD_LIBRARY_PATH be enough?

**Comment by willingc** [comment]
Hello @guillaumeeb,

For different languages or Python2 and Python3, you can install kernels as described [https://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-different-environments](https://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-different-environments).

You can also review the documentation about user environments https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#configuring-user-environments

I would avoid using PYTHONPATH as mentioned by @minrk.

**Comment by guillaumeeb** [comment]
So the reason for getting
```
ValueError: failed to parse CPython sys.version: '3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:17:00) \n[GCC 7.2.0]'
```
in the first case (notebook launched from a conda env, user kernel installed from a Python3 from source install and a virtualenv on top of it) was due to some environment variable too (as the PYTHONPATH in the second case)?

Looking closer, the `module load conda` used for launching the notebook specifies the following environment variables among others:
```
PKG_CONFIG_PATH
LD_LIBRARY_PATH
```
Those variables inherited from the python3 source install are probably the cause of the above error, right?

**Comment by guillaumeeb** [comment]
Did some tests this morning:

- first case error was indeed due to one of the two environment variables above.
- however, I had to manually add LD_LIBRARY_PATH of the python3 source install to the kernel.json file for the  kernel to work.

Thanks for answering my interrogations.
