### ISSUE TITLE
Jupyter User Problems

### ISSUE THREAD

**Issue by elbrinke** [jupyterhub/jupyterhub#2079]
Hi, 

After a server reboot our Jupyter server stopped working for some reason. 

So i tried : **./jupyterhub start --no-ssl** and the server seems to start up. 

```
@jupyter:/opt/.virtualenvs/jupyter/bin# ./jupyterhub start --no-ssl
[I 2018-08-10 12:15:39.140 JupyterHub app:622] Loading cookie_secret from /opt/.virtualenvs/jupyter/bin/jupyterhub_cookie_secret
[W 2018-08-10 12:15:39.165 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2018-08-10 12:15:39.168 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2018-08-10 12:15:39.168 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-10 12:15:39.168 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2018-08-10 12:15:39.182 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-08-10 12:15:39.185 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2018-08-10 12:15:39.185 JupyterHub app:968] Starting proxy @ http://*:8000/
12:15:39.287 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
12:15:39.289 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2018-08-10 12:15:39.391 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/

```
**But now we are getting another error:**

```
[I 2018-08-10 12:18:27.290 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=eddy --port=40967 --cookie-name=jupyter-hub-token-eddy --base-url=/user/eddy --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
[E 2018-08-10 12:18:27.322 JupyterHub user:237] Unhandled error starting eddy's server: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
[E 2018-08-10 12:18:27.358 JupyterHub web:1548] Uncaught exception POST /hub/login?next= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='192.168.1.241:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'close', 'Content-Length': '51', 'Content-Type': 'application/x-www-form-urlencoded', 'Dnt': '1', 'Accept-Language': 'en-US,en;q=0.5', 'Referer': 'http://192.168.1.241:8000/hub/login', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Host': '192.168.1.241:8000', 'Accept-Encoding': 'gzip, deflate', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'})
    Traceback (most recent call last):
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/.virtualenvs/jupyter/lib/python3.4/site-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyterhub-singleuser'
```
When we try to login using Web Browser on port 8000, we get the following on the browser:
```

500 : Internal Server Error
Failed to start your server. Please contact admin.
```
Can someone please assist us with this?

Best Regards
Eddy

**Comment by jhermann** [comment]
Looks like the main thing you're missing is activating the virtualenv *before* the start. Also, using absolute paths to utils can help.

See https://github.com/1and1/debianized-jupyterhub/blob/master/scripts/jupyterhub-launcher for a script that ensures a robust runtime env (activation, setting the cwd, …).

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks for the question and response to the issue too. 👍
