### ISSUE TITLE
hub error 'User user1 is slow to start (timeout=10)' despite jupyter pod running

### ISSUE THREAD

**Issue by nethsix** [jupyterhub/jupyterhub#2083]
Platform: google cloud
Jupyterhub helm chart: v0.6.0-d359d98

I successfully setup and run zero-to-jupyterhub-k8s. However a day or so, I will no longer be able to login.

Initially I thought this could be resource issue, so I upgraded my k8s nodes to 'n1-highmem-2', which is:

High memory machine type with 2 vCPUs and 13 GB of system memory.

Upon checking further, from the logs I show below, it seems that the hub is complaining about the jupyter pod not spawning quickly enough but the logs on the jupyter pod shows that it is already running.

I thought I could resolve this by setting http_timeout, start_timeout of the hub (see config.yaml), but it has no effect whatsoever.

I deployed using helm as follows:

```
helm install jupyterhub/jupyterhub --version=v0.6.0-d359d98 --name=fastowl-tf-timeout-jupyter --namespace=fastowl-tf-timeout-space -f config/k8s-config-github-tf-timeout.yml --debug --timeout=99999
```

Please help! Thank you.

## Contents of config.yaml

```
hub:
  cookieSecret: "cccccccccc"
  extraConfig: |
    c.Spawner.http_timeout = 3000
    c.Spawner.start_timeout = 3000
token:
  proxy: "bbbbbbbbb"
proxy:
  secretToken: "aaaaaaaaa"
singleuser:
  image:
    name: jupyter/tensorflow-notebook
    tag: 8a1b90cbcba5
auth:
  type: github
  github:
    clientId: "xxxxxxxxxx"
    clientSecret: "yyyyyyyyyyyyy"
    callbackUrl: "http://tensorflow.fastowl.xyz/hub/oauth_callback"
```

## Hub logs

* kubectl --namespace xyz log hub-xxxxxxxxxx-dzxhh

```
[W 2018-07-08 02:25:41.372 JupyterHub base:483] User user1 is slow to start (timeout=10)   [258/1822]
[I 2018-07-08 02:25:41.372 JupyterHub base:751] user1 is pending spawn
[I 2018-07-08 02:25:41.379 JupyterHub log:122] 200 GET /hub/user/user1/ (user1@10.0.9.1) 10059.79ms
[I 2018-07-08 02:25:52.084 JupyterHub log:122] 302 GET /hub/home → /hub/login?next=%2Fhub%2Fhome (@103.
5.140.162) 0.75ms
[I 2018-07-08 02:25:52.092 JupyterHub log:122] 200 GET /hub/login?next=%2Fhub%2Fhome (@103.5.140.162) 1
.33ms
[I 2018-07-08 02:25:58.432 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:25:58.432 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:26:15.024 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:26:15.025 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:26:30.231 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:26:30.231 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:26:45.450 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:26:45.450 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:27:00.656 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:27:00.656 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:27:15.856 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:27:15.856 JupyterHub base:727] user1 is pending spawn
[I 2018-07-08 02:27:31.125 JupyterHub base:722] Pending spawn for user1 didn't finish in 10.0 seconds
[I 2018-07-08 02:27:31.125 JupyterHub base:727] user1 is pending spawn
```

## Jupyter pod logs

* kubectl --namespace xyz log jupyter-yyyyyyy

```
[W 2018-07-08 02:38:33.412 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-07-08 02:38:33.672 SingleUserNotebookApp extension:53] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-07-08 02:38:33.672 SingleUserNotebookApp extension:54] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-07-08 02:38:33.683 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] Serving notebooks from local directory: /home/jovyan
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] 0 active kernels
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] The Jupyter Notebook is running at:
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] http://0.0.0.0:8888/user/user1/
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1586] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by nethsix** [comment]
I was looking through the list of issues, and found #2043 , which may be related?

In my case, the hub is also thinking that the user's jupyter pod is not up although it actually list; i can see the pod by doing `kubectl get pod`.

If I restart the hub by doing `kubectl delete pod <hub>` then everything works again. However, some users will have this issue again after after they become idle.

**Comment by consideRatio** [comment]
@nethsix

```sh
# is the pod running?
kubectl get pod jupyter-<username> -n <your-namespace>

# if not, what does the logs ...
kubectl logs jupyter-<username> -n <your-namespace>
# ... and the description of the pod say?
kubectl describe pod jupyter-<username> -n <your-namespace>
```

**Comment by nethsix** [comment]
@consideRatio 

I've restarted the hub so everything is fine now. I'm sure the issue will happen tomorrow. In the meantime:

> # is the pod running?
> `kubectl get pod jupyter-<username> -n <your-namespace>`

Yes. I can see both the hub, and pod running.

> # if not, what does the logs ...
> `kubectl logs jupyter-<username> -n <your-namespace>`

The pod is running. The log (I saved this log when the user couldn't log in):

```
[W 2018-07-08 02:38:33.412 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-07-08 02:38:33.672 SingleUserNotebookApp extension:53] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-07-08 02:38:33.672 SingleUserNotebookApp extension:54] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-07-08 02:38:33.683 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] Serving notebooks from local directory: /home/jovyan
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] 0 active kernels
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] The Jupyter Notebook is running at:
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1585] http://0.0.0.0:8888/user/user1/
[I 2018-07-08 02:38:33.690 SingleUserNotebookApp notebookapp:1586] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

> # ... and the description of the pod say?
> `kubectl describe pod jupyter-<username> -n <your-namespace>`

Currently the jupyter-pod is working well so I will provide this information again when it fails.

**Comment by consideRatio** [comment]
@nethsix thanks!

Btw I noticed now that you are using `--version=v0.6.0-d359d98` of the Helm chart. There is a v0.6 release out while the one you are using probably was before v0.6, and we are about to release v0.7 in not too long.

**Comment by nethsix** [comment]
@consideRatio Do you think v0.6 will help? I have another cluster, and I can try to redeploy with v0.6 or should I wait for v0.7?

**Comment by consideRatio** [comment]
I'm not sure, the singleuser images will have JupyterHub 0.9.1 installed, while the helm chart pre v0.6 will have an older JupyterHub, can they communicate and setup properly? I'm not sure... The z2jh guide sais one should ensure a matching version between the jupyterhub installed on the hub pod and the jupytehub package installed on the singleuser server - but in reality this is often not an issue it seems. At least not in between Jupyterhub 0.8.1 and JupyterHub 0.9.1.

What is the jupyterhub version on the chart--version you are using?

I'm not confident at all about this, hmmm...

**Comment by nethsix** [comment]
In my config for jupyterhub, I'm using this docker image:

```
singleuser:
  image:
    name: jupyter/tensorflow-notebook
    tag: 8a1b90cbcba5
```

I cannot find a good way to map the tag to the appropriate commit in https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook to figure out which jupyterhub it is using. tensorflow-notebook is actually derived from base-notebook, and for base-notebooke the jupyterhub version is v0.9.*? See file:

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L91

**Comment by nethsix** [comment]
I can see these error messages on the hub:

```
[I 2018-09-01 01:55:33.095 JupyterHub oauth2:82] OAuth redirect: 'http://tensorflow.fastowl.xyz/hub/oau
th_callback'
[I 2018-09-01 01:55:33.097 JupyterHub log:122] 302 GET /hub/oauth_login?next= → https://github.com/logi
n/oauth/authorize?redirect_uri=http%3A%2F%2Ftensorflow.fastowl.xyz%2Fhub%2Foauth_callback&client_id=7f5
ac1a064a96008b169&state=eyJzdGF0ZV9pZCI6ICJmY2QzMWViYzJmMzA0M2I5YWIxZWQwYTYwY2RhMzA2ZiIsICJuZXh0X3VybCI
6ICIifQ%3D%3D&response_type=code (@10.128.0.6) 2.20ms
[I 2018-09-01 01:55:34.579 JupyterHub base:346] User logged in: nethsix
[I 2018-09-01 01:55:34.582 JupyterHub log:122] 302 GET /hub/oauth_callback?code=830e709c0907a74d2c17&st
ate=eyJzdGF0ZV9pZCI6ICJmY2QzMWViYzJmMzA0M2I5YWIxZWQwYTYwY2RhMzA2ZiIsICJuZXh0X3VybCI6ICIifQ%3D%3D → /hub
/ (@10.128.0.6) 388.40ms
[I 2018-09-01 01:55:34.730 JupyterHub log:122] 302 GET /hub/ → /hub/home (nethsix@10.128.0.6) 3.06ms
[I 2018-09-01 01:55:34.878 JupyterHub log:122] 200 GET /hub/home (nethsix@10.128.0.6) 5.34ms
[I 2018-09-01 01:55:36.545 JupyterHub log:122] 302 GET /hub/spawn → /user/nethsix/ (nethsix@10.0.9.1) 4
.29ms
[I 2018-09-01 01:55:36.700 JupyterHub log:122] 302 GET /user/nethsix/ → /hub/user/nethsix/ (@10.0.9.1) 
0.94ms
[I 2018-09-01 01:55:36.984 JupyterHub spawner:946] PVC claim-nethsix already exists, so did not create 
new pvc.
[W 2018-09-01 01:55:46.934 JupyterHub base:483] User nethsix is slow to start (timeout=10)
[I 2018-09-01 01:55:46.935 JupyterHub base:751] nethsix is pending spawn
[I 2018-09-01 01:55:46.940 JupyterHub log:122] 200 GET /hub/user/nethsix/ (nethsix@10.0.9.1) 10074.54ms
[I 2018-09-01 01:55:55.967 JupyterHub log:122] 200 GET /hub/api (@10.0.9.131) 0.80ms
[I 2018-09-01 01:56:02.228 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:56:02.229 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:56:17.459 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:56:17.459 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:56:32.670 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:56:32.671 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:56:44.222 JupyterHub log:122] 200 GET /hub/api/users (cull-idle@127.0.0.1) 6.32ms
[I 2018-09-01 01:56:47.886 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:56:47.886 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:57:03.096 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:57:03.096 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:57:18.318 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:57:18.319 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:57:33.532 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:57:33.533 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:57:48.851 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:57:48.852 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:58:04.115 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:58:04.116 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:58:19.366 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:58:19.366 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:58:34.613 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:58:34.613 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:58:49.830 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:58:49.831 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:59:05.141 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:59:05.142 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:59:22.397 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:59:22.397 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:59:39.391 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:59:39.391 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 01:59:56.581 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 01:59:56.581 JupyterHub base:727] nethsix is pending spawn
[I 2018-09-01 02:00:13.557 JupyterHub base:722] Pending spawn for nethsix didn't finish in 10.0 seconds
[I 2018-09-01 02:00:13.557 JupyterHub base:727] nethsix is pending spawn
[E 2018-09-01 02:00:29.983 JupyterHub user:427] Unhandled error starting nethsix's server: pod/jupyter-
nethsix did not start in 300 seconds!
[E 2018-09-01 02:00:30.022 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at
 0x7f096a3a4ac8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_us
er_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/kubespawner/spawner.py", line 985, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backo
ff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-nethsix did not start in 300 seconds!
    
[E 2018-09-01 02:00:30.024 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at
 0x7f096a3a4ac8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_us
er_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/kubespawner/spawner.py", line 985, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backo
ff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-nethsix did not start in 300 seconds!
    
[E 2018-09-01 02:00:30.025 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at
 0x7f096a3a4ac8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_us
er_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 378, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/kubespawner/spawner.py", line 985, in start
        timeout=self.start_timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backo
ff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-nethsix did not start in 300 seconds!
```

**Comment by willingc** [comment]
@nethsix Are you still having this issue with the 1.7 helm chart? If so, can you share your configuration? Thanks.

**Comment by victorcete** [comment]
@nethsix we hit the same problem on Kubernetes, the problem seems to be the `kubespawner` timeout, actually.

Taking a look at the code, it seems to be using another timeout flag:
https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L385

```
  extraConfig: |-
    c.KubeSpawner.start_timeout = 900
```

Adding that additional config worked for us, our Docker images are quite big and downloading it took a lot of time.

Hope it helps!

**Comment by maya-harel** [comment]
I also have this issue, but only when enabling Calico https://docs.aws.amazon.com/eks/latest/userguide/calico.html

**Comment by consideRatio** [comment]
@maya-harel in case this problem persist using the absolute latest chart release (as you can find in the badges of the github repos readme, and specify with the --version flag during a helm upgrade command), then open a new issue about it if you think there is a bug with this helm chart, or ask a question on the forum if it is a matter of usage support.

I made a changes making me think it will work for you in the latest development release of the chart, also assuming you need network policies enabled etc.
