### ISSUE TITLE
Erro when executing this command "python3.6 -m pip install ipykernel"

### ISSUE THREAD

**Issue by iamyashasvi** [jupyterhub/jupyterhub#2093]
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.6/distutils/command/install.py", line 351, in finalize_options
    self.create_home_path()
  File "/usr/lib/python3.6/distutils/command/install.py", line 581, in create_home_path
    os.makedirs(path, 0o700)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/xarvis/.local/lib/python3.6'

**Comment by minrk** [comment]
That looks like the permissions on your home directory are not correct, possibly because a `sudo pip install --user` has occurred in the past. You can fix the ownership in your ~/.local directory with:

    chown -R $(id -u) $HOME/.local

**Comment by Tridoshic** [comment]
I have the same issue. I attempted the permission correction but it didn't work. 

[Myid@anaca-scripthost-01 ~]$ chown -R $(id -u) $HOME/.local
chown: cannot access â€˜/import/home/E250977/.localâ€™: No such file or directory



Installing collected packages: pycparser, cffi, bcrypt, pynacl, cryptography, paramiko
Exception:
Traceback (most recent call last):
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/opt/sense_cli/lib64/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/sense_cli/lib/python3.6/site-packages/pycparser-2.20.dist-info'
