### ISSUE TITLE
How do I stop or kill the running instance and start a new instance?

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2104]
I had Jupyter Hub installed and running yesterday. 

I want to start a new instance - in the case of system maintenance this would be needed - but, after I typed in the same command like yesterday:

sudo jupyterhub
I got the following messages and off course the instance is not up and running:

> [I 2018-08-24 13:48:33.066 JupyterHub app:724] Loading cookie_secret from /home/hadoopuser/jupyterhub_cookie_secret
> [W 2018-08-24 13:48:33.103 JupyterHub app:365]
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
> 
> [W 2018-08-24 13:48:33.107 JupyterHub app:864] No admin users, admin interface will be unavailable.
> [W 2018-08-24 13:48:33.107 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
> [I 2018-08-24 13:48:33.107 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
> [I 2018-08-24 13:48:33.121 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
> [E 2018-08-24 13:48:33.129 JupyterHub app:1139] Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)
>     Did CONFIGPROXY_AUTH_TOKEN change?

I ran: configurable-http-proxy, it shows below:
```
[hadoopuser@hadoop02 ~]$ configurable-http-proxy
13:49:15.052 - warn: [ConfigProxy] REST API is not authenticated.
13:49:15.063 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
13:49:15.063 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
13:49:15.066 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:253:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
13:49:15.067 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE 127.0.0.1:8001
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```
So what is the right way to restart a new instance? Thank you very much.

**Comment by forbxy** [comment]
try kill the existed configurable-http-proxy, then restart jupyterhub
you should set c.ConfigurableHTTPProxy.auth_token if you don't want restart CHP while restart jupyterhub

**Comment by mdivk** [comment]
Thank you, killing the existing configurable-http-proxy works
