### ISSUE TITLE
[W 2018-08-25 21:32:17.920 JupyterHub auth:471] PAM Authentication failed : [PAM Error 3] Error in service module

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2107]
I want to add more users with the access to the JupyterHub server, below is what I did:
`c.Authenticator.whitelist = {'rxie'}`
I restarted the server, here is the output:

> [I 2018-08-25 20:36:57.623 JupyterHub app:724] Loading cookie_secret from /home/hadoopuser/.jupyter/jupyterh         ub_cookie_secret
> [W 2018-08-25 20:36:57.659 JupyterHub app:365]
>     Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
>     Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
> 
> [W 2018-08-25 20:36:57.663 JupyterHub app:864] No admin users, admin interface will be unavailable.
> [W 2018-08-25 20:36:57.663 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users`          in config.
> [E 2018-08-25 20:36:57.681 JupyterHub app:916] Error adding user 'rxie' already in db
>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.3/site-packages/jupyterhub/app.py", line 911, in init_users
>         yield gen.maybe_future(self.authenticator.add_user(user))
>       File "/usr/local/lib/python3.3/site-packages/jupyterhub/auth.py", line 403, in add_user
>         raise KeyError("User %s does not exist." % user.name)
>     KeyError: 'User rxie does not exist.'

Am I missing anything here? Thank you very much.

**Comment by minrk** [comment]
That error would occur if the hadoopuser lookup of `rxie` failed. Try running as the `hadoopuser` user:

    sudo -u hadoopuser python3 -c 'import pwd; print(pwd.getpwnam("rxie"))'

If that doesn't work, the `hadoopuser` user may have insufficient privileges to check passwords for other users.

**Comment by mdivk** [comment]
I found the root cause, 'rxie' was not in the host, I just created this user and it is working now,  thank you.
