### ISSUE TITLE
Problem while Spawing Single user Server

### ISSUE THREAD

**Issue by kannankumar** [jupyterhub/jupyterhub#2109]
Hi, 
While trying to setup Jupyterhub on a remote server, I'm able to get the User Login to work. 
```
root@d2161a877:~# jupyterhub --port 8000
[I 2018-08-27 03:28:57.785 JupyterHub app:834] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2018-08-27 03:28:57.807 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2018-08-27 03:28:57.807 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-08-27 03:28:57.808 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[I 2018-08-27 03:28:57.848 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-08-27 03:28:57.850 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-08-27 03:28:57.850 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-08-27 03:28:57.850 JupyterHub proxy:458] Starting proxy @ http://*:8000/
03:28:58.404 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
03:28:58.407 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
03:28:58.843 - info: [ConfigProxy] 200 GET /api/routes
[W 2018-08-27 03:28:58.844 JupyterHub proxy:304] Adding missing default route
[I 2018-08-27 03:28:58.844 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
03:28:58.850 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
03:28:58.851 - info: [ConfigProxy] 201 POST /api/routes/
[I 2018-08-27 03:28:58.851 JupyterHub app:1581] JupyterHub is now running at http://:8000/

```
**However it fails as soon as I try to "Start My Server". The spawner fails with the following error:**

```[I 2018-08-27 03:32:39.379 JupyterHub log:122] 200 GET /hub/home (i303431@::ffff:10.52.235.222) 35.68ms
[I 2018-08-27 03:32:58.070 JupyterHub log:122] 302 GET /hub/spawn → /user/i303431/ (i303431@::ffff:10.52.235.222) 6.26ms
[I 2018-08-27 03:32:58.237 JupyterHub log:122] 302 GET /user/i303431/ → /hub/user/i303431/ (@::ffff:10.52.235.222) 1.17ms
Last login: Mon Aug 27 03:22:53 UTC 2018
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-27-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

[I 2018-08-27 03:32:58.532 JupyterHub spawner:978] Spawning jupyterhub-singleuser --port=35439
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/singleuser.py", line 375
    async def check_hub_version(self):
            ^
SyntaxError: invalid syntax
[W 2018-08-27 03:33:08.567 JupyterHub web:1587] 500 GET /hub/user/i303431/ (::ffff:10.52.235.222): Spawner failed to start [status=1]. The logs for i303431 may contain details.
[E 2018-08-27 03:33:08.581 JupyterHub log:114] {
      "X-Forwarded-Host": "d2161a877:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:10.52.235.222",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1535104629|17:jupyter-hub-token|44:YzNjZGQwNjFmMzA0NDUyZWI0NzRlYzM0MDE1NWRkNjE=|de29a3e9d12d454deed201c9941eb07a11e8a68de789178dedb72794b59d0f8d\"",
      "Accept-Language": "en-US,en;q=0.9,en-GB;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://d2161a877:8000/hub/home",
      "Dnt": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "d2161a877:8000"
    }
[E 2018-08-27 03:33:08.581 JupyterHub log:122] 500 GET /hub/user/i303431/ (i303431@::ffff:10.52.235.222) 10186.58ms
[W 2018-08-27 03:33:26.100 JupyterHub user:458] i303431's server never showed up at http://127.0.0.1:35439/user/i303431/ after 30 seconds. Giving up
[E 2018-08-27 03:33:26.118 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fe799a519e8> after timeout
    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/root/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:35439/user/i303431/ didn't respond in 30 seconds

```
I've been searching to find a solution to  similar issue but no luck. Any pointers on where to start looking would also be helpful.

**Comment by minrk** [comment]
What do you get from `which -a jupyterhub-singleuser`?  JupyterHub 0.9 requires Python 3.5, but it looks like your singleuser servers are starting with Python 3.4 instead of the 3.6 that your Hub is running with.

**Comment by kannankumar** [comment]
```
root@d2161a877:~# which -a jupyterhub-singleuser
/usr/local/bin/jupyterhub-singleuser
```
@minrk - I'm not sure why it takes the Python 3.4  where I've installed Anaconda with Python3.6.

**Comment by willingc** [comment]
Hi @kannankumar 

```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-27-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```
It looks like you are using an older Ubuntu version. Make sure the server has  3.6 installed. Double check if you are using a recent Dockerfile for the singleuser notebook image. See https://github.com/jupyter/docker-stacks for examples.

**Comment by kannankumar** [comment]
Hi @willingc 
Thanks for your help. 
I have installed Python3.6 and also made an alias to python3. However now I'm facing issues i think even before the hub is launched :
```
root@d2161a877:~# jupyterhub --port 8000
[I 2018-08-29 02:35:35.305 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.2
[I 2018-08-29 02:35:35.305 JupyterHub app:1667] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.2
[I 2018-08-29 02:35:35.306 JupyterHub app:1014] Loading cookie_secret from /root/jupyterhub_cookie_secret
[E 2018-08-29 02:35:35.314 JupyterHub app:1952]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1949, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1674, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1078, in init_db
        **self.db_kwargs
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/orm.py", line 734, in new_session_factory
        engine = create_engine(url, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
        raise e
      File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
        from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
      File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ModuleNotFoundError: No module named '_sqlite3'
```
On further checking the _sqlite3 module seems to be available :
```root@d2161a877:~# python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _sqlite3 import *
>>>
```
Am I doing something stupid or anything I might be missing ?

**Comment by kannankumar** [comment]
I found out that I was compiling python3.6 from source which required explicit install of  `libsqlite3-dev` for `sqlite3` and then compiling python again. [(Helpful SO post)](https://stackoverflow.com/questions/42766063/python3-6-import-sqlite3-error)

I got it to work by following the above post, but since I wanted to use the `anaconda` packages I removed the other versions of python (`python3.4` and `python3.6`) and went with a fresh `anaconda` install as suggested in [Jupyterhub Wiki for Installation](https://github.com/jupyterhub/jupyterhub/wiki/Installation-of-Jupyterhub-on-remote-server)
