### ISSUE TITLE
SingleUser failed to connect to Hub ip

### ISSUE THREAD

**Issue by qwinkler** [jupyterhub/jupyterhub#2131]
Hi. I want to create multi-user Jupyterhub inside docker container with dockerspawner inside this container. I don't want to use a SSL and OAuth right now, just simple project. Project structure(details in README file):
[https://github.com/smoulderme/test-jupyterhub-docker](https://github.com/smoulderme/test-jupyterhub-docker)

It works perfect with default spawner. If I comment these 2 lines(9-10):
[https://github.com/smoulderme/test-jupyterhub-docker/blob/master/jupyterhub_config.py#L9](https://github.com/smoulderme/test-jupyterhub-docker/blob/master/jupyterhub_config.py#L9)
then all will work.

If I add dockerspawner as jupyterhub spawner class - then I got a message in `jupyer-<username>` container:
`Failed to connect to my Hub at http://172.26.0.2:8081/hub/api (attempt 1/5). Is it running?`
I tried to execute this command from my terminal:
`curl http://172.26.0.2:8081/hub/api`
And I got respone:
`{"version": "0.9.1"}`

So, the api is reachable.

**Full log from jupyterhub container:**
```
[I 2018-09-05 17:41:19.698 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.1
[I 2018-09-05 17:41:19.698 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.10.0
[I 2018-09-05 17:41:19.703 JupyterHub app:1053] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-09-05 17:41:19.732 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-09-05 17:41:19.733 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-09-05 17:41:19.738 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
[I 2018-09-05 17:41:19.756 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2018-09-05 17:41:19.823 JupyterHub app:1849] Hub API listening on http://172.26.0.2:8081/hub/
[W 2018-09-05 17:41:19.825 JupyterHub proxy:552] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-09-05 17:41:19.825 JupyterHub proxy:554] Starting proxy @ http://:8000
17:41:20.349 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
17:41:20.352 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
17:41:20.451 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-09-05 17:41:20.452 JupyterHub proxy:301] Checking routes
[I 2018-09-05 17:41:20.452 JupyterHub proxy:370] Adding default route for Hub: / => http://172.26.0.2:8081
17:41:20.455 - info: [ConfigProxy] Adding route / -> http://172.26.0.2:8081
17:41:20.456 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-09-05 17:41:20.457 JupyterHub app:1906] JupyterHub is now running at http://:8000
[I 2018-09-05 17:41:20.815 JupyterHub log:158] 302 GET / -> /hub (@::ffff:172.26.0.1) 1.58ms
[W 2018-09-05 17:41:20.824 JupyterHub base:242] Invalid or expired cookie token
[I 2018-09-05 17:41:20.825 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:172.26.0.1) 1.26ms
[W 2018-09-05 17:41:20.833 JupyterHub base:242] Invalid or expired cookie token
[I 2018-09-05 17:41:20.834 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@::ffff:172.26.0.1) 1.47ms
[I 2018-09-05 17:41:20.882 JupyterHub log:158] 200 GET /hub/login (@::ffff:172.26.0.1) 42.50ms
[I 2018-09-05 17:41:23.003 JupyterHub base:499] User logged in: test
[I 2018-09-05 17:41:23.004 JupyterHub log:158] 302 POST /hub/login?next= -> /user/test/ (test@::ffff:172.26.0.1) 17.41ms
[I 2018-09-05 17:41:23.013 JupyterHub log:158] 302 GET /user/test/ -> /hub/user/test/ (@::ffff:172.26.0.1) 1.82ms
[W 2018-09-05 17:41:23.063 JupyterHub auth:642] Failed to open PAM session for test: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2018-09-05 17:41:23.063 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2018-09-05 17:41:23.077 JupyterHub dockerspawner:564] Container 'jupyter-test' is gone
[I 2018-09-05 17:41:23.188 JupyterHub dockerspawner:698] Created container jupyter-test (id: 7154e1e) from image jupyterhub/singleuser:0.8
[I 2018-09-05 17:41:23.188 JupyterHub dockerspawner:721] Starting container jupyter-test (id: 7154e1e)
[W 2018-09-05 17:41:33.037 JupyterHub base:699] User test is slow to become responsive (timeout=10)
[I 2018-09-05 17:41:33.038 JupyterHub base:1016] test is pending spawn
[I 2018-09-05 17:41:33.050 JupyterHub log:158] 200 GET /hub/user/test/ (test@::ffff:172.26.0.1) 10032.76ms
[W 2018-09-05 17:41:53.286 JupyterHub user:504] test's server never showed up at http://127.0.0.1:32802/user/test/ after 30 seconds. Giving up
[I 2018-09-05 17:41:53.290 JupyterHub dockerspawner:794] Stopping container jupyter-test (id: 7154e1e)
[E 2018-09-05 17:41:53.298 JupyterHub gen:940] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError("Server at http://127.0.0.1:32802/user/test/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 522, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 496, in spawn
        resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32802/user/test/ didn't respond in 30 seconds
    
[I 2018-09-05 17:43:14.032 JupyterHub log:158] 200 GET /hub/api (@172.26.0.1) 0.98ms
```

**Full log from jupyter-test container:**
```
/usr/local/bin/start-singleuser.sh: ignoring /usr/local/bin/start-notebook.d/*
Container must be run with group "root" to update passwd file
Executing the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888
[W 2018-09-05 17:41:24.198 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-09-05 17:41:24.548 SingleUserNotebookApp extension:59] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-09-05 17:41:24.548 SingleUserNotebookApp extension:60] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-09-05 17:41:24.554 SingleUserNotebookApp singleuser:365] Starting jupyterhub-singleuser server version 0.8.1
[E 2018-09-05 17:41:44.578 SingleUserNotebookApp singleuser:354] Failed to connect to my Hub at http://172.26.0.2:8081/hub/api (attempt 1/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 351, in check_hub_version
        resp = yield client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
    tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
[C 2018-09-05 17:41:53.320 SingleUserNotebookApp notebookapp:1497] received signal 15, stopping
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 455, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 367, in start
    ioloop.IOLoop.current().run_sync(self.check_hub_version)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 571, in run_sync
    self.start()
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1498, in _signal_stop
    self.io_loop.add_callback_from_signal(self.io_loop.stop)
AttributeError: 'SingleUserNotebookApp' object has no attribute 'io_loop' 
```

**Comment by minrk** [comment]
What docker image are you using? It looks like it has an incompatible collection of packages (specifically, an old version of `notebook` and a new version of `tornado`). Try updating packages in your image.

**Comment by smoulderme** [comment]
> What docker image are you using? It looks like it has an incompatible collection of packages (specifically, an old version of `notebook` and a new version of `tornado`). Try updating packages in your image.

Thank you for your reply! I tried with:
`c.DockerSpawner.image = 'jupyterhub/singleuser:0.9.1'`

And:
`c.DockerSpawner.image = 'jupyterhub/singleuser:latest`

Also I add to Dockerfile this line:
`RUN apt-get -y upgrade`

but nothing is changed, unfortunately...

**Comment by willingc** [comment]
As @minrk recommended, please make sure that you are using updated versions in the image. Thanks.

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html provides information about images.

**Comment by smoulderme** [comment]
> As @minrk recommended, please make sure that you are using updated versions in the image. Thanks.
> 
> https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html provides information about images.

Thank you for reply!
Now I am using latest jupyterhub image in Dockerfile: `FROM jupyterhub/jupyterhub:latest`
Also I made updates and upgrades if it is needed: `RUN apt-get update && apt-get -y upgrade`

Next, I am using latest datascience image:
```
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = 'jupyter/datascience-notebook:latest'
```

**Full project structure:**
[https://github.com/smoulderme/test-jupyterhub-docker](https://github.com/smoulderme/test-jupyterhub-docker)

And I've had no luck as yet. I have the same problem:

```
500 : Internal Server Error

Failed to reach your server. Please try again later. Contact admin if the issue persists.

You can try restarting your server from the home page.

```

Without Dockerspawner(with default spawner - everything is ok).

**Full log from jupyterhub container:**
```
[I 2018-09-19 08:35:25.915 JupyterHub app:1667] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.3
[I 2018-09-19 08:35:25.915 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.10.0
[I 2018-09-19 08:35:25.919 JupyterHub app:1053] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-09-19 08:35:25.941 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-09-19 08:35:25.941 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-09-19 08:35:25.946 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
[I 2018-09-19 08:35:25.967 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2018-09-19 08:35:26.038 JupyterHub app:1849] Hub API listening on http://172.26.0.2:8081/hub/
[W 2018-09-19 08:35:26.039 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-09-19 08:35:26.039 JupyterHub proxy:567] Starting proxy @ http://:8000
08:35:26.497 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
08:35:26.499 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
08:35:26.514 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-09-19 08:35:26.514 JupyterHub proxy:301] Checking routes
[I 2018-09-19 08:35:26.515 JupyterHub proxy:370] Adding default route for Hub: / => http://172.26.0.2:8081
08:35:26.517 - info: [ConfigProxy] Adding route / -> http://172.26.0.2:8081
08:35:26.518 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-09-19 08:35:26.518 JupyterHub app:1906] JupyterHub is now running at http://:8000
[I 2018-09-19 08:35:29.925 JupyterHub log:158] 302 GET / -> /hub (@::ffff:172.26.0.1) 1.24ms
[W 2018-09-19 08:35:29.933 JupyterHub base:242] Invalid or expired cookie token
[I 2018-09-19 08:35:29.934 JupyterHub log:158] 302 GET /hub -> /hub/ (@::ffff:172.26.0.1) 0.69ms
[W 2018-09-19 08:35:29.942 JupyterHub base:242] Invalid or expired cookie token
[I 2018-09-19 08:35:29.943 JupyterHub log:158] 302 GET /hub/ -> /hub/login (@::ffff:172.26.0.1) 1.23ms
[I 2018-09-19 08:35:29.988 JupyterHub log:158] 200 GET /hub/login (@::ffff:172.26.0.1) 39.01ms
[I 2018-09-19 08:35:32.369 JupyterHub base:499] User logged in: test
[I 2018-09-19 08:35:32.370 JupyterHub log:158] 302 POST /hub/login?next= -> /user/test/ (test@::ffff:172.26.0.1) 15.41ms
[I 2018-09-19 08:35:32.383 JupyterHub log:158] 302 GET /user/test/ -> /hub/user/test/ (@::ffff:172.26.0.1) 0.74ms
[W 2018-09-19 08:35:32.441 JupyterHub auth:642] Failed to open PAM session for test: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2018-09-19 08:35:32.441 JupyterHub auth:643] Disabling PAM sessions from now on.
[I 2018-09-19 08:35:32.460 JupyterHub dockerspawner:564] Container 'jupyter-test' is gone
[I 2018-09-19 08:35:32.586 JupyterHub dockerspawner:698] Created container jupyter-test (id: f71df0c) from image jupyter/datascience-notebook:latest
[I 2018-09-19 08:35:32.587 JupyterHub dockerspawner:721] Starting container jupyter-test (id: f71df0c)
[W 2018-09-19 08:35:42.410 JupyterHub base:734] User test is slow to become responsive (timeout=10)
[I 2018-09-19 08:35:42.410 JupyterHub base:1056] test is pending spawn
[I 2018-09-19 08:35:42.419 JupyterHub log:158] 200 GET /hub/user/test/ (test@::ffff:172.26.0.1) 10030.51ms
[W 2018-09-19 08:36:02.761 JupyterHub user:510] test's server never showed up at http://127.0.0.1:32769/user/test/ after 30 seconds. Giving up
[I 2018-09-19 08:36:02.769 JupyterHub dockerspawner:794] Stopping container jupyter-test (id: f71df0c)
[E 2018-09-19 08:36:02.776 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError("Server at http://127.0.0.1:32769/user/test/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 528, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 502, in spawn
        resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
        timeout=timeout
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:32769/user/test/ didn't respond in 30 seconds

```
**Full log from jupyter-test container:**
```
Container must be run with group "root" to update passwd file
Executing the command: jupyterhub-singleuser --ip="0.0.0.0" --port=8888
[W 2018-09-19 08:35:33.518 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2018-09-19 08:35:33.818 SingleUserNotebookApp extension:59] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2018-09-19 08:35:33.818 SingleUserNotebookApp extension:60] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2018-09-19 08:35:33.828 SingleUserNotebookApp singleuser:405] Starting jupyterhub-singleuser server version 0.9.2
[E 2018-09-19 08:35:53.835 SingleUserNotebookApp singleuser:388] Failed to connect to my Hub at http://172.26.0.2:8081/hub/api (attempt 1/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 385, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
[C 2018-09-19 08:36:02.800 SingleUserNotebookApp notebookapp:1497] received signal 15, stopping
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 495, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 407, in start
    ioloop.IOLoop.current().run_sync(self.check_hub_version)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 571, in run_sync
    self.start()
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 1390, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1498, in _signal_stop
    self.io_loop.add_callback_from_signal(self.io_loop.stop)
AttributeError: 'SingleUserNotebookApp' object has no attribute 'io_loop'

```

**Comment by minrk** [comment]
> I tried to execute this command from my terminal:
>     curl http://172.26.0.2:8081/hub/api

Can you run that same command inside a docker container? I suspect there's an issue with the docker networking setup. When the Hub is inside docker itself, I would typically use `c.JupyterHub.hub_ip = '0.0.0.0'` which sets it to listen on all interfaces. When this is done, containers use the Hub's hostname (its container id by default) to connect, which tends to be more reliable on the docker network.

**Comment by smoulderme** [comment]
> Can you run that same command inside a docker container?.

Yes, of course!
I installed curl inside Jupyterhub container and there is the output:
```
root@87205d2e1e7b:/srv/jupyterhub# curl http://172.26.0.2:8081/hub/api
{"version": "0.9.3"}
```
I tried to execute this command inside user's container(**jupyter-test**) but I got a fail: 
```
sudo docker exec -it -u root jupyter-test bash
root@4cf13206b660:~# curl http://172.26.0.2:8081/hub/api
```

I didn't get an output and container was killed.

Also I inserted this line:
```
c.JupyterHub.hub_ip = '0.0.0.0'
```

Instead of this line:
```
c.JupyterHub.hub_ip = public_ips()[0]
```

Nothing is changed except of hub api url:
```
[E 2018-09-19 12:18:33.308 SingleUserNotebookApp singleuser:388] Failed to connect to my Hub at http://eeefb453818f:8081/hub/api (attempt 1/5). Is it running?
```

Jupyterhub container:
```
root@eeefb453818f:/srv/jupyterhub# curl http://eeefb453818f:8081/hub/api
{"version": "0.9.3"}
```

Last thing.
I added a network in docker-compose file:
```
environment:
       DOCKER_NETWORK_NAME: jupyterhub-network
```

Nothing is changed except for hub api, unfortunately:
```
root@2d55475d58ae:/srv/jupyterhub# curl http://192.168.64.2:8081/hub/api
{"version": "0.9.3"}
```

**Comment by getitzack** [comment]
I got the same error without using docker.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
