### ISSUE TITLE
adduser default not compatible with CentOS

### ISSUE THREAD

**Issue by LegitStack** [jupyterhub/jupyterhub#2145]
This maybe a bug, or unique to my setup idk.

I'm using PAMAuthenticator. On the admin screen I tried creating a new user 'btack' but it errored.

You'll notice the command it uses is
`adduser -q --gecos '""' --disabled-password btack`
But on my CentOS 7 system that doesn't seem to work, (the `-q`) and I don't even see it on linux man pages such as [linux.die.net](https://linux.die.net/man/8/adduser).

So anyway, is it a bug or is it just me?

Either way, how do I override the `LocalAuthentication.add_system_user(self,user)` within my `jupyterhub_config.py` file?

here's my error:
```
[I 2018-09-12 11:08:11.391 JupyterHub auth:511] Creating user: adduser -q --gecos '""' --disabled-password btack
[E 2018-09-12 11:08:11.393 JupyterHub users:83] Failed to create user: btack
    Traceback (most recent call last):
      File "/var/anaconda3/lib/python3.6/site-packages/jupyterhub/apihandlers/users.py", line 81, in post
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/var/anaconda3/lib/python3.6/site-packages/jupyterhub/auth.py", line 487, in add_user
        yield gen.maybe_future(self.add_system_user(user))
      File "/var/anaconda3/lib/python3.6/site-packages/jupyterhub/auth.py", line 516, in add_system_user
        raise RuntimeError("Failed to create system user %s: %s" % (name, err))
    RuntimeError: Failed to create system user btack: adduser: invalid option -- 'q'
    Usage: adduser [options] LOGIN
           adduser -D
           adduser -D [options]

    Options:
      -b, --base-dir BASE_DIR       base directory for the home directory of the
                                    new account
      -c, --comment COMMENT         GECOS field of the new account
      -d, --home-dir HOME_DIR       home directory of the new account
      -D, --defaults                print or change default useradd configuration
      -e, --expiredate EXPIRE_DATE  expiration date of the new account
      -f, --inactive INACTIVE       password inactivity period of the new account
      -g, --gid GROUP               name or ID of the primary group of the new
                                    account
      -G, --groups GROUPS           list of supplementary groups of the new
                                    account
      -h, --help                    display this help message and exit
      -k, --skel SKEL_DIR           use this alternative skeleton directory
      -K, --key KEY=VALUE           override /etc/login.defs defaults
      -l, --no-log-init             do not add the user to the lastlog and
                                    faillog databases
      -m, --create-home             create the user's home directory
      -M, --no-create-home          do not create the user's home directory
      -N, --no-user-group           do not create a group with the same name as
                                    the user
      -o, --non-unique              allow to create users with duplicate
                                    (non-unique) UID
      -p, --password PASSWORD       encrypted password of the new account
      -r, --system                  create a system account
      -R, --root CHROOT_DIR         directory to chroot into
      -s, --shell SHELL             login shell of the new account
      -u, --uid UID                 user ID of the new account
      -U, --user-group              create a group with the same name as the user
      -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping


```

**Comment by minrk** [comment]
I guess debian- and fedora-based adduser have different options. The command was tested on Ubuntu, which has:

```
$ adduser --help
...
general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX[_SYSTEM] configuration variable
  --extrausers      uses extra users as the database
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file
```

Deviations like this are why this command is configurable. You can set it with:

```
c.LocalAuthenticator.add_user_cmd = ['adduser', '-m', '-G', 'jupyterhub-users']
```

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please leave a comment requesting this issue be reopened if you need additional assistance. Thanks to all!

**Comment by karthisuku** [comment]
Thanks @minrk for the great documentation

**Comment by cateto** [comment]
Red Hat 4.8.5-44 also has this problem. Thanks @minrk
