### ISSUE TITLE
JupyterHub is started but not able to log in: Error loading server extension jupyterlab

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2148]
I am having error below when I tried to use jupyterhub:

Spawning jupyterhub-singleuser --port=50928
[W 2018-09-13 22:41:17.283 SingleUserNotebookApp notebookapp:1554] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1546, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'

Why there is error relates to jupyterlab?

I have previous jupyter (with three kernels) on this node, would that matter? 

How can I completely uninstall the existing jupyter related tool?

Thank you very much.

**Comment by minrk** [comment]
init_server_extensions should see these extension-loading errors and move on. Are there later errors that indicate why it's not starting?

To disable the jupyterlab serverextension:

    jupyter serverextension disable jupyterlab

**Comment by mdivk** [comment]
Thank you Min.

The following output is as below:


> 
> [I 2018-09-13 22:41:15.788 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=50928
> [W 2018-09-13 22:41:17.283 SingleUserNotebookApp notebookapp:1554] Error loading server extension jupyterlab
>     Traceback (most recent call last):
>       File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1546, in init_server_extensions
>         mod = importlib.import_module(modulename)
>       File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
>     ModuleNotFoundError: No module named 'jupyterlab'
> [I 2018-09-13 22:41:17.285 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.3
> [I 2018-09-13 22:41:17.291 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 1.75ms
> [I 2018-09-13 22:41:17.292 SingleUserNotebookApp notebookapp:1685] Serving notebooks from local directory: /home/rxie
> [I 2018-09-13 22:41:17.292 SingleUserNotebookApp notebookapp:1685] The Jupyter Notebook is running at:
> [I 2018-09-13 22:41:17.292 SingleUserNotebookApp notebookapp:1685] http://cedgedev02:50928/user/rxie/
> [I 2018-09-13 22:41:17.293 SingleUserNotebookApp notebookapp:1686] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [W 2018-09-13 22:41:25.658 JupyterHub base:734] User rxie is slow to become responsive (timeout=10)
> [I 2018-09-13 22:41:25.659 JupyterHub base:1056] rxie is pending spawn
> [I 2018-09-13 22:41:25.670 JupyterHub log:158] 200 GET /hub/user/rxie/ (rxie@192.168.103.81) 10031.70ms
> [W 2018-09-13 22:41:44.859 JupyterHub user:510] rxie's server never showed up at http://127.0.0.1:50928/user/rxie/ after 30 seconds. Giving up
> [I 2018-09-13 22:41:44.861 SingleUserNotebookApp notebookapp:1617] Shutting down 0 kernels
> [E 2018-09-13 22:41:45.092 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError("Server at http://127.0.0.1:50928/user/rxie/ didn't respond in 30 seconds",)> after timeout
>     Traceback (most recent call last):
>       File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
>         future.result()
>       File "/usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
>         await spawn_future
>       File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 528, in spawn
>         raise e
>       File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 502, in spawn
>         resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
>       File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
>         timeout=timeout
>       File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
>         raise TimeoutError(fail_message)
>     TimeoutError: Server at http://127.0.0.1:50928/user/rxie/ didn't respond in 30 seconds
> 
> [I 2018-09-13 22:41:45.098 JupyterHub log:158] 200 GET /hub/api/users/rxie/server/progress (rxie@192.168.103.81) 19325.74ms
> 22:45:25.304 - info: [ConfigProxy] 200 GET /api/routes
> [I 2018-09-13 22:45:25.306 JupyterHub proxy:301] Checking routes
> 22:50:25.304 - info: [ConfigProxy] 200 GET /api/routes
> [I 2018-09-13 22:50:25.306 JupyterHub proxy:301] Checking routes
> 22:55:25.304 - info: [ConfigProxy] 200 GET /api/routes
> 

I followed your suggestion and disabled jupyterlab, though I seem to have started the JupyterHub successfully, and still not able to login:

> [I 2018-09-14 08:46:14.406 JupyterHub app:1906] JupyterHub is now running at http://192.168.100.219:443/
> [I 2018-09-14 08:46:26.099 JupyterHub log:158] 200 GET /hub/home (rxie@192.168.103.81) 94.00ms
> [I 2018-09-14 08:46:29.126 JupyterHub log:158] 302 GET /hub/spawn -> /user/rxie/ (rxie@192.168.103.81) 15.09ms
> [I 2018-09-14 08:46:29.146 JupyterHub log:158] 302 GET /user/rxie/ -> /hub/user/rxie/ (@192.168.103.81) 1.24ms
> [W 2018-09-14 08:46:29.278 JupyterHub auth:642] Failed to open PAM session for rxie: [PAM Error 14] Cannot make/remove an entry for the specified session
> [W 2018-09-14 08:46:29.278 JupyterHub auth:643] Disabling PAM sessions from now on.
> [I 2018-09-14 08:46:29.295 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=39851
> [I 2018-09-14 08:46:30.756 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.3
> [I 2018-09-14 08:46:30.766 JupyterHub log:158] 200 GET /hub/api (@127.0.0.1) 2.03ms
> [I 2018-09-14 08:46:30.768 SingleUserNotebookApp notebookapp:1685] Serving notebooks from local directory: /home/rxie
> [I 2018-09-14 08:46:30.769 SingleUserNotebookApp notebookapp:1685] The Jupyter Notebook is running at:
> [I 2018-09-14 08:46:30.769 SingleUserNotebookApp notebookapp:1685] http://cedgedev02:39851/user/rxie/
> [I 2018-09-14 08:46:30.769 SingleUserNotebookApp notebookapp:1686] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [W 2018-09-14 08:46:39.187 JupyterHub base:734] User rxie is slow to become responsive (timeout=10)
> [I 2018-09-14 08:46:39.187 JupyterHub base:1056] rxie is pending spawn
> [I 2018-09-14 08:46:39.198 JupyterHub log:158] 200 GET /hub/user/rxie/ (rxie@192.168.103.81) 10031.61ms
> [W 2018-09-14 08:47:00.644 JupyterHub user:510] rxie's server never showed up at http://127.0.0.1:39851/user/rxie/ after 30 seconds. Giving up
> [I 2018-09-14 08:47:00.646 SingleUserNotebookApp notebookapp:1617] Shutting down 0 kernels
> [E 2018-09-14 08:47:00.873 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError("Server at http://127.0.0.1:39851/user/rxie/ didn't respond in 30 seconds",)> after timeout
>     Traceback (most recent call last):
>       File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
>         future.result()
>       File "/usr/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
>         await spawn_future
>       File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 528, in spawn
>         raise e
>       File "/usr/lib/python3.6/site-packages/jupyterhub/user.py", line 502, in spawn
>         resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
>       File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
>         timeout=timeout
>       File "/usr/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
>         raise TimeoutError(fail_message)
>     TimeoutError: Server at http://127.0.0.1:39851/user/rxie/ didn't respond in 30 seconds
> 
> [I 2018-09-14 08:47:00.878 JupyterHub log:158] 200 GET /hub/api/users/rxie/server/progress (rxie@192.168.103.81) 21576.49ms
>

**Comment by mdivk** [comment]
so after jupyterlab is disabled, relative error was gone that's all, the remaining output is the same as before.

**Comment by mdivk** [comment]
By the way, can anyone tell me what would be the best way to completely remove all the existing Jupyter stuff so that I can start a fresh new installation of JupyterHub. I have three existing kernels for Jupyter under my name:

jupyter kernelspec list
Available kernels:
  scala      /home/rxie/.local/share/jupyter/kernels/scala
  python2    /usr/share/jupyter/kernels/python2
  python3    /usr/share/jupyter/kernels/python3

Thank you very much.
