### ISSUE TITLE
tornado.httpclient.HTTPClientError: HTTP 403: Forbidden

### ISSUE THREAD

**Issue by udaynaik** [jupyterhub/jupyterhub#2173]
Using 0.9.3 JupyterHub in a docker container.  Tried to tweak proxy, hub and API ip and port settings with no luck so far.  

```
jupyterhub | [I 2018-09-22 00:59:51.986 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.9.1
jupyterhub | [D 2018-09-22 00:59:51.991 JupyterHub app:1048] Generating new cookie_secret
jupyterhub | [I 2018-09-22 00:59:51.992 JupyterHub app:1053] Writing cookie_secret to /data/jupyterhub_cookie_secret
jupyterhub | [D 2018-09-22 00:59:51.992 JupyterHub app:1069] Connecting to db: sqlite:///jupyterhub.sqlite
jupyterhub | [D 2018-09-22 00:59:52.016 JupyterHub orm:656] Stamping empty database with alembic revision 896818069c98
jupyterhub | [I 2018-09-22 00:59:52.020 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
jupyterhub | [I 2018-09-22 00:59:52.020 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
jupyterhub | [I 2018-09-22 00:59:52.031 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
jupyterhub | [D 2018-09-22 00:59:52.031 alembic.runtime.migration migration:516] new branch insert 896818069c98
jupyterhub | [W 2018-09-22 00:59:52.338 JupyterHub configurable:168] Config option `base_dn` not recognized by `LDAPAuthenticator`.
jupyterhub | [D 2018-09-22 00:59:52.380 JupyterHub app:1471] Loading state for admin from db
jupyterhub | [D 2018-09-22 00:59:52.382 JupyterHub app:1471] Loading state for user from db
jupyterhub | [D 2018-09-22 00:59:52.383 JupyterHub app:1487] Loaded users:
jupyterhub |        admin admin
jupyterhub |         user
jupyterhub | [I 2018-09-22 00:59:52.393 JupyterHub app:1849] Hub API listening on http://jupyterhub:8010/hub/
jupyterhub | [W 2018-09-22 00:59:52.394 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
jupyterhub | [I 2018-09-22 00:59:52.394 JupyterHub proxy:567] Starting proxy @ http://0.0.0.0:8000/
jupyterhub | [D 2018-09-22 00:59:52.394 JupyterHub proxy:568] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', 'jupyterhub', '--api-port', '5432', '--error-target', 'http://jupyterhub:8010/hub/error']
jupyterhub | [D 2018-09-22 00:59:52.402 JupyterHub proxy:517] Writing proxy pid file: jupyterhub-proxy.pid
jupyterhub | 00:59:52.796 - info: [ConfigProxy] Proxying http://0.0.0.0:8000 to (no default)
jupyterhub | 00:59:52.798 - info: [ConfigProxy] Proxy API at http://jupyterhub:5432/api/routes
jupyterhub | [D 2018-09-22 00:59:53.360 JupyterHub proxy:603] Proxy started and appears to be up
jupyterhub | [D 2018-09-22 00:59:53.361 JupyterHub proxy:296] Fetching routes to check
jupyterhub | [D 2018-09-22 00:59:53.363 JupyterHub proxy:686] Proxy: Fetching GET http://jupyterhub:5432/api/routes
jupyterhub | 00:59:53.368 - warn: [ConfigProxy] 403 GET /api/routes 
jupyterhub | [E 2018-09-22 00:59:53.369 JupyterHub app:1952]
jupyterhub |     Traceback (most recent call last):
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1950, in launch_instance_async
jupyterhub |         await self.start()
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1895, in start
jupyterhub |         await self.proxy.check_routes(self.users, self._service_map)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 57, in locked_method
jupyterhub |         return await method(*args, **kwargs)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 297, in check_routes
jupyterhub |         routes = await self.get_all_routes()
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 733, in get_all_routes
jupyterhub |         resp = await self.api_request('', client=client)
jupyterhub |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 694, in api_request
jupyterhub |         result = await client.fetch(req)
jupyterhub |     tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
jupyterhub |     
jupyterhub | [D 2018-09-22 00:59:53.371 JupyterHub application:647] Exiting application: jupyterhub
jupyterhub exited with code 1
```

Here is my config snippets:
```
# User containers will access hub by container name on the Docker network
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8010

#c.JupyterHub.hub_ip = '0.0.0.0'  # listen on all interfaces
#c.JupyterHub.hub_connect_ip = '0.0.0.0'  # ip as seen on the docker network. Can also be a hostname.

##### Following is proxy ports 
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.port = 8000

###### Proxy API
c.ConfigurableHTTPProxy.api_url = 'http://jupyterhub:5432'
#c.JupyterHub.proxy_api_ip = 'jupyterhub'
#c.JupyterHub.proxy_api_port = 5432


```

Here is docker inspect relevant portions:
```
 "Config": {
            "Hostname": "32136a6282d6",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SSL_KEY=./secrets/jupyterhub.key",
                "SSL_CERT=./secrets/jupyterhub.crt",
                "DOCKER_NETWORK_NAME=jupyterhub-network",
                "DOCKER_NOTEBOOK_IMAGE=digitalanatomist/hub-deep-learning-notebook-gpu:latest ## feel free to use or change that",
                "DOCKER_NOTEBOOK_DIR=/home/ ## feel free to use or change that but be consistent with the user defeined in the container by the image",
                "DOCKER_SPAWN_CMD=start-singleuser.sh",
                "CONFIGPROXY_AUTH_TOKEN= \"openssl rand -hex 32\" #configure your key as you like; you need to change that... also you can use another method which would be preveribly used so the key does not show up here",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "POSTGRES_DB=jupyterhub",
                "POSTGRES_HOST=hub-db",
                "POSTGRES_PASSWORD=supersecretpassword # you need to change that... also you can use another method which would be preveribly used so the password does not show up here either in the secrets folder under posgres.env or as a docker-volume",
                "PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "jupyterhub",
                "-f",
                "/srv/jupyterhub/jupyterhub_config.py"
            ],
            "Image": "jupyterhub",
            "Volumes": {
                "/data/hub": {},
                "/home/ ## feel free to use or change that but be consistent with the user defeined in the container by the image": {},
                "/var/run/docker.sock": {}
            },
            "WorkingDir": "/srv/jupyterhub",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "ab038051745c128406295f303a073a989196e8b3303a5294e9e3bebd25d5005e",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "gpu-jupyterhub",
                "com.docker.compose.service": "hub",
                "com.docker.compose.version": "1.22.0",
                "maintainer": "Jupyter Project <jupyter@googlegroups.com>",
                "org.jupyter.service": "jupyterhub"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a628f5b7661632f2b37d4b9f757222cce1a67cd141301ca23ec9cafb41882ded",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/a628f5b76616",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "jupyterhub-network": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "hub",
                        "32136a6282d6"
                    ],
                    "NetworkID": "fe9f39040e3b8f118d14e078512aff41b0c97e8c336d1997fffc7bdf02b5fa8e",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }

```

**Comment by whlteXbread** [comment]
I'm having this same issue (now on 0.9.4), can't quite figure out what's going on. FWIW this configuration comes from [GPU-Jupyterhub](https://github.com/FAU-DLM/GPU-Jupyterhub) and the relevant Jupyterhub dockerfile is in the root of the project. 

In that `jupyterhub_config.py` there's no `c.JupyterHub.ip` specified, but it doesn't seem to matter if it's specified or not: the error still occurs. I also changed all the IP parameters to `127.0.0.1` but that didn't seem to do anything either.

Stumped.

**Comment by whlteXbread** [comment]
Okay, it was a really dumb mistake on my part. 

Basically, even if something is "commented" after the equals sign in the `.env` file, the comment ends up being part of the variable.

So for example, the following line in the `inspect` output that @udaynaik posted is problematic:

```
"CONFIGPROXY_AUTH_TOKEN= \"openssl rand -hex 32\" #configure your key as you like; you need to change that... also you can use another method which would be preveribly used so the key does not show up here",
```
Not only does that command need to be evaluated outside the `.env` file, the comment must be removed as well. I was digging through a [different issue](https://github.com/jupyterhub/jupyterhub/issues/1377#issuecomment-433935529) that tipped me off.

Hope this helps somebody else too.
