### ISSUE TITLE
Hub login problem, fail to start jupyterhub with sudo

### ISSUE THREAD

**Issue by sidebo** [jupyterhub/jupyterhub#2232]
I can start jupyterhub but not log in using my unix credentials ("Invalid username or password"). In this thread https://github.com/jupyterhub/jupyterhub/issues/1612 it was recommended I start the hub as superuser to possibly get around this, but then I get the error below. Any help would be greatly appreciated. I'm on an slc6 machine, and installed jupyterhub via linuxbrew. 

```
sudo /home/linuxbrew/.linuxbrew/bin/jupyterhub

[I 2018-10-10 11:05:38.837 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-10-10 11:05:38.838 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-10-10 11:05:38.840 JupyterHub app:1016] Loading cookie_secret from /home/psidebo/sh1015-lab-atlas-open-data-zbosonmass/jupyterhub/jupyterhub_cookie_secret
[I 2018-10-10 11:05:38.859 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-10-10 11:05:38.859 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-10-10 11:05:38.859 JupyterHub app:1174] Add any administrative users to 'c.Authenticator.admin_users' in config.
[I 2018-10-10 11:05:38.859 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-10-10 11:05:38.894 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-10-10 11:05:38.894 JupyterHub proxy:472] Found proxy pid file: /home/psidebo/sh1015-lab-atlas-open-data-zbosonmass/jupyterhub/jupyterhub-proxy.pid
[W 2018-10-10 11:05:38.894 JupyterHub proxy:484] Proxy no longer running at pid=48214
[W 2018-10-10 11:05:38.895 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-10-10 11:05:38.895 JupyterHub proxy:567] Starting proxy @ http://:8000

/home/linuxbrew/.linuxbrew/lib/node_modules/configurable-http-proxy/lib/configproxy.js:118
  let camelOptions = {};
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:95:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[C 2018-10-10 11:05:39.825 JupyterHub app:1867] Failed to start proxy
    Traceback (most recent call last):
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/jupyterhub/app.py", line 1865, in start
        await self.proxy.start()
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/jupyterhub/proxy.py", line 594, in start
        _check_process()
      File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/jupyterhub/proxy.py", line 590, in _check_process
        raise e from None
    RuntimeError: Proxy failed to start with exit code 8
```

**Comment by minrk** [comment]
sudo clears most of your env, so if you want to inherit your path, you need to either `sudo /path/to/script` where the script ensures the relevant env is setup, or use `sudo -s` to start a sudo shell and then run commands from there, or use `sudo -E ` to preserve some env.
