### ISSUE TITLE
Username with upper-case character causes 500 error

### ISSUE THREAD

**Issue by paulshealy1** [jupyterhub/jupyterhub#2263]
**Describe the bug**
I am on Ubuntu 16.04. If I create a username with an upper-case character, say userA1, I get a 500 Internal Server Error when I log in to JupyterHub. The stack trace:

    Traceback (most recent call last):
      File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/anaconda/envs/py35/lib/python3.5/asyncio/futures.py", line 294, in result
        raise self._exception
      File "/anaconda/envs/py35/lib/python3.5/asyncio/tasks.py", line 242, in _step
        result = coro.throw(exc)
      File "/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 483, in login_user
        await maybe_future(self.authenticator.add_user(user))
      File "/anaconda/envs/py35/lib/python3.5/asyncio/futures.py", line 381, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/anaconda/envs/py35/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
        future.result()
      File "/anaconda/envs/py35/lib/python3.5/asyncio/futures.py", line 294, in result
        raise self._exception
      File "/anaconda/envs/py35/lib/python3.5/asyncio/tasks.py", line 240, in _step
        result = coro.send(None)
      File "/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/auth.py", line 525, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User usera1 does not exist.'

**Comment by minrk** [comment]
This error is raised when a jupyterhub user is created that doesn't correspond to a local system user and a system user is needed (i.e. a LocalAuthenticator class is used), but `LocalAuthenticator.create_system_users` has not been set.

How was the user created? What Authenticator and Spawner are you using, and what version of jupyterhub?

**Comment by minrk** [comment]
#2264 adds a more informative error message, explaining that create_system_users may be an option.
