### ISSUE TITLE
 Error 500 when trying to use GitHub OAuth

### ISSUE THREAD

**Issue by msmarchena** [jupyterhub/jupyterhub#2285]
Hi, I am trying to add users using GitHub authentificator but I am having some problems. Jupyterhub is installed in a VPS using a nginx reverse proxy. When I was using my linux user everything was working but when I added GitHub authentificator configuration I got error 500. The github user was added to the server.

Below the server output:

     (jupyterhub-tutorial) marlene@vps451721:/srv/jupyterhub/jupyterhub-pydata-2016$ jupyterhub troubleshooting
     [W 2018-11-04 22:14:20.101 JupyterHub app:441] JupyterHub.proxy_cmd is deprecated in JupyterHub 0.8, use ConfigurableHTTPProxy.command
    [I 2018-11-04 22:14:20.106 JupyterHub app:1673] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.8.0
    [I 2018-11-04 22:14:20.107 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
    [I 2018-11-04 22:14:20.109 JupyterHub app:1016] Loading cookie_secret from /srv/jupyterhub/jupyterhub-pydata-2016/jupyterhub_cookie_secret
    [I 2018-11-04 22:14:20.138 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
    [I 2018-11-04 22:14:20.213 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
    [W 2018-11-04 22:14:20.215 JupyterHub proxy:565] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
    [I 2018-11-04 22:14:20.215 JupyterHub proxy:567] Starting proxy @ http://my_IP_here:8000/
    22:14:20.796 [ConfigProxy] info: Proxying http://my_IP_here:8000 to (no default)
    22:14:20.800 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
    [I 2018-11-04 22:14:21.242 JupyterHub proxy:301] Checking routes
    [I 2018-11-04 22:14:21.244 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
    22:14:21.243 [ConfigProxy] info: 200 GET /api/routes 
    22:14:21.250 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
    22:14:21.251 [ConfigProxy] info: 201 POST /api/routes/ 
    [I 2018-11-04 22:14:21.253 JupyterHub app:1912] JupyterHub is now running at http://my_IP_here:8000/
    [E 2018-11-04 22:14:32.907 JupyterHub web:1670] Uncaught exception GET /hub/login (109...)
        HTTPServerRequest(protocol='http', host='mysite.com', method='GET', uri='/hub/login', version='HTTP/1.1', remote_ip='109...')
        Traceback (most recent call last):
          File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(value)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 72, in get
        self.finish(self._render(username=username))
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 41, in _render
        {'next': self.get_argument('next', '')},
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 813, in render_template
        template = self.get_template(name)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 807, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/loaders.py", line 408, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: login.html
    
    [E 2018-11-04 22:14:32.915 JupyterHub web:1114] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/tornado/web.py", line 1112, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 886, in write_error
        html = self.render_template('error.html', **ns)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 813, in render_template
        template = self.get_template(name)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 807, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/marlene/anaconda3/envs/jupyterhub-tutorial/lib/python3.5/site-packages/jinja2/loaders.py", line 408, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: error.html
    
    [E 2018-11-04 22:14:32.921 JupyterHub log:150] {
      "Connection": "close",
      "X-Forwarded-Host": "mysite.com",
      "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6",
      "X-Forwarded-Port": "80",
      "X-Real-Ip": "109...",
      "Cache-Control": "max-age=0",
      "X-Nginx-Proxy": "true",
      "X-Forwarded-For": "109...,107...",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-Proto": "http",
      "Host": "mysite.com",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
      "Cookie": "_xsrf=2|951a2e0b|8dc9845e26735dd298b3e2b7accbc0a6|1541024139",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate, br"
    }
    [E 2018-11-04 22:14:32.922 JupyterHub log:158] 500 GET /hub/login (@109...) 15.69ms

Here my jupyterhub_config.py. 

    from oauthenticator.github import GitHubOAuthenticator
    c.JupyterHub.authenticator_class = GitHubOAuthenticator

    c.GitHubOAuthenticator.oauth_callback_url = 'https://mysite.comt/hub/oauth_callback'
    c.GitHubOAuthenticator.client_id = 'my_client_id'
    c.GitHubOAuthenticator.client_secret = 'my_client_secret'

    c.JupyterHub.data_files_path = '/home/marlene/anaconda3/envs/jupyterhub-tutorial'
    c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub-pydata-2016/jupyterhub_cookie_secret'
    c.JupyterHub.db_url = '/srv/jupyterhub/jupyterhub-pydata-2016/jupyterhub.sqlite'
    c.JupyterHub.confirm_no_ssl = True
    c.Authenticator.admin_users = {'marlene, msmarchena'}
    c.Authenticator.whitelist = {'msmarchena'}
    c.LocalAuthenticator.create_system_users = True
    c.JupyterHub.data_files_path = '/home/marlene/anaconda3/envs/jupyterhub-tutorial/share/jupyter/hub'
    c.JupyterHub.proxy_cmd = ['/home/marlene/anaconda3/envs/jupyterhub-tutorial/bin/configurable-http-proxy']
    c.Spawner.cmd = ['jupyterhub-singleuser']
    c.Spawner.notebook_dir = '/home/marlene/notebooks'
    c.JupyterHub.base_url = '/'

nginx.conf is

    user www-data;
    worker_processes 4;
    pid /run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {

            include /etc/nginx/mime.types;
            default_type application/octet-stream;

        server {
            listen 80;
            server_name mysite.com;
            rewrite        ^ https://$host$request_uri? permanent;
        }

        server {
            listen 443;
            client_max_body_size 50M;

            server_name mysite.com;

            ssl on;
            ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem;

            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_prefer_server_ciphers on;
            ssl_dhparam /etc/ssl/certs/dhparam.pem;
            ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_stapling on;
            ssl_stapling_verify on;
            add_header Strict-Transport-Security max-age=15768000;

            # Expose logs to "docker logs".
            # See https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile#L12-L14
            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;

            #location ~ /(user-[a-zA-Z0-9]*)/static(.*) {
            #    alias /usr/local/lib/python3.4/dist-packages/notebook/static/$2;
           #}

             location / {
                proxy_pass http://127.0.0.1:8000;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_set_header X-NginX-Proxy true;
            }

            location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
                proxy_pass http://127.0.0.1:8000;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_set_header X-NginX-Proxy true;

                # WebSocket support
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 86400;
                proxy_set_header Origin "";
            }
        }

    }

I do not understand where the problem come from. Any idea will be much appreciate.

**Comment by msmarchena** [comment]
I think my configuration is wrong. I'm going to close this issue because I need to rethink a new one.

Thanks for your great job !
