### ISSUE TITLE
Unable to install jupyterhub in oracle

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/jupyterhub#2324]
I am trying to install jupyterhub with oracle as backend. But I am getting the following error.

```
[W 2018-11-22 08:46:09.730 JupyterHub app:882] 
    extra_log_file is DEPRECATED in jupyterhub-0.8.2.
    
    extra_log_file only redirects logs of the Hub itself,
    and will discard any other output, such as
    that of subprocess spawners or the proxy.
    
    It is STRONGLY recommended that you redirect process
    output instead, e.g.
    
        jupyterhub &>> '/logs/jupyter-hub.log'
    
[I 2018-11-22 08:46:09.730 JupyterHub app:1673] Using Authenticator: notebooks_spawner.authenticator.AppleConnectAuthenticator
[I 2018-11-22 08:46:09.730 JupyterHub app:1673] Using Spawner: notebooks_spawner.NotebooksSpawner
[I 2018-11-22 08:46:09.731 JupyterHub app:1055] Writing cookie_secret to /app/jupyterhub_cookie_secret
[E 2018-11-22 08:46:13.010 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyterhub/app.py", line 1680, in initialize
        self.init_db()
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyterhub/app.py", line 1080, in init_db
        **self.db_kwargs
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyterhub/orm.py", line 746, in new_session_factory
        Base.metadata.create_all(engine)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
        tables=tables)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
        conn._run_visitor(visitorcallable, element, **kwargs)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
        **kwargs).traverse_single(element)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
        return meth(obj, **kw)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
        _is_metadata_operation=True)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
        return meth(obj, **kw)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
        include_foreign_key_constraints=include_foreign_key_constraints
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
        return meth(self, multiparams, params)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
        return connection._execute_ddl(self, multiparams, params)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
        compiled
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
        context)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
        exc_info
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
        raise value.with_traceback(tb)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
        context)
      File "/home/gbi-datalab/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00902: invalid datatype [SQL: '\nCREATE TABLE users (\n\tid INTEGER NOT NULL, \n\tname NVARCHAR2(255), \n\tadmin SMALLINT, \n\tcreated DATE, \n\tlast_activity DATE, \n\tcookie_id NVARCHAR2(255) NOT NULL, \n\tstate TEXT, \n\tencrypted_auth_state BLOB, \n\tPRIMARY KEY (id), \n\tUNIQUE (name), \n\tCHECK (admin IN (0, 1)), \n\tUNIQUE (cookie_id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by minrk** [comment]
hm, I can't tell which data type is the one oracle doesn't like. Any ideas?

Can you share your jupyterhub_config (minus any credentials, private info)? I've never used oracle db.

**Comment by akhilputhiry** [comment]
@minrk here you go...

```
#! -*- Coding: utf-8 -*-
    from traitlets.config import get_config

    c = get_config()

    # proxy
    c.ConfigurableHTTPProxy.should_start = False
    c.ConfigurableHTTPProxy.api_url = "http://proxy:8001"
    c.ConfigurableHTTPProxy.auth_token = "78a6f67cad1c4ee7a48132e311eb4f74"

    # hub
    c.JupyterHub.hub_ip = "0.0.0.0"
    c.JupyterHub.base_url = "/notebooks/proxy/"
    c.JupyterHub.hub_connect_ip = "192.168.161.1"
    c.JupyterHub.spawner_class = "notebooks_spawner.NotebooksSpawner"
    c.JupyterHub.authenticator_class = "notebooks_spawner.Authenticator"
    c.JupyterHub.cleanup_servers = True
    c.JupyterHub.redirect_to_server = False
    c.JupyterHub.allow_named_servers = True
    c.JupyterHub.services = [
        {
            "admin": True,
            "name": "notebooks-backend",
            "api_token": "78a6f67cad1c4ee7a48132e311eb4f74",
        }
    ]
    c.JupyterHub.db_url = ""oracle+cx_oracle://system:oracle@localhost:1521/xe""
    c.JupyterHub.db_kwargs = {"pool_recycle": 300}
    c.JupyterHub.extra_log_file = "/logs/jupyter-hub.log"

    # spawner
    c.Spawner.start_timeout = 300
    c.Spawner.poll_interval = 1
    c.Spawner.working_dir = "/notebooks"
    c.Spawner.service_account = "jupyter-hub"
    c.Spawner.git_server = "github.com"
    c.Spawner.git_username = "akhil"
    c.Spawner.git_namespace = "akhil"
    c.Spawner.git_access_token = "adsdasdasdsadasdasd"
```

**Comment by akhilputhiry** [comment]
@minrk It looks like a problem with `sqlalchemy` Oracle do not have a data type called `TEXT` but if we look in to the query being generated by the alembic migration we can see the field `state` is of type `TEXT` which is creating the problem.

Ref - https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT213

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
