### ISSUE TITLE
Configuring JupyterHub behind corporate firewall. Issue with white listed users.  Server throwing 500 errors.

### ISSUE THREAD

**Issue by YborBorn** [jupyterhub/jupyterhub#2328]
Hello. Similar to deisi ([https://github.com/jupyterhub/jupyterhub/issues/1122]), I'm inside a corporate firewall. I have a server box running Ubuntu 16.04LTS, Anaconda3, iPython, and JupyterHub version 0.9.4. I've configured my JupyterHub config file as (and please forgive my Philistine formatting... I'm trying to debug this so all my settings are at the top of my config and I've anonymized some of the sensitive paths and user names):

import os
import pprint
pprint.pprint(dict(os.environ))

c.JupyterHub.ip = '166.17.125.77'
c.JupyterHub.port = 8000
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8001
c.JupyterHub.hub_bind_url = 'http://127.0.0.1:8081'
c.JupyterHub.allow_named_servers = True
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret' 
c.JupyterHub.ssl_cert = '/home/admin/pki/certs/newKey.csr' 
c.JupyterHub.ssl_key = '/home/admin/pki/certs/newKey.key'
c.ConfigurableHTTPProxy.auth_token = (a really long string here)
c.ConfigurablHTTPProxy.should_start = False
c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'admin', 'user', 'user3', 'user4'}
c.Authenticator.admin_users = {'admin'}
c.Spawner.ip = '127.0.0.1'
c.Spawner.cmd = ['/home/admin/anaconda3/bin/jupyterhub-singleuser']
c.PAMAuthenticator.check_account = True
c.PAMAuthenticator.encoding = 'utf8'
c.PAMAuthenticator.open_sessions = True
c.PAMAuthenticator.service = 'login'

I'm launching the hub with:
/home/admin/anaconda3/bin/jupyterhub -f /etc/jupyter/jupyterhub_config.py

I can log in and just fine but when go to the Admin screen and try to start the white listed users servers, I get:  API request failed (500) error. 

Here's the error I'm seeing in the terminal when I try to spawn a new white listed user
[I 2018-11-26 16:50:58.574 JupyterHub spawner:1100] Spawning /home/admin/anaconda3/bin/jupyterhub-singleuser '--ip="127.0.0.1"' --port=34741
[E 2018-11-26 16:50:58.578 JupyterHub user:477] Unhandled error starting user2's server: Exception occurred in preexec_fn.
[E 2018-11-26 16:50:58.600 JupyterHub web:1670] Uncaught exception POST /hub/api/users/user2/server (127.0.0.1)
    HTTPServerRequest(protocol='http', host='166.17.125.77:8000', method='POST', uri='/hub/api/users/user2/server', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/admin/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/apihandlers/users.py", line 373, in post
        await self.spawn_single_user(user, server_name, options=options)
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/home/admin/anaconda3/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1110, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/home/admin/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/admin/anaconda3/lib/python3.6/subprocess.py", line 1345, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
    
[E 2018-11-26 16:50:58.601 JupyterHub log:150] {
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1543268420|20:jupyterhub-hub-login|44:YmI2NTljOTIwNjk2NGU1N2FmNWY1ZGQzMDQ1Mzg5ZGI=|721769b5ec74a0dfc980a4d2757e6ddddae775414ef60bb7bd6dd43c9045e4a6\"; jupyterhub-session-id=07e714a8ad99447c9d64532bb0ef71d4; _xsrf=2|e3da26ae|c0f01a76dfce25b4490d3e838f61df69|1542988691",
      "Cache-Control": "no-cache",
      "Connection": "close",
      "Dnt": "1",
      "Content-Length": "0",
      "Host": "166.17.125.77:8000",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US",
      "Referer": "https://166.17.125.77:8000/hub/admin",
      "X-Requested-With": "XMLHttpRequest",
      "Accept": "*/*",
      "Content-Type": "application/json"
    }

Thanks.

**Comment by YborBorn** [comment]
I installed systemdspawner.SystemdSpawner and this has seemed to have solved my problem. I can now control individual users, thought it's still complicated. :)
