### ISSUE TITLE
Error listen EADDRINUSE :::443

### ISSUE THREAD

**Issue by shipengcheng1230** [jupyterhub/jupyterhub#2362]
Hello, I followd those essential steps for deploying based on the document but have been frustrated to solve this problem. I am using the latest jupyterhub installed from conda. I have a domain at https://discover.gso.uri.edu/ with a proper ssl keys/certs. The computer runs a Red Hat 7, httpd-2.4.6-88.el7.x86_64. When I use the minimum settings to start my jupyterhub, it pops the the `EADDRINUSE :::443` error but somehow the hub is able to run. But I cannot access the hub page remotely, by appending the port `:8081`. (I am not near the computer right now so that I cannot test the localhost).

I googled around but couldn't find a similar situation (those results are kind of obsolete). I know the error message tells me that the port is in use but I see everywhere else people use this setting. Could anyone help me solve this? Thank you in advance!

```shell
[root@discover]/srv/jupyterhub# jupyterhub --port=443 --ssl-key /etc/ssl/private/discover.gso.uri.edu.key --ssl-cert /etc/ssl/certs/discover.gso.uri.edu.pem 
[I 2018-12-14 22:44:22.536 JupyterHub app:1673] Using Authenticator: jupyterhub.auth.PAMAuthenticator-0.9.4
[I 2018-12-14 22:44:22.536 JupyterHub app:1673] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-0.9.4
[I 2018-12-14 22:44:22.537 JupyterHub app:1055] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-12-14 22:44:22.550 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2018-12-14 22:44:22.550 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2018-12-14 22:44:22.619 alembic.runtime.migration migration:327] Running stamp_revision  -> 896818069c98
[I 2018-12-14 22:44:22.694 JupyterHub proxy:431] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-12-14 22:44:22.696 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2018-12-14 22:44:22.696 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-12-14 22:44:22.696 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
[I 2018-12-14 22:44:22.731 JupyterHub app:1855] Hub API listening on http://127.0.0.1:8081/hub/
[I 2018-12-14 22:44:22.732 JupyterHub proxy:567] Starting proxy @ http://:443/
22:44:23.053 - info: [ConfigProxy] Proxying https://*:443 to (no default)
22:44:23.054 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
22:44:23.055 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE :::443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/opt/anaconda3/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:250:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
22:44:23.204 - info: [ConfigProxy] 200 GET /api/routes 
[I 2018-12-14 22:44:23.204 JupyterHub proxy:301] Checking routes
[I 2018-12-14 22:44:23.205 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
22:44:23.207 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
22:44:23.208 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-12-14 22:44:23.209 JupyterHub app:1912] JupyterHub is now running at http://:443/

```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
