### ISSUE TITLE
How To Run Jupyterhub on HTTPS?

### ISSUE THREAD

**Issue by palashSharma17** [jupyterhub/jupyterhub#2400]
Hi I have installed jupyterhub on my machine and i have configured certificate and key path in jupyterhub_config.py file but i am getting the following error.

```
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:775:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:47:10)
    at new ConfigurableProxy (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:222:32)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:296:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
[C 2019-01-30 16:39:49.697 JupyterHub app:1867] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/app.py", line 1865, in start
        await self.proxy.start()
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/proxy.py", line 594, in start
        _check_process()
      File "/usr/local/lib/python3.5/site-packages/jupyterhub/proxy.py", line 590, in _check_process
        raise e from None
    RuntimeError: Proxy failed to start with exit code 1
```

Kindly Revert ASAP.

**Comment by minrk** [comment]
What version of nodejs and configurable-http-proxy do you have? Have you set a passphrase on your ssl key?

**Comment by palashSharma17** [comment]
Sorry for replying late. I have configured the passphrase and now it works for me.

Thanks

**Comment by vasu0494** [comment]
Hello palashSharma17,
I'm trying to run configurbable-http-prxy with ssl cert anfd key. when i'm starting the proxy I'm facing this error. How Can i supply password.  
Error: error:0906A068:PEM routines:PEM_do_header:bad password read
   at Object.createSecureContext (_tls_common.js:144:17)
   at Server (_tls_wrap.js:868:27)
   at new Server (https.js:62:14)
   at Object.createServer (https.js:84:10)
   at new ConfigurableProxy (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:222:32)
   at Object.<anonymous> (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:300:13)
   at Module._compile (internal/modules/cjs/loader.js:689:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
   at Module.load (internal/modules/cjs/loader.js:599:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
