### ISSUE TITLE
[Permission denied][500 : Internal Server Error]

### ISSUE THREAD

**Issue by JaobsenYc** [jupyterhub/jupyterhub#2442]
Hi guys,
I tried to install **jupyterhub with pyenv and anaconda** on two servers, they both don't work and have the same issue.
I login Jupyterhub with local users, and it shows 

```
500 : Internal Server Error
Failed to start your server on the last attempt. Please contact admin if the issue persists.
```

Servers' sides (jaobsenyc is my Jupyterhub' admin user)

```
[E 2019-02-28 00:30:17.401 JupyterHub spawner:1115] Permission denied trying to run '/root/.pyenv/versions/anaconda3-2018.12/bin/jupyterhub-singleuser'. Does jaobsenychave access to this file?
[E 2019-02-28 00:30:17.402 JupyterHub user:477] Unhandled error starting jaobsenyc's server: [Errno 13] Permission denied: 'jupyterhub-singleuser'
[E 2019-02-28 00:30:17.451 JupyterHub web:1670] Uncaught exception GET /hub/user/jaobsenyc/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='webpy.jaobsen.com', method='GET', uri='/hub/user/jaobsenyc/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/site-packages/jupyterhub/spawner.py", line 1110, in start
        self.proc = Popen(cmd, **popen_kwargs)
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "/root/.pyenv/versions/anaconda3-2018.12/lib/python3.7/subprocess.py", line 1516, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: 'jupyterhub-singleuser'
```

I know it's a permission error, but i can't figure out the reason.
I've alreay changed "/root/.pyenv/versions/anaconda3-2018.12/" to 777 permission.

## Please help me!

**Comment by minrk** [comment]
Do all users have read and execute permissions to all parent directories of the env? e.g. can you do:

    sudo -u jaobsenychave ls -l /root/.pyenv/versions/anaconda3-2018.12/bin/

For JupyterHub, normally the Hub env is in some shared location such as `/opt/jupyterhub` rather than root's home directory which is usually private.

**Comment by JaobsenYc** [comment]
Actually, I've changed the permissions to 777, so every user could access that folder.
**This problem is solved by reinstalling pyenv and anaconda in a share location, like you said "/opt/pyenv"**. It now works for me.
Thanks anyway.
