### ISSUE TITLE
Tornado 6.0 and JupyterHub issue

### ISSUE THREAD

**Issue by huseinzol05** [jupyterhub/jupyterhub#2448]
I want to deploy Github authentication behind Nginx,

This is my jupyterhub config,
```python
from oauthenticator.github import GitHubOAuthenticator

c.JupyterHub.allow_named_servers = True
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.GitHubOAuthenticator.oauth_callback_url = (
    'https://jupyterhub.dev.bitcurate.com/hub/oauth_callback'
)
c.GitHubOAuthenticator.client_id = '354163794ed454598dd2'
c.GitHubOAuthenticator.client_secret = (
    '6351525872a75567a6c6ed45356b254a7802edbd'
)
c.LocalAuthenticator.create_system_users = True
```

And this is my nginx conf,
```text
server {
	server_name jupyterhub.example.com;

  location / {
		proxy_pass http://jupyterhub:8000;
		proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
	location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
            proxy_pass http://jupyterhub:8000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-NginX-Proxy true;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;

        }

    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

server {
    if ($host = jupyterhub.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    	listen 80;
    	server_name jupyterhub.example.com;
    return 404; # managed by Certbot


}
```

When I authenticated my github account,
```text
[E 2019-03-02 14:17:41.714 JupyterHub web:1788] Uncaught exception GET /hub/oauth_callback?code=98fb6895817a1078ebd6&state=eyJzdGF0ZV9pZCI6ICJlM2Y1OWQ1YTI3Yjg0ODFhYTZkNDI2MzBmZTQ3Yjg0ZSIsICJuZXh0X3VybCI6ICIifQ%3D%3D (42.191.185.51)

    HTTPServerRequest(protocol='http', host='jupyterhub.dev.bitcurate.com', method='GET', uri='/hub/oauth_callback?code=98fb6895817a1078ebd6&state=eyJzdGF0ZV9pZCI6ICJlM2Y1OWQ1YTI3Yjg0ODFhYTZkNDI2MzBmZTQ3Yjg0ZSIsICJuZXh0X3VybCI6ICIifQ%3D%3D', version='HTTP/1.1', remote_ip='42.191.185.51')

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 191, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 116, in authenticate
        resp = yield http_client.fetch(req)
    tornado.simple_httpclient.HTTPStreamClosedError: Stream closed

[E 2019-03-02 14:17:41.716 JupyterHub log:150] {
      "X-Forwarded-Host": "jupyterhub.example.com",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80",
      "Cookie": "_ga=GA1.2.1046683617.1549628873; _gid=GA1.2.1632910557.1551529980; _gat=1; oauthenticator-state=\"2|1:0|10:1551536260|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSmxNMlkxT1dRMVlUSTNZamcwT0RGaFlUWmtOREkyTXpCbVpUUTNZamcwWlNJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|49068ce687962d0354ae793824f49e843d4e826c2911fd6580c2288fd55e23e5\"",
      "Accept-Language": "en-MY,en;q=0.9,en-US;q=0.8,ms;q=0.7",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://jupyterhub.example.com/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "X-Forwarded-For": "42.191.185.51,::ffff:172.18.0.4",
      "Host": "jupyterhub.example.com",
      "X-Real-Ip": "42.191.185.51"
    }


[E 2019-03-02 14:17:41.716 JupyterHub log:158] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@42.191.185.51) 325.77ms
14:18:52.369 [ConfigProxy] info: 200 GET /api/routes 
[I 2019-03-02 14:18:52.369 JupyterHub proxy:301] Checking routes
```

Anyone can help me sort this out?

**Comment by huseinzol05** [comment]
I will try to downgrade Tornado from version 6 to version 5.1

**Comment by huseinzol05** [comment]
Yep, fixed when,
```bash
pip3 install tornado==5.1.1
```

Jupyter seems broken on Tornado 6.0

**Comment by oberstet** [comment]
@huseinzol05 the current requirements do not follow this restriction:

https://github.com/jupyterhub/jupyterhub/blob/master/requirements.txt#L12

I lost several hours trying to track down the issue before I found your comment.

So IMO this issue should be reopened and `requirments.txt` changed to `tornado==5.1.1`

**Comment by GeorgianaElena** [comment]
Similar issue reported in https://github.com/tornadoweb/tornado/issues/2651#issuecomment-497261092 and https://github.com/tornadoweb/tornado/issues/2651#issuecomment-515687031.

Seems like downgrading from from Tornado v6.x to v5.1.1 temporarily fixes this. @minrk, what do you think?

**Comment by minrk** [comment]
This is a bug in tornado and not an issue in jupyterhub, but oauthenticator 0.9.0 fixes it by adopting asyncio coroutines (https://github.com/jupyterhub/oauthenticator/pull/275). I think this can be closed.

**Comment by kuan51** [comment]
I am using jupyterhub with oauthenticator 0.9.0 but am still having this issue. It was fixed by downgrading Tornado to 5.1.1. 

Here are relevant parts from my jupyterhub_config.py:
```from oauthenticator.github import LocalGitHubOAuthenticator
c.JupyterHub.authenticator_class = LocalGitHubOAuthenticator
c.LocalGitHubOAuthenticator.create_system_users = True
c.GitHubOAuthenticator.oauth_callback_url = 'https://[redacted_fqdn]/jupyter/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '[redacted]'
c.GitHubOAuthenticator.client_secret = '[redacted]'
c.JupyterHub.base_url = '/jupyter'
```

And then running jupyterhub with --debug:
```[I 2019-08-08 19:43:04.837 JupyterHub app:2422] JupyterHub is now running at https://:8000/jupyter/
19:43:04.838 [ConfigProxy] info: 201 POST /api/routes/jupyter
[I 2019-08-08 19:43:08.715 JupyterHub log:174] 200 GET /jupyter/hub/login (@[redacted_ip]) 61.90ms
[D 2019-08-08 19:48:04.838 JupyterHub proxy:765] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
19:48:04.842 [ConfigProxy] info: 200 GET /api/routes
[I 2019-08-08 19:48:04.843 JupyterHub proxy:319] Checking routes
[I 2019-08-08 19:48:29.970 JupyterHub oauth2:100] OAuth redirect: 'https://[redacted_fqdn]/jupyter/hub/oauth_callback'
[I 2019-08-08 19:48:29.973 JupyterHub log:174] 302 GET /jupyter/hub/oauth_login?next= -> https://github.com/login/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2F[redacted_fqdn]%2Fjupyter%2Fhub%2Foauth_callback&client_id=e58273c61ecbebb85838&state=[secret] (@[redacted_ip]) 3.67ms
[E 2019-08-08 19:48:30.715 JupyterHub web:1788] Uncaught exception GET /jupyter/hub/oauth_callback?code=[redacted]&state=[redacted] ([redacted_ip])
    HTTPServerRequest(protocol='https', host='[redacted_fqdn]', method='GET', uri='/jupyter/hub/oauth_callback?code=[redacted]&state=[redacted]', version='HTTP/1.1', remote_ip='[redacted_ip]')
    Traceback (most recent call last):
      File "/opt/jupyterhub/jvenv/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/jupyterhub/jvenv/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 207, in get
        user = await self.login_user()
      File "/opt/jupyterhub/jvenv/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 655, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/jupyterhub/jvenv/lib/python3.6/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/jupyterhub/jvenv/lib/python3.6/site-packages/oauthenticator/github.py", line 115, in authenticate
        resp = await http_client.fetch(req)
    tornado.simple_httpclient.HTTPStreamClosedError: Stream closed

[D 2019-08-08 19:48:30.720 JupyterHub base:1110] No template for 500
[E 2019-08-08 19:48:30.734 JupyterHub log:166] {
      "X-Forwarded-Host": "[redacted_fqdn]",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "443",
      "Cookie": "oauthenticator-state=[secret]",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://[redacted_fqdn]/jupyter/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.145 Safari/537.36 Vivaldi/2.6.1566.49",
      "Dnt": "1",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "X-Forwarded-For": "[redacted_ip]",
      "X-Real-Ip": "[redacted_ip]",
      "Host": "[redacted_fqdn]"
    }
[E 2019-08-08 19:48:30.736 JupyterHub log:174] 500 GET /jupyter/hub/oauth_callback?code=[secret]&state=[secret] (@[redacted_ip]) 236.26ms
```

pip show jupyterhub
```Name: jupyterhub
Version: 1.0.0
Summary: JupyterHub: A multi-user server for Jupyter notebooks
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /opt/jupyterhub/jvenv/lib/python3.6/site-packages
Requires: certipy, entrypoints, oauthlib, pamela, traitlets, prometheus-client, jinja2, SQLAlchemy, requests, python-dateutil, tornado, alembic, async-generator
```

pip show tornado
```Name: tornado
Version: 6.0.3
Summary: Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
Home-page: http://www.tornadoweb.org/
Author: Facebook
Author-email: python-tornado@googlegroups.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /opt/jupyterhub/jvenv/lib/python3.6/site-packages
Requires:
```

nginx config
```server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
    return 301 https://$host$request_uri;

}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # General Server Configs
    server_name [redacted_fqdn];
    #root /var/www/html;
    #index index.html index.htm index.nginx-debian.html;

    # Location statements
    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    location /jupyter {
        proxy_pass https://127.0.0.1:8000;
        proxy_set_header Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
    }

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_certificate /etc/ssl/[redacted_fqdn]/bundle.crt;
    ssl_certificate_key /etc/ssl/[redacted_fqdn]/private.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # modern configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;
}
```

**Comment by mokumar1202** [comment]
Hi All,

I have completed setting up Anaconda distribution, installed JupyterHub but when i login to the Hub, i get Spawn failed: Server at http://127.0.0.1:35990/user// didn't respond in 30 seconds.

I have tried many suggestions but nothing seems to fix it. I have also tried downgrading Tornado version to 4.5.3 but it failed as there were too many dependencies associated.

Please could someone help.

Just FYI, i have also reinstalled Anaconda, configured Proxy, generated jupyterhub_config.py.

**Comment by betatim** [comment]
Using `master` of oauthenticator and almost master of JupyterHub I ran into this problem as well.

I noticed that I didn't have pycurl installed (check the JupyterHub log output for a note that it won't use pycurl). I used `conda install -c conda-forge pycurl` to install pycurl after which I didn't have any problems any more.

**Comment by mokumar1202** [comment]
Hi Betatim/All, Apologies for the late reply. This seemed to work out of blue when i gave read and execute permissions for the users and was alright for the few days. But today when i started my jupyter server, the same issue is back again. 

tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for kumarm85 may contain details.)
[W 2020-03-12 11:05:35.376 JupyterHub user:692] kumarm85's server never showed up at http://127.0.0.1:40471/user/kumarm85/ after 30 seconds. Giving up
[E 2020-03-12 11:05:35.490 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /data/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError("Server at http://127.0.0.1:40471/user/kumarm85/ didn't respond in 30 seconds")> after timeout

I have also downgraded Tornado to 5.1.1 but no luck.

**Comment by mokumar1202** [comment]
Update:

I have also installed oauthenticator==0.9.0 and pycurl as well but still not able to spawn server.
