### ISSUE TITLE
Scala kernel not working - time out? not able to generate a kernel

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2454]
Here is my detailed steps of installing a Scala kernel through Toree:

```
# conda install toree -c akode (also tried channel: GlaxoSmithKline, same result)
# jupyter toree install --spark_home=/opt/cloudera/parcels/SPARK2/lib/spark2 --interpreters=Scala
```

Kernel is below:
```
cat /usr/local/share/jupyter/kernels/apache_toree_scala/kernel.json
{
  "argv": [
    "/usr/local/share/jupyter/kernels/apache_toree_scala/bin/run.sh",
    "--profile",
    "{connection_file}"
  ],
  "env": {
    "DEFAULT_INTERPRETER": "Scala",
    "__TOREE_SPARK_OPTS__": "",
    "__TOREE_OPTS__": "",
    "SPARK_HOME": "/opt/cloudera/parcels/SPARK2/lib/spark2",
    "PYTHONPATH": "/opt/cloudera/parcels/SPARK2/lib/spark2/python:/opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/py4j-0.10.7-src.zip",
    "PYTHON_EXEC": "python"
  },
  "display_name": "Apache Toree - Scala",
  "language": "scala"
}
```

When I start a new notebook of Scala kernel, I see output in log:
```
Mar 06 15:54:13 cedgedev02 jupyterhub[19954]: Starting Spark Kernel with SPARK_HOME=/opt/cloudera/parcels/SPARK2/lib/spark2
Mar 06 15:54:13 cedgedev02 jupyterhub[19954]: [I 2019-03-06 15:54:13.570 SingleUserNotebookApp kernelmanager:164] Kernel started: 016e9348-7c54-417e-841c-3f7ac7f9b623
Mar 06 15:54:13 cedgedev02 jupyterhub[19954]: [I 2019-03-06 15:54:13.572 SingleUserNotebookApp log:158] 201 POST /user/rxie/api/sessions (rxie@192.168.103.81) 26.69ms
Mar 06 15:54:13 cedgedev02 jupyterhub[19954]: [I 2019-03-06 15:54:13.577 SingleUserNotebookApp log:158] 200 GET /user/rxie/api/contents/Untitled37.ipynb/checkpoints?_=1551905653132 (rxie@192.168.103.81) 2.94ms
Mar 06 15:58:12 cedgedev02 jupyterhub[19954]: 15:58:12.934 - info: [ConfigProxy] 200 GET /api/routes


```
Just hanging here forever, no even timeout error.

I notice `/usr/local/share/jupyter/kernels/apache_toree_scala/bin/run.sh` in the argv option of the kernel, so just be a test I ran it directly from shell and here is the output:

```
# /usr/local/share/jupyter/kernels/apache_toree_scala/bin/run.sh
Starting Spark Kernel with SPARK_HOME=/opt/cloudera/parcels/SPARK2/lib/spark2
WARNING: User-defined SPARK_HOME (/opt/cloudera/parcels/SPARK2-2.3.0.cloudera3-1.cdh5.13.3.p0.458809/lib/spark2) overrides detected (/opt/cloudera/parcels/SPARK2/lib/spark2).
WARNING: Running spark-class from user-defined location.
19/03/06 16:08:01 WARN spark.SparkConf: The configuration key 'spark.yarn.executor.memoryOverhead' has been deprecated as of Spark 2.3 and may be removed in the future. Please use the new key 'spark.executor.memoryOverhead' instead.
19/03/06 16:08:02 INFO toree.Main$$anon$1: Kernel version: 0.1.0-incubating
19/03/06 16:08:02 INFO toree.Main$$anon$1: Scala version: Some(2.10.4)
19/03/06 16:08:02 INFO toree.Main$$anon$1: ZeroMQ (JeroMQ) version: 3.2.5
19/03/06 16:08:02 INFO toree.Main$$anon$1: Initializing internal actor system
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.HashSet$.empty()Lscala/collection/immutable/HashSet;
        at akka.actor.ActorCell$.<init>(ActorCell.scala:336)
        at akka.actor.ActorCell$.<clinit>(ActorCell.scala)
        at akka.actor.RootActorPath.$div(ActorPath.scala:185)
        at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:465)
        at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:453)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
        at scala.util.Try$.apply(Try.scala:192)
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
        at scala.util.Success.flatMap(Try.scala:231)
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
        at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:585)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:578)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
        at org.apache.toree.boot.layer.StandardBareInitialization$class.createActorSystem(BareInitialization.scala:71)
        at org.apache.toree.Main$$anon$1.createActorSystem(Main.scala:34)
        at org.apache.toree.boot.layer.StandardBareInitialization$class.initializeBare(BareInitialization.scala:60)
        at org.apache.toree.Main$$anon$1.initializeBare(Main.scala:34)
        at org.apache.toree.boot.KernelBootstrap.initialize(KernelBootstrap.scala:70)
        at org.apache.toree.Main$delayedInit$body.apply(Main.scala:39)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.apache.toree.Main$.main(Main.scala:23)
        at org.apache.toree.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

From the error in the output I see **Scala version: Some(2.10.4)**, for a comparison, I ran spark2-shell, I see the following scala version info:

```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.0.cloudera3
      /_/
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121)
```
Seems to me there are two Scala versions here, with the failing one in Jupyter kernel is  Some(2.10.4) while the working one from shell is 2.11.8, I suspect this might be the culprit.

If yes, how could I specify the jupyter kernel's scala to be the same one as 2.11.8 which works? 

Thank you very much.

Any clue is appreciated.

P.S. 1: I also double checked the `SPARK_HOME` and `/usr/local/share/jupyter/kernels/apache_toree_scala/bin/run.sh`, I see at the end of run.sh:

eval exec "${SPARK_HOME}/bin/spark-submit" "${SPARK_OPTS}" --class org.apache.toree.Main "${TOREE_ASSEMBLY}" "${TOREE_OPTS}" "$@"

And if I run ${SPARK_HOME}/bin/spark-submit --version I see the same versioning info when running spark2-shell, which seems to tell me the Toree's run.sh is correct? where does it get messed up then?

**Comment by FK7** [comment]
@mdivk Did you fixed the issue? since I am getting the same error while creating notebook for PySpark 2.4.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
