### ISSUE TITLE
Redirection Error While Openning User Notebook - Too many redirections

### ISSUE THREAD

**Issue by mgnfcnt** [jupyterhub/jupyterhub#2463]
I am getting 500 internal server error while opening user's notebook but server is started

I have create 2 users and also their notebook directories also grant folder permissions. But nano of them is worked
```
# Configuration file for jupyterhub.

import os
from jupyterhub.spawner import LocalProcessSpawner
from jupyter_client.localinterfaces import public_ips

c = get_config()

data_dir = '/home/data'
source_dir = '/home/notebooks'

class MySpawner(LocalProcessSpawner):

    def start(self):

        # Local vars
        username = self.user.name
        home_dir = '/home/%s/notebooks' %username
        cases_dir = home_dir+'/cases'
        examples_dir = home_dir+'/examples'
        workspace_dir = home_dir+'/workspace'

        # Home
        os.system("mkdir -p %s" %home_dir)

        # Welcome
        os.system("cp %s/Welcome.ipynb %s" %(source_dir,home_dir))

        # Examples
        os.system("rm -rf %s" %examples_dir)
        os.system("cp -r %s/examples %s" %(source_dir,home_dir))

        # Cases
        os.system("rm -rf %s" %cases_dir)
        os.system("cp -r %s/cases %s" %(source_dir,home_dir))

        # Workspace
        os.system("mkdir -p %s" %workspace_dir)
        os.system("cp -r %s/workspace-%s/. %s" %(data_dir,username,workspace_dir))
        os.system("chown -R %s %s" %(username,workspace_dir))
        return super().start()

    def stop(self):

        # Local vars
        username = self.user.name
        home_dir = '/home/%s/notebooks' %username
        workspace_dir = home_dir+'/workspace'

        # Backup workspace
        os.system("rsync -avz --delete %s %s/workspace-%s" %(workspace_dir,data_dir,username))
        return super().stop()

c.Authenticator.admin_users = set([])

c.JupyterHub.ip = public_ips()[0]
c.JupyterHub.port = 443
c.JupyterHub.admin_access = True
c.JupyterHub.cookie_secret_file = data_dir+'jupyterhub_cookie_secret'
c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
c.JupyterHub.spawner_class = MySpawner
c.JupyterHub.hub_ip = public_ips()[0]
c.JupyterHub.hub_port = 1453

c.JupyterHub.services = [{'name': 'cull-idle',
                          'admin': True,
                          'command': 'python cull_idle_servers.py --timeout=3600'.split()}]
c.Spawner.debug = False
c.Spawner.notebook_dir = '/home/notebooks'
c.Spawner.args = ['--NotebookApp.default_url=%s/Welcome.ipynb' %source_dir]

c.LocalAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'mgnfcnt', 'testuser'}
c.Authenticator.admin_users = {'mgnfcnt'}


```

**Comment by mgnfcnt** [comment]
```
[E 2019-03-08 11:57:27.286 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py:619> exception=TimeoutError("Server at http://127.0.0.1:57975/user/ttcdes/ didn't respond in 30 seconds")> after timeout
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/user.py", line 528, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/user.py", line 502, in spawn
        resp = await server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 197, in wait_for_http_server
        timeout=timeout
      File "/opt/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:57975/user/mgnfcnt/ didn't respond in 30 seconds
```

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
