### ISSUE TITLE
 Failed to open PAM session for docker_admin: [PAM Error 14] Cannot make/remove an entry for the specified session

### ISSUE THREAD

**Issue by playermanny2** [jupyterhub/jupyterhub#2486]
Hi,

After running my jupyterhub instance with docker i'm getting a 

500 : Internal Server Error
Failed to start your server on the last attempt. Please contact admin if the issue persists.

When checking in the logs, the specific errors is(I've changed the name of my site because it isn't public)
```
 Failed to open PAM session for docker_admin: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-03-26 15:43:20.458 JupyterHub auth:643] Disabling PAM sessions from now on.
[D 2019-03-26 15:43:20.466 JupyterHub spawner:63] Spawning ['sudo', '-u', 'docker_admin', '-nH', '/opt/conda/bin/sudospawner']
root is not in the sudoers file.  This incident will be reported.
[E 2019-03-26 15:43:20.476 JupyterHub spawner:83] Failed to get JSON result from mediator: ''
[E 2019-03-26 15:43:20.477 JupyterHub user:477] Unhandled error starting docker_admin's server: substring not found
[D 2019-03-26 15:43:20.487 JupyterHub user:578] Deleting oauth client jupyterhub-user-docker_admin
[E 2019-03-26 15:43:20.500 JupyterHub web:1670] Uncaught exception GET /hub/user/docker_admin/ (::ffff:108.94.146.20)
    HTTPServerRequest(protocol='https', host='www.nameofmysite.com', method='GET', uri='/hub/user/docker_admin/', version='HTTP/1.1', remote_ip='::ffff:108.94.146.20')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 1052, in get
        await self.spawn_single_user(user)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 705, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/sudospawner/spawner.py", line 92, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/opt/conda/lib/python3.6/site-packages/sudospawner/spawner.py", line 80, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found

[D 2019-03-26 15:43:20.505 JupyterHub base:880] No template for 500
[E 2019-03-26 15:43:20.513 JupyterHub log:150] {
      "X-Forwarded-Host": "www.nameofmysite.com",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "443",
      "X-Forwarded-For": "::ffff:108.94.146.20",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1553614999|20:jupyterhub-hub-login|44:ZWJjMzQwZWEzM2I3NDc0NjhmNjlkOGMzMGUwM2NlZTY=|06d5ae904b5875cd1fd654718b2b66ae1675c5dab43d60571110989408d9bf67\"; _xsrf=2|e2038cf5|c5a21f7e2904636bc9025a8b1d853fbc|1553541029; jupyterhub-session-id=e95c37f064b04bd98a8ba05773533095",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://www.nameofmysite.com/hub/login",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Connection": "close",
```
This has only started occuring after using a SSL certificate, without using the ssl certificate it works fine.

My jupyterhub config looks like this:

```# Configuration file for jupyterhub.

c = get_config()

# use the sudo spawner
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'

c.SudoSpawner.sudospawner_path = '/opt/conda/bin/sudospawner'
c.SudoSpawner.mediator_log_level = 'DEBUG'
c.JupyterHub.log_level = 10
c.Spawner.environment = {'ORACLE_HOME': '/opt/oracle/instantclient_12_2', 'LD_LIBRARY_PATH': '/opt/oracle/instantclient_12_2', 'LD_RUN_PATH': '/opt/oracle/instantclient_12_2' }

# Set Jupyerlab as default url
c.Spawner.default_url = '/lab'

# Serve using standard SSL
c.JupyterHub.port = 443
c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--redirect-port', '80']

c.JupyterHub.ssl_key = '/home/docker_admin/certs/privkey.pem'
c.JupyterHub.ssl_cert = '/home/docker_admin/certs/fullchain.pem'
#c.Spawner.args = ['--debug']
```
I am running the instance with command
```
sudo docker run -it -p 443:443 jupyterhub-sudo
```
Any help or idea on why this is not working would be appreciated. I've already tried to to add the command  to fix it but it did not help.
<code>c.PAMAuthenticator.open_sessions = False
</code>

Thanks!

**Comment by playermanny2** [comment]
This should be solved by adding root to sudoers that can spin up the sudospawner. However now I'm getting a

 [ConfigProxy] Uncaught Exception Error: listen EACCES 0.0.0.0:443

**Comment by playermanny2** [comment]
[ConfigProxy] Uncaught Exception Error: listen EACCES 0.0.0.0:443

this is a port binding error for non root users.

fixed by sudo setcap 'cap_net_bind_service=+ep' `which node`

all of this is done inside the docker container via a Dockerfile

reference: https://github.com/jupyterhub/jupyterhub/issues/774
