### ISSUE TITLE
500 Internal Server Error caused by NoneType has no attribute 'active'

### ISSUE THREAD

**Issue by bmshouse** [jupyterhub/jupyterhub#2500]
**Describe the bug**
500 : Internal Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 971, in get
    if "api" in user_path.split("/") and not user.active: 
AttributeError: 'NoneType' object has no attribute 'active'

**To Reproduce**
On a fresh start the bug does not present. However, after running JupyterHub for a few hours...
1. Logout { https://server/logout }
2. Click the Login Link and authenticate

**Expected behavior**
After a successful login, users should be redirected to their container

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.13, Win 7, Win 10
 - Browser Firefox, Chrome, Brave (Latest)
 - Version 0.9.6 (Using Helm chart 8.2)

**Additional context**
We are using Google OAuth for authentication

**Comment by bmshouse** [comment]
It seems that a similar problem occurred in the past issue #2295

**Comment by bmshouse** [comment]
Rolled back to an earlier version and still getting this error. Must not have been the cause of the problem. Thanks anyway.
