### ISSUE TITLE
How to recognized othenticator module ?

### ISSUE THREAD

**Issue by minhwan3295** [jupyterhub/jupyterhub#2501]
I want to use othenticaror with github.

This is my docker file

FROM jupyterhub/jupyterhub:latest
RUN mkdir -p /srv/jupyterhub
RUN apt-get update
RUN apt-get install net-tools -y
RUN apt-get install vim -y
RUN apt-get install python3-pip -y
RUN useradd -m -d /srv/jupyterhub/namu namu
RUN echo 'namu:namutech' | chpasswd
RUN pip3 install notebook
RUN pip3 install jupyterlab
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install oauthenticator

I installed oauthenticator

I added below arguments.
1.
from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator

2.
from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'

But He couldn't find module called othenticator.
This is my error.

[E 2019-04-03 15:40:35.087 JupyterHub app:2458]
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 2455, in launch_instance_async
await self.initialize(argv)
File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 2077, in initialize
self.load_config_file(self.config_file)
File "", line 2, in load_config_file
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 598, in load_config_file
raise_config_file_errors=self.raise_config_file_errors,
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
config = loader.load_config()
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
self._read_file_as_dict()
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
py3compat.execfile(conf_filename, namespace)
File "/opt/conda/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
exec(compiler(f.read(), fname, 'exec'), glob, loc)
File "/srv/jupyterhub/jupyterhub_config.py", line 4, in 
from oauthenticator.github import GitHubOAuthenticator
ModuleNotFoundError: No module named 'oauthenticator'

**Comment by ryogesh** [comment]
Can you launch a bash shell on the running docker container (refer https://docs.docker.com/engine/reference/commandline/exec/ )
E.g. 
docker exec -i -t <containerID> /bin/bash

From bash, launch python3 and try to import

from oauthenticator.github import GitHubOAuthenticator

Check for any errors
