### ISSUE TITLE
Just can't get it to work

### ISSUE THREAD

**Issue by kevart** [jupyterhub/jupyterhub#2504]
Sorry for the inaccurate title, but there's just a few things that are too hard here. See my process/progress below.

According to the [Dockerfile](https://github.com/jupyterhub/jupyterhub/blob/master/Dockerfile) Option 1 is to provide a custom config file.

Here's my Dockerfile:

```
FROM jupyterhub/jupyterhub:latest
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
```

I have created `jupyterhub_config.py` beforehand and only added this line:

```
c.DummyAuthenticator.password = "some_password"
```

.. **didn't work.** [Documentation](-basics.html#use-dummyauthenticator-for-testing) needs to mention that:

```
c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
```

also needs to be enabled.

**Next issue:**

```
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/hub/spawn-pending/asdf', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/pages.py", line 290, in get
        raise copy.copy(exc).with_traceback(exc.__traceback__)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
        timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 633, in spawn
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 537, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1377, in start
        env = self.get_env()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1326, in get_env
        env = self.user_env(env)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1313, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: asdf'
```

Seems now I need to find out how to additionally add users .. pretty frustrating and time-consuming. I am just trying to run it _somehow_ to evaluate whether to go with jupyterhub or Zeppelin.

**Next iteration:** adding "root" as user and admin user (because that user exists inside docker).

I can log in and it starts - yeey, for a short moment until I see the following errors on the console:

```
pawning jupyterhub-singleuser --port=41085
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 24, in <module>
    import notebook
ModuleNotFoundError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 26, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
```

and additionally:

```
Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:800> exception=TimeoutError("Server at http://127.0.0.1:41085/user/root/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 645, in spawn
        await self._wait_up(spawner)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 692, in _wait_up
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 660, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:41085/user/root/ didn't respond in 30 seconds
```

**Seems I need to install `notebook`**. After doing so (with `RUN /opt/conda/bin/pip install notebook`), it is still not working:

```
[C 2019-04-04 05:20:58.234 SingleUserNotebookApp notebookapp:1769] Running as root is not recommended. Use --allow-root to bypass.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for root may contain details.)
```

**So I have to allow root with `--allow-root`?** Let's try that. Updated my Dockerfile to run

```
jupyterhub --allow-root -f ./jupyterhub_config.py
```

with the following outcome:

long list of -- flags followed by

```
[C 2019-04-04 05:23:35.915 JupyterHub application:90] Bad config encountered during initialization:
[C 2019-04-04 05:23:35.916 JupyterHub application:91] Unrecognized flag: '--allow-root'
```

giving up

**Comment by betatim** [comment]
Sorry you didn't have a good first experience.

For evaluation and "just have a look" I'd follow [these instructions](https://github.com/jupyterhub/jupyterhub#install-packages) instead of trying to setup a docker based hub. 

The key comment in https://github.com/jupyterhub/jupyterhub#docker is "In general, one needs to make a derivative image.". For me this means it is a more complex setup than the one above. You need to understand what authenticators and spawners are to be able to make a choice and know what their prerequisites are.

Maybe there is already a `jupyterhub-demo` docker image out there that has made some choices for you and "just works"?

**Comment by kevart** [comment]
Thanks for the reply @betatim. I actually got it to work by creating a non-user first in the end (but it took some time to get there).

I think it would really help if the docker image would come with a standard user. Just to provide an initial first, positive user experience.
