### ISSUE TITLE
Capitalization in returns from Authenticators is not respected

### ISSUE THREAD

**Issue by distortedsignal** [jupyterhub/jupyterhub#2515]
I believe that the capitalization of the username returned from the TestAuthenticator class is not being respected. I've recently installed JupyterHub on a (Centos7) server and am starting to write my own authenticators. I ran into this issue after setting up this environment.

Output of `pip freeze` before `pip install`ing the custom Authenticator class:
```
alembic==1.0.8
asn1crypto==0.24.0
async-generator==1.10
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
cryptography==2.6.1
decorator==4.4.0
defusedxml==0.5.0
eight==0.4.2
future==0.16.0
idna==2.8
ipython-genutils==0.2.0
Jinja2==2.10.1
jupyterhub==0.9.6
lxml==4.3.3
Mako==1.0.8
MarkupSafe==1.1.1
pamela==1.0.0
prometheus-client==0.6.0
pycparser==2.19
pyOpenSSL==18.0.0
python-dateutil==2.8.0
python-editor==1.0.4
python-oauth2==1.1.0
pytz==2019.1
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.2
tornado==6.0.2
traitlets==4.3.2
urllib3==1.24.1
virtualenv==15.1.0
```

Authenticator class:
```py
from jupyterhub.auth import Authenticator
from tornado import gen

class TestAuthenticator(Authenticator):
  @gen.coroutine
  def authenticate(self, handler, data):
    return 'Tom'
```

Minfied jupyterhub config file:
```py
# Configuration file for jupyterhub.

#------------------------------------------------------------------------------
# Application(SingletonConfigurable) configuration
#------------------------------------------------------------------------------

## This is an application.

## Set the log level by value or name.
c.Application.log_level = 'DEBUG'

#------------------------------------------------------------------------------
# JupyterHub(Application) configuration
#------------------------------------------------------------------------------

## An Application for starting a Multi-User Jupyter Notebook server.

## Class for authenticating users.
#
#  This should be a class with the following form:
#
#  - constructor takes one kwarg: `config`, the IPython config object.
#
#  with an authenticate method that:
#
#  - is a coroutine (asyncio or tornado)
#  - returns username on success, None on failure
#  - takes two arguments: (handler, data),
#    where `handler` is the calling web.RequestHandler,
#    and `data` is the POST form data from the login page.
c.JupyterHub.authenticator_class = 'mypackage.TestAuthenticator'

#------------------------------------------------------------------------------
# Spawner(LoggingConfigurable) configuration
#------------------------------------------------------------------------------

## Path to the notebook directory for the single-user server.
#
#  The user sees a file listing of this directory when the notebook interface is
#  started. The current interface does not easily allow browsing beyond the
#  subdirectories in this directory's tree.
#
#  `~` will be expanded to the home directory of the user, and {username} will be
#  replaced with the name of the user.
#
#  Note that this does *not* prevent users from accessing files outside of this
#  path! They can do so with many other means.
c.Spawner.notebook_dir = '/notebooks'
```

Log output:
```
[I 2019-04-11 12:40:48.684 JupyterHub base:509] User logged in: tom
[I 2019-04-11 12:40:48.685 JupyterHub log:158] 302 POST /hub/login?next= -> /user/tom/ (tom@::ffff:10.1.10.37) 71.62ms
[I 2019-04-11 12:40:48.708 JupyterHub log:158] 302 GET /user/tom/ -> /hub/user/tom/ (@::ffff:10.1.10.37) 1.27ms
[E 2019-04-11 12:40:48.787 JupyterHub base:1011] Preventing implicit spawn for tom because last spawn failed: 'getpwnam(): name not found: tom'
[E 2019-04-11 12:40:48.787 JupyterHub web:1788] Uncaught exception GET /hub/user/tom/ (::ffff:10.1.10.37)
    HTTPServerRequest(protocol='http', host='10.39.241.3:8000', method='GET', uri='/hub/user/tom/', version='HTTP/1.1', remote_ip='::ffff:10.1.10.37')
    Traceback (most recent call last):
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      --snip--
      File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1070, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: tom'

[D 2019-04-11 12:40:48.788 JupyterHub base:890] No template for 500
[E 2019-04-11 12:40:48.790 JupyterHub log:150] {"X-Forwarded-Host": "10.39.241.3:8000","X-Forwarded-Proto": "http","X-Forwarded-Port": "8000","X-Forwarded-For": "::ffff:10.1.10.37","Cookie": "jupyterhub-hub-login=\"2|1:0|10:1555006805|20:jupyterhub-hub-login|44:OTdmMTA5Y2YzZmI5NGFkNDk5ZjM5NTRkYTk4M2VjMTQ=|d80c8e87c232f3198b7c9196acbc3ee7700fc0de0b79c69d659a9b35aa4f8b87\"; jupyterhub-session-id=12e3aba64a0b40049d548dae0ce9498a; _xsrf=2|bea05d33|57eb05c68a16f675751deae048e6eb2b|1554775311","Accept-Language": "en-US,en;q=0.9","Accept-Encoding": "gzip, deflate","Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36","Dnt": "1","Upgrade-Insecure-Requests": "1","Cache-Control": "max-age=0","Connection": "close","Host": "10.39.241.3:8000"}
[E 2019-04-11 12:40:48.790 JupyterHub log:158] 500 GET /hub/user/tom/ (tom@::ffff:10.1.10.37) 59.21ms
```

I believe that the capitalization of the username returned from the TestAuthenticator class is not being respected. For example, I believe that the first line of the output log is coming from [jupyterhub/handlers/base.pyL509](https://github.com/jupyterhub/jupyterhub/blob/0.9.6/jupyterhub/handlers/base.py#L509).

**Comment by distortedsignal** [comment]
I believe that my confusion is that I did not expect the username to be normalized after it was returned from the `authenticate` function. For reference, I believe that the internal place where the username is changed is at [jupyterhub/auth.py#L271](https://github.com/jupyterhub/jupyterhub/blob/0.9.6/jupyterhub/auth.py#L271).

**Comment by distortedsignal** [comment]
In my opinion, one of two things needs to change:
1. Normalizing the username should be optional and turned on by a flag in the config file.
2. A note should be inserted in the config file documentation in order to clarify that any Authenticator that subclasses Authenticator will need to override this function to let the returned usernames through unmolested.

**Comment by distortedsignal** [comment]
Duplicate of #1671
