### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by vishaldesai** [jupyterhub/jupyterhub#2517]
I can login using user vishal but getting timeout error as shown below.

Dockerfile:
```
FROM jupyterhub/jupyterhub:latest
#FROM jupyterhub/jupyterhub-onbuild
RUN apt-get update
RUN apt-get --assume-yes install vim
RUN echo "c.Authenticator.whitelist = {'vishal'}" >> /srv/jupyterhub/jupyterhub_config.py
Run echo "c.LocalAuthenticator.create_system_users = True" >> /srv/jupyterhub/jupyterhub_config.py
RUN echo "c.Authenticator.admin_users = {'vishal'}" >> /srv/jupyterhub/jupyterhub_config.py
RUN echo "c.JupyterHub.admin_access = True " >> /srv/jupyterhub/jupyterhub_config.py
```

```
f40f240c8a47:jupyterhub desaivis$ docker run --rm -ti -p 8000:8000 jupyterhub/test
[I 2019-04-12 13:42:51.653 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0b2
[I 2019-04-12 13:42:51.653 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0b2
[I 2019-04-12 13:42:51.661 JupyterHub app:1302] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2019-04-12 13:42:51.684 alembic.runtime.migration migration:130] Context impl SQLiteImpl.
[I 2019-04-12 13:42:51.685 alembic.runtime.migration migration:137] Will assume non-transactional DDL.
[I 2019-04-12 13:42:51.702 alembic.runtime.migration migration:356] Running stamp_revision  -> 4dc2d5a8c53c
[I 2019-04-12 13:42:51.801 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2019-04-12 13:42:51.842 JupyterHub auth:766] Creating user: adduser -q --gecos '""' --disabled-password vishal
[I 2019-04-12 13:42:52.000 JupyterHub app:2338] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-04-12 13:42:52.002 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-04-12 13:42:52.002 JupyterHub proxy:645] Starting proxy @ http://:8000
13:42:52.615 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
13:42:52.623 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2019-04-12 13:42:52.840 JupyterHub proxy:319] Checking routes
[I 2019-04-12 13:42:52.841 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
[I 2019-04-12 13:42:52.866 JupyterHub app:2423] JupyterHub is now running at http://:8000
[I 2019-04-12 13:42:59.711 JupyterHub log:174] 302 GET / -> /hub/ (@127.0.0.1) 2.03ms
[W 2019-04-12 13:42:59.728 JupyterHub base:350] Invalid or expired cookie token
[I 2019-04-12 13:42:59.732 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@127.0.0.1) 4.56ms
[I 2019-04-12 13:42:59.797 JupyterHub log:174] 200 GET /hub/login (@127.0.0.1) 53.40ms
[I 2019-04-12 13:43:37.517 JupyterHub base:663] User logged in: vishal
[I 2019-04-12 13:43:37.530 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (vishal@127.0.0.1) 47.52ms
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.9.125-linuxkit x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

[W 2019-04-12 13:43:37.609 JupyterHub auth:941] Failed to open PAM session for vishal: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2019-04-12 13:43:37.609 JupyterHub auth:942] Disabling PAM sessions from now on.
[I 2019-04-12 13:43:37.621 JupyterHub spawner:1387] Spawning jupyterhub-singleuser --port=36953
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 24, in <module>
    import notebook
ModuleNotFoundError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 26, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[I 2019-04-12 13:43:38.554 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/vishal (vishal@127.0.0.1) 1014.73ms
[I 2019-04-12 13:43:38.579 JupyterHub pages:303] vishal is pending spawn
[I 2019-04-12 13:43:38.589 JupyterHub log:174] 200 GET /hub/spawn-pending/vishal (vishal@127.0.0.1) 22.70ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=HTTPError()>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 922, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for vishal may contain details.)
[W 2019-04-12 13:44:08.751 JupyterHub user:678] vishal's server never showed up at http://127.0.0.1:36953/user/vishal/ after 30 seconds. Giving up
[E 2019-04-12 13:44:08.783 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py:800> exception=TimeoutError("Server at http://127.0.0.1:36953/user/vishal/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 589, in error_callback
        future.result()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
        await spawn_future
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 654, in spawn
        await self._wait_up(spawner)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 701, in _wait_up
        raise e
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/user.py", line 669, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:36953/user/vishal/ didn't respond in 30 seconds
    
[I 2019-04-12 13:44:08.785 JupyterHub log:174] 200 GET /hub/api/users/vishal/server/progress (vishal@127.0.0.1) 30065.86ms
```
![Screen Shot 2019-04-12 at 9 48 07 AM](https://user-images.githubusercontent.com/9009125/56042060-2b5ac000-5d08-11e9-9ede-41c4ab197f0f.png)

**Comment by ryogesh** [comment]
Refer: https://github.com/jupyterhub/jupyterhub#docker
"To run the single-user servers, which may be on the same system as the Hub or not, Jupyter Notebook version 4 or greater must be installed."

Hence the error "ModuleNotFoundError: No module named 'notebook'"

You can try installing any of the notebooks 
https://hub.docker.com/u/jupyter

**Comment by vishaldesai** [comment]
Thanks @ryogesh. It works now.

As I'm deploying this to AWS ECS I cannot login to container to reset password. Is there anyway to set password for admin users from config file?

**Comment by minrk** [comment]
@vishaldesai yes, you can create them in your Dockerfile via calls to `adduser`, etc. You can also `pip install notebook` in your dockerfile.

**Comment by vishaldesai** [comment]
Thanks. This can be closed.

**Comment by awracms** [comment]
Awesome it worked - see my Dockerfiles example for other:
`FROM jupyterhub/jupyterhub

RUN pip install notebook

ENV USERNAME=admin
ENV PASSWORD=admin

RUN useradd -m -p $(openssl passwd -1 ${PASSWORD}) -s /bin/bash -G sudo ${USERNAME}
USER admin
WORKDIR /home/admin`

**Comment by ssharma94** [comment]
Awesome it worked. See Dockerfiles example:
```
FROM jupyterhub/jupyterhub

RUN pip install notebook

ENV USERNAME=admin
ENV PASSWORD=admin

RUN useradd -m -p $(openssl passwd -1 ${PASSWORD}) -s /bin/bash -G sudo ${USERNAME}
USER admin
WORKDIR /home/admin
```
