### ISSUE TITLE
KeyError: 'missing key "certfile" in ssl_options'

### ISSUE THREAD

**Issue by mattk08** [jupyterhub/jupyterhub#2522]
I'm trying to start jupyterhub with SSL.  I've provided my key and cert, and jupyter starts, but when I connect, I get this error.

jupyterhub --debug --ssl-key private_key  --ssl-cert mycert.pem --port 8888

```Traceback (most recent call last):
  File "/usr/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 496, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 403, in initialize
    return super().initialize(argv)
  File "</usr/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/usr/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 450, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 1402, in init_webapp
    max_buffer_size=self.max_buffer_size)
  File "/usr/lib64/python3.6/site-packages/tornado/util.py", line 286, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/usr/lib64/python3.6/site-packages/tornado/httpserver.py", line 191, in initialize
    read_chunk_size=chunk_size,
  File "/usr/lib64/python3.6/site-packages/tornado/tcpserver.py", line 130, in __init__
    raise KeyError('missing key "certfile" in ssl_options')
KeyError: 'missing key "certfile" in ssl_options'```

**Comment by minrk** [comment]
Do you have any configuration in jupyterhub_config.py? What version of jupyterhub?

**Comment by mattk08** [comment]
I have the default jupyterhub_config.py with no changes.  
```jupyterhub --version 0.9.6```

**Comment by mattk08** [comment]
As a test, I ran jupyter notebook (v5.7.8) with the same cert/keyfile to try to rule out a problem with the cert/key and it works fine.

**Comment by mattk08** [comment]
This was silly mistake on my part.  

When i first installed jupyterhub I was logged in as my user and I had done some tests with jupyter_config in my home directory.  Later, I was running jupyterhub as root with a jupyter_config in the root directory, but was logging into jupyterhub with the LDAP authenticator and when the local process spawner kicked off, it was scanning my user home directory for jupyterhub config files and found one that I was playing with earlier that was not configured to use certs.
