### ISSUE TITLE
configurable-http-proxy failed t start because of ssl bad password

### ISSUE THREAD

**Issue by vasu0494** [jupyterhub/jupyterhub#2554]
Error: error:0906A068:PEM routines:PEM_do_header:bad password read
   at Object.createSecureContext (_tls_common.js:144:17)
   at Server (_tls_wrap.js:868:27)
   at new Server (https.js:62:14)
   at Object.createServer (https.js:84:10)
   at new ConfigurableProxy (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:222:32)
   at Object.<anonymous> (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:300:13)
   at Module._compile (internal/modules/cjs/loader.js:689:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
   at Module.load (internal/modules/cjs/loader.js:599:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
_tls_common.js:144
     c.context.setKey(key, passphrase);
               ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
   at Object.createSecureContext (_tls_common.js:144:17)
   at Server (_tls_wrap.js:868:27)
   at new Server (https.js:62:14)
   at Object.createServer (https.js:84:10)
   at new ConfigurableProxy (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:222:32)
   at Object.<anonymous> (/opt/rh/rh-nodejs10/root/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:300:13)
   at Module._compile (internal/modules/cjs/loader.js:689:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
   at Module.load (internal/modules/cjs/loader.js:599:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

How can I specify passphrase while starting the proxy.

I'm trying to start service using following command
Ex:
"configurable-http-proxy --ip 0.0.0.0 --port 8443 --api-ip 0.0.0.0 --api-port 9443 --ssl-key=path/to/ssl.key --ssl-cert=path/to/ssl.crt"

**Comment by ryogesh** [comment]
Does this help?
https://github.com/jupyterhub/configurable-http-proxy/pull/175

**Comment by vasu0494** [comment]
yes, thanks everyone.

**Comment by vasu0494** [comment]
export CONFIGPROXY_SSL_KEY_PASSPHRASE=helloworld
