### ISSUE TITLE
Jupyter hub 500 internal server issue while login for users

### ISSUE THREAD

**Issue by krishm228** [jupyterhub/jupyterhub#2567]
**We are receiving the following Error** 

500: Internal server Error
Failed to reach your server .Please try again later.contact admin 

**We could see the following error in the logs** 
Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 720, in get
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), spawner._spawn_future)
      File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)

Please  help us to fix the issue and to log into Jupyterhub with out any issues

**Comment by nellaivijay** [comment]
in addition to that, we noticed below exception, 
[E 2019-05-16 12:13:54.617 JupyterHub log:122] 500 GET /hub/user/des/ (des@10.10.10.10) 10325.94ms
[D 2019-05-16 12:13:58.188 JupyterHub log:122] 304 GET /hub/home (des@10.10.10.10) 4.81ms
[I 2019-05-16 12:14:00.102 JupyterHub log:122] 302 GET /hub/spawn → /user/tantrp/ (tantrp@10.42.38.199) 3.48ms
[I 2019-05-16 12:14:00.365 JupyterHub log:122] 302 GET /user/tantrp/ → /hub/user/tantrp/ (@10.10.10.10) 0.44ms
[D 2019-05-16 12:14:01.392 JupyterHub base:718] Waiting for tantrp pending spawn
[D 2019-05-16 12:14:06.800 JupyterHub log:122] 304 GET /hub/home (des@10.10.10.10) 4.62ms
[I 2019-05-16 12:14:11.394 JupyterHub base:722] Pending spawn for tantrp didn't finish in 10.0 seconds
[I 2019-05-16 12:14:11.394 JupyterHub base:727] tantrp is pending spawn
[I 2019-05-16 12:14:11.398 JupyterHub log:122] 200 GET /hub/user/tantrp/ (des@10.10.10.10) 10007.36ms
[W 2019-05-16 12:14:12.157 JupyterHub user:458] tantrp's server never showed up at http://127.0.0.1:53932/user/tantrp/ after 30 seconds. Giving up

**Comment by nellaivijay** [comment]
Updating the jupyterhub --debug info below, 
`[cdhadmin@ddlpldst102 ~]$ jupyterhub --debug
[D 2019-05-16 16:11:50.044 JupyterHub application:555] Looking for jupyterhub_config in /home/cdhadmin
[D 2019-05-16 16:11:50.048 JupyterHub app:866] Generating new cookie_secret
[I 2019-05-16 16:11:50.048 JupyterHub app:871] Writing cookie_secret to /home/cdhadmin/jupyterhub_cookie_secret
[D 2019-05-16 16:11:50.050 JupyterHub app:886] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2019-05-16 16:11:50.062 JupyterHub orm:475] Stamping empty database with alembic revision 3ec6993fe20c
[I 2019-05-16 16:11:50.067 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2019-05-16 16:11:50.067 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2019-05-16 16:11:50.073 alembic.runtime.migration migration:327] Running stamp_revision  -> 3ec6993fe20c
[D 2019-05-16 16:11:50.073 alembic.runtime.migration migration:516] new branch insert 3ec6993fe20c
[W 2019-05-16 16:11:50.125 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2019-05-16 16:11:50.125 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-05-16 16:11:50.125 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[D 2019-05-16 16:11:50.144 JupyterHub app:1241] Loaded users:
[I 2019-05-16 16:11:50.149 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-05-16 16:11:50.149 JupyterHub proxy:415]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2019-05-16 16:11:50.150 JupyterHub proxy:456] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2019-05-16 16:11:50.150 JupyterHub proxy:458] Starting proxy @ http://*:8000/
[D 2019-05-16 16:11:50.150 JupyterHub proxy:459] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error']
[D 2019-05-16 16:11:50.154 JupyterHub proxy:491] Proxy started and appears to be up
[D 2019-05-16 16:11:50.156 JupyterHub proxy:552] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
[E 2019-05-16 16:11:50.158 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1621, in launch_instance_async
        yield self.start()
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/app.py", line 1569, in start
        yield self.proxy.check_routes(self.users, self._service_map)
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 294, in check_routes
        routes = yield self.get_all_routes()
      File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 589, in get_all_routes
        resp = yield self.api_request('', client=client)
    tornado.httpclient.HTTPError: HTTP 403: Forbidden

[D 2019-05-16 16:11:50.159 JupyterHub application:647] Exiting application: jupyterhub
[cdhadmin@ddlpldst102 ~]$ 16:11:50.270 - info: [ConfigProxy] Proxying http://*:8000 to (no default)
16:11:50.273 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
16:11:50.274 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:253:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
16:11:50.275 - error: [ConfigProxy] Uncaught Exception Error: listen EADDRINUSE 127.0.0.1:8001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at Immediate._tickCallback [as _onImmediate] (internal/process/next_tick.js:180:9)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
`

**Comment by ryogesh** [comment]
"Uncaught Exception Error: listen EADDRINUSE 127.0.0.1:8001"

Is the port in use by another process? try ss -tan |grep <port>

**Comment by krishm228** [comment]
@ryogesh , Thanks for the response.

We could see the following output
ss -tan |grep 8001
LISTEN     0      128    127.0.0.1:8001                     *:*
CLOSE-WAIT 1      0      127.0.0.1:60448              127.0.0.1:8001
FIN-WAIT-2 0      0      127.0.0.1:8001               127.0.0.1:60448

when we do netstat -tulnp | grep 60448  we couldn't find anything over there.

Could you please suggest.

Thanks in advance

**Comment by ryogesh** [comment]
there is already a process listening on 8001. Can you try to find which process, and resolve
sudo ss -tanp |grep 8001

or you can change the jupyterhub config file to use a different port.

**Comment by krishm228** [comment]
Thanks for your suggestions ..
 we are able to resolve the issue based on the following error 
Logs info:
File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/proxy.py", line 589, in get_all_routes
resp = yield self.api_request('', client=client)
tornado.httpclient.HTTPError: HTTP 403: Forbidden

By logs we could see issue with tornado package, when we verified we came know  it is not causing an issue but there is an dependent package pyzmq which is running lower version causing issue hence upgraded the pyzmq.
After recycling the services of Jupyterhub issue disappear.
