### ISSUE TITLE
Gettting 500 when trying to setup ldap with onelogin

### ISSUE THREAD

**Issue by Am1rr3zA** [jupyterhub/jupyterhub#2583]
I am trying to configure Jupyerhub (the one that installed on AWS EMR)  to use LDAP for it's configuration. I am following thus steps
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-jupyterhub-ldap-users.html

but whenever I try to login I get this exception in  `/var/log/jupyter/jupyter.log`

```
[E 2019-05-23 22:51:40.348 JupyterHub web:1670] Uncaught exception POST /hub/login?next= (::ffff:10.100.0.151)
    HTTPServerRequest(protocol='https', host='ip-10-140-3-232.ec2.internal:9443', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:10.100.0.151')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.6/types.py", line 248, in wrapped
        coro = func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 301, in authenticate
        resolved_username = self.resolve_username(username)
      File "/opt/conda/lib/python3.6/site-packages/ldapauthenticator/ldapauthenticator.py", line 237, in resolve_username
        attributes=[self.lookup_dn_user_dn_attribute]
      File "/opt/conda/lib/python3.6/site-packages/ldap3/core/connection.py", line 785, in search
        check_names=self.check_names)
      File "/opt/conda/lib/python3.6/site-packages/ldap3/operation/search.py", line 376, in search_operation
        request['attributes'] = build_attribute_selection(attributes, schema)
      File "/opt/conda/lib/python3.6/site-packages/ldap3/operation/search.py", line 311, in build_attribute_selection
        attribute_selection[index] = Selector(attribute)
      File "/opt/conda/lib/python3.6/site-packages/pyasn1/type/univ.py", line 819, in __init__
        base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/pyasn1/type/base.py", line 240, in __init__
        value = self.prettyIn(value)
      File "/opt/conda/lib/python3.6/site-packages/pyasn1/type/univ.py", line 878, in prettyIn
        return bytes(value)
    TypeError: cannot convert 'NoneType' object to bytes

[E 2019-05-23 22:51:40.355 JupyterHub log:150] {
      "X-Forwarded-Host": "ip-10-140-3-232.ec2.internal:9443",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "9443",
      "X-Forwarded-For": "::ffff:10.100.0.151",
      "Upgrade-Insecure-Requests": "1",
      "Cookie": "_xsrf=2|0bb5c469|a9cfc3a3b84fbdab3fc843f7a387f407|1558650495",
      "Connection": "close",
      "Content-Length": "52",
      "Content-Type": "application/x-www-form-urlencoded",
      "Referer": "https://ip-10-140-3-232.ec2.internal:9443/hub/login",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0",
      "Host": "ip-10-140-3-232.ec2.internal:9443"
    }
[E 2019-05-23 22:51:40.355 JupyterHub log:158] 500 POST /hub/login?next= (@::ffff:10.100.0.151) 684.25ms
```

I have tried `ldapsearch` and it's working fine and I get back those user but I can not loging to jupyerhub

```
 ldapsearch -x -H ldaps://ldap.us.onelogin.com  -D "cn=LDAP_USER,ou=users,dc=***,dc=onelogin,dc=com"  -W  -b "dc=***,dc=onelogin,dc=com"  -s sub  "(objectclass=*)" uidNumber gidNumber
```

My user name is like `xxx@yyy.com` so I have created the with same format in `/home/xxx@yyy.com` and also added this 
`c.LDAPAuthenticator.valid_username_regex = '^[a-z][.a-z0-9_@]*$'`
in my `jupyterhub_config.py` to accept `@`

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Comment by davidedelvento** [comment]
I am experiencing exactly this problem, so frustrating that the stack trace does not say anything useful. Was it ever solved??
