### ISSUE TITLE
500 GET Error Spawning Failing running JupyterHub on Ubuntu non root

### ISSUE THREAD

**Issue by JackLidge** [jupyterhub/jupyterhub#2591]
I'm trying to run a JupyterHub on a local system which will be accessed by multiple users remotely. I've been following the set up for running it as non-root as detailed here: [Using sudo to run Jupyterhub without root privileges](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges).

In order to get around some errors I've had to update the path to configurable-http-proxy (v1.3.0) in the config.py file and also install the legacy nodejs package for my version of node (v11.14.0). Now when I try to run Jupyterhub from the user created to run it non root, using the following command and try to log in as a user specified in the config:

`sudo -u jhub /opt/miniconda3/envs/mdc1_7/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner`

I get the following output on terminal:
```
[I 2019-05-29 16:04:55.414 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0
[I 2019-05-29 16:04:55.414 JupyterHub app:2120] Using Spawner: sudospawner.spawner.SudoSpawner
[I 2019-05-29 16:04:55.417 JupyterHub app:1257] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2019-05-29 16:04:55.430 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2019-05-29 16:04:55.469 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[I 2019-05-29 16:04:55.470 JupyterHub proxy:645] Starting proxy @ http://192.168.23.102:8000/
16:04:55.572 - info: [ConfigProxy] Proxying https://192.168.23.102:8000 to (no default)
16:04:55.574 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2019-05-29 16:04:55.713 JupyterHub proxy:319] Checking routes
[I 2019-05-29 16:04:55.713 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
[I 2019-05-29 16:04:55.716 JupyterHub app:2422] JupyterHub is now running at http://192.168.23.102:8000/
[I 2019-05-29 16:05:12.099 JupyterHub base:663] User logged in: vxeos
[I 2019-05-29 16:05:12.101 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (vxeos@127.0.0.1) 29.80ms
sh: 1: cannot create /run/motd.dynamic.new: Permission denied

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

sudo: a password is required
[E 2019-05-29 16:05:12.160 JupyterHub spawner:83] Failed to get JSON result from mediator: ''
[E 2019-05-29 16:05:12.160 JupyterHub user:626] Unhandled error starting vxeos's server: substring not found
[I 2019-05-29 16:05:12.188 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/vxeos (vxeos@127.0.0.1) 73.42ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/jupyterhub/handlers/base.py:697> exception=ValueError('substring not found',)>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 889, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 807, in finish_user_spawn
    await spawn_future
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/jupyterhub/user.py", line 642, in spawn
    raise e
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/jupyterhub/user.py", line 546, in spawn
    url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/sudospawner/spawner.py", line 92, in start
    reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/opt/miniconda3/envs/mdc1_7/lib/python3.6/site-packages/sudospawner/spawner.py", line 80, in do
    data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
ValueError: substring not found
[E 2019-05-29 16:05:12.206 JupyterHub pages:284] Previous spawn for vxeos failed: substring not found
[E 2019-05-29 16:05:12.225 JupyterHub log:166] {
      "Upgrade-Insecure-Requests": "1",
      "Cookie": "jupyterhub-hub-login=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Connection": "close",
      "Referer": "https://192.168.23.102:8000/hub/login?next=",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0",
      "Host": "192.168.23.102:8000"
    }
[E 2019-05-29 16:05:12.225 JupyterHub log:174] 500 GET /hub/spawn-pending/vxeos (vxeos@127.0.0.1) 24.70ms
```

If it helps, below is the config.py file:
`
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.port = 8000
c.JupyterHub.ssl_cert = '/srv/jupyterhub/jupyterhub.cert'
c.JupyterHub.ssl_key = '/srv/jupyterhub/jupyterhub.key'
#c.Spawner.notebook_dir = '~/notebooks/'
c.Authenticator.whitelist = {'sibelius_admin','vxeos','jhub'}
c.Authenticator.admin_users = {'sibelius_admin','jhub'}
c.ConfigurableHTTPProxy.command = '/opt/miniconda3/envs/mdc1_7/bin/configurable-http-proxy'`

Any help with this issue would be greatly appreciated.

**Comment by ryogesh** [comment]
"sudo: a password is required"
1)
Have you setup the account in /etc/sudoers for NOPASSWD
e.g. rhea ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD
2) 
Does "Test sudo setup:" per documentation work?

**Comment by JackLidge** [comment]
I've set up the /etc/sudoers file using the group reference option, adding the following to the bottom using visudo:
```
Cmnd_Alias JUPYTER_CMD = /opt/miniconda3/envs/mdc1_7/bin/sudospawner
%jupyterhub ALL=(jhub) /usr/bin/sudo
jhub ALL=(%jupyterhub) NOPASSWD:JUPYTER_CMD
```
Where jhub is a user set up in the equivalent way to rhea in the docs. Should I have followed the docs exactly and set up a user called rhea?

Yes, following the "Test sudo setup" from the documentation works as expected.

**Comment by JackLidge** [comment]
solved this issue by adding: 
`c.SudoSpawner.sudospawner_path = '/*actual path*/sudospawner'` 
to the jupyterhub_config.py file as my environment is somewhere other than /usr/local/bin and ensuring I start-up with the exact command used in the help article.
