### ISSUE TITLE
Can't run pre-commit hook

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#2636]
I'm trying to run the pre-commit hooks, and running into the following:

```
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
  - id: reorder-python-imports
    language_version: python3.6
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: requirements-txt-fixer
  - id: flake8
cat: cat: No such file or directory
An unexpected error has occurred: CalledProcessError: Command: ('/home/yuvipanda/.local/share/virtualenvs/telemetry/bin/python3', '-mvirtualenv', '/home/yuvipanda/.cache/pre-commit/repo4a40_y6k/py_env-python3.6', '-p', 'python3.6')
Return code: 1
Expected return code: 0
Output: 
    Running virtualenv with interpreter /usr/bin/python3.6
    
Errors: 
    Traceback (most recent call last):
      File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/virtualenv.py", line 22, in <module>
        import distutils.spawn
    ModuleNotFoundError: No module named 'distutils.spawn'
    

Traceback (most recent call last):
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/main.py", line 294, in main
    return run(args.config, store, args)
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/commands/run.py", line 291, in run
    install_hook_envs(hooks, store)
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/languages/python.py", line 161, in install_environment
    _make_venv(env_dir, python)
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/languages/python.py", line 173, in make_venv
    cmd_output(*cmd, env=env, cwd='/')
  File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/home/yuvipanda/.local/share/virtualenvs/telemetry/bin/python3', '-mvirtualenv', '/home/yuvipanda/.cache/pre-commit/repo4a40_y6k/py_env-python3.6', '-p', 'python3.6')
Return code: 1
Expected return code: 0
Output: 
    Running virtualenv with interpreter /usr/bin/python3.6
    
Errors: 
    Traceback (most recent call last):
      File "/home/yuvipanda/.local/share/virtualenvs/telemetry/lib/python3.7/site-packages/virtualenv.py", line 22, in <module>
        import distutils.spawn
    ModuleNotFoundError: No module named 'distutils.spawn'
    
```

This makes #2542 keep failing, and it makes me sad.

**Comment by minrk** [comment]
This looks like virtualenv is missing fundamental dependencies, which is weird since they are part of the stdlib, so it shouldn't be able to be missing. How have you installed Python (3.6 and 3.7)? If it's from apt, is there a chance it's missing something like `python3-distutils` since apt can break up the Python stdlib into optional pieces that really shouldn't be optional?

**Comment by consideRatio** [comment]
I think installing pre-commit with conda instead of pip may be relevant. Is your pre-commit package installed with pip or pipenv? Hmmm on mobile and cant quickly link to discussion about issues with pre-commit.

**Comment by manics** [comment]
This should all work now
