### ISSUE TITLE
Q: logo_file config - only absolute paths or relative to what?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2673]
I'm wondering if the JupyterHub `logo_file` traitlet can be configured to use a relative path, and if it can, figure out what will it be relative to.

https://github.com/jupyterhub/jupyterhub/blob/669dbfd449af475e413ec28bb582c3cc17007580/jupyterhub/app.py#L588-L595

If it is not possible to use a relative path configuration, and you can write some additional configuration, I figure I could configure it like this but I verified that.

```
c.JupyterHub.logo_file = os.path.join(c.JupyterHub.data_files_path, 'static', 'images', 'jupyterhub-80.png')
```

---

I found this very related issue #2178 by ... me :sweat_smile:

**Comment by consideRatio** [comment]
The idea above of setting the `logo_file` to something relying on `static_path` didn't work out, with the following error.

```
[E 2019-08-05 12:57:13.011 JupyterHub app:2482]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2479, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2088, in initialize
        self.load_config_file(self.config_file)
      File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 469, in <module>
        exec(config_py)
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not LazyConfigValue
```

Hmmm...

# My issue summarized
I have injected a folder with images, and can reference these fine from jupyterhub templates using for example `/hub/static/external/custom.png`. I'd like to avoid copy-pasting and making a small change to the page.html template though. The page.html template reference `/hub/logo` and that is configured to point to whatever c.JupyterHub.logo_file points to. But this needs a absolute OS filesystem path and I'd like to avoid referencing a absolute OS filesystem path.

I fail to avoid hardcoding it currently though, while that is certainly an option.

**Comment by manics** [comment]
Is there an action here?
