### ISSUE TITLE
jupyterhub --version returns error

### ISSUE THREAD

**Issue by MRichards99** [jupyterhub/jupyterhub#2692]
**Describe the bug**
Executing the command `jupyterhub --version` returns the correct version number but also an error message. This doesn't appear to effect my instance of Jupyterhub. I've installed Jupyterhub in a virtual environment, using Python 3.6.8. I first installed Jupyterhub at version 0.9.6 and have upgraded (using Pip) this morning to version 1.0.0

**To Reproduce**
1. Using Python 3.6.8, install Jupyterhub version 0.9.6 with Pip into a virtual environment
2. Using Pip, use the `--upgrade` option to upgrade to 1.0.0
3. Execute `jupyterhub --version`
4. See error as per expected behaviour section

**Expected behavior**
You should see the following output (or at least I have done):
```
1.0.0
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/app.py:2477> exception=SystemExit(0,)>
Traceback (most recent call last):
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
    await self.initialize(argv)
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/jupyterhub/app.py", line 2085, in initialize
    super().initialize(*args, **kwargs)
  File "</home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/decorator.py:decorator-gen-2>", line 2, in initialize
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/traitlets/config/application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "</home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/decorator.py:decorator-gen-4>", line 2, in parse_command_line
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/traitlets/config/application.py", line 531, in parse_command_line
    self.exit(0)
  File "/home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages/traitlets/config/application.py", line 648, in exit
    sys.exit(exit_status)
SystemExit: 0
```

**Desktop (please complete the following information):**
 - OS: Scientific Linux 7

**Additional context**
This didn't happen in version 0.9.6 but occurs in version 1.0.0.

- Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.
- Running in `--debug` mode can also be helpful for troubleshooting.

Output of `jupyter troubleshoot --debug`
```
$PATH:
        /home/xfu59478/jupyterhub/venv3.6/bin
        /home/xfu59478/jupyterhub/venv3.6/bin
        /usr/local/bin
        /usr/bin
        /usr/local/sbin
        /usr/sbin
        /home/xfu59478/.local/bin
        /home/xfu59478/bin

sys.path:
        /home/xfu59478/jupyterhub/venv3.6/bin
        /usr/lib64/python36.zip
        /usr/lib64/python3.6
        /usr/lib64/python3.6/lib-dynload
        /home/xfu59478/jupyterhub/venv3.6/lib64/python3.6/site-packages
        /home/xfu59478/jupyterhub/venv3.6/lib/python3.6/site-packages

sys.executable:
        /home/xfu59478/jupyterhub/venv3.6/bin/python3.6

sys.version:
        3.6.8 (default, May  2 2019, 20:40:44)
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

platform.platform():
        Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-redhat-7.6-Nitrogen

which -a jupyter:
        /home/xfu59478/jupyterhub/venv3.6/bin/jupyter
        /home/xfu59478/jupyterhub/venv3.6/bin/jupyter

pip list:
        Package                      Version
        ---------------------------- ----------
        alembic                      1.0.8
        apache-libcloud              2.5.0
        asn1crypto                   0.24.0
        async-generator              1.10
        attrs                        19.1.0
        backcall                     0.1.0
        bleach                       3.1.0
        certifi                      2019.3.9
        certipy                      0.1.3
        cffi                         1.12.3
        chardet                      3.0.4
        cryptography                 2.7
        decorator                    4.4.0
        defusedxml                   0.5.0
        entrypoints                  0.3
        idna                         2.8
        ipykernel                    5.1.0
        ipython                      7.4.0
        ipython-genutils             0.2.0
        jedi                         0.13.3
        Jinja2                       2.10.1
        jsonschema                   3.0.1
        jupyter-client               5.2.4
        jupyter-core                 4.4.0
        jupyterhub                   1.0.0
        jupyterhub-ldapauthenticator 1.2.2
        ldap3                        2.6
        libcloudspawner              1.2.1.dev2
        Mako                         1.0.8
        MarkupSafe                   1.1.1
        mistune                      0.8.4
        nbconvert                    5.4.1
        nbformat                     4.4.0
        notebook                     5.7.8
        oauthenticator               0.8.2
        oauthlib                     3.1.0
        pamela                       1.0.0
        pandocfilters                1.4.2
        parso                        0.4.0
        pexpect                      4.7.0
        pickleshare                  0.7.5
        pip                          19.2.2
        prometheus-client            0.6.0
        prompt-toolkit               2.0.9
        ptyprocess                   0.6.0
        pyasn1                       0.4.5
        pycparser                    2.19
        Pygments                     2.3.1
        pyOpenSSL                    19.0.0
        pyrsistent                   0.14.11
        python-dateutil              2.8.0
        python-editor                1.0.4
        python-oauth2                1.1.0
        pyzmq                        18.0.1
        requests                     2.21.0
        Send2Trash                   1.5.0
        setuptools                   39.0.1
        six                          1.12.0
        SQLAlchemy                   1.3.2
        statsd                       3.3.0
        terminado                    0.8.2
        testpath                     0.4.2
        tornado                      6.0.2
        traitlets                    4.3.2
        urllib3                      1.24.1
        wcwidth                      0.1.7
        webencodings                 0.5.1
```

**Comment by GeorgianaElena** [comment]
Hi @MRichards99! Thanks for reporting this issue! I'm going to label this as "duplicate" because I *think* it's similar to https://github.com/jupyterhub/jupyterhub/issues/2568.

**Comment by consideRatio** [comment]
Closed by https://github.com/jupyterhub/jupyterhub/pull/2584, the fix will be part of the release after 1.0.0 that I'm writing a changelog for now.

Thanks for your help reporting this so clearly @MRichards99!

**Comment by mukhendra** [comment]
Hi @GeorgianaElena @consideRatio ,

I'm also facing same issue in my ubntu 16.04 version ,python3 --version 3.5, jupyterhub --version 1.0.0
when i run jupyterhub- h, getting error like "Error: asyncio:Task exception was never retrieved"

**Comment by consideRatio** [comment]
@mukhendra this issue is resolved in JupyterHub 1.1.0 but not JupyterHub 1.0.0

**Comment by mukhendra** [comment]
Thanks @consideRatio may i know how to upgrade from JupyterHub 1.0.0 to JupyterHub 1.1.0

**Comment by consideRatio** [comment]
Depends on how it is installed, but perhaps `pip install --upgrade jupyterhub`
