### ISSUE TITLE
Mac terminal issues

### ISSUE THREAD

**Issue by KenjiGwonin** [jupyterhub/jupyterhub#2706]
I have a big problem of terminal. I deleted so many python data like anaconda, python3, Django
and so on.
and then the problem is happened.
when I open terminal it is shown 

Error processing line 1 of /Users/kenji-gwonin/anaconda3/lib/python3.7/site-packages/matplotlib-3.1.0-py3.7-nspkg.pth:

Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/contextlib.py", line 5, in <module>
    from collections import deque
ImportError: cannot import name 'deque' from 'collections' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 586, in <module>
    main()
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 573, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/site.py", line 178, in addpackage
    import traceback
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/linecache.py", line 8, in <module>
    import functools
  File "/Users/kenji-gwonin/anaconda3/lib/python3.7/functools.py", line 21, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple' from 'collections' (unknown location)
hannoMacBook-Pro:~ kenji-gwonin$ 

I don't know how to fix this issue. please tell me how to fix.
finally, maybe my English level is not good so i don't know you can get my explanation.
but do my best
please

**Comment by ryogesh** [comment]
Looks like you may have deleted the required packages from your installation
see the error
"ImportError: cannot import name 'namedtuple' from 'collections' (unknown location)"

To check, launch a python shell, run and see if the folder and files exist
```
import collections
print(collections.__file__)
```
You may solve the problem by installing Conda again. Refer Conda's documentation for general instructions and for debug/troubleshooting issues.

**Comment by KenjiGwonin** [comment]
i'm sorry for the late reply.
I completely forgot to reply you. thanks to your advice, I solved the problem
