### ISSUE TITLE
Jupyterhub requirement for Tornado 5+ and incompatible with ipyparallel -> LocalSpawner broken?

### ISSUE THREAD

**Issue by galitus** [jupyterhub/jupyterhub#2719]
Hey, 

**Describe the bug**
Jupyterhub 1.0.0 has the strict requirement for tornado 5. 
But the ipyparallel does not work with tornado 5+.
So i don't know how to use it, in my eyes it's (the default config  LocalSpawner) broken till ipyparallel is fixed to work with tornado 5+.
Or am I wrong? Maybe i'm just to stupid to set it up right?

I found this bug: https://github.com/ipython/ipyparallel/issues/318
in which minrk wrote ipyparallel needs to be fixed and tornado 4.5 should be used and it's still open.

So, I don't understand how to use jupyterhub bare metal and default config with a requirement for tornado 5+ when ipyparallel seems not to be fixed.

Do I have to configure something else? Create a workaround?
Help would be really appreciated.

**To Reproduce**
1. install jupyterhub from release source with dependencies on a bare metal machine with just python (no anaconda)
2a. start jupyterhub, login and start your server, create a file and write some simple hello world print -> you will get a kernel error
2b. ipcluster start (same error, i guess jupyterhub will do the same, when a file is used)

**Expected behavior**
The hello world print should work and create output. It does not because the kernel is not working.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser : Ungoogled chromium, doesn't matter at all
 - Version : Version 72.0.3626.122 (Official Build) (64-bit)

**Additional context**

    [E 2019-09-04 12:24:21.104 SingleUserNotebookApp handlers:527] Unhandled error in API request

    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'loop'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib64/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib64/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib64/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/usr/lib64/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/usr/lib64/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/lib64/python3.6/site-packages/jupyter_client/manager.py", line 258, in start_kernel
        self.start_restarter()
      File "/usr/lib64/python3.6/site-packages/jupyter_client/ioloop/manager.py", line 49, in start_restarter
        kernel_manager=self, loop=self.loop,
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate
        value = self.validate(obj, value)
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 1677, in validate
        self.error(obj, value)
      File "/usr/lib64/python3.6/site-packages/traitlets/traitlets.py", line 1524, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f9bbe3e5208>) was specified.

installed versions:
jupyterhub: 1.0.0
ipyparallel: 6.0.2
ipython: 5.4.1
dev-python/traitlets: 4.3.2
jupyter_client: 5.1.0
jupyter_core: 4.4.0
notebook: 5.0.0

If you need any additional informations, please let me know.

Greetings

**Comment by willingc** [comment]
@minrk This question is about JupyterHub, ipyparallel and Tornado 5 support. Thoughts on best next step?

**Comment by galitus** [comment]
Hey, 

sorry for my late response. I tried it on another server, same OS, with a newer notebook, ipython, ipyparallel and it seems to work fine with the localspawner. No problem so far. 
So maybe just the requirements have to be adjusted or documented for the localspawner?

Greetings
