### ISSUE TITLE
How to start JupyterLab at port 443?

### ISSUE THREAD

**Issue by 80O** [jupyterhub/jupyterhub#2728]
When I try to run `jupyterhub --ip 0.0.0.0 --port 443` I get the following permission denied error:

```
[I 2019-09-10 08:34:45.113 JupyterHub app:2147] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.1dev
[I 2019-09-10 08:34:45.113 JupyterHub app:2147] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.1dev
[I 2019-09-10 08:34:45.115 JupyterHub app:1273] Loading cookie_secret from /home/hub/jupyterhub_cookie_secret
[I 2019-09-10 08:34:45.125 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2019-09-10 08:34:45.125 JupyterHub app:1548] No admin users, admin interface will be unavailable.
[W 2019-09-10 08:34:45.125 JupyterHub app:1550] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-09-10 08:34:45.125 JupyterHub app:1579] Not using whitelist. Any authenticated user will be allowed.
[I 2019-09-10 08:34:45.147 JupyterHub app:2364] Hub API listening on http://127.0.0.1:8081/hub/
[W 2019-09-10 08:34:45.147 JupyterHub proxy:516] Found proxy pid file: /home/hub/jupyterhub-proxy.pid
[W 2019-09-10 08:34:45.147 JupyterHub proxy:533] Proxy still running at pid=12292
[W 2019-09-10 08:34:46.148 JupyterHub proxy:553] Stopped proxy at pid=12292
[I 2019-09-10 08:34:46.150 JupyterHub proxy:645] Starting proxy @ http://0.0.0.0:443/
08:34:46.531 [ConfigProxy] info: Proxying https://0.0.0.0:443 to (no default)
08:34:46.533 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
08:34:46.536 [ConfigProxy] error: Uncaught Exception: listen EACCES: permission denied 0.0.0.0:443
08:34:46.536 [ConfigProxy] error: Error: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (net.js:1242:19)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1446:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[C 2019-09-10 08:34:56.941 JupyterHub app:2376] Failed to start proxy
    Traceback (most recent call last):
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/app.py", line 2374, in start
        await self.proxy.start()
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/proxy.py", line 679, in start
        await server.wait_up(1)
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 189, in wait_for_server
        timeout=timeout,
      File "/home/hub/anaconda3/lib/python3.7/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at jupyterserver:443 didn't respond in 1 seconds

```

I followed the setup from here: https://jupyterhub.readthedocs.io/en/stable/quickstart.html

**Comment by markperri** [comment]
Did you run it as root?  443 is a privileged port.  Either way I think it's better to handle SSL separately with a reverse proxy.
