### ISSUE TITLE
500 error trying to use docker spawners

### ISSUE THREAD

**Issue by gpillemer** [jupyterhub/jupyterhub#273]
Sorry another issue... 
Server is working fine with default configuration. 
I tried to follow the docker setup and then when trying to start up server with either the temporary docker spawner or system user spawner, i get a 500 error, and the following in the terminal   

```
 Traceback (most recent call last):
      File "/usr/local/lib/python3.3/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/home/gpillemer/jupyterhub/dockerspawner/src/jupyterhub/jupyterhub/handlers/login.py",                                                     line 66, in post
        status = yield user.spawner.poll()
      File "/usr/local/lib/python3.3/site-packages/dockerspawner/dockerspawner.py", line 221, in p                                                    oll
        container = yield self.get_container()
      File "/usr/local/lib/python3.3/site-packages/dockerspawner/dockerspawner.py", line 247, in g                                                    et_container
        'inspect_container', self.container_name
      File "/usr/local/lib/python3.3/concurrent/futures/_base.py", line 394, in result
        return self.__get_result()
      File "/usr/local/lib/python3.3/concurrent/futures/_base.py", line 353, in __get_result
        raise self._exception
      File "/usr/local/lib/python3.3/concurrent/futures/thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.3/site-packages/dockerspawner/dockerspawner.py", line 209, in _                                                    docker
        return m(*args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/docker/utils/decorators.py", line 20, in wrappe                                                    d
        return f(self, resource_id, *args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/docker/client.py", line 474, in inspect_contain                                                    er
        self._get(self._url("/containers/{0}/json".format(container))),
      File "/usr/local/lib/python3.3/site-packages/docker/clientbase.py", line 86, in _get
        return self.get(url, **self._set_request_timeout(kwargs))
      File "/usr/local/lib/python3.3/site-packages/requests/sessions.py", line 477, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/requests/sessions.py", line 465, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.3/site-packages/requests/sessions.py", line 573, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/requests/adapters.py", line 415, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such fil                                                    e or directory'))
```

**Comment by minrk** [comment]
I suspect there is something missing in the config used to connect to docker. Can you perhaps try a simple docker-py example and see if it works? How are you running docker? Are you using TLS?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
