### ISSUE TITLE
matlab_kernel not starting

### ISSUE THREAD

**Issue by SoulEater45** [jupyterhub/jupyterhub#2804]
I was trying to setup jypterhub in a docker container witch access to an external instance of matlab. This worked fine for a normal jupyter notebook instance (jupyter/datascience-notebook) but not in a jupyterhub container with all the same configurations. The following error is being shown:
```[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/matlab_kernel/kernel.py", line 81, in _matlab
    self.__matlab = matlab.engine.start_matlab()
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 117, in start_matlab
    eng = future.result()
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/matlabfuture.py", line 87, in result
    handle = pythonengine.getMATLAB(self._future)
matlab.engine.EngineError: Transport stopped.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/lib/python3.6/site-packages/metakernel/_metakernel.py", line 395, in do_execute
    retval = self.do_execute_direct(code)
  File "/opt/conda/lib/python3.6/site-packages/matlab_kernel/kernel.py", line 97, in do_execute_direct
    retval = self._execute_async(code)
  File "/opt/conda/lib/python3.6/site-packages/matlab_kernel/kernel.py", line 255, in _execute_async
    future = self._matlab.eval(code, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/matlab_kernel/kernel.py", line 83, in _matlab
    self.__matlab = matlab.engine.connect_matlab()
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 177, in connect_matlab
    eng = future.result()
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/opt/conda/lib/python3.6/site-packages/matlab/engine/matlabfuture.py", line 87, in result
    handle = pythonengine.getMATLAB(self._future)
matlab.engine.EngineError: Transport stopped.
```

I really tried everything to make it run, but with no luck, can someone please help me.

**Comment by ryogesh** [comment]
1) "File "/opt/conda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 177, in connect_matlab" 
Are you running the container in host network_mode or the default bridge? Try switching and see if it helps.

2) Can you run with debug enabled and share the jupyterhub logs; Sharing the config also helps;

**Comment by tide1994cc** [comment]
Maybe you should check pyhon==3.6 whether to support matlab you installed. As far as I know,  matlab 2016 is not working, when you use python ==3.6，matlab 2017a is suitable.
