### ISSUE TITLE
Jupyterhub server is not responding sometimes

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [jupyterhub/jupyterhub#2808]
We have a couple of jupyterhub servers running behind a load balancer (cookie persistence). Recently, some of the jupyterhub servers are not responding sometimes. They are going on and off. 

### Troubleshooting Info:
**When server is running** 
[user@hostname:~]# curl -i -k https://localhost:443
HTTP/1.1 302 Found
date: Thu, 07 Nov 2019 18:39:13 GMT
connection: close
server: TornadoServer/5.0.2
x-jupyterhub-version: 0.8.1
content-security-policy: frame-ancestors 'self'; report-uri /notebooks/hub/security/csp-report
location: /notebooks/hub/
content-length: 0
content-type: text/html; charset=UTF-8

**When server is not responding** 
[user@hostname:~]# curl -i -k https://localhost:443
curl: (35) Encountered end of file

**Logs when no response**

```10:45:56.187 - error: [ConfigProxy] Proxy error:  Error: connect EMFILE 127.0.0.1:8081 - Local (undefined:undefined)
at internalConnect (net.js:858:16)
at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
at defaultTriggerAsyncIdScope (net.js:948:9)
at processTicksAndRejections (internal/process/next_tick.js:74:9)
10:45:56.187 - error: [ConfigProxy] 503 GET /
10:45:56.188 - error: [ConfigProxy] Failed to get custom error page Error: connect EMFILE 127.0.0.1:8081 - Local (undefined:undefined)
at internalConnect (net.js:858:16)
at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
at defaultTriggerAsyncIdScope (net.js:948:9)
at processTicksAndRejections (internal/process/next_tick.js:74:9)
10:45:56.188 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
at ClientRequest.<anonymous> (/opt/conda/anaconda3/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
at ClientRequest.emit (events.js:197:13)
at Socket.socketErrorListener (_http_client.js:399:9)
at Socket.emit (events.js:197:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
at processTicksAndRejections (internal/process/next_tick.js:76:17)```

**Comment by praveenkanamarlapudi** [comment]
After user login, we are seeing below error

```jupyterhub[152822]: [I 2019-11-07 10:53:25.253 SingleUserNotebookApp log:122] 302 GET /notebooks/user/USERNAME/oauth_callback?code=<OAUTH_CODE> → /notebooks/user/USERNAME/lab? (@10.244.66.169) 75.44ms
jupyterhub[152822]: [I 2019-11-07 10:53:25.362 JupyterHub log:122] 200 GET /notebooks/hub/api/authorizations/token/[secret] (USERNAME@127.0.0.1) 6.76ms
jupyterhub[152822]: 10:53:31.766 - error: [ConfigProxy] Proxy error:  Error: connect EMFILE 127.0.0.1:35892 - Local (undefined:undefined)
jupyterhub[152822]: at internalConnect (net.js:858:16)
jupyterhub[152822]: at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
jupyterhub[152822]: at defaultTriggerAsyncIdScope (net.js:948:9)
jupyterhub[152822]: at processTicksAndRejections (internal/process/next_tick.js:74:9)
jupyterhub[152822]: 10:53:31.767 - error: [ConfigProxy] 503 GET /notebooks/user/USERNAME/static/base/images/favicon.ico
jupyterhub[152822]: 10:53:31.767 - error: [ConfigProxy] Failed to get custom error page Error: connect EMFILE 127.0.0.1:8081 - Local (undefined:undefined)
jupyterhub[152822]: at internalConnect (net.js:858:16)
jupyterhub[152822]: at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
jupyterhub[152822]: at defaultTriggerAsyncIdScope (net.js:948:9)
jupyterhub[152822]: at processTicksAndRejections (internal/process/next_tick.js:74:9)
jupyterhub[152822]: 10:53:31.768 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
jupyterhub[152822]: at ClientRequest.<anonymous> (/opt/conda/anaconda3/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
jupyterhub[152822]: at ClientRequest.emit (events.js:197:13)
jupyterhub[152822]: at Socket.socketErrorListener (_http_client.js:399:9)
jupyterhub[152822]: at Socket.emit (events.js:197:13)
jupyterhub[152822]: at emitErrorNT (internal/streams/destroy.js:82:8)
jupyterhub[152822]: at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
jupyterhub[152822]: at processTicksAndRejections (internal/process/next_tick.js:76:17)
jupyterhub[152822]: [I 2019-11-07 10:53:25.370 SingleUserNotebookApp log:122] 200 GET /notebooks/user/USERNAME/lab? (USERNAME@10.244.66.169) 17.57ms```

**Comment by ryogesh** [comment]
It may be due to timeout to spawn the container, default is 30s; try increasing to say 60s; also check your LB timeout.

**Comment by praveenkanamarlapudi** [comment]
It's not a containerized env. It's running on hosts. We are seeing this error frequently now a days.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
