### ISSUE TITLE
USING multiuser I got " NoJ SON object could be decoded"

### ISSUE THREAD

**Issue by jordi-vaquero** [jupyterhub/jupyterhub#282]
Hello everyone, 
first I would like to say that this project is really helpful. 
Lately I am trying to configure the servie to be used by all the users in our research lab, and I followed the steps for install and for the non-root configuration.
But when I try to log in I get the following error, 
```
E 2015-08-05 15:16:15.286 JupyterHub orm:376] Unhandled error starting jordi's server: No JSON object could be decoded
[E 2015-08-05 15:16:15.303 JupyterHub web:1496] Uncaught exception POST /hub/login?next= (165.123.89.213) HTTPServerRequest(protocol='http', host='naxos2:9995', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='165.123.89.213', headers={'Content-Length': '32', 'Cache-Control': 'max-age=0', 'Host': 'naxos2:9995', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.8,ca;q=0.6,es;q=0.4,it;q=0.2', 'Https': '1', 'X-Forwarded-For': '165.123.89.213', 'Referer': 'http://naxos2:9995/hub/login', 'X-Forwarded-Port': '9995', 'Content-Type': 'application/x-www-form-urlencoded', 'Connection': 'close', 'Origin': 'http://naxos2:9995', 'Cookie': 'username-naxos2-9999="2|1:0|10:1436995774|20:username-naxos2-9999|48:N2ZkNDNhNjQtZDczNC00YTFiLTgwYjAtZmQ2ZjZjNDJmYTkw|1880e7dccb1cfab6d12be0a8c178528f751120e64e61befea8f8f0b00c88fe6c"', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36'})

Traceback (most recent call last):
      File "/usr/local/lib/python3.3/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/usr/local/lib/python3.3/site-packages/jupyterhub/handlers/login.py", line 69, in post
        yield self.spawn_single_user(user)
      File "/usr/local/lib/python3.3/site-packages/jupyterhub/handlers/base.py", line 282, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.3/site-packages/jupyterhub/orm.py", line 386, in spawn
        raise e
      File "/usr/local/lib/python3.3/site-packages/jupyterhub/orm.py", line 367, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.3/site-packages/sudospawner/spawner.py", line 56, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.env)
      File "/usr/local/lib/python3.3/site-packages/sudospawner/spawner.py", line 48, in do
        return json.loads(data.decode('utf8'))
      File "/usr/local/lib/python3.3/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/local/lib/python3.3/json/decoder.py", line 352, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/lib/python3.3/json/decoder.py", line 370, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
```

Can you please point me out where the problem could be?

**Comment by minrk** [comment]
Unfortunately, no JSON is the main symptom of roughly anything going wrong in the sudospawner, which is proving super hard to make nicely debuggable. This is often a permission error.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
