### ISSUE TITLE
Installation error on Ubuntu 18.04 "python setup.py egg_info" fails with error code 1.

### ISSUE THREAD

**Issue by damon-chem-e** [jupyterhub/jupyterhub#2844]
When installing LittleJupyterHub on Ubuntu 18.04 I get the following error message (note that python3-dev, curl, python3, and git are all successfully installed. Anaconda is also installed):

(base) damon@kbd:~$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/boot                strap/bootstrap.py | sudo -E python3 - --admin damon
[sudo] password for damon:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Curren                t
                                 Dload  Upload   Total   Spent    Left  Speed
100  6354  100  6354    0     0  20832      0 --:--:-- --:--:-- --:--:-- 20764

Checking if TLJH is already installed...
Setting up hub environment
Installed python & virtual environment
Set up hub virtual environment
Setting up TLJH installer...
Ran /opt/tljh/hub/bin/pip install --upgrade git+https://github.com/jupyterhub/the-littlest-jupyterhub.git with exit code 1
The directory '/home/damon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/damon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/jupyterhub/the-littlest-jupyterhub.git
  Cloning https://github.com/jupyterhub/the-littlest-jupyterhub.git to /tmp/pip-ctmyoqoq-build
Collecting backoff (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/f0/32/c5dd4f4b0746e9ec05ace2a5045c1fc375ae67ee94355344ad6c7005fd87/backoff-1.10.0-py2.py3-none-any.whl
Collecting jinja2 (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125kB)
Collecting jupyterhub-traefik-proxy==0.1.* (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/ef/da/86150770ed3f745877b6c1fae25a1b633ae3865de35deab8af3bb369b50b/jupyterhub_traefik_proxy-0.1.4-py3-none-any.whl
Collecting passlib (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/11/b8/e9a78f3033228013ba8564adad8d0031bf9d39ea3acc3cdb9d55fabeb4ba/passlib-1.7.2-py2.py3-none-any.whl (507kB)
Collecting pluggy>0.7<1.0 (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting requests (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting ruamel.yaml==0.15.* (from the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/e7/9f/83bb34eaf84032b0b54fcc4a6aff1858572d279d65a301c7ae875f523df5/ruamel.yaml-0.15.100-cp36-cp36m-manylinux1_x86_64.whl (656kB)
Collecting MarkupSafe>=0.23 (from jinja2->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting jupyterhub>=0.9 (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/0d/67/c1e7d691bcb635fcde61c544d8fbca1edebb7bb4f68f34f5de291eba02d0/jupyterhub-1.0.0-py3-none-any.whl (3.2MB)
Collecting escapism (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/d2/28/0f93611a7b8f50a5d22a576af9fe06af32abe5e2c47f09f64e39f8ea6dc3/escapism-1.0.0-py2.py3-none-any.whl
Collecting toml (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting aiohttp (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
Collecting python-consul (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/3f/d0/59bc5f1c6c4d4b498c41d8ce7052ee9e9d68be19e16038a55252018a6c4d/python_consul-1.1.0-py2.py3-none-any.whl
Collecting etcd3 (from jupyterhub-traefik-proxy==0.1.*->the-littlest-jupyterhub==0.1)
  Downloading https://files.pythonhosted.org/packages/a6/99/c3ae7544f75067192c490f817b9440acbe32dda1f7e9c27b19c1e85c46e3/etcd3-0.11.0.tar.gz (61kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a28u58y7/etcd3/setup.py", line 23, in <module>
        requirements = load_reqs('requirements/base.txt')
      File "/tmp/pip-build-a28u58y7/etcd3/setup.py", line 16, in load_reqs
        with open(filename) as reqs_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/base.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a28u58y7/etcd3/

Traceback (most recent call last):
  File "<stdin>", line 174, in <module>
  File "<stdin>", line 159, in main
  File "<stdin>", line 56, in run_subprocess
subprocess.CalledProcessError: Command '['/opt/tljh/hub/bin/pip', 'install', '--upgrade', 'git+https://github.com/jupyterhub/the-littlest-jupyterhub.git']' returned non-zero exit status 1.

**Comment by AndisDraguns** [comment]
Seems like etcd3 0.11.0 is broken: https://github.com/kragniz/python-etcd3/issues/952.
A workaround for TLJH that worked for me was to modify the bootstrap.py file and install etcd3 0.10.0 and other requirements manually.

Get the bootstrap.py and modify it:
```
sudo apt install python3 python3-dev git curl
cd /tmp
curl -O https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py
nano bootstrap.py
```

Set `pip_flags = ['--no-deps']` and CTRL+O; ENTER; CTRL+X to write and exit.

Now start the installer to get TLJH folders:
`sudo -E python3 bootstrap.py --admin user1`

After it fails, manually install the packages:
```
sudo -E /opt/tljh/hub/bin/pip install --upgrade ruamel.yaml==0.15.*
sudo -E /opt/tljh/hub/bin/pip install --upgrade jinja2
sudo -E /opt/tljh/hub/bin/pip install --upgrade pluggy==0.9
sudo -E /opt/tljh/hub/bin/pip install --upgrade passlib
sudo -E /opt/tljh/hub/bin/pip install --upgrade backoff
sudo -E /opt/tljh/hub/bin/pip install --upgrade requests
sudo -E /opt/tljh/hub/bin/pip install etcd3==0.10.0
sudo -E /opt/tljh/hub/bin/pip install jupyterhub-traefik-proxy==0.1.*
```

And now, the installation should finish successfully:
`sudo -E python3 bootstrap.py --admin user1`
