### ISSUE TITLE
Trying to spawn notebook server, but isn't working

### ISSUE THREAD

**Issue by AV-Coding** [jupyterhub/jupyterhub#2883]
Hello, I'm trying to launch jupyterHub on a VM. I used `pip` to install jupyterhub. The command I use to start jupyterhub is `sudo jupyterhub` and I call it in `/etc/jupyterhub`. This is the location of my configuration file. When I launch Jupyterhub and sign in on the browser to spawn a notebook server, it's fine.The user that I sign in with, exists on the VM. However, when I try to sign in with an account that doesn't exist on the VM, I get the following error(I'm using dummyauthenticaor for the authenication service):

Couldn't set CWD to /home/jjpalanca ([Errno 2] No such file or directory: '/home/jjpalanca')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/singleuser.py", line 660, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/singleuser.py", line 558, in initialize
    return super().initialize(argv)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1717, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1372, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jjpalanca'

From what I understand, my config file/ the authentication service should handle a situation where the user doesn't exist, so I don't understand why it isn't spawning the notebook server. Any help would be greatly appreciated.

This is my config file:
c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'

#c.Spawner.notebook_dir = '/home/arielv/spawners/terrainSpawner/notebooks'
c.Spawner.notebook_dir = '/etc/jupyterhub/notebooks'

from jupyterhub.spawner import LocalProcessSpawner
#import jupyterhub.app

from traitlets import default
import shlex
import getpass
import pprint
import requests
import pipes
from tornado.ioloop import PeriodicCallback
from subprocess import Popen

#token=jupyterhub.app.terrain_token
class TerrainSpawner(LocalProcessSpawner):
    @default('options_form')
    def _options_form(self):
        default_env = "YourName=%s\n" % self.user.name
        return """
        <label for="args">Extra notebool CLI aruments</label>
        <input name="args" placeholde="e.g. --debug"></input>
        """.format(env=default_env)

    def options_from_form(self, formdata):
        """Turn html formdata (always lists of strings) into the dict we want."""
        options = {}
        arg_s = formdata.get('args', [''])[0].strip()
        if arg_s:
            options['argv'] = shlex.split(arg_s)
        #print("This is the new token value that we need:" + jupyterhub.app.terrain_token)
        return options

    def get_args(self):
        """Return arguments to pass to the notebook server"""
        argv = super().get_args()
        if self.user_options.get('argv'):
            argv.extend(self.user_options['argv'])
        return argv

    def get_env(self):
        """Return environment variable dict"""
        env = super().get_env()
        return env
c.JupyterHub.spawner_class = TerrainSpawner

c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'

c.DummyAuthenticator.password = "password"

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
