### ISSUE TITLE
ModuleNotFoundError: No module named 'async_generator' with LocalProcessSpawner in a docker container

### ISSUE THREAD

**Issue by Nithanaroy** [jupyterhub/jupyterhub#2902]
I get `ModuleNotFoundError: No module named 'async_generator'` when I try to login using an existing user in my docker container with SimpleLocalProcessSpawner or LocalProcessSpawner

**jupyter_config.py**
```python
from jupyterhub.auth import Authenticator
from jupyterhub.utils import hash_token, compare_token
# from dockerspawner import DockerSpawner
import os
import sys, traceback

class PasswordOnlyForRootAuthenticator(Authenticator):
    def authenticate(self, handler, data):
        try:
            username, password = data['username'], data['password']
            actual_password = hash_token(os.environ.get("HUB_ROOT_PASSWORD"))

            if username in c.Authenticator.admin_users:
                if compare_token(actual_password, password):
                    return username
                else:
                    return None
            return username
        except:
            traceback.print_exc(file=sys.stdout)

c.JupyterHub.authenticator_class = PasswordOnlyForRootAuthenticator
# c.JupyterHub.spawner_class = DockerSpawner
c.JupyterHub.spawner_class = 'jupyterhub.spawner.SimpleLocalProcessSpawner'

import netifaces
docker0 = netifaces.ifaddresses('eth0')
docker0_ipv4 = docker0[netifaces.AF_INET][0]
c.JupyterHub.hub_ip = docker0_ipv4['addr']
```

**Error**
```
[I 2020-01-18 07:14:56.324 JupyterHub base:707] User logged in: test
[I 2020-01-18 07:14:56.330 JupyterHub log:174] 302 POST /hub/login?next= -> /hub/spawn (test@172.17.0.1) 42.08ms
[I 2020-01-18 07:14:56.396 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=35683
Traceback (most recent call last):
  File "/export/apps/python/3.6.1/bin/jupyterhub-singleuser", line 7, in <module>
    from jupyterhub.singleuser import main
  File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 52, in <module>
    from .services.auth import HubOAuth, HubOAuthenticated, HubOAuthCallbackHandler
  File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/services/auth.py", line 40, in <module>
    from ..utils import url_path_join
  File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/utils.py", line 23, in <module>
    from async_generator import aclosing
ModuleNotFoundError: No module named 'async_generator'
[I 2020-01-18 07:14:57.357 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/test (test@172.17.0.1) 1016.61ms
[I 2020-01-18 07:14:57.376 JupyterHub pages:347] test is pending spawn
[I 2020-01-18 07:14:57.387 JupyterHub log:174] 200 GET /hub/spawn-pending/test (test@172.17.0.1) 17.97ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for test may contain details.)
[W 2020-01-18 07:15:24.128 JupyterHub user:692] test's server never showed up at http://127.0.0.1:35683/user/test/ after 30 seconds. Giving up
[E 2020-01-18 07:15:24.172 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError("Server at http://127.0.0.1:35683/user/test/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/user.py", line 668, in spawn
        await self._wait_up(spawner)
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/user.py", line 715, in _wait_up
        raise e
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/user.py", line 683, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/export/apps/python/3.6.1/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:35683/user/test/ didn't respond in 30 seconds
```

**Comment by consideRatio** [comment]
Does this work with jupyterhub 1.0.0 but not with 1.1.0?

What version of JH is this?

**Comment by Nithanaroy** [comment]
I tried with 1.1.0, 1.0.0 and 0.9.0 and it the same error in all. I'm using Python 3.6.1.

In a centos 7 docker container with root user I start the hub,
```bash
jupyterhub --ip 0.0.0.0 --port 8888
```
with the above jupyterhub config.

**Comment by Nithanaroy** [comment]
Installed jupyterhub 1.0.0 with conda and `LocalProcessSpawner` works with existing users on the machine. Is there any process spawner which works for new users as well to be used in production?
