### ISSUE TITLE
Connection Refused When Launching Without Proxy

### ISSUE THREAD

**Issue by mjstroud** [jupyterhub/jupyterhub#2912]
I am attempting to start JupyterHub independent of the configurable-http-proxy, and am failing. When I start the hub with the proxy I have no issues, however when I disable it using the configuration options recommended here [https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html](https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html), I am getting the following error.
```
>> jupyterhub -f /etc/jupyterhub/jupyterhub_new_config.py
[I 2020-01-28 10:25:36.795 JupyterHub app:2240] Running JupyterHub version 1.1.0
[I 2020-01-28 10:25:36.796 JupyterHub app:2271] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.1.0
[I 2020-01-28 10:25:36.796 JupyterHub app:2271] Using Spawner: wrapspawner.wrapspawner.ProfilesSpawner
[I 2020-01-28 10:25:36.796 JupyterHub app:2271] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.1.0
[I 2020-01-28 10:25:36.798 JupyterHub app:1349] Loading cookie_secret from /var/log/jupyterhub/jhub/jupyterhub_cookie_secret
[I 2020-01-28 10:25:36.847 JupyterHub app:1655] Not using whitelist. Any authenticated user will be allowed.
10
[I 2020-01-28 10:25:36.865 JupyterHub app:2311] Initialized 0 spawners in 0.004 seconds
[I 2020-01-28 10:25:36.867 JupyterHub app:2520] Not starting proxy
[E 2020-01-28 10:25:36.873 JupyterHub app:2718]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 2716, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 2524, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 806, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 774, in api_request
        result = await client.fetch(req)
    ConnectionRefusedError: [Errno 111] Connection refused
```
Most of the other configuration is default with the exception of my wrapspawner configuration to work with a backend Slurm cluster.

Any help here would be appreciated.

**Comment by manics** [comment]
@mjstroud Have you already started the configurable-http-proxy separately? Or are you running a diffferent proxy?

**Comment by mjstroud** [comment]
I am using the configurable-http-proxy. And yes starting it first worked. My faulty assumption here was that the two could be up or down independently, but without the proxy users simply wouldn't be able to connect. Thanks for your help.
