### ISSUE TITLE
Permission issue jupyterhub :error no 13 Permission denied git

### ISSUE THREAD

**Issue by heyitsaakash** [jupyterhub/jupyterhub#2921]
Hi i am using nbgitpuller in jupyter hub to fetch certain notebooks in public git repositories.

Also, I am using github authentication it is working fine.

When i am trying to hit the url below (formed from nbgitpuller link)

http://ec2-xx.-xx-xx.compute-1.amazonaws.com:8000/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fxxxakash%2Fsagemaker-experiment&urlpath=tree%2Fexperiment%2FUntitled.ipynb&branch=master

I am getting an exception that is related to permission. I also changed the permission using chmod 777 of the user's directory /home/aakash in my case still it is not resolving.
Traceback (most recent call last):
File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/nbgitpuller/handlers.py", line 85, in pull
raise e
File "/usr/local/lib/python3.7/site-packages/nbgitpuller/handlers.py", line 79, in pull
for line in gp.pull():
File "/usr/local/lib/python3.7/site-packages/nbgitpuller/pull.py", line 79, in pull
yield from self.initialize_repo()
File "/usr/local/lib/python3.7/site-packages/nbgitpuller/pull.py", line 93, in initialize_repo
yield from execute_cmd(clone_args)
File "/usr/local/lib/python3.7/site-packages/nbgitpuller/pull.py", line 19, in execute_cmd
proc = subprocess.Popen(cmd, **kwargs)
File "/usr/lib64/python3.7/subprocess.py", line 775, in init
restore_signals, start_new_session)
File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'git'

![image](https://user-images.githubusercontent.com/17155549/73744718-5e7aae00-4777-11ea-8489-5f8402501767.png)

**Comment by heyitsaakash** [comment]
closing it -  it was because i was'nt having git installed on unix box.
