### ISSUE TITLE
Getting SSL error on Redhat 7.1

### ISSUE THREAD

**Issue by michaelaye** [jupyterhub/jupyterhub#294]
I'm getting uncaught exception from SSL errors when trying to log in:

```bash
$ jupyterhub
[I 2015-08-31 14:58:46.852 JupyterHub app:518] Loading cookie_secret from /home/klay6683/jupyterhub_cookie_secret
[W 2015-08-31 14:58:46.898 JupyterHub app:257]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2015-08-31 14:58:46.908 JupyterHub app:654] Not using whitelist. Any authenticated user will be allowed.
[I 2015-08-31 14:58:46.922 JupyterHub app:1032] Hub API listening on http://localhost:8081/hub/
[I 2015-08-31 14:58:46.929 JupyterHub app:789] Starting proxy @ http://*:8000/
14:58:47.099 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
14:58:47.104 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-08-31 14:58:47.137 JupyterHub app:1055] JupyterHub is now running at http://localhost:8000/
[I 2015-08-31 14:58:52.264 JupyterHub log:100] 302 GET / (@10.247.20.68) 1.89ms
[I 2015-08-31 14:58:52.274 JupyterHub log:100] 302 GET /hub (@10.247.20.68) 0.54ms
[I 2015-08-31 14:58:52.322 JupyterHub log:100] 200 GET /hub/ (@10.247.20.68) 39.41ms
[I 2015-08-31 14:58:59.827 JupyterHub log:100] 302 GET / (@10.247.20.68) 1.14ms
[I 2015-08-31 14:58:59.829 JupyterHub log:100] 302 GET /hub (@10.247.20.68) 0.52ms
[I 2015-08-31 14:59:19.211 JupyterHub spawner:365] Spawning jupyterhub-singleuser --user=klay6683 --port=43815 --cookie-name=jupyter-hub-token-klay6683 --base-url=/user/klay6683 --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
Failed to set groups [Errno 1] Operation not permitted
/usr/local/python/miniconda/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
/usr/local/python/miniconda/lib/python3.4/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
[I 2015-08-31 14:59:20.202 klay6683 notebookapp:1061] Serving notebooks from local directory: /home/klay6683/src/iuvs/notebooks
[I 2015-08-31 14:59:20.202 klay6683 notebookapp:1061] 0 active kernels
[I 2015-08-31 14:59:20.202 klay6683 notebookapp:1061] The IPython Notebook is running at: https://localhost:43815/user/klay6683/
[I 2015-08-31 14:59:20.202 klay6683 notebookapp:1062] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2015-08-31 14:59:20.276 klay6683 iostream:1260] SSL Error on 10 ('::1', 40001, 0, 0): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:600)
[E 2015-08-31 14:59:20.277 klay6683 http1connection:702] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/python/miniconda/lib/python3.4/site-packages/tornado/iostream.py", line 1243, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/usr/local/python/miniconda/lib/python3.4/ssl.py", line 810, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:600)
```

Just in case it has something to do with how well the `npm` install went, I put the log of that install here:

```bash
[root@ringsvm klay6683]# npm install -g configurable-http-proxy
npm http GET https://registry.npmjs.org/configurable-http-proxy
npm http 200 https://registry.npmjs.org/configurable-http-proxy
npm http GET https://registry.npmjs.org/configurable-http-proxy/-/configurable-http-proxy-0.4.0.tgz
npm http 200 https://registry.npmjs.org/configurable-http-proxy/-/configurable-http-proxy-0.4.0.tgz
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/strftime
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/http-proxy
npm http 200 https://registry.npmjs.org/strftime
npm http 200 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/strftime/-/strftime-0.8.4.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-2.8.1.tgz
npm http 200 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/http-proxy/-/http-proxy-1.11.2.tgz
npm http 200 https://registry.npmjs.org/strftime/-/strftime-0.8.4.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.8.1.tgz
npm http 200 https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/http-proxy/-/http-proxy-1.11.2.tgz
npm http GET https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/eventemitter3
npm http GET https://registry.npmjs.org/requires-port
npm http 200 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
npm http 200 https://registry.npmjs.org/requires-port
npm http GET https://registry.npmjs.org/requires-port/-/requires-port-0.0.1.tgz
npm http 200 https://registry.npmjs.org/eventemitter3
npm http GET https://registry.npmjs.org/eventemitter3/-/eventemitter3-1.1.1.tgz
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/stack-trace
npm http 200 https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
npm http 200 https://registry.npmjs.org/requires-port/-/requires-port-0.0.1.tgz
npm http 200 https://registry.npmjs.org/eventemitter3/-/eventemitter3-1.1.1.tgz
npm http 200 https://registry.npmjs.org/cycle
npm http 200 https://registry.npmjs.org/isstream
npm http 200 https://registry.npmjs.org/eyes
npm http 200 https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz
npm http GET https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http GET https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.2.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.0.tgz
npm http 200 https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http GET https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz
npm http 200 https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz
npm http 200 https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.6.2.tgz
npm http 200 https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http 200 https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz
npm http 200 https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.0.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
/bin/configurable-http-proxy -> /lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy
npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
configurable-http-proxy@0.4.0 /lib/node_modules/configurable-http-proxy
├── strftime@0.8.4
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── http-proxy@1.11.2 (eventemitter3@1.1.1, requires-port@0.0.1)
└── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, colors@0.6.2, async@0.2.10, pkginfo@0.3.0)
```

My system is:
Red Hat Enterprise Linux Workstation release 7.1 (Maipo)
Python3 dist: Miniconda, all updates
Jupyterhub: via pip

**Comment by minrk** [comment]
When you run your single-user server, does it run with https?

**Comment by michaelaye** [comment]
I never did anything else than the `npm` install step and then executing `jupyterhub` as given above, so I'm guessing no? I didn't configure anything towards that. Unless it would pick up such things from an ipython nbserver setup?

**Comment by kashyapchhatbar** [comment]
I was kind of puzzled by these strange exceptions. 

For me, I was having another local notebook server already running whose configuration is in `$HOME/.jupyter`. The problem was I had set it up to use the same certificate but on different port, so I think jupyterhub (which is already on SSL using the SSL certificate) calls the singer-user server which in turn starts the process on SSL using the same old SSL certificate but on a different port was causing python SSL library to go haywire because it was already running.

When that was the case, I removed `$HOME/.jupyter` and stopped my local notebook server, restarted jupyterhub and it was sane again.

Hope it helps but I doubt that's the case for your exceptions...

**Comment by jimgoo** [comment]
I had the same issue and solved it by doing what @kashyapchhatbar said. +1!

**Comment by kkumer** [comment]
I had similar problem with same solution: normal jupyter server with configuration in `$HOME/.jupyter` using different certificate on different port and which was stopped at the time, but jupyterhub still refused to spawn a user server. It didn't raise error/exception, but just an endless stream of warnings
```
[W 2016-02-25 14:37:44.652 kkumer iostream:1276] SSL Error on 9 ('::1', 54498, 0, 0): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
```
delaying start of user server forever.

As soon as I moved `$HOME/.jupyter` away, everything was fine.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Comment by malej** [comment]
@kkumer @kashyapchhatbar  @jimgoo -- I'm running into the same issue as you've had here. What is your `jupyterhub_config.py` contain and where did you place these? Interestingly enough, without touching anything in the `.jupyter` directory my basic `jupyter notebook` now fails to connect with SSL error (I've had no issues with `jupyter notebook` itself before installing jupyterhub).

![screen shot 2017-02-08 at 6 40 03 pm](https://cloud.githubusercontent.com/assets/898974/22764070/0bd9c9e2-ee2e-11e6-9c84-f485af136d26.png)

**Comment by danielrychel** [comment]
I am currently experiencing the exact same problem and I think this should be the solution. How do I go about removing the `/.jupyter` file?

**Comment by willingc** [comment]
@danielrychel You should be able to delete the `.jupyter` directory using `rm -rf` on Linux for deleting a directory.
