### ISSUE TITLE
Docker: "Spawn failed: Server didn't respond in 30 seconds", can be fixed by pip install notebook in container

### ISSUE THREAD

**Issue by JulianAssmann** [jupyterhub/jupyterhub#3007]
### Bug description
When using jupyterhub with docker, the error "Spawn failed: Server didn't respond in 30 seconds" occurs when logging in as a user. This can be fixed by running 
`pip install notebook`
inside the docker container.

#### Expected behaviour
Spawning the user server without problems, as is the case after pip installing notebook in the docker container

### How to reproduce
1. `docker run -d -p 8000:8000 jupyterhub/jupyterhub`
2. `docker exec -it [container_id] /bin/sh`
3. (in docker container) `adduser test`
4. Open `http://localhost:8000/` in browser of host machine
5. Login as the newly created user
6. Wait and see the error

### Your personal set up

 - OS:
Ubuntu 19.04, Docker Version 19.03.8 (build afacb8b7f0)
 - Version:
Docker image [jupyterhub/jupyterhub:1.2](https://hub.docker.com/layers/jupyterhub/jupyterhub/1.2/images/sha256-caeee1788998dcf8ab25ba5cd97313941075571c86445a843ec8bc9cc09f2b32?context=explore)
 - Configuration:
See steps above

### Logs
These logs were aquired by running `docker logs -f [container_id]`:
```
[I 2020-03-31 10:47:31.372 JupyterHub app:2291] Running JupyterHub version 1.2.0dev
[I 2020-03-31 10:47:31.374 JupyterHub app:2322] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.2.0dev
[I 2020-03-31 10:47:31.374 JupyterHub app:2322] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.2.0dev
[I 2020-03-31 10:47:31.374 JupyterHub app:2322] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
[I 2020-03-31 10:47:31.388 JupyterHub app:1429] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2020-03-31 10:47:31.422 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2020-03-31 10:47:31.423 alembic.runtime.migration migration:162] Will assume non-transactional DDL.
[I 2020-03-31 10:47:31.433 alembic.runtime.migration migration:515] Running stamp_revision  -> 4dc2d5a8c53c
[I 2020-03-31 10:47:31.496 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2020-03-31 10:47:31.498 JupyterHub app:1659] No admin users, admin interface will be unavailable.
[W 2020-03-31 10:47:31.498 JupyterHub app:1661] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2020-03-31 10:47:31.498 JupyterHub app:1690] Not using whitelist. Any authenticated user will be allowed.
[I 2020-03-31 10:47:31.568 JupyterHub app:2362] Initialized 0 spawners in 0.003 seconds
[W 2020-03-31 10:47:31.573 JupyterHub proxy:643] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2020-03-31 10:47:31.573 JupyterHub proxy:646] Starting proxy @ http://:8000
10:47:32.538 [ConfigProxy] info: Proxying http://*:8000 to (no default)
10:47:32.544 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
10:47:32.699 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-31 10:47:32.701 JupyterHub app:2607] Hub API listening on http://127.0.0.1:8081/hub/
10:47:32.703 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-31 10:47:32.703 JupyterHub proxy:320] Checking routes
[I 2020-03-31 10:47:32.703 JupyterHub proxy:400] Adding default route for Hub: / => http://127.0.0.1:8081
10:47:32.706 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
10:47:32.707 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
10:47:32.708 [ConfigProxy] info: 201 POST /api/routes/ 
[I 2020-03-31 10:47:32.709 JupyterHub app:2682] JupyterHub is now running at http://:8000
[I 2020-03-31 10:47:36.437 JupyterHub log:178] 302 GET /user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 -> /hub/user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 (@::ffff:172.17.0.1) 1.86ms
[I 2020-03-31 10:48:09.422 JupyterHub log:178] 302 GET /user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 -> /hub/user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 (@::ffff:172.17.0.1) 1.42ms
[I 2020-03-31 10:49:01.550 JupyterHub log:178] 302 GET / -> /hub/ (@::ffff:172.17.0.1) 5.20ms
[W 2020-03-31 10:49:01.581 JupyterHub base:392] Invalid or expired cookie token
[I 2020-03-31 10:49:01.582 JupyterHub log:178] 302 GET /hub/ -> /hub/login (@::ffff:172.17.0.1) 2.52ms
[I 2020-03-31 10:49:01.672 JupyterHub log:178] 200 GET /hub/login (@::ffff:172.17.0.1) 79.89ms
[I 2020-03-31 10:49:03.750 JupyterHub base:707] User logged in: julian
[I 2020-03-31 10:49:03.756 JupyterHub log:178] 302 POST /hub/login?next= -> /hub/spawn (julian@::ffff:172.17.0.1) 82.06ms
[W 2020-03-31 10:49:03.849 JupyterHub auth:956] Failed to open PAM session for julian: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2020-03-31 10:49:03.849 JupyterHub auth:957] Disabling PAM sessions from now on.
[I 2020-03-31 10:49:03.862 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=46655
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/singleuser.py", line 24, in <module>
    import notebook
ModuleNotFoundError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/singleuser.py", line 26, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[I 2020-03-31 10:49:04.776 JupyterHub log:178] 302 GET /hub/spawn -> /hub/spawn-pending/julian (julian@::ffff:172.17.0.1) 1013.83ms
[I 2020-03-31 10:49:04.789 JupyterHub pages:367] julian is pending spawn
[I 2020-03-31 10:49:04.800 JupyterHub log:178] 200 GET /hub/spawn-pending/julian (julian@::ffff:172.17.0.1) 15.83ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:741> exception=HTTPError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
    timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
    % (status, spawner._log_name),
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for julian may contain details.)
[I 2020-03-31 10:49:14.418 JupyterHub log:178] 302 GET /user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 -> /hub/user/julian/api/kernels/c09fe6f1-9b63-40e1-b150-54501725f922/channels?session_id=8e7d4886817d4bbf8a7dd9f1b64ad4f5 (@::ffff:172.17.0.1) 1.46ms
[W 2020-03-31 10:49:31.427 JupyterHub user:692] julian's server never showed up at http://127.0.0.1:46655/user/julian/ after 30 seconds. Giving up
[E 2020-03-31 10:49:31.463 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError("Server at http://127.0.0.1:46655/user/julian/ didn't respond in 30 seconds",)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 593, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 668, in spawn
        await self._wait_up(spawner)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 715, in _wait_up
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 683, in _wait_up
        http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
        timeout=timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 177, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://127.0.0.1:46655/user/julian/ didn't respond in 30 seconds
    
[I 2020-03-31 10:49:31.467 JupyterHub log:178] 200 GET /hub/api/users/julian/server/progress (julian@::ffff:172.17.0.1) 26471.31ms
```

**Comment by fvanmaele** [comment]
Note: we followed the instructions in https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html to get started, and didn't expect the installation of additional packages was required for testing basic functionality.

**Comment by manics** [comment]
https://jupyterhub.readthedocs.io/en/stable/quickstart-docker.html is quite confusing for a quickstart:
> This jupyterhub/jupyterhub docker image is only an image for running the Hub service itself. It does not provide the other Jupyter components, such as Notebook installation, which are needed by the single-user servers. To run the single-user servers, which may be on the same system as the Hub or not, Jupyter Notebook version 4 or greater must be installed.

We could do one of
- delete that docs page since it's not a quickstart
- provide full instructions for configuring JupyterHub in docker with [`DockerSpawner`](https://github.com/jupyterhub/dockerspawner/), perhaps with docker-compose?

What does everyone else think?

**Comment by GeorgianaElena** [comment]
@manics, I found 2 similar discussions about what approach should be taken about the jupyterhub Docker image:
* https://github.com/jupyterhub/jupyterhub/pull/915
* https://github.com/jupyterhub/jupyterhub/issues/2503

Combining all of these together, I believe we could:
* provide a quickstart docker image with dummy auth and simple spawner
* provide full instructions for configuring JupyterHub in docker with DockerSpawner, perhaps with docker-compose? (or reference the https://github.com/jupyterhub/jupyterhub-deploy-docker docs)

What do you think?

**Comment by manics** [comment]
Having a quickstart self-contained Docker image sounds good, just wondering if there are any security issues to be aware of when setting the defaults? E.g. "just works as a demo with no config needed" vs "minimal explicit config needed".

I'm in favour or not duplicating docs if possible, so how about one of
- make https://github.com/jupyterhub/jupyterhub-deploy-docker the single place for production JupyterHub Docker instructions (I wasn't aware we had that repo! Though it hasn't been updated for over a year)
- archive `jupyterhub-deploy-docker` and copy its contents to a subdirectory of another repo, e.g. DockerSpawner?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-extension-manager-on-jupyterhub-for-individual-users/4467/5

**Comment by 1kastner** [comment]
I guess "production environment" might be something very different depending on the use case. The JupyterHub could serve as an interface to a company/institution cluster (for known and trusted employees) or it could serve as a shortcut to avoid installations in a seminar or exam setting (semi-trusted). The latter was the situation I had in mind when [creating this config](https://collaborating.tuhh.de/cmk3624/minimal-jupyterhub-docker-config). By telling this, I mean that configurations are quite use-case specific even if they don't contain specific information (such as URLs etc.).

@manics I guess under any circumstance we need a docker-compose file or something that could do the same job, since docker-in-docker is generally a tricky subject. I guess especially for the semi-trusted or untrusted version, there are a lots of caveats, since the internet is full with warnings about that docker is not meant to securely isolate users from each other if they actively try to break out of their systems.

**Comment by manics** [comment]
@1kastner My understanding of the current "quick-start" is that you'd run JupyterHub in Docker with the default Spawner so all singleuser servers are inside the same Docker container. However I think getting rid of that "quick-start" completely and instead recommending a docker-compose.yml with Docker-in-Docker is reasonable and reduces the duplication and maintenance required for the docs.

Does anyone else have a preference?

**Comment by minrk** [comment]
@GeorgianaElena's plan sounds perfect to me.

Adding the notebook package also isn't enough, since without further configuration to create user accounts, you won't be able to login.

running a whole hub and users in one container doesn't make a lot of sense, and requires quite a bit of configuration (non-default Authenticators, Spawners, user creation, etc.). So if we update `jupyterhub/jupyterhub` to include the notebook package, then the result is really that we've created an image people shouldn't use. It's not really possible to create an image for jupyterhub that's useful in realistic scenarios without requiring extension by the user for their own deployment. The same is true, for example, of other server tools like nginx - you have to give it configuration in order for it to be useful.

We could have an all-in-one container just for demo purposes that uses dummy auth and dummy spawner, but I don't think it should be the default image, since nobody should use it that way except to quickly check out what jupyterhub is.

I wanted jupyterhub-deploy-docker to be exactly this example best practice, base deployment of jupyterhub on docker, and reviving `jupyterhub-deploy-docker` is perhaps the thing to do, but unfortunately that has grown too complicated as it has been expanded to try to serve too many use cases via configuration. We should probably start over and try to do less.

So my preference would probably be (adding some detail to @GeorgianaElena's proposal):

1. maintain jupyterhub/jupyterhub as a sensible base image, assuming best practice of users outside the image (as with DockerSpawner, KubeSpawner, etc.)
2. maintain explicitly minimal best-practice docker-compose (possibly reviving jupyterhub-deploy-docker) with:
  - DockerSpawner
  - proxy in separate container
  - (this is where it gets complicated) oauth...?
  - (maybe) database in separate container
3. if folks find it useful, which seems to be the case, build new `jupyterhub-demo` image with:
  - notebook requirements
  - simplespawner
  - dummyauth
  This should not be used for any purposes other than quickly checking out what jupyterhub is. It shouldn't be a base image for anyone to build on.

**Comment by mianasbat** [comment]
For quick deployment and testing, I followed the process docker deployment and got the same spawn error. I remember using R server which works in a way that will allow system users to login from front-end though it wasnt docker deployment but I think docker will do the same. 

So probably the question is do you have a tutorial where I can quickly deploy it and test it see if it is useful for achieving our objective?

**Comment by 0t3dWCE** [comment]
As you can read from logs:
`ModuleNotFoundError: No module named 'notebook'`

navagate to container:

`$ docker exec -it jupiterhub`

install missed packages:

`# pip3 install notebook`
`# pip3 install jupiterlab`

Now you will able to spawn server inside container via web interface.

**Comment by mariusmathisen** [comment]
@0t3dWCE A typo - should be jupyter not jupiter  :)

**Comment by Frenzoid** [comment]
Just ran into this same issue, i cant believe that 2 years later, noone has pull requested the missing libraries into the Dockerfile.

Missing pip libraries: notebook, jupyter.

PR related: https://github.com/jupyterhub/jupyterhub/pull/4412

**Comment by amirhosseinkabiri** [comment]
pooof! I just solved this crazy problem. I used to login with root user and even installed the anaconda using root user in /root directory. but when I used another VM, created another user name condauser, installed the anaconda with that user, every thing works fine. 
remind that you should run the jupyterhub with root user but use that recently created user to login.

**Comment by hersh006** [comment]
In 2024 I think this is still an issue. 

Not an expert in docker (for example my docker is configured such that I have to run it as root :-() or much else for that matter but I followed the instructions here:
https://jupyterhub.readthedocs.io/en/stable/tutorial/quickstart-docker.html

#From the command line
#start jupyterhub on docker
sudo docker run -d -p 8000:8000 --name jupyterhub quay.io/jupyterhub/jupyterhub jupyterhub

#spawn a root shell
sudo docker exec -it jupyterhub bash

#add a test user for testing
adduser test

#Jupyterlab doesn't work
#check the logs
# find the container id 
sudo docker ps 
433e923091f5

docker logs -f 433e923091f5
#jupyter_core is not installed
python3 -m pip install notebook

#Now it works

Am I doing something wrong? I thought maybe I am looking at the docs for the wrong version, but it seems to be the latest.

As was observed 4 years ago, I'm not sure that tutorial is the right term for these documents collectively? I found the instructions to be very hard to follow.
