### ISSUE TITLE
docs: `jupyter troubleshooting` does not exist

### ISSUE THREAD

**Issue by mriedem** [jupyterhub/jupyterhub#3119]
### Bug description
This page [1] says you can run the `jupyter troubleshooting` command to get information about the deployment. However, that command does not exist. But `jupyterhub troubleshooting` does:

```
jovyan@hub-7bbcd57db8-t2cr6:/$ which jupyter
jovyan@hub-7bbcd57db8-t2cr6:/$ which jupyterhub
/usr/local/bin/jupyterhub
jovyan@hub-7bbcd57db8-t2cr6:/$ jupyterhub troubleshooting
[I 2020-07-21 14:50:23.652 JupyterHub app:2295] Running JupyterHub version 1.2.0dev
[I 2020-07-21 14:50:23.653 JupyterHub app:2326] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.2.0dev
[I 2020-07-21 14:50:23.654 JupyterHub app:2326] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.2.0dev
[I 2020-07-21 14:50:23.654 JupyterHub app:2326] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
[I 2020-07-21 14:50:23.665 JupyterHub app:1384] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[E 2020-07-21 14:50:23.672 JupyterHub app:1565] Failed to connect to db: sqlite:///jupyterhub.sqlite
[E 2020-07-21 14:50:23.674 JupyterHub app:1369] jovyan cannot create files in /
[C 2020-07-21 14:50:23.674 JupyterHub app:1574] If you recently upgraded JupyterHub, try running
        jupyterhub upgrade-db
    to upgrade your JupyterHub database schema
```

I'm not sure if that `jupyter troubleshooting` is a typo or if it used to exist, but it doesn't seem to work with jupyterhub at 8a3790b01ff944c453ffcc0486149e2a58ffabea.

I'm trying to figure out a command to dump the effective application settings when our hub is running to make sure that changes to the config are reflected properly in the application since I don't see any config option to dump the settings on hub startup. I figured maybe the `troubleshooting` sub-command could help do that (I'm also having a hard time figuring out where that sub-command is even defined within the jupyterhub code, but that's a different issue).

[1] https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#troubleshooting-commands

#### Expected behaviour
The docs should be accurate.

#### Actual behaviour
The docs are inaccurate, as far as I can tell anyway.

### How to reproduce
Run `jupyter troubleshooting` against your hub pod and you get an error:

```
jovyan@hub-7bbcd57db8-t2cr6:/$ jupyter troubleshooting
bash: jupyter: command not found
```

### Your personal set up
Using z2jh to deploy the hub and our hub image is using commit 8a3790b01ff944c453ffcc0486149e2a58ffabea.

**Comment by mriedem** [comment]
Maybe a separate issue, but I noticed that when I ran `jupyterhub troubleshooting` above it wasn't using our real config. When I provided the path to the config file, it tries to start the hub which is already running and fails:

```
jovyan@hub-7bbcd57db8-t2cr6:/$ jupyterhub -f /etc/jupyterhub/jupyterhub_config.py troubleshooting
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
Loading extra config: myConfig
[I 2020-07-21 15:05:41.982 JupyterHub app:2295] Running JupyterHub version 1.2.0dev
[I 2020-07-21 15:05:41.983 JupyterHub app:2326] Using Authenticator: jhub_qx_login.jhub_qx_login.QXUserAuthenticator
[I 2020-07-21 15:05:41.983 JupyterHub app:2326] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2020-07-21 15:05:41.983 JupyterHub app:2326] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
[I 2020-07-21 15:05:41.985 JupyterHub app:1384] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[D 2020-07-21 15:05:41.985 JupyterHub app:1555] Connecting to db: postgres+psycopg2://ibm_cloud_b13a5802_4570_44be_b036_cd92f5a585da:[redacted]@02053853-2fb7-4f89-85dc-b68dda58c98e.b8a5e798d2d04f2e860e54e5d042c915.databases.appdomain.cloud:31644/jhub_dev
[D 2020-07-21 15:05:42.207 JupyterHub orm:763] database schema version found: 4dc2d5a8c53c
[W 2020-07-21 15:05:42.317 JupyterHub app:1618] JupyterHub.hub_connect_port is deprecated as of 0.9. Use JupyterHub.hub_connect_url to fully specify the URL for connecting to the Hub.
[I 2020-07-21 15:05:42.401 JupyterHub app:1694] Not using whitelist. Any authenticated user will be allowed.
1
[D 2020-07-21 15:05:42.554 JupyterHub app:1959] Initializing spawners
[D 2020-07-21 15:05:42.571 JupyterHub app:2092] Loaded users:
    
[I 2020-07-21 15:05:42.571 JupyterHub app:2366] Initialized 0 spawners in 0.018 seconds
[I 2020-07-21 15:05:42.603 JupyterHub app:2575] Not starting proxy
[D 2020-07-21 15:05:42.604 JupyterHub proxy:766] Proxy: Fetching GET http://172.21.34.247:8001/api/routes
[E 2020-07-21 15:05:42.606 JupyterHub app:2615] Failed to bind hub to http://0.0.0.0:8081/hub/
[E 2020-07-21 15:05:42.606 JupyterHub app:2773]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2771, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2610, in start
        self.http_server.listen(port, address=ip)
      File "/usr/local/lib/python3.6/dist-packages/tornado/tcpserver.py", line 151, in listen
        sockets = bind_sockets(port, address=address)
      File "/usr/local/lib/python3.6/dist-packages/tornado/netutil.py", line 174, in bind_sockets
        sock.bind(sockaddr)
    OSError: [Errno 98] Address already in use
    
[D 2020-07-21 15:05:42.607 JupyterHub application:653] Exiting application: jupyterhub
```

My guess here is that the `troubleshooting` sub-command isn't being honored / doesn't exist, which would explain why I can't find it in the actual jupyterhub source code.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/is-there-a-way-to-dump-hub-app-settings-config/5305/1
