### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by srichakradhar** [jupyterhub/jupyterhub#3138]
### Bug description

I'm not able to run JupyterHub on Windows after installing with pip. 

#### Expected behaviour

jupyterhub should run the first time setup and allow connecting to server on http://localhost:8000

#### Actual behaviour

when run using `python -m jupyterhub`, I get
```sh
[I 2020-08-09 00:05:13.702 JupyterHub app:2240] Running JupyterHub version 1.1.0
[I 2020-08-09 00:05:13.702 JupyterHub app:2270] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.1.0
[I 2020-08-09 00:05:13.703 JupyterHub app:2270] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.1.0
[I 2020-08-09 00:05:13.703 JupyterHub app:2270] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.1.0
[I 2020-08-09 00:05:13.710 JupyterHub app:1394] Writing cookie_secret to C:\Users\Sri\jupyterhub_cookie_secret
[I 2020-08-09 00:05:13.776 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2020-08-09 00:05:13.777 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[I 2020-08-09 00:05:13.809 alembic.runtime.migration migration:515] Running stamp_revision  -> 4dc2d5a8c53c
[I 2020-08-09 00:05:14.266 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
[E 2020-08-09 00:05:14.268 JupyterHub app:2718]
    Traceback (most recent call last):
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\app.py", line 2715, in launch_instance_async
        await self.initialize(argv)
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\app.py", line 2286, in initialize
        await self.init_users()
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\app.py", line 1597, in init_users
        if self.authenticator.enable_auth_state:
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\app.py", line 918, in _authenticator_default
        return self.authenticator_class(parent=self, db=self.db)
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\auth.py", line 863, in __init__
        raise _pamela_error from None
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\jupyterhub\auth.py", line 16, in <module>
        import pamela
      File "C:\Users\Sri\AppData\Roaming\Python\Python38\site-packages\pamela.py", line 49, in <module>
        LIBPAM = CDLL(find_library("pam"))
      File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 363, in __init__
        if '/' in name or '\\' in name:
    TypeError: argument of type 'NoneType' is not iterable
```
### How to reproduce

1. `pip install jupyterhub`
2. `python -m jupyterhub`
3. See error

### Your personal set up

 - OS:
 
Windows 10
 - Version:
 
Python 3.8.2
 - Configuration:

**Comment by consideRatio** [comment]
There will be a executable script installed called jupyterhub, what happens if you run that? It may or may not be on your path depending on how you have installed your python.

**Comment by GeorgianaElena** [comment]
Hi @srichakradhar :wave: This sounds like an installation or configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ ? Thanks!

**Comment by lcnittl** [comment]
Were you able to resolve this @srichakradhar ? I have the same problem here on Windows. Not sure how anyone could do anything wrong on a pip install

**Comment by dancebean** [comment]
I have encountered the same problem. Seems to do with the pamela module, which was created by the jupyterlab team as well

**Comment by minrk** [comment]
JupyterHub doesn't officially support Windows, and the default authenticator and spawner do not work on Windows. The default PAM Authenticator uses libpam a \*ix library, which is why this fails. You _can_ unofficially use JupyterHub with a non-default authenticator and spawner, such as oauth + docker.
