### ISSUE TITLE
jupyterhub 1.2: Error in Authenticator.pre_spawn_start

### ISSUE THREAD

**Issue by hdlbq** [jupyterhub/jupyterhub#3182]
### Bug description
I started the jupyterhub, tried to connect myself. Sometimes, it fails with this error:
tornado.web.HTTPError: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: RuntimeError Service jupyter-username not found)

 - OS:
Debian GNU/Linux 9.12 (stretch)
 - Version:
 JupyterHub 1.2.0dev 20200918085642
Using Authenticator: jhub_cas_authenticator.cas_auth.CASAuthenticator
Using Spawner: dockerspawner.swarmspawner.SwarmSpawner-0.11.1
Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
- log joined:
```
[I 2020-09-18 08:56:42.139 JupyterHub app:2331] Running JupyterHub version 1.2.0dev
[I 2020-09-18 08:56:42.140 JupyterHub app:2361] Using Authenticator: jhub_cas_authenticator.cas_auth.CASAuthenticator
[I 2020-09-18 08:56:42.140 JupyterHub app:2361] Using Spawner: dockerspawner.swarmspawner.SwarmSpawner-0.11.1
[I 2020-09-18 08:56:42.140 JupyterHub app:2361] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0dev
[D 2020-09-18 08:56:42.149 JupyterHub app:1451] Generating new cookie_secret
[I 2020-09-18 08:56:42.149 JupyterHub app:1456] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[D 2020-09-18 08:56:42.149 JupyterHub app:1578] Connecting to db: sqlite:///jupyterhub.sqlite
[D 2020-09-18 08:56:42.163 JupyterHub orm:784] Stamping empty database with alembic revision 4dc2d5a8c53c
[I 2020-09-18 08:56:42.167 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2020-09-18 08:56:42.167 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[I 2020-09-18 08:56:42.191 alembic.runtime.migration migration:515] Running stamp_revision  -> 4dc2d5a8c53c
[D 2020-09-18 08:56:42.191 alembic.runtime.migration migration:725] new branch insert 4dc2d5a8c53c
[I 2020-09-18 08:56:42.425 JupyterHub proxy:461] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2020-09-18 08:56:42.455 JupyterHub app:1716] Not using allowed_users. Any authenticated user will be allowed.
[D 2020-09-18 08:56:42.498 JupyterHub app:1868] Purging expired APITokens
[D 2020-09-18 08:56:42.500 JupyterHub app:1868] Purging expired OAuthAccessTokens
[D 2020-09-18 08:56:42.502 JupyterHub app:1868] Purging expired OAuthCodes
[D 2020-09-18 08:56:42.512 JupyterHub app:1995] Initializing spawners
[D 2020-09-18 08:56:42.513 JupyterHub app:2128] Loaded users:
    
[I 2020-09-18 08:56:42.514 JupyterHub app:2398] Initialized 0 spawners in 0.002 seconds
[W 2020-09-18 08:56:42.516 JupyterHub proxy:642] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2020-09-18 08:56:42.517 JupyterHub proxy:646] Starting proxy @ http://0.0.0.0:8000/
[D 2020-09-18 08:56:42.517 JupyterHub proxy:647] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://0c227d25fcbb:8081/hub/error']
[D 2020-09-18 08:56:42.520 JupyterHub proxy:562] Writing proxy pid file: jupyterhub-proxy.pid
08:56:43.216 [ConfigProxy] [32minfo[39m: Proxying http://0.0.0.0:8000 to (no default)
08:56:43.220 [ConfigProxy] [32minfo[39m: Proxy API at http://127.0.0.1:8001/api/routes
[D 2020-09-18 08:56:43.450 JupyterHub proxy:682] Proxy started and appears to be up
[D 2020-09-18 08:56:43.451 JupyterHub proxy:766] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
08:56:43.461 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 
[I 2020-09-18 08:56:43.462 JupyterHub app:2646] Hub API listening on http://0.0.0.0:8081/hub/
[I 2020-09-18 08:56:43.462 JupyterHub app:2648] Private Hub API connect url http://0c227d25fcbb:8081/hub/
[I 2020-09-18 08:56:43.462 JupyterHub app:2661] Starting managed service cull-idle
[I 2020-09-18 08:56:43.462 JupyterHub service:339] Starting service 'cull-idle': ['/usr/bin/python3', '/srv/jupyterhub/cull_idle_servers.py', '--timeout=3600']
[I 2020-09-18 08:56:43.465 JupyterHub service:121] Spawning /usr/bin/python3 /srv/jupyterhub/cull_idle_servers.py --timeout=3600
[D 2020-09-18 08:56:43.468 JupyterHub spawner:1153] Polling subprocess every 30s
[D 2020-09-18 08:56:43.469 JupyterHub proxy:315] Fetching routes to check
[D 2020-09-18 08:56:43.469 JupyterHub proxy:766] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
08:56:43.471 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 
[I 2020-09-18 08:56:43.471 JupyterHub proxy:320] Checking routes
[I 2020-09-18 08:56:43.471 JupyterHub proxy:400] Adding default route for Hub: / => http://0c227d25fcbb:8081
[D 2020-09-18 08:56:43.472 JupyterHub proxy:766] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
08:56:43.473 [ConfigProxy] [32minfo[39m: Adding route / -> http://0c227d25fcbb:8081
08:56:43.473 [ConfigProxy] [32minfo[39m: Route added / -> http://0c227d25fcbb:8081
08:56:43.474 [ConfigProxy] [32minfo[39m: 201 POST /api/routes/ 
[I 2020-09-18 08:56:43.474 JupyterHub app:2721] JupyterHub is now running at http://0.0.0.0:8000/
[D 2020-09-18 08:56:43.475 JupyterHub app:2324] It took 1.366 seconds for the Hub to start
[I 2020-09-18 08:57:21.102 JupyterHub log:181] 302 GET /hub/admin -> /hub/login?next=%2Fhub%2Fadmin (@10.0.0.2) 1.28ms
[D 2020-09-18 08:57:21.121 JupyterHub cas_auth:48] Has service ticket? False
[D 2020-09-18 08:57:21.121 JupyterHub cas_auth:56] Redirecting to CAS to get service ticket: https://cas2.com/cas?service=https://jupyterhubserver.com%2Fhub%2Flogin
[I 2020-09-18 08:57:21.121 JupyterHub log:181] 302 GET /hub/login?next=%2Fhub%2Fadmin -> https://cas2.com/cas?service=https://jupyterhubserver.com%2Fhub%2Flogin (@10.0.0.2) 0.90ms
[D 2020-09-18 08:57:21.259 JupyterHub cas_auth:48] Has service ticket? True
[D 2020-09-18 08:57:21.259 JupyterHub cas_auth:61] Validating service ticket ST-47229-a...
[D 2020-09-18 08:57:21.259 JupyterHub cas_auth:133] Validate URL: https://cas2.com/cas/p3/serviceValidate?service=https://jupyterhubserver.com%2Fhub%2Flogin&ticket=XXXXX
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:139] Response was successful: HTTPResponse(_body=None,_error_is_response_code=False,buffer=<_io.BytesIO object at 0x7f6d38032770>,code=200,effective_url='https://cas2.com/cas/p3/serviceValidate?service=https://jupyterhubserver.com%2Fhub%2Flogin&ticket=XXXXX',error=None,headers=<tornado.httputil.HTTPHeaders object at 0x7f6d380435b0>,reason='200',request=<tornado.httpclient.HTTPRequest object at 0x7f6d38043460>,request_time=0.09683465957641602,start_time=1600419441.2593346,time_info={'queue': 1.1205673217773438e-05, 'namelookup': 0.016096, 'connect': 0.027904, 'appconnect': 0.087763, 'pretransfer': 0.087816, 'starttransfer': 0.096387, 'total': 0.096556, 'redirect': 0.0})
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:67] Service ticket was valid.
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:68] User is 'username@com.com'.
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:70] Attribute uid: user
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:70] Attribute isFromNewLogin: false
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:70] Attribute email: 
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:70] Attribute authenticationDate: Fri Sep 18 09:20:27 CEST 2020
[D 2020-09-18 08:57:21.356 JupyterHub cas_auth:70] Attribute longTermAuthenticationRequestTokenUsed: false
[D 2020-09-18 08:57:21.357 JupyterHub cas_auth:70] Attribute simpleName: 
[D 2020-09-18 08:57:21.357 JupyterHub cas_auth:81] User is now 'username'.
[D 2020-09-18 08:57:21.357 JupyterHub cas_auth:100] CAS authentication successful for 'username'.
[D 2020-09-18 08:57:21.359 JupyterHub base:526] Setting cookie for username: jupyterhub-hub-login
[D 2020-09-18 08:57:21.359 JupyterHub base:522] Setting cookie jupyterhub-hub-login: {'httponly': True, 'path': '/hub/'}
[D 2020-09-18 08:57:21.360 JupyterHub user:289] Creating <class 'dockerspawner.swarmspawner.SwarmSpawner'> for username:
[D 2020-09-18 08:57:21.362 JupyterHub cas_auth:104] Calling authenticator.add_user() for '<User(username 0/1 running)>'
[D 2020-09-18 08:57:21.362 JupyterHub cas_auth:106] CAS redirecting to: /hub/spawn?ticket=XXXXX
[I 2020-09-18 08:57:21.362 JupyterHub log:181] 302 GET /hub/login?ticket=XXXXX -> /hub/spawn?ticket=XXXXX (@10.0.0.2) 104.25ms
[D 2020-09-18 08:57:21.377 JupyterHub base:285] Recording first activity for <User(username 0/1 running)>
[D 2020-09-18 08:57:21.389 JupyterHub base:330] Refreshing auth for username
[D 2020-09-18 08:57:21.389 JupyterHub pages:189] Triggering spawn with supplied query arguments for username
[D 2020-09-18 08:57:21.389 JupyterHub base:867] Initiating spawn for username
[D 2020-09-18 08:57:21.389 JupyterHub base:871] 0/100 concurrent spawns
[D 2020-09-18 08:57:21.389 JupyterHub base:876] 0 active servers
bootstrap.sh: directory for user already exists. skipped
boostrap.sh copying stuff
sending incremental file list
work/

sent 104 bytes  received 23 bytes  254.00 bytes/sec
total size is 184  speedup is 1.45
sending incremental file list
.ipynb_checkpoints/
.julia/
.julia/config/

sent 265 bytes  received 33 bytes  596.00 bytes/sec
total size is 726  speedup is 2.44
[D 2020-09-18 08:57:21.463 JupyterHub user:603] Calling Spawner.start for username
[D 2020-09-18 08:57:21.480 JupyterHub dockerspawner:777] Getting container 'jupyter-username'
[I 2020-09-18 08:57:21.483 JupyterHub dockerspawner:783] Service 'jupyter-username' is gone
[I 2020-09-18 08:57:21.491 JupyterHub dockerspawner:985] Created service jupyter-username (id: sh5bxu0) from image hdlbq/datascience-notebook-julia:1.1
[I 2020-09-18 08:57:21.491 JupyterHub dockerspawner:1009] Starting service jupyter-username (id: sh5bxu0)
[D 2020-09-18 08:57:21.491 JupyterHub swarmspawner:144] Getting task of service 'jupyter-username'
[D 2020-09-18 08:57:21.491 JupyterHub dockerspawner:777] Getting container 'jupyter-username'
[E 2020-09-18 08:57:21.496 JupyterHub user:690] Unhandled error starting username's server: Service jupyter-username not found
[D 2020-09-18 08:57:21.497 JupyterHub user:791] Stopping username
[D 2020-09-18 08:57:21.497 JupyterHub swarmspawner:144] Getting task of service 'jupyter-username'
[D 2020-09-18 08:57:21.497 JupyterHub dockerspawner:777] Getting container 'jupyter-username'
[D 2020-09-18 08:57:21.501 JupyterHub swarmspawner:132] Service sh5bxu0 status: {'Message': 'created',
     'PortStatus': {},
     'State': 'new',
     'Timestamp': '2020-09-18T08:57:21.492099641Z'}
[D 2020-09-18 08:57:21.511 JupyterHub user:817] Deleting oauth client jupyterhub-user-username
[D 2020-09-18 08:57:21.525 JupyterHub user:820] Finished stopping username
[E 2020-09-18 08:57:21.549 JupyterHub pages:199] Failed to spawn single-user server with query arguments
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/pages.py", line 195, in get
        return await self._wrap_spawn_single_user(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/pages.py", line 313, in _wrap_spawn_single_user
        raise web.HTTPError(
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: RuntimeError Service jupyter-username not found)
   
[D 2020-09-18 08:57:21.550 JupyterHub pages:216] Triggering spawn with default options for username
[D 2020-09-18 08:57:21.550 JupyterHub base:867] Initiating spawn for username
[D 2020-09-18 08:57:21.550 JupyterHub base:871] 0/100 concurrent spawns
[D 2020-09-18 08:57:21.550 JupyterHub base:876] 0 active servers
```

**Comment by manics** [comment]
@hdlbq Are you able to reproduce this with one of the default authenticators, e.g. the dummy authenticator?

**Comment by jonsnowseven** [comment]
Hello, I am facing the same issue using DummyAuthenticator. I have the following configuration in `jupyterhub_config.py`:

```python
c.JupyterHub.authenticator_class = "dummy" # also tried c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator' but I suppose it has the same effect as "dummy"
c.DummyAuthenticator.password = "some_password"
```

When opening JupyterHub, I typed username "jon" and the password above and got the error:

![image](https://user-images.githubusercontent.com/25992803/113178974-0b9b6a00-9247-11eb-9e75-6952d0a15421.png)

**Comment by brospars** [comment]
I was using an old way to specify the single-user spawn command (found in jupyterhub-docker-deploy)

```python
spawn_cmd = os.environ.get('DOCKER_SPAWN_CMD', "start-singleuser.sh")
c.SwarmSpawner.extra_create_kwargs.update({ 'command': spawn_cmd })
```

Using this instead fixed the issue :

```python
c.SwarmSpawner.cmd = "start-singleuser.sh"
```
