### ISSUE TITLE
Bad handling of base_url

### ISSUE THREAD

**Issue by tannevaled** [jupyterhub/jupyterhub#3210]
### Bug description

insert one extra *hub* into the urls when base_url is defined

#### Expected behaviour

Adding default route for Hub: /jupyter/ => http://10.43.82.224:8081
prefix /hub/api/users with the base_url value 
prefix /hub/health with the base_url value

#### Actual behaviour

- insert one extra *hub* into the api/users url
- insert one extra *hub* into the health url

```bash
[I 2020-10-18 08:34:29.600 JupyterHub proxy:400] Adding default route for Hub: /jupyter/ => http://10.43.82.224:8081
[I 2020-10-18 08:34:29.603 JupyterHub app:2631] JupyterHub is now running at http://10.43.212.163:443/jupyter/
[I 2020-10-18 08:34:29.738 JupyterHub log:174] 302 GET /hub/api/users -> **/jupyter/hub/hub/api/users** (cull-idle@127.0.0.1) 10.98ms
[E 2020-10-18 08:34:29.764 JupyterHub web:1220] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1218, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1195, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1120, in render_template
        return template.render(**template_ns)
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/share/jupyterhub/templates/404.html", line 1, in top-level template code
        {% extends "error.html" %}
      File "/usr/local/share/jupyterhub/templates/error.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/local/share/jupyterhub/templates/page.html", line 75, in top-level template code
        {% if not no_spawner_check and user and user.spawner.options_form %}
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 471, in getattr
        return getattr(obj, attribute)
    jinja2.exceptions.UndefinedError: 'jupyterhub.orm.Service object' has no attribute 'spawner'
    
[E 201018 08:34:29 ioloop:763] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f71249b5400>>, <Future finished exception=HTTP 404: Not Found>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 743, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 767, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/etc/jupyterhub/cull_idle_servers.py", line 119, in cull_idle
        resp = yield fetch(req)
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/etc/jupyterhub/cull_idle_servers.py", line 113, in fetch
        return (yield client.fetch(req))
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
    tornado.httpclient.HTTPClientError: HTTP 404: Not Found
[W 2020-10-18 08:34:29.767 JupyterHub log:174] 404 GET /jupyter/hub/hub/api/users (cull-idle@127.0.0.1) 28.87ms
[I 2020-10-18 08:34:37.567 JupyterHub log:174] 302 GET /hub/health -> /**jupyter/hub/hub/health** (@10.42.1.1) 3.54ms
```
### How to reproduce
```yaml
$ cat jupyterhub-config.yaml
proxy:
  secretToken: X
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: offload
hub:
  extraConfig:
    baseUrl: |
      c.JupyterHub.base_url = 'jupyter'
```
```bash
$ helm upgrade --install jupyterhub jupyterhub/jupyterhub --namespace jupyterhub --values jupyterhub-config.yaml
$ kubectl --namespace jupyterhub logs "$(kubectl --namespace jupyterhub get pods |grep hub|cut -d' ' -f1)"
```
### Your personal set up

 - OS:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
 - Version:
```bash
$ helm list --namespace jupyterhub
NAME      	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART           	APP VERSION
jupyterhub	jupyterhub	9       	2020-10-18 10:34:09.360206547 +0200 CEST	deployed	jupyterhub-0.9.1	1.1.0      
```
 - Configuration:
3 nodes k3s cluster on Ubuntu Focal installed with k3sup
1 apache load balancer

**Comment by consideRatio** [comment]
Make it /jupyter

**Comment by tannevaled** [comment]
no luck

$ cat jupyterhub-config.yaml 
proxy:
  secretToken: X
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: offload
hub:
  extraConfig:
    baseUrl: |
      c.JupyterHub.base_url = '/jupyter2'

but
[I 2020-10-18 09:55:08.349 JupyterHub app:2631] JupyterHub is now running at http://10.43.212.163:443/jupyter2/
[I 2020-10-18 09:55:08.593 JupyterHub log:174] 302 GET /hub/api/users -> /jupyter2/hub/hub/api/users (cull-idle@127.0.0.1) 23.86ms
[E 2020-10-18 09:55:08.667 JupyterHub web:1220] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1218, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1195, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 1120, in render_template
        return template.render(**template_ns)
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/share/jupyterhub/templates/404.html", line 1, in top-level template code
        {% extends "error.html" %}
      File "/usr/local/share/jupyterhub/templates/error.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/local/share/jupyterhub/templates/page.html", line 75, in top-level template code
        {% if not no_spawner_check and user and user.spawner.options_form %}
      File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 471, in getattr
        return getattr(obj, attribute)
    jinja2.exceptions.UndefinedError: 'jupyterhub.orm.Service object' has no attribute 'spawner'
