### ISSUE TITLE
[ConfigProxy] error: 503 POST /hub/spawn/{USER_NAME} socket hang up

### ISSUE THREAD

**Issue by ayush-san** [jupyterhub/jupyterhub#3600]
### Bug description
We have a custom ECS spawner where we spawn tasks on ECS clusters. It was working fine if we are running the task on the ECS cluster which already has enough resources but it gives a socket hang-up exception if the cluster has to spawn up a new instance and then provision that task(Using capacity provider strategy). 

LOGS
```
[D 2021-09-10 12:45:27.127 JupyterHub taskspawner:201] ayush.chauhan launching jupyter-python-kernel with config {'memory': 120880, 'cpu': 16} in training-notebook-cluster
12:46:27.009 [ConfigProxy] error: 503 POST /hub/spawn/ayush.chauhan socket hang up
12:47:27.007 [ConfigProxy] error: 503 POST /hub/spawn/ayush.chauhan socket hang up
[I 2021-09-10 12:47:52.645 JupyterHub taskspawner:232] ecs task up and running for ayush.chauhan
[I 2021-09-10 12:47:52.770 JupyterHub taskspawner:126] Notebook started at XX.XX.XX.XX:RANDOM_PORT
[W 2021-09-10 12:47:52.778 JupyterHub base:947] User ayush.chauhan is slow to start (timeout=10)
[I 2021-09-10 12:47:52.795 JupyterHub log:174] 302 POST /hub/spawn/ayush.chauhan -> /hub/spawn-pending/ayush.chauhan (ayush.chauhan@122.177.107.112) 145784.71ms
[W 2021-09-10 12:47:52.795 JupyterHub user:630] ayush.chauhan's server failed to start in 60 seconds, giving up
[D 2021-09-10 12:47:52.796 JupyterHub user:739] Stopping ayush.chauhan
[I 2021-09-10 12:47:52.796 JupyterHub taskspawner:148] Polling for ayush.chauhan notebook
[D 2021-09-10 12:47:52.796 JupyterHub taskspawner:114] Running executor...
[I 2021-09-10 12:47:52.796 JupyterHub taskspawner:157] Getting tasks for training-notebook-cluster, startedBy EcsTaskSpawner:ayush.chauhan
[I 2021-09-10 12:47:52.797 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 26.33ms
[I 2021-09-10 12:47:52.798 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 26.40ms
[I 2021-09-10 12:47:52.798 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 26.50ms
[I 2021-09-10 12:47:52.799 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 26.55ms
[I 2021-09-10 12:47:52.799 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 26.62ms
[I 2021-09-10 12:47:52.799 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 26.59ms
[I 2021-09-10 12:47:52.800 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 26.69ms
[I 2021-09-10 12:47:52.800 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 26.76ms
[W 2021-09-10 12:47:52.803 JupyterHub web:1787] 400 POST /hub/spawn/ayush.chauhan (122.177.107.112): ayush.chauhan is pending stop
[D 2021-09-10 12:47:52.803 JupyterHub base:1197] No template for 400
[W 2021-09-10 12:47:52.808 JupyterHub log:174] 400 POST /hub/spawn/ayush.chauhan (ayush.chauhan@122.177.107.112) 34.01ms
[D 2021-09-10 12:47:52.808 JupyterHub pages:581] No template for 503
[I 2021-09-10 12:47:52.809 JupyterHub taskspawner:164] 1 tasks found for EcsTaskSpawner:ayush.chauhan
[I 2021-09-10 12:47:52.810 JupyterHub log:174] 200 GET /hub/error/503?url=%2Fhub%2Fspawn%2Fayush.chauhan (@172.17.0.1) 36.42ms
[I 2021-09-10 12:47:52.811 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 36.54ms
[I 2021-09-10 12:47:52.811 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 36.65ms
[I 2021-09-10 12:47:52.812 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 36.76ms
[I 2021-09-10 12:47:52.812 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 36.89ms
[D 2021-09-10 12:47:52.812 JupyterHub pages:581] No template for 503
[I 2021-09-10 12:47:52.813 JupyterHub log:174] 200 GET /hub/error/503?url=%2Fhub%2Fspawn%2Fayush.chauhan (@172.17.0.1) 37.80ms
[W 2021-09-10 12:47:52.815 JupyterHub web:1787] 400 POST /hub/spawn/ayush.chauhan (122.177.107.112): ayush.chauhan is pending stop
[D 2021-09-10 12:47:52.816 JupyterHub base:1197] No template for 400
[W 2021-09-10 12:47:52.816 JupyterHub log:174] 400 POST /hub/spawn/ayush.chauhan (ayush.chauhan@122.177.107.112) 40.34ms
[I 2021-09-10 12:47:52.817 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 40.45ms
[I 2021-09-10 12:47:52.817 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 40.62ms
[I 2021-09-10 12:47:52.818 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 40.81ms
[I 2021-09-10 12:47:52.818 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 41.03ms
[I 2021-09-10 12:47:52.819 JupyterHub log:174] 200 GET /hub/api (@172.31.103.33) 41.27ms
[D 2021-09-10 12:47:52.827 JupyterHub base:285] Recording first activity for <APIToken('6e4f...', user='ayush.chauhan')>
[D 2021-09-10 12:47:52.839 JupyterHub users:715] Not updating activity for <User(ayush.chauhan 1/1 running)>: 2021-09-10T12:47:50.518798Z < 2021-09-10T12:47:52.789044Z
[D 2021-09-10 12:47:52.839 JupyterHub users:728] Activity on server ayush.chauhan/: 2021-09-10T12:47:50.518798Z
[I 2021-09-10 12:47:52.846 JupyterHub log:174] 200 POST /hub/api/users/ayush.chauhan/activity (ayush.chauhan@172.31.103.33) 21.00ms
[I 2021-09-10 12:47:52.846 JupyterHub taskspawner:131] Stopping ECS task for ayush.chauhan
[D 2021-09-10 12:47:52.846 JupyterHub taskspawner:114] Running executor...
[D 2021-09-10 12:47:52.846 JupyterHub taskspawner:279] ayush.chauhan notebook_type is training
[I 2021-09-10 12:47:52.846 JupyterHub taskspawner:157] Getting tasks for training-notebook-cluster, startedBy EcsTaskSpawner:ayush.chauhan
[I 2021-09-10 12:47:52.867 JupyterHub taskspawner:164] 1 tasks found for EcsTaskSpawner:ayush.chauhan
[I 2021-09-10 12:47:52.925 JupyterHub taskspawner:306] clearing state for ayush.chauhan
[I 2021-09-10 12:47:52.925 JupyterHub taskspawner:296] getting state for ayush.chauhan
[D 2021-09-10 12:47:52.937 JupyterHub user:767] Deleting oauth client jupyterhub-user-ayush.chauhan
[D 2021-09-10 12:47:52.947 JupyterHub user:770] Finished stopping ayush.chauhan
[E 2021-09-10 12:47:52.955 JupyterHub gen:623] Exception in Future <Task finished name='Task-164' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:845> exception=TimeoutError('Timeout')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 656, in spawn
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 560, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.util.TimeoutError: Timeout
    
[D 2021-09-10 12:48:11.764 JupyterHub proxy:766] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
12:48:11.767 [ConfigProxy] info: 200 GET /api/routes 
[I 2021-09-10 12:48:11.767 JupyterHub proxy:320] Checking routes
[I 2021-09-10 12:48:26.300 JupyterHub log:174] 302 GET /hub/ -> /hub/spawn (ayush.chauhan@122.177.107.112) 10.28ms
[D 2021-09-10 12:48:26.444 JupyterHub pages:188] Serving options form for ayush.chauhan
[I 2021-09-10 12:48:26.445 JupyterHub log:174] 200 GET /hub/spawn (ayush.chauhan@122.177.107.112) 4.42ms
[I 2021-09-10 12:48:33.976 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 0.64ms
[I 2021-09-10 12:48:33.977 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 0.51ms
[I 2021-09-10 12:48:33.979 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 0.46ms
[I 2021-09-10 12:48:33.980 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 0.50ms
[I 2021-09-10 12:48:34.451 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 0.66ms
[I 2021-09-10 12:48:34.452 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 0.47ms
[I 2021-09-10 12:48:34.453 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 0.35ms
[I 2021-09-10 12:48:34.454 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 0.36ms
[I 2021-09-10 12:49:05.090 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 0.68ms
[I 2021-09-10 12:49:05.091 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 0.50ms
[I 2021-09-10 12:49:05.092 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 0.39ms
[I 2021-09-10 12:49:05.094 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 0.39ms
[I 2021-09-10 12:49:07.658 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.40) 0.59ms
[I 2021-09-10 12:49:07.661 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.59.18) 0.46ms
[I 2021-09-10 12:49:07.662 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.118) 0.39ms
[I 2021-09-10 12:49:07.663 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:172.31.49.211) 0.35ms
```

Hub is behind a target group, here are the target group metrics for the same period
![image](https://user-images.githubusercontent.com/57655135/132866822-d720efcd-7b8b-46b7-b915-b4a0d2a8d1ec.png)
After this hub process starts giving 504
<img width="572" alt="Screenshot 2021-09-10 at 18 16 40" src="https://user-images.githubusercontent.com/57655135/132866876-487734c4-d6ec-4df8-ad48-6887c2d72d5b.png">

### Your personal setup

 - OS: ubuntu 20.04
 Version(s):
 - Python 3.8.10
 - Jupyterhub 1.1.0

**Comment by manics** [comment]
This sounds like a problem with your custom spawner rather than an issue in JupyterHub. If you need more help please could you use the [community forum](https://discourse.jupyter.org/)? Thanks!
