### ISSUE TITLE
tornado.curl_httpclient.CurlError: 599 Empty Reply from Server - with Oauth on some users

### ISSUE THREAD

**Issue by Yayg** [jupyterhub/jupyterhub#3618]
Hi everyone and thanks for developping such an amazing tool,
I'm using JupyterHub on Kubernetes with helm and Keycloak for OIDC.
Jupyterhub version: 1.1.3
Chart version: 1.1.3
Keycloak version: 12.0.4 (also helmed with codecentric/keycloak)

### Bug description

When loging in with Keycloak some users get "500 Internal Server Error", then when refreshing "400 OAuth state missing from cookies" and jupyterhub shows the following error:
```
I 2021-09-23 13:33:14.850 JupyterHub log:189] 302 GET / -> /hub/ (@10.172.142.121) 1.78ms
[I 2021-09-23 13:33:15.147 JupyterHub log:189] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@10.172.142.121) 1.75ms
[I 2021-09-23 13:33:15.183 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2F (@10.172.142.121) 4.77ms
[I 2021-09-23 13:33:17.979 JupyterHub oauth2:111] OAuth redirect: 'https://jhub-dev.eds.aphp.fr/hub/oauth_callback'
[I 2021-09-23 13:33:17.982 JupyterHub log:189] 302 GET /hub/oauth_login?next=%2Fhub%2F -> https://auth.eds.aphp.fr/auth/realms/master/protocol/openid-connect/auth?response_type=code&redirect_uri=https%3A%2F%2Fjhub-dev.eds.aphp.fr%2Fhub%2Foauth_callback&client_id=jupyterhub&state=[secret]&scope=ldap-groups (@10.172.142.121) 3.07ms
[E 2021-09-23 13:33:18.161 JupyterHub oauth2:389] Error fetching user data 599 GET https://auth.eds.aphp.fr/auth/realms/master/protocol/openid-connect/userinfo: HTTP 599: Empty reply from server
[E 2021-09-23 13:33:18.162 JupyterHub web:1789] Uncaught exception GET /hub/oauth_callback?code=e5a40fe1-02bb-4b81-94a4-b488ebd02bca.09a2f2a1-f45a-473b-93ed-581466b325d2.feae45a6-94c2-45f8-83c6-80dc56b6c4e3&state=eyJzdGF0ZV9pZCI6ICI1MTUzOWU1Y2U1MTA0OGZjYjMwN2E2NDYyYzViODZmYSIsICJuZXh0X3VybCI6ICIvaHViLyJ9 (10.172.142.121)
    HTTPServerRequest(protocol='https', host='jhub-dev.eds.aphp.fr', method='GET', uri='/hub/oauth_callback?code=e5a40fe1-02bb-4b81-94a4-b488ebd02bca.09a2f2a1-f45a-473b-93ed-581466b325d2.feae45a6-94c2-45f8-83c6-80dc56b6c4e3&state=eyJzdGF0ZV9pZCI6ICI1MTUzOWU1Y2U1MTA0OGZjYjMwN2E2NDYyYzViODZmYSIsICJuZXh0X3VybCI6ICIvaHViLyJ9', version='HTTP/1.1', remote_ip='10.172.142.121')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 231, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 754, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 469, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/generic.py", line 171, in authenticate
        user_data_resp_json = await self._get_user_data(token_resp_json)
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 390, in fetch
        raise e
      File "/usr/local/lib/python3.8/dist-packages/oauthenticator/oauth2.py", line 369, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
    tornado.curl_httpclient.CurlError: HTTP 599: Empty reply from server
    
[E 2021-09-23 13:33:18.187 JupyterHub log:181] {
      "Cookie": "oauthenticator-state=[secret]",
      "Accept-Language": "en",
      "Accept-Encoding": "gzip, deflate, br",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "same-site",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "X-Original-Forwarded-For": "10.200.207.155, 127.0.0.1",
      "X-Scheme": "https",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jhub.kubernetes",
      "X-Forwarded-For": "10.172.142.121,::ffff:192.168.64.1",
      "X-Real-Ip": "10.172.142.121",
      "X-Request-Id": "4a63923bea89a856f64688eeb5cd705a",
      "Host": "jhub-dev.eds.aphp.fr",
      "Connection": "close"
    }
[E 2021-09-23 13:33:18.187 JupyterHub log:189] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@10.172.142.121) 114.56ms
```
The error seems to be because the userinfo on my keycloak server is broken but it actually works for some users and the error is still there for other versions of keycloak (14.0.0 and 15.0.2) so I guess the problem comes from Jupyterhub

#### Expected behaviour

The user should be able to login normally

#### Actual behaviour

Some users cannot login (and nothing seems to differentiate the users from one another on the Keycloak side)

### How to reproduce

1. Deploy keycloak 12.0.4 and setup a client
2. Deploy jupyterhub 1.1.3 and use the following oidc config:
```
    GenericOAuthenticator:
      client_id: jupyterhub
      client_secret: 008e4bba-9ecd-4553-8263-0e9351d9e2b7
      oauth_callback_url: https://jhub-dev.eds.aphp.fr/hub/oauth_callback
      authorize_url: https://auth.eds.aphp.fr/auth/realms/master/protocol/openid-connect/auth
      token_url: https://auth.eds.aphp.fr/auth/realms/master/protocol/openid-connect/token
      userdata_url: https://auth.eds.aphp.fr/auth/realms/master/protocol/openid-connect/userinfo
      login_service: keycloak
      userdata_params:
        state: state
#     scope:
#       - openid
#       - profile
#       - email
#       - ldap-groups
#       - web-origins
      username_key: fullname
    JupyterHub:
      admin_access: true
      authenticator_class: generic-oauth
```
### Your personal set up

 - OS:
Kubernetes over Centos7
 - Version(s):
1..1.3

- <details><summary>Full environment</summary>

```
jovyan@hub-776cfc4d77-9xpjh:/srv/jupyterhub$ pip freeze
alembic==1.6.5
appdirs==1.4.3
async-generator==1.10
attrs==21.2.0
bcrypt==3.2.0
cachetools==4.2.2
certifi==2021.5.30
certipy==0.1.3
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.7
distlib==0.3.0
entrypoints==0.3
escapism==1.0.1
filelock==3.0.12
google-auth==1.31.0
greenlet==1.1.0
idna==2.10
importlib-metadata==1.5.0
ipython-genutils==0.2.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-telemetry==0.1.0
jupyterhub==1.4.2
jupyterhub-firstuseauthenticator==0.14.1
jupyterhub-hmacauthenticator==1.0
jupyterhub-idle-culler==1.1
jupyterhub-kubespawner==1.1.0
jupyterhub-ldapauthenticator==1.3.2
jupyterhub-ltiauthenticator==1.0.0
jupyterhub-nativeauthenticator==0.0.7
jupyterhub-tmpauthenticator==0.6
kubernetes==17.17.0
ldap3==2.9
Mako==1.1.4
MarkupSafe==2.0.1
more-itertools==4.2.0
mwoauth==0.3.7
nullauthenticator==1.0.0
oauthenticator==14.2.0
oauthlib==3.1.1
onetimepass==1.0.1
packaging==20.3
pamela==1.0.0
pluggy==0.13.0
prometheus-client==0.11.0
psycopg2-binary==2.9.1
py==1.8.1
py-spy==0.3.8
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycurl==7.44.1
PyJWT==1.7.1
PyMySQL==1.0.2
pyOpenSSL==20.0.1
pyparsing==2.4.6
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
python-ldap==3.3.1
python-slugify==5.0.2
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
ruamel.yaml==0.17.9
ruamel.yaml.clib==0.2.2
six==1.16.0
SQLAlchemy==1.4.18
sqlalchemy-cockroachdb==1.4.0
statsd==3.3.0
text-unidecode==1.3
toml==0.10.0
tornado==6.1
tox==3.13.2
traitlets==5.0.5
urllib3==1.26.5
virtualenv==20.0.17
websocket-client==1.1.0
zipp==1.0.0
```

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
It looks like you've also posted this to Discourse: https://discourse.jupyter.org/t/599-empty-reply-from-server-oauth/10941

To avoid discussions happening in two places which makes it harder for people to follow I'll therefore close this.
