### ISSUE TITLE
HTTP 403: Forbidden error when opening courses tab

### ISSUE THREAD

**Issue by rajaprerak** [jupyterhub/jupyterhub#3633]
### Bug description
When I am logging in and going to instructors tab, I am getting an error. I have already gone through https://github.com/jupyterhub/jupyterhub/issues/1377. But, still no luck.

#### Expected behaviour
Link to courses

#### Actual behaviour
Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/nbgrader/server_extensions/course_list/handlers.py", line 173, in get jhub_courses = yield self.check_for_jupyterhub_formgraders(config) File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1148, in run value = future.result() File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1156, in run yielded = self.gen.throw(*exc_info) File "/usr/local/lib/python3.8/dist-packages/nbgrader/server_extensions/course_list/handlers.py", line 143, in check_for_jupyterhub_formgraders response = yield http_client.fetch(url, headers=auth) File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1148, in run value = future.result() tornado.httpclient.HTTPClientError: HTTP 403: Forbidden

### How to reproduce

1. Login
2. Go to courses tab
3. See error

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!
