### ISSUE TITLE
Spawner failed to start [status=1]; ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by smeylan** [jupyterhub/jupyterhub#3709]
### Bug description
I am trying to get multi-user JupyterHub running again on an Ubutuntu 20.04 system after upgrading from 16.04. I uninstalled and reinstalled all Jupyter-related packages (following [this link](https://jupyterhub.readthedocs.io/en/stable/installation-guide.html)), and deleted `.jupyter` and `.ipython` directories for my user because I'd see issues in such a big jump. When I launch with `sudo jupyterhub` I can log in and launch a server with my ubuntu user credentials, but it fails to spawn. I can't make sense of the resulting error messages in the logs, which seem generic. My understanding is that the single-user logs will also appear in the same place as the Hub logs with the default installation, so my logs below should include everything.

I suspect `ERROR:asyncio:Task exception was never retrieved` is hiding the errors.

I also subsequently tried installing through TLJH but ran into 404 errors after trying to get it use existing home directories / not make new users. 

#### Expected behavior
JupyterHub should spawn a server for my user, or I should see some interpretable logs saying what's wrong.

#### Actual behaviour
In the frontend I see `Spawn failed: Server at http://127.0.0.1:38140/user/stephan/ didn't respond in 30 seconds`. Logs are below.

### How to reproduce

Fresh install of Jupyterhub of 20.04 through pip following these [instructions](https://jupyterhub.readthedocs.io/en/stable/installation-guide.html)

### Your personal set up

 - OS: Ubuntu 20.04
 - Version(s): jupyterhub 2.0.0, Python 3.8.10>

- <details><summary>Full environment</summary>

```
alembic==1.7.5
anyio==3.4.0
apparmor==2.13.3
appdirs==1.4.3
apt-xapian-index==0.49
apturl==0.5.2
argon2-cffi==21.1.0
async-generator==1.10
attrs==21.2.0
Automat==0.8.0
Babel==2.9.1
backcall==0.2.0
bcrypt==3.1.7
bleach==4.1.0
blinker==1.4
Brlapi==0.7.0
certifi==2021.10.8
certipy==0.1.3
cffi==1.15.0                                                                                                                                         
chardet==3.0.4
charset-normalizer==2.0.9
Click==7.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==36.0.0
cupshelpers==1.0
dbus-python==1.2.16
debugpy==1.5.1
decorator==5.1.0
defer==1.0.6
defusedxml==0.7.1
distlib==0.3.0
distro==1.4.0
distro-info===0.23ubuntu1
dnspython==1.16.0
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.14.1
filelock==3.0.12
future==0.18.2
gpg===1.13.1-unknown
greenlet==1.1.2
httplib2==0.14.0
hyperlink==19.0.0
idna==3.3
importlib-metadata==4.8.2
importlib-resources==5.4.0
incremental==16.10.1
iotop==0.6
ipykernel==6.6.0
ipython==7.30.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
json5==0.9.6
jsonschema==4.2.1
jupyter==1.0.0
jupyter-client==7.1.0
jupyter-console==6.4.0
jupyter-contrib-core==0.3.3
jupyter-core==4.9.1
jupyter-nbextensions-configurator==0.4.1
jupyter-server==1.13.0
jupyter-telemetry==0.1.0
jupyterhub==2.0.0
jupyterlab==3.2.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.2
jupyterlab-widgets==1.0.2
keyring==18.0.1                                                                                                                                               
keyrings.alt==3.4.0
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
LibAppArmor==2.13.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.6
Markdown==3.1.1
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mistune==0.8.4
monotonic==1.5
more-itertools==4.2.0
nbclassic==0.3.4
nbclient==0.5.9
nbconvert==6.3.0
nbformat==5.1.3
nest-asyncio==1.5.4
netifaces==0.10.4
notebook==6.4.6
oauthlib==3.1.1
onboard==1.4.1
oneconf==0.3.9
packaging==21.3
pamela==1.0.0
pandocfilters==1.5.0
paramiko==2.6.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pip-autoremove==0.10.0
piston-mini-client==0.7.5
progressbar==2.5
prometheus-client==0.12.0
prompt-toolkit==3.0.23
protobuf==3.6.1
ptyprocess==0.7.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycparser==2.21
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
Pygments==2.10.0
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==21.0.0
pyparsing==3.0.6
pyRFC3339==1.1
pyrsistent==0.18.0
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.6
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-json-logger==2.0.2
pytz==2021.3
pyxdg==0.26
PyYAML==5.3.1
pyzmq==22.3.0
qtconsole==5.2.1
QtPy==1.11.3
reportlab==3.5.34
requests==2.26.0
requests-unixsocket==0.2.0
ruamel.yaml==0.17.17
ruamel.yaml.clib==0.2.6
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
Send2Trash==1.8.0
service-identity==18.1.0
simplejson==3.16.0
six==1.16.0
sniffio==1.2.0
software-center-aptd-plugins==0.0.0
SQLAlchemy==1.4.27
ssh-import-id==5.10
supervisor==4.1.0
system-service==0.3
systemd-python==234
terminado==0.12.1
testpath==0.5.0
tornado==6.1
traitlets==5.1.1
Twisted==18.9.0
ubuntu-advantage-tools==27.4
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.7
usb-creator==0.3.7
virtualenv==20.0.17
wadllib==1.3.3
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.3
widgetsnbextension==3.5.2
xdiagnose==3.8.9
xkit==0.0.0
zipp==3.6.0
zope.interface==4.7.1
```
</details>

- <details><summary>Configuration</summary>

```python
# Everything left at defaults
```
</details>

- <details><summary>Logs</summary>

```
[I 2021-12-08 07:20:25.382 JupyterHub spawner:1526] Spawning jupyterhub-singleuser
[I 2021-12-08 07:20:25.702 JupyterHub log:189] 302 GET /hub/spawn/stephan -> /hub/spawn-pending/stephan (stephan@::1) 1004.97ms
[I 2021-12-08 07:20:25.717 JupyterHub pages:397] stephan is pending spawn
[I 2021-12-08 07:20:25.724 JupyterHub log:189] 200 GET /hub/spawn-pending/stephan (stephan@::1) 12.19ms
[I 2021-12-08 07:20:26.377 SingleUserLabApp mixins:615] Starting jupyterhub single-user server version 2.0.0
[I 2021-12-08 07:20:26.377 SingleUserLabApp mixins:629] Extending jupyterlab.labhubapp.SingleUserLabApp from jupyterlab 3.2.4
[I 2021-12-08 07:20:26.377 SingleUserLabApp mixins:629] Extending jupyter_server.serverapp.ServerApp from jupyter_server 1.13.0
[I 2021-12-08 07:20:26.407 SingleUserLabApp manager:345] jupyterlab | extension was successfully linked.
[C 2021-12-08 07:20:26.410 NotebookApp] Bad config encountered during initialization: Trait, server_extensions, not found.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-20' coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:830> exception=HTTPError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 1031, in spawn_single_user
    await gen.with_timeout(
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 1065, in spawn_single_user
    raise web.HTTPError(
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for stephan may contain details.)
[W 2021-12-08 07:20:53.462 JupyterHub user:798] stephan's server never showed up at http://127.0.0.1:38140/user/stephan/ after 30 seconds. Giving up.

    Common causes of this timeout, and debugging tips:

    1. The server didn't finish starting,
       or it crashed due to a configuration issue.
       Check the single-user server's logs for hints at what needs fixing.
    2. The server started, but is not accessible at the specified URL.
       This may be a configuration issue specific to your chosen Spawner.
       Check the single-user server logs and resource to make sure the URL
       is correct and accessible from the Hub.
    3. (unlikely) Everything is working, but the server took too long to respond.
       To fix: increase `Spawner.http_timeout` configuration
       to a number of seconds that is enough for servers to become responsive.

[E 2021-12-08 07:20:53.502 JupyterHub gen:623] Exception in Future <Task finished name='Task-21' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:934> exception=TimeoutError("Server at http://127.0.0.1:38140/user/stephan/ didn't respond in 30 seconds")> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 941, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 779, in spawn
        await self._wait_up(spawner)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 823, in _wait_up
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 793, in _wait_up
        resp = await server.wait_up(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 241, in wait_for_http_server
        re = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 189, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    asyncio.exceptions.TimeoutError: Server at http://127.0.0.1:38140/user/stephan/ didn't respond in 30 seconds

[I 2021-12-08 07:20:53.505 JupyterHub log:189] 200 GET /hub/api/users/stephan/server/progress (stephan@::1) 27756.51ms
```
</details>

**Comment by smeylan** [comment]
Figured it out --- there were some residual python2 binaries from an ancient version of Jupiter. A more careful cleaning out of everything fixed it.

**Comment by teshomem** [comment]
I am experiencing same issue. Could you share your experience? What did you clear out?
