### ISSUE TITLE
Notebook Spawning Fails

### ISSUE THREAD

**Issue by chermes** [jupyterhub/jupyterhub#3724]
### Bug description
Hi,

I am currently experiencing a strange issue with the latest 2.0.0 version of jupyterhub (Docker image):
Using the default PAM authentication and setting up a local user, the spawning process fails.
Please let me know if you need more information or I did something wrong in this setup.
Thank you!

#### Expected behaviour
I would expect to see a notebook server instance.

#### Actual behaviour
In the browser, I see the following error:
Spawn failed: Server at http://127.0.0.1:51055/user/jdoe/ didn't respond in 30 seconds

#### Step 0
Open two shells, `Shell 1` and `Shell 2`.

#### Step 1
In Shell 1:
> `docker run --rm -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub:2.0.0`

#### Step 2
In Shell 2:
> `docker exec -it jupyterhub bash`
> `adduser jdoe`
(Follow the instructions to create this user.)

#### Step 3
Open http://localhost:8000 and login in with user "jdoe" and password.
After some seconds (>30 s), a "Spawn failed" message occurs.

#### Step 4
In Shell 1, this exception occurs in the log (see the full log below):
```
[I 2021-12-17 14:36:43.080 JupyterHub spawner:1526] Spawning jupyterhub-singleuser
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import main
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/singleuser/app.py", line 38, in <module>
    raise _import_error
````
#### Addendum
Interestingly, if I do the same with the image tag ":1.5.0" it works if I install the notebooks module in Shell 2 before the login in via the browser (Step 2):
> `python3 -m pip install notebook`

### Your personal set up
Using the official Docker image, freshly pulled from the hub.

 - OS:
   Windows using WSL2, 
   Docker 20.10.8
 - Version(s):
    From inside the container:
    `jupyterhub --version`: `2.0.0`
    `python3 --version`: `Python 3.8.10`

</details>

- <details><summary>Configuration</summary>
No extra configuration or set up is used.
</details>

- <details><summary>Logs</summary>
```
docker run --rm -p 8000:8000 --name jupyterhub jupyterhub/jupyterhub:2.0.0
[I 2021-12-17 14:55:32.267 JupyterHub app:2717] Running JupyterHub version 2.0.0
[I 2021-12-17 14:55:32.267 JupyterHub app:2747] Using Authenticator: jupyterhub.auth.PAMAuthenticator-2.0.0
[I 2021-12-17 14:55:32.268 JupyterHub app:2747] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-2.0.0
[I 2021-12-17 14:55:32.268 JupyterHub app:2747] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-2.0.0
[I 2021-12-17 14:55:32.274 JupyterHub app:1641] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[I 2021-12-17 14:55:32.287 alembic.runtime.migration migration:201] Context impl SQLiteImpl.
[I 2021-12-17 14:55:32.287 alembic.runtime.migration migration:204] Will assume non-transactional DDL.
[I 2021-12-17 14:55:32.294 alembic.runtime.migration migration:615] Running stamp_revision  -> 833da8570507
[I 2021-12-17 14:55:32.390 JupyterHub proxy:496] Generating new CONFIGPROXY_AUTH_TOKEN
[I 2021-12-17 14:55:32.408 JupyterHub app:1913] Not using allowed_users. Any authenticated user will be allowed.
[W 2021-12-17 14:55:32.417 JupyterHub app:2152] No admin role found; assuming hub upgrade. Initializing default roles for all entities
[I 2021-12-17 14:55:32.430 JupyterHub app:2786] Initialized 0 spawners in 0.002 seconds
[W 2021-12-17 14:55:32.432 JupyterHub proxy:687] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2021-12-17 14:55:32.432 JupyterHub proxy:691] Starting proxy @ http://:8000
14:55:32.807 [ConfigProxy] info: Proxying http://*:8000 to (no default)
14:55:32.809 [ConfigProxy] info: Proxy API at http://127.0.0.1:8001/api/routes
14:55:32.907 [ConfigProxy] info: 200 GET /api/routes
[I 2021-12-17 14:55:32.908 JupyterHub app:3035] Hub API listening on http://127.0.0.1:8081/hub/
14:55:32.908 [ConfigProxy] info: 200 GET /api/routes
[I 2021-12-17 14:55:32.909 JupyterHub proxy:431] Adding route for Hub: / => http://127.0.0.1:8081
14:55:32.910 [ConfigProxy] info: Adding route / -> http://127.0.0.1:8081
14:55:32.910 [ConfigProxy] info: Route added / -> http://127.0.0.1:8081
14:55:32.910 [ConfigProxy] info: 201 POST /api/routes/
[I 2021-12-17 14:55:32.910 JupyterHub app:3101] JupyterHub is now running at http://:8000
[W 2021-12-17 14:55:35.118 JupyterHub base:391] Invalid or expired cookie token
[W 2021-12-17 14:55:35.119 JupyterHub scopes:496] Not authorizing access to /hub/api/users/jdoe/server/progress. Requires any of [read:servers], not derived from scopes []
[W 2021-12-17 14:55:35.119 JupyterHub web:1787] 403 GET /hub/api/users/jdoe/server/progress (::ffff:172.17.0.1): Action is not authorized with current scopes; requires any of [read:servers]
[W 2021-12-17 14:55:35.119 JupyterHub log:189] 403 GET /hub/api/users/jdoe/server/progress (@::ffff:172.17.0.1) 1.47ms
[I 2021-12-17 14:56:17.256 JupyterHub log:189] 302 GET / -> /hub/ (@::ffff:172.17.0.1) 0.74ms
[I 2021-12-17 14:56:17.260 JupyterHub log:189] 302 GET /hub/ -> /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 0.63ms
[I 2021-12-17 14:56:17.289 JupyterHub log:189] 200 GET /hub/login?next=%2Fhub%2F (@::ffff:172.17.0.1) 23.87ms
[I 2021-12-17 14:56:22.980 JupyterHub roles:358] Adding role user for User: jdoe
[I 2021-12-17 14:56:22.989 JupyterHub base:796] User logged in: jdoe
[I 2021-12-17 14:56:22.990 JupyterHub log:189] 302 POST /hub/login?next=%2Fhub%2F -> /hub/ (jdoe@::ffff:172.17.0.1) 30.04ms
[I 2021-12-17 14:56:23.001 JupyterHub log:189] 302 GET /hub/ -> /hub/spawn (jdoe@::ffff:172.17.0.1) 7.89ms
[I 2021-12-17 14:56:23.011 JupyterHub roles:480] Adding role server to token: <APIToken('4c70...', user='jdoe', client_id='jupyterhub')>
[I 2021-12-17 14:56:23.019 JupyterHub provider:607] Creating oauth client jupyterhub-user-jdoe
[I 2021-12-17 14:56:23.043 JupyterHub spawner:1526] Spawning jupyterhub-singleuser
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import main
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/singleuser/app.py", line 38, in <module>
    raise _import_error
TypeError: exceptions must derive from BaseException
[I 2021-12-17 14:56:24.008 JupyterHub log:189] 302 GET /hub/spawn -> /hub/spawn-pending/jdoe (jdoe@::ffff:172.17.0.1) 1002.82ms
[I 2021-12-17 14:56:24.015 JupyterHub pages:397] jdoe is pending spawn
[I 2021-12-17 14:56:24.018 JupyterHub log:189] 200 GET /hub/spawn-pending/jdoe (jdoe@::ffff:172.17.0.1) 4.63ms
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-33' coro=<BaseHandler.spawn_single_user() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:830> exception=HTTPError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 1031, in spawn_single_user
    await gen.with_timeout(
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 1065, in spawn_single_user
    raise web.HTTPError(
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for jdoe may contain details.)
[W 2021-12-17 14:56:50.978 JupyterHub user:798] jdoe's server never showed up at http://127.0.0.1:51055/user/jdoe/ after 30 seconds. Giving up.

    Common causes of this timeout, and debugging tips:

    1. The server didn't finish starting,
       or it crashed due to a configuration issue.
       Check the single-user server's logs for hints at what needs fixing.
    2. The server started, but is not accessible at the specified URL.
       This may be a configuration issue specific to your chosen Spawner.
       Check the single-user server logs and resource to make sure the URL
       is correct and accessible from the Hub.
    3. (unlikely) Everything is working, but the server took too long to respond.
       To fix: increase `Spawner.http_timeout` configuration
       to a number of seconds that is enough for servers to become responsive.

[E 2021-12-17 14:56:51.003 JupyterHub gen:623] Exception in Future <Task finished name='Task-34' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:934> exception=TimeoutError("Server at http://127.0.0.1:51055/user/jdoe/ didn't respond in 30 seconds")> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 941, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 779, in spawn
        await self._wait_up(spawner)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 823, in _wait_up
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 793, in _wait_up
        resp = await server.wait_up(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 241, in wait_for_http_server
        re = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 189, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    asyncio.exceptions.TimeoutError: Server at http://127.0.0.1:51055/user/jdoe/ didn't respond in 30 seconds

[I 2021-12-17 14:56:51.004 JupyterHub log:189] 200 GET /hub/api/users/jdoe/server/progress (jdoe@::ffff:172.17.0.1) 26920.62ms
```
</details>

**Comment by manics** [comment]
Hi! That docker image isn't designed to be run as a standalone image, it's designed for production use where you'd configure a remote spawner: https://github.com/jupyterhub/jupyterhub#docker

You could try the demo image instead, but note that it's not for production use as it's completely insecure:
- https://hub.docker.com/r/jupyterhub/jupyterhub-demo
- https://github.com/jupyterhub/jupyterhub/tree/main/demo-image

**Comment by chermes** [comment]
Thank you @manics for the fast reply!
I will take a look at the demo notebook.
