### ISSUE TITLE
Admin page doesn't load table

### ISSUE THREAD

**Issue by MrPlumbum82** [jupyterhub/jupyterhub#3865]
### Bug description
The `Admin` page in the Jupyterhub `Control Panel` loads an empty page if a single user from a list of `n` users does not have a spawned playbook (server).

#### Expected behaviour
I would expect to see the complete table/list of users and their spawned playbook servers.
<img width="1310" alt="Screen Shot 2022-04-12 at 3 22 27 PM" src="https://user-images.githubusercontent.com/11234396/163046088-08ed341e-3b4f-4f6c-ad49-090df50b1296.png">

#### Actual behaviour
If a single user from the list shown above would `stop` their server, the admin page breaks and the javascript seems to be accessing the `name` field of a `null` object.
<img width="1311" alt="Screen Shot 2022-04-12 at 3 27 21 PM" src="https://user-images.githubusercontent.com/11234396/163046130-339632f5-b520-41c1-87a1-b884e6197763.png">

### How to reproduce
1. Start-Up a new Juypterhub server
2. Sign in with an `admin` user (automatically creating a playbook server for this user)
3. Visit Admin page (loads fine)
4. Click on the red `Stop Server` button
5. Watch the table will disappear
6. Open the console drawer and view the error message pop up: `cannot read property name of null`

### Your personal set up
My set up consists of running a `jupyterhub/jupyterhub` docker container, with a `postgres` database and a custom `nginx` proxy. I am using the `dockerspawner.swarmspawner` to launch many `single user` playbooks via the following docker image `jupyterhub/singleuser`.

 - OS:
   - ubuntu 20.04

 - Version(s):
   - Python version: 3.8.10
   - Jupyterhub version: 2.2.1
   - oauthenticator.azuread.AzureAdOAuthenticator-14.2.0
   - dockerspawner.swarmspawner.SwarmSpawner-12.1.0

<details><summary>Full environment</summary>

```
alembic @ file:///tmp/wheelhouse/alembic-1.7.6-py3-none-any.whl
async-generator @ file:///tmp/wheelhouse/async_generator-1.10-py3-none-any.whl
attrs @ file:///tmp/wheelhouse/attrs-21.4.0-py2.py3-none-any.whl
certifi @ file:///tmp/wheelhouse/certifi-2021.10.8-py2.py3-none-any.whl
certipy @ file:///tmp/wheelhouse/certipy-0.1.3-py3-none-any.whl
cffi @ file:///tmp/wheelhouse/cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
charset-normalizer @ file:///tmp/wheelhouse/charset_normalizer-2.0.12-py3-none-any.whl
cryptography @ file:///tmp/wheelhouse/cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl
docker==2.7.0
docker-pycreds==0.4.0
dockerspawner==12.1.0
entrypoints @ file:///tmp/wheelhouse/entrypoints-0.4-py3-none-any.whl
escapism==1.0.1
greenlet @ file:///tmp/wheelhouse/greenlet-1.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
idna @ file:///tmp/wheelhouse/idna-3.3-py3-none-any.whl
importlib-metadata @ file:///tmp/wheelhouse/importlib_metadata-4.11.2-py3-none-any.whl
importlib-resources @ file:///tmp/wheelhouse/importlib_resources-5.4.0-py3-none-any.whl
Jinja2 @ file:///tmp/wheelhouse/Jinja2-3.0.3-py3-none-any.whl
jsonschema @ file:///tmp/wheelhouse/jsonschema-4.4.0-py3-none-any.whl
jupyter-telemetry @ file:///tmp/wheelhouse/jupyter_telemetry-0.1.0-py3-none-any.whl
jupyterhub @ file:///tmp/wheelhouse/jupyterhub-2.2.1-py3-none-any.whl
jupyterhub-ldapauthenticator==1.2.2
ldap3==2.9.1
Mako @ file:///tmp/wheelhouse/Mako-1.2.0-py3-none-any.whl
MarkupSafe @ file:///tmp/wheelhouse/MarkupSafe-2.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
oauthenticator==14.2.0
oauthlib @ file:///tmp/wheelhouse/oauthlib-3.2.0-py3-none-any.whl
packaging @ file:///tmp/wheelhouse/packaging-21.3-py3-none-any.whl
pamela @ file:///tmp/wheelhouse/pamela-1.0.0-py2.py3-none-any.whl
prometheus-client @ file:///tmp/wheelhouse/prometheus_client-0.13.1-py3-none-any.whl
psycopg2-binary==2.9.3
pyasn1==0.4.8
pycparser @ file:///tmp/wheelhouse/pycparser-2.21-py2.py3-none-any.whl
pycurl==7.43.0.2
PyJWT==2.3.0
pyOpenSSL @ file:///tmp/wheelhouse/pyOpenSSL-22.0.0-py2.py3-none-any.whl
pyparsing @ file:///tmp/wheelhouse/pyparsing-3.0.7-py3-none-any.whl
pyrsistent @ file:///tmp/wheelhouse/pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
python-dateutil @ file:///tmp/wheelhouse/python_dateutil-2.8.2-py2.py3-none-any.whl
python-json-logger @ file:///tmp/wheelhouse/python_json_logger-2.0.2-py3-none-any.whl
requests @ file:///tmp/wheelhouse/requests-2.27.1-py2.py3-none-any.whl
ruamel.yaml @ file:///tmp/wheelhouse/ruamel.yaml-0.17.21-py3-none-any.whl
ruamel.yaml.clib @ file:///tmp/wheelhouse/ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl
six @ file:///tmp/wheelhouse/six-1.16.0-py2.py3-none-any.whl
SQLAlchemy @ file:///tmp/wheelhouse/SQLAlchemy-1.4.32-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
tornado @ file:///tmp/wheelhouse/tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl
traitlets @ file:///tmp/wheelhouse/traitlets-5.1.1-py3-none-any.whl
urllib3 @ file:///tmp/wheelhouse/urllib3-1.26.8-py2.py3-none-any.whl
websocket-client==1.3.2
zipp @ file:///tmp/wheelhouse/zipp-3.7.0-py3-none-any.whl
```
</details>

<details><summary>Configuration</summary>

```python
# Configuration file for JupyterHub
import os
from oauthenticator.azuread import AzureAdOAuthenticator

c = get_config()

# Help with developing this to get more informative errors
c.Application.log_level = 'DEBUG'

# Login with Azure AD
c.JupyterHub.authenticator_class = AzureAdOAuthenticator
c.AzureAdOAuthenticator.tenant_id = os.environ.get('AAD_TENANT_ID')
# Need to make this dynamic
c.AzureAdOAuthenticator.oauth_callback_url = [REDACTED-URL]
c.AzureAdOAuthenticator.client_id = os.environ.get('AAD_CLIENT_ID')
c.AzureAdOAuthenticator.client_secret = os.environ.get('AAD_CLIENT_SECRET')

# Nginx proxy 
# Force the proxy to only listen to connections to 127.0.0.1 (on port 8000)
c.JupyterHub.bind_url = 'https://0.0.0.0:8000'

# Authentication for prometheus metrics
#  Default: True
c.JupyterHub.authenticate_prometheus = False

# DB connection
c.JupyterHub.db_url = 'postgresql://postgres:{password}@jupyterhub_postgres:5432/{db}'.format(
    password=os.environ['POSTGRES_PASSWORD'],
    db=os.environ['POSTGRES_DB'],
)

# Spawner config
c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner'
network_name = os.environ.get('DOCKER_NETWORK_NAME')
c.SwarmSpawner.network_name = network_name
c.SwarmSpawner.extra_host_config = {'network_mode': network_name}
# Connect to the Hub's
c.SwarmSpawner.hub_connect_url = [REDACTED-URL]
c.SwarmSpawner.use_internal_ip = True
c.SwarmSpawner.pull_policy = "always"
c.SwarmSpawner.image = [REDACTED-URL]

c.SwarmSpawner.name_template= "{username}-{prefix}"

# Admins list if we can't use AzureAD
c.Authenticator.admin_users = {'sadan mallhi'}

```
</details>

<details><summary>Logs</summary>

## Browser Console Error when navigating to Admin Page
```

TypeError: Cannot read properties of null (reading 'name')
    at admin-react.js:2:31608
    at Array.map (<anonymous>)
    at Ye (admin-react.js:2:31533)
    at nl (admin-react.js:2:125170)
    at Fl (admin-react.js:2:134688)
    at $i (admin-react.js:2:178033)
    at ku (admin-react.js:2:164494)
    at wu (admin-react.js:2:164422)
    at bu (admin-react.js:2:164285)
    at du (admin-react.js:2:161360)
ri @ admin-react.js:2

```
</details>

**Comment by minrk** [comment]
I suspect this has been fixed by one of the recent admin page PRs such as #3834
