### ISSUE TITLE
Timeout causes failure when the hub service is republished

### ISSUE THREAD

**Issue by icankeep** [jupyterhub/jupyterhub#3902]
## basic info
JupyterHub version: 1.3.0

We have made some extensions based on jupyterhub and customized the spawner based on our internal container service. 

We have a headache every time we release the hub service, because it often has a greater impact on user usage. For example, this time, when we released the service, it seemed that the probe request of the user container accumulated too much in the hub tornado loop, which caused the interface(/api/routes) to obtain the route to time out at startup. In the end, I changed the [timeout time to 300s](https://github.com/jupyterhub/jupyterhub/blob/a91197635ab1a9d8c9b3d2e83b4f213d0d535d8d/jupyterhub/proxy.py#L828) to start successfully. 

## log stack
```bash
    729 [W 2022-05-14 00:56:00.728 JupyterHub proxy:816] api_request to the proxy failed with status code 599, retrying...
    730 [E 2022-05-14 00:56:00.728 JupyterHub app:2859]
    731     Traceback (most recent call last):
    732       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/app.py", line 2857, in launch_instance_async
    733         await self.start()
    734       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/app.py", line 2722, in start
    735         await self.proxy.check_routes(self.users, self._service_map)
    736       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/proxy.py", line 62, in locked_method
    737         return await method(*args, **kwargs)
    738       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/proxy.py", line 315, in check_routes
    739         routes = await self.get_all_routes()
    740       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/proxy.py", line 861, in get_all_routes
    741         resp = await self.api_request('', client=client)
    742       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/proxy.py", line 828, in api_request
    743         timeout=30,
    744       File "/opt/conda/envs/mtjupyter/lib/python3.6/site-packages/jupyterhub/utils.py", line 183, in exponential_backoff
    745         raise TimeoutError(fail_message)
    746     TimeoutError: Repeated api_request to proxy path "" failed.
    747 
    748 [I 2022-05-14 00:56:08.622 JupyterHub app:2349] Running JupyterHub version 1.3.0
    749 [I 2022-05-14 00:56:08.623 JupyterHub app:2380] Using Authenticator: mtjupyter_hub.sso.SankuaiOAuthenticator
    750 [I 2022-05-14 00:56:08.623 JupyterHub app:2380] Using Spawner: mtjupyter_hub.spawner.HulkSpawner
    751 [I 2022-05-14 00:56:08.623 JupyterHub app:2380] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.3.0
    752 [I 2022-05-14 00:56:08.624 JupyterHub app:1416] Loading cookie_secret from env[JPY_COOKIE_SECRET]
    753 [I 2022-05-14 00:56:08.643 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
    754 [I 2022-05-14 00:56:08.680 JupyterHub app:1726] Not using allowed_users. Any authenticated user will be allowed.

```

**Comment by icankeep** [comment]
Before the release, there were 800 servers in the hub. After the release, there are only more than 100 servers in the hub, but the containers of the disappeared servers are still alive.

**Comment by icankeep** [comment]
Is there an elegant way to solve this problem?

**Comment by manics** [comment]
Hi! JupyterHub 1.3.0 is quite old. Do you still see the same behaviour with the latest version 2.3.0?

If you so see the same problem could you provide us the exact steps to reproduce the issue, including your JupyterHub configuration?

> Before the release, there were 800 servers in the hub. After the release, there are only more than 100 servers in the hub, but the containers of the disappeared servers are still alive.

Do you still see this problem with one of the public open-source spawners?

**Comment by minrk** [comment]
It's strange that there would be contention on the spawner checks, because those are [awaited](https://github.com/jupyterhub/jupyterhub/blob/1.3.0/jupyterhub/app.py#L2443-L2452) before _starting_ the proxy check, so there shouldn't be a lot of concurrent actions going on. It may be that the Spawner class is not actually completing its checks when they are awaited, and starting some background task that's taking time.

Definitely check if jupyterhub 2.3 fixes this, and if not we can investigate things like increasing the 'wait for the proxy' timeout, or possibly restructuring startup so there isn't so much going on at once.

It is definitely odd that the proxy is unavailable for an extended period - is the proxy service usually restarted when the hub is also restarted? That is typically not desirable, as it causes unnecessary service disruptions (Hub restarts are designed to minimize impact for active users, but proxy restarts are highly disruptive).

**Comment by icankeep** [comment]
Thank you for your replies, we really want to experience the new features through the upgrade. I read the upgrade documentation before, and it says that upgrading jupyterhub to 2.x requires shutting down the servers of all users. This is unacceptable to us, so we did not upgrade.

**Comment by icankeep** [comment]
We split the proxy layer and the hub, so that there is no problem with the above

**Comment by icankeep** [comment]
And our cull-idle process is also split into an independent process. It used to be a sub-service of the hub, and it will start quickly after the hub restarts. I think this behavior is inappropriate.

**Comment by minrk** [comment]
More complete startup logs (especially with `--debug`) may help. I'm not sure what the Hub would be doing that would slow down a simple http request to the proxy for 30 seconds if the proxy is indeed running and available. Presumably it's something in the Spawner, but only logs during the time between the start of the request and its eventual timeout can tell us.

Does your hub have `pycurl` available? I know the fallback tornado `SimpleAsyncHTTPClient` has performance and timeout issues when there are a lot of users, which is why we prefer pycurl by default, but it is not a strict dependency.
