### ISSUE TITLE
Possible race condition with idle-culler

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#3956]
### Bug description

The following has shown up in several of our hubs' logs when they get redeployed and start up:
```
[W 2022-06-22 17:43:26.841 JupyterHub log:189] 403 GET /hub/api/users?state=[secret] (jupyterhub-idle-culler@127.0.0.1) 5.25ms
[E 220622 17:43:26 ioloop:761] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f4880030a30>>, <Task finished name='Task-1' coro=<cull_idle() done, defined at /usr/local/lib/python3.9/site-packages/jupyterhub_idle_culler/__init__.py:73> exception=HTTP 403: Forbidden>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.9/site-packages/jupyterhub_idle_culler/__init__.py", line 422, in cull_idle
        async for user in fetch_paginated(req):
      File "/usr/local/lib/python3.9/site-packages/jupyterhub_idle_culler/__init__.py", line 135, in fetch_paginated
        response = await resp_future
      File "/usr/local/lib/python3.9/site-packages/jupyterhub_idle_culler/__init__.py", line 117, in fetch
        return await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

The idle culler is running and does appear to be working.
#### Expected behaviour

idle-culler would be able to access the api endpoint without error, or this async-y condition is accounted for and emits a message instead of an exception.

### How to reproduce

This is on hub startup.

### Your personal set up

https://github.com/berkeley-dsep-infra/datahub

helm chart 1.1.3-n554.hfa81c67f
jupyterhub 2.3.0
jupyterhub-idle-culler 1.2.1

<details><summary>Full environment</summary>

```
authenticator==14.2.0
oauthlib==3.2.0
onetimepass==1.0.1
packaging==21.3
pamela==1.0.0
pem==21.2.0
prometheus-client==0.14.1
psycopg2-binary==2.9.3
py-spy==0.3.12
pyasn1==0.4.8
pycparser==2.21
pycryptodome==3.14.1
pycryptodomex @ file:///tmp/pre-built-wheels/pycryptodomex-3.14.1-cp35-abi3-manylinux2010_x86_64.whl
pycurl @ file:///tmp/pre-built-wheels/pycurl-7.45.1-cp39-cp39-linux_x86_64.whl
pyjwkest==1.4.2
PyJWT==1.7.1
PyMySQL==1.0.2
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-json-logger==2.0.2
python-slugify==6.1.2
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.1
ruamel.yaml==0.17.21
ruamel.yaml.clib @ file:///tmp/pre-built-wheels/ruamel.yaml.clib-0.2.6-cp39-cp39-manylinux1_x86_64.whl
six==1.16.0
SQLAlchemy==1.4.36
sqlalchemy-cockroachdb==1.4.3
statsd==3.3.0
text-unidecode==1.3
tornado==6.1
traitlets==5.2.1.post0
urllib3==1.26.9
wrapt==1.14.1
yarl==1.7.2
```
</details>

<details><summary>Configuration</summary>

[kubespawner](https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L301)
[canvasauthenticator](https://github.com/berkeley-dsep-infra/datahub/tree/staging/images/hub/canvasauthenticator) 

</details>

**Comment by consideRatio** [comment]
> The following has shown up in several of our hubs' logs when they get redeployed and start up:

So this happens once, but no more, or a few times but then no more? Hmmm, is the credentials for the jupyterhub-idle-culler not loaded into jupyterhub fast enough to be accepted?

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/87326ff4f97c9f74e48939661d7154f2aa77c2a6/jupyterhub/files/hub/jupyterhub_config.py#L384-L390

I note [that z2jh's config](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/87326ff4f97c9f74e48939661d7154f2aa77c2a6/jupyterhub/files/hub/jupyterhub_config.py#L384-L390) does `load_role` after we define the services referencing the role, but i doubt this is an issue. When we see the 403 response from jupyterhub, to me that indicates jupyterhub has started successfully, but concludes its invalid credentials provided along with the request.

Hmmm... I suspect there is a real bug in jupyterhub here, but I'm not sure.

**Comment by ryanlovett** [comment]
> So this happens once, but no more, or a few times but then no more?

Sorry, my original report was flawed. This is actually happening much more often, e.g. thousands of times, and continously, over a couple of days. I had sorted /hub/admin to view running users but it seems to only sort entries on that page, not by all users. In looking directly at the age of running pods (which I should have done), I see that many are as old as a couple weeks and the hub reports no activity for those users. So idle-culler is not working and isn't just at hub startup.

**Comment by yuvipanda** [comment]
We're running master of z2jh, so this could be something there.

**Comment by consideRatio** [comment]
Ah, I presume this will be resolved by configuration fix in https://github.com/berkeley-dsep-infra/datahub/pull/3475 and go ahead and close this for now.
