### ISSUE TITLE
Long-running JupyterLab instance on JupyterHub crashes with `received signal 15, stopping`

### ISSUE THREAD

**Issue by afshin** [jupyterhub/jupyterhub#3961]
This is a cross-post of [an issue originally opened in JupyterLab](https://github.com/jupyterlab/jupyterlab/issues/12702) by @RanadeepPolavarapu. 

We are not sure what the root cause of it is and thought it prudent to post here in case it looks familiar to you folks.

### Bug description
Description from the original issue:
> Our users who have their JuypterLab instances open and continuously running for days will occasionally experience an issue where JuypterLab crashes. I have provided the logs showing the exact occurrence. This is the same set of logs that will be produced each time this issue happens where JuypterLab crashes.

> ![](https://user-images.githubusercontent.com/7084995/173839592-db0b594b-5272-4166-a2fd-319fb2c2cef4.png)

### How to reproduce
Steps to reproduce from original issue:
> 1. Create a decent number of kernels running at the same time with notebooks open. In our case 7 kernels were active.
> 2. Let it sit for days with your browser active on the page or in the background.
> 3. It will randomly disconnect the JLab when it crashes.

### Your personal set up

> - Operating System and version: Linux Ubuntu 20.04.2 (using Docker image jupyter/scipy-notebook:python-3.8.8)
> - Browser and version: Chrome 101
> - JupyterLab version: 3.0.16
> - JupyterHub version: 1.5.0

> Our architecture is running JupyterLab on JupyterHub with Kubespawner on AWS EKS Kubernetes cluster.

> We notice that as soon as JupyterLab crashes in this case, the JupyterHub also crashes subsequently after with an error but point of origination appears to coming from JupyterLab first.

<details>
<summary>From the JupyterLab logs:</summary>
<pre>
[I 2022-06-14 23:52:47.596 SingleUserNotebookApp management:199] EOF on FD 13; stopping reading
[I 2022-06-14 23:52:47.595 SingleUserNotebookApp serverapp:1904] Shutting down 1 terminal
Websocket closed
[I 2022-06-14 23:52:46.703 SingleUserNotebookApp kernelmanager:268] Starting buffering for 8765964c-14ec-44f8-9d48-45270f8aae86:678da080-49a2-4f03-a67c-ccf4b1caa7f1
[I 2022-06-14 23:52:46.701 SingleUserNotebookApp kernelmanager:268] Starting buffering for a8c22114-8b1d-486d-bcae-ec553c4771fb:a61671b9-a380-4b6b-aa5e-f9969122cead
[I 2022-06-14 23:52:46.702 SingleUserNotebookApp kernelmanager:268] Starting buffering for 0789acfa-3069-4265-8420-c487db467705:07d075cb-7722-48b0-bf01-d14266490b0d
[I 2022-06-14 23:52:46.702 SingleUserNotebookApp kernelmanager:268] Starting buffering for 210d5b0a-49f6-4634-8060-d44914110730:6206d02e-53dd-4636-884a-8d3c3baa6d94
[I 2022-06-14 23:52:45.885 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 040b6e6a-4a17-4750-8d10-3dacf6eece30
[I 2022-06-14 23:52:45.884 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: a8c22114-8b1d-486d-bcae-ec553c4771fb
[I 2022-06-14 23:52:45.885 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 0789acfa-3069-4265-8420-c487db467705
[I 2022-06-14 23:52:45.883 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 8765964c-14ec-44f8-9d48-45270f8aae86
[I 2022-06-14 23:52:45.884 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 210d5b0a-49f6-4634-8060-d44914110730
[I 2022-06-14 23:52:45.883 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 41f7c9b6-9760-4a65-87ef-c7127bf6a57b
[I 2022-06-14 23:52:45.882 SingleUserNotebookApp multikernelmanager:240] Kernel shutdown: 8f8a092c-944f-443e-a337-7c141a5be775
[I 2022-06-14 23:52:45.882 SingleUserNotebookApp serverapp:1889] Shutting down 7 kernels
[C 2022-06-14 23:52:45.881 SingleUserNotebookApp serverapp:1652] received signal 15, stopping
[C 2022-06-14 23:52:45.881 SingleUserNotebookApp serverapp:1652] received signal 15, stopping
</pre>

JupyterHub logs when this happens:
```
07:58:54.000 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/terminals/websocket/1 read ECONNRESET
[I 2022-06-16 07:58:54.002 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fterminals%2Fwebsocket%2F1 (@10.99.55.63) 1.29ms
07:58:54.127 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/6ec6ed9c-2956-4e16-bcff-ec7963aa41dc/channels connect ECONNREFUSED 10.99.54.241:8888
07:58:54.129 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end
[I 2022-06-16 07:58:54.129 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F6ec6ed9c-2956-4e16-bcff-ec7963aa41dc%2Fchannels%3Fsession_id%3D8fc91f8a-d8b6-4e1f-936d-65ffb4282858 (@10.99.55.63) 1.13ms
07:58:54.129 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Socket.Writable.write (_stream_writable.js:296:5)
    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07:58:54.192 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/6ec6ed9c-2956-4e16-bcff-ec7963aa41dc/channels connect ECONNREFUSED 10.99.54.241:8888
07:58:54.193 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end
[I 2022-06-16 07:58:54.193 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F6ec6ed9c-2956-4e16-bcff-ec7963aa41dc%2Fchannels%3Fsession_id%3D4179c033-0d82-4f9b-b54e-fe92b4424534 (@10.99.55.63) 1.06ms
07:58:54.193 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Socket.Writable.write (_stream_writable.js:296:5)
    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07:58:54.284 [ConfigProxy] [31merror[39m: 503 PUT /user/johndoe/lab/api/workspaces/default connect ECONNREFUSED 10.99.54.241:8888
[I 2022-06-16 07:58:54.286 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Flab%2Fapi%2Fworkspaces%2Fdefault%3F1655366334127 (@10.99.55.63) 0.99ms
[I 2022-06-16 07:58:56.712 JupyterHub spawner:2716] Deleting pod team/jupyter-johndoe
[W 2022-06-16 07:58:56.765 JupyterHub app:2151] User johndoe server stopped with exit code: 1
[I 2022-06-16 07:58:56.765 JupyterHub proxy:309] Removing user johndoe from proxy (/user/johndoe/)
07:58:56.766 [ConfigProxy] [32minfo[39m: Removing route /user/johndoe
07:58:56.766 [ConfigProxy] [32minfo[39m: 204 DELETE /api/routes/user/johndoe 
```
</details>

Attached the troubleshoot logs below in a file, content didn't fit in the GitHub issue.
[troubleshoot.txt](https://github.com/jupyterlab/jupyterlab/files/8909836/troubleshoot.txt)

**Comment by manics** [comment]
That ConfigProxy error just means the JupyterHub proxy couldn't connect to the singleuser server, since it's crashed this is to be expected.

I can't see anything JupyterHub related so far. Have you tried reproducing the error without JupyterHub, i.e. running the container directly?

**Comment by RanadeepPolavarapu** [comment]
These are the reproduction steps with JupyterLab + JupyterHub setup:

## Reproduction Steps
1. Create a decent number of kernels running at the same time with notebooks open. In our case 7 kernels were active.
2. Let it sit for days with your browser active on the page or in the background.
3. It will randomly disconnect the JLab when it crashes.3

However, this issue happens inconsistently so we aren't exactly sure on what specifically causes this `Starting buffering` followed by `kernel shutdown` and `received signal 15, stopping`. Our researchers run into this weekly though across a large number of users (around 50 users online at any given time and at least a handful run into this weekly).

**Comment by minrk** [comment]
Do you have idle culling enabled? Checking the JupyterHub logs may be useful.

**Comment by RanadeepPolavarapu** [comment]
@minrk We do have idle culling enabled but the users who experienced this issue are exempt from idle culler.

**Comment by minrk** [comment]
Can you include the logs from the hub starting a bit _before_ the shutdown signal (the logs given start only after the Hub has noticed it shut down, not when the shutdown is requested)? Maybe also cloud logs relating to the `jupyter-johndoe` pod?

Since it's getting signal 15 (SIGTERM), I _strongly_ suspect something is explicitly terminating the pod from outside. The fact that JupyterHub is _reacting_ to pod shutdown instead of _initiating_ it makes me think it isn't JupyterHub at all, but rather something in the cluster (perhaps a resource exhaustion) terminating the pod. This should show up in the pod events, but may not appear in the JupyterHub logs.

**Comment by RanadeepPolavarapu** [comment]
I checked the kube event logs to see if it's resource exhaustion but we have log rotation on Docker daemon level inside the EKS nodes enabled so disk usage from our metrics was well within the limit. The CPU and memory usage was also within the limit. 

When we trigger a shutdown from Hub itself by hitting the stop server button we see the SIGTERM 15 log still. Logs of this case where trigger a shutdown from Hub:
![image](https://user-images.githubusercontent.com/7084995/185423421-ec78d50f-10c6-46b7-a4e8-ba2b76b16835.png)

**Comment by RanadeepPolavarapu** [comment]
Here is the Hub logs prior to the shutdown:

```
Aug 14, 2022 @ 23:05:32.798	[I 2022-08-15 03:05:32.798 JupyterHub log:189] 302 GET /hub/home -> /hub/login?next=%2Fhub%2Fhome (@::ffff:10.99.59.73) 0.65ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:05:38.232	03:05:38.232 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:05:38.399	[I 2022-08-15 03:05:38.398 JupyterHub proxy:347] Checking routes	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:01.901	03:06:01.901 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/terminals/websocket/1 read ECONNRESET	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:01.902	03:06:01.902 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/2d9f7500-72b3-41f8-b570-c08aebfe2621/channels read ECONNRESET	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:01.904	[I 2022-08-15 03:06:01.904 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fterminals%2Fwebsocket%2F1 (@10.99.49.243) 1.18ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:01.905	[I 2022-08-15 03:06:01.905 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F2d9f7500-72b3-41f8-b570-c08aebfe2621%2Fchannels%3Fsession_id%3Dd6d70a9e-33e4-46b6-b7d2-7d680b4bda0e (@10.99.49.243) 0.90ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.114	03:06:02.113 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/85737b07-a984-4084-95a9-975c0481c197/channels connect ECONNREFUSED 10.99.57.101:8888	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	03:06:02.115 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at IncomingMessage.emit (events.js:198:13)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at IncomingMessage.Readable.read (_stream_readable.js:505:10)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at resume_ (_stream_readable.js:955:3)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at process._tickCallback (internal/process/next_tick.js:63:19)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	[I 2022-08-15 03:06:02.115 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F85737b07-a984-4084-95a9-975c0481c197%2Fchannels%3Fsession_id%3D86f1851d-907e-4a7a-9107-01d7451b9ef1 (@10.99.49.243) 0.90ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	03:06:02.115 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at writeAfterEnd (_stream_writable.js:248:12)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at Socket.Writable.write (_stream_writable.js:296:5)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.115	    at flow (_stream_readable.js:974:34)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.228	03:06:02.227 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/8f014e82-9a97-4490-afda-ace64861c620/channels connect ECONNREFUSED 10.99.57.101:8888	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	03:06:02.229 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	03:06:02.229 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at writeAfterEnd (_stream_writable.js:248:12)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at Socket.Writable.write (_stream_writable.js:296:5)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at IncomingMessage.emit (events.js:198:13)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at IncomingMessage.Readable.read (_stream_readable.js:505:10)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at process._tickCallback (internal/process/next_tick.js:63:19)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	[I 2022-08-15 03:06:02.229 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F8f014e82-9a97-4490-afda-ace64861c620%2Fchannels%3Fsession_id%3Dc0a9fa2b-0a84-43f9-92d9-32c8d20e82d7 (@10.99.49.243) 1.10ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at flow (_stream_readable.js:974:34)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.229	    at resume_ (_stream_readable.js:955:3)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.318	03:06:02.318 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/1db5ea72-889a-4ea2-bd67-6dac00d0d09f/channels connect ECONNREFUSED 10.99.57.101:8888	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at writeAfterEnd (_stream_writable.js:248:12)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at Socket.Writable.write (_stream_writable.js:296:5)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at IncomingMessage.emit (events.js:198:13)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at process._tickCallback (internal/process/next_tick.js:63:19)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	03:06:02.320 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	[I 2022-08-15 03:06:02.320 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F1db5ea72-889a-4ea2-bd67-6dac00d0d09f%2Fchannels%3Fsession_id%3D9e07a197-3a2e-4c23-b159-e861946a7ae0 (@10.99.49.243) 0.94ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	03:06:02.320 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at IncomingMessage.Readable.read (_stream_readable.js:505:10)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at flow (_stream_readable.js:974:34)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.320	    at resume_ (_stream_readable.js:955:3)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.411	03:06:02.411 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/080777b2-ecb8-4956-b49f-8ba22966cb86/channels connect ECONNREFUSED 10.99.57.101:8888	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at writeAfterEnd (_stream_writable.js:248:12)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at Socket.Writable.write (_stream_writable.js:296:5)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at IncomingMessage.emit (events.js:198:13)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at process._tickCallback (internal/process/next_tick.js:63:19)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	03:06:02.413 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	[I 2022-08-15 03:06:02.413 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F080777b2-ecb8-4956-b49f-8ba22966cb86%2Fchannels%3Fsession_id%3Dd487d802-08d6-4296-b0b8-3013daf6d80b (@10.99.49.243) 0.89ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	03:06:02.413 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at IncomingMessage.Readable.read (_stream_readable.js:505:10)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at flow (_stream_readable.js:974:34)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.413	    at resume_ (_stream_readable.js:955:3)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.502	03:06:02.502 [ConfigProxy] [31merror[39m: 503 GET /user/johndoe/api/kernels/13ed1ce8-1d27-41a4-a6f5-9f8dcf0222a8/channels connect ECONNREFUSED 10.99.57.101:8888	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.503	03:06:02.503 [ConfigProxy] [31merror[39m: Uncaught Exception: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.503	[I 2022-08-15 03:06:02.503 JupyterHub log:189] 200 GET /hub/error/503?url=%2Fuser%2Fjohndoe%2Fapi%2Fkernels%2F13ed1ce8-1d27-41a4-a6f5-9f8dcf0222a8%2Fchannels%3Fsession_id%3De900d3c7-c38a-467b-9214-b63fc60aa10a (@10.99.49.243) 0.92ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at IncomingMessage.Readable.read (_stream_readable.js:505:10)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at flow (_stream_readable.js:974:34)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at process._tickCallback (internal/process/next_tick.js:63:19)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	03:06:02.503 [ConfigProxy] [31merror[39m: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at writeAfterEnd (_stream_writable.js:248:12)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at Socket.Writable.write (_stream_writable.js:296:5)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at IncomingMessage.upstream.on (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:479:52)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at IncomingMessage.emit (events.js:198:13)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:02.504	    at resume_ (_stream_readable.js:955:3)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:28.148	[I 2022-08-15 03:06:28.148 JupyterHub proxy:309] Removing user johndoe from proxy (/user/johndoe/)	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:28.148	[W 2022-08-15 03:06:28.148 JupyterHub app:2151] User johndoe server stopped with exit code: 1	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:28.149	03:06:28.149 [ConfigProxy] [32minfo[39m: Removing route /user/johndoe	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:28.149	03:06:28.149 [ConfigProxy] [32minfo[39m: 204 DELETE /api/routes/user/johndoe 	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:06:32.831	[I 2022-08-15 03:06:32.831 JupyterHub log:189] 302 GET /hub/home -> /hub/login?next=%2Fhub%2Fhome (@::ffff:10.99.55.18) 0.66ms	cmf-rig	jupyterhub-568d768b5f-4kgzd
Aug 14, 2022 @ 23:07:01.613	03:07:01.613 [ConfigProxy] [31merror[39m: 503 PUT /user/johndoe/lab/api/workspaces/default socket hang up	cmf-rig	jupyterhub-568d768b5f-4kgzd
```

**Comment by minrk** [comment]
The Hub logs at least confirm my suspicion that the Hub is _not_ shutting down the server, nor is it jupyter-server's internal culling. It is definitely _something else_. I think only kubernetes events / cluster logs will be able to shed light on this, not anything from Jupyter.

**Comment by sokratisg** [comment]
@RanadeepPolavarapu care to share some more details or even a hint, of course provided you can without exposing sensitive info.

We're having a similar, occasional issue but so far haven't invested the time we'd need to track it down.

In your case was it caused by something running on k8s (ie. cluster-autoscaler) or something completely different?

**Comment by csaroff** [comment]
For me, this happened because the pod ran out of memory. Would be nice if this could be surfaced to the user in a more obvious way.

With autoscaling and culling enabled, my first instinct was that the culler was the root cause. The node that the pod was running on was scaled down before I got a chance to run a `kubectl describe node` so it wasn't clear that the pod was running out of memory.

Luckily, we're running prometheus & grafana which helped diagnose the issue. It took me a while to debug, so hopefully this helps the next person

**Comment by minrk** [comment]
I think having an annotation for stopped servers that records _why_ they stopped last would be super useful. I think that's going to be quite challenging for the different Spawner implementations, but should be doable.  It should be easy enough to at least distinguish between:

- explicitly shutdown, and by whom (this will tell you: user shutdown, idle culler)
- shutdown cleanly (e.g. internal self-cull, shutdown via UI or plugin)
- crashed (OOM more often than anything else)

The next bit is where to surface that information in UI, which I'm not sure about.
