### ISSUE TITLE
Unhandled error starting single user spawner

### ISSUE THREAD

**Issue by LTKy** [jupyterhub/jupyterhub#4004]
An error occurred while starting jupyterhub, and the error stacks are as follows:
```
[E 2022-08-08 11:26:51.238 JupyterHub user:817] Unhandled error starting mtp's server: expected str, bytes or os.PathLike object, not NoneType 
    Traceback (most recent call last): 
      File "/opt/huawei/miniconda/envs/python36/lib/python3.6/site-packages/jupyterhub/user.py", line 732, in spawn 
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f) 
      File "/opt/huawei/miniconda/envs/python36/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1573, in start 
        self.proc = Popen(cmd, **popen_kwargs) 
      File "/opt/huawei/miniconda/envs/python36/lib/python3.6/subprocess.py", line 729, in __init__ 
        restore_signals, start_new_session) 
      File "/opt/huawei/miniconda/envs/python36/lib/python3.6/subprocess.py", line 1275, in _execute_child 
        env_list.append(k + b'=' + os.fsencode(v)) 
      File "/opt/huawei/miniconda/envs/python36/lib/python3.6/os.py", line 800, in fsencode 
        filename = fspath(filename)  # Does type-checking of `filename`. 
    TypeError: expected str, bytes or os.PathLike object, not NoneType 
     
[E 2022-08-08 11:26:51.283 JupyterHub pages:317] Error starting server mtp: expected str, bytes or os.PathLike object, not NoneType 
    Traceback (most recent call last): 
    None: None 
```

Don't know how to fix it, ask for help.

**Comment by consideRatio** [comment]
Hi!

Please ask for help in discourse.jupyter.org and include details on how and where you have installed and configured jupyterhub.
