### ISSUE TITLE
unable to launch server ModuleNotFoundError: No module named 'jupyter_server'

### ISSUE THREAD

**Issue by Fxe** [jupyterhub/jupyterhub#4242]
### Bug description

Docker image Jupyterhub is unable to launch server

### How to reproduce

> docker run -p 8000:8000 -d --name jupyterhub jupyterhub/jupyterhub jupyterhub
> docker exec -it jupyterhub bash
> useradd -m guest
> passwd guest

> docker logs -f jupyterhub

```
[I 2022-12-01 21:19:40.027 JupyterHub spawner:1674] Spawning jupyterhub-singleuser
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/usr/local/lib/python3.10/dist-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import SingleUserNotebookApp, main
  File "/usr/local/lib/python3.10/dist-packages/jupyterhub/singleuser/app.py", line 38, in <module>
    raise _import_error
  File "/usr/local/lib/python3.10/dist-packages/jupyterhub/singleuser/app.py", line 30, in <module>
    App = import_item(JUPYTERHUB_SINGLEUSER_APP)
  File "/usr/local/lib/python3.10/dist-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server'

```

**Comment by manics** [comment]
The docker image only contains JupyterHub, it doesn't contain all the singleuser components as the expectation is they'll be run somewhere else.
