### ISSUE TITLE
Jupyterhub Proxy TimeoutError on very slow systems

### ISSUE THREAD

**Issue by atrawog** [jupyterhub/jupyterhub#4308]
### Bug description

The Jupyterhub Proxy has a hard coded timeout value of one second for the proxy startup.

https://github.com/jupyterhub/jupyterhub/blob/38ba275367936c9a5a081a7b5acf326134705a0a/jupyterhub/proxy.py#L785

On a very slow systems one second isn't long enough and can cause intermittent startup issues. Especial on a system that's still busy with booting or compiling .pyc files.  

```
Jan 24 13:01:18 jpi jupyterhub[424]: [I 2023-01-24 13:01:18.626 JupyterHub proxy:750] Starting proxy @ http://:8000
Jan 24 13:01:30 jpi jupyterhub[424]: [C 2023-01-24 13:01:30.342 JupyterHub app:3091] Failed to start proxy
Jan 24 13:01:30 jpi jupyterhub[424]:     Traceback (most recent call last):
Jan 24 13:01:30 jpi jupyterhub[424]:       File "/micromamba/lib/python3.9/site-packages/jupyterhub/app.py", line 3089, in start
Jan 24 13:01:30 jpi jupyterhub[424]:         await self.proxy.start()
Jan 24 13:01:30 jpi jupyterhub[424]:       File "/micromamba/lib/python3.9/site-packages/jupyterhub/proxy.py", line 785, in start
Jan 24 13:01:30 jpi jupyterhub[424]:         await server.wait_up(1)
Jan 24 13:01:30 jpi jupyterhub[424]:       File "/micromamba/lib/python3.9/site-packages/jupyterhub/utils.py", line 243, in wait_for_server
Jan 24 13:01:30 jpi jupyterhub[424]:         await exponential_backoff(
Jan 24 13:01:30 jpi jupyterhub[424]:       File "/micromamba/lib/python3.9/site-packages/jupyterhub/utils.py", line 236, in exponential_backoff
Jan 24 13:01:30 jpi jupyterhub[424]:         raise asyncio.TimeoutError(fail_message)
Jan 24 13:01:30 jpi jupyterhub[424]:     asyncio.exceptions.TimeoutError: Server at jpi:8000 didn't respond in 1 seconds
```

In my case the simple way to fix the issue is to change line 785 in proxy.py to:

```
            await server.wait_up(10)
```

#### Expected behaviour

The Proxy Timeout should be a configurable option in jupyterhub_config.py and not a hard coded value in the code. 

#### Actual behaviour

The JupyterHub startup fails with a cryptic error message.

### How to reproduce

Run JupyterHub on a very slow systems

### Your personal set up

 - Pi OS 11 64 bit running on qemu-system-aarch64 emulating a Raspberry 3b+
 - jupyterhub 3.1.0  pyh2a2186d_0  conda-forge

**Comment by minrk** [comment]
@atrawog makes sense, want to make a PR with that change?

**Comment by sclaybon** [comment]
If there is anyone still looking into this. Is there another way around updating the source file? Like a config of some sort?

**Comment by minrk** [comment]
This has actually been fixed by #4561, which is not yet been released, but should be in 4.1 in the coming weeks. I'm afraid there is no workaround other than running the proxy [externally](https://jupyterhub.readthedocs.io/en/latest/howto/separate-proxy.html) given how this is written. Running the proxy as its own service is always a good idea in production (i.e. its own service / systemd unit / container / etc.).
