### ISSUE TITLE
JupyterHub is broken due to latest release of SqlAlchemy 

### ISSUE THREAD

**Issue by dclong** [jupyterhub/jupyterhub#4312]
### Bug description

JupyterHub installed using `pip3 install jupyterhub` fails to launch with the following error messages due to a breaking release of SqlAlchemy (2.0.0). 
```
[I 2023-01-26 17:04:14.612 JupyterHub app:2810] Running JupyterHub version 3.1.0
[I 2023-01-26 17:04:14.612 JupyterHub app:2840] Using Authenticator: jupyterhub.auth.PAMAuthenticator-3.1.0
[I 2023-01-26 17:04:14.612 JupyterHub app:2840] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-3.1.0
[I 2023-01-26 17:04:14.612 JupyterHub app:2840] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.1.0
[I 2023-01-26 17:04:14.613 JupyterHub app:1694] Writing cookie_secret to /root/jupyterhub_cookie_secret
[E 2023-01-26 17:04:14.618 JupyterHub app:3334]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 3331, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 2852, in initialize
        self.init_db()
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 1823, in init_db
        self.session_factory = orm.new_session_factory(
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/orm.py", line 1061, in new_session_factory
        check_db_revision(engine)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/orm.py", line 953, in check_db_revision
        current_table_names = set(inspect(engine).get_table_names())
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/inspection.py", line 111, in inspect
        ret = reg(subject)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/reflection.py", line 304, in _engine_insp
        return Inspector._construct(Inspector._init_engine, bind)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/reflection.py", line 237, in _construct
        init(self, bind)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/reflection.py", line 248, in _init_engine
        engine.connect().close()
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3245, in connect
        return self._connection_cls(self)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 174, in __init__
        self.dispatch.engine_connect(self)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/attr.py", line 487, in __call__
        fn(*args, **kw)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/event/legacy.py", line 100, in wrap_leg
        return fn(*conv(*args))
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/orm.py", line 919, in ping_connection
        connection.scalar(select([1]))
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/_selectable_constructors.py", line 493, in select
        return Select(*entities)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/selectable.py", line 5219, in __init__
        self._raw_columns = [
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/selectable.py", line 5220, in <listcomp>
        coercions.expect(
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/coercions.py", line 413, in expect
        resolved = impl._literal_coercion(
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/coercions.py", line 652, in _literal_coercion
        self._raise_for_expected(element, argname)
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/coercions.py", line 1143, in _raise_for_expected
        return super()._raise_for_expected(
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/coercions.py", line 711, in _raise_for_expected
        super()._raise_for_expected(
      File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/coercions.py", line 536, in _raise_for_expected
        raise exc.ArgumentError(msg, code=code) from err
    sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [1]. Did you mean to say select(1)?
    
```

#### Expected behaviour

JupyterHub installed by `pip3 install jupyterhub` should work out-of-the-box instead of requiring users to restrict its dependencies when installing it. 

#### Actual behaviour

See the bug description.

### How to reproduce

1. Install JupyterHub with `pip3 install jupyterlab jupyterhub`
2. Launch JupyterHub 

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by minrk** [comment]
3.1.1 is out with the fix. Please report back again if you still have issues!
