### ISSUE TITLE
`jupyterhub/tests/test_singleuser.py::test_singleuser_app_class[notebook.notebookapp.NotebookApp]` fails with dev traitlets

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#4418]
### Bug description
`jupyterhub/tests/test_singleuser.py::test_singleuser_app_class[notebook.notebookapp.NotebookApp]` fails when dev traitlets are installed

#### Expected behaviour

JupyterHub CI tests should pass

#### Actual behaviour

When https://github.com/ipython/traitlets/tree/0505aef059b03bc93638533af9933004ffe23074 is installed in the Python 3.11 `main_dependencies` test:
https://github.com/jupyterhub/jupyterhub/blob/6502b50576cc2196c77b126ebe206f99f3e683dd/.github/workflows/test.yml#L166-L168
One test fails, due to:
```
$ JUPYTERHUB_SINGLEUSER_APP=notebook.notebookapp.NotebookApp python -m jupyterhub.singleuser --help-all

Traceback (most recent call last):
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/traitlets/traitlets.py", line 1953, in _resolve_string
    return import_item(string)
           ^^^^^^^^^^^^^^^^^^^
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/test/work/jupyter/jupyterhub/jupyterhub/singleuser/__init__.py", line 67, in <module>
    from .app import SingleUserNotebookApp, main
  File "/test/work/jupyter/jupyterhub/jupyterhub/singleuser/app.py", line 51, in <module>
    SingleUserNotebookApp = make_singleuser_app(App)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/work/jupyter/jupyterhub/jupyterhub/singleuser/mixins.py", line 904, in make_singleuser_app
    empty_parent_app = App()
                       ^^^^^
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/traitlets/traitlets.py", line 1239, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/traitlets/traitlets.py", line 1282, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/traitlets/traitlets.py", line 1258, in setup_instance
    init(self)
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/notebook/traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "/test/mambaforge/envs/py11/lib/python3.11/site-packages/notebook/traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

https://github.com/ipython/traitlets/blob/0505aef059b03bc93638533af9933004ffe23074/traitlets/utils/warnings.py#L6-L11
requires a `stacklevel` kwarg but
https://github.com/jupyter/notebook/blob/v6.5.4/notebook/traittypes.py#L238
doesn't pass it

**Comment by manics** [comment]
@blink1073 Is this breakage due to https://github.com/ipython/traitlets/pull/838 intended?

**Comment by blink1073** [comment]
`traitlets.warn` was never a part of the public API (it wasn't part of `_all_`).  The bug here is that `notebook.traittypes` is importing `warn` from `traitlets` instead of `warnings`.

**Comment by I-Am-D-B** [comment]
Did this bug somehow get re-introduced?  I'm getting essentially the same thing with 6.5.5, when I didn't yesterday, it looks like.

```
Traceback (most recent call last):
  File ".......venv/lib/python3.10/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File ".......venv/lib/python3.10/site-packages/traitlets/traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File ".......venv/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'
```

```
rm -rf venv/
python3.10 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools
pip install ~/code/inSequioPrime/python/inSequioPyApi/dist/inSequioPyApi-1.0.1.28-py3-none-any.whl 
pip install --force-reinstall -v "notebook>=6,<7"
jupyter-notebook 
```

Effectively, this worked yesterday, jupyter-notebook 6.5.5 failing to start notebook server today.  Only relevant thing I found.  Some underlying dependency that's not pinned for 6.5.5 change?

**Comment by minrk** [comment]
@I-Am-D-B I don't think that's related. I think you're hitting https://github.com/jupyter/notebook/issues/7048 which is a bug in notebook, but also a backward-incompatible change in traitlets 5.10 that probably needs reverting. Pinning `traitlets<5.10` should fix it for now.

**Comment by minrk** [comment]
Closing in favor of the jupyter/notebook issue.

**Comment by I-Am-D-B** [comment]
Thanks @minrk.  I did:

`pip install --force-reinstall -v "traitlets<5.10"` and now `jupyter-notebook` runs.

Back to what I was trying to actually debug 2 days ago...

**Comment by msamhoud** [comment]
Thanks @minrk 
`pip install --force-reinstall -v "traitlets<5.10"` fixed the problem
