### ISSUE TITLE
ValueError: I don't know how to create users on OS X

### ISSUE THREAD

**Issue by cooltheobob** [jupyterhub/jupyterhub#4613]
### Bug description

I'm new to jupyterhub, now I'm testing on my MacBook, but when i run the start command it throws an exception. Does jupyterhub doesn't support MacBook? Thank you!

### How to reproduce
Run the start command
```
jupyterhub -f jupyterhub_config.py
```

#### Expected behaviour

It can be successful and can add user automaticly

#### Actual behaviour
```
[E 2023-10-25 15:42:52.980 JupyterHub app:1995] Error adding user kaylee already in db
    Traceback (most recent call last):
      File "/data_science/lib/python3.9/site-packages/jupyterhub/app.py", line 1993, in init_users
        await maybe_future(f)
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 900, in add_user
        await maybe_future(self.add_system_user(user))
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 954, in add_system_user
        cmd = [arg.replace('USERNAME', name) for arg in self.add_user_cmd]
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 719, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 629, in get
        default = obj.trait_defaults(self.name)
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 1907, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 1260, in __call__
        return self.func(*args, **kwargs)
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 833, in _add_user_cmd_default
        raise ValueError("I don't know how to create users on OS X")
    ValueError: I don't know how to create users on OS X
```

### Your personal set up

I changed the jupyterhub_config.py but it doesn't work

 - OS: MacOS14
 - Version(s): python(3.9.18) jupyterhub(4.0.2)

<details><summary>Full environment</summary>

```
alembic==1.12.0
anyio==4.0.0
appnope==0.1.3
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.0
async-generator==1.10
async-lru==2.0.4
attrs==23.1.0
Babel==2.13.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.1.0
certifi==2023.7.22
certipy==0.1.3
cffi==1.16.0
charset-normalizer==3.3.1
comm==0.1.4
cryptography==41.0.5
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.1.3
executing==2.0.0
fastjsonschema==2.18.1
fqdn==1.5.1
greenlet==3.0.0
idna==3.4
importlib-metadata==6.8.0
ipykernel==6.26.0
ipython==8.16.1
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
jupyter-events==0.8.0
jupyter-lsp==2.2.0
jupyter-telemetry==0.1.0
jupyter_client==8.5.0
jupyter_core==5.4.0
jupyter_server==2.9.0
jupyter_server_terminals==0.4.4
jupyterhub==4.0.2
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab_server==2.25.0
Mako==1.2.4
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mistune==3.0.2
nbclient==0.8.0
nbconvert==7.9.2
nbformat==5.9.2
nest-asyncio==1.5.8
notebook==7.0.6
notebook_shim==0.2.3
oauthlib==3.2.2
overrides==7.4.0
packaging==23.2
pamela==1.1.0
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.11.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
pyOpenSSL==23.2.0
python-dateutil==2.8.2
python-json-logger==2.0.7
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.30.2
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.10.6
ruamel.yaml==0.18.2
ruamel.yaml.clib==0.2.8
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
SQLAlchemy==2.0.22
stack-data==0.6.3
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.3
traitlets==5.12.0
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
uri-template==1.3.0
urllib3==2.0.7
wcwidth==0.2.8
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.4
zipp==3.17.0
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```

```
[E 2023-10-25 15:42:52.980 JupyterHub app:1995] Error adding user kaylee already in db
    Traceback (most recent call last):
      File "/data_science/lib/python3.9/site-packages/jupyterhub/app.py", line 1993, in init_users
        await maybe_future(f)
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 900, in add_user
        await maybe_future(self.add_system_user(user))
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 954, in add_system_user
        cmd = [arg.replace('USERNAME', name) for arg in self.add_user_cmd]
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 719, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 629, in get
        default = obj.trait_defaults(self.name)
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 1907, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/data_science/lib/python3.9/site-packages/traitlets/traitlets.py", line 1260, in __call__
        return self.func(*args, **kwargs)
      File "/data_science/lib/python3.9/site-packages/jupyterhub/auth.py", line 833, in _add_user_cmd_default
        raise ValueError("I don't know how to create users on OS X")
    ValueError: I don't know how to create users on OS X
```
- Source Code
```
@default('add_user_cmd')
    def _add_user_cmd_default(self):
        """Guess the most likely-to-work adduser command for each platform"""
        if sys.platform == 'darwin':
            raise ValueError("I don't know how to create users on OS X")
        elif which('pw'):
            # Probably BSD
            return ['pw', 'useradd', '-m', '-n']
        else:
            # This appears to be the Linux non-interactive adduser command:
            return ['adduser', '-q', '--gecos', '""', '--disabled-password']
```
</details>

**Comment by minrk** [comment]
The default PAM Authenticator cannot create system users on mac. It does work for _existing_ users. The error you see occurs when you've asked JupyterHub to create users that don't exist on the system.

You can also use another Authenticator which doesn't hook up to system users.

e.g. for local testing, I often start with:

```python
c.JupyterHub.authenticator_class = 'dummy'
c.JupyterHub.spawner_class = 'simple'
c.JupyterHub.ip = '127.0.0.1'
```

to run everything as a single system user, where the JupyterHub users are 'fake'. It all depends on how you want users to authenticate and run their servers.

**Comment by cooltheobob** [comment]
> The default PAM Authenticator cannot create system users on mac. It does work for _existing_ users. The error you see occurs when you've asked JupyterHub to create users that don't exist on the system.
> 
> You can also use another Authenticator which doesn't hook up to system users.
> 
> e.g. for local testing, I often start with:
> 
> ```python
> c.JupyterHub.authenticator_class = 'dummy'
> c.JupyterHub.spawner_class = 'simple'
> c.JupyterHub.ip = '127.0.0.1'
> ```
> 
> to run everything as a single system user, where the JupyterHub users are 'fake'. It all depends on how you want users to authenticate and run their servers.

It worked! Thanks so much!

By the way, now I need to integrate jupyter into my own platform, such as user authentication and the spawner's result of enforcement. 
There are two ways that I know: 
1.  Develop the source code and then deploy (The question is that it will be very difficult to upgrade when the official version is released)
2. Use the official docker image (The question is that it will be very difficult to develop the code to adapt to my own platform)

Do you have some advice? Thank you~

**Comment by cooltheobob** [comment]
@minrk

**Comment by manics** [comment]
@cooltheobob Your last question is a good one for the [Jupyter community forum](https://discourse.jupyter.org/) which is where we encourage people to discuss using and integrating Jupyter. Would you mind searching the forum for similar topics, and adding your question there if you can't find anything? Thanks!
