### ISSUE TITLE
"Spawn failed: Could not create PVC claim-foobar"

### ISSUE THREAD

**Issue by abctaylor** [jupyterhub/jupyterhub#4668]
### Bug description
Hi there - nothing turning up on Google for this error message. Where can I start to find out why JH couldn't make a PVC for a test user? This is with dummy auth turned on. All pods are healthy.

### How to reproduce

Create a user on first run after logging in with fake creds `foobar`

#### Expected behaviour
Notebook spins up for user `foobar` and PVC is created

#### Actual behaviour
<img width="1037" alt="image" src="https://github.com/jupyterhub/jupyterhub/assets/30197206/1511392d-6639-4c4e-95fe-f7640b374e94">

### Your personal set up

k8s 1.27, Cilium (CNI), MetalLB (load balancer), Longhorn (CSI)

<details><summary>Configuration</summary>

## config.yaml used in Helm

```
singleuser:
  storage:
    capacity: 100Mi
    dynamic:
      storageClass: longhorn
```
</details>

<details><summary>Logs</summary>

## hub pod logs
```
[W 2024-01-02 23:11:37.079 JupyterHub user:876] foobar's server failed to start in 300 seconds, giving up.

    Common causes of this timeout, and debugging tips:

    1. Everything is working, but it took too long.
       To fix: increase `Spawner.start_timeout` configuration
       to a number of seconds that is enough for spawners to finish starting.
    2. The server didn't finish starting,
       or it crashed due to a configuration issue.
       Check the single-user server's logs for hints at what needs fixing.

[W 2024-01-02 23:11:37.117 JupyterHub base:1057] 3 consecutive spawns failed.  Hub will exit if failure count reaches 5 before succeeding
[E 2024-01-02 23:11:37.117 JupyterHub gen:630] Exception in Future <Task finished name='Task-3582' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py:981> exception=TimeoutError('Could not create PVC claim-foobar')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/gen.py", line 625, in error_callback
        future.result()
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 988, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 902, in spawn
        raise e
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 798, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubespawner/spawner.py", line 2706, in _start
        await exponential_backoff(
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/utils.py", line 237, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    TimeoutError: Could not create PVC claim-foobar

```

## Longhorn logs
```
I1231 21:45:57.666042       1 volume_store.go:97] Starting save volume queue
I1231 21:45:57.767083       1 controller.go:860] Started provisioner controller driver.longhorn.io_csi-provisioner-65cb5cc4ff-lpxz4_0dfa0311-522c-4a9d-9902-7552d5123113!
I0102 22:44:26.849063       1 controller.go:1337] provision "quant/hub-db-dir" class "longhorn": started
W0102 22:44:26.858453       1 controller.go:620] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0102 22:44:26.858494       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"quant", Name:"hub-db-dir", UID:"1a7dd209-570f-42b7-90cf-99184e84ed58", APIVersion:"v1", ResourceVersion:"2649558", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "quant/hub-db-dir"
I0102 22:44:29.065338       1 controller.go:923] successfully created PV pvc-1a7dd209-570f-42b7-90cf-99184e84ed58 for PVC hub-db-dir and csi volume name pvc-1a7dd209-570f-42b7-90cf-99184e84ed58
I0102 22:44:29.065375       1 controller.go:1420] provision "quant/hub-db-dir" class "longhorn": volume "pvc-1a7dd209-570f-42b7-90cf-99184e84ed58" provisioned
I0102 22:44:29.065393       1 controller.go:1433] provision "quant/hub-db-dir" class "longhorn": succeeded
I0102 22:44:29.080611       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"quant", Name:"hub-db-dir", UID:"1a7dd209-570f-42b7-90cf-99184e84ed58", APIVersion:"v1", ResourceVersion:"2649558", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-1a7dd209-570f-42b7-90cf-99184e84ed58

```
</details>

**Comment by abctaylor** [comment]
Nothing more cringe than a bot spewing emojis
