### ISSUE TITLE
Enable to fetch User Info REST API

### ISSUE THREAD

**Issue by lifetooeasy** [jupyterhub/jupyterhub#4675]
since few days I am not able to fetch user info using the REST API with a token.

This code is not working anymore:

```
import requests

api_url = 'http://127.0.0.1:8081/hub/api'

r = requests.get(api_url + '/users',
    headers={
        'Authorization': f'token {token}',
    }
)

r.raise_for_status()
users = r.json()
```

The other endpoints work fine e.g `/users/{name}`or `/info` only fetch all users `/users` is not working.

**Comment by consideRatio** [comment]
What does the JupyterHub logs say as part of responding with error 500?

**Comment by lifetooeasy** [comment]
`[E 2024-01-18 11:59:35.241 JupyterHub log:189] 500 GET /hub/api/users (my_username@::1) 323.23ms`

**Comment by consideRatio** [comment]
Before and after, nothing else?

**Comment by lifetooeasy** [comment]
```
[E 2024-01-18 12:10:07.658 JupyterHub web:1789] Uncaught exception GET /hub/api/users (::1)
HTTPServerRequest(protocol='http', host='xxx', method='GET', uri='/hub/api/users', version='HTTP/1.1', remote_ip='::1')
```

**Comment by consideRatio** [comment]
Even more, about the uncaught exception

**Comment by consideRatio** [comment]
A uncaught exception should have a stacktrace, that is relevant to get

**Comment by lifetooeasy** [comment]
Yes, you are right now I see some separate errors between the lines:

```
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]: [E 2024-01-18 14:49:28.545 JupyterHub web:1789] Uncaught exception GET /hub/api/users (::1)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:     HTTPServerRequest(protocol='http', host='xxx', method='GET', uri='/hub/api/users', version='HTTP/1.1', remote_ip='::1')
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:     Traceback (most recent call last):
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         result = method(*self.path_args, **self.path_kwargs)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/site-packages/jupyterhub/utils.py", line 257, in decorated
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         return method(self, *args, **kwargs)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/site-packages/jupyterhub/apihandlers/users.py", line 103, in get
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         self.write(json.dumps(data))
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/json/__init__.py", line 231, in dumps
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         return _default_encoder.encode(obj)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/json/encoder.py", line 199, in encode
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         chunks = self.iterencode(o, _one_shot=True)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/json/encoder.py", line 257, in iterencode
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         return _iterencode(o, 0)
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:       File "/home/jupyterhub/.conda/envs/jupyterhub/lib/python3.9/json/encoder.py", line 179, in default
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:         raise TypeError(f'Object of type {o.__class__.__name__} '
Jan 18 14:49:28 jh-prod8.dkrz.de jupyterhub[168037]:     TypeError: Object of type set is not JSON serializable

```

**Comment by consideRatio** [comment]
There are plenty of information of relevance, such as jupyterhub version, config and such, in order to guess what went wrong here and if this is a bug to fix.

I can't say directly what this is about, but suspect its due to deletion of database etc. The stack trace was very relevant though!

**Comment by consideRatio** [comment]
Hmmmm... Well i think this needs to be closed then as i don't think this will lead to fixing a bug or similar in jupyterhub v4+, so what remains is just pure support =\
