### ISSUE TITLE
networkpolicy（proxy） causes pod to fail to start

### ISSUE THREAD

**Issue by hunter-luo666** [jupyterhub/jupyterhub#4680]
### Bug description
pod hub can not start(networkpolicy maybe wrong)

### How to reproduce

Environment：
AWS EKS （Kubernetes version  1.25）
Add-ons：amazon VPC CNI  （version：v1.15.0-eksbuild.2）
             Advanced configuration：
{
    "enableNetworkPolicy": "true",
}
 
download   jupyterhub-3.2.1.tgz
tar -xf jupyterhub-3.2.1.tgz
cd jupyterhub
helm upgrade --install --debug jupyterhub . -f ./values.yaml --namespace jupyterhub

after deploy，all other pods run normally，but hub pod run abnormally.
hub logs:
```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2024-01-23 07:31:43.524 JupyterHub app:2859] Running JupyterHub version 4.0.2
[I 2024-01-23 07:31:43.525 JupyterHub app:2889] Using Authenticator: jupyterhub.auth.DummyAuthenticator-4.0.2
[I 2024-01-23 07:31:43.525 JupyterHub app:2889] Using Spawner: kubespawner.spawner.KubeSpawner-6.2.0
[I 2024-01-23 07:31:43.525 JupyterHub app:2889] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.0.2
[I 2024-01-23 07:31:44.295 JupyterHub app:1984] Not using allowed_users. Any authenticated user will be allowed.
[I 2024-01-23 07:31:44.873 JupyterHub app:2928] Initialized 0 spawners in 0.026 seconds
[I 2024-01-23 07:31:44.929 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.twenty_four_hours
[I 2024-01-23 07:31:44.956 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.seven_days
[I 2024-01-23 07:31:44.989 JupyterHub metrics:278] Found 0 active users in the last ActiveUserPeriods.thirty_days
[I 2024-01-23 07:31:44.989 JupyterHub app:3142] Not starting proxy
[W 2024-01-23 07:31:47.991 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:31:51.117 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:31:54.310 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:31:57.377 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:32:01.616 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:32:05.128 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:32:10.651 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[W 2024-01-23 07:32:15.523 JupyterHub proxy:899] api_request to the proxy failed with status code 599, retrying...
[E 2024-01-23 07:32:15.523 JupyterHub app:3382]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/app.py", line 3380, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/app.py", line 3146, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/proxy.py", line 946, in get_all_routes
        resp = await self.api_request('', client=client)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/proxy.py", line 910, in api_request
        result = await exponential_backoff(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/utils.py", line 237, in exponential_backoff
        raise asyncio.TimeoutError(fail_message)
    TimeoutError: Repeated api_request to proxy path "" failed.
2024-01-23T07:32:15.524710584Z
```

when delete networkpolicy proxy, hub pod run normally.

what is wrong ?

 

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by manics** [comment]
Last time I looked at the EKS VPC CNI controller it didn't fully implement network policies. You can try going through the policies rules individually (I've looked into this before, it's very tedious) to work out which ones are incompatible with the Amazon VPC CNI using trial and error, but given it's a problem with the controller I don't think we should add any workarounds in this chart.

Calico is easier to use https://docs.aws.amazon.com/eks/latest/userguide/calico.html
Or you could disable network policies if you don't need them.
