### ISSUE TITLE
JupyterHub differs in `xsrf` behaviour from jupyter-server

### ISSUE THREAD

**Issue by krassowski** [jupyterhub/jupyterhub#4845]
### Bug description

jupyter-server accepts requests such as POST if they have an `xsrf` token OR if they include the correct auth token. Quoting from jupyter-server docs:

>  Jupyter server includes protection from cross-site request forgeries, requiring API requests to either:
> - originate from pages served by this server (validated with XSRF cookie and token), or
> - authenticate with a token

For reference here is [the link to the docs](https://github.com/jupyter-server/jupyter_server/blob/b85c15b5678cd6ea9de28e4f547bc0dfef0a69c7/jupyter_server/serverapp.py#L1299-L1308) and here is the [`JupyterHandler.check_xsrf_cookie` implementation](https://github.com/jupyter-server/jupyter_server/blob/b85c15b5678cd6ea9de28e4f547bc0dfef0a69c7/jupyter_server/base/handlers.py#L532-L535).

Now, JupyterHub overrides the `BaseHandler` in a way which is not obvious to an extension author. For example, we were surprised to see that the POST handler fails when used by API in [`jupyterlab-gallery`](https://github.com/nebari-dev/jupyterlab-gallery) (which you folks may like - it is a work-in-progress nbgipuller wrapper to be used inside of JupyterLab). This can be seen in https://github.com/nebari-dev/jupyterlab-gallery/pull/27/commits/1e3fb3ca9eb73e1c3d5c0ff24ad92ab3cfe1fb9b for which all the tests pass nicely on `jupyter-server` despite having no `xsrf` token.

I understand that this is because of this code:

https://github.com/jupyterhub/jupyterhub/blob/01aeb84a130a4c34b04f6e20673a74f166212ff2/jupyterhub/singleuser/mixins.py#L819-L843

which not only injects its own `BaseHandler`, but also explicitly overwrites `check_xsrf_cookie`

This was only changed recently in https://github.com/jupyterhub/jupyterhub/pull/4771

> As usual, this may be a bug or documentation issue, or an issue with myself not being able to find where it is mentioned in the docs

### How to reproduce

1. Create a jupyter-server extension with a POST endpoint.
2. Send a requests to the endpoint

#### Expected behaviour

A couple of ways we can approach this:
- a) change behaviour in JupyterHub (which may be undesirable - that's fine)
- b) improve documentation for extension authors here and on jupyter-server side to make this explicit
- c) make JupyterLab's `ServerConnection.makeRequest` append the `xsrf` token when it detects that it is running on JupyterHub

#### Actual behaviour

3. See that requests without xsrf but with Auth token work in jupyter-server
4. See that requests without xsrf but with Auth token do not work in JupyterHub

```py
[D 2024-06-27 11:38:01.031 ServerApp] Not accepting cookie auth on GET /user/username/jupyterlab-gallery/pull: '_xsrf' argument missing from GET
[W 2024-06-27 11:38:01.031 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/opt/conda/envs/default/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/default/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/default/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 146, in get_login_url
        login_url = original_get_login_url()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/default/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
```

### Your personal set up

 - Version(s): 5.0

**Comment by krassowski** [comment]
Of note, this assumption was used in JupyterLab codebase:

>  * We use `token` authentication if available, falling back on an XSRF
> * cookie if one has been provided on the `document`.

https://github.com/jupyterlab/jupyterlab/blob/133a9e4f3090f736dd12ffb92e84834424f24a9f/packages/services/src/serverconnection.ts#L40-L41

**Comment by manics** [comment]
Thanks for the writeup. I'm pretty sure the rest of JupyterHub uses the expected behaviour that you've described (xsrf check not needed for API tokens). Please feel free to open a PR to fix this if you want.

In addition if you've got any ideas on a better implementation of the singleuser mixin that reduces the low level patching of base class methods let us know in a new issue!

**Comment by krassowski** [comment]
Thank you! I discovered that in one instance I was using an event stream which does not support auth tokens and it indeed needed an explicit xsrf token. I am super confused as to why it worked on Binder but not on an internal JupyterHub deployment - I need to investigate more here. In any case I hope this issue is a good signpost to the important logic override which might be causing issues in some edge cases and that I will find some time to investigate more soon after getting back from vacation.

**Comment by manics** [comment]
It probably works on mybinder.org (as well as any BinderHub without authentication) because they don't run `jupyterhub-singleuser`:
- https://github.com/jupyterhub/binderhub/blob/19b6acacea975b4a3263c49d97e65f8b8bfaa355/helm-chart/binderhub/values.yaml#L223-L249
- https://github.com/jupyterhub/binderhub/blob/19b6acacea975b4a3263c49d97e65f8b8bfaa355/binderhub/binderspawner_mixin.py#L68-L77

If authentication is enabled `cmd: jupyterhub-singleuser` is needed, and I'd expect you to have the same problem
https://binderhub.readthedocs.io/en/latest/authentication.html#enabling-authentication

**Comment by minrk** [comment]
Thanks for the writeup! The description of what's required is accurate, you should _either_ need an API token _or_ all 3 of auth cookie, xsrf cookie, and xsrf token in argument/header. XSRF checks are not applied to token-authenticated requests.

I believe JupyterLab's makeRequest also does the right thing, where it uses an API token if available (always true in JupyterHub), or an xsrf token if cookie auth is to be used.

What changed in JupyterHub 4.1 relative to default Jupyter Server is which requests allowed cookie authentication _without_ an xsrf token. Specifically, Jupyter Server explicitly [allows GET requests to lack XSRF if the Referer matches](https://github.com/jupyter-server/jupyter_server/blob/f2d40f692c29e155349b179d57a454e7f23ea898/jupyter_server/base/handlers.py#L539-L547), effectively assuming (valid in most real web applications) that a single origin should be trusted. Whereas JupyterHub doesn't accept that, since it would permit user-to-user requests on single-domain deployments.

I've deployed jupyterlab-gallery (0.3.2), and I don't see any issues. The pull request works fine, with `_xsrf` passed in the query string for the EventSource at `/user/test/jupyterlab-gallery/pull?_xsrf=...`. Maybe you can share your environment? Here's mine:

<details>
<summary>pip freeze</summary>

```
alembic==1.13.2
annotated-types==0.7.0
anyio==4.4.0
appnope==0.1.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.6.2
certipy==0.1.3
cffi==1.16.0
charset-normalizer==3.3.2
comm==0.2.2
cryptography==42.0.8
debugpy==1.8.2
decorator==5.1.1
defusedxml==0.7.1
exceptiongroup==1.2.1
executing==2.0.1
fastjsonschema==2.20.0
fqdn==1.5.1
gitdb==4.0.11
GitPython==3.1.43
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
ipykernel==6.29.5
ipython==8.26.0
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterhub==5.0.0
jupyterlab==4.2.3
jupyterlab-gallery==0.3.2
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
Mako==1.3.5
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
mistune==3.0.2
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nbgitpuller==1.2.1
nest-asyncio==1.6.0
notebook_shim==0.2.4
oauthlib==3.2.2
overrides==7.7.0
packaging==24.1
pamela==1.1.0
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.2.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.22
pydantic==2.8.0
pydantic_core==2.20.0
Pygments==2.18.0
pyOpenSSL==24.1.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
PyYAML==6.0.1
pyzmq==26.0.3
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.18.1
Send2Trash==1.8.3
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.5
SQLAlchemy==2.0.31
stack-data==0.6.3
terminado==0.18.1
tinycss2==1.3.0
tomli==2.0.1
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
uri-template==1.3.0
urllib3==2.2.2
wcwidth==0.2.13
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
```

</details>

BinderHub did need an update to pass XSRF and auth tokens to the EventSource: https://github.com/jupyterhub/binderhub/pull/1847 because EventSource, like WebSocket, doesn't support authorization headers for some unknown reason, which is why there are tools like [fetch event source](https://github.com/Azure/fetch-event-source) which rebuilds the EventSource API on top of standard fetch streams.

**Comment by krassowski** [comment]
Thank you for looking into this and providing the context! I added the `_xsrf` in `jupyterlab-gallery` v0.3.0, the issue was with an older version (v0.2.1). I don't think an immediate fix is needed on JupyterHub side, maybe a documentation PR is all what is needed (which I can contribute in the future).

**Comment by minrk** [comment]
Yeah, I think documenting this case is perhaps what's needed, I don't think any behavior is incorrect for JupyterLab or JupyterHub. EventSource and WebSocket are the main ones where standard auth mechanisms don't work, which leads to this. Personally, I'd recommend fetchEventSource since it lets you use standard auth without needing to special case EventSource requests. I wish there was an equivalent for WebSocket.
