### ISSUE TITLE
Your server is starting up.  You will be redirected automatically when it's ready for you.But not coming up. 

### ISSUE THREAD

**Issue by Balajideivam** [jupyterhub/jupyterhub#488]
[E 2016-03-21 15:54:55.089 JupyterHub gen:733] Exception in Future <tornado.concurrent.Future object at 0x7f7c9970a6d8> after timeout
    Traceback (most recent call last):
      File "/opt/seagate/jupyterhub/anaconda3/lib/python3.4/site-packages/tornado/gen.py", line 729, in error_callback
        future.result()
      File "/seamnt/int001/seagate/jupyterhub/jupyterhub/orm.py", line 421, in spawn
        raise e
      File "/seamnt/int001/seagate/jupyterhub/jupyterhub/orm.py", line 397, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/seamnt/int001/seagate/jupyterhub/jupyterhub/orm.py", line 111, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/seamnt/int001/seagate/jupyterhub/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:42670/user/deivamb didn't respond in 30 seconds

[I 2016-03-21 15:54:56.426 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=deivamb --port=47682 --cookie-name=jupyter-hub-token-deivamb --base-url=/user/deivamb --hub-prefix=/jupyterhub/ --hub-api-url=http://localhost:8080/jupyterhub/api --ip=localhost --notebook-dir=/seamnt/sasdata-stage/jupyterhub
Traceback (most recent call last):
  File "/opt/seagate/jupyterhub/anaconda3/bin/jupyterhub-singleuser", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/seamnt/int001/seagate/jupyterhub/scripts/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/seamnt/int001/seagate/jupyterhub/jupyterhub/singleuser.py", line 14, in <module>
    import requests
  File "/opt/seagate/jupyterhub/anaconda3/lib/python3.4/site-packages/requests/__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "/opt/seagate/jupyterhub/anaconda3/lib/python3.4/site-packages/requests/models.py", line 49, in <module>
    json_dumps = json.dumps
AttributeError: 'module' object has no attribute 'dumps'
[W 2016-03-21 15:55:06.440 JupyterHub base:290] User deivamb server is slow to start
[I 2016-03-21 15:55:06.449 JupyterHub log:100] 302 GET /jupyterhub/user/deivamb (deivamb@10.31.7.52) 10038.28ms
[I 2016-03-21 15:55:06.536 JupyterHub log:100] 302 GET /user/deivamb (@10.31.7.52) 0.62ms

**Comment by betatim** [comment]
Could you upload your `/opt/seagate/jupyterhub/anaconda3/bin/jupyterhub-singleuser` somewhere? I am surprised to see something like `exec(compile(...))` in there.

**Comment by minrk** [comment]
@betatim I expect that's setuptools wrapping scripts.

@Balajideivam do you perhaps have a `json.py` file lying around somewhere? Possibly in `deivamb`'s home directory?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over one month. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by mukhendra** [comment]
your server is starting up. You will be redirected automatically when it's ready for you. In jupyter notebook how to resolve it.

Can you guys please help us

**Comment by Roger-GOAT** [comment]
same issue. Anyone has a idea?

**Comment by kaili-yang** [comment]
same issue.  I just want to get the latest editted file on it. Now the jupyter notebook is stuck so I can't access to the latest file .
