### ISSUE TITLE
Running a hub-managed-service with JupyterHub >=5.0.0  crashes hub throwing `KeyError 'hub'`

### ISSUE THREAD

**Issue by stubclan** [jupyterhub/jupyterhub#4927]
### Bug description

Starting a hub-managed service with JupyterHub (version >=5.0.0) using the provided configuration causes an error and hub eventually crashes after several tries. The traceback indicates an issue with the `content_security_policy` and the `hub` setting not being available in the handler settings.

#### Few observations
* I have tested jupyterhub==4.1.6 and it works completely fine with this setup. 
* If I remove "url" field from services then it seems to run without errors but service is still not accessible. After removing 'url' and starting hub and then manually starting the hub managed service and adding the route seems to work. 
* When I look at routing table on proxy, it doesn't register this service at all.
* External services are running without any issues.

### How to reproduce

1. Set up JupyterHub (version >=5.0.0).
2. Add the following configuration to jupyterhub_config.py:
   ```python
   c.JupyterHub.services = [
       {
           "name": "ddc",
           "url": "https://127.0.0.1:8889",
           "command": ["ddc-broker-service", "--catalog_file", "catalog.json", "--port", "8889"],
           # can be any service
       }
   ]
3. Start JupyterHub
4. KeyError

#### Expected Behavior
The hub-managed service should start correctly without errors, and the service should be accessible at the specified URL.

#### Actual Behavior
The service fails to start, and the following traceback is generated:
```log
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/http1connection.py", line 278, in _read_message
    delegate.finish()
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/routing.py", line 268, in finish
    self.delegate.finish()
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/web.py", line 2399, in finish
    self.execute()
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/web.py", line 2421, in execute
    self.handler = self.handler_class(
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/web.py", line 232, in __init__
    self.clear()
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/tornado/web.py", line 333, in clear
    self.set_default_headers()
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 250, in set_default_headers
    self.set_header('Content-Security-Policy', self.content_security_policy)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/jupyterhub/apihandlers/base.py", line 37, in content_security_policy
    return '; '.join([super().content_security_policy, "default-src 'none'"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 226, in content_security_policy
    ["frame-ancestors 'none'", "report-uri " + self.csp_report_uri]
                                               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 212, in csp_report_uri
    'csp_report_uri', url_path_join(self.hub.base_url, 'security/csp-report')
                                    ^^^^^^^^
  File "/home/ubuntu/.conda/envs/ddc-broker-service/lib/python3.12/site-packages/jupyterhub/handlers/base.py", line 172, in hub
    return self.settings['hub']
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'hub'
```

#### Your personal setup
OS: Ubuntu
Version(s): JupyterHub ==5.0.0, configurable-http-proxy==4.6.2

#### jupyterhub_config.py
```python
import os
import warnings

c.JupyterHub.authenticator_class = 'pam'
c.ConfigurableHTTPProxy.debug = True
c.Authenticator.allow_all = True

if "PUBLIC_HOST" not in os.environ:
    msg = (
        "env PUBLIC_HOST is not set, defaulting to http://127.0.0.1:8000.  "
        "This can cause problems with OAuth.  "
        "Set PUBLIC_HOST to your public (browser accessible) host."
    )
    warnings.warn(msg)
    public_host = "http://127.0.0.1:8000"
else:
    public_host = os.environ["PUBLIC_HOST"].rstrip('/')
service_name = "ddc"
oauth_redirect_uri = f"{public_host}/services/{service_name}/oauth_callback"


c = get_config()  # noqa
c.JupyterHub.services = [
    {
        "name": service_name,
        "url": "https://127.0.0.1:8889",
        "command": ["ddc-broker-service", "--catalog_file", "ddc_broker_server_config.json", "--port", "8889"],
        "oauth_redirect_uri": oauth_redirect_uri,
        "environment": {"PUBLIC_HOST": public_host},
    }
]

c.JupyterHub.load_roles = [
    {
        "name": "user",
        "scopes": ["self", "access:services"],
    },
]
```

**Comment by manics** [comment]
I can't reproduce your error.
```py
import os

c.JupyterHub.port = int(os.getenv("PORT"))
c.JupyterHub.base_url = os.getenv("BASEURL")

c.JupyterHub.authenticator_class = "dummy"
c.JupyterHub.spawner_class = "simple"


c.JupyterHub.load_roles = [
    {
        "name": "user",
        "scopes": ["self", "access:services"],
    },
]

c.JupyterHub.services = [
    {
        "name": "ddc",
        "url": "http://127.0.0.1:8889",
        "command": ["python", "-mhttp.server", "8889"],
        # can be any service
    }
]
```
allows me to access the Python HTTP server running on port 8889 (it returns a 404 since the path is invalid, but the service is responding)

**Comment by stubclan** [comment]
@manics  thanks for a quick response. For my use case, there are multiple services both hub-managed and external services. External services are fine but when trying to start hub managed ones it fails like above. 

The only thing I can say for now is these services have been running for 2 years now and broke only after 5.0.0 upgrade, is there something that needs to be added or removed ? I have went through the changelogs and also the Services  docs (https://jupyterhub.readthedocs.io/en/latest/reference/services.html) but so far nothing. I could be missing something trivial but ran out of ideas so created a bug here.

I haven't tried with an example service but will try that tomorrow.

**Comment by minrk** [comment]
@stubclan is it possible to see your service? From the traceback, it looks like perhaps your service is importing the JupyterHub handler base classes, which are not expected to work outside the JupyterHub process itself.

**Comment by stubclan** [comment]
Thanks @minrk. Its a python implementation of open service broker api (https://www.openservicebrokerapi.org/)

```python
'''
DDC broker server application.
'''

import asyncio
import json
import logging
import os
import secrets
from typing import Any
from urllib.parse import urlparse

from jupyterhub.apihandlers import API404
from jupyterhub.services.auth import HubOAuthCallbackHandler
from jupyterhub.utils import url_path_join
from tornado import web
from traitlets import (
    Bytes,
    Dict,
    Enum,
    Integer,
    Unicode,
    Union,
    default,
    validate
)
from traitlets.config import Application

from . import package
from .handlers import (
    CatalogHandler,
    HealthCheck,
    ServiceInstanceBindingHandler,
    ServiceInstanceHandler,
    ServiceInstanceLastOperationHandler,
    ServiceInstanceNameHandler
)


class DDCBrokerServerApp(Application):
    '''
    DDC broker server application.
    '''

    name = package.__title__  # type: ignore
    description = package.__description__  # type: ignore

    #: Path to configuration file. Defaults to ddc_broker_server_config.json.
    config_file = Unicode(
        'ddc_broker_server_config.json',
        config=True,
        help='''
            Path to configuration file. Defaults to ddc_broker_server_config.json.

            The application searches for the configuration files at:

            - `$PWD` working directory (highest precedence)
            - `DDC_BROKER_SERVER_APP_CONFIG` environment variable for additional paths
            - `/etc/ddc-broker-service/`
            - `/usr/local/etc/ddc-broker-service/`
        '''
    )

    #: Server listen hostname. Defaults to localhost.
    host = Unicode(
        'localhost',
        config=True,
        help='Server listen hostname. Defaults to localhost.'
    )

    #: Server listen port. Defaults to 8888.
    port = Integer(
        8888,
        config=True,
        help='Server listen port. Defaults to 8888.'
    )

    #: Hub URL.
    hub_url = Unicode(
        config=True,
        help='Hub URL.'
    )

    #: Application catalog as JSON file.
    catalog_file = Unicode(
        '/usr/local/etc/ddc-broker-service/catalog.json',
        config=True,
        help='''
            Application catalog as JSON file.
            Defaults to `/usr/local/etc/ddc-broker-service/catalog.json`.
        '''
    )

    #: Application catalog.
    catalog = Dict(
        config=True,
        help='Application catalog.'
    )

    #: Template to use to form the name of provisioned instances.
    instance_name_template = Unicode(
        'instance-{name}',
        config=True,
        help='Template to use to form the name of provisioned instances.'
    )

    #: Service prefix URL.
    service_prefix = Unicode(
        config=True,
        help='Service prefix URL.'
    )

    #: OAuthentication callback URL.
    oauth_callback_url = Unicode(
        config=True,
        help='OAuthentication callback URL.'
    )

    #: Cookie secret to encrypt service cookies.
    cookie_secret = Union(
        [
            Bytes(default_value=secrets.token_bytes(32)),
            Unicode()
        ],
        config=True,
        help='Cookie secret to encrypt service cookies.'
    )

    #: The log level for the application. Defaults to `info`.
    log_level = Enum(
        (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL'),
        default_value=logging.INFO,
        config=True,
        help='Set the log level by value or name. Defaults to `info`.'
    )

    #: Argument aliases.
    aliases = {
        'config': 'DDCBrokerServerApp.config_file',
        'host': 'DDCBrokerServerApp.host',
        'port': 'DDCBrokerServerApp.port',
        'hub_url': 'DDCBrokerServerApp.hub_url',
        'catalog_file': 'DDCBrokerServerApp.catalog_file',
        'catalog': 'DDCBrokerServerApp.catalog',
        'instance_name_template': 'DDCBrokerServerApp.instance_name_template',
        'service_prefix': 'DDCBrokerServerApp.service_prefix',
        'oauth_callback_url': 'DDCBrokerServerApp.oauth_callback_url',
        'cookie_secret': 'DDCBrokerServerApp.cookie_secret',
        'log_level': 'DDCBrokerServerApp.log_level'
    }

    @default('hub_url')
    def _default_hub_url(self) -> str:
        '''
        Set default Hub URL based on `JUPYTERHUB_API_URL`.

        Returns:
            str: The Hub URL.
        '''

        api_url = os.getenv('JUPYTERHUB_API_URL', '')
        parsed_url = urlparse(api_url)

        return f'{parsed_url.scheme}://{parsed_url.hostname}'

    @default('catalog')
    def _default_catalog(self) -> Dict:
        '''
        Set default catalog to catalog file content.

        Returns:
            Dict: The application catalog.
        '''

        with open(self.catalog_file, mode='r', encoding='utf-8') as file:
            return json.load(file)

    @default('service_prefix')
    def _default_service_prefix(self) -> str:
        '''
        Set default service prefix to `JUPYTERHUB_SERVICE_PREFIX`.

        Returns:
            str: The service prefix.
        '''

        return os.getenv('JUPYTERHUB_SERVICE_PREFIX', '/services/ddc/')

    @default('oauth_callback_url')
    def _default_oauth_callback_url(self) -> str:
        '''
        Set default OAuthentication callback URL to `JUPYTERHUB_OAUTH_CALLBACK_URL`.

        Returns:
            str: The OAuthentication callback URL.
        '''

        return os.getenv('JUPYTERHUB_OAUTH_CALLBACK_URL', '/services/ddc/oauth_callback')

    @validate('cookie_secret')
    def _validate_cookie_secret(self, proposal: Any) -> bytes:
        '''
        Coerces strings with even number of hexadecimal characters to bytes.

        Parameters:
            proposal (Any): Proposed configuration.

        Returns:
            bytes: Cookie secret as bytes.

        Raises:
            ValueError: Invalid cookie secret string.
        '''

        cookie_secret = proposal['value']

        if isinstance(cookie_secret, str):
            try:
                return bytes.fromhex(cookie_secret)
            except ValueError as exception:
                raise ValueError(
                    'invalid cookie secret string.'
                ) from exception
        else:
            return cookie_secret

    def _make_app(self) -> web.Application:
        '''
        Make Tornado application.

        Returns:
            web.Application: A Tornado application.
        '''

        base_url = self.service_prefix

        settings = {
            'debug': self.log_level <= logging.DEBUG,  # type: ignore
            'base_url': base_url,
            'cookie_secret': self.cookie_secret,
            'log': self.log,
            'hub_url': self.hub_url,
            'catalog': self.catalog,
            'instance_name_template': self.instance_name_template
        }

        return web.Application(
            [
                (base_url, HealthCheck),
                (self.oauth_callback_url, HubOAuthCallbackHandler),
                (url_path_join(base_url, r'/v2/catalog'), CatalogHandler),
                (
                    url_path_join(
                        base_url, r'/service_instances/([^/]+)/name'
                    ),
                    ServiceInstanceNameHandler
                ),
                (
                    url_path_join(
                        base_url, r'/v2/service_instances/([^/]+)'
                    ),
                    ServiceInstanceHandler
                ),
                (
                    url_path_join(
                        base_url, r'/v2/service_instances/([^/]+)/last_operation'
                    ),
                    ServiceInstanceLastOperationHandler
                ),
                (
                    url_path_join(
                        base_url, r'/v2/service_instances/([^/]+)/service_bindings/([^/]+)'
                    ),
                    ServiceInstanceBindingHandler
                ),
                (r'.*', API404)
            ],
            **settings
        )

    def initialize(self, *args: Any, **kwargs: Any):
        '''
        Initialize DDC broker server application with configuration file.

        The application searches for the configuration files at:

        - `$PWD` working directory (highest precedence)
        - `DDC_BROKER_SERVER_APP_CONFIG` environment variable for additional paths
        - `/etc/ddc-broker-service/`
        - `/usr/local/etc/ddc-broker-service/`

        Parameters:
            *args (Any): Additional arguments.
            **kwargs (Any): Additional keyword arguments.
        '''

        super().initialize(*args, **kwargs)

        config_paths = set([
            os.getcwd(),
            *os.getenv('DDC_BROKER_SERVER_APP_CONFIG', '').split(':'),
            '/etc/ddc-broker-service',
            '/usr/local/etc/ddc-broker-service'
        ])
        config_paths.discard('')

        self.load_config_file(self.config_file, path=list(config_paths))

    async def listen(self):
        '''
        Listen broker server.
        '''

        app = self._make_app()

        app.listen(
            address=self.host,
            port=self.port
        )

        await asyncio.Event().wait()

    def start(self):
        '''
        Start broker server.
        '''

        address = ':'.join([self.host, str(self.port)])
        self.log.info(f'Listen to DDC broker server at {address}')

        asyncio.run(self.listen())


__all__ = [
    'DDCBrokerServerApp'
]

```

**Comment by minrk** [comment]
Yes, looks like it's the API404, which is part of JupyterHub, not available to services. There shouldn't be any imports from `jupyterhub.handlers` or `jupyterhub.apihandlers` in a service.

**Comment by stubclan** [comment]
Thanks a lotttt @minrk, it's a big resolve for me. Totally missed this part, now its working as expected. Will close this issue
