### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_core'

### ISSUE THREAD

**Issue by mbacvanski** [jupyterhub/jupyterhub#4933]
### Bug description

On first install of tljh on Ubuntu 22.04.3 LTS, the page "Your server is starting up" after logging in fails with "Spawn failed: Server at http://127.0.0.1:45679/user/marc/ didn't respond in 30 seconds". 

Looking at the logs with `sudo journalctl -u jupyter-<name-of-user>` I see the trace

```
Feb 22 11:22:39 grove systemd[1]: Started /opt/tljh/user/bin/jupyterhub-singleuser.
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]: Traceback (most recent call last):
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:   File "/opt/tljh/user/bin/jupyterhub-singleuser", line 5, in <module>
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:     from jupyterhub.singleuser import main
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:   File "/opt/tljh/user/lib/python3.10/site-packages/jupyterhub/singleuser/__init__.py", line 17, in <module>
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:     from .mixins import HubAuthenticatedHandler, make_singleuser_app
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:   File "/opt/tljh/user/lib/python3.10/site-packages/jupyterhub/singleuser/mixins.py", line 48, in <module>
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:     from ._disable_user_config import _disable_user_config, _exclude_home
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:   File "/opt/tljh/user/lib/python3.10/site-packages/jupyterhub/singleuser/_disable_user_config.py", line 24, in <module>
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]:     from jupyter_core import paths
Feb 22 11:22:39 grove jupyterhub-singleuser[1664364]: ModuleNotFoundError: No module named 'jupyter_core'
Feb 22 11:22:39 grove systemd[1]: jupyter-marc.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 11:22:39 grove systemd[1]: jupyter-marc.service: Failed with result 'exit-code'.
```

### How to reproduce

I installed tljh with these commands with the base conda environment

```
python3 -m pip install jupyterhub
npm install -g configurable-http-proxy
python3 -m pip install notebook
```

### Your personal set up

OS: Ubuntu 22.04.3 LTS
Python: 3.10.12

<details><summary>Full environment</summary>

```
apturl==0.5.2
bcrypt==3.2.0
blinker==1.4
Brlapi==0.8.3
certifi==2020.6.20
chardet==4.0.0
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
dbus-python==1.2.18
defer==1.0.6
distro==1.7.0
distro-info==1.1+ubuntu0.2
duplicity==0.8.21
fasteners==0.14.1
future==0.18.2
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
jeepney==0.7.1
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lockfile==0.12.2
louis==3.20.0
macaroonbakery==1.3.1
Mako==1.1.3
MarkupSafe==2.0.1
monotonic==1.6
more-itertools==8.10.0
netifaces==0.11.0
oauthlib==3.2.0
olefile==0.46
packaging==21.3
paramiko==2.9.3
pexpect==4.8.0
Pillow==9.0.1
protobuf==3.12.4
psutil==5.9.0
ptyprocess==0.7.0
pycairo==1.20.1
pycups==2.0.1
PyGObject==3.42.1
PyJWT==2.3.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyparsing==2.4.7
pyRFC3339==1.1
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.1
python-debian==0.1.43+ubuntu1.1
pytz==2022.1
pyxdg==0.27
PyYAML==5.4.1
reportlab==3.6.8
requests==2.25.1
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
six==1.16.0
ssh-import-id==5.11
systemd-python==234
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
usb-creator==0.3.7
wadllib==1.3.6
xdg==5
xkit==0.0.0
zipp==1.0.0```
</details>

**Comment by consideRatio** [comment]
@minrk I transferred this from TLJH due to a missing dependency on `jupyter_core` leading to a failure to startup jupyterhub-singleuser, thinking it could be something to fix in this project rather than in tljh - but I'm not sure.

Should jupyterhub depend on jupyter_core? Should we do a try/except when trying to import jupyter_core?

**Comment by minrk** [comment]
An explicit singleuser dependency on jupyter_core won't really change anything here because it already depends on lab or notebook, which is the real unmet dependency, so this situation already only happens when singleuser dependencies are unmet. But in general, it is a good practice to express dependencies on the packages we import directly.

But it probably does make sense to try to make an informative error on the _first_ import likely to fail if singleuser dependencies are unmet, to point people in the right direction. I can have a look at that. Maybe that's jupyter_core, or maybe we had this but imports got reordered by the adoption of isort.
