### ISSUE TITLE
rhea permission error starting configurable-http-proxy

### ISSUE THREAD

**Issue by iamed18** [jupyterhub/jupyterhub#510]
I've attempted to follow the instruction guide for [setting up rhea to run sudospawner](https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) and the creation of `rhea` seems to have gone well except that she has a hard time starting up configureable-http-proxy. Ignition command and fail output attached here:

```bash
$ sudo -u rhea jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner -f /etc/jupyterhub/jupyterhub_config.py 
[I 2016-04-13 16:20:33.520 JupyterHub app:558] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 2016-04-13 16:20:33.563 JupyterHub app:292] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2016-04-13 16:20:33.568 JupyterHub app:685] No admin users, admin interface will be unavailable.
[W 2016-04-13 16:20:33.568 JupyterHub app:686] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-04-13 16:20:33.569 JupyterHub app:712] Not using whitelist. Any authenticated user will be allowed.
[I 2016-04-13 16:20:33.581 JupyterHub app:1113] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-04-13 16:20:33.584 JupyterHub app:860] Starting proxy @ http://127.0.0.1:8000/

fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/etc/letsencrypt/live/HUB.DOMAIN.TLD/privkey.pem'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:104:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
[C 2016-04-13 16:20:34.606 JupyterHub app:1119] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1117, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 881, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 877, in _check
        raise e
    
RuntimeError: Proxy failed to start with exit code 8
```

The error at the top sounds like `rhea` doesn't have access to the SSL keys. I changed her permissions to mimic `root`'s and this didn't have any effect. As a sanity check, I tried to `ls` the key directory as my user:
```bash
$ ls /etc/letsencrypt/live
ls: cannot open directory /etc/letsencrypt/live: Permission denied
```

But then I did it as rhea:

```bash
$ sudo -u rhea ls /etc/letsencrypt/live
HUB.DOMAIN.TLD
```

So it looks like she can see it, but still the starting error persists.

Thoughts? Thanks in advance for your time.

**Comment by minrk** [comment]
Can you do `ls -la`?

**Comment by iamed18** [comment]
Output of  `ls -laR live/` from within `/etc/letsencrypt'

```
eleonard@HOST:/etc/letsencrypt$ sudo -u rhea ls -laR live
live:
total 16
drwxrwx--- 4 root rhea 4096 Apr  8 22:39 .
drwxr-xr-x 8 root root 4096 Apr  4 16:02 ..
drwxrwxr-x 2 root rhea 4096 Apr  6 23:34 HOST.DOMAIN.TLD
drwxrwxr-x 2 root rhea 4096 Apr  8 22:39 HOST2.DOMAIN.TLD

live/HOST.DOMAIN.TLD:
total 8
drwxrwxr-x 2 root rhea 4096 Apr  6 23:34 .
drwxrwx--- 4 root rhea 4096 Apr  8 22:39 ..
lrwxrwxrwx 1 root rhea   47 Apr  6 23:34 cert.pem -> ../../archive/HOST.DOMAIN.TLD/cert2.pem
lrwxrwxrwx 1 root rhea   48 Apr  6 23:34 chain.pem -> ../../archive/HOST.DOMAIN.TLD/chain2.pem
lrwxrwxrwx 1 root rhea   52 Apr  6 23:34 fullchain.pem -> ../../archive/HOST.DOMAIN.TLD/fullchain2.pem
lrwxrwxrwx 1 root rhea   50 Apr  6 23:34 privkey.pem -> ../../archive/HOST.DOMAIN.TLD/privkey2.pem

live/HOST2.DOMAIN.TLD:
total 8
drwxrwxr-x 2 root rhea 4096 Apr  8 22:39 .
drwxrwx--- 4 root rhea 4096 Apr  8 22:39 ..
lrwxrwxrwx 1 root rhea   48 Apr  8 22:39 cert.pem -> ../../archive/HOST2.DOMAIN.TLD/cert1.pem
lrwxrwxrwx 1 root rhea   49 Apr  8 22:39 chain.pem -> ../../archive/HOST2.DOMAIN.TLD/chain1.pem
lrwxrwxrwx 1 root rhea   53 Apr  8 22:39 fullchain.pem -> ../../archive/HOST2.DOMAIN.TLD/fullchain1.pem
lrwxrwxrwx 1 root rhea   51 Apr  8 22:39 privkey.pem -> ../../archive/HOST2.DOMAIN.TLD/privkey1.pem
```

Since these links all point to somewhere, I'll do those as well:

```
eleonard@HOST:/etc/letsencrypt$ sudo -u rhea ls -laR archive
ls: cannot open directory archive: Permission denied
```

Seems like a security measure with SSL to not give out permissions to the actual files. For completeness' sake, here's the list with root.

```eleonard@HOST:/etc/letsencrypt$ sudo ls -laR archive
archive:
total 16
drwx------ 4 root root 4096 Apr  8 22:39 .
drwxr-xr-x 8 root root 4096 Apr  4 16:02 ..
drwxr-xr-x 2 root root 4096 Apr  6 23:34 HOST.DOMAIN.TLD
drwxr-xr-x 2 root root 4096 Apr  8 22:39 HOST2.DOMAIN.TLD

archive/HOST.DOMAIN.TLD:
total 40
drwxr-xr-x 2 root root 4096 Apr  6 23:34 .
drwx------ 4 root root 4096 Apr  8 22:39 ..
-rw-r--r-- 1 root root 1818 Apr  4 16:02 cert1.pem
-rw-r--r-- 1 root root 1818 Apr  6 23:34 cert2.pem
-rw-r--r-- 1 root root 1647 Apr  4 16:02 chain1.pem
-rw-r--r-- 1 root root 1647 Apr  6 23:34 chain2.pem
-rw-r--r-- 1 root root 3465 Apr  4 16:02 fullchain1.pem
-rw-r--r-- 1 root root 3465 Apr  6 23:34 fullchain2.pem
-rw-r--r-- 1 root root 1704 Apr  4 16:02 privkey1.pem
-rw-r--r-- 1 root root 1704 Apr  6 23:34 privkey2.pem

archive/HOST2.DOMAIN.TLD:
total 24
drwxr-xr-x 2 root root 4096 Apr  8 22:39 .
drwx------ 4 root root 4096 Apr  8 22:39 ..
-rw-r--r-- 1 root root 1822 Apr  8 22:39 cert1.pem
-rw-r--r-- 1 root root 1647 Apr  8 22:39 chain1.pem
-rw-r--r-- 1 root root 3469 Apr  8 22:39 fullchain1.pem
-rw-r--r-- 1 root root 1704 Apr  8 22:39 privkey1.pem
```

**Comment by minrk** [comment]
Looks like you've found the key that the archive directory is a private root-owned directory. You need to make that readable by rhea, e.g. by making a `letsencrypt` group that `rhea` is in, or some such, and then making it group-readable. Since this contains private keys, you don't want it to be world-readable.

**Comment by iamed18** [comment]
Changing the permissions of `archive` fixed the issue. Configurable-http-proxy is able to run via the sudospawner method now.

Thanks for the input!

(I have a new issue to open up, perhaps, but this one can be closed.)

**Comment by minrk** [comment]
Thanks!
