### ISSUE TITLE
libzmq.so.4 and --error-target

### ISSUE THREAD

**Issue by marmalodak** [jupyterhub/jupyterhub#566]
I upgrade my machine to Fedora 23 and then rebuilt my jupyterhub installation.  I had two issues:

1. My system did not have /usr/lib64/libzmq.so.4, I had to create a symlink to /usr/lib64/libmzq.so.5.

2. error: unknown option --error-target
This is from the log file:
```
/e2e/venv/jupyter-venv/home
[D 2016-05-11 12:58:11.785 JupyterHub application:529] Looking for /e2e/root/jupyter/jupyterhub-config in None
[D 2016-05-11 12:58:11.785 JupyterHub application:549] Loaded config file: /e2e/root/jupyter/jupyterhub-config.py
[I 2016-05-11 12:58:11.787 JupyterHub app:622] Loading cookie_secret from /jupyterhub_cookie_secret
[D 2016-05-11 12:58:11.787 JupyterHub app:694] Connecting to db: sqlite:///e2e/root/jupyter/jupyterhub.sqlite
[W 2016-05-11 12:58:11.820 JupyterHub app:304]
Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
[W 2016-05-11 12:58:11.824 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2016-05-11 12:58:11.824 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-05-11 12:58:11.824 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[D 2016-05-11 12:58:11.831 JupyterHub app:888] Loaded users:
[I 2016-05-11 12:58:11.841 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-05-11 12:58:11.845 JupyterHub app:959] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-05-11 12:58:11.845 JupyterHub app:968] Starting proxy @ http://0.0.0.0:80/
[D 2016-05-11 12:58:11.845 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '80', '--api-ip', '127.0.0.1', '--api-port', '81', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error']
error: unknown option `--error-target'
[C 2016-05-11 12:58:12.865 JupyterHub app:1237] Failed to start proxy
Traceback (most recent call last):
File "/e2e/venv/jupyter-venv/lib64/python3.4/site-packages/jupyterhub/app.py", line 1235, in start
yield self.start_proxy()
File "/e2e/venv/jupyter-venv/lib64/python3.4/site-packages/jupyterhub/app.py", line 989, in start_proxy
_check()
File "/e2e/venv/jupyter-venv/lib64/python3.4/site-packages/jupyterhub/app.py", line 985, in _check
raise e
RuntimeError: Proxy failed to start with exit code 1
[D 2016-05-11 12:58:12.876 JupyterHub application:584] Exiting application: jupyterhub
```
I can work around this by commenting out the --error-target in app.py.

**Comment by minrk** [comment]
missing `--error-target` means you need to upgrade `configurable-http-proxy`:

    npm install -g configurable-http-proxy

or

    conda install -c conda-forge configurable-http-proxy

The missing libzmq suggests that you have installed pyzmq, but libzmq has since been upgraded out from underneath it. The fix for that should be to rebuild and reinstall pyzmq.

**Comment by willingc** [comment]
Closing this issue as resolved. Labeling the issue with "Reference" since this solution may help other users.
