### ISSUE TITLE
500 errors when attempting to start a JupyterHub server in Docker

### ISSUE THREAD

**Issue by magsol** [jupyterhub/jupyterhub#590]
I'm trying to deploy [JupyterHub in Docker](https://github.com/jupyterhub/jupyterhub-deploy-docker) using the instructions provided but am consistently beset by `500` errors when I attempt to start a server.

I'm using the master branch from the jupyterhub repo, and Docker 1.11.1. I'm also using a self-signed cert [as per the provided instructions](https://jupyter-notebook.readthedocs.org/en/latest/public_server.html#using-ssl-for-encrypted-communication).

I saw documentation on the JupyterHub website [for this very problem](https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#500-error-after-spawning-my-single-user-server), but it doesn't appear to address the specific case I'm having. I've tried changing the `c.JupyterHub.hub_ip` to different values--I've tried `localhost`, `192.168.1.68` (the IP of the host machine), `172.17.0.1` (the domain for the Docker bridge network), and even the default of `jupyterhub`. The specific IP addresses return errors where the proxy server could not bind, and `localhost` and `jupyterhub` both result in the aforementioned 500 error.

Here is the output from `docker logs jupyterhub` after I try to connect to the server URL and start a server (this is with `hub_ip` set to either `localhost` or `jupyterhub`):

```
user123@hostmachine1:~/jupyterhub-deploy-docker$ sudo docker logs jupyterhub
[I 2016-05-26 15:41:19.766 JupyterHub app:622] Loading cookie_secret from /data/jupyterhub_cookie_secret
[W 2016-05-26 15:41:19.809 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2016-05-26 15:41:19.827 JupyterHub app:1231] Hub API listening on http://jupyterhub:8080/hub/
[I 2016-05-26 15:41:19.829 JupyterHub app:968] Starting proxy @ http://*:443/
15:41:19.893 - info: [ConfigProxy] Proxying https://*:443 to http://jupyterhub:8080
15:41:19.894 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
[I 2016-05-26 15:41:19.932 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:443/
[I 2016-05-26 15:41:32.916 JupyterHub log:100] 302 GET / (@192.168.1.67) 2.25ms
[I 2016-05-26 15:41:32.924 JupyterHub log:100] 302 GET /hub (@192.168.1.67) 0.37ms
[I 2016-05-26 15:41:32.936 JupyterHub log:100] 302 GET /hub/ (user123@192.168.1.67) 2.60ms
[I 2016-05-26 15:41:32.967 JupyterHub log:100] 200 GET /hub/home (user123@192.168.1.67) 22.59ms
[I 2016-05-26 15:41:34.573 JupyterHub log:100] 302 GET /hub/spawn (user123@192.168.1.67) 2.88ms
[I 2016-05-26 15:41:34.581 JupyterHub log:100] 302 GET /user/user123 (@192.168.1.67) 0.46ms
[I 2016-05-26 15:41:34.594 JupyterHub dockerspawner:335] Container 'jupyter-user123' is gone
[W 2016-05-26 15:41:34.594 JupyterHub dockerspawner:306] container not found
[I 2016-05-26 15:41:34.636 JupyterHub dockerspawner:335] Container 'jupyter-user123' is gone
[E 2016-05-26 15:41:34.641 JupyterHub user:237] Unhandled error starting user123's server: 404 Client Error: Not Found ("b'No such image: jupyter/scipy-notebook:latest'")
[I 2016-05-26 15:41:34.643 JupyterHub dockerspawner:335] Container 'jupyter-user123' is gone
[W 2016-05-26 15:41:34.643 JupyterHub dockerspawner:306] container not found
[E 2016-05-26 15:41:34.666 JupyterHub web:1524] Uncaught exception GET /hub/user/user123 (192.168.1.67)
    HTTPServerRequest(protocol='https', host='hostmachine1.hostdomain', method='GET', uri='/hub/user/user123', version='HTTP/1.1', remote_ip='192.168.1.67', headers={'Host': 'hostmachine1.hostdomain', 'Accept-Language': 'en-US,en;q=0.8', 'Connection': 'close', 'X-Forwarded-Proto': 'https', 'Referer': 'https://hostmachine1.hostdomain/hub/home', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', 'X-Forwarded-For': '192.168.1.67', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, sdch', 'Cookie': 'jupyter-hub-token=“”’, 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'X-Forwarded-Port': '443'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 494, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 393, in start
        resp = yield self.docker('create_container', **create_kwargs)
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 292, in _docker
        return m(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/docker/api/container.py", line 120, in create_container
        return self.create_container_from_config(config, name)
      File "/opt/conda/lib/python3.5/site-packages/docker/api/container.py", line 131, in create_container_from_config
        return self._result(res, True)
      File "/opt/conda/lib/python3.5/site-packages/docker/client.py", line 158, in _result
        self._raise_for_status(response)
      File "/opt/conda/lib/python3.5/site-packages/docker/client.py", line 153, in _raise_for_status
        raise errors.NotFound(e, response, explanation=explanation)
    docker.errors.NotFound: 404 Client Error: Not Found ("b'No such image: jupyter/scipy-notebook:latest'")
    
[E 2016-05-26 15:41:34.677 JupyterHub log:99] {
      "Host": "hostmachine1.hostdomain",
      "Accept-Language": "en-US,en;q=0.8",
      "Connection": "close",
      "X-Forwarded-Proto": "https",
      "Referer": "https://hostmachine1.hostdomain/hub/home",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36",
      "X-Forwarded-For": "192.168.1.67",
      "Upgrade-Insecure-Requests": "1",
      "Accept-Encoding": "gzip, deflate, sdch",
      "Cookie": "jupyter-hub-token=\"",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "X-Forwarded-Port": "443"
    }
[E 2016-05-26 15:41:34.677 JupyterHub log:100] 500 GET /hub/user/user123 (user123@192.168.1.67) 88.03ms
```

There's a 500 error combined with a 404, though I assume the two aren't related (I could be wrong, though). Any suggestions would be greatly appreciated!

**Comment by minrk** [comment]
It looks like you haven't pulled the single-user image yet. Try:

    docker pull jupyter/scipy-notebook

**Comment by magsol** [comment]
Ah...you are indeed correct. My apologies >_<

Now, the single-user server spins up `jupyter-user123`, but fails again with a 500 error [like this one](https://github.com/jupyterhub/jupyterhub/issues/291), whereby I noticed I still had `c.JupyterHub.hub_ip = 'localhost'`, so I changed that to `'jupyterhub'`, and poof everything started working!

Though I am curious about that 404 error in there.

**Comment by mausch** [comment]
I just ran into this situation... I was expecting jupyterhub to pull the image rather than me having to pull it manually on the host. Should I file a feature request about this? Is it something anyone is already working on? Thanks.

**Comment by minrk** [comment]
Please do open a feature request on jupyterhub/dockerspawner. I don't believe anyone is working on that, but it shouldn't be too much work.

**Comment by EmptyCrown** [comment]
I just ran into this situation as well. I tried
```
docker pull jupyter/scipy-notebook
```
But the error remains. Is the image somehow not there still? Thanks!
