### ISSUE TITLE
Traceback after changing hub prefix

### ISSUE THREAD

**Issue by akaihola** [jupyterhub/jupyterhub#605]
I changed the hub prefix in my configuration for JupyterHub 0.6.1 from `'/'` to

    c.JupyterHub.hub_prefix = '/base/hub/'

and started JupyterHub. I got this:
```
[E 2016-06-10 17:49:05.869 JupyterHub app:1296]
    Traceback (most recent call last):
      File "jupyterhub/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib64/python3.5/types.py", line 199, in __next__
        return next(self.__wrapped)
      File "jupyterhub/jupyterhub/app.py", line 1085, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "traitlets/config/application.py", line 74, in catch_config_error
        return method(app, *args, **kwargs)
      File "traitlets/config/application.py", line 565, in load_config_file
        self.update_config(config)
      File "traitlets/config/configurable.py", line 192, in update_config
        self._load_config(config)
      File "traitlets/config/configurable.py", line 169, in _load_config
        warn(msg)
      File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
        next(self.gen)
      File "traitlets/traitlets.py", line 1085, in hold_trait_notifications
        self.notify_change(change)
      File "traitlets/traitlets.py", line 1127, in notify_change
        c(change)
    TypeError: _hub_prefix_changed() missing 2 required positional arguments: 'old' and 'new'
```

**Comment by akaihola** [comment]
Seems to be fixed in master though.
