### ISSUE TITLE
JupyterHub fails to start Jupyter in container with error in self.proxy.delete_user(user)

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/jupyterhub#617]
I get this when trying to start my server via DockerSpawner after running `docker rm -f jupyter-robnagler`:

```text
503: Proxy Target Missing

The upstream service is unavailable

configurable-http-proxy
```

The logs show something like this, where the last blocks are repeated over and over:

```
Jun 22 15:12:00 hub docker[10630]: 21:12:00.976 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.977 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.977 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.977 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.978 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.979 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.979 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: 21:12:00.979 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:00 hub docker[10630]: [97B blob data]
Jun 22 15:12:00 hub docker[10630]: 21:12:00.981 - debug: [ConfigProxy] DELETE /user/robnagler
Jun 22 15:12:01 hub docker[10630]: [203B blob data]
Jun 22 15:12:01 hub docker[10630]: Traceback (most recent call last):
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
Jun 22 15:12:01 hub docker[10630]: ret = callback()
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
Jun 22 15:12:01 hub docker[10630]: return fn(*args, **kwargs)
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
Jun 22 15:12:01 hub docker[10630]: self.add_future(ret, lambda f: f.result())
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 346, in user_stopped
Jun 22 15:12:01 hub docker[10630]: yield self.proxy.delete_user(user)
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 181, in delete_user
Jun 22 15:12:01 hub docker[10630]: client=client,
Jun 22 15:12:01 hub docker[10630]: tornado.httpclient.HTTPError: HTTP 404: Not Found
Jun 22 15:12:01 hub docker[10630]: [97B blob data]
Jun 22 15:12:01 hub docker[10630]: [203B blob data]
Jun 22 15:12:01 hub docker[10630]: Traceback (most recent call last):
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
Jun 22 15:12:01 hub docker[10630]: ret = callback()
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
Jun 22 15:12:01 hub docker[10630]: return fn(*args, **kwargs)
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
Jun 22 15:12:01 hub docker[10630]: self.add_future(ret, lambda f: f.result())
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 346, in user_stopped
Jun 22 15:12:01 hub docker[10630]: yield self.proxy.delete_user(user)
Jun 22 15:12:01 hub docker[10630]: File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 181, in delete_user
Jun 22 15:12:01 hub docker[10630]: client=client,
Jun 22 15:12:01 hub docker[10630]: tornado.httpclient.HTTPError: HTTP 404: Not Found
```

**Comment by willingc** [comment]
@robnagler After running the `docker rm` command, are you restarting the configurable-http-proxy as well as the hub? https://jupyterhub.readthedocs.io/en/latest/getting-started.html#proxy-authentication-token

@minrk Other thoughts?

**Comment by minrk** [comment]
@robnagler what version of CHP (`configurable-http-proxy --version`) and commit of this repo? It's strange that DELETE is logged so many times. Can you show the bit before all those DELETEs start showing up?

**Comment by robnagler** [comment]
Sorry for the delay. Here's the full log for the time around the DELETEs: [jupyterhub-2016-06-22.log.gz](https://github.com/jupyterhub/jupyterhub/files/339513/jupyterhub-2016-06-22.log.gz)

**Comment by willingc** [comment]
Thanks @robnagler for sending the log. We'll take a look at it and get some thoughts back to you.

**Comment by willingc** [comment]
@robnagler I'm sorry that we haven't responded back yet on this issue. Are you still seeing this behavior? 

In the future, please do ping us in the issue if we fail to respond in a few days. Again, I'm sorry this fell off our radar.

cc @minrk

**Comment by robnagler** [comment]
No worries. I can't say. JupyterHub is very stable (THANKS!) so we haven't had the restarts we had when first getting started. Feel free to close.

**Comment by willingc** [comment]
Thanks @robnagler. Good to hear it's stable for you now too :smile:
