### ISSUE TITLE
Jupyterhub fails on user login, permission denied error

### ISSUE THREAD

**Issue by geoffroy-destaintot** [jupyterhub/jupyterhub#625]
Hello,

I'm trying to install jupyterhub on debian 8.2.
I would like to be able to create the create_system_users, so I suppose that jupyterhub must be installed as root (for adduser to work).

Being root, I installed a conda env, and installed jupyterhub:
```
pip install jupyterhub
pip install --upgrade notebook
```

I already have a user on my system called gonzag and I register him as admin_user (in conf file).

I start jupyterhub as root.

The login page of the server works fine, but when I log in as gonzag, I get an internal server error: 

> Error
> Failed to start your server. Please contact admin.

I put the traceback and conf file below.

**Any clue of what is happening ?** Thanks for your help.

Here is my traceback (server started with --debug):
```
[D 2016-07-01 08:23:24.287 JupyterHub application:529] Looking for jupyterhub_config in None
[D 2016-07-01 08:23:24.289 JupyterHub application:549] Loaded config file: /root/prod/jupyterhub/jupyterhub_config.py
[I 2016-07-01 08:23:24.296 JupyterHub app:622] Loading cookie_secret from /root/prod/jupyterhub/jupyterhub_cookie_secret
[D 2016-07-01 08:23:24.296 JupyterHub app:694] Connecting to db: sqlite:///jupyterhub.sqlite
[W 2016-07-01 08:23:24.378 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2016-07-01 08:23:24.399 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[D 2016-07-01 08:23:24.426 JupyterHub app:888] Loaded users: 
      gonzag admin
[I 2016-07-01 08:23:24.447 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-07-01 08:23:24.457 JupyterHub app:968] Starting proxy @ http://0.0.0.0:8000/
[D 2016-07-01 08:23:24.458 JupyterHub app:969] Proxy cmd: ['configurable-http-proxy', '--ip', '0.0.0.0', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://127.0.0.1:8081', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/root/prod/ssl/key.key', '--ssl-cert', '/root/prod/ssl/cert.crt']
[D 2016-07-01 08:23:24.768 JupyterHub app:997] Proxy started and appears to be up
[I 2016-07-01 08:23:24.769 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8000/
[I 2016-07-01 08:23:35.139 JupyterHub log:100] 302 GET / (@92.169.78.132) 3.44ms
[I 2016-07-01 08:23:35.150 JupyterHub log:100] 302 GET /hub (@92.169.78.132) 1.13ms
[I 2016-07-01 08:23:35.171 JupyterHub log:100] 302 GET /hub/ (@92.169.78.132) 2.08ms
[I 2016-07-01 08:23:35.275 JupyterHub log:100] 200 GET /hub/login (@92.169.78.132) 92.29ms
[I 2016-07-01 08:23:40.022 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=gonzag --port=44600 --cookie-name=jupyter-hub-token-gonzag --base-url=/user/gonzag --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1 '--notebook-dir=~'
[E 2016-07-01 08:23:40.101 JupyterHub user:237] Unhandled error starting gonzag's server: [Errno 13] Permission denied
[E 2016-07-01 08:23:40.188 JupyterHub web:1524] Uncaught exception POST /hub/login?next= (92.169.78.132)
    HTTPServerRequest(protocol='https', host='notebooks.xxxx.fr:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='92.169.78.132', headers={'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'X-Forwarded-Proto': 'https', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cookie': '_ga=GA1.2.642400893.1464272612', 'Cache-Control': 'max-age=0', 'Referer': 'https://notebooks.xxxx.fr:8000/hub/login', 'Origin': 'https://notebooks.xxxx.fr:8000', 'Host': 'notebooks.xxxx.fr:8000', 'Connection': 'close', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'X-Forwarded-For': '92.169.78.132', 'X-Forwarded-Port': '8000', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29'})
    Traceback (most recent call last):
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 79, in post
        yield self.spawn_single_user(user)
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/root/miniconda3/envs/notebooks/lib/python3.5/types.py", line 243, in wrapped
        coro = func(*args, **kwargs)
      File "/root/miniconda3/envs/notebooks/lib/python3.5/site-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/root/miniconda3/envs/notebooks/lib/python3.5/subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "/root/miniconda3/envs/notebooks/lib/python3.5/subprocess.py", line 1544, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied
    
[D 2016-07-01 08:23:40.202 JupyterHub base:441] No template for 500
[E 2016-07-01 08:23:40.230 JupyterHub log:99] {
      "Accept-Language": "en-US,en;q=0.8,fr;q=0.6",
      "X-Forwarded-Proto": "https",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Cookie": "_ga=GA1.2.642400893.1464272612",
      "Cache-Control": "max-age=0",
      "Referer": "https://notebooks.xxxx.fr:8000/hub/login",
      "Origin": "https://notebooks.xxxx.fr:8000",
      "Host": "notebooks.xxxx.fr:8000",
      "Connection": "close",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
      "X-Forwarded-For": "92.169.78.132",
      "X-Forwarded-Port": "8000",
      "Accept-Encoding": "gzip, deflate, br",
      "Content-Type": "application/x-www-form-urlencoded",
      "Content-Length": "29"
    }
[E 2016-07-01 08:23:40.231 JupyterHub log:100] 500 POST /hub/login?next= (@92.169.78.132) 710.51ms
[I 2016-07-01 08:23:44.583 JupyterHub app:1115] Cleaning up single-user servers...
[I 2016-07-01 08:23:44.938 JupyterHub app:1126] Cleaning up proxy[9209]...
[I 2016-07-01 08:23:44.939 JupyterHub app:1152] ...done
```

Here is my conf file:

```
# Configuration file for jupyterhub.

#------------------------------------------------------------------------------
# Configurable configuration
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# LoggingConfigurable configuration
#------------------------------------------------------------------------------

# A parent class for Configurables that log.
# 
# Subclasses have a log trait, and the default behavior is to get the logger
# from the currently running Application.

#------------------------------------------------------------------------------
# SingletonConfigurable configuration
#------------------------------------------------------------------------------

# A configurable that only allows one instance.
# 
# This class is for classes that should only have one instance of itself or
# *any* subclass. To create and retrieve such a class use the
# :meth:`SingletonConfigurable.instance` method.

#------------------------------------------------------------------------------
# Application configuration
#------------------------------------------------------------------------------

# This is an application.

# The date format used by logging formatters for %(asctime)s
# c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'

# The Logging format template
# c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'

# Set the log level by value or name.
c.Application.log_level = "DEBUG"

#------------------------------------------------------------------------------
# JupyterHub configuration
#------------------------------------------------------------------------------

# An Application for starting a Multi-User Jupyter Notebook server.

# Grant admin users permission to access single-user servers.
# 
# Users should be properly informed if this is enabled.
c.JupyterHub.admin_access = False

# DEPRECATED, use Authenticator.admin_users instead.
# c.JupyterHub.admin_users = set()

# Answer yes to any questions (e.g. confirm overwrite)
# c.JupyterHub.answer_yes = False

# Dict of token:username to be loaded into the database.
# 
# Allows ahead-of-time generation of API tokens for use by services.
# c.JupyterHub.api_tokens = {}

# Class for authenticating users.
# 
# This should be a class with the following form:
# 
# - constructor takes one kwarg: `config`, the IPython config object.
# 
# - is a tornado.gen.coroutine
# - returns username on success, None on failure
# - takes two arguments: (handler, data),
#   where `handler` is the calling web.RequestHandler,
#   and `data` is the POST form data from the login page.
# c.JupyterHub.authenticator_class = 'jupyterhub.auth.PAMAuthenticator'

# The base URL of the entire application
# c.JupyterHub.base_url = '/'

# Whether to shutdown the proxy when the Hub shuts down.
# 
# Disable if you want to be able to teardown the Hub while leaving the proxy
# running.
# 
# Only valid if the proxy was starting by the Hub process.
# 
# If both this and cleanup_servers are False, sending SIGINT to the Hub will
# only shutdown the Hub, leaving everything else running.
# 
# The Hub should be able to resume from database state.
# c.JupyterHub.cleanup_proxy = True

# Whether to shutdown single-user servers when the Hub shuts down.
# 
# Disable if you want to be able to teardown the Hub while leaving the single-
# user servers running.
# 
# If both this and cleanup_proxy are False, sending SIGINT to the Hub will only
# shutdown the Hub, leaving everything else running.
# 
# The Hub should be able to resume from database state.
# c.JupyterHub.cleanup_servers = True

# The config file to load
# c.JupyterHub.config_file = 'jupyterhub_config.py'

# Confirm that JupyterHub should be run without SSL. This is **NOT RECOMMENDED**
# unless SSL termination is being handled by another layer.
# c.JupyterHub.confirm_no_ssl = False

# Number of days for a login cookie to be valid. Default is two weeks.
# c.JupyterHub.cookie_max_age_days = 14

# The cookie secret to use to encrypt cookies.
# 
# Loaded from the JPY_COOKIE_SECRET env variable by default.
# c.JupyterHub.cookie_secret = b''

# File in which to store the cookie secret.
# c.JupyterHub.cookie_secret_file = 'jupyterhub_cookie_secret'

# The location of jupyterhub data files (e.g. /usr/local/share/jupyter/hub)
# c.JupyterHub.data_files_path = '/root/miniconda3/share/jupyter/hub'

# Include any kwargs to pass to the database connection. See
# sqlalchemy.create_engine for details.
# c.JupyterHub.db_kwargs = {}

# url for the database. e.g. `sqlite:///jupyterhub.sqlite`
# c.JupyterHub.db_url = 'sqlite:///jupyterhub.sqlite'

# log all database transactions. This has A LOT of output
# c.JupyterHub.debug_db = False

# show debug output in configurable-http-proxy
# c.JupyterHub.debug_proxy = False

# Send JupyterHub's logs to this file.
# 
# This will *only* include the logs of the Hub itself, not the logs of the proxy
# or any single-user servers.
# c.JupyterHub.extra_log_file = ''

# Extra log handlers to set on JupyterHub logger
# c.JupyterHub.extra_log_handlers = []

# Generate default config file
# c.JupyterHub.generate_config = False

# The ip for this process
# c.JupyterHub.hub_ip = '127.0.0.1'

# The port for this process
# c.JupyterHub.hub_port = 8081

# The prefix for the hub server. Must not be '/'
# c.JupyterHub.hub_prefix = '/hub/'

# The public facing ip of the whole application (the proxy)
c.JupyterHub.ip = '0.0.0.0'

# Supply extra arguments that will be passed to Jinja environment.
# c.JupyterHub.jinja_environment_options = {}

# Interval (in seconds) at which to update last-activity timestamps.
# c.JupyterHub.last_activity_interval = 300

# Specify path to a logo image to override the Jupyter logo in the banner.
# c.JupyterHub.logo_file = ''

# File to write PID Useful for daemonizing jupyterhub.
# c.JupyterHub.pid_file = ''

# The public facing port of the proxy
c.JupyterHub.port = 8000

# The ip for the proxy API handlers
# c.JupyterHub.proxy_api_ip = '127.0.0.1'

# The port for the proxy API handlers
# c.JupyterHub.proxy_api_port = 0

# The Proxy Auth token.
# 
# Loaded from the CONFIGPROXY_AUTH_TOKEN env variable by default.
# c.JupyterHub.proxy_auth_token = ''

# Interval (in seconds) at which to check if the proxy is running.
# c.JupyterHub.proxy_check_interval = 30

# The command to start the http proxy.
# 
# Only override if configurable-http-proxy is not on your PATH
# c.JupyterHub.proxy_cmd = ['configurable-http-proxy']

# Purge and reset the database.
# c.JupyterHub.reset_db = False

# The class to use for spawning single-user servers.
# 
# Should be a subclass of Spawner.
# c.JupyterHub.spawner_class = 'jupyterhub.spawner.LocalProcessSpawner'

# Path to SSL certificate file for the public facing interface of the proxy
# 
# Use with ssl_key
c.JupyterHub.ssl_cert = '/root/prod/ssl/cert.crt'

# Path to SSL key file for the public facing interface of the proxy
# 
# Use with ssl_cert
c.JupyterHub.ssl_key = '/root/prod/ssl/key.key'

# Host to send statds metrics to
# c.JupyterHub.statsd_host = ''

# Port on which to send statsd metrics about the hub
# c.JupyterHub.statsd_port = 8125

# Prefix to use for all metrics sent by jupyterhub to statsd
# c.JupyterHub.statsd_prefix = 'jupyterhub'

# Run single-user servers on subdomains of this host.
# 
# This should be the full https://hub.domain.tld[:port]
# 
# Provides additional cross-site protections for javascript served by single-
# user servers.
# 
# Requires <username>.hub.domain.tld to resolve to the same host as
# hub.domain.tld.
# 
# In general, this is most easily achieved with wildcard DNS.
# 
# When using SSL (i.e. always) this also requires a wildcard SSL certificate.
# c.JupyterHub.subdomain_host = ''

# Paths to search for jinja templates.
# c.JupyterHub.template_paths = []

# Extra settings overrides to pass to the tornado application.
# c.JupyterHub.tornado_settings = {}

#------------------------------------------------------------------------------
# Spawner configuration
#------------------------------------------------------------------------------

# Base class for spawning single-user notebook servers.
# 
# Subclass this, and override the following methods:
# 
# - load_state - get_state - start - stop - poll

# Extra arguments to be passed to the single-user server
# c.Spawner.args = []

# The command used for starting notebooks.
# c.Spawner.cmd = ['jupyterhub-singleuser']

# Enable debug-logging of the single-user server
# c.Spawner.debug = False

# The default URL for the single-user server.
# 
# Can be used in conjunction with --notebook-dir=/ to enable  full filesystem
# traversal, while preserving user's homedir as landing page for notebook
# 
# `%U` will be expanded to the user's username
# c.Spawner.default_url = ''

# Disable per-user configuration of single-user servers.
# 
# This prevents any config in users' $HOME directories from having an effect on
# their server.
# c.Spawner.disable_user_config = False

# Whitelist of environment variables for the subprocess to inherit
# c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL']

# Environment variables to load for the Spawner.
# 
# Value could be a string or a callable. If it is a callable, it will be called
# with one parameter, which will be the instance of the spawner in use. It
# should quickly (without doing much blocking operations) return a string that
# will be used as the value for the environment variable.
# c.Spawner.environment = {}

# Timeout (in seconds) before giving up on a spawned HTTP server
# 
# Once a server has successfully been spawned, this is the amount of time we
# wait before assuming that the server is unable to accept connections.
# c.Spawner.http_timeout = 30

# The IP address (or hostname) the single-user server should listen on
# c.Spawner.ip = '127.0.0.1'

# The notebook directory for the single-user server
# 
# `~` will be expanded to the user's home directory `%U` will be expanded to the
# user's username
c.Spawner.notebook_dir = '~'

# An HTML form for options a user can specify on launching their server. The
# surrounding `<form>` element and the submit button are already provided.
# 
# For example:
# 
#     Set your key:
#     <input name="key" val="default_key"></input>
#     <br>
#     Choose a letter:
#     <select name="letter" multiple="true">
#       <option value="A">The letter A</option>
#       <option value="B">The letter B</option>
#     </select>
# c.Spawner.options_form = ''

# Interval (in seconds) on which to poll the spawner.
# c.Spawner.poll_interval = 30

# Timeout (in seconds) before giving up on the spawner.
# 
# This is the timeout for start to return, not the timeout for the server to
# respond. Callers of spawner.start will assume that startup has failed if it
# takes longer than this. start should return when the server process is started
# and its location is known.
# c.Spawner.start_timeout = 60

#------------------------------------------------------------------------------
# LocalProcessSpawner configuration
#------------------------------------------------------------------------------

# A Spawner that just uses Popen to start local processes as users.
# 
# Requires users to exist on the local system.
# 
# This is the default spawner for JupyterHub.

# Seconds to wait for process to halt after SIGINT before proceeding to SIGTERM
# c.LocalProcessSpawner.INTERRUPT_TIMEOUT = 10

# Seconds to wait for process to halt after SIGKILL before giving up
# c.LocalProcessSpawner.KILL_TIMEOUT = 5

# Seconds to wait for process to halt after SIGTERM before proceeding to SIGKILL
# c.LocalProcessSpawner.TERM_TIMEOUT = 5

#------------------------------------------------------------------------------
# Authenticator configuration
#------------------------------------------------------------------------------

# A class for authentication.
# 
# The primary API is one method, `authenticate`, a tornado coroutine for
# authenticating users.

# set of usernames of admin users
# 
# If unspecified, only the user that launches the server will be admin.
c.Authenticator.admin_users = {"gonzag"}

# Dictionary mapping authenticator usernames to JupyterHub users.
# 
# Can be used to map OAuth service names to local users, for instance.
# 
# Used in normalize_username.
# c.Authenticator.username_map = {}

# Regular expression pattern for validating usernames.
# 
# If not defined: allow any username.
# c.Authenticator.username_pattern = ''

# Username whitelist.
# 
# Use this to restrict which users can login. If empty, allow any user to
# attempt login.
# c.Authenticator.whitelist = set()

#------------------------------------------------------------------------------
# LocalAuthenticator configuration
#------------------------------------------------------------------------------

# Base class for Authenticators that work with local Linux/UNIX users
# 
# Checks for local users, and can attempt to create them if they exist.

# The command to use for creating users as a list of strings.
# 
# For each element in the list, the string USERNAME will be replaced with the
# user's username. The username will also be appended as the final argument.
# 
# For Linux, the default value is:
# 
#     ['adduser', '-q', '--gecos', '""', '--disabled-password']
# 
# To specify a custom home directory, set this to:
# 
#     ['adduser', '-q', '--gecos', '""', '--home', '/customhome/USERNAME', '--
# disabled-password']
# 
# This will run the command:
# 
# adduser -q --gecos "" --home /customhome/river --disabled-password river
# 
# when the user 'river' is created.
# c.LocalAuthenticator.add_user_cmd = []

# If a user is added that doesn't exist on the system, should I try to create
# the system user?
c.LocalAuthenticator.create_system_users = True

# Automatically whitelist anyone in this group.
# c.LocalAuthenticator.group_whitelist = set()

#------------------------------------------------------------------------------
# PAMAuthenticator configuration
#------------------------------------------------------------------------------

# Authenticate local Linux/UNIX users with PAM

# The encoding to use for PAM
# c.PAMAuthenticator.encoding = 'utf8'

# Whether to open PAM sessions when spawners are started.
# 
# This may trigger things like mounting shared filsystems, loading credentials,
# etc. depending on system configuration, but it does not always work.
# 
# It can be disabled with::
# 
#     c.PAMAuthenticator.open_sessions = False
# c.PAMAuthenticator.open_sessions = True

# The PAM service to use for authentication.
# c.PAMAuthenticator.service = 'login'
```

**Comment by minrk** [comment]
It looks like you have installed JupyterHub into `/root/`. Your users need read+execute access to where `jupyterhub-singleuser` is installed, which is not generally the default for `/root/`. Try installing conda to a system-wide location, such as `/opt/conda`, and make sure users have read-access to this location, e.g. by doing:

    sudo -u yourname /path/to/conda/bin/jupyterhub-singleuser -h

**Comment by geoffroy-destaintot** [comment]
thank your for your precious help, it works now !

**Comment by ajohnson1986** [comment]
Hello, 
I am having the similar error even after installing the

**Comment by ajohnson1986** [comment]
Hi 
Found the solution by configuring the following property to the absolute path 
c.Spawner.cmd = ['/path to /bin/jupyterhub-singleuser']

**Comment by cattei** [comment]
spawner not my way... still 500 error

**Comment by dpshelio** [comment]
I get the same problem. Setting the Spawner command I see in the logs a permition denied:
```python
PermissionError: [Errno 13] Permission denied: '/opt/anaconda/bin/jupyterhub-singleuser'
```
but the permissions seem correct:
```
-rwxrwxr-x. 1 root root 106 May 12 17:27 /opt/anaconda/bin/jupyterhub-singleuser
```
and I get the help when run as the user in question as suggested above with:
```
sudo -u yourname /path/to/conda/bin/jupyterhub-singleuser -h
```

**Comment by asuchit** [comment]
I am still getting permission error even I check the permissions and also gave absolute path.

Can someone help... how can I fix it ?

**Comment by marinalopez2110** [comment]
If I installed it in /root (that's clearly my problem, A security problem). What's the best way to fix it? Reinstall in /etc/? Something that I should consider when doing it? Thanks!

**Comment by marinalopez2110** [comment]
I reinstalled. All working fine. Thanks.

**Comment by adam-erickson** [comment]
I reinstalled Anaconda to `/opt/anaconda3`, where it was already installed before, and everything magically worked. Previously, it was giving me a permission error for the user intended to spawn the hub processes. No idea why it worked the second time, but not the first.

**Comment by mokumar1202** [comment]
Hi All, 

I have completed setting up Anaconda distribution, installed JupyterHub but when i login to the Hub, i get Spawn failed: Server at http://127.0.0.1:35990/user/<userid>/ didn't respond in 30 seconds.

I have tried many suggestions but nothing seems to fix it. Please could someone help.

Just FYI, i have also reinstalled Anaconda, configured Proxy, generated jupyterhub_config.py.

**Comment by somir** [comment]
> ```
> sudo -u yourname /path/to/conda/bin/jupyterhub-singleuser -h
> ```

But in my case "sudo -u yourname /path/to/conda/bin/jupyterhub-singleuser -h
" this command also says Permission denied (sudo: unable to execute /root/anaconda3/bin/jupyterhub-singleuser: Permission denied).......

Anythings else????

**Comment by L-Hai** [comment]
Reinstalling the conda environment of jupyterhub in /opt/ solved my problem.
