### ISSUE TITLE
500 error creating users on EC2 instance

### ISSUE THREAD

**Issue by benrobinson1976** [jupyterhub/jupyterhub#628]
Hello- I am following the instructions from https://github.com/jupyterhub/jupyterhub/wiki/Deploying-JupyterHub-on-AWS to create an EC2 instance with GitHub Oauth. Like some others I am running into the 500 error when spawning a single-user instance after authenticating. Here is the error:

```
[W 2016-07-01 16:55:24.850 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2016-07-01 16:55:24.859 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2016-07-01 16:55:24.879 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-07-01 16:55:24.882 JupyterHub app:968] Starting proxy @ http://*:8443/
16:55:24.978 - info: [ConfigProxy] Proxying https://*:8443 to http://127.0.0.1:8081
16:55:24.980 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8444/api/routes
[I 2016-07-01 16:55:24.986 JupyterHub app:1254] JupyterHub is now running at http://127.0.0.1:8443/
[I 2016-07-01 16:55:32.090 JupyterHub log:100] 302 GET / (@<myIP>) 1.21ms
[I 2016-07-01 16:55:32.127 JupyterHub log:100] 302 GET /hub (@<myIP>) 0.36ms
[I 2016-07-01 16:55:32.169 JupyterHub log:100] 302 GET /hub/ (benrobinson1976@<myIP>) 2.58ms
[I 2016-07-01 16:55:32.226 JupyterHub log:100] 200 GET /hub/home (benrobinson1976@<myIP>) 22.25ms
[I 2016-07-01 16:55:33.452 JupyterHub log:100] 302 GET /hub/spawn (benrobinson1976@<myIP>) 4.55ms
[I 2016-07-01 16:55:33.490 JupyterHub log:100] 302 GET /user/benrobinson1976 (@<myIP>) 1.35ms
[I 2016-07-01 16:55:33.576 JupyterHub spawner:467] Spawning jupyterhub-singleuser --user=benrobinson1976 --port=49475 --cookie-name=jupyter-hub-token-benrobinson1976 --base-url=/user/benrobinson1976 --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1 --notebook-dir=./assignments --NotebookApp.default_url=/notebooks/Welcome.ipynb
[E 2016-07-01 16:55:33.585 JupyterHub user:237] Unhandled error starting benrobinson1976's server: Exception occurred in preexec_fn.
[E 2016-07-01 16:55:33.593 JupyterHub web:1524] Uncaught exception GET /hub/user/benrobinson1976 (<myIP>)
    HTTPServerRequest(protocol='https', host='<mydomain>.com', method='GET', uri='/hub/user/benrobinson1976', version='HTTP/1.1', remote_ip='<myIP>', headers={'X-Forwarded-Proto': 'https', 'X-Forwarded-Port': '443', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Referer': 'https://<mydomain>.com/hub/home', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'en-US,en;q=0.8', 'Host': '<mydomain>.com', 'Connection': 'close', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36', 'Cookie': 'jupyter-hub-token="2|1:0|10:1467318405|17:jupyter-hub-token|44:YTNkYzQxYTgxYTkwNGU2OTg0ZjQ2ZWMzYTM2ODlhMjY=|f1d16dba80ab341948e187654ec472dab1f36b7c351715e654e4f2a47d8bbc08"', 'X-Forwarded-For': '<myIP>'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 494, in get
        yield self.spawn_single_user(current_user)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 247, in spawn
        raise e
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 228, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/spawner.py", line 470, in start
        start_new_session=True, # don't forward signals
      File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.4/subprocess.py", line 1458, in _execute_child
        raise child_exception_type(err_msg)
    subprocess.SubprocessError: Exception occurred in preexec_fn.
```

The <myIP> above appears to be a different subnet from the IP of the EC2 host (internal). Perhaps that's an issue? Here is my config (some values removed):

```python
from jupyter_client.localinterfaces import public_ips
c.JupyterHub.hub_ip = public_ips()[0]

c = get_config()

import os
pjoin = os.path.join
runtime_dir = os.path.join('/srv/jupyterhub')
ssl_dir = pjoin(runtime_dir, 'ssl')
if not os.path.exists(ssl_dir):
        os.makedirs(ssl_dir)

c.JupyterHub.port = 8443
c.JupyterHub.ssl_key = pjoin(ssl_dir, 'privkey.pem')
c.JupyterHub.ssl_cert = pjoin(ssl_dir, 'fullchain.pem')
c.JupyterHub.cookie_secret_file = pjoin(runtime_dir, 'cookie_secret')
c.JupyterHub.db_url = pjoin(runtime_dir, 'jupyterhub.sqlite')
#c.JupyterHub.extra_log_file = '/var/log/jupyterhub.log'
c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.GitHubOAuthenticator.oauth_callback_url = 'https://<mydomain>/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = 'client_id'
c.GitHubOAuthenticator.client_secret = 'secret'
c.Authenticator.create_system_users = True
c.Authenticator.admin_users = {'ubuntu'}
c.Spawner.notebook_dir = './assignments'
c.Spawner.args = ['--NotebookApp.default_url=/notebooks/Welcome.ipynb']
```

I've tried a few different hub_ip's based on comments from this issue log. I also don't see a Docker jupyter container running, but perhaps it's not even getting that far. Any help appreciated, thanks for your time.

**Comment by benrobinson1976** [comment]
This is also not a static instance

**Comment by minrk** [comment]
I'm guessing the assignment directory doesn't exist. The notebook servers must start in directories that exist. Does the user you are logging as already exist on the system?

**Comment by benrobinson1976** [comment]
Thanks for the reply - yes the user (benrobinson1976) was created on the system, I thought due to c.Authenticator.create_system_users = True in the config. It might be more helpful to include another error:
```
 RuntimeError: Failed to create system user benrobinson1976: adduser: Only root may add a user or group to the system.
```

After this I created the user and assignments directory manually and then got the error described previously.

**Comment by minrk** [comment]
Is JupyterHub running as root?

**Comment by benrobinson1976** [comment]
No- the first time I started was running as sudo, but the above errors were all from running as the ubuntu user (no sudo). Do all the users need to be in the same group as user that runs jupyterhub?

**Comment by minrk** [comment]
To create system users, the Hub must be root. To use real users on the system, either the Hub must be root, or a lot of sudo configuration is needed to grant the Hub user access to run notebook servers as different users, and you must use the [sudospawner](https://github.com/jupyterhub/sudospawner).

**Comment by benrobinson1976** [comment]
Ok thanks, I'm still looking into the various options for a multi user system. Starting as root fixed the above problem.
