### ISSUE TITLE
error: unknown option `--error-target'

### ISSUE THREAD

**Issue by updiversity** [jupyterhub/jupyterhub#685]
Hi,

i did recently an update of jupyterhub. Now i have installed version 0.6.1

Unfortunately, when I run with or without certificates, the proxy does not start successfully. I have this error message:

```
error: unknown option `--error-target'

[C 2016-08-10 13:39:34.652 JupyterHub app:1237] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1235, in start
        yield self.start_proxy()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 989, in start_proxy
        _check()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 985, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 1
```

I tried to upgrade configurable-http-proxy, via this command:

`npm install -g configurable-http-proxy
`

but it did not solve the problem neither...

Can somebody help me on this issue ?

**Comment by minrk** [comment]
What is `configurable-http-proxy --version`? This argument was added in CHP 1.0, I believe.

**Comment by minrk** [comment]
You might also check `which -a configurable-http-proxy` in case there's more than one hanging around.

**Comment by willingc** [comment]
Closing issue due to inactivity. Please feel free to reopen if you have further information. Thanks!
