### ISSUE TITLE
Minimal example for adding custom authentication

### ISSUE THREAD

**Issue by nvenayak** [jupyterhub/jupyterhub#756]
I'm trying to authenticate hub from a django app, I'm trying to use the following authentication method:

```
class DjangoAuthenticator(Authenticator):
    @gen.coroutine
    def authenticate(self, handler, data):
        http_client = HTTPClient()

        url = 'http://myhost'+'/get_username_auth'        
        req = HTTPRequest(url,method="GET")
        
        resp = http_client.fetch(req)
        if resp.body.decode('utf8') == 'NOT_AUTHORIZED':
            return None
        else:
            return resp.body.decode('utf8') # .body.decode('utf8', 'replace')

    def get_handlers(self, app):
        return [
            ('/login', DjangoLoginHandler),
        ]

c.JupyterHub.authenticator_class = DjangoAuthenticator
```

Here is the handler, which is fairly similar to the default handler
```
class DjangoLoginHandler(BaseHandler):
    scope = []
    @gen.coroutine
    def get(self):
        user = yield self.get_current_user()
        if user:
            if not next_url:
                if user.running:
                    next_url = user.url
                else:
                    next_url = self.hub.server.base_url
            # set new login cookie
            # because single-user cookie may have been cleared or incorrect
            self.set_login_cookie(self.get_current_user())
            self.redirect(next_url, permanent=False)
        else:
            username = yield self.authenticate('')
            if username:
                self.statsd.incr('login.success')
                self.statsd.timing('login.authenticate.success', auth_timer.ms)
                user = self.user_from_username(username)
                already_running = False

                if user.spawner:
                    status = yield user.spawner.poll()
                    already_running = (status == None)

                if not already_running and not user.spawner.options_form:
                    yield self.spawn_single_user(user)
                self.set_login_cookie(user)
                next_url = self.get_argument('next', default='')

                if not next_url.startswith('/'):
                    next_url = ''
                next_url = next_url or self.hub.server.base_url
                self.redirect(next_url)
                self.log.info("User logged in: %s", username)
```

I get the following error, (I tried the same using the async client and yielding the response, similar to the oauth code with a similar result.

```
jupyterhub |     HTTPServerRequest(protocol='https', host='myhost', method='GET', uri='/hub/login', version='HTTP/1.1', remote_ip='myclient', headers={'X-Forwarded-Port': '443', 'Host': 'myhost', 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-For': 'myclient', 'Connection': 'close', 'X-Forwarded-Proto': 'https', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Cache-Control': 'max-age=0'})
jupyterhub |     Traceback (most recent call last):
jupyterhub |       File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
jupyterhub |         result = yield result
jupyterhub |       File "/srv/jupyterhub/jupyterhub_config.py", line 77, in get
jupyterhub |         user = yield self.get_current_user()
jupyterhub |       File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1090, in handle_yield
jupyterhub |         self.future = convert_yielded(yielded)
jupyterhub |       File "/opt/conda/lib/python3.5/functools.py", line 743, in wrapper
jupyterhub |         return dispatch(args[0].__class__)(*args, **kw)
jupyterhub |       File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1222, in convert_yielded
jupyterhub |         raise BadYieldError("yielded unknown object %r" % (yielded,))
jupyterhub |     tornado.gen.BadYieldError: yielded unknown object None
jupyterhub |
jupyterhub | [D 2016-09-20 02:13:23.802 JupyterHub base:441] No template for 500
jupyterhub | [E 2016-09-20 02:13:23.839 JupyterHub log:99] {
jupyterhub |       "X-Forwarded-Port": "443",
jupyterhub |       "Host": "myhost",
jupyterhub |       "Accept-Language": "en-US,en;q=0.8",
jupyterhub |       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36",
jupyterhub |       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
jupyterhub |       "Upgrade-Insecure-Requests": "1",
jupyterhub |       "X-Forwarded-For": "myclient",
jupyterhub |       "Connection": "close",
jupyterhub |       "X-Forwarded-Proto": "https",
jupyterhub |       "Accept-Encoding": "gzip, deflate, sdch, br",
jupyterhub |       "Cache-Control": "max-age=0"
jupyterhub |     }
```

@rgbkrk @minrk any idea how to get more detailed stack trace or maybe how to directly solve the problem? This is in my config file already `c.JupyterHub.log_level = 'DEBUG'`

For reference, the django view would look something like:

```
def get_username_auth(request):
    # Return the username if authenticated, None if not.
    if request.user.is_authenticated():
        return HttpResponse(request.user.get_username())
    else:
        return HttpResponse('NOT_AUTHORIZED')
```

**Comment by nvenayak** [comment]
Found a solution that should work. There's an issue with the cookies not being read properly but that is another problem:

```
class DjangoLoginHandler(BaseHandler):
    scope = []


    @gen.coroutine
    def get(self):
        user = self.get_current_user()
        if user:
            if not next_url:
                if user.running:
                    next_url = user.url
                else:
                    next_url = self.hub.server.base_url
            # set new login cookie
            # because single-user cookie may have been cleared or incorrect
            self.set_login_cookie(self.get_current_user())
            self.redirect(next_url, permanent=False)
        else:
            username = yield self.authenticate('')
            if username:
                user = self.user_from_username(username)

                self.set_login_cookie(user)
                next_url = self.get_argument('next', default='')

                if not next_url.startswith('/'):
                    next_url = ''
                next_url = next_url or self.hub.server.base_url

                self.log.info("User logged in: %s", username)
                self.redirect(next_url)
            else:
                self.redirect('http://myhost/login?next=/hub/login')

class DjangoAuthenticator(Authenticator):

    @gen.coroutine
    def authenticate(self, handler, data):
        """Authenticate a user with login form data.
        
        This must be a tornado gen.coroutine.
        It must return the username on successful authentication,
        and return None on failed authentication.
        
        Checking the whitelist is handled separately by the caller.
        Args:
            handler (tornado.web.RequestHandler): the current request handler
            data (dict): The formdata of the login form.
                         The default form has 'username' and 'password' fields.
        Return:
            str: the username of the authenticated user
            None: Authentication failed
        """
        http_client = AsyncHTTPClient()

        url = 'http://myhost'+'/get_username_auth'        
        req = HTTPRequest(url,method="GET")
        
        resp = yield http_client.fetch(req)
        if resp.body.decode('utf8') == 'NOT_AUTHORIZED':
            return None
        else:
            return resp.body.decode('utf8') # .body.decode('utf8', 'replace')
    
    def get_handlers(self, app):
        return [('/login', DjangoLoginHandler),]

c.JupyterHub.authenticator_class = DjangoAuthenticator
```
