### ISSUE TITLE
error: [ConfigProxy] Uncaught Exception Error

### ISSUE THREAD

**Issue by cindyburian** [jupyterhub/jupyterhub#774]
I'm trying to get jupyterhub running, and am getting this error when trying to start it:

[root@tyrion jupyterhub]# sudo -u swi /apps/prediction/thirdparty.el6/python-3.5.2/bin/jupyterhub
[I 2016-09-23 15:54:27.035 JupyterHub app:622] Loading cookie_secret from /apps/prediction/thirdparty.el6/jupyterhub/ssl/cookie_secret
[I 2016-09-23 15:54:27.100 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2016-09-23 15:54:27.135 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[I 2016-09-23 15:54:27.141 JupyterHub app:968] Starting proxy @ http://192.132.2.136:443/
15:54:27.238 - info: [ConfigProxy] Proxying https://192.132.2.136:443 to http://127.0.0.1:8081
15:54:27.241 - info: [ConfigProxy] Proxy API at http://127.0.0.1:444/api/routes
15:54:27.245 - error: [ConfigProxy] Uncaught Exception Error: listen EACCES 192.132.2.136:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
15:54:27.245 - error: [ConfigProxy] Uncaught Exception Error: listen EACCES 127.0.0.1:444
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
[C 2016-09-23 15:54:28.151 JupyterHub app:1237] Failed to start proxy
    Traceback (most recent call last):
      File "/apps/prediction/thirdparty.el6/python-3.5.2/lib/python3.5/site-packages/jupyterhub/app.py", line 1235, in start
        yield self.start_proxy()
      File "/apps/prediction/thirdparty.el6/python-3.5.2/lib/python3.5/site-packages/jupyterhub/app.py", line 989, in start_proxy
        _check()
      File "/apps/prediction/thirdparty.el6/python-3.5.2/lib/python3.5/site-packages/jupyterhub/app.py", line 985, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 0
    
I do have jupyterhub_config.py, and these are the lines I have configured:

c.JupyterHub.cookie_secret_file = '$PATH/cookie_secret'
c.JupyterHub.ip = '123.45.6.789'
c.JupyterHub.port = 443
c.JupyterHub.proxy_auth_token = 'LONGNUMBER'
c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'
c.JupyterHub.ssl_cert = '$PATH/new.cert.cert'
c.JupyterHub.ssl_key = '$PATH/new.cert.key'
c.Spawner.notebook_dir = '~/notebooks'
c.Authenticator.admin_users = {'user1', 'user2'}

Thanks for any help.

**Comment by minrk** [comment]
EACCES suggests that the user running the proxy does not have permission to listen on the privileged port 443. By default, you must be root to do this. You can grant node permission to do this without sudo [with setcap](https://gist.github.com/firstdoit/6389682):

    sudo setcap 'cap_net_bind_service=+ep' `which node`

**Comment by willingc** [comment]
@cindyburian Just looping back to your question to see if you have additional questions or if Min's suggestion helped. :smile:

**Comment by cindyburian** [comment]
Sorry for the slow reply - was out all last week.  This fixed it!  One step closer...  Thanks!

**Comment by Srinivasb0** [comment]
Hello. I ran the sudo setcap 'cap_net_bind_service=+ep' `which node` to fix this, but it is throwing an error "Failed to set capabilities on file `/usr/bin/node' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file. How i can fix this?

**Comment by chaoyue729** [comment]
@cindyburian how did u fix the problem?

**Comment by mikecroucher** [comment]
I had the problem that @Srinivasb0 had. So, I did 
```
 which node
```
to get 
```
/usr/bin/node
```
A closer look at this file shows it's a symbolic link
```
ls -l `which node`

lrwxrwxrwx 1 root root 6 Aug  9 20:29 /usr/bin/node -> nodejs
```
So, for me, the fix was to do 
```
sudo setcap 'cap_net_bind_service=+ep' `which nodejs`
```

**Comment by sidebo** [comment]
@cindyburian I'm trying to do the same thing and would like to talk to someone who managed. Can I get in touch?
