### ISSUE TITLE
Is docker image usable?

### ISSUE THREAD

**Issue by lordloh** [jupyterhub/jupyterhub#791]
I attempted to use the jupyter hub as -

```
docker run -d --name jupyterhub -p 0.0.0.0:8182:8182 -p 0.0.0.0:8002:8002 -p 0.0.0.0:8081:8081 jupyterhub/jupyterhub jupyterhub -f /etc/jupyterhub_config.py --port=8182
```

I had to modify ports to avoid port conflicts.

I then created a user and set the password. Followed by a configuration file and set the ports. Here is the result of `ps aux`

```
root         1  8.3  0.2 155340 40612 ?        Ss   07:05   0:00 /opt/conda/bin/python /opt/conda/bin/jupyterhub -f /etc/jupyterhub_config.py --port=8182
root         9  2.2  0.1 668652 19156 ?        Ssl  07:05   0:00 node /usr/local/bin/configurable-http-proxy --ip  --port 8182 --api-ip 0.0.0.0 --api-port 8002 --default-target http://127.0.0.1:8081 --error-target http://127.0.0.1:8081/hub/error
root        11  0.5  0.0  21924  3380 ?        Ss   07:05   0:00 bash
root        16  0.0  0.0  19188  2404 ?        R+   07:05   0:00 ps aux
```

This is my log from `docker log jupyterhub`

```
[I 2016-10-03 05:53:19.214 JupyterHub app:703] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[W 2016-10-03 05:53:19.368 JupyterHub app:344]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2016-10-03 05:53:19.500 JupyterHub app:843] No admin users, admin interface will be unavailable.
[W 2016-10-03 05:53:19.500 JupyterHub app:844] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2016-10-03 05:53:19.500 JupyterHub app:871] Not using whitelist. Any authenticated user will be allowed.
[I 2016-10-03 05:53:19.515 JupyterHub app:1429] Hub API listening on http://0.0.0.0:8081/hub/
[W 2016-10-03 05:53:19.517 JupyterHub app:1155] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2016-10-03 05:53:19.517 JupyterHub app:1157] Starting proxy @ http://*:8182/
05:53:19.587 - info: [ConfigProxy] Proxying http://*:8182 to http://127.0.0.1:8081
05:53:19.588 - info: [ConfigProxy] Proxy API at http://0.0.0.0:8002/api/routes
[I 2016-10-03 05:53:19.620 JupyterHub app:1459] JupyterHub is now running at http://127.0.0.1:8182/
[I 2016-10-03 05:53:34.770 JupyterHub log:100] 302 GET / (@127.0.0.1) 1.52ms
[I 2016-10-03 05:53:34.781 JupyterHub log:100] 302 GET /hub (@127.0.0.1) 0.37ms
[W 2016-10-03 05:53:34.793 JupyterHub pages:32] Disallowing redirect outside JupyterHub: ''
[I 2016-10-03 05:53:34.796 JupyterHub log:100] 302 GET /hub/ (@127.0.0.1) 0.90ms
[I 2016-10-03 05:53:34.804 JupyterHub log:100] 302 GET /login (@127.0.0.1) 0.66ms
[I 2016-10-03 05:53:34.833 JupyterHub log:100] 200 GET /hub/login (@127.0.0.1) 18.44ms
[I 2016-10-03 05:53:39.409 JupyterHub spawner:534] Spawning jupyterhub-singleuser --user=bharath --cookie-name=jupyter-hub-token-bharath --base-url=/user/bharath --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1 --port=42306
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 15, in <module>
    import notebook
ImportError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 17, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[W 2016-10-03 05:53:49.568 JupyterHub web:1545] 500 POST /hub/login?next= (127.0.0.1): Spawner failed to start [status=1]
[E 2016-10-03 05:53:49.577 JupyterHub log:99] {
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36",
      "Dnt": "1",
      "Referer": "http://192.168.144.10:8182/hub/login",
      "Cache-Control": "max-age=0",
      "Host": "192.168.144.10:8182",
      "Content-Length": "34",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Content-Type": "application/x-www-form-urlencoded",
      "Connection": "close",
      "Origin": "http://192.168.144.10:8182",
      "Accept-Language": "en-US,en;q=0.8,en-GB;q=0.6,hi;q=0.4",
      "Upgrade-Insecure-Requests": "1",
      "Cookie": "_ga=GA1.1.892838217.1472976074; _gorilla_csrf=MTQ3NTQ0ODQzM3xJbFppWWxaM1ZsWnhWRk5hZEVaSVZqSTRLMDlYTjIwMVpDOW9iVTAwUVUwMGQzaEtaVlJOUm5OWFJrazlJZ289fNAbVoQal7gtUgBsjIxRTQQ99pWCY--14ft0iaGW6wIL; csrfToken=hdxqKnvqAZfyLG7bTSK26C5PjNmEJDhCsKnKBYRIK8LEVJimwLQow58QIMGyGzFPEp8jl/RM/7ALH+VH+sn/yA=="
    }
[E 2016-10-03 05:53:49.577 JupyterHub log:100] 500 POST /hub/login?next= (@127.0.0.1) 10456.16ms
[W 2016-10-03 05:54:09.645 JupyterHub user:271] bharath's server never showed up at http://127.0.0.1:42306/user/bharath after 30 seconds. Giving up
[E 2016-10-03 05:54:09.831 JupyterHub gen:878] Exception in Future <tornado.concurrent.Future object at 0x7ff914e28710> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 874, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 287, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 263, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:42306/user/bharath didn't respond in 30 seconds
```

The last line of this log shows that port 42306 is not reachable. It was never forwarded. How do I fix this? What have I got wrong?

I get a login screen and a 500 error on logging in.

Thank you.

**Comment by minrk** [comment]
The jupyterhub base image only has what it needs to run the Hub itself, not single-user servers. When the Hub is in a container, typically single-user servers are in separate containers, rather than the same container. If you want to run single-user servers in the same container, you can, but you will need to install additional packages (mainly `pip install notebook` for the most basic).

**Comment by lordloh** [comment]
Thank you, I gathered that from docs and issues. I started by thinking that single user servers and the hub were mutually exclusive. And figured from the logs that they were not. I am not able to figure out how to stringing the jupyterhub container to spawning single-user-server containers  on each user login. 

Are there docs describing this?

Thank you :-)

**Comment by minrk** [comment]
https://github.com/jupyterhub/jupyterhub-deploy-docker is a repo containing a full deployment of JupyterHub via docker-compose, where the Hub is in a container, and DockerSpawner is used to spawn the single-user servers.

**Comment by willingc** [comment]
Hi @lordloh,

Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened if needed. Thanks to all!
