### ISSUE TITLE
SSL: [CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by pcarazo** [jupyterhub/jupyterhub#798]
Hello,

we are having problems to stablish properly the certificates.
The server uses a proxy to redirect the virtual machine to the defined IP 224.
We still don't have a domain, so we are using the Server's IP to create the SSL certs with OpenSSL.
The certs are defined in Apache and JupyterHub, but it gives the following error when we try to authenticate:

```
[W 2016-10-06 09:16:18.782 JupyterHub iostream:1276] SSL Error on 11 ('XXX.XXX.XXX.224', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
[E 2016-10-06 09:16:18.783 JupyterHub web:1524] Uncaught exception GET /hub/hub/oauth_callback?return=https%3A%2F%2FXXX.XXX.XXX.224%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253A8cd01e4d04f341de84375e7840cd47e691f7fa924ea2407e3d76f362b2b4f52a&target=https%3A%2F%2FXXX.XXX.XXX.224%2Fsecure%2F%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252FXXX.XXX.XXX.224%253A443%252Fhub%252Foauth_callback%26client_id%3D (XXX.XXX.XXX.2)
    HTTPServerRequest(protocol='http', host='XXX.XXX.XXX.224', method='GET', uri='/hub/hub/oauth_callback?return=https%3A%2F%2FXXX.XXX.XXX.224%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253A8cd01e4d04f341de84375e7840cd47e691f7fa924ea2407e3d76f362b2b4f52a&target=https%3A%2F%2FXXX.XXX.XXX.224%2Fsecure%2F%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252FXXX.XXX.XXX.224%253A443%252Fhub%252Foauth_callback%26client_id%3D', version='HTTP/1.1', remote_ip='XXX.XXX.XXX.2', headers={'Referer': 'https://IDP/SSO?execution=e2s1&_eventId_proceed=1', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0', 'X-Forwarded-For': 'XXX.XXX.XXX.2', 'Accept-Encoding': 'gzip, deflate, br', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Host': 'XXX.XXX.XXX.224', 'Host': 'XXX.XXX.XXX.224', 'X-Forwarded-Server': 'XXX.XXX.XXX.224', 'Connection': 'close', 'Accept-Language': 'es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Cookie': '_saml_idp=aHR0cHM6Ly9pZHAuaWZjYS5lcy9pZHAvc2hpYmJvbGV0aA%3D%3D; _shibsession_64656661756c7468747470733a2f2f3139332e3134362e37352e3232342f53686962626f6c6574682e73736f=_e52def7a33b6eda13afd8ec5172bf738'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/ubuntu/oauthenticator/oauthenticator/oauth2.py", line 50, in get
        username = yield self.authenticator.authenticate(self)
      File "/home/ubuntu/oauthenticator/oauthenticator/shibd.py", line 65, in authenticate
        resp = yield http_client.fetch(req)
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 264, in <lambda>
        future, lambda future: callback(future.result()))
      File "/usr/local/lib/python3.4/dist-packages/tornado/tcpclient.py", line 174, in connect
        server_hostname=host)
      File "/usr/local/lib/python3.4/dist-packages/tornado/iostream.py", line 1259, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

[D 2016-10-06 09:16:18.788 JupyterHub base:441] No template for 500
[E 2016-10-06 09:16:18.801 JupyterHub log:99] {
      "Referer": "IDP/SSO?execution=e2s1&_eventId_proceed=1",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0",
      "X-Forwarded-For": "XXX.XXX.XXX.2",
      "Accept-Encoding": "gzip, deflate, br",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-Host": "XXX.XXX.XXX.224",
      "Host": "XXX.XXX.XXX.224",
      "X-Forwarded-Server": "XXX.XXX.XXX.224",
      "Connection": "close",
      "Accept-Language": "es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Cookie": "_saml_idp=aHR0cHM6Ly9pZHAuaWZjYS5lcy9pZHAvc2hpYmJvbGV0aA%3D%3D; _shibsession_64656661756c7468747470733a2f2f3139332e3134362e37352e3232342f53686962626f6c6574682e73736f=_e52def7a33b6eda13afd8ec5172bf738"
    }
[E 2016-10-06 09:16:18.801 JupyterHub log:100] 500 GET /hub/hub/oauth_callback?return=https%3A%2F%2FXXX.XXX.XXX.224%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253A8cd01e4d04f341de84375e7840cd47e691f7fa924ea2407e3d76f362b2b4f52a&target=https%3A%2F%2FXXX.XXX.XXX.224%2Fsecure%2F%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252FXXX.XXX.XXX.224%253A443%252Fhub%252Foauth_callback%26client_id%3D (@XXX.XXX.XXX.2) 23.50ms
```

If you need more info let me know ;)

**Comment by minrk** [comment]
What Authenticator are you using? It looks like your OAuth service is using untrusted certs? If you can't use a trusted cert (If you have a domain, certs are free with letsencrypt), then when you connect to the untrusted server you need to disable ssl verification. Wherever your auth is making that connection, you'll need to pass a flag to disable ssl verification.

**Comment by pcarazo** [comment]
Thanks for answering!

With SudoSpawner it works fine, but we'd like to use shibboleth which is giving us headaches so far.
We still don't have a domain so we used the IP as "domain" for the certs.

About the ssl verification, I tried running jupyterhub with using the flag "--no-ssl", but then it can't connect with the kernels. It says "connecting to kernel" all the time.
Did you mean that? Anyway I gonna try disabling ssl verification in firefox.

**Comment by minrk** [comment]
The SSL verification that's failing is not connections to the Hub, it's the Authenticator connecting to your external shibboleth server. This guy:

```
File "/home/ubuntu/oauthenticator/oauthenticator/shibd.py", line 65, in authenticate
        resp = yield http_client.fetch(req)
```

That's where you need to disable certificate validation. From [the docs](http://www.tornadoweb.org/en/stable/httpclient.html?highlight=validate_cert#request-objects), you want to set `validate_cert=False` in the request object here if you know you are making a request of an HTTPS endpoint with an unverifiable cert.

**Comment by pcarazo** [comment]
After setting that flag, these errors appear:

```
Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/home/ubuntu/oauthenticator/oauthenticator/oauth2.py", line 50, in get
        username = yield self.authenticator.authenticate(self)
      File "/home/ubuntu/oauthenticator/oauthenticator/shibd.py", line 68, in authenticate
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))
      File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)
    
[D 2016-10-10 12:16:15.270 JupyterHub base:441] No template for 500
[E 2016-10-10 12:16:15.274 JupyterHub log:99] {
      "Host": "XXX.XXX.XXX.224",
      "Referer": "https://IDP/SSO;jsessionid=E4BB4D738C5DADEB1CDFC5C0578501F4?execution=e1s1&_eventId_proceed=1",
      "Cookie": "_saml_idp=aHR0cHM6Ly9pZHAuaWZjYS5lcy9pZHAvc2hpYmJvbGV0aA%3D%3D; _shibsession_64656661756c7468747470733a2f2f3139332e3134362e37352e3232342f53686962626f6c6574682e73736f=_52f45245f4f312b07c24289f543ddea9",
      "Accept-Encoding": "gzip, deflate, br",
      "Connection": "close",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.5",
      "X-Forwarded-Host": "XXX.XXX.XXX.224",
      "X-Forwarded-Server": "XXX.XXX.XXX.224",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-For": "XXX.XXX.XXX.31",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"
    }
[E 2016-10-10 12:16:15.274 JupyterHub log:100] 500 GET /hub/hub/oauth_callback?return=https%3A%2F%2F193.146.75.224%2FShibboleth.sso%2FSAML2%2FPOST%3Fhook%3D1%26target%3Dss%253Amem%253A774344618b7cd4cc63965482cc8c8237e77eb59f9f72a375e1f5af6c75935322&target=https%3A%2F%2F193.146.75.224%2Fsecure%2F%3Fclient_id%3D%26redirect_uri%3Dhttps%253A%252F%252FXXX.XXX.XXX.224%253A8000%252Fhub%252Foauth_callback%26response_type%3Dcode (@193.144.210.31) 46.58ms

```

**Comment by minrk** [comment]
That looks like your OAuth server isn't sending a JSON response, but your client is decoding it without checking whether it exists. Is your `shibd.py` available online somewhere?

**Comment by pcarazo** [comment]
Here it is:

```
import json
import os

from tornado.auth import OAuth2Mixin
from tornado import gen, web

from tornado.httputil import url_concat
from tornado.httpclient import HTTPRequest, AsyncHTTPClient
from tornado.auth import GoogleOAuth2Mixin
from jupyterhub.auth import LocalAuthenticator

from traitlets import Unicode

from .oauth2 import OAuthLoginHandler, OAuthenticator

SHIBD_HOST = os.environ.get('SHIBD_HOST') or 'XXX.XXX.XXX.224'

class ShibdHandler(OAuthLoginHandler, GoogleOAuth2Mixin):
    _OAUTH_AUTHORIZE_URL = "https://%s/secure" % SHIBD_HOST

class ShibdOAuthenticator(OAuthenticator):

    login_service = "Shibd"
    login_handler = ShibdHandler

    @gen.coroutine
    def authenticate(self, handler):
        http_client = AsyncHTTPClient()
        params = dict(
            field='uid'
        )
        # Determine who the logged in user is
        headers={"Accept": "application/json",
                 "Cookie": handler.request.headers.get("Cookie")
        }

        url_api = "https://%s/secure/api.php" % SHIBD_HOST

        url = url_concat(url_api, params)



        req = HTTPRequest(url,
                          method="GET",
                          headers=headers,
                          validate_cert=False
                        )
        resp = yield http_client.fetch(req)


        resp_json = json.loads(resp.body.decode('utf8', 'replace'))
        username = resp_json["uid"]
        if not username:
            raise web.HTTPError(400, "error login with shibboleth sp")
        if "@" in username:
            username = username.split("@", 1)[0]
        print(username)
        if self.whitelist and username not in self.whitelist:
            username = None
        return username


class LocalShibdOAuthenticator(LocalAuthenticator, ShibdOAuthenticator):

    """A version that mixes in local system user creation"""
    pass

```

**Comment by minrk** [comment]
When you get the response, you'll want to check for error codes, etc. in the response. Given that it's not valid JSON, there is probably an error.

**Comment by pcarazo** [comment]
I've gotten the string which is being decoded.
In the hub that is working we get properly the body (json) and user. But in this one we get the following, and I don't understand why:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <title>Selector de IDP</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-5" />
  <link rel="stylesheet" type="text/css" href="idpselect.css" />
</head>

<body>
  <header>
	<a id="logo" href="http://www.servicecentrelifewatch.eu/home" title="Lifewatch" />">Lifewatch</a>
	<h1>Seleccione su provedor de identidad</h1>
  </header>
  <div id="container">
   <div id="idpSelect"></div>
  </div>
  <footer>
    <div id="copyright">
   		<a href="http://www.mineco.gob.es"><img src="./mineco.jpg" style="height: 50px;"></a>
		<a href="http://www.red.es/redes/%C2%BFquienes-somos/feder"><img src="./feder.png" style="height: 50px;margin-left:50px;margin-right:50px;"></a>
	    
    </div>
  </footer>

  <script src="idpselect_config.js" type="text/javascript" language="javascript"></script>

  <script src="idpselect.js" type="text/javascript" language="javascript"></script>


  <noscript>
    <!-- If you need to care about non javascript browsers you will need to 
         generate a hyperlink to a non-js DS.

         To build you will need:
             - URL:  The base URL of the DS you use
             - EI: Your entityId, URLencoded.  You can get this from the line that 
               this page is called with.
             - RET: Your return address dlib-adidp.ucs.ed.ac.uk. Again you can get
               this from the page this is called with, but beware of the 
               target%3Dcookie%253A5269905f bit..

        < href=${URL}?entityID=${EI}&return=${RET}
     -->

    Your Browser does not support javascript. Please use 
    <a href="http://federation.org/DS/DS?entityID=https%3A%2F%2FyourentityId.edu.edu%2Fshibboleth&return=https%3A%2F%2Fyourreturn.edu%2FShibboleth.sso%2FDS%3FSAMLDS%3D1%26target%3Dhttps%3A%2F%2Fyourreturn.edu%2F">this link</a>.

  </noscript>
</body>
</html>
```

I've checked and JS is enabled in the browsers, and I've updated JS as well in the machine.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
