### ISSUE TITLE
Stop Server freezes jupyterhub

### ISSUE THREAD

**Issue by Fleckenteufel** [jupyterhub/jupyterhub#809]
If I use the "Stop My Server" button to stop the jupyter notebook server, the entire jupyterhub (also for the other users) becomes unresponsive. When I try to restart the server, I get the following error message:

```
[E 2016-10-12 16:50:30.990 JupyterHub app:924] Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)
      Did CONFIGPROXY_AUTH_TOKEN change?
```

The way to get it running again is as suggested [here](http://stackoverflow.com/questions/35183829/jupyterhub-error-503-proxy-target-missing) to kill the proxy process manually.

If it helps I can try to provide additional information, I just don't know what's useful to you. Just let me know.

**Comment by yuvipanda** [comment]
Hello!

Can you provide us the contents of your jupyterhub_config.py file? And also possibly the complete output of `ps auxf` *while* jupyterhub is hanging? And the logs from jupyterhub when you hit 'stop my server'? Thanks!

**Comment by Fleckenteufel** [comment]
This is my effective jupyterhub_config.py file:

``` python
c.JupyterHub.config_file = '/etc/jupyterhub/jupyterhub_config.py'
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.db_url = 'sqlite:///etc/jupyterhub/jupyterhub.sqlite'
c.JupyterHub.ssl_cert = '/etc/ssl/certs/some_file.pem'
c.JupyterHub.ssl_key = '/etc/ssl/private/some_file.key'
c.Spawner.notebook_dir = '~/.jupyter/notebooks'
c.Authenticator.admin_users = {'ehebestreit'}
c.PAMAuthenticator.open_sessions = True
```

The jupyterhub logs are as follows:

```
[I 2016-10-13 07:47:35.329 JupyterHub orm:178] Removing user ehebestreit from proxy
Segmentation fault
root@sisyphous:/# 07:47:35.574 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at Socket.socketOnEnd (_http_client.js:305:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
07:47:35.580 - error: [ConfigProxy] 503 DELETE /hub/api/users/ehebestreit/server
07:47:35.586 - error: [ConfigProxy] Failed to get custom error page Error: connect ECONNREFUSED 127.0.0.1:8081
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
07:47:35.587 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
07:47:35.588 - error: [ConfigProxy] Failed to get custom error page Error: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at Socket.socketCloseListener (_http_client.js:245:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
07:47:35.588 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:245:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
07:49:35.349 - error: [ConfigProxy] Proxy error:  Error: connect ECONNREFUSED 127.0.0.1:8081
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
07:49:35.349 - error: [ConfigProxy] 503 DELETE /hub/api/users/ehebestreit/server
07:49:35.351 - error: [ConfigProxy] Failed to get custom error page Error: connect ECONNREFUSED 127.0.0.1:8081
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
07:49:35.352 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
07:49:35.352 - error: [ConfigProxy] Failed to get custom error page Error: socket hang up
    at createHangUpError (_http_client.js:213:15)
    at Socket.socketCloseListener (_http_client.js:245:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
07:49:35.353 - error: [ConfigProxy] Uncaught Exception TypeError: this._handle_proxy_error_default is not a function
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:333:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:245:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
```

For the output of `ps auxf` there are a lot of other processes running that I don't want to all post here. But what I think is important for this issue:

```
user   12265  0.0  0.0 308676 57704 ?        Ssl  Okt11   1:21 /usr/bin/python3.5 /usr/local/bin/jupyterhub-singleuser --user=user --port=56779 --cookie-name=jupyter-hub-token-user --base-url=/user/user 
user   12285  0.0  0.1 3584336 293404 ?      Ssl  Okt11   2:45  \_ /usr/bin/python3 -m IPython.kernel -f /home/user/.local/share/jupyter/runtime/kernel-41e0476b-bd1f-4ba0-b81e-c28d417b3ca8.json
user   14446  0.0  0.1 3576016 285084 ?      Ssl  Okt11   1:50  \_ /usr/bin/python3 -m IPython.kernel -f /home/user/.local/share/jupyter/runtime/kernel-3603303a-da87-4f21-84d3-2ea55a936307.json
user   10773  0.0  0.0 3435516 144616 ?      Ssl  Okt12   0:23  \_ /usr/bin/python3 -m IPython.kernel -f /home/user/.local/share/jupyter/runtime/kernel-a3e92a02-6294-4b7c-a548-a85d2f8d6ddd.json
user   24472  0.0  0.0 3405908 114836 ?      Ssl  Okt12   0:15  \_ /usr/bin/python3 -m IPython.kernel -f /home/user/.local/share/jupyter/runtime/kernel-deec9539-fa7b-4f10-b507-c54bd1e7ef21.json
...
root      5886  0.0  0.0 947404 30260 pts/1    Sl   07:47   0:00 node /usr/local/bin/configurable-http-proxy --ip  --port 8000 --api-ip 127.0.0.1 --api-port 8001 --default-target http://127.0.0.1:8081 --error-ta
```

The jupyterhub process seems to have ended.

I realized that the same issue also appears if I want to stop my jupyterhub service (I created a service as described [here](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service)). So I don't necessarily have to stop a server for this to happen.

After restarting the jupyterhub, all the single-user servers are running again and all the notebooks are open.

**Comment by Fleckenteufel** [comment]
Maybe this is interesting: I get a Segmentation Fault as well, if I try to close a session with `pamtester`:

```
root@local-server:~# pamtester login ehebestreit open_session
...
(pam_mount.c:568): pam_mount 2.14: entering session stage
(pam_mount.c:629): no volumes to mount
command: 'pmvarrun' '-u' 'ehebestreit' '-o' '1' 
(pmvarrun.c:258): parsed count value 11
(pam_mount.c:441): pmvarrun says login count is 12
(pam_mount.c:660): done opening session (ret=0)
pamtester: successfully opened a session
(pam_mount.c:116): Clean global config (0)
root@local-server:~# pamtester login ehebestreit close_session
Segmentation fault
```

However, doing opening and closing in one run, it works:

```
root@local-server:~# pamtester -v login ehebestreit open_session close_session
pamtester: invoking pam_start(login, ehebestreit, ...)
pamtester: performing operation - open_session
...
(pam_mount.c:568): pam_mount 2.14: entering session stage
(pam_mount.c:629): no volumes to mount
command: 'pmvarrun' '-u' 'ehebestreit' '-o' '1' 
(pmvarrun.c:258): parsed count value 12
(pam_mount.c:441): pmvarrun says login count is 13
(pam_mount.c:660): done opening session (ret=0)
pamtester: successfully opened a session
pamtester: performing operation - close_session
(pam_mount.c:706): received order to close things
(pam_mount.c:709): No volumes to umount
command: 'pmvarrun' '-u' 'ehebestreit' '-o' '-1' 
(pmvarrun.c:258): parsed count value 13
(pam_mount.c:441): pmvarrun says login count is 12
(pam_mount.c:735): ehebestreit seems to have other remaining open sessions
(pam_mount.c:743): pam_mount execution complete
pamtester: session has successfully been closed.
(pam_mount.c:116): Clean global config (0)
```

I don't know if I just used pamtester wrong, or if this is related to what happens in jupyterhub.

**Comment by willingc** [comment]
Hi @Fleckenteufel,

I'm going to close this issue since it's been a few months with no activity. You mentioned in your last message that you were able to get things working. Thanks and please feel free to request this to be reopened if there are still outstanding questions :-)

**Comment by lucy-itjob** [comment]
Hi Willingc,

My problem may related to this issue , so I reply these here;

We I try to restart the Jupyther Hub, Here is the error

########Error########
[I 2017-10-06 10:13:34.703 JupyterHub app:622] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2017-10-06 10:13:34.732 JupyterHub app:304] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[W 2017-10-06 10:13:34.736 JupyterHub app:757] No admin users, admin interface will be unavailable.
[W 2017-10-06 10:13:34.736 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-10-06 10:13:34.736 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
[I 2017-10-06 10:13:34.753 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
[E 2017-10-06 10:13:34.768 JupyterHub app:924] Proxy appears to be running at http://*:8000/, but I can't access it (HTTP 403: Forbidden)
    Did CONFIGPROXY_AUTH_TOKEN change?

##

**Comment by lucy-itjob** [comment]
willing,
I attached the jupyterhub_config.py as txt file here, could you please provide the advise here?

Thanks

[jupyterhub_config.py.txt](https://github.com/jupyterhub/jupyterhub/files/1362969/jupyterhub_config.py.txt)

**Comment by minrk** [comment]
That error suggests that the proxy is running before JupyterHub started. Given that `CONFIGPROXY_AUTH_TOKEN` is not set, this can mean that JupyterHub did not shutdown cleanly. Look for a process called `configurable-http-proxy` and shut it down, and shutdown all jupyter-related processes, then try starting jupyterhub again.
