### ISSUE TITLE
jupyterhub.sqlite chunks my username in to chars

### ISSUE THREAD

**Issue by ricdea** [jupyterhub/jupyterhub#816]
I'm trying to set up jupyterhub on centos 7 but when running the jupyterhub command in the terminal, I get an error message like this:

```
(python3) 09:54:47 richard.dean datascicol02 /home/richard.dean/jupyterhub
$ jupyterhub
[I 2016-10-14 09:54:49.767 JupyterHub app:622] Loading cookie_secret from /home/richard.dean/jupyterhub/jupyterhub_cookie_secret
[W 2016-10-14 09:54:49.812 JupyterHub app:304]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[E 2016-10-14 09:54:49.852 JupyterHub app:1296]
    Traceback (most recent call last):
      File "/home/richard.dean/anaconda2/envs/python3/lib/python3.5/site-packages/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/home/richard.dean/anaconda2/envs/python3/lib/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/home/richard.dean/anaconda2/envs/python3/lib/python3.5/site-packages/jupyterhub/app.py", line 1102, in initialize
        yield self.init_users()
      File "/home/richard.dean/anaconda2/envs/python3/lib/python3.5/site-packages/jupyterhub/app.py", line 803, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/home/richard.dean/anaconda2/envs/python3/lib/python3.5/site-packages/jupyterhub/auth.py", line 328, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User d does not exist.'

```

On deleting the jupyterhub.sqlite instance, and rerunning, I'd always get a similar error, but with a different character from my username.

Here's the contents of the Users table:
```
>>> import sqlite3
>>> con = sqlite3.connect("jupyterhub.sqlite")
>>> cur = con.cursor()
>>> cur.execute("SELECT * FROM Users")
<sqlite3.Cursor object at 0x7fa5e62d3ce0>
>>> rows = cur.fetchall()
>>> for row in rows:
...   print(row)
...
(1, 'd', None, 1, '2016-10-14 08:50:27.765199', 'c78d9bdc651b4eefa5c79e371e8db659', None)
(2, 'i', None, 1, '2016-10-14 08:50:27.790153', 'fe2660e2c5af4f7bb310836257dfaa64', None)
(3, 'a', None, 1, '2016-10-14 08:50:27.791579', '89623024186046d8855166bf6beb5bbc', None)
(4, 'n', None, 1, '2016-10-14 08:50:27.792977', '10a4846c35114876aeb6ce77f9fb9bfe', None)
(5, 'c', None, 1, '2016-10-14 08:50:27.794406', '7b5083883f4a4125b5fb3449dc4bece1', None)
(6, 'h', None, 1, '2016-10-14 08:50:27.795858', '8eeea5e870764af3b1865de28e56c4b2', None)
(7, 'r', None, 1, '2016-10-14 08:50:27.797272', '8823887fd5984623aabbaec6041f8f75', None)
(8, '.', None, 1, '2016-10-14 08:50:27.798741', '845393822c6f48b99560ef9f3387b4f9', None)
(9, 'e', None, 1, '2016-10-14 08:50:27.800292', 'f2a76dc7cc5049738a1178b27059abd1', None)

```

All the users it has created are just single characters from my username "richard.dean".

How can I fix this?

**Comment by minrk** [comment]
This is most likely caused by a typo in a config file, such as:

```python
c.Authenticator.admin_users = set('username')
```

which is equivalent to:

```python
{'u', 's', 'e', 'r', 'n', 'a', 'm'}
```

when you want:

```python
c.Authenticator.admin_users = set(['username'])
```

(same goes for whitelist)

**Comment by ricdea** [comment]
Thanks. That worked.
