### ISSUE TITLE
DELETE /api/users/{name}/server ... stops server, but then restarts new one automatically

### ISSUE THREAD

**Issue by Analect** [jupyterhub/jupyterhub#874]
**How to reproduce the issue**
Run up a JupyterHub using the latest 0.7b1 release, as per this pending [pull request](https://github.com/jupyterhub/jupyterhub-deploy-docker/pull/27). I'm using it in conjunction with JupyterLab.  I manually added tokens for a number of users into the jupyter_config.py file, as per [here](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/rest.md#adding-tokens-to-the-config-file).

**What you expected to happen**
For the server to be stopped and the relevant user's 'server' container to be removed.

**What actually happens**
Container state prior to sending the DELETE API call:
```
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED              STATUS              PORTS                            NAMES
a185f614d2d7        mydockerregistry.com:5050/jupyter/datascience-notebook:jlab0.1   "tini -- start-single"   About a minute ago   Up About a minute   8888/tcp                         jupyter-testuser
46c891d3e0e7        mydockerregistry.com:5050/jupyter/jupyterhub:0.7.0b1_jlab        "jupyterhub -f /srv/j"   30 minutes ago       Up 30 minutes       0.0.0.0:443->443/tcp, 8000/tcp   jupyterhub
```
The API call succeeds with a 204 response.  As per below, the 'server' container is stopped and removed.  However, a new one is immediately started.  Perhaps this is a resiliency feature built into the [jupyterhub-deploy-docker](https://github.com/jupyterhub/jupyterhub-deploy-docker) implementation, although I haven't been able to find it documented anywhere.  If so, is there a parameter I can pass in the DELETE API call that could over-ride this behaviour.

Given there's no multi-server feature per user at this point, ideally, I'm looking to be able to stop a user's server (via the API) and spawn a separate one, but potentially pointing to a different image ... and so I don't want it restarting with the same image automatically, as it is doing now.

```
jupyterhub | [I 2016-11-17 09:49:28.709 JupyterHub orm:207] Removing user testuser from proxy
jupyterhub | [I 2016-11-17 09:49:28.717 JupyterHub dockerspawner:474] Stopping container jupyter-testuser (id: a185f61)
jupyterhub | [I 2016-11-17 09:49:28.910 JupyterHub dockerspawner:480] Removing container jupyter-testuser (id: a185f61)
jupyterhub | [I 2016-11-17 09:49:28.942 JupyterHub base:388] User testuser server took 0.231 seconds to stop
jupyterhub | [I 2016-11-17 09:49:28.950 JupyterHub log:100] 204 DELETE /hub/api/users/testuser/server (testuser@172.18.0.2) 247.23ms
jupyterhub | [I 2016-11-17 09:49:30.061 JupyterHub log:100] 302 GET /user/testuser/api/terminals?1479376171385 (@172.18.0.2) 2.68ms
jupyterhub | [I 2016-11-17 09:49:30.084 JupyterHub dockerspawner:332] Container 'jupyter-testuser' is gone
jupyterhub | [W 2016-11-17 09:49:30.084 JupyterHub dockerspawner:303] container not found
jupyterhub | [I 2016-11-17 09:49:30.105 JupyterHub dockerspawner:332] Container 'jupyter-testuser' is gone
jupyterhub | [I 2016-11-17 09:49:30.154 JupyterHub dockerspawner:394] Created container 'jupyter-testuser' (id: 256a16d) from image mydockerregistry.com:5050/jupyter/datascience-notebook:jlab0.1
jupyterhub | [I 2016-11-17 09:49:30.154 JupyterHub dockerspawner:404] Starting container 'jupyter-testuser' (id: 256a16d)
jupyterhub | [I 2016-11-17 09:49:31.468 JupyterHub base:322] User testuser server took 1.383 seconds to start
jupyterhub | [I 2016-11-17 09:49:31.468 JupyterHub orm:188] Adding user testuser to proxy /user/testuser => http://172.18.0.3:8888
jupyterhub | [I 2016-11-17 09:49:31.482 JupyterHub log:100] 302 GET /hub/user/testuser/api/terminals?1479376171385 (testuser@172.18.0.2) 1400.89ms
```
Container state a few seconds after the DELETE API call:
```
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED             STATUS              PORTS                            NAMES
256a16d573a3        mydockerregistry.com:5050/jupyter/datascience-notebook:jlab0.1   "tini -- start-single"   37 seconds ago      Up 35 seconds       8888/tcp                         jupyter-testuser
46c891d3e0e7        mydockerregistry.com:5050/jupyter/jupyterhub:0.7.0b1_jlab        "jupyterhub -f /srv/j"   32 minutes ago      Up 32 minutes       0.0.0.0:443->443/tcp, 8000/tcp   jupyterhub
```

**Share what version of JupyterHub you are using**
0.7b1 (as per top)
Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

`jupyter troubleshoot` output here:
https://gist.github.com/Analect/b77f07b67e11b25b6a7635713804b310

**Comment by minrk** [comment]
This is the key line:

> `jupyterhub | [I 2016-11-17 09:49:30.061 JupyterHub log:100] 302 GET /user/testuser/api/terminals?1479376171385 (@172.18.0.2) 2.68ms`

The user apparently still has open windows on their existing server. In this case, a terminal page. Requesting a page from the server when it's not running triggers a new spawn. This is not optional at the moment, but it could be.

**Comment by Analect** [comment]
OK. That's good to know.

A. If you run up a JupyterLab ... and open a few *.ipynbs ... and a few terminals ... then then select Close All from the menu.  The terminals will remain.

![image](https://cloud.githubusercontent.com/assets/4063815/20428686/4dcdc912-ad82-11e6-8ed6-521cf9200e47.png)

B. If you then go back to the admin page and hit 'stop server' ... as you said, because the terminals didn't close out (in A above), they are causing a new container to spawn.

While this might suit certain users, I think if there was a possibility for a hard close with the API call, that would be really helpful.

C.  In fact, as an additional test, I manually closed out any remaining terminals ... so even with a web-page open, and no component windows 'live', then going back into admin and hitting 'stop server' ... it will still spawner another container after a few seconds.

![image](https://cloud.githubusercontent.com/assets/4063815/20428955/c8e1186a-ad83-11e6-83ae-b870fabe9aae.png)

I notice in the logs, this phantom terminal is there again ... but I'm not aware of any other window open exposing Jupyterhub ... other than the 'empty' jupyterlab above ... and the hub admin page .. where I am actively hitting 'stop server' each time ... and then observing the new container getting added each time.

```
[I 2016-11-18 11:50:07.625 JupyterHub log:100] 204 DELETE /hub/api/users/testuser/server (testuser@172.18.0.2) 221.34ms
[I 2016-11-18 11:50:09.061 JupyterHub log:100] 200 GET /hub/admin (testuser@172.18.0.2) 7.18ms
[I 2016-11-18 11:50:12.081 JupyterHub log:100] 200 GET /hub/admin (testuser@172.18.0.2) 7.14ms
[I 2016-11-18 11:50:14.832 JupyterHub log:100] 302 GET /user/testuser/api/terminals?1479469816642 (@172.18.0.2) 0.94ms
[I 2016-11-18 11:50:14.838 JupyterHub log:100] 302 GET /user/testuser/api/contents/?content=1&1479469816643 (@172.18.0.2) 0.79ms
[I 2016-11-18 11:50:14.867 JupyterHub dockerspawner:332] Container 'jupyter-testuser' is gone
[W 2016-11-18 11:50:14.867 JupyterHub dockerspawner:303] container not found
[I 2016-11-18 11:50:14.887 JupyterHub dockerspawner:332] Container 'jupyter-testuser' is gone
[W 2016-11-18 11:50:14.888 JupyterHub dockerspawner:303] container not found
[I 2016-11-18 11:50:14.892 JupyterHub dockerspawner:332] Container 'jupyter-testuser' is gone
[E 2016-11-18 11:50:14.892 JupyterHub web:1548] Uncaught exception GET /hub/user/testuser/api/contents/?content=1&1479469816643 (172.18.0.2)
    HTTPServerRequest(protocol='http', host='myjupyterhubserver.com', method='GET', uri='/hub/user/testuser/api/contents/?content=1&1479469816643', version='HTTP/1.1', remote_ip='172.18.0.2', headers={'Connection': 'close', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Cookie': 'jupyter-hub-token="2|1:0|10:1479459591|17:jupyter-hub-token|44:MjNkNzQ0Nzg2YzljNGUwM2I3MzA2OWU3ZTYzM2Y2MTU=|67936c55396f9c0605c8728a39ce751f9796ac12bee121541e733551ac757df2"', 'Host': 'myjupyterhubserver.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36', 'Referer': 'https://myjupyterhubserver.com/user/testuser/lab', 'Accept-Language': 'en-US,en;q=0.8', 'Accept': '*/*'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 535, in get
        yield self.spawn_single_user(current_user)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 306, in spawn_single_user
        raise RuntimeError("Spawn already pending for: %s" % user.name)
    RuntimeError: Spawn already pending for: testuser
    
[E 2016-11-18 11:50:14.902 JupyterHub log:99] {
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1479459591|17:jupyter-hub-token|44:MjNkNzQ0Nzg2YzljNGUwM2I3MzA2OWU3ZTYzM2Y2MTU=|67936c55396f9c0605c8728a39ce751f9796ac12bee121541e733551ac757df2\"",
      "Host": "myjupyterhubserver.com",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36",
      "Referer": "https://myjupyterhubserver.com/user/testuser/lab",
      "Accept-Language": "en-US,en;q=0.8",
      "Accept": "*/*"
    }
[E 2016-11-18 11:50:14.902 JupyterHub log:100] 500 GET /hub/user/testuser/api/contents/?content=1&1479469816643 (testuser@172.18.0.2) 36.72ms
[I 2016-11-18 11:50:14.952 JupyterHub dockerspawner:394] Created container 'jupyter-testuser' (id: 991e5f2) from image test-paas-private
[I 2016-11-18 11:50:14.952 JupyterHub dockerspawner:404] Starting container 'jupyter-testuser' (id: 991e5f2)
[I 2016-11-18 11:50:15.707 JupyterHub log:100] 200 GET /hub/admin (testuser@172.18.0.2) 16.27ms
[I 2016-11-18 11:50:16.262 JupyterHub base:322] User testuser server took 1.395 seconds to start
[I 2016-11-18 11:50:16.263 JupyterHub orm:188] Adding user testuser to proxy /user/testuser => http://172.18.0.3:8888
[I 2016-11-18 11:50:16.275 JupyterHub log:100] 302 GET /hub/user/testuser/api/terminals?1479469816642 (testuser@172.18.0.2) 1414.53ms
[I 2016-11-18 11:50:16.446 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-testuser/[secret] (testuser@172.18.0.3) 10.72ms
[I 2016-11-18 11:50:18.889 JupyterHub log:100] 200 GET /hub/admin (testuser@172.18.0.2) 9.35ms
```

**Comment by Analect** [comment]
Just as a follow-up to the above .. .when I eventually close the empty JupyterLab browser window, the automatic re-spawning resolves itself.  But it seems to suggest that for whatever reason .. that terminal pinging back to the hub was alive in there somewhere .. .but not visible as an entity in any of the windows ... and not showing up under the 'terminal sessions' area.

**Comment by minrk** [comment]
That is likely a bug in the JupyterLab terminals not cleaning up after themselves.

**Comment by Analect** [comment]
Should I open and issue there ... and point back to here?

**Comment by minrk** [comment]
That would be great!

**Comment by willingc** [comment]
Thanks @Analect!
