### ISSUE TITLE
Nonexistent user in c.Authenticator.whitelist causes crash even after change

### ISSUE THREAD

**Issue by bwkeller** [jupyterhub/jupyterhub#923]
Hello,

I seem to have encountered a little bug.  I'm running Jupyterhub 0.6.1, and I discovered that if a user is added to c.Authenticator.whitelist in the jupyterhub config file, the server will crash on start with the following error:

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1102, in initialize
        yield self.init_users()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 803, in init_users
        yield gen.maybe_future(self.authenticator.add_user(user))
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/auth.py", line 328, in add_user
        raise KeyError("User %s does not exist." % user.name)
    KeyError: 'User NONEXISTENT does not exist.'

```

Now, that is of course sensible behavior.  However, if that user is removed from the whitelist in the config file, jupyterhub will no still be unable to start up, crashing immediately with the same traceback unless the jupyterhub.sqlite file is removed.  While this isn't catastrophic (especially with such a simple workaround), I imagine it could trip some users.

```
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/lib/jvm/java-8-oracle/bin
	/usr/lib/jvm/java-8-oracle/db/bin
	/usr/lib/jvm/java-8-oracle/jre/bin

sys.path:
	/usr/local/bin
	/usr/lib/python2.7
	/usr/lib/python2.7/plat-x86_64-linux-gnu
	/usr/lib/python2.7/lib-tk
	/usr/lib/python2.7/lib-old
	/usr/lib/python2.7/lib-dynload
	/usr/local/lib/python2.7/dist-packages
	/usr/lib/python2.7/dist-packages
	/usr/lib/python2.7/dist-packages/gtk-2.0

sys.executable:
	/usr/bin/python

sys.version:
	2.7.6 (default, Oct 26 2016, 20:30:19) 
	[GCC 4.8.4]

platform.platform():
	Linux-3.13.0-106-generic-x86_64-with-Ubuntu-14.04-trusty

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	apt-xapian-index (0.45)
	asyncoro (4.2.2)
	attrs (16.2.0)
	backports-abc (0.4)
	backports.shutil-get-terminal-size (1.0.0)
	backports.ssl-match-hostname (3.5.0.1)
	BeautifulSoup (3.2.1)
	beautifulsoup4 (4.5.1)
	bokeh (0.12.3)
	Bottleneck (1.1.0)
	bs4 (0.0.1)
	cassandra-driver (3.0.0)
	cassandra-pylib (0.0.0)
	ccm (2.1.2)
	certifi (2016.9.26)
	cffi (1.6.0)
	chardet (2.0.1)
	click (6.6)
	colorama (0.2.5)
	configparser (3.5.0)
	cryptography (1.3.1)
	cssselect (0.9.1)
	cycler (0.10.0)
	Cython (0.20.1.post0)
	dask (0.11.1)
	decorator (4.0.10)
	dispy (4.6.16)
	docutils (0.11)
	entrypoints (0.2.2)
	enum34 (1.1.6)
	Flask (0.11.1)
	funcsigs (1.0.2)
	functools32 (3.2.3.post2)
	future (0.16.0)
	futures (3.0.3)
	gunicorn (19.6.0)
	gyp (0.1)
	html5lib (0.999)
	idna (2.1)
	ipaddress (1.0.16)
	ipykernel (4.5.0)
	ipython (5.1.0)
	ipython-genutils (0.1.0)
	ipywidgets (5.2.2)
	itsdangerous (0.24)
	Jinja2 (2.8)
	joblib (0.10.0)
	jsonschema (2.5.1)
	jupyter (1.0.0)
	jupyter-client (4.4.0)
	jupyter-console (5.0.0)
	jupyter-core (4.2.0)
	keen (0.3.26)
	lxml (3.3.3)
	MarkupSafe (0.23)
	matplotlib (1.5.3)
	mistune (0.7.3)
	mock (2.0.0)
	mpi4py (2.0.0)
	mpmath (0.19)
	nbconvert (4.2.0)
	nbformat (4.1.0)
	ndg-httpsclient (0.4.2)
	nose (1.3.1)
	notebook (4.2.3)
	numexpr (2.6.1)
	numpy (1.11.2)
	pandas (0.19.1)
	pathlib2 (2.1.0)
	patsy (0.4.1)
	pbr (1.10.0)
	pexpect (4.2.1)
	pickleshare (0.7.4)
	Pillow (2.3.0)
	pip (9.0.1)
	prompt-toolkit (1.0.9)
	protobuf (3.0.0b2)
	ptyprocess (0.5.1)
	py (1.4.31)
	pyasn1 (0.1.9)
	pyasn1-modules (0.0.8)
	pycassa (1.11.1)
	pycparser (2.14)
	pycryptodome (3.4.3)
	Pygments (2.1.3)
	pyinotify (0.9.4)
	pyOpenSSL (16.0.0)
	pyparsing (2.1.5)
	pytest (3.0.1)
	python-apt (0.9.3.5ubuntu2)
	python-dateutil (2.5.3)
	python-debian (0.1.21-nmu2ubuntu2)
	pytz (2016.7)
	PyYAML (3.11)
	pyzmq (16.0.0)
	qtconsole (4.2.1)
	queuelib (1.4.2)
	requests (2.10.0)
	roman (2.0.0)
	scikit-learn (0.18)
	scipy (0.17.1)
	Scrapy (1.0.5)
	seaborn (0.7.1)
	service-identity (16.0.0)
	setuptools (28.8.0)
	simplegeneric (0.8.1)
	simplejson (3.3.1)
	singledispatch (3.4.0.3)
	six (1.10.0)
	sklearn (0.0)
	sp (1.1.0)
	Sphinx (1.2.2)
	ssh-import-id (3.21)
	statsmodels (0.6.1)
	sympy (1.0)
	tables (3.3.0)
	tensorflow (0.10.0)
	terminado (0.6)
	thrift (0.9.3)
	tornado (4.4.2)
	tqdm (4.8.4)
	traitlets (4.3.1)
	tsfresh (0.3.0)
	Twisted (16.1.1)
	urllib3 (1.7.1)
	w3lib (1.14.2)
	wcwidth (0.1.7)
	Werkzeug (0.11.10)
	wheel (0.29.0)
	widgetsnbextension (1.2.6)
	zope.interface (4.1.3)
```

**Comment by minrk** [comment]
Indeed it could! Users are added to the database from the whitelist, but users not in the whitelist that have been added previously remain in the database, though they won't be allowed to login. You can delete these users from the admin page, or you can clear the `jupyterhub.sqlite` database and start fresh.

**Comment by bwkeller** [comment]
Oh man, I see that this is explained in the docs too.  Should have done some more reading before I opened this issue.  Sorry all.

**Comment by willingc** [comment]
@bwkeller No problem. Thanks for bringing the question up as I think the docs could actually be clearer on this topic.

**Comment by minrk** [comment]
Also a mitigation: JupyterHub 0.7 demotes this error from a crash to a logged error, so it should be less of an impediment.
