### ISSUE TITLE
Error 500 with Kernel over Nginx

### ISSUE THREAD

**Issue by camilo-nunez** [jupyterhub/jupyterhub#940]
Hi! I try to run a api with nginx and a subdomain. At first, I had problems not recognizing the kernel, but a use the [config](https://gist.github.com/zonca/08c413a37401bdc9d2a7f65a7af44462) file of [Zonca](https://gist.github.com/zonca) and it worked. However, at the time of running a kernel on a notebook (2.7 or 3), the state of this is only in the mode "Connecting to kernel". Also, when i see the "Conda environments" i get this internal error:

`[E 2017-01-17 00:05:14.610 camilo.nunez handlers:514] Unhandled error in API request
    Traceback (most recent call last):
      File "/etc/anaconda3/lib/python3.5/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/etc/anaconda3/lib/python3.5/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/etc/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/etc/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in <listcomp>
        "packages": [pkg_info(package) for package in data]
      File "/etc/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
[E 2017-01-17 00:05:14.613 camilo.nunez log:46] {
      "Dnt": "1",
      "Accept-Language": "es-es",
      "X-Nginx-Proxy": "true",
      "X-Forwarded-For": "190.96.59.193,::ffff:127.0.0.1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12",
      "Cookie": "jupyter-hub-token-camilo.nunez=\"2|1:0|10:1484622311|30:jupyter-hub-token-camilo.nunez|44:NTdmYmE0OWI5NWZmNGU2NjhiMmRkZWYyMTc4YjFlOTc=|be29eb34d1375b67b69e11622906abe4a8ea2c63966ccf067b03a7a6074636dd\"; _xsrf=2|70883bec|23c97fbc1587cba43eeddb01a790805f|1484620606",
      "Host": "student.cnf.cl",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "Connection": "close",
      "Referer": "https://student.cnf.cl/user/camilo.nunez/tree?",
      "X-Forwarded-Host": "student.cnf.cl",
      "Accept-Encoding": "gzip, deflate",
      "X-Real-Ip": "190.96.59.193",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "80"
    }
[E 2017-01-17 00:05:14.615 camilo.nunez log:47] 500 GET /user/camilo.nunez/conda/environments/root?_=1484622310554 (190.96.59.193) 941.18ms referer=https://student.cnf.cl/user/camilo.nunez/tree?`

I don't know if this internal error has to do with kernel error.

annex:

My Nginx .conf:
```

# HTTP server to redirect all 80 traffic to SSL/HTTPS

include /etc/nginx/mime.types;
#default_type application/octet-stream;
server {
    listen 80;
    server_name student.cnf.cl;

    # Tell all requests to port 80 to be 302 redirected to HTTPS
    return 302 https://$host$request_uri;
}

# HTTPS server to handle JupyterHub
server {
    listen 443;

    client_max_body_size 50M;
    server_name student.cnf.cl;

    error_log  /data/hub_progra/log/nginx/error.log;
    access_log /data/hub_progra/log/nginx/access.log;

    ssl on;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key  /etc/nginx/ssl/nginx.key;

        ssl_ciphers "AES128+EECDH:AES128+EDH";
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        ssl_stapling on; # Requires nginx >= 1.3.7
        ssl_stapling_verify on; # Requires nginx => 1.3.7
        resolver_timeout 5s;

    # Managing literal requests to the JupyterHub front end
    location / {
        proxy_pass http://127.0.0.1:8027;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-NginX-Proxy true;
    }

        location ~* /(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)/? {
            proxy_pass http://127.0.0.1:8027;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-NginX-Proxy true;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;

        }

}

```

jupyterhub_config.py

```
c = get_config()

import os
pjoin = os.path.join

runtime_dir = os.path.join('/data/hub_progra')

# Port to public
c.JupyterHub.port = 8027
c.JupyterHub.confirm_no_ssl = True

# Force the proxy to only listen to connections to 127.0.0.1
#c.JupyterHub.ip = '127.0.0.1'

# Only SSl
#ssl_dir = pjoin(runtime_dir, 'ssl')
#if not os.path.exists(ssl_dir):
#    os.makedirs(ssl_dir)
#c.JupyterHub.ssl_cert = "/etc/nginx/ssl/nginx.crt"
#c.JupyterHub.ssl_key = "/etc/nginx/ssl/nginx.key"



# JupyterHub cookie secret and state db
c.JupyterHub.cookie_secret_file = pjoin(runtime_dir, 'cookie_secret')
c.JupyterHub.db_url = pjoin(runtime_dir, 'jupyterhub.sqlite')

# put the log file in /var/log
c.JupyterHub.extra_log_file = '/data/hub_progra/log/jupyterhub.log'

# specify users and admin
c.Authenticator.whitelist = {'camilo.nunez'}
c.Authenticator.admin_users = {'camilo.nunez'}
 ```

Output of jupyter troubleshoot:
```
$PATH:
	/etc/anaconda3/bin
	/etc/anaconda3/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/local/rvm/bin

sys.path:
	/etc/anaconda3/bin
	/etc/anaconda3/lib/python35.zip
	/etc/anaconda3/lib/python3.5
	/etc/anaconda3/lib/python3.5/plat-linux
	/etc/anaconda3/lib/python3.5/lib-dynload
	/etc/anaconda3/lib/python3.5/site-packages
	/etc/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg
	/etc/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg

sys.executable:
	/etc/anaconda3/bin/python

sys.version:
	3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
	[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

platform.platform():
	Linux-3.16.0-4-amd64-x86_64-with-debian-8.7

which -a jupyter:
	/etc/anaconda3/bin/jupyter
	/etc/anaconda3/bin/jupyter

pip list:
	alabaster (0.7.9)
	anaconda-clean (1.0)
	anaconda-client (1.5.1)
	anaconda-navigator (1.3.1)
	argcomplete (1.0.0)
	astroid (1.4.7)
	astropy (1.2.1)
	Babel (2.3.4)
	backports.shutil-get-terminal-size (1.0.0)
	beautifulsoup4 (4.5.1)
	bitarray (0.8.1)
	blaze (0.10.1)
	bokeh (0.12.2)
	boto (2.42.0)
	Bottleneck (1.1.0)
	cffi (1.7.0)
	chest (0.2.3)
	click (6.6)
	cloudpickle (0.2.1)
	clyent (1.2.2)
	colorama (0.3.7)
	conda (4.3.4)
	conda-build (2.0.2)
	configobj (5.0.6)
	contextlib2 (0.5.3)
	cryptography (1.5)
	cycler (0.10.0)
	Cython (0.24.1)
	cytoolz (0.8.0)
	dask (0.11.0)
	datashape (0.5.2)
	decorator (4.0.10)
	dill (0.2.5)
	docutils (0.12)
	dynd (0.7.3.dev1)
	et-xmlfile (1.0.1)
	fastcache (1.0.2)
	filelock (2.0.6)
	Flask (0.11.1)
	Flask-Cors (2.1.2)
	gevent (1.1.2)
	greenlet (0.4.10)
	h5py (2.6.0)
	HeapDict (1.0.0)
	idna (2.1)
	imagesize (0.7.1)
	ipykernel (4.5.0)
	ipython (5.1.0)
	ipython-genutils (0.1.0)
	ipywidgets (5.2.2)
	itsdangerous (0.24)
	jdcal (1.2)
	jedi (0.9.0)
	Jinja2 (2.8)
	jsonschema (2.5.1)
	jupyter (1.0.0)
	jupyter-client (4.4.0)
	jupyter-console (5.0.0)
	jupyter-core (4.2.0)
	jupyterhub (0.7.1)
	lazy-object-proxy (1.2.1)
	llvmlite (0.13.0)
	locket (0.2.0)
	lxml (3.6.4)
	MarkupSafe (0.23)
	matplotlib (1.5.3)
	mistune (0.7.3)
	mpmath (0.19)
	multipledispatch (0.4.8)
	nb-anacondacloud (1.2.0)
	nb-conda (2.0.0)
	nb-conda-kernels (2.0.0)
	nbconvert (4.2.0)
	nbformat (4.1.0)
	nbpresent (3.0.2)
	networkx (1.11)
	nltk (3.2.1)
	nose (1.3.7)
	notebook (4.3.1)
	numba (0.28.1)
	numexpr (2.6.1)
	numpy (1.11.1)
	odo (0.5.0)
	openpyxl (2.3.2)
	pamela (0.3.0)
	pandas (0.18.1)
	partd (0.3.6)
	path.py (0.0.0)
	pathlib2 (2.1.0)
	patsy (0.4.1)
	pep8 (1.7.0)
	pexpect (4.0.1)
	pickleshare (0.7.4)
	Pillow (3.3.1)
	pip (8.1.2)
	pkginfo (1.3.2)
	ply (3.9)
	prompt-toolkit (1.0.3)
	psutil (4.3.1)
	ptyprocess (0.5.1)
	py (1.4.31)
	pyasn1 (0.1.9)
	pycosat (0.6.1)
	pycparser (2.14)
	pycrypto (2.6.1)
	pycurl (7.43.0)
	pyflakes (1.3.0)
	Pygments (2.1.3)
	pylint (1.5.4)
	pyOpenSSL (16.2.0)
	pyparsing (2.1.4)
	pytest (2.9.2)
	python-dateutil (2.5.3)
	pytz (2016.6.1)
	PyYAML (3.12)
	pyzmq (15.4.0)
	QtAwesome (0.3.3)
	qtconsole (4.2.1)
	QtPy (1.1.2)
	redis (2.10.5)
	requests (2.12.4)
	rope-py3k (0.9.4.post1)
	ruamel-yaml (-VERSION)
	scikit-image (0.12.3)
	scikit-learn (0.17.1)
	scipy (0.18.1)
	setuptools (27.2.0)
	simplegeneric (0.8.1)
	singledispatch (3.4.0.3)
	six (1.10.0)
	snowballstemmer (1.2.1)
	sockjs-tornado (1.0.3)
	Sphinx (1.4.6)
	spyder (3.0.0)
	SQLAlchemy (1.0.13)
	statsmodels (0.6.1)
	sympy (1.0)
	tables (3.2.3.1)
	terminado (0.6)
	toolz (0.8.0)
	tornado (4.4.1)
	traitlets (4.3.0)
	unicodecsv (0.14.1)
	wcwidth (0.1.7)
	Werkzeug (0.11.11)
	wheel (0.29.0)
	widgetsnbextension (1.2.6)
	wrapt (1.10.6)
	xlrd (1.0.0)
	XlsxWriter (0.9.3)
	xlwt (1.1.2)

conda list:
	# packages in environment at /etc/anaconda3:
	#
	_license                  1.1                      py35_1  
	_nb_ext_conf              0.3.0                    py35_0  
	alabaster                 0.7.9                    py35_0  
	anaconda                  custom                   py35_0  
	anaconda-clean            1.0.0                    py35_0  
	anaconda-client           1.5.1                    py35_0  
	anaconda-navigator        1.3.1                    py35_0  
	argcomplete               1.0.0                    py35_1  
	astroid                   1.4.7                    py35_0  
	astropy                   1.2.1               np111py35_0  
	babel                     2.3.4                    py35_0  
	backports                 1.0                      py35_0  
	beautifulsoup4            4.5.1                    py35_0  
	bitarray                  0.8.1                    py35_0  
	blaze                     0.10.1                   py35_0  
	bokeh                     0.12.2                   py35_0  
	boto                      2.42.0                   py35_0  
	bottleneck                1.1.0               np111py35_0  
	cairo                     1.12.18                       6  
	cffi                      1.7.0                    py35_0  
	chest                     0.2.3                    py35_0  
	click                     6.6                      py35_0  
	cloudpickle               0.2.1                    py35_0  
	clyent                    1.2.2                    py35_0  
	colorama                  0.3.7                    py35_0  
	conda                     4.3.4                    py35_0  
	conda-build               2.0.2                    py35_0  
	conda-env                 2.6.0                         0  
	configobj                 5.0.6                    py35_0  
	configurable-http-proxy   1.3.1                         0    conda-forge
	contextlib2               0.5.3                    py35_0  
	cryptography              1.5                      py35_0  
	curl                      7.49.0                        1  
	cycler                    0.10.0                   py35_0  
	cython                    0.24.1                   py35_0  
	cytoolz                   0.8.0                    py35_0  
	dask                      0.11.0                   py35_0  
	datashape                 0.5.2                    py35_0  
	dbus                      1.10.10                       0  
	decorator                 4.0.10                   py35_0  
	dill                      0.2.5                    py35_0  
	docutils                  0.12                     py35_2  
	dynd-python               0.7.2                    py35_0  
	entrypoints               0.2.2                    py35_0  
	et_xmlfile                1.0.1                    py35_0  
	expat                     2.1.0                         0  
	fastcache                 1.0.2                    py35_1  
	filelock                  2.0.6                    py35_0  
	flask                     0.11.1                   py35_0  
	flask-cors                2.1.2                    py35_0  
	fontconfig                2.11.1                        6  
	freetype                  2.5.5                         1  
	get_terminal_size         1.0.0                    py35_0  
	gevent                    1.1.2                    py35_0  
	glib                      2.43.0                        1  
	greenlet                  0.4.10                   py35_0  
	gst-plugins-base          1.8.0                         0  
	gstreamer                 1.8.0                         0  
	h5py                      2.6.0               np111py35_2  
	harfbuzz                  0.9.39                        1  
	hdf5                      1.8.17                        1  
	heapdict                  1.0.0                    py35_1  
	icu                       54.1                          0  
	idna                      2.1                      py35_0  
	imagesize                 0.7.1                    py35_0  
	ipykernel                 4.5.0                    py35_0  
	ipython                   5.1.0                    py35_0  
	ipython_genutils          0.1.0                    py35_0  
	ipywidgets                5.2.2                    py35_0  
	itsdangerous              0.24                     py35_0  
	jbig                      2.1                           0  
	jdcal                     1.2                      py35_1  
	jedi                      0.9.0                    py35_1  
	jinja2                    2.8                      py35_1  
	jpeg                      8d                            2  
	jsonschema                2.5.1                    py35_0  
	jupyter                   1.0.0                    py35_3  
	jupyter_client            4.4.0                    py35_0  
	jupyter_console           5.0.0                    py35_0  
	jupyter_core              4.2.0                    py35_0  
	jupyterhub                0.7.1                    py35_0    conda-forge
	lazy-object-proxy         1.2.1                    py35_0  
	libdynd                   0.7.2                         0  
	libffi                    3.2.1                         0  
	libgcc                    4.8.5                         2  
	libgfortran               3.0.0                         1  
	libpng                    1.6.22                        0  
	libsodium                 1.0.10                        0  
	libtiff                   4.0.6                         2  
	libxcb                    1.12                          0  
	libxml2                   2.9.2                         0  
	libxslt                   1.1.28                        0  
	llvmlite                  0.13.0                   py35_0  
	locket                    0.2.0                    py35_1  
	lxml                      3.6.4                    py35_0  
	markupsafe                0.23                     py35_2  
	matplotlib                1.5.3               np111py35_0  
	mistune                   0.7.3                    py35_0  
	mkl                       11.3.3                        0  
	mkl-service               1.1.2                    py35_2  
	mpmath                    0.19                     py35_1  
	multipledispatch          0.4.8                    py35_0  
	nb_anacondacloud          1.2.0                    py35_0  
	nb_conda                  2.0.0                    py35_0  
	nb_conda_kernels          2.0.0                    py35_0  
	nbconvert                 4.2.0                    py35_0  
	nbformat                  4.1.0                    py35_0  
	nbpresent                 3.0.2                    py35_0  
	networkx                  1.11                     py35_0  
	nltk                      3.2.1                    py35_0  
	nodejs                    6.6.0                         0    conda-forge
	nose                      1.3.7                    py35_1  
	notebook                  4.3.1                    py35_0  
	numba                     0.28.1              np111py35_0  
	numexpr                   2.6.1               np111py35_0  
	numpy                     1.11.1                   py35_0  
	odo                       0.5.0                    py35_1  
	openpyxl                  2.3.2                    py35_0  
	openssl                   1.0.2j                        0  
	pamela                    0.3.0                    py35_0    conda-forge
	pandas                    0.18.1              np111py35_0  
	partd                     0.3.6                    py35_0  
	patchelf                  0.9                           0  
	path.py                   8.2.1                    py35_0  
	pathlib2                  2.1.0                    py35_0  
	patsy                     0.4.1                    py35_0  
	pep8                      1.7.0                    py35_0  
	pexpect                   4.0.1                    py35_0  
	pickleshare               0.7.4                    py35_0  
	pillow                    3.3.1                    py35_0  
	pip                       8.1.2                    py35_0  
	pixman                    0.32.6                        0  
	pkginfo                   1.3.2                    py35_0  
	ply                       3.9                      py35_0  
	prompt_toolkit            1.0.3                    py35_0  
	psutil                    4.3.1                    py35_0  
	ptyprocess                0.5.1                    py35_0  
	py                        1.4.31                   py35_0  
	pyasn1                    0.1.9                    py35_0  
	pycosat                   0.6.1                    py35_1  
	pycparser                 2.14                     py35_1  
	pycrypto                  2.6.1                    py35_4  
	pycurl                    7.43.0                   py35_0  
	pyflakes                  1.3.0                    py35_0  
	pygments                  2.1.3                    py35_0  
	pylint                    1.5.4                    py35_1  
	pyopenssl                 16.2.0                   py35_0  
	pyparsing                 2.1.4                    py35_0  
	pyqt                      5.6.0                    py35_0  
	pytables                  3.2.3.1             np111py35_0  
	pytest                    2.9.2                    py35_0  
	python                    3.5.2                         0  
	python-dateutil           2.5.3                    py35_0  
	pytz                      2016.6.1                 py35_0  
	pyyaml                    3.12                     py35_0  
	pyzmq                     15.4.0                   py35_0  
	qt                        5.6.0                         0  
	qtawesome                 0.3.3                    py35_0  
	qtconsole                 4.2.1                    py35_1  
	qtpy                      1.1.2                    py35_0  
	readline                  6.2                           2  
	redis                     3.2.0                         0  
	redis-py                  2.10.5                   py35_0  
	requests                  2.12.4                   py35_0  
	rope                      0.9.4                    py35_1  
	ruamel_yaml               0.11.14                  py35_0  
	scikit-image              0.12.3              np111py35_1  
	scikit-learn              0.17.1              np111py35_2  
	scipy                     0.18.1              np111py35_0  
	setuptools                27.2.0                   py35_0  
	simplegeneric             0.8.1                    py35_1  
	singledispatch            3.4.0.3                  py35_0  
	sip                       4.18                     py35_0  
	six                       1.10.0                   py35_0  
	snowballstemmer           1.2.1                    py35_0  
	sockjs-tornado            1.0.3                    py35_0  
	sphinx                    1.4.6                    py35_0  
	spyder                    3.0.0                    py35_0  
	sqlalchemy                1.0.13                   py35_0  
	sqlite                    3.13.0                        0  
	statsmodels               0.6.1               np111py35_1  
	sympy                     1.0                      py35_0  
	terminado                 0.6                      py35_0  
	tk                        8.5.18                        0  
	toolz                     0.8.0                    py35_0  
	tornado                   4.4.1                    py35_0  
	traitlets                 4.3.0                    py35_0  
	unicodecsv                0.14.1                   py35_0  
	wcwidth                   0.1.7                    py35_0  
	werkzeug                  0.11.11                  py35_0  
	wheel                     0.29.0                   py35_0  
	widgetsnbextension        1.2.6                    py35_0  
	wrapt                     1.10.6                   py35_0  
	xlrd                      1.0.0                    py35_0  
	xlsxwriter                0.9.3                    py35_0  
	xlwt                      1.1.2                    py35_0  
	xz                        5.2.2                         0  
	yaml                      0.1.6                         0  
	zeromq                    4.1.4                         0  
	zlib                      1.2.8                         3
```
Thanks

**Comment by willingc** [comment]
Hi @camilo-nunez,

Did you get this resolved? If so, what was the issue? It might help the next person. Thanks!

**Comment by camilo-nunez** [comment]
Hi ! Yes i resolved it. The fastest solution I found was to disable SSL in the Nginx configuration and Jupyterhub file.

This is the nginx.conf result:
```
# HTTPS server disable
server {
    listen 80;

    client_max_body_size 50M;
    server_name DOMAIN;

    error_log  PATH_TO/error.log;
    access_log  PATH_TO/access.log;


    location / {
        proxy_pass http://127.0.0.1:8027;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
    }

    location ~ /api/kernels/ {
        proxy_pass http://127.0.0.1:8027;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
```

And the jupyterhub_config.py:

```
c = get_config()

import os
pjoin = os.path.join

runtime_dir = os.path.join('PATH_TO')

# Port to public
c.JupyterHub.port = 8027
c.JupyterHub.confirm_no_ssl = True

# JupyterHub cookie secret and state db
c.JupyterHub.cookie_secret_file = pjoin(runtime_dir, 'cookie_secret')
c.JupyterHub.db_url = pjoin(runtime_dir, 'jupyterhub.sqlite')

# put the log file in /var/log
c.JupyterHub.extra_log_file = ' PATH_TO/log/jupyterhub.log'
```
