### ISSUE TITLE
Crash in singleuser.py: 'change' is a dict rather than an object

### ISSUE THREAD

**Issue by apetresc** [jupyterhub/jupyterhub#972]
**How to reproduce the issue**
I'm installing JupyterHub with the following relevant versions:

```
Python 3.5.2 (Anaconda version)
jupyter-client==4.4.0
jupyter-core==4.2.1
jupyterhub==0.7.2
notebook==4.3.1
```

And a `jupyterhub_config.py` similar to this one (just with credentials, etc, removed):
```python
c = get_config()

import os
pjoin = os.path.join

c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.GitHubOAuthenticator.oauth_callback_url = "http://localhost:8000/hub/oauth_callback"
c.GitHubOAuthenticator.client_id = '---'
c.GitHubOAuthenticator.client_secret = '---'
c.LocalAuthenticator.create_system_users = True

c.Spawner.notebook_dir = '/opt/jupyterhub/notebooks'
```
(This is all running in a Docker container, if it matters, which I don't think it does).

I then log in with a valid GitHub user.

**What you expected to happen**
My server to start up.

**What actually happens**
The spawner fails with the following error:
```
[I 2017-02-08 15:45:11.053 JupyterHub spawner:783] Spawning jupyterhub-singleuser '--user="apetresc"' '--cookie-name="jupyter-hub-token-apetresc"' '--base-url="/user/apetresc"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="12
7.0.0.1"' --port=35187 '--notebook-dir="/opt/jupyterhub/notebooks"'
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    main()
  File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 322, in main
    return SingleUserNotebookApp.launch_instance(argv)
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1136, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 875, in parse_command_line
    super(NotebookApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 512, in parse_command_line
    self.update_config(config)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 192, in update_config
    self._load_config(config)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/configurable.py", line 169, in _load_config
    warn(msg)
  File "/opt/conda/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 1085, in hold_trait_notifications
    self.notify_change(change)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 1127, in notify_change
    c(change)
  File "/opt/conda/lib/python3.5/site-packages/jupyterhub/singleuser.py", line 147, in _user_changed
    self.log.name = change.new
AttributeError: 'dict' object has no attribute 'new'
```

Indeed, when I insert debugging output right before `singleuser.py:147`, it seems that `change` is a `dict`, not an object. Simply replacing line 147 with:

```python
self.log.name = change['new']
```
fixes the crash; the server starts properly and everything seems to run normally.

Jupyter Troubleshoot output:
```
root@368f9994a5f0:/srv/jupyterhub# jupyter troubleshoot                                                                         
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/opt/conda/bin
	/opt/conda/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/opt/conda/bin
	/opt/conda/lib/python35.zip
	/opt/conda/lib/python3.5
	/opt/conda/lib/python3.5/plat-linux
	/opt/conda/lib/python3.5/lib-dynload
	/opt/conda/lib/python3.5/site-packages
	/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg

sys.executable:
	/opt/conda/bin/python

sys.version:
	3.5.2 | packaged by conda-forge | (default, Jan 11 2017, 14:44:18) 
	[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

platform.platform():
	Linux-4.9.7-1-ARCH-x86_64-with-debian-stretch-sid

which -a jupyter:
	/opt/conda/bin/jupyter
	/opt/conda/bin/jupyter

pip list:
	alembic (0.8.10)
	backports-abc (0.4)
	backports.shutil-get-terminal-size (1.0.0)
	basemap (1.1.0)
	beautifulsoup4 (4.4.1)
	boto (2.45.0)
	CampaignManager (1.9.1)
	click (6.6)
	conda (4.2.13)
	configparser (3.5.0)
	cycler (0.10.0)
	decorator (4.0.9)
	entrypoints (0.2.1)
	findspark (0.0.5)
	future (0.16.0)
	geopy (1.11.0)
	ipykernel (4.3.1)
	ipython (4.2.0)
	ipython-genutils (0.1.0)
	ipywidgets (5.1.3)
	Jinja2 (2.8)
	jsonschema (2.5.1)
	jupyter (1.0.0)
	jupyter-client (4.4.0)
	jupyter-console (5.1.0)
	jupyter-core (4.2.1)
	jupyterhub (0.7.2)
	jupyterhub-dummyauthenticator (0.1)
	Mako (1.0.6)
	MarkupSafe (0.23)
	matplotlib (2.0.0)
	mistune (0.7.2)
	nbconvert (4.2.0)
	nbformat (4.0.1)
	notebook (4.3.1)
	numpy (1.12.0)
	oauthenticator (0.4.0)
	Oddish (2.3.0.dev3)
	pamela (0.2.1)
	pandas (0.18.0)
	pexpect (4.0.1)
	pickleshare (0.7.2)
	Pillow (3.4.2)
	pip (9.0.1)
	plotly (2.0.0)
	prompt-toolkit (1.0.13)
	psycopg2 (2.6.2)
	ptyprocess (0.5.1)
	pycosat (0.6.1)
	pycrypto (2.6.1)
	Pygments (2.1.3)
	pyodbc (4.0.3)
	pyparsing (2.1.10)
	pyproj (1.9.5.1)
	pyshp (1.2.10)
	python-dateutil (2.6.0)
	python-editor (1.0.3)
	pytz (2016.10)
	PyYAML (3.12)
	pyzmq (15.2.0)
	qtconsole (4.2.1)
	requests (2.10.0)
	rkquerybuilder (0.1.6)
	ruamel-yaml (-VERSION)
	rubione (1.0.4)
	setuptools (27.2.0)
	simplegeneric (0.8.1)
	six (1.10.0)
	SQLAlchemy (1.0.12)
	terminado (0.6)
	tornado (4.3)
	tqdm (3.8.0)
	traitlets (4.2.1)
	wcwidth (0.1.7)
	wheel (0.29.0)
	widgetsnbextension (1.2.6)
	xlrd (1.0.0)
	xlwt (1.1.2)

conda list:
	# packages in environment at /opt/conda:
	#
	alembic                   0.8.10                    <pip>
	backports-abc             0.4                       <pip>
	backports.shutil-get-terminal-size 1.0.0                     <pip>
	basemap                   1.1.0                     <pip>
	beautifulsoup4            4.4.1                     <pip>
	boto                      2.45.0                    <pip>
	CampaignManager           1.9.1                     <pip>
	click                     6.6                       <pip>
	conda                     4.2.13                   py35_0    conda-forge
	conda-env                 2.6.0                         0    conda-forge
	configparser              3.5.0                     <pip>
	configurable-http-proxy   1.3.1                         0    conda-forge
	cycler                    0.10.0                   py35_0  
	cycler                    0.9.0                     <pip>
	dbus                      1.10.10                       0  
	decorator                 4.0.10                   py35_0    conda-forge
	decorator                 4.0.9                     <pip>
	entrypoints               0.2.1                     <pip>
	expat                     2.1.0                         0  
	findspark                 0.0.5                     <pip>
	fontconfig                2.12.1                        3  
	freetype                  2.5.5                         2  
	future                    0.16.0                    <pip>
	geopy                     1.11.0                    <pip>
	geos                      3.5.0                         0  
	glib                      2.50.2                        1  
	gst-plugins-base          1.8.0                         0  
	gstreamer                 1.8.0                         0  
	icu                       54.1                          0  
	ipykernel                 4.3.1                     <pip>
	ipython                   4.2.0                     <pip>
	ipython_genutils          0.1.0                    py35_0    conda-forge
	ipywidgets                5.1.3                     <pip>
	jinja2                    2.8                      py35_1    conda-forge
	jpeg                      9b                            0  
	jsonschema                2.5.1                     <pip>
	jupyter                   1.0.0                     <pip>
	jupyter-client            4.4.0                     <pip>
	jupyter-console           5.1.0                     <pip>
	jupyter-core              4.2.1                     <pip>
	jupyterhub                0.7.2                     <pip>
	jupyterhub-dummyauthenticator 0.1                       <pip>
	libffi                    3.2.1                         1  
	libgcc                    5.2.0                         0  
	libpng                    1.6.27                        0  
	libxcb                    1.12                          1  
	libxml2                   2.9.4                         0  
	Mako                      1.0.6                     <pip>
	markupsafe                0.23                     py35_1    conda-forge
	matplotlib                2.0.0                     <pip>
	mistune                   0.7.2                     <pip>
	mkl                       2017.0.1                      0  
	nbconvert                 4.2.0                     <pip>
	nbformat                  4.0.1                     <pip>
	ncurses                   5.9                          10    conda-forge
	nodejs                    6.6.0                         0    conda-forge
	notebook                  4.3.1                     <pip>
	numpy                     1.12.0                    <pip>
	numpy                     1.11.3                   py35_0  
	oauthenticator            0.4.0                     <pip>
	Oddish                    2.3.0.dev3                <pip>
	openssl                   1.0.2j                        0  
	pamela                    0.2.1                     <pip>
	pandas                    0.18.0                    <pip>
	pexpect                   4.0.1                     <pip>
	pickleshare               0.7.2                     <pip>
	Pillow                    3.4.2                     <pip>
	pip                       9.0.1                    py35_0    conda-forge
	plotly                    2.0.0                     <pip>
	prompt-toolkit            1.0.13                    <pip>
	psycopg2                  2.6.2                     <pip>
	ptyprocess                0.5.1                     <pip>
	pycosat                   0.6.1                    py35_1  
	pycrypto                  2.6.1                    py35_4  
	Pygments                  2.1.3                     <pip>
	pyodbc                    4.0.3                     <pip>
	pyparsing                 2.1.4                    py35_0  
	pyparsing                 2.1.10                    <pip>
	pyproj                    1.9.5.1                   <pip>
	pyshp                     1.2.10                    <pip>
	python                    3.5.2                         4    conda-forge
	python-dateutil           2.5.2                     <pip>
	python-dateutil           2.6.0                    py35_0  
	python-editor             1.0.3                     <pip>
	pytz                      2016.10                  py35_0  
	pytz                      2016.10                   <pip>
	PyYAML                    3.12                      <pip>
	pyzmq                     15.2.0                    <pip>
	qtconsole                 4.2.1                     <pip>
	readline                  6.2                           2  
	requests                  2.12.4                   py35_0    conda-forge
	requests                  2.10.0                    <pip>
	rkquerybuilder            0.1.6                     <pip>
	ruamel_yaml               0.11.14                  py35_0  
	rubione                   1.0.4                     <pip>
	setuptools                27.2.0                   py35_0  
	simplegeneric             0.8.1                     <pip>
	sip                       4.18                     py35_0  
	six                       1.10.0                   py35_1    conda-forge
	SQLAlchemy                1.0.12                    <pip>
	sqlalchemy                1.1.4                    py35_0    conda-forge
	sqlite                    3.13.0                        0  
	terminado                 0.6                       <pip>
	tk                        8.5.18                        0  
	tornado                   4.3                       <pip>
	tornado                   4.4.2                    py35_0    conda-forge
	tqdm                      3.8.0                     <pip>
	traitlets                 4.3.0                    py35_0    conda-forge
	traitlets                 4.2.1                     <pip>
	wcwidth                   0.1.7                     <pip>
	wheel                     0.29.0                   py35_0  
	widgetsnbextension        1.2.6                     <pip>
	xlrd                      1.0.0                     <pip>
	xlwt                      1.1.2                     <pip>
	xz                        5.2.2                         0  
	yaml                      0.1.6                         0  
	zlib                      1.2.8                         3
```

**Comment by apetresc** [comment]
It just occurred to me that this might be caused by my hard dependency on `traitlets==4.2.1`; maybe the `@observe` annotation changed its API between `4.2.1` and `4.3.0`? I am rebuilding the Docker image with `traitlets==4.3.1` and I'll see if that resolves it!

**Comment by aeksco** [comment]
I encountered this error earlier tonight - turns out my version of `juyterhub` was out of date.

Running `pip3 install --upgrade jupyterhub` resolved the problem.
