### ISSUE TITLE
Error 400, can't connect to the kernel

### ISSUE THREAD

**Issue by funnelandhose** [jupyterhub/jupyterhub#982]
Hello!

I've been checking out the other threads about this issue, but none of the answers seem to work for me...

I have apache running and it works when using http, but https with shibboleth is required in my system, which works so far.
I've tried as well nginx, but I can't use shibboleth here, but https works fine with sudospawner.

So, when using apache with shibboleth, https works fine till the point of connecting to the kernel. Websockets fail and it gives error 400, or the connection was finished before doing the handshake (depending on several solutions I've tried).

Here is the configuration for apache:

```
LoadModule mod_shib /usr/lib/apache2/modules/mod_shib2.so
NameVirtualHost *:443
<VirtualHost *:443>
    ServerAdmin admin@domain.com
    ServerName  serverName.domain.com
    DocumentRoot /var/www/
#    Alias /shibboleth-sp/logo.jpg /usr/share/shibboleth/logo.jpg

   SSLEngine On
   SSLCertificateFile "/etc/ssl/certs/hostcert.pem"
   SSLCertificateKeyFile "/etc/ssl/private/hostkey.pem"

   ProxyRequests Off
   ProxyPreserveHost On

   <Proxy *>
           Order deny,allow
           Allow from all
   </Proxy>

   SSLProtocol             all -SSLv2 -SSLv3
   SSLCipherSuite          KEY
   SSLHonorCipherOrder     on
   SSLCompression          off

   <Location /Shibboleth.sso/>
              SetHandler shib
    </Location>

<Location /secure/>
              AuthType shibboleth
              ShibRequestSetting requireSession 1
              ShibUseHeaders On
              require valid-user
 </Location>

 <Location /auth/shibboleth/callback>
              AuthType shibboleth
              ShibRequestSetting requireSession 1
              ShibUseHeaders On
              require valid-user
 </Location>

# PROXY PASS FOR JUPYTER

   <Location /hub/>
              ProxyPass  http://127.0.0.1:8000/hub/
              ProxyPassReverse  http://127.0.0.1:8000/hub/
              ProxyPassReverseCookieDomain localhost serverName.domain.com
#            Header set Origin "http://localhost:8000/"
#            RequestHeader set Origin "http://localhost/"
    </Location>
    <Location /hub/api/kernels/ >
              ProxyPass   ws://localhost:8000/hub/api/kernels/
              ProxyPassReverse  ws://localhost:8000/hub/api/kernels/
    </Location>
    <Location /hub/terminals/websocket/>
              ProxyPass        ws://localhost:8000/hub/terminals/websocket/
              ProxyPassReverse ws://localhost:8000/hub/terminals/websocket/
    </Location>

#     <LocationMatch ~  "/hub/(user/[^/]*)/(api/kernels/[^/]+/channels|terminals/websocket)(.*)">
#         ProxyPass ws://localhost:8000/hub/$1/$2$3
#         ProxyPassReverse ws://localhost:8000/
#     </LocationMatch>

</VirtualHost>
```

Any advice?

**Comment by willingc** [comment]
Hi @funnelandhose,

Sorry about the delay in responding. 

Are you using Ubuntu 14.04? [This comment](https://github.com/jupyterhub/jupyterhub/issues/219#issuecomment-242595818) as well as the thread it is in will likely help.

**Comment by funnelandhose** [comment]
Hi @willingc,

I didn't answer before because we have tried to reinstall the system.
Still doesn't work, this is the given error:

```
[I 2017-02-23 10:48:44.666 JupyterHub log:100] 200 GET /hub/login (@::ffff:XXX.XXX.XXX.XXX) 33.10ms
*** Error in `/usr/bin/python3': free(): invalid pointer: 0xf6e1cc68 ***
Aborted
user@powerPC:~$ 10:48:50.349 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
10:48:50.351 - error: [ConfigProxy] 503 POST /hub/login?next=
```

**Comment by willingc** [comment]
@funnelandhose Thanks for the update. What node version is on the server that is not working? JupyterHub needs a recent version of node and some distros ship with an old version of node. See https://github.com/jupyterhub/jupyterhub#installation for installing a recent version of node on Ubuntu/Debian.

**Comment by funnelandhose** [comment]
@willingc We had v4.8.0, but recently we tried installing 7.6 and still gave the same error.

We gonna try again ;)

Thanks for the help btw!

**Comment by willingc** [comment]
@funnelandhose Are you still having the error?

**Comment by funnelandhose** [comment]
Sorry, we have got problems on our platform and right now it isn't working so I am not able to try.
You can close this thread and I will update it later on. Thank you!

**Comment by willingc** [comment]
Thanks @funnelandhose. 👍
